eslint/eslint

.travis.yml
=> Build: add node 12

docs/user-guide/migrating-to-6.0.0.md
This updates the migration guide to add the missing items mentioned in https://github.com/eslint/eslint/pull/11515#issue-261757235.
It does not add https://github.com/eslint/eslint/issues/9505 yet because there is some debate about whether that feature will still make it into the release.
=> Docs: add missing items to migration guide

package.json
[X] Other, please explain: upgrade `eslint-plugin-node` to 9.0.0.
This PR update `eslint-plugin-node` in `devDependencies`.
- https://github.com/mysticatea/eslint-plugin-node/releases/tag/v9.0.0
It can recognize Node.js 12 stuff.
=> Chore: update eslint-plugin-node to 9.0.0

docs/developer-guide/nodejs-api.md
=> Docs: replace `var` with `const` in code examples

docs/rules/indent.md
updated the docs from `4, { ImportDeclaration: 1 }` to `4, { "ImportDeclaration": 1 }`
no
=> Docs: updated ImportDeclaration in docs-rules-indent

docs/user-guide/README.md, docs/user-guide/migrating-to-6.0.0.md
This PR fixes about the migration guide:
- Adds links to migration guides into `docs/user-guide/README.md`.
- Fixes invalid self-closing tag.
=> Docs: small fix about the migration guide

Makefile.js
Update file resolution for generating index page in documentation for new releases
Nothing
=> Chore: Fix site generation script for releases

Makefile.js
Formatters were moved to a new folder, so release script was failing.
Nothing
=> Chore: Fix formatter documentation generation

.github/FUNDING.yml
This PR adds `.github/FUNDING.yml`.
I'm not sure if this works well or not. This is a copy of https://github.com/babel/babel/pull/10016.
=> Chore: add .github/funding.yml

lib/linter/linter.js
it is no longer needed, as #11742 get merged. :)
not really.
=> Chore: remove incorrect comment

package.json
This upgrades Espree to v6.0.0.
=> Upgrade: espree@6.0.0

Makefile.js
This PR updates the bundling step to account for the changes in https://github.com/eslint/eslint.github.io/pull/588.
This updates the path the bundles are copied to in eslint.github.io after the …
=> Chore: update path for release bundles

docs/rules/array-element-newline.md, docs/rules/func-names.md, docs/rules/function-paren-newline.md, docs/rules/new-parens.md, docs/rules/no-return-await.md, docs/rules/no-self-assign.md, docs/rules/no-template-curly-in-string.md, docs/rules/no-underscore-dangle.md, docs/rules/semi-style.md, docs/rules/space-before-blocks.md, docs/rules/switch-colon-spacing.md, docs/rules/template-tag-spacing.md, docs/user-guide/configuring.md
fix some typos and optimization points
The `"never"` option of [array-element-newline](https://eslint.org/docs/rules/array-element-newline) is …
=> Docs: some typos and optimization points

docs/user-guide/getting-started.md
This PR fixes wrong Node.js version in the Getting Started page.
=> Docs: fix wrong Node.js version in getting started

package.json
[x] Other, please explain: Upgrade to new release of eslint-scope
Upgrade eslint-scope in package.json
Not really
=> Upgrade: eslint-scope@^5.0.0

lib/rules/func-names.js, tests/lib/rules/func-names.js
[x] Changes an existing rule 
Fixes #12022 
=> Update: report location of func-names (fixes #12022)

docs/user-guide/configuring.md
Update docs for `ecmaVersion: 2020` introduced in https://github.com/eslint/eslint/commit/fee6acbe13cecd4c028e681e185fc6a6d6ba9452
=> Docs: update docs for ecmaVersion 2020

package.json
[x] Other, please explain: Upgrade espree with new acorn-jsx dependency to try to resolve npm deduplication issues for users
Upgrade espree
Not really
=> Upgrade: espree@^6.1.1

tools/eslint-fuzzer.js
add es2020 support in fuzzer
no.
=> Chore: support es2020 in fuzz

docs/rules/no-irregular-whitespace.md
Fix broken Markdown syntax in `no-irregular-whitespace.md` for one of the external links.
=> Docs: Fix link in no-irregular-whitespace.md

docs/rules/no-useless-catch.md
Added a finally example under the "Do's".
Considering that there is a try/catch-throw/finally example under the "dont do", shouldn't there be an example of how to do that finally correctly?
**Is …
=> Docs: adding finally example

lib/rules/no-useless-rename.js, tests/lib/rules/no-useless-rename.js
[X] Bug fix
default
<details>
```js
sourceType: "module"
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVzZWxlc3MtcmVuYW1lOmVycm9yICovXG5cbih7IGZvbyAvL2NvbW1lbnRcbiAgICA6IGZvbyB9ID0ge30pO1xuXG5pbXBvcnQgeyBmb28gLyogY29tbWVudCAqLyBhcyBmb28gfSBmcm9tICdmb28nO1xuXG5leHBvcnQgeyBmb28gYXMgLyogY29tbWVudCAqLyBmb2 …
=> Fix: no-useless-rename autofix removes comments

README.md
Added `2019` in the README as a fully supported version.
Since the sentence is 'has full support' I guess it's too early to add 2020 as well?
=> Docs: Add supported ECMAScript version to README

docs/user-guide/configuring.md
Added `es2017` and `es2020` environments to [Configuring ESLint](https://eslint.org/docs/user-guide/configuring)
=> Docs: Add new ES environments to Configuring ESLint

lib/rules/no-extra-bind.js, tests/lib/rules/no-extra-bind.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLWJpbmQ6ZXJyb3IgKi9cblxudmFyIGEgPSBmdW5jdGlvbigpe30uYmluZCgvKiBjb21tZW50ICovIGIgLyogY29tbWVudCAqLyk7XG5cbnZhciBjID0gZnVuY3Rpb24oKXt9LiAvLyBjb21tZW50XG4gICAgYmluZChkKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZ …
=> Fix: no-extra-bind autofix removes comments

.github/workflows/ci.yml
This PR fixes our `CI.yml`. It updates `version` parameter by `node-version`.
=> Chore: update version parameter name

package.json
Bump `inquirer` package to `^7.0.0` because 6.x depends on `lodash@4.17.12` which has [Snyk Issue]( https://www.npmjs.com/advisories/1065)
Bump `inquirer` package to `^7.0.0` because 6.x depends on `lodash@4.17.12` which has [Snyk Issue]( …
=> Upgrade: bump inquirer to ^7.0.0

.github/workflows/ci.yml
[X] Other, please explain: update CI configuration
This PR updates CI configuration to add Node.js 13.x and the minimum supported version `8.10.0`.
=> Build: update CI for Node.js 13

package.json
Other
Upgraded dependency "optionator".
=> Upgrade: upgrade optionator to avoid license issue (fixes #11536)

tests/lib/rules/for-direction.js
Add test cases for `for-direction`
Added test cases for covering this branch(screenshot) in for-direction.js.
This PR increases test coverage for yield-star-spacing
* `yield-star-spacing.js`
|       | master | PR |
-- | -- | -- | 
Statements | 97.14% | 100%  |
Branches | 92.86% |  95.24% |
Functions | 100% | 100% |
Lines | 97.14% | 100% |
=> Chore: add test cases for for-direction

docs/developer-guide/working-with-rules.md
This PR fixes a link to a section in working-with-rules.md.
no
=> Fix: change a broken link in working-with-rules.md

docs/rules/brace-style.md
=> Docs: fix minor typo in brace-style.md

docs/rules/max-lines.md
=> Docs: fix dead link in max-lines rule docs

docs/rules/sort-keys.md
=> Docs: Improve sort-keys

lib/rules/radix.js, tests/lib/rules/radix.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/* eslint radix: error */
/* globals parseInt: off */
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHJhZGl4OiBlcnJvciAqL1xuLyogZ2xvYmFscyBwYXJzZUludDogb2ZmICovXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19) (v6.8.0 …
=> Fix: radix rule crash on disabled globals

lib/rules/no-irregular-whitespace.js
[x] Other, please explain: Fixing a typo in a file
disalow -> disallow
No.
=> Fix typo in no-irregular-whitespace.js

lib/rules/complexity.js
=> Chore: Fix typo in complexity.js

lib/rules/no-obj-calls.js
* **ESLint Version:** 6.8.0
* **Node Version:** 12.13.0
* **npm Version:** 6.13.7
use rollup to include eslint in the browser
bundle `eslint/lib/linter/linter.js`
**What …
=> Chore: rename shadowed global

README.md
=> Chore: Use consistent badge style

README.md
Chore
This PR adds an Open Collective badge and reorders the badges in groupings that I think make more sense.
1. Does this make sense?
1. Do we need the bounty source badge? I've never actually seen a bounty paid out, and it's adding noise to the line of current more-relevant badges.
=> Chore: add Twitter and Open Collective badge

docs/rules/arrow-parens.md
I made a minor grammar change to the docs for arrow-parens. Another way to say it could also be
> One benefit of this option
I prefer what's in the PR as it notes there are multiple benefits to the option more clearly.
Not particularly.
=> Updated arrow-parens for minor grammar issue

package.json
Updated the package of acorn that had vulnerability
Updated acorn version since there is vulnerability in 7.1.0
=> Update: acorn version

.github/workflows/ci.yml
[x] Other
Updated the version of Action `actions/checkout`. [Here](https://github.com/marketplace/actions/checkout#whats-new) are more about the changes.
=> Chore: update GitHub Actions

.gitignore
updating `.gitignore`
follow-up from here https://github.com/eslint/eslint/pull/13004#issuecomment-595959598
As eslint is not committing lock files , I added them to `gitignore` for safety as not to get committed in future if not required
If there is a plan to commit lock files, then this PR needs to be changed
=> Chore: added lock files to gitignore

package.json
Dependency upgrade
fixes https://github.com/eslint/eslint/issues/13012. This PR bumps Espree to v6.2.1 (which bumps the version of Acorn to include the security vulnerability fix).
=> Upgrade: espree@6.2.1 (fixes #13012)

docs/maintainer-guide/governance.md
In the last TSC meetings, we decided on three changes to governance:
1. Eliminate non-attending status for TSC members
2. Limit the size of the TSC to five people
3. Automatically remove a TSC member when they have missed four consecutive meetings
I've updated the governance page to reflect these changes. 
Is the …
=> Docs: Update governance

docs/rules/no-return-await.md
This article really is the clearest explanation of this rule and how to understand it.  Jake even mentions eslint and this rule in the article.
- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
=> Add further reading to rule

docs/rules/no-return-await.md
- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
Fixes #13084 
Added a line
The line I added
@nzakas
=> Docs: Fix typo

docs/rules/no-compare-neg-zero.md
I added eslint rule comments into all examples for the `disallow comparing against -0` section.
=> Docs: add eslint rule comments to code block in example

.eslintrc.js, docs/rules/callback-return.md, docs/rules/global-require.md, docs/rules/handle-callback-err.md, docs/rules/no-buffer-constructor.md, docs/rules/no-mixed-requires.md, docs/rules/no-new-require.md, docs/rules/no-path-concat.md, docs/rules/no-process-env.md, docs/rules/no-process-exit.md, docs/rules/no-restricted-modules.md, docs/rules/no-sync.md, lib/init/autoconfig.js, lib/init/source-code-utils.js, lib/rules/callback-return.js, lib/rules/global-require.js, lib/rules/handle-callback-err.js, lib/rules/no-buffer-constructor.js, lib/rules/no-mixed-requires.js, lib/rules/no-new-require.js, lib/rules/no-path-concat.js, lib/rules/no-process-env.js, lib/rules/no-process-exit.js, lib/rules/no-restricted-modules.js, lib/rules/no-sync.js, lib/shared/relative-module-resolver.js, package.json, packages/eslint-config-eslint/default.yml, tests/bin/eslint.js, tests/lib/linter/code-path-analysis/code-path.js
refs #12835 
As discussed in https://github.com/eslint/eslint/issues/12835, this PR deprecates the Node.js and CommonJS rules we have in core. These rules are generously being adopted by @mysticatea's `eslint-plugin-node` project (PR [here](https://github.com/mysticatea/eslint-plugin-node/pull/206))!
Is there anything I …
=> Update: deprecate Node.js & CommonJS rules

docs/rules/prefer-rest-params.md
Add eslint configuring rule comment in prefer-rest-params.md
=> Docs: add rule comment in prefer-rest-params doc

docs/rules/object-curly-newline.md
Added an example to the rule's documentation for imports/exports to make it more obvious that the --fix option for this rule will not format import/exports as the airbnb styleguide rule 10.8 recommends.
=> Docs: Adds import example for object-curly-newline rule (refs #12018)

tests/lib/rules/array-bracket-newline.js
[X] Other, please explain: tests
Added tests for `array-bracket-newline` which covers the nested array use cases
eg
```js
[
1, [2,3]
]
```
the diff might be a long one because of prettier formatting ,
=> Chore: tests for nested arrays (array-bracket-newline)

package.json
Dependency upgrade
This upgrades Espree to v7 (which drops support for Node v8).
=> Breaking: upgrade espree@7.0.0

package.json
Dependency upgrade
This PR bumps `eslint-release` to 2.0 so that we can take advantage of the new changelog generation behavior for major releases (see [here](https://github.com/eslint/eslint-release/commit/3d05dc5a07238b4134172a512b3929369ea011f8))
Nothing in particular!
=> Upgrade: eslint-release@2.0.0

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/QUESTION.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md, .github/ISSUE_TEMPLATE/SECURITY.md, README.md, SUPPORT.md, docs/developer-guide/contributing/changes.md, docs/developer-guide/contributing/reporting-bugs.md, docs/maintainer-guide/governance.md, messages/extend-config-missing.txt, messages/no-config-found.txt, messages/plugin-conflict.txt, messages/plugin-missing.txt, messages/whitespace-found.txt, packages/eslint-config-eslint/README.md
Replaced all links to the Gitter chat with a link to Discord (https://eslint.org/chat, to make it easy to change later)
Did I miss any references to Gitter?
=> Docs: Gitter -> Discord URL (refs #13039)

docs/developer-guide/nodejs-api.md
As noted in #13302, this link is currently broken. The author was not able to sign the CLA and so the PR was closed. Thanks @spl for bringing this to our attention!
=> Docs: fix broken link in Node.js API docs

docs/rules/no-array-constructor.md
Added an example to counter on the "incorrect" styles.
=> Docs: Document the "correct" way to build an array with values

lib/rules/accessor-pairs.js
I fixed **@ fileoverview** description correctly.
No.
=> Chore: correct fileoverview doc in accessor-pairs

.github/ISSUE_TEMPLATE/config.yml
Chore
We get a lot of issues that result in us asking users to submit an RFC. I just learned that you can include links in the issue template list and thought this would be a good idea!
=> Chore: Add breaking/core change link to issue templates

.github/FUNDING.yml
Adding Tidelift link to funding.yml
Added Tidelift link to our funding.yml file. This is required as part of the program.
Nope. :)
=> Chore: Add Tidelift to funding.yml

docs/developer-guide/working-with-rules.md
=> Docs: fixed broken hash link for working-with-rules.md

.github/FUNDING.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md
This PR removes health files that are already present in [community health files]https://github.com/eslint/.github).
Removed `CODE_OF_CONDUCT.md`, `.github/FUNDING.yml`, and updated the code of conduct info in `CONTRIBUTING.md`.
Just double-check everything looks good. :)
=> Chore: Remove duplicate health files

lib/rules/keyword-spacing.js, tests/lib/rules/keyword-spacing.js
Updated location for `unexpected` white space. 
- **Before**
- **After**
refs #12334
=> Update: keyword-spacing unexpected space loc improve (refs #12334)

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
Changed the location for `key-spacing`  when there are extra space. 
ref #12334
**Before**
**after**
None
=> Update: key-spacing loc changes for extra space (refs #12334)

docs/rules/no-unreachable-loop.md, lib/rules/index.js, lib/rules/no-unreachable-loop.js, tests/lib/rules/no-unreachable-loop.js, tools/rule-types.json
[X] New rule 
fixes #12381
```js
/*eslint no-unreachable-loop: "error"*/
while (foo) {
doSomething(foo);
foo = foo.parent;
break;
}
function verifyList(head) {
let item = head;
do {
if (verify(item)) {
return true;
} else {
return false;
}
} while (item)
}
function findSomething(arr) {
for (var i = 0; i < arr.length; i++) {
if (isSomething(arr[i])) {
return arr[i];
} else {
throw new Error("Doesn't exist.");
}
}
}
for (key in obj) {
if (key.startsWith("_")) {
break;
}
firstKey = key;
firstValue = obj[key];
break;
}
for (foo of bar) {
if (foo.id === id) {
doSomething(foo);
}
break;
}
```
new rule: `no-unreachable-loop`
**Is …
=> New: Add no-unreachable-loop rule (fixes #12381)

docs/user-guide/configuring.md
Micro wording fix in a doc.
Nope!
=> Docs: fix wording in configuring.md

karma.conf.js, package.json
[X] Other, please explain: 
Updated Puppeteer version to latest in package.json as the latest puppeteer version has support for aarch64 platform and also added architecture check to set ```CHROME_BIN``` path in karma.conf.js.
=> Upgrade: Updated puppeteer version to v4.0.0

webpack.config.js
This PR updates webpack `resolve.mainFields` to match website's [webpack config](https://github.com/eslint/website/blob/b9771e1edd74763039785591e90eb6473f7497c7/webpack.config.js#L54)
Added `"browser"`.
=> Build: update webpack resolve.mainFields to match website config

docs/developer-guide/working-with-rules.md
Came across this very old documentation at the very bottom of a very long page and noticed it hadn't been updated to use string rule levels.
Who knows what I might find if I wade into a [doc refactor](https://github.com/eslint/eslint/issues/13482#issuecomment-656888778) for the roadmap :spider:
=> Docs: Update int rule level to string

package.json
Upgrade Lodash
Upgraded our direct dependency to Lodash to 4.17.19.
There's a related NPM advisory: https://www.npmjs.com/advisories/1523
If you decide to approve this PR, you can either merge it directly, or wait for two of our dependencies to upgrade Lodash too:
* Inquirer: …
=> Upgrade:lodash@4.17.19

README.md
Updated the technology sponsors section of the README.
Any misspellings or typos?
=> Docs: Update technology sponsors in README

lib/rules/comma-dangle.js
Reverts eslint/eslint#13166. During today's TSC meeting we decided that this constitutes a breaking change and that it should be reverted until our next major release.
=> Fix: revert "Update: disallow multiple options in comma-dangle schema"

docs/user-guide/configuring.md, lib/shared/types.js, package.json
[x] Other, please explain: Dependency upgrade
refs #13568
As discussed, this PR bumps Espree to include the new ES 2021 language features. Since this environment didn't exist before, I don't think there's much danger in merging this early (even if we don't get the requisite rule changes into the release). That being said, it would be great if we …
=> Upgrade: espree@7.3.0 (refs #13568)

docs/developer-guide/development-environment.md
Updated "Step 1: Install Node.js" of the "Development Environment" documentation with the aim to make it coherent.
This pull request is created as a test to get used to the process before I can start working on "Configuration Documentation" as a part of the Google Season of Docs project.
=> Docs: Update Step 1 of Development Environment documentation

package.json
Upgraded to the latest version of `@eslint/eslintrc`.
Anything else I missed?
=> Fix: Update broken @eslint/eslintrc version (fixes #13641)

tests/lib/eslint/eslint.js
=> Chore: fix typo

docs/rules/no-await-in-loop.md
This PR adds missing eslint directive comments to correct and incorrect examples for the `no-await-in-loop` rule.
Added `/*eslint no-await-in-loop: "error"*/` to `no-await-in-loop` examples.
=> Docs: add missing eslint directive comments in no-await-in-loop

docs/developer-guide/working-with-plugins.md
=> Docs: grammatical error

package.json
Upgrades `eslint-scope` to v5.1.1
Updated `package.json` with `"eslint-scope": "^5.1.1"`.
=> Upgrade: eslint-scope@5.1.1

docs/developer-guide/nodejs-api.md
Fix anchor links to LintResult, LintMessage, EditInfo, and Formatter
No
=> Fix anchor links

package.json
Upgrades `eslint-visitor-keys` to v2.0.0
Updated `package.json` with `eslint-visitor-keys": "^2.0.0"`.
=> Upgrade: eslint-visitor-keys@2.0.0

docs/developer-guide/nodejs-api.md
This is a partial follow-up to some future work [pointed out](https://github.com/eslint/eslint/pull/13715#discussion_r495178656) by @mdjermanovic in #13715. 
@mdjermanovic, feel free to take over this branch or close this PR in favor of another that does this as part of the more complete update you had in mind.
=> Docs: Update anchor links to use existing linkrefs (refs #13715)

README.md
Code of Conduct
Fixed the reference to the code of conduct. The previous URL only redirected to the foundation's home page.
No.
=> doc: fix code of conduct reference

docs/maintainer-guide/governance.md
Easy navigation and easy reading
=> Docs: fix broken url in docs

docs/rules/no-restricted-imports.md
Mentioned that it doesn't work for dynamic imports, as currently a reader might expect that it does. Following #13594, which was closed due to lack of consensus.
No.
=> Docs: no-restricted-imports is only for static imports

bin/eslint.js
fixes #13850
Restores logging for modules such as `config-array-factory` and `cascading-config-array-factory` when `--debug` flag is set.
enabled `eslintrc:*`.
=> Fix: enable debug logs for @eslint/eslintrc (fixes #13850)

docs/developer-guide/working-with-rules.md
Just a tiny fix in one of the docs pages.
=> Docs: Fix a broken link in working-with-rules.md

lib/rules/one-var.js, tests/lib/rules/one-var.js
fixes #13834 
Added a check for export statement and adding a `export` accordingly
N/A
=> Fix: one-var autofixing for export (fixes #13834)

package.json
[X] Other, please explain: upgrading `file-entry-cache` to version 6. This drops the indirect dependency on `write`. See royriojas/flat-cache#49
=> Upgrade: file-entry-cache@6.0.0

package.json
Upgrades to include bug fixes from [`@eslint/eslintrc@0.2.2`](https://github.com/eslint/eslintrc/releases/tag/v0.2.2) and [`espree@7.3.1`](https://github.com/eslint/espree/releases/tag/v7.3.1), both of which I just released as part of #13878.
=> Upgrade: @eslint/esintrc and espree for bug fixes (refs #13878)

docs/rules/array-element-newline.md
Changed wrong rule name in docs
=> Docs: Fix wrong rule name

package.json
[x] Other, please explain: Upgrading `table` to version 6
Upgraded `table` to version 6. The only breaking change is raiding the minimum Node.js version according to the [release notes](https://github.com/gajus/table/releases/tag/v6.0.0).
There's some bugfixes and some small optimisations in there but nothing groundbreaking.
=> Upgrade: table@6.0.4

docs/user-guide/integrations.md
`eslint-loader` has been deprecated in favor of `eslint-webpack-plugin`, see https://github.com/webpack-contrib/eslint-loader
=> Docs: update build tool for webpack

tests/lib/rules/space-in-parens.js
Test a case with `space-in-parens: ["error", "always"]` that I think is neither tested nor documented:
```js
foo( )
```
Test that the following is correct with `space-in-parens: ["error", "always"]`:
```js
foo( )
```
see above
=> Chore: test `foo( )` with space-in-parens: ["error", "always"]

docs/rules/space-in-parens.md
update space-in-parens related rules: remove the obsolete reference and add newer references
references should no longer be deprecated
=> Docs: update space-in-parens related rules

package.json
[x] Other, please explain: Update Lodash to 4.17.20
This commit updates Lodash to remove a security vulnerability related to Prototype Pollution, see: https://snyk.io/vuln/SNYK-JS-LODASH-590103
=> Upgrade: Bump lodash to fix security issue

package.json
Upgrades `@eslint/eslintrc` to include changes from [`@eslint/eslintrc@0.3.0`](https://github.com/eslint/eslintrc/releases/tag/v0.3.0)
Set `"@eslint/eslintrc": "^0.3.0"` in package.json
=> Upgrade: @eslint/eslintrc to improve error message for invalid extends

docs/developer-guide/working-with-plugins.md, docs/developer-guide/working-with-rules-deprecated.md, docs/developer-guide/working-with-rules.md, docs/rules/no-undef.md, docs/rules/strict.md, docs/rules/yield-star-spacing.md, docs/user-guide/README.md, docs/user-guide/command-line-interface.md, docs/user-guide/getting-started.md
Updated links in various documents from the old `configuring.md` to the new `configuring/*` documents.
=> Docs: update configuring links

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Fixes https://github.com/eslint/eslint/issues/13899
=> Fix: extend prefer-const fixer range to whole declaration (fixes #13899)

package.json
[x] Other, please explain: Dependency upgrade
Upgrade Puppeteer to 7.1.0
This reduces the size of the `node_modules` folder for developers by ~30MB (451MB on `master` to 422MB on this branch) as part of #14098
=> Upgrade: Puppeteer to 7.1.0 (refs #14098)

package.json
[x] Other, please explain: Upgrade `@eslint/eslintrc` to [0.4.0](https://github.com/eslint/eslintrc/releases/tag/v0.4.0)
Upgrade `@eslint/eslintrc` to [0.4.0](https://github.com/eslint/eslintrc/releases/tag/v0.4.0)
=> Upgrade: @eslint/eslintrc to 0.4.0

docs/maintainer-guide/issues.md
Just wanted to clarify who can do each section of the issue triage process and a bit more detail on how to label/move things around.
Does this make sense?
=> Docs: Clarify triage process

docs/user-guide/configuring/configuration-files.md
Added missing closing backtick.
No.
=> Docs: Fix Formatting

docs/developer-guide/shareable-configs.md
Removed extraneous dash. Otherwise the point about collision is lost.
=> Docs: Remove Extraneous Dash

lib/cli-engine/lint-result-cache.js
Removes a line of JSDoc that used to belong to the description of `configHelper` parameter, which was removed in https://github.com/eslint/eslint/commit/6ae21a4bfe5a1566f787fbad798182a524b96d28
Removed the line.
=> Chore: remove leftover JSDoc from lint-result-cache

package.json
Update lodash to version 4.17.21
Updating lodash package to the latest version from 4.17.20 to 4.17.21 for security reasons to be updated to the latest version
=> Upgrade: Update lodash in package.json to V 4.17.21 

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Quotes around `repro:needed` label in the bug report template don't work well:
https://github.com/eslint/eslint/issues/new?assignees=&labels=bug%2C+"repro%3Aneeded"&template=BUG_REPORT.md&title=
New issues don't have a predefined `repro:needed` label.
Removed the quotes. The new URL will be: …
=> Docs: Fix `repro:needed` label in bug report template

docs/maintainer-guide/issues.md
Explains when to use the "Blocked" column in the triage project.
Does this make sense?
=> Docs: Update issue triage to include blocked column

docs/rules/max-lines.md
=> Docs: Update max-lines.md

package.json
Since [lint-staged v10](https://github.com/okonet/lint-staged/releases/tag/v10.0.0) modified files are automatically added to the git commit index.
No
=> Chore: remove extraneous command from lint-staged config

.github/PULL_REQUEST_TEMPLATE.md
Added comment regarding the template to be intentionally not a checkbox.
It has been several times contributors have thought that it's a mistake and have sent PR updating the template,
for example - https://github.com/eslint/eslint/pull/13759 , https://github.com/eslint/eslint/pull/12848, …
=> Docs: update pull request template

tests/fixtures/formatters/broken.js
Renamed a misspelled identifier in a test fixture.
=> Chore: rename misspelled identifier in test

.github/workflows/ci.yml
[] Other, please explain:
run test on new released node v16
=> Build: add node v16

package.json
[x] Other, please explain: Dev tooling update _(Upgrades `eslump` to the latest version to fix deprecation warnings when running `npm install` in the ESLint repo)._
I upgraded eslump to the latest version. The only breaking change in this version is dropping support for Node.js 6 and 8.
[eslump v3.0.0 release …
=> Chore: Upgrade eslump to 3.0.0

tests/bench/large.js
=> Chore: Fix typo in large.js

lib/rules/comma-spacing.js
I just replaced `indexOf -1` -> `includes` in some places
=> Chore: use includes instead of indexOf

docs/rules/no-sequences.md
FIx example. error spotted in https://github.com/eslint/eslint/pull/14578#discussion_r642151035
No
=> Docs: fix `no-sequences` example

package.json
=> Upgrade: glob-parent version in package.json

docs/maintainer-guide/issues.md
Added a description of the "Feedback Needed" column in the Triage project.
No
=> Docs: Add Feedback Needed triage description

package.json
Upgrades @eslint/eslintrc to include https://github.com/eslint/eslintrc/pull/32
Set `"@eslint/eslintrc": "^0.4.2"` in `package.json`
=> Upgrade: @eslint/eslintrc to 0.4.2

docs/developer-guide/working-with-rules.md
Fix a broken link.
1. Before - [https://eslint.org/docs/user-guide/command-line-interface#fix](https://eslint.org/docs/user-guide/command-line-interface#fix) Notice that it won't scroll to the `fix` option in this case.
2. After - [https://eslint.org/docs/user-guide/command-line-interface#-fix](https://eslint.org/docs/us …
=> Docs: fix a broken link

Makefile.js, packages/eslint-config-eslint/default.yml
so it can be applied to all eslint repos
Chore: enable reportUnusedDisableDirectives in eslint-config-eslint
no.
=> Chore: enable reportUnusedDisableDirectives in eslint-config-eslint

docs/user-guide/integrations.md
Add Mega-Linter to the list of integrations
Nope :)
=> Docs: Add Mega-Linter to the list of integrations

tests/lib/linter/linter.js
[X] Other, please explain: refactoring
Remove a duplicate line of code.
No
=> Chore: remove duplicate code

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Update `BUG_REPORT` template
No
=> Docs: update BUG_REPORT template

package.json
[x] Other, please explain: Bump the `@eslint/eslintrc` dependency to the latest release
I just released `@eslint/eslintrc@0.4.3`, and this bumps ESLint's dependency version.
No.
=> Upgrade: @eslint/eslintrc to v0.4.3

LICENSE
Updates the copyright in our license to Open JS Foundation
Nope
=> Docs: Update license copyright

.github/workflows/codeql-analysis.yml
refs: https://securitylab.github.com/tools/codeql
CodeQL: the libraries and queries that power security researchers around the world, as well as code scanning in GitHub Advanced Security (code scanning), LGTM.com, and LGTM Enterprise.
=> Build: add codeql

package.json
[X] Other, please explain: Chore
update `glob-parent` dependencies. 
Fix #14879 
No
=> Chore: update `glob-parent` (fixes #14879)

.github/workflows/ci.yml
refs https://github.com/eslint/eslint/pull/14592#pullrequestreview-711093863 and https://github.com/eslint/eslint/pull/14592#issuecomment-883787306
[actions/setup-node](https://github.com/actions/setup-node#usage) recommends to always specify Node.js version:
> The `node-version` input is optional. If not supplied, the …
=> Chore: Specify Node 14.x for Verify Files CI job

package.json
Updates dependency.
https://github.com/humanwhocodes/config-array/blob/main/CHANGELOG.md#060-2021-04-20
No.
=> Upgrade: `@humanwhocodes/config-array` to 0.6

package.json
Dependency upgrade.
https://github.com/eslint/eslint-visitor-keys/releases/tag/v3.0.0
No.
=> Upgrade: `eslint-visitor-keys` to v3

tests/lib/rules/semi.js
[x] Other, please explain: Refs https://github.com/eslint/eslint/issues/12334
add test assertions on location for `semi`
No
=> Chore: add assetions on reporting location in `semi` (refs #12334)

docs/user-guide/migrating-to-8.0.0.md
Adds the v8.0.0 migration guide.
Did I miss any breaking changes?
=> Docs: Add v8.0.0 migration guide (fixes #14856)

.gitignore
[x] Other, please explain: Chore
Add `yarn-error.log` and `.pnpm-debug.log` to `.gitignore`.  We already ignore all lock files as contributors are free to use any package manager locally so ignoring their respective log files can prevent someone from accidentally committing the file.
No
=> Chore: ignore `yarn-error.log` and `.pnpm-debug.log`

lib/rules/no-restricted-imports.js, lib/rules/no-restricted-modules.js
=> Chore: fix small typo

docs/rules/no-implicit-globals.md
=> Docs: Fix typo in no-implicit-globals.md

lib/rules/eol-last.js, tests/lib/rules/eol-last.js
Refs #12334
Add assertions on reporting location in test cases for `eol-last`.
No
=> Update: reporting loc for `never` option in `eol-last` (refs #12334)

README.md
Updated list of supported ECMAScript versions according to https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released
=> docs: readme: add 2021 and 2022 to supported ECMAScript versions

docs/developer-guide/nodejs-api.md
Added a line under the Linter header to inform users of when they might be better off using the ESLint class
No
=> Docs: Clarify Linter vs ESLint in node.js api docs (fixes #14953)

docs/user-guide/configuring/configuration-files.md
I updated the documentation in [Extending Configuration Files](https://eslint.org/docs/user-guide/configuring/configuration-files#extending-configuration-files) by adding another example overriding a rule in order to make clear to the reader how rules with options given as object are overridden.
No
=> Docs: Make clear how rule options are overridden (fixes #14962)

package.json
fixes #15017
Disallows use of reserved words as identifiers when default parser is used with `"ecmaVersion": 3`.
This is a breaking change.
Updated `espree` to v9.0.0 in package.json.
=> Breaking: Disallow reserved words in ES3 (fixes #15017)

package.json
=> Upgrade: @eslint/eslintrc@1.0.1

.github/ISSUE_TEMPLATE/bug-report.yml
Fixes our bug report form.
* Added an extra space after `Operating System:` for consistency with previous items.
* Added required blank line before a code block. Without the blank line, those would be just backtick characters followed by plain text.
* Removed the remaining `render: markdown`. With that option, the text …
=> Chore: fix bug report template

docs/developer-guide/contributing/README.md
Minor update to documentation referencing the new OpenJS Foundation CLA, and removing a reference to the decommissioned JSF CLA.
Signed-off-by: Brian Warner <brian@bdwarner.com>
=> Update CLA info

docs/user-guide/migrating-to-8.0.0.md
The example should be:
```js
meta: {
fixable: "code" // or "whitespace"
},
create(context) {
// your rule
}
};
```
instead of
```js
module.exports = function(context) {
meta: {
fixable: "code" // or "whitespace"
},
create(context) {
// your rule
}
};
```
=> Docs: fix fixable example

docs/user-guide/configuring/rules.md
Fixed a typo in the rules page on the user docs
nope
=> Docs: Remove a dot from curly link

docs/developer-guide/working-with-rules.md
=> docs: fix typo in `working-with-rules.md`

docs/rules/no-use-before-define.md
Simple change adding the "variables" attribute to the options overview.
=> docs: Add variables option to overview in no-use-before-define

package.json
Updates eslint-visitor-keys dependency to the latest v3.1.0, which includes keys for `StaticBlock`.
Set `"eslint-visitor-keys": "^3.1.0"` in package.json.
This is to allow more reliable testing of PRs that will implement class static blocks, although this shouldn't really change anything as in this case fallback traversal …
=> chore: upgrade eslint-visitor-keys for class static blocks

docs/developer-guide/contributing/pull-requests.md
Removed a colon
The colon that I removed
=> docs: Remove inconsistent colon in pull request docs

docs/developer-guide/code-path-analysis.md, lib/linter/code-path-analysis/code-path-analyzer.js, lib/linter/code-path-analysis/code-path.js, tests/fixtures/code-path-analysis/class-static-blocks--between-fields.js, tests/fixtures/code-path-analysis/class-static-blocks--between-methods.js, tests/fixtures/code-path-analysis/class-static-blocks--conditional.js, tests/fixtures/code-path-analysis/class-static-blocks--empty.js, tests/fixtures/code-path-analysis/class-static-blocks--function-inside.js, tests/fixtures/code-path-analysis/class-static-blocks--if-else.js, tests/fixtures/code-path-analysis/class-static-blocks--multiple-1.js, tests/fixtures/code-path-analysis/class-static-blocks--multiple-2.js, tests/fixtures/code-path-analysis/class-static-blocks--simple.js, tests/lib/linter/code-path-analysis/code-path.js
Refs #15016, fixes Code Path Analysis.
Class static blocks are implicit functions. Therefore, they should be treated as separate code paths. This adds `class-static-block` code paths. Each `StaticBlock` node will start a new code path, with `origin: "class-static-block"`.
Example:
```js
class Foo {
static { 
this.bar = baz;
} …
```
=> feat: code path analysis for class static blocks

templates/blogpost.md.ejs
Updated the release notes blog post format to support design changes on the blog:
1. Added a category
2. Added a teaser - this will appear in the header on the new blog design and will just be inserted at the top of the page in the current blog design
This is a companion to https://github.com/eslint/website/pull/887
No
=> docs: Update release notes blog post template

docs/user-guide/integrations.md
Updated information about JetBrains IDEs.
=> docs: update integrations.md

package.json
Updates `@eslint/eslintrc@1.0.5` so that `eslint` and `@eslint/eslintrc` have dependency requirements on `espree` synced.
=> chore: upgrade @eslint/eslintrc@1.0.5

docs/rules/sort-keys.md
=> docs: fix typo in example for `sort-keys` rule

lib/rules/max-lines-per-function.js, tests/lib/rules/max-lines-per-function.js
Fixes #15390, reverts #15140
Reverted 8f44cf505765b663e371412ab57f0f1dbbe78513.
=> fix: revert changes to reported locations in max-lines-per-function

docs/rules/class-methods-use-this.md
Just fix an incorrect heading level.
No.
=> docs: fix heading level for an option in `class-methods-use-this` rule

CONTRIBUTING.md
Update CLA info to the latest.
Fix https://github.com/eslint/eslint/issues/15367
No
=> docs: update CLA info

.github/workflows/ci.yml
[X] Other, please explain: CI
Use node v16 for testing on `macOS` and `windows`.
No
=> ci: use node v16 for `macOS` and `windows` jobs

docs/rules/array-element-newline.md
Refers https://github.com/eslint/eslint/issues/15426
Add some more examples for `array-element-newline` rule.
No
=> docs: add more examples for `array-element-newline` rule

docs/rules/for-direction.md
Added an innocent small bug the rule found in our codebase.
Feel free to close this PR if you do not agree that this example is interesting.
=> docs: Adding an incorrect code in for-direction.md

templates/blogpost.md.ejs
Updated front matter for our release blog post template to match the new blog format.
No
=> chore: Update blogpost.md.ejs

package.json
[x] Other, please explain: Upgrade Espree
I just released [Espree v9.3.0](https://github.com/eslint/espree/releases/tag/v9.3.0), and this PR upgrades to the new version.
=> chore: Upgrade espree to 9.3.0

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
Removes `master` branch from CI configs.
Updated `branches: [master, main]` to `branches: [main]` in `ci.yml` and `codeql-analysis.yml`.
In https://github.com/eslint/eslint/pull/15062 we kept `master` for the transition purposes. Now it's no longer necessary.
=> ci: remove master branch from CI configs

package.json
[x] Other, please explain: dependency upgrade
I just released [`eslint-visitor-keys@3.2.0`](https://github.com/eslint/eslint-visitor-keys/releases/tag/v3.2.0).
no
=> chore: Upgrade to eslint-visitor-keys@3.2.0

docs/rules/no-eval.md
The original http://blogs.msdn.com:80/b/ericlippert/archive/2003/11/01/53329.aspx was taken down at the end of 2015, according to archive.org.
The author has copied the article to https://ericlippert.com/2003/11/01/eval-is-evil-part-one/ and even added an update in 2020.
URL update
=> docs: [no-eval] replace dead link with working one

.github/workflows/ci.yml
We changed eslint.org website Build & Deploy configuration on Netlify to use Node 16 (https://github.com/eslint/website/issues/919).
This PR updates CI Browser Test to use Node 16, in order to match the website build.
Updated `ci.yml` file.
=> ci: use Node 16 for browser test

package.json
Updates espree dependency to ^9.3.1.
There are no changes in espree that affect ESLint, this is just for consistency.
=> chore: Upgrade to espree@9.3.1

package.json
Updates @eslint/eslintrc dependency to `^1.2.0` to include https://github.com/eslint/eslintrc/pull/71.
=> chore: upgrade @eslint/eslintrc@1.2.0

docs/rules/computed-property-spacing.md
Refs https://github.com/eslint/eslint/issues/12048, fixes `computed-property-spacing`.
Refs https://github.com/eslint/eslint/pull/14004 (closed due to age).
Added an example with computed keys in object patterns to the first section of `computed-property-spacing` docs.
Examples of correct and incorrect code have already been …
=> docs: add object pattern to first section of computed-property-spacing

docs/user-guide/configuring/configuration-files.md
it fixes the failing ci(the main branch is failing now).
=> chore: rm trailing space in docs

docs/user-guide/integrations.md
Resolves  eslint/eslint#15690
* [fast-eslint-8 on atom.io](https://atom.io/packages/fast-eslint-8)
* [fast-eslint-8 on github](https://github.com/db-developer/fast-eslint-8)
=> docs: add fast-eslint-8 to atom integrations (userguide)

docs/rules/space-infix-ops.md
Fixes #15736 
- [v] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Fix a misspelling and Typo in space-infix-ops docs
I wish revierwers check to see if it has been modified to fit the context.
=> docs: Typo in space-infix-ops docs 

package.json
Updated precommit hook.
Updated the precommit hook to use markdownlint's autofix (we already autofix JS files).
=> chore: markdownlint autofix on commit

.github/workflows/ci.yml
add node v18 in gh actions config.
no.
=> build: add node v18

docs/src/rules/no-constant-binary-expression.md, docs/src/rules/no-constant-condition.md
Follow-up to https://github.com/eslint/eslint/pull/15296. Updates `no-constant-binary-expression.md` with static frontmatter.
=> chore: add static frontmatter to no-constant-binary-expression docs

package.json
Fixes #15766 by updating `@eslint/eslintrc` dependency to include https://github.com/eslint/eslintrc/pull/77
Updated `@eslint/eslintrc` version in `package.json`.
=> fix: allow project paths to have URL-encoded characters

docs/src/rules/no-constant-binary-expression.md
Fixes 'Related Rules' heading in `no-constant-binary-expression` docs.
Fixed `Related Rules:` -> `## Related Rules`
=> docs: fix 'Related Rules' heading in no-constant-binary-expression

docs/src/maintainer-guide/governance.md, docs/src/maintainer-guide/releases.md
Removes links to the removed 2fa document.
Removed two links.
=> docs: remove links to 2fa document

.github/workflows/codeql-analysis.yml
Fixes #15816
Replaced a link that uses deprecated `git.io` with a full link, the same as in https://github.com/github/codeql-action/commit/bf4ba6945d7c065bf5ef8784b2510949aa9de685
=> chore: update link in `codeql-analysis.yml`

docs/src/developer-guide/unit-tests.md
The [Unit Tests](https://eslint.org/docs/developer-guide/unit-tests) documentation is using removed rule `no-wrap-func` in the example for running individual rule tests, so the example doesn't actually work.
Replaced `no-wrap-func.js` with `no-undef.js`.
=> docs: update example for running individual rule tests

package.json
Fixes #15456 by updating `espree` dependency to include https://github.com/eslint/espree/pull/547
=> fix: "use strict" should not trigger strict mode in ES3

package.json
Updates @eslint/eslintrc dependency to ^1.2.3 to sync dependencies.
=> chore: upgrade @eslint/eslintrc@1.2.3

docs/.eleventy.js
This adjusts the docs site base URL to `/docs` so we can proxy to it easily.
Make sure deploy preview works.
=> docs: Adjust docs site path prefix

package.json
Upgrades `@eslint/eslintrc@1.3.0` to include https://github.com/eslint/eslintrc/pull/81
=> chore: upgrade @eslint/eslintrc@1.3.0

docs/src/_includes/components/nav-version-switcher.html
In new docs, eslint version is visible in mobile view.
Before changes:
After changes:
=> docs: display eslint version in mobile view

docs/src/_includes/partials/docs-footer.html
=> docs: fix openjs link

.github/workflows/docs-deploy.yml
Workflow change
I switched the docs deploy workflow to use a Netlify build hook instead of building the website locally. I verified that this will trigger a full build and deploy to production.
Please double-check that this will work correctly. :)
=> chore: Use build hook for docs deploy

docs/src/developer-guide/nodejs-api.md, docs/src/maintainer-guide/governance.md, docs/src/pages/index.md, docs/src/user-guide/command-line-interface.md, docs/src/user-guide/index.md
Some internal links were missing a trailing slash.
Added missing trailing slash to several links.
This avoids redirections on the current site, and reduces the impact of the absence of redirections on the new site.
=> docs: add missing trailing slash to some internal links

docs/src/_includes/components/nav-version-switcher.html, docs/src/_includes/components/version-switcher.html
"Versions" fallback link for non-JS browsers is broken.
Added `| url`.
=> chore: fix versions link

docs/src/rules/object-property-newline.md
Rephrasing to have a unified wording when referring to the rule option
=> docs: unify the wording referring to optional exception

docs/src/assets/scss/syntax-highlighter.scss
Fix https://github.com/eslint/eslint/issues/16012
I noticed 
so sending the same fix as playground
- https://github.com/eslint/playground/pull/65
=> fix: remove ligatures from fonts

docs/src/assets/scss/print.scss
Before:
After:
Hide TOC from main branch in print preview.
=> fix: remove TOC from printable

.gitignore, docs/src/_data/versions.json
This updates the docs version dropdown to include several previous versions. Note that I've already set up archive.eslint.org to point to the current website so those URLs actually do work.
Did I get the version numbers correct?
=> chore: prepare versions data file

docs/src/assets/js/search.js
Fixes console errors. 
On the 404 page, the search option is not available and throws an error if we try to access so added check before accessing the elements.
=> docs: add listener only if element exists

docs/src/assets/scss/eslint-site-header.scss
On small width screens, the ESLint logo link in the upper left corner is not clickable. I can reproduce this on both mobile (chrome, android) and desktop (when I resize the browser window to a small width).
Same as https://github.com/eslint/eslint.org/pull/210
=> docs: make logo link clickable on small width screens

docs/src/assets/scss/carbon-ads.scss
Enhanced carbon ad style. Similar to https://github.com/eslint/eslint.org/pull/250/
=> docs: revamp carbon ad style

docs/src/user-guide/formatters/index.md
the main branch is currently failing now: https://github.com/eslint/eslint/runs/7158892591
=> chore: fix markdown linting error

docs/src/assets/scss/docs.scss
Added scroll behaviour to smoothly animate the scroll position.
Before:
https://user-images.githubusercontent.com/30730124/176533611-f7cfe020-b109-442b-b050-88c1a1b500c8.mov
After:
https://user-images.githubusercontent.com/30730124/176533661-50aa7ebb-eeeb-43a5-a694-12a3ba622ff4.mov
=> docs: Add scroll behaviour smooth

package.json
puppeteer < v12 has been deprecated. see https://www.npmjs.com/package/puppeteer?activeTab=versions;
we cannot upgrade to v14+, as it has dropped node.js v12: https://github.com/puppeteer/puppeteer/releases/tag/v14.0.0
no.
=> chore: upgrade puppeteer v13

package.json
[x] Other, please explain: First-party dependency upgrade
I just released [Espree 9.3.3](https://github.com/eslint/espree/releases/tag/v9.3.3), which included [one bug fix](https://github.com/eslint/espree/pull/554).
No.
=> chore: Upgrade to Espree 9.3.3

docs/src/assets/js/search.js
Optimize the search result which is not helpful at the moment.
Here's the current search result:
Show the matched text whenever possible.
Here's the updated search result:
Nope.
=> feat: optimize search result

package.json
Added `svgo` command to pre commit hook to optimize the svg files. 
Added `svgo` command to pre commit hook to optimize the svg files.
=> docs: add svgo command to pre commit hook

docs/src/rules/no-loss-of-precision.md
fixes https://github.com/eslint/eslint/issues/15767
Nope
=> docs: remove word immediately

docs/src/developer-guide/code-conventions.md, docs/src/developer-guide/package-json-conventions.md
Added a file outlining conventions for package.json to keep script names consistent across packages, per #14827
Proof read and let me know if anything is unclear. If you have any suggestions on improving or extending the standard, I'd love to hear them, but I'm a little worried this will get stuck in analysis paralysis. Once …
=> docs: package.json conventions

package.json
Updates `@eslint/eslintrc` dependency just to sync the required version of `espree`.
=> chore: upgrade @eslint/eslintrc@1.3.1

package.json
[`@eslint/eslintrc@1.3.2`](https://github.com/eslint/eslintrc/releases/tag/v1.3.2) contains https://github.com/eslint/eslintrc/pull/91, which together with this commit will fix #16277.
=> fix: Upgrade eslintrc to stop redefining plugins

docs/src/rules/logical-assignment-operators.md
Fixed `enforceIfStatements` -> `enforceForIfStatements` in `logical-assignment-operators` examples.
No
=> docs: fix logical-assignment-operators option typo

docs/README.md
Updated the README in the `docs` folder to have more detailed setup instructions.
=> docs: update `docs` README with setup details

docs/src/user-guide/integrations.md
Adding Visual Studio to the list of editor integrations.
Nope.
=> Add VS to integrations

package.json
Updates @eslint/eslintrc dependency to the latest v1.3.3 just for consistency, there are no functional changes.
=> chore: upgrade @eslint/eslintrc@1.3.3

.github/ISSUE_TEMPLATE/config.yml
Add a link to issues screen.
This adds a link to the VS Code plugin repository on our "new issue" page. I'm hoping to divert those folks over to the plugin rather than coming here first.
=> chore: Add VS Code issues link

docs/src/user-guide/configuring/configuration-files-new.md
Fixes syntax in examples in `configuration-files-new.md`.
Just added a few missing commas between properties in object literals.
=> docs: fix syntax in examples for new config files

docs/src/_includes/layouts/base.html, docs/src/_includes/layouts/doc.html, docs/src/_includes/partials/docs-header.html
This reverts commit 24950b3fb0b84ebf3aadc7bc6f81cd3b49cb1fbe.
Reverted #16403, as it breaks content widths on mobile. In particular, on mobile, you'd have to scroll left-right to read the text in paragraphs.
* Current head:
https://eslint.org/docs/head/user-guide/configuring/configuration-files
<details> …
=> Revert "docs: update header (#16403)"

docs/src/user-guide/core-concepts.md
Fixed link to `semi` rule in Core Concepts.
=> docs: core-concepts: fix link to semi rule

docs/src/user-guide/core-concepts.md
=> docs: fix link to Formatters on the Core Concepts page

docs/src/user-guide/formatters/index.md, templates/formatter-examples.md.ejs
I noticed that https://github.com/eslint/eslint/commit/823b018b1c4e3e7979c06d7628d769ed9efc926a has reverted https://github.com/eslint/eslint/pull/16399 change in `user-guide/formatters/index.md`. That's because this file is generated from a template during releases.
Restored the change from #16399 in …
=> docs: update formatters template

docs/src/developer-guide/contributing/pull-requests.md
https://github.com/eslint/eslint-github-bot/issues/179#issuecomment-1204642630
=> docs: note commit messages don't support scope

lib/eslint/eslint-helpers.js, tests/lib/eslint/flat-eslint.js
Before this change, the CLI running in flat config mode would not throw an error if at least one glob pattern matched. After this change, the CLI running in flat config mode throws an error, which matches the behavior of eslintrc mode.
Fixes #16275
Please double-check the added test and the updated test to be sure the correct …
=> fix: Ensure unmatched glob patterns throw an error

lib/shared/runtime-info.js
=> chore: use `pkg` parameter in `getNpmPackageVersion`

docs/src/assets/scss/languages.scss, docs/src/assets/scss/versions.scss
- [Preview Languages Page](https://deploy-preview-16553--docs-eslint.netlify.app/languages/)
- [Preview Versions Page](https://deploy-preview-16553--docs-eslint.netlify.app/versions/)
=> docs: improve styles for versions and languages page

docs/src/rules/no-extra-parens.md, tests/lib/rules/no-extra-parens.js
Update correct/incorrect examples for no-extra-parens. Added a corresponding test case too. 
[Playground Link](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogXCJlcnJvclwiICovXG5cbihPYmplY3QucHJvdG90eXBlLnRvU3RyaW5nLmNhbGwoKSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmN …
=> docs: update correct code examples for `no-extra-parens` rule

docs/src/developer-guide/development-environment.md
=> docs: HTTPS link to yeoman.io

docs/src/static/feed.njk, docs/src/static/sitemap.njk
Fixes `sitemap.xml` and `feed.xml` files.
After https://github.com/eslint/eslint/pull/16484, default `layout: doc` applies to these files so they're broken.
https://eslint.org/docs/latest/sitemap.xml
https://eslint.org/docs/latest/feed.xml
Added `layout: false` to avoid applying the default layout to these files.
=> docs: fix sitemap and feed

docs/src/assets/scss/components/rules.scss
Just notice this issue https://github.com/eslint/eslint/issues/16042#issuecomment-1302609180, however it's not the same problem as broken line number.
Here's the html EBNF code block would generate:
```html
<pre class="language-ebnf"><code class="language-ebnf"><span class="highlight-line"><span class="token definition rule keyword">name</span> <span class="token operator">=</span> <span class="token rule">life</span><span class="token operator">-</span><span class="token rule">cycle</span> <span class="token operator">|</span> <span class="token rule">main</span> <span class="token string">":fix"</span><span class="token special class-name">? target?</span> <span class="token rule">option</span><span class="token operator">*</span> <span class="token …
```
=> docs: fix css leaking

docs/src/rules/prefer-const.md
=> docs: fix: typo prefer-const.md

.github/ISSUE_TEMPLATE/config.yml
Discord is a server, not a channel, so updated that wording and clarified how to use it.
=> docs: Clarify Discord info in issue template config

package.json
Updates `@eslint/eslintrc` dependency to v1.4.0 to include https://github.com/eslint/eslintrc/pull/98.
=> chore: upgrade @eslint/eslintrc@1.4.0

README.md
Remove manually maintained TOC, and custom anchors (`<a name="anchor-name"></a>`)
GitHub automatically generates anchors and TOC based on the heading in the Markdown file, and I don't think we need to maintain them manually anymore.
=> docs: remove manually maintained anchors

docs/src/assets/js/search.js
Fixed search bar focusing on pressing `Esc`
Resolves #16699
=> docs: fix search bar focus on `Esc`

docs/src/user-guide/core-concepts.md
fix link to `@typescript-eslint/parser`
=> docs: fix link to npm package

README.md, tools/update-readme.js
Fix the [CI failure here](https://github.com/eslint/eslint/actions/runs/3799190990/jobs/6461488079#step:5:8) caused by a trailing whitespace.
Trim whitespace from member's name.
=> chore: fix CI failure

package.json
[x] Other, please explain: Dependency upgrade
Upgrades to the just-released [`@eslint/eslintrc@1.4.1`](https://github.com/eslint/eslintrc/releases/tag/v1.4.1), which contained docs and typings fixes.
=> chore: Upgrade @eslint/eslintrc@1.4.1

.github/workflows/add-to-triage.yml
Triage project update
This action ensures that all new issues get added to the Triage project. This replaces the old functionality that was in the GitHub bot (see https://github.com/eslint/eslint-github-bot/pull/184).
Assuming this is correct, we should copy this same file to all the public repos.
=> chore: Add new issues to triage project

docs/src/rules/class-methods-use-this.md, docs/src/rules/eqeqeq.md, docs/src/rules/func-name-matching.md, docs/src/rules/generator-star-spacing.md
use inline code for rule options name
=> docs: use inline code for rule options name

docs/src/assets/scss/components/theme-switcher.scss
When I was browsing the Chinese version https://zh-hans.eslint.org/docs/latest/, I noticed the buttons didn't seem right when there're enough spaces (reproduced under firefox/chrome/safari/edge on macOS):
Update the `flex` rule with explicit `flex-grow` and `flex-shrink` so the buttons will accommodate respectively.
=> docs: fix theme switcher button

docs/src/rules/no-constant-condition.md
I have added the common beginners’ mistake of incorrectly comparing a value against multiple other values. ESLint triggers the no-constant-condition error for code such as this, but the documentation doesn’t clearly point out what is wrong and how to fix it.
```js
if(input === "hello" || "bye"){ // Unexpected constant condition. …
```
=> docs: no-constant-condition: Add multi-comparison example

docs/.eleventy.js, docs/src/assets/scss/docs.scss, docs/src/assets/scss/tokens/themes.scss, docs/src/contribute/architecture/index.md, docs/src/extend/code-path-analysis.md
have made a new container called 'img-container' to wrap all the image diagrams and added the background and border radius property to that new container.
related to issue #16683
=> docs: add background to code-path-diagrams for dark-mode

docs/src/contribute/index.md, docs/src/contribute/report-security-vulnerability.md
Add Report a Security Vulnerability page
Added Report a Security Vulnerability page
Resolves #16764
=> docs: Report a Security Vulnerability page

docs/src/extend/custom-processors.md, docs/src/extend/index.md, docs/src/extend/plugins.md, docs/src/extend/shareable-configs.md, docs/src/integrate/nodejs-api.md
- [ x I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Add custom processors page. Split content from plugins page. 
Resolves #16761
=> docs: Custom processors page

docs/src/extend/custom-formatters.md, docs/src/extend/custom-processors.md, docs/src/extend/custom-rules.md, docs/src/extend/plugins.md, docs/src/extend/shareable-configs.md, docs/src/integrate/nodejs-api.md
Plugin docs cleanup & expansion. Also moved the custom extensions that are only part of plugins to be in the TOC under plugins.
Resolves #16811
=> docs: Plugin docs cleanup & expansion

eslint.config.js, package.json
Upgrades to yet-to-be-released `@eslint/eslintrc@2.0.0`.
Updated the dependency in `package.json`. Also updated `eslint.config.js` to pass in now-required eslint recommended config object to `FlatCompat`, otherwise linting would fail.
Must be updated before merging as it's currently using `@eslint/eslintrc` from GitHub.
=> chore: upgrade @eslint/eslintrc@2.0.0

package.json
[x] Other, please explain: Upgrade a dependency
Upgrades `@eslint/js` as part of #16891. We're [keeping these two package versions in lockstep](https://github.com/eslint/eslint/pull/16844#issuecomment-1439146284) until JS-related rules are extracted into the package, at which point they can be released independently.
=> chore: upgrade @eslint/js@8.35.0

package.json
Upgrades `espree` to include https://github.com/eslint/espree/pull/562
Updated dependency in `package.json`.
=> chore: upgrade espree@9.5.0

package.json
Upgrades `@eslint/eslintrc` just to sync dependencies.
Updated dependency in `package.json`.
=> chore: upgrade @eslint/eslintrc@2.0.1

package.json
Updated dependency in `package.json`.
=> chore: upgrade @eslint/js@8.36.0

docs/src/rules/array-callback-return.md
In the docs for `array-callback-return` rule, this PR updates `Array.prototype.toSorted` specification link.
In https://github.com/eslint/eslint/pull/16845, we used a link to the proposal because https://github.com/tc39/ecma262/pull/2997 had not yet been merged into the ECMAScript Language Specification.
Updated the link so that …
=> docs: update `Array.prototype.toSorted` specification link

.github/workflows/ci.yml
CI on Node 19 currently fails due to a confirmed bug in the recently released Node v19.8.0.
This pins Node 19 to the previous version until https://github.com/nodejs/node/issues/47096 is fixed.
`19.x` -> `19.7.0` in `.github/workflows/ci.yml`.
=> ci: pin Node 19 to 19.7.0

.github/workflows/ci.yml
Now that https://github.com/nodejs/node/issues/47096 has been fixed in the just-released Node 19.8.1, we can use the latest version again.
`19.7.0` -> `19.x` in `.github/workflows/ci.yml`.
=> ci: unpin Node 19

lib/rules/logical-assignment-operators.js
Fixed a typo in the description of the `logical-assignment-operators` rule.
=> Fix a typo in `logical-assignment-operators` rule description

docs/README.md, docs/src/_data/sites/en.yml, docs/src/_data/sites/zh-hans.yml
Currently we don't have a documentation-specific license, so it defaults to all rights reserved. As discussed in the [tsc-meeting in 2023-03-09](https://github.com/eslint/tsc-meetings/blob/main/notes/2023/2023-03-09.md#documentation-specific-license), we are going to license the docs under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).
[ ] Add …
=> feat: docs license

package.json
Upgrades to the latest `eslint-visitor-keys@3.4.0`.
=> chore: upgrade eslint-visitor-keys@3.4.0

package.json
Upgrades to the latest `espree@9.5.1`
=> chore: upgrade espree@9.5.1

package.json
Upgrades to the latest `@eslint/eslintrc@2.0.2`.
=> chore: upgrade @eslint/eslintrc@2.0.2

package.json
=> chore: upgrade @eslint/js@8.37.0

lib/rules/new-parens.js
Refactor an existing rule [ `new-parens` ] schema. It programmatically works but it shouldn't be written this way [ anyOf ]. Related [link here](https://github.com/eslint/eslint/issues/16879#issuecomment-1496689392).
I modified the current schema : 
```
schema: {
anyOf: [
{
type: "array",
items: [
{
enum: ["always", "never"]
} …
```
=> refactor: simplify new-parens rule schema

package.json
=> chore: upgrade @eslint/js@8.38.0

lib/rules/prefer-object-spread.js, tests/lib/rules/prefer-object-spread.js
Files `lib/rules/prefer-object-spread.js` and `tests/lib/rules/prefer-object-spread.js` contain references to the LICENSE file in the root directory. This is unnecessary for this project and can cause confusion, as in https://github.com/eslint/eslint/discussions/17064.
Removed those references.
Those lines were added in the …
=> chore: remove unnecessary references to the LICENSE file

package.json
=> chore: upgrade @eslint/js@8.39.0

package.json
Upgrades to the latest `eslint-visitor-keys@3.4.1`.
=> chore: upgrade eslint-visitor-keys@3.4.1

package.json
Upgrades to the latest `espree@9.5.2`
=> chore: upgrade espree@9.5.2

package.json
Upgrades to the latest `@eslint/eslintrc@2.0.3`.
=> chore: upgrade @eslint/eslintrc@2.0.3

package.json
=> chore: upgrade @eslint/js@8.40.0

docs/src/maintain/manage-issues.md
Updates the issue triage process to discuss the new Priority and Impact fields.
Does the description make sense?
=> docs: Update triage process description

package.json
=> chore: upgrade @eslint/js@8.41.0

tests/lib/rules/key-spacing.js
Two tests for the `key-spacing` rule have an incorrect number of code points in the description.
Updated the descriptions.
`[..."🌷"].length` = number of code points, `"🌷".length` = number of code units,
=> chore: update descriptions in key-spacing tests

package.json
=> chore: upgrade @eslint/js@8.42.0

docs/README.md, docs/src/_data/sites/en.yml, docs/src/_data/sites/zh-hans.yml
Reverts eslint/eslint#17010
Refs #17225 step3
=> Revert "feat: docs license"

docs/README.md, docs/src/_data/sites/en.yml, docs/src/_data/sites/zh-hans.yml
Refs #17225.
Adds references to the MIT license.
The same as https://github.com/eslint/eslint/pull/17010, just referencing the MIT license instead of the CC license.
=> docs: add references to MIT License

docs/package.json
changes package.json license ISC => MIT, Refs https://github.com/eslint/eslint/commit/788d83629a3790a7db6f52dcf0b4bddf51c6d063
n/a.
=> chore: docs package.license ISC => MIT

docs/src/rules/id-match.md
Fixed a typo and added `const` & `let` to the list of declarations.
=> docs: fix typos and missing info

docs/src/use/configure/configuration-files-new.md
I've added a note about how to enable predefined globals as discussed in https://github.com/eslint/eslint/discussions/17101#discussioncomment-5706223.
This is a redo of #17114 after #17227
=> docs: explain how to include predefined globals

docs/src/maintain/manage-issues.md
Refers #17225
Resubmit changes from https://github.com/eslint/eslint/pull/17157, https://github.com/eslint/eslint/pull/17084 and https://github.com/eslint/eslint/commit/970ef1c868235a58297682513842f1256cdfbd03
There was a typo in the original PR(https://github.com/eslint/eslint/pull/17157), I've fixed that too (`assessement` -> …
=> docs: resubmit `Manage Issues` documentation

docs/src/use/configure/configuration-files-new.md, docs/src/use/configure/configuration-files.md
Re-submits the changes from https://github.com/eslint/eslint/pull/17068
https://github.com/eslint/eslint/pull/17267/files#r1225040120
=> docs: resubmit `Configuration Files` documentation

docs/src/rules/no-new.md
https://github.com/eslint/eslint/pull/17020#issuecomment-1582660996
No
=> docs: resubmit `no-new` rule documentation

docs/src/extend/custom-rules.md
Refs https://github.com/eslint/eslint/issues/17225
Resubmitting the docs changes made in https://github.com/eslint/eslint/commit/6987dc59e46f4e345d0d6c20c1f2c6846bbd7acc
=> docs: Resubmit Fix formatting in Custom Rules docs

docs/src/extend/plugins.md, docs/src/rules/callback-return.md, docs/src/rules/global-require.md, docs/src/rules/handle-callback-err.md, docs/src/rules/no-buffer-constructor.md, docs/src/rules/no-mixed-requires.md, docs/src/rules/no-new-require.md, docs/src/rules/no-path-concat.md, docs/src/rules/no-process-env.md, docs/src/rules/no-process-exit.md, docs/src/rules/no-restricted-modules.md, docs/src/rules/no-sync.md, docs/src/use/configure/language-options.md, docs/src/use/integrations.md, docs/src/use/migrate-to-8.0.0.md, docs/src/use/migrating-to-7.0.0.md
credits: https://github.com/voxpelli
Refs:
* https://github.com/eslint/eslint/issues/17225
* https://github.com/eslint/eslint/pull/17061
=> docs: resubmit pr17061 doc changes

package.json
=> chore: upgrade @eslint/js@8.43.0

docs/src/extend/custom-rules.md
credits: https://github.com/domdomegg
Refs:
* https://github.com/eslint/eslint/issues/17225
* https://github.com/eslint/eslint/pull/17115
=> docs: resubmit pr 17115 doc changes

package.json
[X ] Other, please explain:
At the moment, Eslint uses version ^7.3.5 of semver. The problem arises when launching the command 'npm audit' due to a vulnerability in regular expression denial of service via the function 'new Range'. You can find more information about this vulnerability in the following reference: …
=> chore: upgrade semver@7.5.3

package.json
=> chore: upgrade @eslint/js@8.44.0

docs/src/rules/max-len.md
Ability to provide [`code` and `tabWidth` for `max-len` rule as positional arguments](https://github.com/eslint/eslint/blob/8c1ec65fa3d355d072f2c9c66e91aeada8e7ba14/lib/rules/max-len.js#L123-L134) is mostly undocumented, although that feature is available [since 7 years …
=> docs: `max-len` rule `code` and `tabWidth` as positional arguments

lib/eslint/flat-eslint.js
Remove unused code.
This PR removes the unreferenced `defaultIgnores` property from the private members of the `FlatESLint` class.
While debugging, I noticed that this property was never being used within flat config, as it appears to be a [leftover of `CLIEngine`](https://github.com/eslint/eslint/blob/f82e56e9acfb9562ece76441472 …
=> chore: Remove `defaultIgnores` from FlatESLint private members

docs/README.md
Fix script names mentioned in the README.
No
=> docs: update script names in README

.github/workflows/add-to-triage.yml
Update workflow
Removed PRs from the add-to-triage workflow. This isn't working for outside contributors due to the reliance on secrets. We'll try to reimplement directly on the project.
Right now this fails for any PRs from people outside the organization and causes confusion as a CI failure.
=> chore: Update add-to-triage.yml

messages/eslintrc-incompat.js
Fix https://github.com/eslint/eslint/issues/17463
Nothing
=> docs: update documentation URL in error message

package.json
=> chore: upgrade @eslint/js@8.48.0

package.json
Update dependency.
This updates the `@humanwhocodes/config-array` package with the latest version.
=> chore: Upgrade config-array

packages/eslint-config-eslint/base.js, packages/eslint-config-eslint/package.json
Switches to using eslint-plugin-jsdoc's flat config export for the recommended configuration.
Updated eslint-config-eslint.
=> chore: use eslint-plugin-jsdoc's flat config

package.json
=> chore: upgrade @eslint/js@8.49.0

Makefile.js
Browser test fails on Jenkins: `Error: Command failed: which google-chrome`.
This removes the browser test from `npm test` (the test script we run on Jenkins) so that we can do releases until we fix the problem. We're already running the browser test on CI, so I think it's okay to skip it on Jenkins, at least for now.
Commented …
=> chore: remove browser test from `npm test`

package.json
=> chore: upgrade @eslint/js@8.50.0

lib/linter/code-path-analysis/fork-context.js
Document and refactor
I added more documentation and slightly refactored the `ForkContext` class.
Please double-check that my comment explanations make sense. This was a bit dense to get through. :)
=> chore: Document and refactor ForkContext

lib/linter/code-path-analysis/code-path-state.js
Refactor
Refactored the `CodePathState` class, adding a lot of comments and renaming some fields for clarity.
The biggest change is that I introduced classes to represent the various context objects. This allowed for easier refactoring and documenting.
The comments represent my best understanding of what's going on. I wasn't …
=> chore: Refactor CodePathState

package.json
=> chore: upgrade @eslint/js@8.51.0

docs/src/rules/no-continue.md
make code works without errors
Make the example codes work
NO
=> docs: Make no-continue example code work

tests/lib/rules/no-promise-executor-return.js
Follow up to https://github.com/eslint/eslint/pull/17282#pullrequestreview-1572408147, 
Added more properties to tests for the `no-promise-executor-return` rule, including those that will be required soon when we implement [RFC 2021-stricter-rule-test-validation](https://github.com/eslint/rfcs/blob/main/designs/2021-stricter-rule …
=> test: update tests for no-promise-executor-return

package.json
=> chore: upgrade @eslint/js@8.52.0

eslint.config.js, package.json
Temporarily removes metascraper due to problems with installation on our Jenkins server.
Removed metascraper-related dev dependencies.
=> chore: remove metascraper

eslint.config.js, package.json
Adds back metascraper which was temporarily removed to finish the release.
This reverts commit ba4d4d567a82554250dd8c7933322824e6a73944.
=> Revert "chore: remove metascraper (#17707)"

docs/src/extend/plugin-migration-flat-config.md
I suppose you're not encouraging to update the ESLint documentation ("our"), but rather the documentation of the plugin "your")?
=> docs: Correct working in migrating plugin docs

Makefile.js, docs/src/_data/rules.json, docs/src/_includes/components/rule.macro.html, docs/src/pages/rules.md
Display information about deprecated rules and hide information about removed rules
close https://github.com/eslint/eslint/issues/17709
=> docs: display info about deprecated rules

docs/src/assets/scss/tokens/themes.scss
Update documentation site styles
<details><summary>Before screenshot:</summary>
</details>
<details><summary>After screenshot:</summary>
</details>
In the OS settings, enable the display of the scroll bar Always if you use a touchpad.
=> fix: Make dark scroll bar in dark theme

docs/src/rules/generator-star.md, docs/src/rules/global-strict.md, docs/src/rules/no-arrow-condition.md, docs/src/rules/no-comma-dangle.md, docs/src/rules/no-empty-class.md, docs/src/rules/no-empty-label.md, docs/src/rules/no-extra-strict.md, docs/src/rules/no-reserved-keys.md, docs/src/rules/no-space-before-semi.md, docs/src/rules/no-wrap-func.md, docs/src/rules/space-after-function-name.md, docs/src/rules/space-after-keywords.md, docs/src/rules/space-before-function-parentheses.md, docs/src/rules/space-before-keywords.md, docs/src/rules/space-in-brackets.md, docs/src/rules/space-return-throw-case.md, docs/src/rules/space-unary-word-ops.md, docs/src/rules/spaced-line-comment.md
For all of the removed rules, I added an "Important" block around the removal notice to make it more obvious.
=> docs: Make clear when rules are removed

.github/ISSUE_TEMPLATE/rule-change.yml
Fixed a grammatical mistake for rule changes issue template.
=> chore: Fixed grammar in issue_templates/rule_change

package.json
=> chore: upgrade @eslint/js@8.54.0

package.json
Upgrades `@eslint/eslintrc` to include the fix for https://github.com/eslint/eslintrc/issues/135
Marked as draft as it currently uses eslintrc from GitHub just to check if all tests will pass.
=> chore: upgrade @eslint/eslintrc@2.1.4

.github/workflows/ci.yml
Use Node.js 21.x in the CI tests instead of Node.js 21.2.0. This reverts the changes in #17809, which were done to circumvent an issue in Node.js 21.3.0 (https://github.com/nodejs/node/issues/50989). The latest Node.js version today is [21.4.0](https://github.com/nodejs/node/releases/tag/v21.4.0), and it includes a fix for said …
=> ci: unpin Node.js 21.2.0

docs/src/use/configure/migration-guide.md
added `ecmaVersion` and `sourceType` keys in `languageOptions`
Fixes #17771
=> docs: fix migration-guide example

package.json, packages/eslint-config-eslint/package.json
it removed the usage of eslint v9 deprecated apis. see https://github.com/eslint-community/eslint-plugin-n/pull/144
n/a.
=> chore: update eslint-plugin-n v16.4.0

package.json
it includes the change: https://github.com/eslint-community/eslint-plugin-eslint-plugin/commit/35e14cd7bc1fd865fa11efd955afe600ef2bbc22
n/a.
=> chore: upgrade eslint-plugin-eslint-plugin v5.2.1

package.json, packages/eslint-config-eslint/package.json
it removed the deprecated `context.getScope()` usage. (released in v48.0.0) 
refs: https://github.com/sindresorhus/eslint-plugin-unicorn/commit/ab7732e1de0f431adc7316595dd5636781d33806
n/a.
=> chore: upgrade eslint-plugin-unicorn to v49.0.0

package.json
=> chore: upgrade @eslint/js@8.56.0

lib/rules/no-sequences.js
Refactor an existing rule [ `no-sequences` ] schema. It lacked a `type` property with value `object`. Related [link here](https://github.com/eslint/eslint/issues/16879#issuecomment-1438387008).
I simply added the missing `type` property to the `no-sequences` schema object.
I modified the current schema : 
``` 
schema: [{ …
```
=> fix!: no-sequences rule schema correction

docs/src/extend/code-path-analysis.md, lib/linter/code-path-analysis/code-path.js, lib/rule-tester/flat-rule-tester.js, lib/rule-tester/rule-tester.js, tests/lib/linter/code-path-analysis/code-path-analyzer.js, tests/lib/rule-tester/flat-rule-tester.js, tests/lib/rule-tester/rule-tester.js
=> Revert "feat!: Remove CodePath#currentSegments"

docs/src/extend/shareable-configs-deprecated.md, docs/src/extend/shareable-configs.md
Switched the shareable config docs to use flat config.
Refs #13481
=> docs: Switch shareable config docs to use flat config

docs/src/_includes/components/rule-categories.macro.html, docs/src/extend/custom-rules.md, docs/src/rules/no-undef.md, docs/src/rules/strict.md, docs/src/use/command-line-interface.md, docs/src/use/configure/configuration-files-deprecated.md, docs/src/use/configure/configuration-files.md, docs/src/use/configure/ignore-deprecated.md, docs/src/use/configure/ignore.md, docs/src/use/configure/index.md, docs/src/use/configure/language-options-deprecated.md, docs/src/use/configure/language-options.md, docs/src/use/configure/migration-guide.md, docs/src/use/configure/parser-deprecated.md, docs/src/use/configure/parser.md, docs/src/use/configure/plugins-deprecated.md, docs/src/use/configure/plugins.md, docs/src/use/configure/rules-deprecated.md, docs/src/use/configure/rules.md, docs/src/use/core-concepts.md, docs/src/use/getting-started.md
Switched the default configuration documentation to refer to flat config instead of eslintrc. Primarily, this involved taking all of the content on `configuration-files-new.md` and integrating it into the multi-page configuration documentation we already had. This required moving things around and removing duplicate content. …
=> docs: Switch to flat config by default

docs/src/use/migrate-to-8.0.0.md, docs/src/use/migrate-to-9.0.0.md
Created an initial version of the "Migrate to v9.0.0" guide and added it into the navigation.
Note that I purposely did not include every change we're making in v9, as I'd like to have everyone contribute as PRs are merged to reduce the burden on any one single person.
(In future major versions, we should probably start with a …
=> docs: Migrate to v9.0.0

lib/config/flat-config-schema.js, package.json
I noticed this comment about a thing which could be removed and wanted to make sure it didn't get lost. Happy to close this if you don't want to worry about it.
~~This doesn't pass linting because `no-undef` claims that `structuredClone` is not defined, but I couldn't for the life of me figure out why. The `globals` package [has listed `structuredClone` in `node` since `13.12.0`](https://github.com/sindresorhus/globals/commit/48aeac3efdeee50db9f6d23de04b06eb00d3d6fb).~~ Fixed by upgrade to eslint-plugin-n, see below.
[ ] Changes an existing rule …
=> chore: drop structuredClone polyfill for v9

docs/src/use/migrate-to-9.0.0.md
Updates v9 migration guide with merged rule changes.
Added the following changes:
* https://github.com/eslint/eslint/commit/e563c52e35d25f726d423cc3b1dffcd80027fd99
* https://github.com/eslint/eslint/commit/e5f02c70084c4f80900c0875b08f665e1f030af2
* https://github.com/eslint/eslint/commit/0b21e1fd67d94f907d007a7a9707a3ae1cc08575
=> docs: add rule changes to v9 migration guide

docs/src/use/migrate-to-9.0.0.md
Added sections for the CLI changes to the v9 migration guide
=> docs: Add CLI updates to migrate to v9 guide

docs/src/use/migrate-to-9.0.0.md
Adds flat config default to v9 migration guide.
=> docs: add flat config default to v9 migration guide

package.json
=> chore: upgrade @eslint/js@9.0.0-alpha.0

docs/src/use/configure/combine-configs.md, docs/src/use/configure/configuration-files.md, docs/src/use/configure/ignore.md, docs/src/use/configure/migration-guide.md
Added a page on how to combine different types of configs into a config array. This applies to shareable configs and plugin configs...and everything in between.
fixes #17844
=> docs: Explain how to combine configs

docs/src/use/migrate-to-9.0.0.md
Updates v9 migration guide.
Changed the order of entries in Breaking changes for users to group CLI-related changes, changes related to inline configurations, and changes in rules.
=> docs: reorder entries in v9 migration guide

package.json, tests/bin/eslint.js, tests/fixtures/bin/eslint.config-invalid-key.js, tests/lib/config/flat-config-array.js
Upgraded `config-array` to pull in the new `object-schema` and added a test for the CLI output.
refs #17964
fixes #17960
=> fix: Ensure config keys are printed for config errors

templates/blogpost.md.ejs
Updated the release blog post template to have the correct URL for migration guides going forward. Also tweaked the language a bit.
=> docs: Update release blog post template

docs/src/extend/scope-manager-interface.md, package.json
[x] Other, please explain: deps update
Fixes https://github.com/eslint/eslint/pull/17992
Upgrades `markdownlint` & fixes related lint issues.
NO
=> chore: update `markdownlint` to `v0.33.0`

docs/src/use/configure/ignore.md, docs/src/use/configure/index.md, docs/src/use/configure/migration-guide.md
Adds more specifics to the documentation around ignoring directories and how patterns work in both the ignoring files flat config docs and the config migration docs.
fixes #17822
=> docs: Improve flat config ignores docs

lib/rules/no-implicit-coercion.js, tests/fixtures/autofix-integration/left-pad-expected-quiet.js, tests/fixtures/autofix-integration/left-pad-expected.js, tests/fixtures/autofix-integration/left-pad.js, tests/lib/rules/no-implicit-coercion.js
`no-implicit-coercion`
[ ] Generate fewer warnings
[X] Implement suggestions
[ ] A new option …
=> feat: convert unsafe autofixes to suggestions in `no-implicit-coercion`

.github/workflows/ci.yml, docs/package.json
I've updated configurations on Netlify to use Node.js 20 when building docs and org sites.
This updates docs' `package.engines` to reflect this environment so that we can use dependencies that don't support older versions of Node.js. 
Also updates Node.js version for the Browser test.
Updated `engines` in `docs/package.json`, …
=> chore: use Node.js 20 for docs sites

docs/src/use/configure/ignore.md
Fixes #17964
Added a note that ignore pattern like `build/**` also ignores directory `build/`. Also added few more examples.
=> docs: add more examples to flat config ignores docs

package.json
Updates `espree` dependency to just-released v10.0.0.
=> chore: upgrade espree@10.0.0

package.json
=> chore: upgrade @eslint/js@9.0.0-alpha.2

docs/src/rules/no-restricted-imports.md
Putted everything under a particular heading in `no-restricted-imports` rule docs page
Fixes: #18002
=> docs: update `no-restricted-imports` rule

docs/src/_data/config.json, docs/tools/validate-links.js
This PR intentionally targets the `v8.x` branch.
Refs https://github.com/eslint/eslint/issues/17966
Enables `NEXT` in version selectors on the docs site of `v8.x` branch and consequently on https://eslint.org/docs/latest when we release v8.57.0.
cherry-picked from commit 497ae919203b010d821cf1fa58c45d98ed468a92 (PR …
=> docs: show NEXT in version selectors

docs/src/contribute/governance.md
Updated governance docs to make explicit the team member responsibilities discussed internally.
Also deleted the processes for adding different team members as they are handled in our private repo with issue templates.
=> docs: Update team responsibilities

docs/src/use/command-line-interface.md
Fixes one recently added link between documents to be relative, as we have multiple docs sites.
Updated the link.
=> docs: use relative link from CLI to core concepts

.github/PULL_REQUEST_TEMPLATE.md
Changed "JS Foundation" to "OpenJS Foundation" in the pull request template.
=> docs: JS Foundation -> OpenJS Foundation in PR template

package.json
Updates `eslint-visitor-keys` dependency to just-released v4.0.0.
=> chore: upgrade eslint-visitor-keys@4.0.0

package.json
Updates `espree` dependency to just-released v10.0.1.
=> chore: upgrade espree@10.0.1

package.json
Updates `@eslint/eslintrc` dependency to just-released v3.0.1.
=> chore: upgrade @eslint/eslintrc@3.0.1

package.json
=> chore: upgrade @eslint/js@9.0.0-beta.0

docs/src/extend/custom-rules.md
Link to examples of JSON Schema led to 404. Updated to actual link. 
No.
=> docs: Update link for schema examples

docs/src/_data/sites/en.yml, docs/src/_includes/components/hero.macro.html, docs/src/_includes/layouts/doc.html, docs/src/_includes/partials/ad.html, docs/src/assets/scss/ads.scss, docs/src/assets/scss/styles.scss
This PR intentionally targets the `v8.x` branch.
Refs https://github.com/eslint/eslint/issues/17966, backports switching to Ethical Ads to v8 so that, when we sync `latest` with `v8.x`, Ethical Ads appear on `eslint.org/docs/latest/`.
cherry-picked commit f1c7e6fc8ea77fcdae4ad1f8fe1cd104a281d2e9 (PR …
=> docs: Switch to Ethical Ads

.github/workflows/pr-labeler.yml
the value of `sync-labels` in new pr-labeler's workflow file should be a boolean and ci is failing due to this.
change `sync-labels` value to `true`
<!-- markdownlint-dis
=> fix: sync-labels value of pr-labeler

package.json
Updates `eslint-release` dev dependency to recently released [v3.2.2](https://github.com/eslint/eslint-release/releases/tag/v3.2.2).
=> chore: upgrade eslint-release@3.2.2

package.json
=> chore: upgrade @eslint/js@8.57.0

docs/src/_data/config.json
Updates docs site config to show v8.57.0 as latest version in dropdowns. This config is used on `docs/head` and `docs/next`.
Updated config file.
This should be merged after we release v8.57.0 but before we release v9.0.0-beta.1.
=> docs: show v8.57.0 as latest version in dropdown

CHANGELOG.md
Adds v8.57.0 to the changelog.
Copied v8.57.0 entry from https://github.com/eslint/eslint/commit/1cd3f8c34d3f1614f16d602d660e7c9653311a47
=> build: changelog update for 8.57.0

package.json
Updates `@eslint/eslintrc` dependency to just-released v3.0.2.
=> chore: upgrade @eslint/eslintrc@3.0.2

package.json
=> chore: upgrade @eslint/js@9.0.0-beta.1

packages/js/src/configs/eslint-recommended.js
- Fix #18100 
- Remove invalid type
No
=> chore: remove invalid type in @eslint/js

tests/lib/cli-engine/cli-engine.js, tests/lib/eslint/eslint.js, tests/lib/eslint/legacy-eslint.js
=> chore: remove repetitive words

docs/src/rules/no-lone-blocks.md
set the sourceType to script because function declarations are valid in module or strict mode in `no-lone-blocks` rule.
=> docs: fix incorrect example in `no-lone-blocks`

docs/src/maintain/manage-issues.md, docs/src/maintain/review-pull-requests.md
Updated the pull request review process to better reflect what we actually do and include how to use the two new columns in the triage board.
Does this process make sense?
=> docs: Update PR review process

docs/src/use/configure/configuration-files.md
Added custom plugin example to show how shared data can be used in custom plugin.
Fixes: #16507
=> docs: update shared settings example

docs/src/_data/eslintVersions.js
Removes code that was necessary only for testing https://github.com/eslint/eslint/pull/18260.
Removed getting versions from the local file.
=> chore: remove code for testing version selectors

README.md, docs/src/use/getting-started.md
Update the get-started of the documentation with the upcoming `@eslint/create-config`.
it can be merged after https://github.com/eslint/create-config/pull/81  merged and released.
=> docs: update get-started to the new `@eslint/create-config`

docs/tools/validate-links.js
After we release v9.0.0 final, a `/docs/v8.x` link will appear on the versions page, and then our link check (`npm run lint:links` in `docs/`; we're running this check in CI) will fail.
Added `"/docs/v8.x"` to `skipPatterns`.
=> chore: ignore `/docs/v8.x` in link checker

docs/src/use/configure/migration-guide.md
Added a note in the configuration migration guide that `package.json` configs are no longer supported.
fixes #18296
Is there any place else that would make sense to mention this?
=> docs: Mention package.json config support dropped

packages/eslint-config-eslint/package.json, tests/lib/eslint/eslint.js
[ x] Other, please explain: upgrade `eslint-plugin-n` v17
https://github.com/eslint-community/eslint-plugin-n/releases/tag/v17.0.0
the eslintrc config was not updated, as it's likely to be removed soon: https://github.com/eslint/eslint/pull/18011
=> chore: eslint-plugin-n v17.0.0

package.json
eslint-plugin-eslint-plugin v6.0.0
https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v6.0.0
no.
=> chore: eslint-plugin-eslint-plugin v6.0.0

README.md, docs/src/use/getting-started.md
=> docs: update `npm init @eslint/config` generated file names

docs/src/rules/no-restricted-imports.md
added difference between the `paths` and `patterns` option of `no-restricted-imports` rule.
Fixes: #18253
=> docs: `paths` and `patterns` difference in `no-restricted-imports`

docs/src/_includes/layouts/doc.html
I added a missing accessible name to the scroll-to-top link on the website, to comply with the [WCAG 2.2 Success Criterion 2.4.4: Link Purpose (In Context)](https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context), just [like the menu button and the logo link](https://github.com/search?q=repo%3Aeslint%2Feslint+%22aria …
=> docs: Fix missing accessible name for scroll-to-top link

packages/eslint-config-eslint/package.json
In eslint-config-eslint, updates `eslint-plugin-jsdoc` and `eslint-plugin-unicorn` dependencies to the latest versions.
Updated packages/eslint-config-eslint/package.json
=> chore: upgrade jsdoc & unicorn plugins in eslint-config-eslint

docs/_examples/custom-rule-tutorial-code/enforce-foo-bar.test.js, docs/_examples/custom-rule-tutorial-code/package.json, docs/_examples/integration-tutorial-code/package.json, docs/src/extend/custom-rule-tutorial.md
fixes https://github.com/eslint/eslint/issues/18382
=> docs: update to eslint v9 in custom-rule-tutorial

.github/workflows/ci.yml
Updated CI workflow
[Node.js 22](https://github.com/nodejs/node/releases/tag/v22.0.0) has been released. This PR updates the GitHub Actions CI workflow to run tests also in Node.js 22.
=> ci: run tests in Node.js 22

lib/rules/no-case-declarations.js, tests/lib/rules/no-case-declarations.js
[x] Add ~autofix~ suggestion to a rule
Fixes https://github.com/eslint/eslint/issues/18349
Adds a suggestion fixer to `no-case-declarations` to add `{` `}` brackets around blocks.
Also adds a couple new tests to make sure switches with multiple violating cases report on the right case (consequent).
I'd considered adding logic for friendlier `{` `}` …
=> feat: `no-case-declarations` add suggestions

package.json
=> chore: upgrade @eslint/js@9.2.0

package.json
update dependencies in package.json for the upcoming release.
Updated @eslint/eslintrc and @eslint/js to the latest versions.
=> chore: update dependencies for v9.3.0 release

docs/src/rules/no-constructor-return.md, lib/rules/no-constructor-return.js, tests/lib/rules/no-constructor-return.js
closes #18486
This PR will change the `no-constructor-return` behavior slightly to allow implicit undefined return statements regardless of it's position in the constructor.
It should in theory be a breaking change but the impact is so negligible - and covered by other rules - that we might want to merge this as a …
=> fix: allow implicit undefined return in `no-constructor-return`

docs/src/library/code-blocks.md, docs/src/library/rule.md
=> docs: fix components files

docs/src/assets/js/themes.js
Fix https://github.com/eslint/eslint/issues/18189
https://github.com/eslint/eslint/assets/46647141/0a6422a9-ad82-4488-a33f-fd9c6e4ae91f
No
=> docs: update theme when when `prefers-color-scheme` changes

package.json
=> chore: upgrade to `@eslint/js@9.4.0`

package.json, wdio.conf.js
the browser testing was failing: https://github.com/eslint/eslint/actions/runs/9324019940/job/25668389482. the commit aims to fix it for now, to unblock merging PRs.
not really.
=> ci: pin @wdio/browser-runner v8.36.0

docs/src/extend/plugins.md
Added an example of reading data from `package.json` to use as `meta` in plugins.
fixes #18462
=> docs: Provide example of reading package.json for plugins meta

docs/src/use/configure/migration-guide.md
Mentions the config migrator at the top of the configuration migration guide.
=> docs: Mention config migrator

docs/src/use/configure/migration-guide.md
Added a section to the config migration docs explaining how to enable flat config in VS Code.
fixes #18549
=> docs: Add VS Code info to config migration guide

lib/rules/no-sparse-arrays.js, tests/lib/rules/no-sparse-arrays.js
=> feat: `no-sparse-arrays` report on "comma" instead of the whole array

docs/src/use/configure/migration-guide.md
Updated the configuration migration guide to indicate that the VSCode ESLint extension now supports flat config by default.
=> docs: Update vscode-eslint info

lib/linter/linter.js
Updated `linter.js` to optionally call some of the methods on language objects and `SourceCode`.
In investigating writing the JSON plugin, I discovered that a lot of the methods were not necessary for linting JSON (at least, not as a first attempt). This PR checks for the existence of various methods before calling them, …
=> refactor: Allow optional methods for languages

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
fix #18607 
Extracted report description inference to a common helper to reduce errors. 
Depends on/blocked by https://github.com/eslint/eslint/pull/18608
=> fix: `no-unused-vars` include caught errors pattern in report message

docs/src/use/getting-started.md
Add pnpm option to init eslint config, so it can be easily searched from google to [eslint install page](https://eslint.org/docs/latest/use/getting-started)
It is simple docs update for usablity.
=> docs: Update getting-started.md - add pnpm to init eslint config

docs/src/assets/js/search.js
It looks like our fact filter was incorrectly commented out. I added it back in to limit the search results to just docs.
Refs #17990
Even though this ensures we aren't searching blog posts, it still seems like the results could be refined further to avoid multiple results from the same page. We can handle that in another PR.
=> docs: Limit search to just docs

package.json
=> chore: upgrade @eslint/js@9.7.0

Makefile.js, eslint.config.js, package.json
Update ESLint config
I updated the `eslint.config.js` file to enable linting of JSON files in the repo. This includes:
- installed `@eslint/json`
- updated `eslint.config.js` so all JS-specific configs have `files` patterns specifically targeting JavaScript files
- removed separate JSON validation from `Makefile.js`
Did I …
=> build: Enable JSON linting

lib/languages/js/source-code/source-code.js, lib/linter/apply-disable-directives.js, lib/linter/linter.js, lib/linter/report-translator.js, lib/linter/rule-fixer.js, package.json, tests/lib/linter/apply-disable-directives.js, tests/lib/linter/rule-fixer.js, tests/lib/rules/utils/fix-tracker.js
- Added `SourceCode#getRange()` and `SourceCode.getLoc()`
- Refactored `Linter`, `applyDisableDirectives()` to use the new methods instead of pulling from the node/token
- Updated tests
Refs https://github.com/eslint/eslint/issues/18695
Depends on https://github.com/eslint/rewrite/pull/89
=> feat: Add and use SourceCode#getLoc/getRange

packages/js/package.json
This reverts commit d73b203210c320dd641444359cef09060ffa7459.
Revert the erroneously updated version of `@eslint/js` to v9.7.0.
=> chore: package.json revert @eslint/js version to 9.7.0

package.json
=> chore: upgrade to `@eslint/js@9.8.0`

docs/src/use/getting-started.md
Fixes #18734
Changed the documentation command on line 28 from `yarn create @eslint/config@latest` to `yarn create @eslint/config` to prevent errors caused by incorrect syntax when using the `@latest` tag.
Please kindly verify that the updated command works correctly and aligns with the intended use as described in the …
=> docs: Update yarn command for creating ESLint config

docs/src/_includes/components/nav-version-switcher.html, docs/src/_includes/components/version-switcher.html, docs/src/_includes/partials/versions-list.html
Added version support page to the version dropdown (Addresses point no.2 https://github.com/eslint/eslint.org/issues/594#issuecomment-2243119666)
=> docs: add version support page to the dropdown

docs/src/use/troubleshooting/index.md, docs/src/use/version-support.md
Add the "Version Support" link to the left nav in the docs.
Add the "Version Support" link to the left nav in the docs. (Address point no. 4 - https://github.com/eslint/eslint.org/issues/594#issuecomment-2243119666)
Thanks for the [suggestion](https://github.com/eslint/eslint.org/issues/594#issuecomment-2260614143)
=> docs: add version support page in the side navbar

docs/src/_includes/components/nav-version-switcher.html, docs/src/_includes/components/version-switcher.html, docs/src/_includes/partials/versions-list.html
similar to https://github.com/eslint/eslint/pull/18730
Added version support page to the version dropdown (Addresses point no.2 https://github.com/eslint/eslint.org/issues/594#issuecomment-2243119666)
=> docs: v8.x add version support page to the dropdown

docs/src/extend/plugin-migration-flat-config.md
It's not immediately clear from the current documentation how authors should migrate configs that extend other configs.
According to the [full documentation][1], an array is actually expected, which isn't clear in the migration documentation.
This change updates the documentation to include an array example, and links back to …
=> docs: how to author plugins with configs that extend other configs

package.json
=> chore: upgrade to `@eslint/js@9.9.0`

lib/eslint/eslint.js, tests/lib/eslint/eslint.js
fixes https://github.com/eslint/eslint/issues/18732
=> fix: add logic to handle fixTypes in the lintText()

docs/src/use/command-line-interface.md
Closes #18777 
Updates the note for different package managers to run  ESLint, in command line reference page.
=> docs: update note for package managers

docs/src/extend/custom-processors-deprecated.md, docs/src/extend/custom-processors.md, docs/src/use/configure/plugins.md, docs/src/use/core-concepts/glossary.md, docs/src/use/core-concepts/index.md
Replaced all references to `eslint-plugin-markdown` with `@eslint/markdown`.
=> docs: eslint-plugin-markdown -> @eslint/markdown

docs/src/extend/languages.md, docs/src/extend/plugin-migration-flat-config.md, docs/src/use/configure/plugins.md
Adds some basic documentation around:
1. How to use languages from plugins
2. How to create languages
Is this enough to get people started? We could probably write a small book on how to create languages, but I'm just trying to get the basics written down for now and hoping that the examples of the JSON plugin, and soon the …
=> docs: Use and define languages

docs/src/use/configure/language-options.md, docs/src/use/configure/migration-guide.md
Updated examples in the migration guide and language options pages to include multiple spread objects.
fixes #18803
=> docs: Update globals examples

README.md
Updated the README:
- Added version support information
- Removed outdated FAQs
- Fixed rule configuration example
- Updated Code of Conduct text
refs #18621
=> docs: Update README with version support and clean up content

package.json
Upgraded `@eslint/js` to keep `eslint` and `@eslint/js` in lockstep.
=> chore: upgrade to @eslint/js@9.9.1

eslint.config.js, package.json
Updates dev dependency `@eslint/json` to the latest 0.4.0.
Updated package.json. Also updated `eslint.config.js` because the plugin is now exported as `default` in CJS.
=> chore: update dependency @eslint/json to ^0.4.0

lib/linter/file-context.js, lib/linter/linter.js
Refactor
Pulled the `sharedTraversalContext` details into a new class called `FileContext`.
refs #18787
=> refactor: Extract FileContext into class

.github/workflows/ci.yml, .github/workflows/types-integration.yml, eslint.config.js, lib/types/index.d.ts, lib/types/rules/best-practices.d.ts, lib/types/rules/deprecated.d.ts, lib/types/rules/ecmascript-6.d.ts, lib/types/rules/index.d.ts, lib/types/rules/node-commonjs.d.ts, lib/types/rules/possible-errors.d.ts, lib/types/rules/strict-mode.d.ts, lib/types/rules/stylistic-issues.d.ts, lib/types/rules/variables.d.ts, lib/types/use-at-your-own-risk.d.ts, package.json, tests/lib/types/tsconfig.json, tests/lib/types/types.test.ts
Added the type definitions from `@types/eslint` to the project:
- Added all type definitions in `lib/types`
- Added tests in `tests/lib/types`
- Added new `test:types` script to run type checking tests
- Added `npm run test:types` to CI to be run on each PR
- Added `types` entries to `package.json`
For simplicity, I did not …
=> feat: Add types

package.json
=> chore: upgrade to @eslint/js@9.10.0

.github/ISSUE_TEMPLATE/change.yml
Issue template update.
Added a note asking people not to submit a pull request until after the issue has been accepted. We've been getting a bunch of random PRs based off of issues that weren't accepted and I'm hoping this will help cut down on the noise.
=> chore: Update change.yml

.github/workflows/ci.yml, docs/src/use/configure/configuration-files-new.md, lib/eslint/flat-eslint.js, package.json, tests/lib/eslint/flat-eslint.js
Fixes https://github.com/eslint/eslint/issues/18493 on `v8.x-dev` branch.
Ported https://github.com/eslint/eslint/commit/f6534d14033e04f6c7c88a1f0c44a8077148ec6b to `v8.x-dev`.
=> fix: skip processor code blocks that match only universal patterns

lib/languages/js/source-code/source-code.js, package.json
Updates `SourceCode` to use `Directive` class from `@eslint/plugin-kit` v.0.2.0.
Updated source-code.
=> refactor: use `Directive` class from `@eslint/plugin-kit`

lib/eslint/eslint-helpers.js, tests/lib/eslint/flat-eslint.js
Fixes https://github.com/eslint/eslint/issues/18250 on `v8.x-dev` branch.
Ported https://github.com/eslint/eslint/commit/594eb0e5c2b14a418d686c33d2d40fb439888b70 to `v8.x-dev` branch.
=> fix: do not crash on error in `fs.walk` filter

.github/workflows/ci.yml, lib/config/flat-config-array.js, package.json, tests/fixtures/eslint.config-with-ignores3.js, tests/lib/eslint/flat-eslint.js
Fixes https://github.com/eslint/eslint/issues/18723 and https://github.com/eslint/eslint/issues/18261 on `v8.x-dev` branch.
Bumped `@humanwhocodes/config-array` to v0.12.3, and applyed changes from https://github.com/eslint/eslint/commit/09675e153169d4d0f4a85a95007dcd17d34d70c7.
=> fix: allow `name` in global ignores, fix `--no-ignore` for non-global

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/change.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/new-rule.yml, .github/ISSUE_TEMPLATE/new-syntax.yml, .github/ISSUE_TEMPLATE/rule-change.yml
Update issue templates
Included the note to not open a PR until the issue has been accepted on all issue templates.
=> chore: Add PR note to all templates

lib/config/flat-config-array.js, package.json, tests/lib/config/flat-config-array.js
Fixes https://github.com/eslint/eslint/issues/18259 on `v8.x-dev` branch.
Ported https://github.com/eslint/eslint/commit/03068f13c0e3e6b34b8ca63628cfc79dd256feac to `v8.x-dev` branch.
=> fix: Provide helpful error message for nullish configs

lib/config/flat-config-helpers.js
[x] Other, please explain: Minor refactoring
This change makes the function more readable by removing unnecessary "&&" symbols
=> refactor: use optional chaining when validating config rules

package.json
On `v8.x-dev` branch, pins `vite-plugin-commonjs` to 0.10.1 in order to fix the browser test.
=> chore: pin vite-plugin-commonjs@0.10.1

lib/rules/id-length.js, tests/lib/rules/id-length.js
Right now `id-length` rule is not reporting the name specified to import specifier, made the rule to limit the name given to `ImportSpecifier`.
```js
/*eslint id-length: ["error", { min: 4 }]*/
import { x as foo } from 'module'; // foo will be reported.
```
```js
/*eslint id-length: ["error", { max: 5 }]*/
import { x as …
```
=> feat: limit the name given to `ImportSpecifier` in `id-length`

package.json
=> chore: upgrade @eslint/js@8.57.1

docs/src/rules/no-irregular-whitespace.md
I added unicode abbreviations in no-irregular-whitespace rule documentation. This is usefull because these abbreviations often appear in IDEs instead of unicode values/code for these invisible characters.
Having a nice day
=> docs: add unicode abbreviations in no-irregular-whitespace rule

eslint.config.js, lib/types/universal.d.ts, lib/universal.js, package.json, tests/lib/types/types.test.ts, tests/lib/universal.js
fixes https://github.com/eslint/eslint/issues/18715
- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
fixes https://github.com/eslint/eslint/issues/18715
* No docs updates - this is not an officially supported api.
* need to add typings?
=> feat: add "eslint/universal" to export `Linter`

package.json
=> chore: upgrade @eslint/js@9.11.0

docs/src/use/configure/configuration-files.md
=> docs: replace deprecated `Linter.FlatConfig` type with `Linter.Config`

package.json
=> chore: upgrade @eslint/js@9.11.1

package.json
Recently released @wdio/browser-runner v9.1.0 added peer dependency to mocha@10.
This breaks `npm install` in this project:
```
Run npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: eslint@9.11.1
npm error Found: …
```
=> chore: update dependency mocha to ^10.7.3

.github/workflows/types-integration.yml, lib/unsupported-api.js, package.json
=> fix: Issues with type definitions

docs/src/extend/languages.md
Added mention of `@eslint/plugin-kit` to the language plugins docs.
=> docs: Mention plugin-kit in language docs

docs/src/extend/code-path-analysis.md, docs/src/extend/custom-rule-tutorial.md, docs/src/extend/custom-rules.md
Mentioned code explorer in various spots where it may be helpful to the reader.
=> docs: Mention code explorer

eslint.config.js, package.json
Enables linting of JSON5 files (we currently have only one: `.github/renovate.json5`) and upgrades `@eslint/json` to the latest v0.5.0.
Update eslint config file and package.json.
=> chore: Enable JSON5 linting

package.json
=> chore: upgrade to `@eslint/js@9.12.0`

package.json
~Refs https://github.com/eslint/eslint/issues/18990, temporarily pins knip to 5.30.6 until https://github.com/eslint/eslint/issues/18990 is resolved.~
Fixes https://github.com/eslint/eslint/issues/18990: updates knip dependency to skip v5.31.0.
=> ci: upgrade knip@5.32.0

tests/lib/eslint/eslint.js
Fix unit tests
This PR fixes several unit tests in tests/lib/eslint/eslint.js.
=> test: fix `ESLint` tests

lib/cli.js
Fixes #19020
Updates the eslintrc warning message as per https://github.com/eslint/eslint/issues/19020#issuecomment-2415965781.
=> feat: Improve eslintrc warning message

bin/eslint.js, eslint.config.js, packages/eslint-config-eslint/package.json
it was introduced in node.js v22.8.0
https://nodejs.org/en/blog/release/v22.8.0#new-js-api-for-compile-cache
fixes https://github.com/eslint/eslint/issues/18968
tested on
* ESLint: v9.12.0
* Node version: v22.9.0
* Operating System: darwin 24.1.0
before the change: 
```bash
Loading:
Load performance Run #1:  181.045881ms
Load …
```
=> perf: using Node.js compile cache

lib/types/rules/best-practices.d.ts
[x] Other, please explain: Types
Updated types. Follow up https://github.com/eslint/eslint/pull/18896
In future PRs, let's make sure the types are updated if the rule schema changes.
=> fix: update the `complexity` rule type

package.json
Upgraded `@humanfs/node` to the latest version, which is able to recover from deleted directories during `walk()`.
fixes #18955
=> fix: Don't crash when directory is deleted during traversal.

tests/lib/rules/no-invalid-regexp.js
Refs https://github.com/eslint/eslint/issues/19073. Adds several `no-invalid-regexp` tests with RegExp Modifiers.
Added tests.
The `@eslint-community/regexpp` dependency has already been updated in https://github.com/eslint/eslint/pull/19065.
=> test: add `no-invalid-regexp` tests with RegExp Modifiers

docs/src/extend/custom-rules.md
Fix https://github.com/eslint/eslint/pull/18970
=> docs: update `context.languageOptions.parser` description

.github/workflows/ci.yml, eslint.config.js, knip.jsonc, packages/js/package.json, packages/js/tests/types/tsconfig.json, packages/js/tests/types/types.test.ts, packages/js/types/index.d.ts
[x] Other, please explain: Add types
Fix https://github.com/eslint/eslint/issues/18998
I have defined `eslint` as a dependency because of it's usage in types similar to https://github.com/eslint/eslint/pull/18938
=> feat: add types for the `@eslint/js` package

lib/eslint/eslint.js, package.json
Updated `@humanwhocodes/retry` and set concurrency to 100.
fixes #18977
I didn't add any new tests for this because I couldn't come up with one that failed without it. Functionally, this should result in no difference to the end user and assuming our existing tests pass, I think we're okay.
=> fix: enable retry concurrency limit for readFile()

package.json
=> chore: upgrade @eslint/js@9.14.0

docs/src/use/command-line-interface.md
Switch to use a flat config file as the example for `-c` flag.
fixes #18921
=> docs: Change CLI -c to use flat config

packages/js/README.md, packages/js/src/index.js, packages/js/tests/types/types.test.ts, packages/js/types/index.d.ts
add something to `@eslint/js`
closes #19091 
This PR adds a `meta` object to the `@eslint/js` plugin. I also updated a code example to include names for config objects. The lack of `name` properties was apparently a source of confusion in #19091.
Plugin `meta` and config `name` properties are optional but recommended:
* …
=> feat: add `meta` object to `@eslint/js` plugin

.github/workflows/annotate_pr.yaml, .github/workflows/ci.yml
Update CI worflows
Unpinned [`trunk-io/trunk-action`](https://github.com/trunk-io/trunk-action) to use the latest version. [Release v1.1.19](https://github.com/trunk-io/trunk-action/releases) contains a fix for a problem introduced in v1.1.18(see #19065).
=> ci: unpin `trunk-io/trunk-action`

lib/rules/curly.js, lib/rules/no-lonely-if.js, lib/rules/utils/ast-utils.js, tests/lib/rules/no-lonely-if.js
Fixes #19033
Extract some shared logic from the `curly` rule that also applies here.
=> fix: unsafe report for `no-lonely-if`

docs/src/_includes/components/search.html
[x] Other, please explain: referrer addition for algolia
- exact copy of https://github.com/eslint/eslint.org/pull/660
=> chore: update algolia referrer

package.json
Addressing Regular expression denial of service bug in dependency. While it might not be critical for ESLint usage it pops up in certain internal tooling that register vulnerabilities in packages
Bump `cross-spawn` version to 7.0.5
=> chore: bump cross-spawn

package.json
Updates `@eslint/plugin-kit` dependency to v0.9.0.
=> chore: upgrade @eslint/core@0.9.0

package.json
=> chore: upgrade @eslint/js@9.15.0

package.json
Updated `@eslint/json` dev dependency to the latest v0.8.0.
=> chore: update dependency @eslint/json to ^0.8.0

docs/src/use/configure/migration-guide.md
Hello, I've fixed typos in `migration-guide.md`.
First, I removed unnecessary blank spaces.
Second, I changed `ESlintrc` to `Eslintrc` for consistency. The above paragraph used `Eslintrc`, while the one below used `ESlintrc`. I made them consistent.
Nope!
=> docs: fix typos in `migration-guide.md`

package.json
=> chore: upgrade to `@eslint/js@9.16.0`

package.json
=> chore: Upgrade cross-spawn to 7.0.6

docs/src/rules/prefer-spread.md
Hello, I've added a missing `<h2>` tag (represented as `##`) to `prefer-spread.md`.
While `Known Limitations` is represented as an `<h2>` tag throughout eslint.org, this instance was not marked with `##`. So, I added it.
=> docs: add missing header to `prefer-spread`

.github/workflows/ci.yml, .github/workflows/types-integration.yml, eslint.config.js, knip.jsonc, packages/eslint-config-eslint/base.js, packages/eslint-config-eslint/cjs.js, packages/eslint-config-eslint/formatting.js, packages/eslint-config-eslint/index.js, packages/eslint-config-eslint/nodejs.js, packages/eslint-config-eslint/package.json, packages/eslint-config-eslint/tests/types/types.test-d.cts, packages/eslint-config-eslint/tests/types/types.test-d.mts, packages/eslint-config-eslint/tsconfig.json, packages/eslint-config-eslint/types/base.d.ts, packages/eslint-config-eslint/types/cjs.d.ts, packages/eslint-config-eslint/types/formatting.d.ts, packages/eslint-config-eslint/types/index.d.ts, packages/eslint-config-eslint/types/nodejs.d.ts
=> chore: add type definitions for the `eslint-config-eslint` package

docs/src/rules/no-await-in-loop.md
fixes #18918 (see also https://github.com/eslint/eslint/pull/18942)
Apologies for the delay in getting around to this! I've taken some liberties in modifying existing content as well to try to make it more cohesive as a whole. Please let me know if I've overstepped anywhere! It's tricky to be correct but not too verbose 🙃 …
=> docs: [no-await-in-loop] expand on benefits and inapplicability

docs/src/rules/yoda.md
Hello,
I've updated `yoda` to `Yoda` in `yoda.md` for consistency.
While 'Yoda' is consistently used throughout the documentation, it was missing capitalization. So I corrected it.
=> docs: update `yoda` to `Yoda` in `yoda.md` for consistency

package.json
=> chore: upgrade to `@eslint/js@9.17.0`

docs/src/extend/custom-parsers.md, docs/src/extend/ways-to-extend.md
Updated the Custom Parsers documentation to reflect usage in flat config.
=> docs: update custom parser docs

docs/src/rules/no-global-assign.md, docs/src/rules/no-implicit-globals.md, docs/src/rules/no-native-reassign.md, docs/src/rules/no-restricted-globals.md, docs/src/rules/no-unused-vars.md, docs/src/rules/strict.md, docs/src/use/configure/index.md, docs/src/use/core-concepts/index.md
Removed outdated and no longer relevant information about environments.
=> docs: remove outdated info about environments

docs/src/_data/links.json, docs/src/_data/navigation.json, docs/src/_data/sites/en.yml, docs/src/_data/sites/zh-hans.yml
added navigation link for `Code Explorer` in navbar.
Related issue https://github.com/eslint/eslint.org/issues/676
Related PR https://github.com/eslint/eslint.org/pull/682
=> docs: add navigation link for `code explorer`

docs/src/extend/custom-rules.md
Added warning about extending core rules to custom rules page.
fixes #19169
=> docs: Add warning about extending core rules

docs/src/rules/no-dupe-class-members.md, docs/src/rules/no-dupe-keys.md, docs/src/rules/no-duplicate-case.md, docs/src/rules/no-else-return.md, docs/src/rules/no-empty-character-class.md, docs/src/rules/no-empty-pattern.md
Replaced `var` with `const` in following rules:
`no-dupe-class-members`
`no-dupe-keys`
`no-duplicate-case`
~`no-else-return`~
`no-empty-character-class`
`no-empty-pattern`
refs #19240
=> docs: replace `var` with `const` in rule examples

docs/src/_data/links.json, docs/src/_data/navigation.json, docs/src/_data/sites/en.yml, docs/src/_data/sites/zh-hans.yml
similar to #19285 
Add code explorer in the navbar
similar to #19285
=> docs: add navigation link for code explorer

docs/src/extend/scope-manager-interface.md
Removes the lines in question.
Fixes #19281.
=> docs: remove 'I hope to' comments from scope-manager-interface

docs/src/assets/scss/components/rules.scss
The rule description in the rules reference page overflows, causing a horizontal scroll that affects the entire page layout on mobile devices.
https://github.com/user-attachments/assets/233eea5f-2076-43bb-a929-e79fd7c0b271
Added `overflow-x: auto` to the rule description, ensuring content overflow stays within the `rule_content` …
=> docs: Fix Horizontal Scroll Overflow in Rule Description on Mobile View

docs/src/rules/no-eq-null.md
Hello, 
I’ve added the `related_rules` property to the front matter of `no-eq-null.md`. 
This rule is associated with `eqeqeq`, as shown in the screenshot below:  
Additionally, I’ve added the missing backticks to `null`.
=> docs: add `eqeqeq` in related rules to `no-eq-null`

docs/src/use/configure/configuration-files.md
Added a warning about using `js.configs.all`. We used to have a warning about this but it seems it was lost as we refactored documentation.
=> docs: Clarify dangers of eslint:all

docs/src/contribute/package-json-conventions.md
While reviewing https://github.com/eslint/eslint/pull/19228, I noticed that `package-json-conventions.md` has unnecessary `edit_link` field, which would become problematic when we merge https://github.com/eslint/eslint/pull/19228 so that edit links depend on the branch.
Removed `edit_link` field from …
=> docs: remove hardcoded edit link

package.json
=> chore: upgrade to `@eslint/js@9.18.0`

docs/src/assets/scss/components/search.scss
For screen size less than 1024px the box of search results is overlapping the search input a bit.
as a fix the css for above 1024px screen has been applied to all screen sizes.
The issue is in [HEAD](https://eslint.org/docs/head/) branch right now.
=> docs: fix search result box position for small screens

docs/src/assets/scss/components/rules.scss
The divider of newly added category is inconsistent in different screen size.
updated the `rule.scss` code to fix this.
=> docs: fix divider for rule category

docs/src/_data/links.json
Fixes #19367
Added Bluesky link URL.
=> docs: fix Bluesky links

README.md, docs/src/_includes/components/rule-categories.macro.html
=> docs: clarify frozen rule description

README.md, docs/src/_includes/components/rule-categories.macro.html, docs/src/contribute/core-rules.md
- Added a section on the Core Rules page explaining what a frozen rule is.
- Updated the frozen rules banner to link to the description of what a frozen rule is.
- Removed the section on stylistic rules from the README. I don't think this is necessary now that we are marking rules as frozen. Whether or not they are stylistic is …
=> docs: Explain what frozen rules mean

docs/src/rules/no-eval.md
Changes `sourceType` to `"script"` (default is `"module"`) in `no-eval` examples with `this`.
In particular, the following example should be incorrect but currently it isn't because `this` in module scope does not refer to global object.
Added `{ "sourceType": "script" }`.
=> docs: change `sourceType` in `no-eval` examples

docs/src/rules/no-new.md, docs/src/rules/no-unused-expressions.md, docs/src/rules/no-unused-vars.md, docs/src/rules/no-void.md, docs/src/rules/prefer-arrow-callback.md
replaced var with const and let in rules examples
`no-new`
`no-unused-expressions`
`no-unused-vars`
`no-void`
`prefer-arrow-callback`
Refs https://github.com/eslint/eslint/issues/19240
=> docs: replace var with let or const in rules docs

package.json
=> chore: upgrade @eslint/js@9.20.0

README.md, docs/src/use/getting-started.md
Added docs for setting up a `.npmrc` file for pnpm.
fixes #19421
=> docs: Add instructions for pnpm compat

lib/types/index.d.ts, tests/lib/types/types.test.ts
Fixes #19414
Updated the `Rule.RuleContext` interface to fix the types of some inherited members and added some tests.
=> fix: fix `RuleContext` type

docs/src/assets/js/search.js
=> docs: allow typing in search box while dropdown is open

docs/package.json
Update Eleventy from v2 to v3
Ref: https://github.com/eslint/eslint.org/issues/644
similar to https://github.com/eslint/eslint.org/pull/690
I updated Eleventy from v2 to v3, verified the dev server, and tried building the website. Everything worked fine.
|  Eleventy v2 Build time | Eleventy v2 - Build time |
|-------| ---------| …
=> docs: Update Eleventy from v2 to v3

.github/ISSUE_TEMPLATE/bug-report.yml
[x] Other, please explain: tooling tweak for an issue form
Now that eslintrc is deprecated, I think using the `js` lang should be the norm for most/all issues.
=> chore: set js language for bug report issue config block

package.json
Updates eslint-scope dependency to just-released v8.3.0. There should be no functional differences in eslint, this is to verify the release and allow for further work on the new jsx references feature in eslint.
=> chore: upgrade eslint-scope@8.3.0

package.json
=> chore: upgrade @eslint/js@9.22.0

docs/src/assets/js/search.js
Added condition to not focus on search bar when pressing enter.
Fixes #19501
=> fix: navigation of search results on pressing Enter

docs/src/extend/custom-processors.md, docs/src/extend/languages.md, docs/src/extend/plugin-migration-flat-config.md, docs/src/extend/plugins.md, docs/src/extend/shareable-configs.md, docs/src/use/configure/configuration-files.md, docs/src/use/getting-started.md, packages/eslint-config-eslint/README.md, packages/js/README.md
I went through and updated several more files to use `defineConfig()` in the examples. I also ensured that the examples all use a `files` key in the same object to push this forward as a best practice.
=> docs: Update docs for defineConfig

docs/src/rules/no-unreachable-loop.md, docs/src/rules/no-unreachable.md
replaced var in no-unreacheable and no-unreachable-loop
=> docs: Replace var with let or const

lib/eslint/legacy-eslint.js, tests/lib/linter/linter.js, tests/lib/rules/lines-around-comment.js
=> chore: fix some comments

docs/src/extend/plugins.md, package.json
- Upgraded `@eslint/config-helpers`
- Updated documentation for plugins to describe how to include both eslintrc and flat config format configs
fixes #19513
=> feat: defineConfig() supports "flat/" config prefix

docs/.eleventy.js, docs/src/_includes/layouts/doc.html, docs/src/_plugins/pre-wrapper.js, docs/src/assets/scss/docs.scss
This is a port of my [PR](https://github.com/eslint/eslint.org/pull/698) that added the copy button to the blog, with one exception: it does not apply to correct/incorrect code blocks.
Closes #18769
=> docs: add copy button

docs/src/extend/stats.md, tests/lib/types/types.test.ts
Revert accidental changes
Reverted/fixed some accidental changes of #19355.
=> docs: revert accidental changes

docs/src/rules/no-shadow-restricted-names.md, docs/src/rules/no-shadow.md, docs/src/rules/no-throw-literal.md, docs/src/rules/no-underscore-dangle.md, docs/src/rules/strict.md
Refs https://github.com/eslint/eslint/issues/19240
Updated following rules:
- `docs/src/rules/no-shadow-restricted-names.md`
- `docs/src/rules/no-shadow.md`
- `docs/src/rules/no-throw-literal.md`
- …
=> docs: replace var with const in examples

.trunk/trunk.yaml
[X] Other, please explain: Update build
This PR excludes files that are autogenerated or updated during a release from Prettier formatting in Trunk. The purpose is to avoid failures in CI during a release because of unexpected file formatting. …
=> build: exclude autogenerated files from Prettier formatting

docs/src/extend/custom-rules.md
The code example of fixer doesn't look correct to me. I made the change based on my understanding of what it tries to explain.
no
=> docs: Update custom-rules.md code example of fixer

docs/src/use/command-line-interface.md, lib/linter/code-path-analysis/code-path-state.js, lib/rules/no-constant-binary-expression.js, lib/rules/no-unused-vars.js
=> chore: fix some typos in comment

.editorconfig
**Issue**: The local .editorconfig rules defined in the IDE were overriding the prettierconfig rules defined in project, making unrelated prettier changes getting pushed during commit
**Fix**: Added .editorconfig in …
=> chore: modify .editorconfig to keep parity with prettier config

docs/src/rules/no-else-return.md
-   [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Related to #19240
=> docs: replace existing var with const

docs/src/rules/init-declarations.md, lib/rules/init-declarations.js, tests/lib/rules/init-declarations.js
Refs #19173 
It adds support for TypeScript's `declare` variables.
=> feat: support TS syntax in `init-declarations`

package.json
[x] Other, please explain: internal scripts fix
Fixes the typo as reported in https://github.com/eslint/eslint/pull/19355#issuecomment-2762206554
Co-authored-by: @fisker
=> chore: correct 'flter'/'filter' typo in package script

lib/rules/no-loop-func.js, tests/lib/rules/no-loop-func.js
Fix https://github.com/eslint/eslint/issues/19586
No
=> fix: deduplicate variable names in no-loop-func error messages

docs/src/use/configure/ignore.md
There's no need to resort to `node:path` to resolve relative paths; as `new URL()` can do it, particularly given that we start from a URL with `import.meta.url`.
The code currently in the docs is reminiscent of how …
=> docs: simplify gitignore path handling in includeIgnoreFile section

docs/src/use/configure/configuration-files.md
The `process.features.typescript` flag, which #19401 relies on, was added in Node.js `v22.10`, meaning there currently is only support for `>= v22.10.0.` Manually parsing the flag to support `v22.6.x - v22.9.x` is pretty cumbersome, so I would suggest to document support only starting `>= v22.10.0` 👍
[ ] Add autofix to a …
=> docs: update documentation for `--experimental-strip-types`

package.json
=> chore: upgrade @eslint/js@9.24.0

tests/lib/rules/no-loop-func.js
Fixes a `no-loop-func` test that is currently failing on the main branch.
The test was added in https://github.com/eslint/eslint/pull/19559, but in the meantime we merged https://github.com/eslint/eslint/pull/19595, …
=> test: fix `no-loop-func` test with duplicate variable reports

docs/src/_data/further_reading_links.json, docs/src/rules/no-unused-expressions.md, lib/rules/no-unused-expressions.js, tests/lib/rules/no-unused-expressions.js
Related to #19173 
Made current [eslint/no-unused-expressions](https://eslint.org/docs/latest/rules/no-unused-expressions) typescript syntax aware as per [@typescript-eslint/no-unused-expressions](https://typescript-esli …
=> feat: support TS syntax in `no-unused-expressions`

docs/src/_data/further_reading_links.json, docs/src/rules/no-use-before-define.md
Add an example of why you'd want to disable the `functions` option and correct grammatical errors.
n/a
=> docs: no-use-before-define tweaks

lib/types/rules.d.ts
Added the types to new options that are added to support TypeScript syntax.
No
=> docs: add types for multiple rule options

docs/src/use/getting-started.md
Fix https://github.com/eslint/eslint/issues/19619
No
=> docs: use `eslint-config-xo` in the getting started guide

.trunk/trunk.yaml, package.json
Upgrade Trunk and its linters to the latest releases.
Closes #19627
=> chore: upgrade trunk

package.json
=> chore: upgrade @eslint/js@9.25.0

package.json
=> chore: upgrade @eslint/js@9.25.1

lib/types/index.d.ts, tests/lib/types/types.test.ts
Updates `Plugin.meta` type with `namespace` property, as per [Flat Config Extends RFC](https://github.com/eslint/rfcs/tree/main/designs/2024-config-extends).
Updated `lib/types/index.d.ts` and types tests.
=> fix: add `namespace` to `Plugin.meta` type

lib/cli-engine/cli-engine.js, lib/cli.js, lib/eslint/eslint.js, lib/eslint/legacy-eslint.js, lib/rules/index.js, lib/rules/utils/lazy-loading-rule-map.js, lib/shared/types.js
Fix internal types
I noticed that the `Plugin` type defined in `lib/shared/types` was out of date, so I removed it and replaced its references with `ESLint.Plugin` from the TypeScript types in `lib/types`.
I also replaced references to the previously removed `Rule` type in `lib/shared/types.js` with `Rule.RuleModule` from …
=> chore: fix internal type references to `Plugin` and `Rule`

package.json
=> chore: upgrade to `@eslint/js@9.26.0`

lib/linter/file-context.js, lib/linter/linter.js, tests/lib/linter/file-context.js
Refactor 
Continuing to move functionality out of the `runRules()` function in `Linter`, this moves the functionality for creating rule contexts using a single `FileContext` as the prototype into `FileContext` itself.
refs #18787
I'm not sure if `extend` is the right name for this method. Definitely open to other options.
=> refactor: Easier RuleContext creation

.editorconfig
[x] Other, please explain: Development fix
Fixing a syntax error in the `.editorconfig` file.
Nope.
=> chore: remove unbalanced curly brace from `.editorconfig`

docs/src/contribute/core-rules.md
Updated the description of frozen rules to indicate we will make changes to support TypeScript.
=> docs: Update description of frozen rules to mention TypeScript

package.json
=> chore: upgrade @eslint/js@9.27.0

docs/src/maintain/manage-issues.md, docs/src/use/configure/configuration-files.md, docs/src/use/configure/rules.md, docs/src/use/core-concepts/glossary.md, docs/src/use/core-concepts/index.md, docs/src/use/getting-started.md, packages/eslint-config-eslint/README.md, tools/update-readme.js
Hello,
In this PR, I’ve fixed a few minor typos and added relevant links to improve readability.
=> docs: fix minor typos and add links

.gitignore
Hello,
This PR is follow-up to https://github.com/eslint/markdown/pull/362.
In this PR, I've added `*.code-workspace` to `.gitignore`.
The `*.code-workspace` file functions similarly to the `.vscode` folder and generally shouldn't be included in version control.
Reference: …
=> chore: add `*.code-workspace` to `.gitignore`

docs/src/rules/func-style.md, lib/rules/func-style.js, tests/lib/rules/func-style.js
Modified the `func-style` rule to ignore overloaded function declarations.
Fixes #19738
=> feat: ignore overloaded function declarations in func-style rule

tests/lib/linter/source-code-traverser.js
Removes some unnecessary code and adds a few more checks in `SourceCodeTraverser` tests.
* Modified traversing tests to use the same AST in expected and actual results. This avoids duplicate parsing and allows for checks by reference.
* Added checks to ensure traversal returns objects from the AST.
* Removed a duplicate filter.
=> test: update `SourceCodeTraverser` tests

.github/renovate.json5
We are intentionally using the specified version and don't need to upgrade, hence ignoring for renovate to avoid PRs like  https://github.com/eslint/eslint/pull/19784 and https://github.com/eslint/eslint/pull/19783
- Reference - https://docs.renovatebot.com/configuration-options/#ignoredeps
=> chore: ignore jiti-v2.0 & jiti-v2.1 for renovate

docs/src/rules/no-use-before-define.md, lib/rules/no-use-before-define.js, lib/types/rules.d.ts, tests/lib/rules/no-use-before-define.js
Updated the `no-use-before-define` rule to support TypeScript syntax.
Refs #19173
=> feat: support TypeScript syntax in `no-use-before-define`

package.json
=> chore: update globals to v16

package.json
=> chore: upgrade to `@eslint/js@9.28.0`

conf/globals.js, tests/lib/rules/no-undef.js
Add ES2025 globals.
https://github.com/sindresorhus/globals/blob/main/data/es2025.mjs
=> feat: add ES2025 globals

lib/cli.js, lib/eslint/eslint.js, lib/linter/apply-disable-directives.js, lib/shared/naming.js, lib/shared/relative-module-resolver.js, package.json, tests/lib/shared/naming.js, tests/lib/shared/relative-module-resolver.js
Refactor
This refactor removes `@eslint/eslintrc` from flat config-specific functionality. In order to do this, I had to add back the `naming` and `ModuleResolver` utilities that were previous extracted into `@eslint/eslintrc`. These are necessary primarily to enable loading of formatters.
=> refactor: Remove eslintrc from flat config functionality

package.json, tests/lib/eslint/eslint.js
Fixes #19813
Fixes #19814
Updated `@eslint/config-array` to v0.20.1, which includes fixes for #19813 (https://github.com/eslint/rewrite/pull/220) and #19814 (https://github.com/eslint/rewrite/pull/218), and added tests to confirm that #19813 and #19814 are fixed. All added tests are failing with `@eslint/config-array` v0.20.0.
=> fix: explicit matching behavior with negated patterns and arrays

package.json
=> chore: upgrade @eslint/js@9.29.0

docs/src/use/configure/configuration-files.md
A single letter typo in one of the code excerpts.
Fixed typo.
=> docs: Fixed Typo in configuration-files.md

package.json
=> chore: upgrade to `@eslint/js@9.30.0`

package.json
=> chore: upgrade to `@eslint/js@9.30.1`

CONTRIBUTING.md, docs/src/contribute/work-on-issue.md
Clarified expectations around who is responsible for issues. This mostly just documents what we've already been doing in a clearer way.
fixes #19900
=> docs: Update working on issues info

package.json
Hello,
In this PR, I've bumped mocha to v11.
[mocha v11](https://github.com/mochajs/mocha/releases/tag/v11.0.0) has no breaking changes for us, since it only upgrades the Node.js version requirement, which is compatible with `eslint`.
=> chore: bump mocha to v11

package.json
=> chore: upgrade to `@eslint/js@9.31.0`

package.json
Pin a dev dependency.
refs unjs/jiti#388
This PR temporarily pins the `jiti` dependency to version 2.4.2 to fix unit tests which are currently failing with jiti v2.5.0. E.g.:
https://github.com/eslint/eslint/actions/runs/16487028781/job/46615571667
If a patch is released quickly, we could instead upgrade `jiti` to the newest …
=> ci: pin `jiti` to version 2.4.2

package.json
Updates `@eslint/plugin-kit` dependency to the latest version to include https://github.com/eslint/rewrite/pull/240.
=> fix: bump @eslint/plugin-kit to 0.3.4 to resolve vulnerability

package.json
After https://github.com/eslint/eslint/pull/19964 was merged due to CI errors, a new version of `jiti` (2.5.1) was released to resolve the bug.
So, I'm unpinning the version to `^2.5.1`.
Ref: https://github.com/unjs/jiti/releases/tag/v2.5.1, https://github.com/eslint/eslint/pull/19964
=> ci: unpin `jiti` to version `^2.5.1`

package.json
Upgrade `@eslint/js`
Upgraded `@eslint/js`.
=> fix: Upgrade @eslint/js

docs/src/rules/no-multi-assign.md
fix: typo
fix typo.
Assuming the "correct code" section is right, the "incorrect code" section should follow the same logic.
=> docs: Update no-multi-assign.md

docs/src/rules/no-else-return.md
Before:
The example code explaining the base rule (without options) was written under the `{"allowElseIf": "true"}` . So it was unclear what the sample code was explaining, what the rule does, or what the option does.
After:
Added a new example code section before the "Option" section (Other ESLint rule docs also follow this …
=> docs: [no-else-return] clarify sample code.

docs/src/_includes/components/button.macro.html
=> chore: remove redundant word

docs/src/rules/no-var.md
it didn't make sense for enoughFood to be be true when food is less than people
=> docs: invert comparison logic for example in `no-var` doc page

lib/rules/array-callback-return.js, package.json, packages/js/src/configs/eslint-all.js
Update a dependency and fix the build
I removed an unused `eslint-disable` directive that is being reported as an error since the recent publishing of [`@eslint-community/eslint-utils@4.8.0`](https://www.npmjs.com/package/@eslint-community/eslint-utils/v/4.8.0), and updated the entry in `package.json` to ensure the latest …
=> chore: update `@eslint-community/eslint-utils`

lib/rules/no-empty-function.js, tests/lib/rules/no-empty-function.js
- Added fixable suggestions to insert /* empty */ inside empty function bodies.
- Updated tests
Closes #20055
=> feat: implement suggestions for no-empty-function

docs/src/use/getting-started.md
=> docs: improve phrasing - "if" → "even if" from getting-started section

docs/_examples/custom-rule-tutorial-code/eslint.config.js, docs/_examples/custom-rule-tutorial-code/package.json, docs/_examples/integration-tutorial-code/package.json, docs/src/extend/custom-rule-tutorial.md
In this PR, I've updated the examples to use the `defineConfig` helper function.
I've also upgraded the `eslint` dev dependency to the latest version.
I'm not sure if I've updated all of the related docs and code correctly. If anything is missing, I'm happy to update it.
=> chore: update example to use `defineConfig`

docs/src/extend/custom-parsers.md, docs/src/use/configure/migration-guide.md, docs/src/use/core-concepts/glossary.md
This PR updates docs examples to use the `defineConfig` helper function where appropriate.
=> docs: update examples to use `defineConfig`

package.json
=> chore: upgrade @eslint/js@9.36.0

README.md, packages/eslint-config-eslint/README.md, packages/js/README.md
In this PR, I've updated the `README.md` files in the `packages`.
The main changes are:
1. I added badges, following the ones in the root-level `README.md`.
https://github.com/eslint/eslint/blob/1ace67d9f7903adc3d3f09868aa05b673e7d3f3b/README.md?plain=1#L1-L6
2. I updated the ESLint-related social links to match those in the …
=> docs: update `README` files to add badge and instructions

docs/src/rules/class-methods-use-this.md, docs/src/rules/consistent-return.md, docs/src/rules/default-case.md, docs/src/rules/func-names.md, docs/src/rules/logical-assignment-operators.md, docs/src/rules/max-lines.md, docs/src/rules/new-cap.md, docs/src/rules/no-case-declarations.md, docs/src/rules/no-eq-null.md, docs/src/rules/sort-keys.md
In this PR, I've fixed typos across the docs.
This is a minor change; the main focus is fixing missing punctuation, capitalization, and backticks.
N/A
=> docs: fix typos across the docs

README.md, tools/update-readme.js
Today's data fetch failed with:
```
Cannot read properties of null (reading 'trim')
at /home/runner/work/eslint/eslint/tools/update-readme.js:66:59
```
https://github.com/eslint/eslint/actions/runs/18306247769
This PR updates `tools/update-readme.js` to account for case when team member's name is not available in data.
Updated …
=> chore: use team member's username when name is not available in data

lib/types/index.d.ts, tests/lib/types/types.test.ts
This PR marks legacy `SourceCode` methods as `@deprecated` and refines the typings
=> fix: correct SourceCode typings
