- .github/PULL_REQUEST_TEMPLATE.md
Updating our PR template text
I've been noticing that we're getting an increasing number of PRs that do not have a corresponding accepted issue. While we have a process in place to handle this, I can …
> Chore: add prerequisites checklist to PR template

- lib/rules/id-blacklist.js
- tests/lib/rules/id-blacklist.js
https://github.com/eslint/eslint/issues/12787
I modified the should report logic to check that the `effectiveParent`'s `parent` is a block statement and added tests for the case. …
> Fix: id-blacklist should ignore ObjectPatterns (fixes #12787)

- lib/rules/computed-property-spacing.js
- tests/lib/rules/computed-property-spacing.js
Changes `computed-property-spacing` report locations.
* For missing spaces the rule will now report `loc` instead of just `loc.start`.
* For disallowed spaces the rule will now report the location of spaces (the range that should be removed) instead of the location of the brackets.
before this change:
after this change:
> Fix: improve report location for computed-property-spacing

- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
[X] Bug fix #12737
This bug fix produces **more** warnings by default.
The previous behavior was to disallow `export * from "foo"` just when the whole module `"foo"` is restricted.
After this fix, the rule will disallow `export * from "foo"` even if only some names from `"foo"` are restricted but not the whole module (i.e., configuration for `"foo"` has `importNames` option).
> Update: fix no-restricted-imports export * false negative (fixes #12737)

- docs/rules/default-case-last.md
- lib/rules/default-case-last.js
- lib/rules/index.js
- tests/lib/rules/default-case-last.js
- tools/rule-types.json
[X] New rule #12665
```js
/*eslint default-case-last: "error"*/
switch (foo) {
default:
bar();
break;
case "a":
baz();
break;
}
switch (foo) {
case 1:
bar();
break;
default:
baz();
break;
case 2:
quux();
break;
}
switch (foo) {
case "x":
bar();
break;
default:
case "y":
baz();
break;
}
switch (foo) {
default:
break;
case -1:
bar();
break;
}
switch (foo) {
default:
doSomethingIfNotZero();
case 0:
doSomethingAnyway();
}
```
New rule: `default-case-last`
> New: Add default-case-last rule (fixes #12665)

- lib/rules/prefer-object-spread.js
- tests/lib/rules/prefer-object-spread.js
[X] Bug fix #12086
The rule will now ignore `Object.assign()` with 2 or more arguments if any of the arguments is an object expression with at least one getter or setter.
> Fix: prefer-object-spread false positives with accessors (fixes #12086)

- lib/rules/indent.js
- tests/lib/rules/indent.js
> Fix: wrong indent at tagged template in indent (fixes #12122)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
no-extra-parens
more
```js
// left-hand side of assignments
(a) = b;
(a) += b;
(a.b) = c;
// left-hand side of default assignments
[(a) = b] = [];
[(a.b) = c] = [];
({ a: (b) = c } = {});
({ a: (b.c) = d } = {});
// array pattern elements and rest element
[(a)] = [];
[(a.b)] = [];
[...(a)] = [];
[...(a.b)] = [];
// object pattern property values and rest property
({ a: (b) } = {});
({ a: (b.c) } = {});
({ ...(a) } = …
```
> Breaking: Check assignment targets in no-extra-parens

- lib/rules/template-curly-spacing.js
- tests/lib/rules/template-curly-spacing.js
fix #12744 by treating comments as tokens.
This change will produce new warnings in the cases below.
Can this change be a semver-minor bug fix? …
> Update: treat comment tokens in template-curly-spacing (fixes #12744)

- docs/rules/array-element-newline.md
- lib/rules/array-element-newline.js
- tests/lib/rules/array-element-newline.js
https://eslint.org/docs/rules/array-element-newline
The number of warnings will stay the same.
**How will the change be implemented? (New …
> Update: Separate pattern/expression options for array-element-newline

- docs/rules/radix.md
- lib/rules/radix.js
- tests/lib/rules/radix.js
`radix`
more warnings
**How will the change be implemented? (New option, new default …
> Breaking: make `radix` rule stricter

- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
https://github.com/eslint/eslint/issues/12225
no-constant-condition uses a recursive function `isConstant` to detect if items are constants. 
Previously we were presuming that all arrays were always …
> Fix: no-constant-condition doesn't introspect arrays (fixes #12225)

- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
fixes #12785 
Added the extra white space which was removed here https://github.com/eslint/eslint/pull/12316/files#diff-e8cce2004dd5e0386021b0e80370c8ebL190
No
> Fix: multiline-comment-style rule add extra space after * (fixes #12785)

- tests/lib/rules/no-constant-condition.js
[X] Other, please explain: Follow-up to #12307
Added a test that verifies that the change from #12307 applies only to binary `+`.
> Chore: add test for no-constant-condition

- lib/rules/no-magic-numbers.js
- tests/lib/rules/no-magic-numbers.js
[X] Bug fix
This bug fix produces **more** warnings by default.
* **ESLint Version:** v6.8.0
default
<details>
```js
},
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbWFnaWMtbnVtYmVyczogW1wiZXJyb3JcIiwgeyBcImlnbm9yZUFycmF5SW5kZXhlc1wiOiB0cnVlIH1dKi9cblxuMTAwIC50b1N0cmluZygpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxl …
> Update: fix no-magic-numbers false negative with ignoreArrayIndexes

- lib/rules/no-iterator.js
- lib/rules/no-proto.js
- tests/lib/rules/no-iterator.js
- tests/lib/rules/no-proto.js
For checking template literal, also, I change the checking logic to use `getStaticPropertyName()` in `ast-utils`.
It needs a consensus of ESlint members. - #12801
> Update: check template literal in no-proto, no-iterator (fixes #12801)

- lib/shared/types.js
This is minor fix for shared type definition.
Thanks!
> Chore: add missing `ecmaVersion` 2020/11 type value

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint operator-assignment: ["error", "never"]*/
foo/=bar
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgb3BlcmF0b3ItYXNzaWdubWVudDogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG5cbmZvby89YmFyXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJl …
> Fix: operator-assignment crash on adjacent division assignment

- docs/rules/prefer-regex-literals.md
Added `/*eslint prefer-regex-literals: "error"*/` in the examples, missed that in the original PR.
> Docs: add missing eslint comments in prefer-regex-literals examples

- docs/rules/array-callback-return.md
- lib/rules/array-callback-return.js
- tests/lib/rules/array-callback-return.js
array-callback-return
more
new option checkForEach created, defaulted to false. when true, rule will also check if Array.forEach callback has a return statement and warn if it does
Examples of **incorrect** code for the `{ "checkForEach": true }` option:
```js
/*eslint array-callback-return: ["error", { checkForEach: true }]*/
myArray.forEach(function(item) {
return handleItem(item)
});
```
Examples of **correct** code for the `{ …
> Update: array-callback-return checks Array.forEach (fixes #12551)

- lib/rules/id-blacklist.js
- tests/lib/rules/id-blacklist.js
[X] Bug fix
default
<details>
```js
sourceType: "module"
},
};
```
</details>
```js
/* eslint id-blacklist: ["error", "foo"] */
import { foo as bar } from "mod";
export { foo as bar } from "mod";
import { foo } from "mod";
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGlkLWJsYWNrbGlzdDogW1wiZXJyb3JcIiwgXCJmb29cIl0gKi9cblxuaW1wb3J0IHsgZm9vIGFzIGJhciB9IGZyb20gXCJtb2RcIjtcbmV4cG9 …
> Fix: id-blacklist false positives on renamed imports

- docs/rules/yoda.md
- lib/rules/yoda.js
- tests/lib/rules/yoda.js
I added checking for template literals, which have no expressions.
In the actual version(`v6.8.0`), a comparison between a literal and expression is warned, even if operands in the expressions are consist of literals only.
[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJuZXZlclwiX …
> Update: check template literal in yoda (fixes #12863)

- lib/rules/no-dupe-class-members.js
- tests/lib/rules/no-dupe-class-members.js
[X] Changes an existing rule #12808
`no-dupe-class-members` was ignoring all computed keys.
After this PR, this rule will also check those class members for which `astUtils.getStaticPropertyName` returns a string value. This is new default behavior.
```js
/*eslint no-dupe-class-members: ["error"]*/
class A {
["a"](){}
["a"](){} // error
["b"](){}
b(){} // error
"c"(){}
[`c`](){} // error
[123](){}
123(){} // error
}
```
The rule will still ignore computed keys with values that are not statically known:
```js
/*eslint no-dupe-class-members: ["error"]*/
class A {
[a](){}
[a](){} // no error
}
```
> Breaking: no-dupe-class-members checks some computed keys (fixes #12808)

- docs/user-guide/configuring.md
- lib/cli-engine/cli-engine.js
- lib/cli-engine/config-array/ignore-pattern.js
- tests/lib/cli-engine/cli-engine.js
[X] Other, please explain: change an existing core feature.
This PR implements RFC51 -- changes the default ignore patterns.
- unignore `.eslintrc.js`
- unignore `/bower_components/*`
- ignore `node_modules/*` in subdirectories.
This PR fixes some tests for the unignoring `.eslintrc.js`.
> Breaking: change default ignore pattern (eslint/rfcs#51)

- docs/rules/use-isnan.md
- lib/rules/use-isnan.js
- tests/lib/rules/use-isnan.js
fixes #12810
Rule: `use-isnan`.
This PR changes  `enforceForSwitchCase` option's default value to `true`.
The rule will now by default disallow `switch (NaN)` and `case NaN`.
Changed default value and updated documentation.
> Breaking: use-isnan enforceForSwitchCase default `true` (fixes #12810)

- lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/rules/no-unreachable.js
Changed `code-path-analyzer` to treat `YieldExpression` as a `throwable.`
It will fix #12880 
Are there any other rules affected by this change except `no-unreachable.`?
I searched, but could not find. If I missed something, please tell me. Thanks : )
> Fix: make YieldExpression throwable (fixes #12880)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md)) fixes #12717
1. Removed `!isParenthesisedTwice(node.body)` for fixing #12717.
- It will make this rule to ignore checking "double extra parens" if the option (`enforceForNewInMemberExpressions : false`) is specified.
2. Added some tests for checks whether they ignore "double extra parens" when the option is specified.
- …
> Fix: fix inconsistently works option in no-extra-parens (fixes #12717)

- docs/user-guide/configuring.md
Rules from plugins need to be namespaced using plugin name, which is missing.
Add missing plugin reference
no
> Docs: add missing plugin reference

- docs/rules/func-names.md
- lib/rules/func-names.js
- tests/lib/rules/func-names.js
fixes #12194
Start report code like `export default function() {}` when `always` or `as-needed`.
Yes.
> Breaking: check unnamed default export in func-names (fixes #12194)

- lib/rules/id-blacklist.js
- tests/lib/rules/id-blacklist.js
This PR will fix #12807 
It will make a new warning on the below cases. ( about blacklist `foo`)
1. renaming identifier in an ObjectPattern destructuring.
```js
/*eslint id-blacklist: ["error", "foo"] */
const { bar : foo} = asd;
```
2. the last identifier in an ObjectPattern destructuring.
```js
/*eslint id-blacklist: …
```
> Update: report rename id destructuring in id-blacklist (fixes #12807)

- docs/rules/semi.md
The documentation claimed that JS is unique among C-like languages in having optional semicolons at the end of statements. This is not true, as Go (Golang) also has optional semicolons and is C-like.
This didn't seem terribly important, so rather than go on a tangent about what languages do or don't require semicolons, …
> Remove claim about semicolons from docs

- conf/category-list.json
These descriptions are not run through the Markdown -> HTML generation step, since we blast these over as JSON and use the JSON file as the data source during site generation.
Corresponding PR to fix the current site (since this won't go into effect until our next release) can be found …
> Docs: fix category descriptions for site generation (fixes #12894)

- docs/user-guide/getting-started.md
From eslint/website#693
According to the `configuration.md` page, the `.eslintrc` file format has been deprecated, and the `--init` option will generate either a `.yml`, `.js`, or `.json` file depending on what you pick in the initialization wizard.
This commit syncs the getting-started instructions with the …
> Docs: References correct config file name

- lib/rules/no-eval.js
- tests/lib/rules/no-eval.js
This PR adds `loc.end` to reports in `no-eval`. 
Just a small change from `loc.start` to `loc`.
> Fix: add end location to report in no-eval

- docs/developer-guide/nodejs-api.md
- docs/user-guide/configuring.md
The documentation for custom parsers was extracted from the main
"Working with Plugins" documentationn to its own page in #10431.
I grepped the documentation to make sure I found all of the links:
```sh
$ grep -r 'working-with-custom-parsers' docs
docs/user-guide/configuring.md:1. It must conform to the [parser …
```
> Docs: Fix links to custom parsers doc

- docs/rules/accessor-pairs.md
- lib/rules/accessor-pairs.js
- tests/lib/rules/accessor-pairs.js
fixes #12811
Rule: `accessor-pairs`.
This PR changes  `enforceForClassMembers` option's default value to `true`.
The rule will now by default apply to classes, too.
Changed default value and updated documentation.
> Breaking: classes default `true` in accessor-pairs (fixes #12811)

- lib/rules/wrap-iife.js
- tests/lib/rules/wrap-iife.js
[X] Bug fix
default
<details>
```js
ecmaVersion: 2020
},
};
```
</details>
```js
/*eslint wrap-iife: ["error", "inside"]*/
if (function (){}()) {}
while (function (){}()) {}
do {} while (function (){}())
switch (function (){}()) {}
with (function (){}()) {}
foo(function (){}());
new foo(function (){}());
import(function (){}());
new (function (){}())();
```
[Online Demo …
> Fix: wrap-iife autofix removes mandatory parentheses

- docs/rules/no-dupe-class-members.md
I mentioned that TypeScript has the "no-dupe-class-members" rule built in. TypeScript will throw error TS2393 (Duplicate function implementation) if there are problems with the naming. Turning on ESLint's "no-dupe-class-members" rule can lead to false positives because it won't allow function overloading. The …
> Docs: Mention TypeScript's compiler check

- docs/rules/computed-property-spacing.md
- lib/rules/computed-property-spacing.js
- tests/lib/rules/computed-property-spacing.js
fixes #12812
Rule: `computed-property-spacing`.
This PR changes  `enforceForClassMembers` option's default value to `true`.
The rule will now by default apply to classes, too.
Changed default value and updated documentation.
> Breaking: class default `true` computed-property-spacing (fixes #12812)

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
[x] Bug fix 
Fixes #12884
`arrow-body-style` autofix crashes or produces invalid code while trying to convert object literal expression body to a block body, whenever `(` and `{` are not adjacent:
* This works well: `() => ({})`
* This throws (there's a space between): `() => ( {})` [Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICBcImFycm93LWJvZHktc3R5bGVcIjogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxuKCkgPT4gKCB7fSkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)
* This removes the wrong closing paren: `(() => ( {}))` fixed to `(() => {return  {})}` [Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICBcImFycm93LWJvZHktc3R5bGVcIjogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxuKCgpID0+ICgg …
> Fix: arrow-body-style crash with object literal body (fixes #12884)

- lib/rules/curly.js
- tests/lib/rules/curly.js
[X] Bug fix
Fixes #12928
Implemented a more generic check than the existing `requiresBraceOfConsequent`, to account for more cases when an `if` can become associated with an unrelated `else`.
In the following case, the rule will still report 2 errors although only 1 pair of braces can be removed:
```js
/* eslint curly: ["error", "multi"] */
if (a) {
while (b) { 
if (c) foo(); 
}  
} else 
bar();
```
Auto-fix will remove the outer braces only. After that, the inner braces will become valid.
User can manually remove either of these. After that, the error for the other braces will disappear.
> Fix: curly removes necessary braces between if and else (fixes #12928)

- lib/rules/func-names.js
- tests/lib/rules/func-names.js
[X] Bug fix
This bug fix produces **more** warnings.
* **ESLint Version:** v7.0.0-alpha.1
default
<details>
```js
}
};
```
</details>
[Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGZ1bmMtbmFtZXM6IFtcImVycm9yXCIsIFwiYXMtbmVlZGVkXCJdICovXG5cbltvYmoucHJvcCA9IGZ1bmN0aW9uKCl7fV0gPSBmb287XG5cbih7IGE6IG9iai5wcm9wID0gZnVuY3Rpb24oKXt9IH0gPSBmb28pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlw …
> Update: func-names `as-needed` false negative with AssignmentPattern

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
- tests/lib/rules/multiline-comment-style.js
Additional check in the `RuleTester` - an `invalid` test will fail if any of its error objects contains a key that isn't expected.
Since none of the error params is mandatory, test case might be silently useless or missing to check an important detail (e.g. node type or location) just because of a small typo.
This might be a breaking change at the moment, but at least it found 90 tests with typos such as `messsage`, `messgeId`, `messagesId`, or using `nodeType` instead of `type`.
If accepted, I'll add test cases for this change, of course.
> Breaking: Test with an unknown error property should fail in RuleTester

- lib/rules/no-restricted-modules.js
- tests/lib/rules/no-restricted-modules.js
Issue: https://github.com/eslint/eslint/issues/12926
Added support for `TemplateLiteral` argument check on top of existing string `Literal` check to `no-restricted-modules` rule.
- Does this change needs any documentation changes?
- Are added test fixtures enough?
> Update: no-restricted-modules handle TemplateLiteral (fixes #12926)

- packages/eslint-config-eslint/default.yml
- tests/lib/cli-engine/cascading-config-array-factory.js
Updating `eslint-config-eslint`
Working on https://github.com/eslint/eslint/pull/12939, I noticed that we currently enforce no spaces between the `async` keyword and the parens of an async arrow function.
This PR updates our `space-before-function-paren` configuration to require a space in this case (leaving everything …
> Chore: update space-before-function-paren in eslint-config-eslint

- lib/rules/no-extra-parens.js
- lib/rules/operator-assignment.js
- lib/rules/utils/ast-utils.js
- package.json
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-implicit-coercion.js
- tests/lib/rules/operator-assignment.js
- tests/lib/rules/utils/ast-utils.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/* eslint no-extra-parens: ["error"] */
/* eslint operator-assignment: ["error", "never"] */
a/(/**/b);
a/(//
b);
a/(/regex/);
a/=/**/b;
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogW1wiZXJyb3JcIl0gKi9cbi8qIGVzbGludCBvcGVyYXRvci1hc3NpZ25tZW50OiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdICovXG5cbmEvKC8qKi9 …
> Fix: Check division operator in astUtils.canTokensBeAdjacent

- docs/rules/func-style.md
closes #12900
Two commits
- added lock files to gitignore
- made docs changes for `func-style` rule
#12900
> Docs: added less confusing explanation for func-style (fixes #12900)

- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
[X] Bug fix
fixes #13022
In the branch for computed pattern properties, the `camelcase`  rule should check for inner underscores only, like in all other branches.
> Fix: camelcase false positive with computed property (fixes #13022)

- lib/init/config-file.js
- tests/lib/init/config-file.js
Include a newline character before EOF when writing out a .js or .json-based config in `eslint --init`. Previously only the .yaml mode did this.
> Fix: Newline before eof when creating config via --init

- docs/rules/no-plusplus.md
- lib/rules/no-plusplus.js
- tests/lib/rules/no-plusplus.js
[X] Bug fix
fixes #13005
`allowForLoopAfterthoughts` in the `no-plusplus` rule will now additionally allow `++` and `--` in sequence expressions:
```js
/*eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]*/
for (i = 0, j = 0; i < l; i++, j++); // ok
```
Also fixed false negatives when the node isn't the `update` node:
```js
for (i++;;);
for (; i++;);
```
> Fix: no-plusplus allow comma operands in for afterthought (fixes #13005)

- docs/developer-guide/nodejs-api.md
- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
[X] Add something to the core 
fixes #12606
RuleTester now allows testing Suggestions with `data`. 
Example:
```js
{
code: "var foo;",
errors: [{
suggestions: [{
messageId: "renameFoo",
data: { newName: "bar" },
output: "var bar;"
}, {
messageId: "renameFoo",
data: { newName: "baz" },
output: "var baz;"
}]
}]
}
```
Also, RuleTester documentation was missing `messageId` and `data` for errors.
To avoid breaking change, as noted in [#12606 (comment)](https://github.com/eslint/eslint/issues/12606#issuecomment-560167212), it's still allowed to specify both `desc` and `messageId` for the same suggestion. This …
> Update: Allow testing Suggestions with data in RuleTester (fixes #12606)

- docs/rules/no-empty-function.md
- lib/rules/no-empty-function.js
- tests/lib/rules/no-empty-function.js
Added `asyncFunctions` and `asyncMethods` to `ALLOW_OPTIONS` for `no-empty-function` rule
fixes https://github.com/eslint/eslint/issues/12768
Also, I am bit confused about how to write tests for valid code as for this rule, gives test cases are converted into valid and invalid
> Fix: added async in allow method in no-empty-function (fixes #12768)

- docs/rules/prefer-numeric-literals.md
- lib/rules/prefer-numeric-literals.js
- tests/lib/rules/prefer-numeric-literals.js
I changed it to check literal with using `astUtils.getStaticValue` and `astUtils.isStringLiteral`
This PR will Fixes #13045
> Fix: check template literal in prefer-numeric-literals (fixes #13045)

- docs/rules/quote-props.md
Removed the code from snippet which is correct but placed in the section for incorrect example
for `quote-prop` rule's `always` example in docs
[check the snippet for `incorrect`](https://github.com/eslint/eslint/blob/master/docs/rules/quote-props.md#always)
```js
{
"qux-lorem": true  // correct code
}
``` …
> Docs: removed correct code from incorrect eg section

- docs/user-guide/command-line-interface.md
- docs/user-guide/configuring.md
Fixes #13006
The ```node_modules``` folder is ignored by default. However, in some parts of the documentation it is still included in ignore configs. I removed the ```node_modules``` entries from the examples and clarified in an example ignore config how it can be added back in.
Whether the added/edited documentation is …
> Docs: Clarify that node_modules is ignored by default

- lib/rules/prefer-object-spread.js
- tests/fixtures/parsers/typescript-parsers/object-assign-with-generic/object-assign-with-generic-1.js
- tests/fixtures/parsers/typescript-parsers/object-assign-with-generic/object-assign-with-generic-2.js
- tests/lib/rules/prefer-object-spread.js
[X] Bug fix
fixes #13058
Changed `prefer-object-spread` fixer to remove everything before the opening paren of the argument list, instead of just `callee`. This should remove TypeScript's type arguments as well.
This looks like a correct change even without TS, because it removes whitespace between `Object.assign` and the opening paren of arguments, which is what similar rules usually do (via `fixer.replaceText` on the whole `CallExpression`).
> Fix: remove type arguments in prefer-object-spread (fixes #13058)

- lib/rules/id-blacklist.js
- tests/lib/rules/id-blacklist.js
[X] Bug fix
Fixes #12567
`id-blacklist` will now ignore identifiers that represent a reference to an external global variable:
```js
/* eslint id-blacklist: ["error", "Number", "undefined"] */
const foo = Number.parseInt(bar); // ok
let baz = undefined; // ok
```
Global variables declared in the same source code will be still invalid:
```js
/* eslint id-blacklist: ["error", "foo"] */
var foo = 1; // error
foo = 2; // error
```
This will be still invalid although it is a reference to a global variable, because it also represents a property name:
```js
/* eslint id-blacklist: ["error", "undefined"] */
var foo = { undefined };
```
> Fix: allow references to external globals in id-blacklist (fixes #12567)

- docs/rules/no-use-before-define.md
updated docs example for `variables` option in `no-use-before-define` rule. 
fixes https://github.com/eslint/eslint/issues/12986
https://github.com/eslint/eslint/issues/12986
> Docs: clarify variables option in no-use-before-define (fixes #12986)

- lib/linter/node-event-generator.js
- package.json
- webpack.config.js
Upgrade `esquery` to `1.2.0`
Upgraded `esquery` to `1.2.0` and fixed some problems.
This version has been released today and is causing ESLint builds to fail, for two reasons:
1. Errors thrown by `esquery.parse` do not have `offset` property anymore, I think this was a change in [pegjs](https://github.com/pegjs/pegjs).
Some tests were (correctly) failing because of this. It's fixed by using `err.location.start.offset`.
2. `esquery` now distributes ESM modules, too.
Webpack by default looks for `"module"` (ESM) first. Unfortunately, [that module](https://github.com/estools/esquery/blob/master/esquery.js) is using `export default`, which turns `require("esquery")` into something like:
```js
{ default: { parse, match, matches, query } }
```
instead of expected: …
> Upgrade: esquery@1.2.0

- docs/rules/no-obj-calls.md
- lib/rules/no-new-wrappers.js
- lib/rules/no-obj-calls.js
- tests/lib/rules/no-new-wrappers.js
- tests/lib/rules/no-obj-calls.js
Note: this PR also removes `Math` and `JSON` from the `no-new-wrappers` rule.
`no-obj-calls`
more
```js
/*eslint no-obj-calls: "error"*/
/*eslint-env es2017*/
var newMath = new Math();
var newJSON = new JSON();
var newReflect = new Reflect();
var newAtomics = new Atomics();
```
no errors
4 errors
Updated `no-obj-calls` to warn on `NewExpression` as well.
As suggested in [#11984 …
> Update: Report constructor calls in no-obj-calls

- lib/rules/no-extra-boolean-cast.js
- tests/lib/rules/no-extra-boolean-cast.js
[X] Bug fix
* **ESLint Version:** v7.0.0-alpha.2
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZXh0cmEtYm9vbGVhbi1jYXN0IDogXCJlcnJvclwiKi9cblxuaWYgKEJvb2xlYW4oYSA/IGIgOiBjKSA/IGQgOiBlKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) (v6.8.0)
```js
/*eslint no-extra-boolean-cast : …
```
> Fix: incorrect logic for required parens in no-extra-boolean-cast fixer

- lib/rules/no-prototype-builtins.js
- tests/lib/rules/no-prototype-builtins.js
refs #12334
This PR adds `loc.end` to reports in `no-prototype-builtins`.
Just a small change from `loc.start` to `loc`.
> Fix: add end location to report in no-prototype-builtins (refs #12334)

- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
As mentioned in #13025, I added checking assignment property target in destructuring
This PR, Fixes #13025
> Fix: check assignment property target in camelcase (fixes #13025)

- lib/rules/no-implied-eval.js
- tests/lib/rules/no-implied-eval.js
[x] Other, please explain: support globalThis in no-implied-eval
make support `globalThis` in no-implied-eval
#12670
> Update: support globalThis in no-implied-eval (fixes #12670)

- lib/rules/operator-linebreak.js
- tests/lib/rules/operator-linebreak.js
refs #12334
This PR slightly changes reported location in the `operator-linebreak` rule.
It shouldn't produce any new warning possibly caused by the position of `eslint-disable-*` comments, because it doesn't change `start.line`.
The rule will now report the full operator's location with `start` and `end`, instead of just its `end` location as the error's location.
> Update: report operator location in operator-linebreak (refs #12334)

- lib/rules/no-extra-bind.js
- tests/lib/rules/no-extra-bind.js
refs #12334
This PR adds `loc.end` to reports in `no-extra-bind`.
Just a small change from `loc.start` to `loc`.
> Fix: add end location to report in no-extra-bind (refs #12334)

- lib/rules/utils/ast-utils.js
- tests/lib/linter/linter.js
- tests/lib/rules/no-redeclare.js
- tests/lib/rules/no-unused-vars.js
refs #12334
This PR modifies `astUtils.getNameLocationInGlobalDirectiveComment` in order to add end location to reports in two rules:
* `no-redeclare`
* `no-unused-vars`
`astUtils.getNameLocationInGlobalDirectiveComment` used to return `{ line, column }`.
After this change, return value will be `{ start: { line, column }, end: { line, column }  }`
> Fix: getNameLocationInGlobalDirectiveComment end location (refs #12334)

- docs/rules/require-await.md
- lib/rules/require-await.js
- tests/lib/rules/require-await.js
Fixes https://github.com/eslint/eslint/issues/12459
after this change, `require-await` rule won't check for async generator functions . So an async generator function having no await wont report any error
https://github.com/eslint/eslint/issues/12459
> Fix: require-await ignore async generators (fixes #12459)

- lib/cli-engine/cli-engine.js
- tests/lib/cli-engine/cli-engine.js
Addresses issue #12873 
I adjusted the logic that determines what message to send when a file is ignored.
> Fix: Change error message logic for implicit file ignore (fixes #12873)

- lib/rules/template-curly-spacing.js
- tests/lib/rules/template-curly-spacing.js
Changes `template-curly-spacing` report locations.
* For missing spaces the rule will now report the full location of `${` or `}`
* For disallowed spaces the rule will now report the location of spaces (the range that should be removed).
`"always"` before this change:
`"always"` after this change:
`"never"` before this change:
`"never"` after this change:
Also:
* Refactoring - locations are now also different depending on the option, so the code became difficult to follow with two branches in every line.
* Replaced regexes with `.startsWith()` and `.endsWith()`.
* Replaced call to deprecated `isSpaceBetweenTokens` with `isSpaceBetween`
* Refactoring.
* Checks whether `prevToken`/`nextToken` exists or not are removed. I believe they were not necessary (in the …
> Update: Improve report location for template-curly-spacing

- docs/rules/no-magic-numbers.md
- lib/rules/no-magic-numbers.js
- tests/lib/rules/no-magic-numbers.js
[X] Bug fix #12845
This bug fix produces **more** warnings.
`no-magic-numbers` with option `ignoreArrayIndexes: true` was allowing all numbers `x` in `a[x]`, assuming they're array indexes, like:
`a[-1], a[2.5], a[1e500] ...`
This PR changes the `ignoreArrayIndexes` option to allow only those numbers that will result in a valid array index name: `"0", "1" ... "4294967294"`.
All notations are still allowed, as long as the expression evaluates and coerces to a valid index.
I also renamed some unrelated functions and removed some extra params.
Added max array length check, too. That wasn't mentioned in the original issue, is it okay?
> Update: stricter array index check in no-magic-numbers (fixes #12845)

- lib/rules/no-empty-function.js
- tests/lib/rules/no-empty-function.js
refs #12334
Change reported location in the `no-empty-function` rule.
This shouldn't produce any new warnings because it doesn't change the start line.
The rule will now report the full function's body location (highlights the whole empty block), instead of just its start.
Before:
After:
This is consistent with the `no-empty` rule.
An alternative could be to report the location of `{` only.
> Update: Improve report location for no-empty-function (refs #12334)

- docs/rules/no-inner-declarations.md
- lib/rules/no-inner-declarations.js
- tests/lib/rules/no-inner-declarations.js
fixes https://github.com/eslint/eslint/issues/12222
Currently whenever the distance is more than 1, it was not showing error cause it was considering ancestor as any (`Program` included). 
it will be valid only if ancestor is not `Program` for distance equal to 2
example
```js
if(foo){
var a;
}
```
this will result in …
> Update: no-inner-declarations false negative in non-block (fixes #12222)

- lib/rules/comma-style.js
- tests/lib/rules/comma-style.js
refs #12334
Change the reported location in the comma-style rule. The rule will now report the full location of the comma token with `start` and `end`, instead of only `end` location.
> Update: Improve report location for comma-style

- lib/rules/no-useless-concat.js
- tests/lib/rules/no-useless-concat.js
refs #12334
This PR adds `loc.end` to reports in `no-useless-concat`.
Just a small change from `loc.start` to `loc`.
> Fix: add end location to report in no-useless-concat (refs #12334)

- docs/rules/no-new-object.md
- lib/rules/no-new-object.js
- tests/lib/rules/no-new-object.js
fixes #12809
added a no check for shadow `Object` calls 
#12809
I didn't use the `referenceTracker` as mentioned in the issue to avoid further bugs.
> Fix: no check for shadowed Object (fixes #12809)

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
When the autofixer outputs broken code, the rule tester rightfully hard fails the test.
However, the error current message can be pretty vague as it relies upon the error message from the parser. Some of the parser errors can be explicit and easy to trace, and others can be useless without an error location.
For example, the following invalid code
```js
'const a = "1";`'`
```
Produces this error message in both espree and typescript-eslint
```
Unterminated template literal.
```
Which results in this test failure:
```
A fatal parsing error occurred in autofix: Parsing error: Unterminated template literal.
```
This is especially problematic for fixer failure, because you cannot actually see the fixer output anywhere. So the above error message is impossible to …
> Update: Improve error message for fatal fixer errors

- lib/rules/space-before-function-paren.js
- tests/lib/rules/space-before-function-paren.js
refs #12334.
1. Add end location for cases with extra space.
2. Change the report location to that of opening parenthesis for cases with missing space.
```js
// Before
/* eslint space-before-function-paren: [2, 'never'] */
function foo () {}
//       ~~~   vscode highlight
/* eslint space-before-function-paren: [2, 'always'] */
function foo() {}
//       ~~~   vscode highlight
// Now
/* eslint space-before-function-paren: [2, 'never'] */
function foo () {}
//          ~   vscode highlight
/* eslint space-before-function-paren: [2, 'always'] */
function foo() {}
//          ~   vscode highlight
```
> Update: Improve report location for space-before-function-paren

- lib/rules/newline-per-chained-call.js
- tests/lib/rules/newline-per-chained-call.js
refs #12334
Change reported location in the `newline-per-chained-call` rule.
This shouldn't produce any new warnings because it doesn't change the start line.
Changed location to the full location of `.` or `[`, instead of start location of the `property` node.
Before:
After:
This looks like a big visual change. I chose this among many alternatives because it matches the place where the fixer inserts newline, and it's a common place to insert the newline manually (either on the left or on the right side). Also, the message starts with `.`/`[`
> Update: Improve report location newline-per-chained-call (refs #12334)

- docs/rules/spaced-comment.md
Updated the `exceptions` definition for new line issue
fixes #13032
> Docs: clarify exceptions in spaced-comment (fixes #13032)

- docs/rules/no-return-assign.md
- tests/lib/rules/no-return-assign.js
Added incorrect and correct example using arrow function in docs to represent the parenthesis position.
fixes #13135
> Docs: examples with arrow functions in no-return-assign (fixes #13135)

- lib/init/autoconfig.js
- tests/lib/init/autoconfig.js
Fix #12707. It still has a `triage label` but I can reproduce it 
reproduced - https://github.com/yeonjuan/autoconfbug
The cause of the …
> Fix: init error in extending recommended config (fixes #12707)

- lib/rules/new-cap.js
- tests/lib/rules/new-cap.js
refs #12334
Add end location to reports in the `new-cap` rule.
Changed location to the full location of `callee` (or callee's `property` if it is a `MemberExpression`), instead of just their start locations.
In VS Code, this change is observable with computed properties:
Before:
After:
> Update: Improve report location for new-cap (refs #12334)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[X] Bug fix
* **ESLint Version:** v7.0.0-alpha.2
default
<details>
```js
sourceType: "module"
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogXCJlcnJvclwiKi9cblxuZXhwb3J0IGRlZmF1bHQgKGEsIGIpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) (v6.8.0)
```js
/* eslint …
```
> Fix: no-extra-parens export default sequence expression false positive

- docs/rules/no-inner-declarations.md
Fixes wrong eslint configuration in correct examples for the `no-inner-declarations` rule with the `"both"` option.
Fixed eslint directive comment.
> Docs: fix eslint comment in no-inner-declarations examples

- docs/rules/curly.md
refs #12972
Fixed `multi-or-nest` examples with preceding comments in the `curly` rule to match the actual behavior and added a note to clarify the logic.
> Docs: fix curly multi-or-nest examples with comments (refs #12972)

- package.json
- tests/lib/linter/linter.js
fixes #9366
This PR upgrades `levn` to `0.4.1` to fix the issue of backslashes in strings not being escaped correctly in inline directive comments.
Am I missing anything? Apologies - I know the tests are difficult to read.
> Upgrade: levn@0.4.1 (fixes #9366)

- lib/cli-engine/config-array/ignore-pattern.js
- tests/lib/cli-engine/config-array/ignore-pattern.js
> Fix: newBasePath should be an absolute path (fixes #12850)

- tests/lib/rules/array-element-newline.js
[X] Other, please explain: `tests`
Added a bit complex tests cases for nested array cases 
None
> Chore: nested array tests for array-element-newline

- lib/init/config-initializer.js
- tests/lib/init/config-initializer.js
Chore
This is a small PR that utilizes `espree.latestEcmaVersion` in the config initializer so that we don't have to manually update this each time we add a new version to the parser.
This value will change as soon as we update to a version of Espree with a new supported `ecmaVersion`. Is that undesirable for any …
> Chore: use espree.latestEcmaVersion in config-initializer

- lib/rules/getter-return.js
- tests/lib/rules/getter-return.js
refs #12334
Change reported location in the `getter-return` rule.
This change can produce **more** warnings in existing code, depending on the location of `eslint-disable-*` comments.
The rule will now use `astUtils.getFunctionHeadLoc` instead of its own code for the reported getter's location.
Some notable differences
Before:
After:
In edge cases where `get` and the opening paren are not on the same line, this change can produce more warnings. For example, the following code will be invalid now:
```js
/* eslint getter-return: error */
var x = {
get 
foo () {} // eslint-disable-line getter-return 
};
```
> Update: Improve report location for getter-return (refs #12334)

- lib/options.js
- tests/lib/options.js
* **ESLint Version:** `7.0.0-alpha.3`
* **Node Version:** `13.11.0`
* **npm Version:** `6.13.7`
<details>
```js
"use strict";
root: true,
plugins: [
"markdown",
"react"
],
extends: ["eslint:recommended"],
overrides: [
{
files: [".eslintrc.js"],
env: {
node: true
}
},
{
files: ["**/*.md"],
processor: "markdown/markdown"
},
{
files: ["**/*.md/*.jsx"],
env: {
browser: true,
es6: true
},
globals: {
React: false
},
extends: ["plugin:react/recommended"],
ecmaFeatures: {
jsx: true …
```
> Fix: Remove default .js from --ext CLI option

- .github/workflows/ci.yml
Run tests on Node.js v14
Add Node.js v14, remove v13 , v12 on `windows` and `macOS`
Not much
> Chore: Run tests on Node.js v14

- lib/rules/func-call-spacing.js
- tests/lib/rules/func-call-spacing.js
[X] Bug fix
fixes #13190
`func-call-spacing` will be reporting the following messages:
* "Unexpected whitespace between function name and paren." if the option is `"never"` and there is any whitespace (including spaces and newlines) between function name and paren.
* "Unexpected newline between function name and paren." if the option is `"always"`, `"allowNewlines"` is set to `false`, and there is a newline between function name and paren. 
This reverts change in the message text made in #10764, plus changes "space" to "whitespace" in the message for `"never"`.
> Fix: func-call-spacing "never" reports wrong message (fixes #13190)

- lib/rules/no-unexpected-multiline.js
- tests/lib/rules/no-unexpected-multiline.js
refs #12334
Change reported location in the `no-unexpected-multiline` rule.
For tagged template literals, this change can produce **more** warnings in existing code, depending on the location of `eslint-disable-*` comments.
* Tagged template literals: rule will now report template literal's backtick location, instead of tag's start location. This is consistent with other node types.
* All other nodes: rule will now report the full location of `(`, `[`, `/`, instead of just their start locations.
Before:
After:
An existing code like the following will have a `no-unexpected-multiline` error after this change:
```js
/* eslint no-unexpected-multiline: ["error"] */
// eslint-disable-next-line no-unexpected-multiline
a
`b`
```
Other changes:
* `data` isn't used in …
> Update: report backtick loc in no-unexpected-multiline (refs #12334)

- lib/rules/array-callback-return.js
- tests/lib/rules/array-callback-return.js
refs #12334
Change reported location in the `array-callback-return` rule.
The rule will now use `astUtils.getFunctionHeadLoc` instead of its own code for the reported function's location.
Differences:
* Arrow functions
* Start loc is unchanged (start loc of `=>`).
* End loc will be the end loc of `=>`, instead of nothing.
* Anonymous function expressions 
* Start loc is unchanged (start loc of the function node).
* End loc will be start loc of the opening paren of params, instead of nothing.
* Named function expression: 
* Start loc will be start loc of the function node, instead of the function's name. 
* End loc will be start loc of the opening paren of params, instead of nothing.
In edge cases where `function` and its name are not on the same line this change …
> Update: Improve report location for array-callback-return (refs #12334)

- docs/user-guide/migrating-to-7.0.0.md
> Don't merge until we finished releasing the last one of 6.x.
This PR adds the draft of migration guide for 7.0.0. The purpose is to reduce the conflict of breaking change PRs.
Please correct the sentences.
> Docs: add migration guide

- docs/user-guide/migrating-to-7.0.0.md
Looks like we missed one in the initial PR. Quick fix for consistency! 
> Docs: update 7.0.0 migration guide for consistency

- Makefile.js
Chore
Our current https://eslint.org/docs/rules/ page has broken links to rules that were added in the current prerelease because it updates the website repo's `_data/rules.yml` data file during prereleases (while outputting all the prerelease documentation to `docs/7.0.0/` in the eslint/website repo). I _think_ this …
> Chore: fix rules list for prereleases

- Makefile.js
- conf/category-list.json
https://eslint.org/docs/rules/#node-js-and-commonjs no longer has any rules since they all been deprecated. Going forward, this should be fixed by https://github.com/eslint/eslint/pull/13230. I'll make another PR to the website repo to update the currently published site.
Am I missing anything?
> Fix: remove Node.js and CommonJS category from build process

- lib/rules/callback-return.js
- lib/rules/global-require.js
- lib/rules/handle-callback-err.js
- lib/rules/no-buffer-constructor.js
- lib/rules/no-mixed-requires.js
- lib/rules/no-new-require.js
- lib/rules/no-path-concat.js
- lib/rules/no-process-env.js
- lib/rules/no-process-exit.js
- lib/rules/no-restricted-modules.js
- lib/rules/no-sync.js
The [deprecated rules](https://eslint.org/docs/rules/#deprecated) currently link to broken links. 
Following up on https://github.com/eslint/website/pull/727 (which fixes the site immediately), and since we don't want to be in the business of keeping track of custom plugins, this PR removes the `replacedBy` elements for …
> Fix: remove custom plugins from replacedBy metadata

- tests/lib/rules/require-await.js
Fixes syntax error in two test cases for `require-await`.
These errors are causing build failure with the latest acorn v7.2.0, see PR #13275.
Added parens around arrow function in `await`.
> Chore: fix invalid syntax in require-await tests

- lib/init/config-initializer.js
- tests/lib/init/config-initializer.js
[X] Other, please explain: `init` flag refactor
added `"plugin:@typescript-eslint/recommended"` to extend configs when typescript prompt is `true`. 
fixes https://github.com/eslint/eslint/issues/13233
ref https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs
> As noted in the root README, …
> Update: added typescript-eslint/recommended configs for init

- docs/rules/no-return-await.md
this is a resubmit of https://github.com/eslint/website/pull/716 but to the correct repo ☺️ 
First of all, I know that there have been a lot of discussions on wether this rule is a good one or not. I do not want to bring up that discussion here at all. I just want to clarify the documentation to better explain the …
> Docs: improve documentation of no-return-await

- lib/source-code/source-code.js
Update source-code.js `getComments` method:
Program node [exclude leading and trailing comments from our range](https://github.com/eslint/espree/blob/master/lib/espree.js#L156), and i add special conditions, when given node has parent Program, leading and trailing comments tokens always belong to this node
> Chore: Mark SourceCode getComments() method as deprecated (fixes #13293)

- .github/PULL_REQUEST_TEMPLATE.md
Chore
I added these checkboxes, hoping that it would make it clear to PR authors that we have a consensus-seeking process in place. It seems like most people don't read past the first sentence, though, and therefore don't check the box. Since it's not serving its purpose, I'd like to propose we remove it.
Nothing in …
> Chore: remove checkbox from PR template prerequesites

- lib/rules/linebreak-style.js
- tests/lib/rules/linebreak-style.js
refs #12334
Change reported location in the `linebreak-style` rule.
Added start of the next line as the `end` location.
> Update: Improve report location for linebreak-style (refs #12334)

- lib/linter/linter.js
- tests/fixtures/parsers/linter-test-parsers.js
- tests/fixtures/parsers/non-js-parser.js
- tests/lib/linter/linter.js
Updated code path analyzer to bail if no known ESTree nodes are found in AST. I'm trying to get ESLint to work with syntaxes other then ESTree and this is one place where it throws an error, since all the AST nodes are hardcoded in code-path-analyzer and can't be supplied by the parser. Unfortunately, it would be very …
> Fix: Stop path analyzer on unknown nodes

- lib/rules/rest-spread-spacing.js
- tests/lib/rules/rest-spread-spacing.js
refs #12334
Change reported location in the `rest-spread-spacing` rule.
For `"always"`, the rule will now report the full location of the rest/spread operator, instead of only its end location.
For `"never"`, the rule will now report range between the rest/spread operator and the following token, instead of only the end location of the rest/spread operator.
`"always"` before this change:
`"always"` after this change:
`"never"` before this change:
`"never"` after this change:
> Update: Improve report location for rest-spread-spacing (refs #12334)

- .github/ISSUE_TEMPLATE/NEW_RULE.md
- docs/developer-guide/contributing/new-rules.md
Updated the new rules policy to reflect recent decision.
Spelling. :)
> Docs: Update new rules policies

- lib/rules/no-new-func.js
- tests/lib/rules/no-new-func.js
[x] Bug fix
Previously this rule doesn't check `Function` identifier via scope manager, which causes false positives. This PR fixes this.
[Online demo with the rule that has bug.](https://eslint.org/demo#eyJ0ZXh0IjoiY2xhc3MgRnVuY3Rpb24ge31cbmxldCBmID0gbmV3IEZ1bmN0aW9uKCkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLW5ldy1mdW5jIjoyfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)
Nothing.
> Fix: fix false positives of no-new-func

- lib/rules/semi-spacing.js
- tests/lib/rules/semi-spacing.js
Updated the location when is there unexpected space (both for before and after)
Currently 
```js
var a = 'b'   ;
//  ^ it will report here instead of the spaces
```
with this change
```js
var a = 'b'   ;
// ^^^  it will report here
```
For missing space it currently reports 
```js
var a = 'a';var b = 'b';
//  ^ it …
```
> Update: reporting location for semi-spacing (refs #12334)

- docs/rules/arrow-parens.md
- lib/rules/arrow-parens.js
- tests/lib/rules/arrow-parens.js
**rule: `arrow-parens`**
no reporting when there are comments inside params. 
applicable for `as-needed` option for 
Example of valid code [(these are invalid in master as of now)](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyb3ctcGFyZW5zOiBbXCJlcnJvclwiLCBcImFzLW5lZWRlZFwiXSovXG5cblxuY29uc3QgZiA9ICgvKiogQHR5cGUge …
> Fix: arrow-parens no reporting for comments inside (fixes #12995)

- lib/rules/no-new-symbol.js
- tests/lib/rules/no-new-symbol.js
* **ESLint Version:** v7.0.0
default
<details>
```js
}
}
```
</details>
[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbmV3LXN5bWJvbDogXCJlcnJvclwiKi9cbi8qZXNsaW50LWVudiBlczYqL1xuXG5uZXcgZm9vKFN5bWJvbCk7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOn …
> Fix: no-new-symbol false positive with Symbol as an argument

- lib/rules/one-var-declaration-per-line.js
- tests/lib/rules/one-var-declaration-per-line.js
ref #12334
added loc.end to report in  `one-var-declaration-per-line`.
> Fix: report end loc in one-var-declaration-per-line (refs #12334)

- docs/rules/max-lines-per-function.md
- lib/rules/max-lines-per-function.js
- tests/lib/rules/max-lines-per-function.js
Fixes #13332.
Include a check if the node is an `ArrowFunctionExpression` in `isIIFE` in max-lines-per-function.
No.
> Fix: max-lines-per-function flagging arrow IIFEs (fixes #13332)

- lib/rules/padded-blocks.js
- tests/lib/rules/padded-blocks.js
**BEFORE**
- `always`
- `never`
**AFTER**
- `always`
- `never`
refs #12334
> Update: padded-blocks loc position changes (refs #12334)

- lib/rules/utils/ast-utils.js
- tests/lib/rules/comma-dangle.js
- tests/lib/rules/semi.js
- tests/lib/rules/utils/ast-utils.js
[X] Bug fix
* **ESLint Version:** v7.0.0
default
<details>
```js
}
}
```
</details>
CRLF after `foo` and `bar`
```js
/*eslint semi: error*/
foo
bar
```
Two errors with the following locations (1-based lines and 1-based columns):
* `foo`: "line":3,"column":4, "endLine":4,"endColumn":1
* `bar`: "line":4,"column":4, "endLine":5,"endColumn":1
**What actually happened? Please include the actual, raw output …
> Fix: astUtils.getNextLocation returns invalid location after CRLF

- lib/rules/no-mixed-spaces-and-tabs.js
- tests/lib/rules/no-mixed-spaces-and-tabs.js
This PR changes reported location in the `no-mixed-spaces-and-tabs` rule.
The rule used to always report the same column: 1 (0-based), which looks like a bug. Also, it didn't report `end` loc.
Now, it will report the range of the first space-tab or tab-space pair, so it will underline both the space and the tab.
> Update: Improve location for no-mixed-spaces-and-tabs (refs #12334)

- lib/cli-engine/cli-engine.js
- lib/cli-engine/config-array-factory.js
- lib/init/config-initializer.js
- lib/linter/config-comment-parser.js
- lib/rules/no-control-regex.js
- lib/rules/no-invalid-regexp.js
- lib/rules/no-misleading-character-class.js
- lib/rules/no-regex-spaces.js
- lib/rules/no-useless-backreference.js
- lib/rules/prefer-named-capture-group.js
- lib/rules/quote-props.js
- lib/rules/utils/ast-utils.js
- packages/eslint-config-eslint/default.yml
- tests/_utils/in-memory-fs.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/init/config-initializer.js
- tests/lib/init/source-code-utils.js
- tools/code-sample-minimizer.js
- tools/eslint-fuzzer.js
Updates `eslint-config-eslint`
Added `caughtErrors: "all"` to `no-unused-vars` in order to enforce omission of catch binding in cases where the caught error  would not be used.
Does this change make sense? Also, please verify that all supported Node versions support optional catch binding.
> Chore: update no-unused-vars caughtErrors in eslint-config-eslint

- lib/rules/template-tag-spacing.js
- tests/lib/rules/template-tag-spacing.js
refs #12334
Change reported location in the `template-tag-spacing` rule.
For `"always"`, the rule will now report the full location of the first token before the template literal, instead of just its start.
For `"never"`, the rule will now report range between the first token before the template literal and the template literal, instead of start of the first token before the template literal,
`"always"` before this change:
`"always"` after this change:
`"never"` before this change:
`"never"` after this change:
> Update: Improve report location for template-tag-spacing (refs #12334)

- lib/init/config-initializer.js
- tests/lib/init/config-initializer.js
Updates `--init` behavior.
`--init` will now enable the latest `es2020` env, instead of `es6` env + `es2017` globals.
Does it make sense to enable the latest es environment in new projects? `--init` is already setting the latest `ecmaVersion`.
> Update: enable es2020 environment in --init

- lib/rules/no-unused-expressions.js
- tests/lib/rules/no-unused-expressions.js
* **ESLint Version:** 7.1.0
* **Node Version:** 12.16.3
* **npm Version:** 6.14.5
<details>
```js …
```
> Fix: Ignore import expressions in no-unused-expressions rule

- lib/rules/multiline-ternary.js
- tests/lib/rules/multiline-ternary.js
[X] Bug fix
fixes #13195
This bug fix can produce **more** warnings for options `"always"` and `"always-multiline"`, and fewer warnings for option `"never"`. 
The rule will now treat parentheses around `test`, `consequent`, and `alternate` as a part of them.
The following added invalid tests for `"always"` and `"always-multiline"` would be valid without this change:
```js
"(a\n) ? b\n: c"
"((a)\n) ? b\n: c"
"a ? (\nb)\n: c"
"a ? (\n(b))\n: c"
"a\n? (b\n): c"
"a\n? ((b)\n): c"
"a\n? b : (\nc)"
"a\n? b : (\n(c))"
"(a\n) ? (\nb\n) : (\nc)"
"((a)\n) ? (\n(b)\n) : (\n(c))"
```
The following added valid tests for `"never`  would be invalid without this change:
```js
"(a\n) ? b : c"
"((a)\n) ? b : c"
"a ? (\nb) : c"
"a ? (\n(b)) : c"
"a ? (b\n) : c"
"a ? ((b)\n) : c"
"a ? b : (\nc)"
"a ? b : …
```
> Update: handle parentheses in multiline-ternary (fixes #13195)

- lib/rules/func-call-spacing.js
- tests/lib/rules/func-call-spacing.js
- `unexpectedWhitespace`
**before**
```js
fn ();
^
fn ();
^
fn
^
()
```
**after**
```js
// single white space
fn ();
^ < - both start and end
fn ();
^ < - both start and end
fn
^
()
^
// multiple white space
fn  ();
^^
```
- `missing` 
**before**
```js
fn();
^
```
**after**
```js
fn()
^^
```
- `unexpectedNewline` …
> Update: reporter loc of func-call-spacing (refs #12334)

- docs/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[X] Bug fix
Fixes #12870
This PR adds `enforceForFunctionPrototypeMethods` option to the `no-extra-parens` rule in order to avoid conflicts with `wrap-iife` `"functionPrototypeMethods": true`.
Examples of **correct** code:
```js
/* eslint no-extra-parens: ["error", "all", { "enforceForFunctionPrototypeMethods": false }] */
const foo = (function () {}).call();
const bar = (function () {}).apply();
const baz = (function () {}.call());
const quux = (function () {}.apply());
```
* Added the option.
* Also fixed the wrong IIFE example in the docs.
Yes! Should we add this option to `"functions"` schema, too? It doesn't have any options at the moment. That used to be a separate rule, but got merged in `no-extra-parens` at some point?
This is also a conflict:
```js
/* …
```
> Update: add enforceForFunctionPrototypeMethods option to no-extra-parens

- README.md
Added link to security policy to our README
Typos :)
> Docs: Add security policy link to README

- CHANGELOG.md
fix changelog
same as #13396 which got closed because of a linked PR
added new lines before changelog versions so they appear on their own lines.
Before:
After:
> Docs: Fix changelog versions

- lib/init/config-initializer.js
- tests/lib/init/config-initializer.js
`@typescript-eslint/recommended` now extends from `@typescript-eslint/eslint-recommended`:
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0
/cc @bradzacher 
Removed `@typescript-eslint/eslint-recommended` because it's no longer necessary.
No
> Update: Drop @typescript-eslint/eslint-recommended from `eslint --init`

- packages/eslint-config-eslint/default.yml
Set `exceptRange: true` for the `yoda` rule in  eslint-config-eslint.
Enabled the option in order to allow code such as this:
```js
0 <= value && value < MAX_ARRAY_LENGTH
```
I'm not entirely familiar with the semver policy for eslint-config-eslint. Just to note that this option doesn't enforce anything, so enabling it can produce only fewer warnings.
> Chore: enable exceptRange option in the yoda rule

- lib/rules/curly.js
- tests/lib/rules/curly.js
[X] Bug fix
This bug fix produces **more** warnings.
* **ESLint Version:** v7.0.0-alpha.1
default
<details>
```js
}
};
```
</details>
[Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGN1cmx5OiBbXCJlcnJvclwiLCBcIm11bHRpXCJdICovXG5cbmlmIChhKVxuICAgIGlmIChiKSB7XG4gICAgICAgIGZvbygpO1xuICAgIH1cblxuaWYgKGEpXG4gICAgaWYgKGIpXG4gICAgICAgIGZvbygpO1xuICAgIGVsc2Uge1xuICAgICAgICBiYXIoKTtcbiAgICB9IFxuXG5pZiAoYSlcbiAgICBpZiAoYilcbiAgICAgICAg …
> Update: curly should check consequent `if` statements

- lib/rules/comma-dangle.js
[X] Bug fix
fixes #13165
`comma-dangle` schema mistakenly allows specifying multiple options.
User might expect that this rule allows string option + specific overrides in an additional object option, because some other rules indeed have such configuration.
Added `additionalItems: false` in order to allow specifying only 1 option.
This change can break a build with an invalid configuration, which should be a good thing since it wasn't working as expected.
A similar change was treated as a semver-patch bug fix (#12639).
> Update: disallow multiple options in comma-dangle schema (fixes #13165)

- lib/rules/semi-spacing.js
- tests/lib/rules/semi-spacing.js
[X] Bug fix
This bug fix can produce **more** warnings.
* **ESLint Version:** v7.1.0
default
<details>
```js
}
}
```
</details>
[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHNlbWktc3BhY2luZzogXCJlcnJvclwiICovXG5cbmRvIHtcbn0gd2hpbGUoZm9vKSA7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)
```js
/* eslint semi-spacing: …
```
> Update: semi-spacing should check do-while statements

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Currently in test files for rules and internal rules, if a valid test case in added to invalid test case and have `errors` set to an empty array, it simply passes the test which should be an error as it is false negative. 
Added a check for empty-ness of the array and it will throw  error if the `errors` is empty array …
> Update: added empty error array check for false negative

- lib/rules/object-property-newline.js
- tests/lib/rules/object-property-newline.js
removed the `.start` of the reporting location to include both `start` and `end` as well.
Currently, the location of the key is being reported (both in master and in this PR)
Will it make sense to report the leading whitespace?
like this
by replacing the `loc`
```js
loc: {
start: comma.loc.end,
end: …
```
> Update: object-property-newline end location (refs #12334)

- lib/rules/max-lines.js
- tests/lib/rules/max-lines.js
Currently `max-lines` reports `1:1` for any numbers of line. 
In this change, it will report the extra lines which are causing the error.
Example :
It will report from (loc.start) `2` and till `(loc.end`) `3` (total lines)
refs #12334
***
This can be a bit more red lines as it will goes till eof.
One other option is …
> Update: max-lines reporting loc improvement (refs #12334)

- docs/rules/no-promise-executor-return.md
- lib/rules/index.js
- lib/rules/no-promise-executor-return.js
- tests/lib/rules/no-promise-executor-return.js
- tools/rule-types.json
[X] New rule 
fixes #12640
```js
/*no-promise-executor-return: "error"*/
new Promise((resolve, reject) => {
if (someCondition) {
return defaultResult;
}
getSomething((err, result) => {
if (err) {
reject(err);
} else {
resolve(result);
}
});
});
new Promise((resolve, reject) => getSomething((err, data) => {
if (err) {
reject(err);
} else {
resolve(data);
}
}));
new Promise(() => {
return 1;
});
```
`no-promise-executor-return` rule.
> New: Add no-promise-executor-return rule (fixes #12640)

- docs/rules/operator-linebreak.md
- lib/rules/operator-linebreak.js
[X] Bug fix
* **ESLint Version:** v7.0.0-alpha.3
default
<details>
```js
}
}
```
</details>
[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgb3BlcmF0b3ItbGluZWJyZWFrOiBbXCJlcnJvclwiLCBcImFmdGVyXCIsIHsgXCJvdmVycmlkZXNcIjogeyBcIitcIjogdHJ1ZSB9IH1dKi9cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)
```js
/*eslint …
```
> Update: fix operator-linebreak overrides schema

- lib/rules/id-match.js
- lib/rules/no-unused-vars.js
- lib/rules/padded-blocks.js
[X] Bug fix
* **ESLint Version:** v7.0.0-alpha.3
default
<details>
```js
}
}
```
</details>
[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgaWQtbWF0Y2g6IFtcImVycm9yXCIsIFwiXlthLXpdKyhbQS1aXVthLXpdKykqJFwiLCB7IFwiZm9vXCI6IHRydWUgfV0qL1xuLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJmb29cIjogdHJ1ZSB9XSAqL1xuLyplc2xpbnQgcGFkZGVkLWJsb2NrczogW1wiZXJyb3JcIiwgXCJuZXZlclwiLCB7IFwiZm9vXCI6IHRydWUgfV0gKi9cbiIsIm9wdGlvbnMiOnsi …
> Update: add missing `additionalProperties: false` to some rules' schema

- lib/cli-engine/config-array-factory.js
- tests/fixtures/config-file/cloned-config/configWithInfinity.js
- tests/lib/cli.js
When cloning a rule's config, if `Infinity` is found, it will be replaced with `Number.MAX_SAFE_INTEGER`. This should result in the same effective config while preserving serialization.
Note: This only fixes the issue introduced in v7.3.0. Configs using `Infinity` will still fail in other areas (like caching and …
> Fix: Replace Infinity with Number.MAX_SAFE_INTEGER (fixes #13427)

- docs/rules/prefer-regex-literals.md
- lib/rules/prefer-regex-literals.js
- tests/lib/rules/prefer-regex-literals.js
I’ve changed the rule `prefer-regex-literal` so that it detects regex literals that are passed to the `RegExp` constructor.
* I decided to implement an autofix yet, since the whole rule is not autofixable yet. I think it makes more sense to address this separately 
* ~~I have implemented the rule change as the new default behavior. Once a decision has been made in #12840 I’m happy to change the if necessary and move the new behavior behind an option~~ The new behavior is now implemented behind an option.
> Update: prefer-regex-literal detects regex literals passed to RegExp (fixes #12840)

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
[x] Other, please explain: #12334 
Change reporting location `loc.start` to `loc`.
* "always" option
* "never" option
* "always" option
* "never" option
> Update: improve report location in arrow-body-style (refs #12334)

- docs/rules/camelcase.md
- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
Added an option to ignore global variables in the camelcase rule.
Testing the change and add tests. …
> Update: Add option "ignoreGlobals" to camelcase rule (fixes #11716)

- docs/user-guide/configuring.md
Addresses issue #12348 
This is a small pull request that changes the logic for displaying an error message when a file is ignored by implicit ignore rules. The regular expression for detecting a …
> Docs: Clarify implicit ignore behavior for dotfiles

- docs/rules/no-multiple-empty-lines.md
fixes #13432
Reverted some changes from #13374. It seems that the last commit in that PR had some accidental auto-formatting changes that broke the examples in `no-multiple-empty-lines` documentation.
> Docs: fix no-multiple-empty-lines examples (fixes #13432)

- lib/rules/arrow-parens.js
- tests/fixtures/parsers/arrow-parens/generics-extends-complex.js
- tests/fixtures/parsers/arrow-parens/generics-extends.js
- tests/fixtures/parsers/arrow-parens/generics-simple-async.js
- tests/fixtures/parsers/arrow-parens/generics-simple-no-params.js
- tests/fixtures/parsers/arrow-parens/generics-simple.js
- tests/lib/rules/arrow-parens.js
[X] Bug fix
fixes #12570
Changed `arrow-parens` rule:
* Refactored the code.
* Changed the way it finds opening paren of params to, I believe, the most reliable one. This should prevent crashes, invalid autofixes, and some false positives in typescript code.
* Added check for unexpected tokens before opening paren. This should prevent false positives like `<T>(a) => b` with `"as-needed"` option.
* Also fixed an autofix bug with adjacent tokens, unrelated to typescript.
> Fix: support typescript generics in arrow-parens (fixes #12570)

- docs/rules/multiline-ternary.md
fixes #13368
Removed note that the option `"never"` is "enforcing that the entire ternary expression is on one line", because it doesn't work like that. Also added an example.
> Docs: fix description for `never` in multiline-ternary (fixes #13368)

- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
refs #12334
This PR adds `loc.end` to reports in the `keyword-spacing` rule.
changed `*.loc.start` to just `*.loc`.
> Fix: add end location to reports in keyword-spacing (refs #12334)

- lib/rules/object-curly-newline.js
- tests/lib/rules/object-curly-newline.js
refs #12334
This PR adds `loc.end` to reports in the `object-curly-newline` rule.
changed `*.loc.start` to just `*.loc`.
This is consistent with similar rules: `array-bracket-newline` and `function-paren-newline`.
> Fix: add end location to reports in object-curly-newline (refs #12334)

- lib/rules/max-len.js
- tests/lib/rules/max-len.js
refs #12334
This PR changes reported location in the `max-len` rule.
The rule will now underline the whole line (or the part that counts) instead of just its start.
> Update: Improve report location for max-len (refs #12334)

- lib/rules/no-unneeded-ternary.js
- tests/lib/rules/no-unneeded-ternary.js
refs #12334
This PR changes reported location in the `no-unneeded-ternary` rule.
This change can produce more warnings in certain cases with `eslint-disable-*` comments.
Reported location will be now the full location or the conditional expression, instead of the start loc of its consequent.
I believe it's more correct to report conditional expression's loc instead of consequent's loc, for two reasons:
* The whole conditional expression needs to be replaced with another expression (`!!b`).
* In the `b ? true : false` case, this expression isn't considered invalid by this rule only because of its consequent. If the alternate wasn't a boolean literal as well, this expression would be valid by this rule.
This change can …
> Update: Improve report location for no-unneeded-ternary (refs #12334)

- docs/rules/sort-imports.md
- lib/rules/sort-imports.js
- tests/lib/rules/sort-imports.js
fixes #12951
Added `allowSeparatedGroups` option to the `sort-imports` rule.
Examples of **correct** code for this rule with the `{ "allowSeparatedGroups": true }` option:
```js
/*eslint sort-imports: ["error", { "allowSeparatedGroups": true }]*/
import b from 'foo.js';
import c from 'bar.js';
import a from 'baz.js';
```
```js
/*eslint sort-imports: ["error", { "allowSeparatedGroups": true }]*/
import b from 'foo.js';
import c from 'bar.js';
// comment
import a from 'baz.js';
```
```js
/*eslint sort-imports: ["error", { "allowSeparatedGroups": true }]*/
import b from 'foo.js';
import c from 'bar.js';
quux();
import a from 'baz.js';
```
> Update: add allowSeparatedGroups option to sort-imports (fixes #12951)

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
Fixed the fixer for `in` operator being wrongly fixed. wrapping the whole body when there is an `in` operator. `inIn` method will check if the body has `in` operator or not. wrapping the whole as mentioned in the issue was decided.
fixes #11849
> Fix: arrow-body-style fixer for `in` wrap (fixes #11849)

- lib/rules/no-irregular-whitespace.js
- tests/lib/rules/no-irregular-whitespace.js
refs #12334
This PR improves reported location in the `no-irregular-whitespace` rule.
For irregular spaces, the rule with now report end loc of the sequence, so it will underline the irregular space(s) instead of the previous token.
For irregular linebreaks, the rule with now report start loc of the next line as the end loc, so it will underline the irregular linebreak instead of the previous token.
> Update: Improve report location no-irregular-whitespace (refs #12334)

- tools/code-sample-minimizer.js
- tools/eslint-fuzzer.js
Chore, replaces hard-coded ecmaVersion with `espree.latestEcmaVersion` in fuzzer.
Updated fuzzer and code sample minimizer.
> Chore: use espree.latestEcmaVersion in fuzzer

- docs/rules/id-blacklist.md
- lib/rules/id-blacklist.js
- lib/rules/index.js
- tools/rule-types.json
I noticed that in the haste to rename `id-blacklist` to `id-denylist`, `id-blacklist` was not deprecated.  This PR aims to mark `id-blacklist` as deprecated and document this change.
Regarding documentation, note that some tooling of tooling (well, tooling I use, anyway) expects the rule to have documentation matching …
> Update: deprecate id-blacklist rule

- CHANGELOG.md
changes `CHANGELOG.md`
Currently, it appears as if all changes after v7.1.0 were made in v7.4.0
Added missing linebreaks before v7.2.0, v7.3.0, and v7.3.1
I think the issue that causes this was fixed by eslint/eslint-release#39, but it hasn't been released yet.
> Docs: fix linebreaks between versions in changelog

- docs/developer-guide/working-with-rules.md
refs #13349
Updates sections about `meta.fixable` in the `working-with-rules` document.
Clarifies that ESLint throws an error if a fixable rule doesn't have `meta.fixable` property, instead of just not applying fixes.
> Docs: clarify behavior if `meta.fixable` is omitted (refs #13349)

- .eslintrc.js
- tests/tools/internal-rules/consistent-docs-url.js
- tools/internal-rules/consistent-docs-url.js
This PR enables `internal-rules/consistent-meta-messages`, which enforces existence of `meta.messages` in rules.
Enabled the rule in eslint codebase. 
Also updated `internal-rules/consistent-docs-url` to use `meta.messages`, as it was the only rule (out of all core and internal rules) that hasn't been updated yet.
> Chore: enable consistent-meta-messages internal rule

- README.md
I think we can now say that "ESLint has full support" for ECMAScript 2020.
Added `2020` to the list of supported ECMAScript versions in `README.md`.
> Docs: add ECMAScript 2020 to README

- lib/rules/no-duplicate-case.js
- tests/lib/rules/no-duplicate-case.js
fixes #13485
This PR changes `no-duplicate-case` rule to change from detecting duplicates comparing text to detecting duplicates comparing tokens, like `no-dupe-else-if` rule.
> Update:  Change no-duplicate-case to comparing tokens (fixes #13485)

- messages/extend-config-missing.txt
- messages/no-config-found.txt
- messages/plugin-conflict.txt
- messages/plugin-missing.txt
- messages/whitespace-found.txt
Updated the chatroom link output by error messages to point directly to the #help channel.
Did I miss any chatroom link instances?
I marked this as a bug because we were dropping people into the #welcome channel, but that was confusing to people. Feel free to mark as something other than a bug if that doesn't make …
> Fix: Update the chatroom link to go directly to help channel

- lib/cli-engine/formatters/checkstyle.js
- tests/lib/cli-engine/formatters/checkstyle.js
Run eslint with checkstyle format and .eslintignore.
```
$ eslint ./testdata/*.js -f=checkstyle
```
eslintignore warning should output line and column as 0 or do not output line and column fields.
**What …
> Fix: Do not output `undefined` as line and column when it's unavailable in checkstyle format

- docs/developer-guide/contributing/README.md
Currently the links would get redirected to home page of https://openjsf.org/
> Docs: fix broken links in developer guide

- lib/rule-tester/rule-tester.js
- tests/fixtures/testers/rule-tester/no-var.js
- tests/lib/rule-tester/rule-tester.js
refs #13349, fixes step 2 from [this comment](https://github.com/eslint/eslint/issues/13349#issuecomment-646729029).
This PR updates RuleTester to require `meta` property in fixable rules.
An `invalid` test case, where the rule being tested has fixed the given code, will now fail if the rule doesn't have `meta` property.
* `RuleTester` still doesn't check for `meta.fixable`, because linter already throws an error if the rule that provided a fix does have `meta` but doesn't have `meta.fixable`.
* ~This change doesn't affect legacy-format rules (functions). They will be still allowed to make fixes. I guess that was decided?~
* This change also affects legacy-format rules (functions). RuleTester will no longer allow fixable legacy-format rules.
* This change can …
> Update: require `meta` for fixable rules in RuleTester (refs #13349)

- package.json
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/init/config-file.js
- tests/lib/shared/config-ops.js
- tests/lib/shared/naming.js
- tests/lib/source-code/source-code.js
- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
https://github.com/eslint/eslint/issues/13287
- replaced usages of `leche.withData` with `Array.forEach` for tests
- replaced leche stubbed `fs` declarations
- hawk eyes for identifying any potential edge …
> Chore: remove leche (fixes #13287)

- lib/rules/indent.js
- tests/lib/rules/indent.js
fixes #13497 
Indent for async arrow function was not working as the first token in the async arrow function node is the `async` not the opening paren. So the condition [here](https://github.com/eslint/eslint/blob/master/lib/rules/indent.js#L1089) would not be truthy. 
So I added one more check for simply checking the …
> Fix: indent for async arrow functions (fixes #13497)

- docs/rules/padding-line-between-statements.md
refs #13561
Documentation for `"case"` and `"default"` specifiers in `padding-line-between-statements` may be misleading. It sounds like the rule will require/disallow blank lines before and after `case:` and `default:` lines, while these specifiers actually apply to whole clauses.
Changed the text for `"case"` and `"default"` specifiers, and added an example.
> Docs: clarify "case" specifier in padding-line-between-statements

- docs/rules/no-underscore-dangle.md
- lib/rules/no-underscore-dangle.js
- package.json
- tests/lib/rules/no-underscore-dangle.js
(fixes #12579 )
If there is an underscore at the beginning of the function parameter name, it will give a warning.
None
> Update: allowFunctionParams option in no-underscore-dangle (fixes 12579)

- docs/rules/operator-assignment.md
Added `**` and `**=` to the list of operators in `operator-assignment` rule docs, since the document explicitly lists all operators that are checked by this rule, except for these two.
> Docs: add exponentiation operators to operator-assignment documentation

- docs/developer-guide/nodejs-api.md
- docs/developer-guide/working-with-rules.md
…lons.
- [X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
Fixed a typo in the `developer-guide/working-with-rules#providing-suggestions` documentation - changed semicolumns to semicolons.
> Docs: Fix typo and missing article before noun in docs

- docs/rules/object-curly-newline.md
The example of correct/incorrect really helpful to user.
So if not match between these two, can give confusion.
When I was reading in `object-curly-newline` docs there was not matching example in case of `consistent`.
I'm not sure that I correctly added example in correct case. So I ask to review to focus on pair …
> Docs: fix examples in object-curly-newline

- lib/rules/no-warning-comments.js
- tests/lib/rules/no-warning-comments.js
Added data in the error message which will show the comment itself. 
It will only show till 30 characters
Is `30` is fine ? after `30` char it will be truncated.
> Update: add comment to message in no-warning-comments (fixes #12327)

- docs/rules/id-length.md
- lib/rules/id-length.js
- tests/lib/rules/id-length.js
[issue #113094](https://github.com/eslint/eslint/issues/13094)
I continued the [PR #13099](https://github.com/eslint/eslint/pull/13099)
>to quote from  #13099
>>I added an option named exceptionPatterns to id-length, which takes as value an array of the allowed patterns.
>>If the option is not defined it takes an empty …
> Update: Add exceptionPatterns to id-length rule (fixes #13094)

- lib/rules/prefer-numeric-literals.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/dot-location.js
- tests/lib/rules/dot-notation.js
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-whitespace-before-property.js
- tests/lib/rules/prefer-numeric-literals.js
- tests/lib/rules/quote-props.js
- tests/lib/rules/utils/ast-utils.js
refs #13568
Adds support for numeric separators (along with PR #13574).
* Updated the regex used by `astUtils.isDecimalInteger` and `isDecimalIntegerNumericToken`. Also added tests for these helpers and some tests for rules that are using them.
* Added tests for `prefer-numeric-literals` and `quote-props` rules.
In total, this is one line of code + tests and comments.
* ~`package.json` should be updated before merging.~
* The other part of the changes for numeric separators is in #13574. I think these two PRs cover all that should be updated for numeric separators in this repository, but it would be good to double-check that.
> Update: support numeric separators (refs #13568)

- docs/user-guide/configuring.md
- lib/init/config-initializer.js
- tests/bin/eslint.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/init/config-initializer.js
- tests/lib/rules/no-extend-native.js
- tests/lib/rules/no-undef.js
refs #13602
* ~Added new `es2021` environment with `FinalizationRegistry` and `WeakRef` globals.~ edit: this is in `@eslint/eslintrc` now.
* Updated `--init` to enable the new environment in created configs.
* Updated `configuring.md` with the new environment.
* ~Also updated `configuring.md` and `types.js` with `ecmaVersion: 2021`.~ edit: done in #13609
* Also updated some tests where it seemed the intention was to use the latest es environment and/or the latest ecmaVersion. If that wasn't the case, I can revert those changes.
* ~`package.json` has github `espree` reference.~
* Noticed while rebasing at the end that this PR changes some files @nzakas just marked as "do not modify".
> Update: add es2021 environment (refs #13602)

- tests/lib/rules/no-dupe-keys.js
Add additional rule tests for numeric separators as part of #13568.
This adds tests for numeric literal object keys that aren't digit-only decimal integer literals, including ES6 binary and octal literals, ES2020 bigint literals, and ES2021 numeric separators. The valid tests have similar-looking literals that are distinct keys, and the invalid tests have differently-formatted literals that result in duplicate keys.
This is in addition to #13574 and #13581. Are there any other rules that might be affected?
> Chore: Test formatted integers in no-dupe-keys (refs #13568)

- docs/rules/operator-assignment.md
- lib/rules/constructor-super.js
- lib/rules/operator-assignment.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/func-name-matching.js
- tests/lib/rules/no-bitwise.js
- tests/lib/rules/no-extend-native.js
- tests/lib/rules/no-invalid-this.js
- tests/lib/rules/no-param-reassign.js
- tests/lib/rules/no-throw-literal.js
- tests/lib/rules/operator-assignment.js
- tests/lib/rules/operator-linebreak.js
- tests/lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-promise-reject-errors.js
- tests/lib/rules/space-infix-ops.js
- tests/lib/rules/utils/ast-utils.js
refs #13569
Changes the following rules and helper functions in order to support logical assignments:
* `operator-assignment` rule to NOT report `&&=`, `||=`, and `??=` for now.
* `astUtils.couldBeError` to return `true` for code such as `foo &&= 5`. Also, to return `false` for code such as `foo += bar` (this change can produce more warnings).
* `constructor-super` to treat classes such as `class A extends (B &&= 5)` as those that extend a constructor. Also, to treat classes such as `class A extends (B += C)` as those that don't extend a constructor (this change can produce more warnings).
Fixed the above, and also added tests for: `operator-linebreak`, `space-infix-ops`, `no-invalid-this`, `no-param-reassign`, `no-bitwise`, `func-names-matching`, …
> Update: support logical assignments in core rules (refs #13569)

- docs/rules/no-return-await.md
fixes #13656
* Added a comment above an example that could be misinterpreted.
* Also added missing eslint directives.
> Docs: clarify correct example in no-return-await (fixes #13656)

- lib/rules/id-length.js
- tests/lib/rules/id-length.js
This bug fix can produce **more** linting errors.
* **ESLint Version:** v7.8.1
default …
> Update: fix id-length false negatives on Object.prototype property names

- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
refs #13678, fixes `prefer-destructuring` to not remove comments. It doesn't change the logic of this rule.
* **ESLint Version:** v7.8.1
**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you …
> Fix: prefer-destructuring removes comments (refs #13678)

- docs/user-guide/getting-started.md
npx doesn't work properly with plugins installed with Yarn.
The installation guide might be slightly confusing for new users - e.g.: I use TypeScript in my project, I install `eslint` with yarn as the guide says, and then run it with `npx eslint --init`. It then fails with an error because the TypeScript plugin has been installed with yarn and `npx` doesn't see it:
```
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Cannot find module 'eslint'
```
This can be fixed by using `yarn run <cmd>` instead of `npx <cmd>`. This PR changes documentation to reflect this.
> Docs: Provide install commands for Yarn

- docs/user-guide/migrating-to-4.0.0.md
The void-style tags seem to not work as expected. The later migration guides avoid them. This patch updates the v4 guide to also avoid them.
| Screenshot in Firefox of [v4 migration guide](https://eslint.org/docs/user-guide/migrating-to-4.0.0) | View source warnings
|--|--
| <img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/91667858-94aac100-eaff-11ea-8cab-0573489376e8.png"> | <img width="300" alt="Screenshot 2020-08-30 at 20 26 26" src="https://user-images.githubusercontent.com/156867/91667898-c885e680-eaff-11ea-9bd8-83861942ef3d.png">
> Docs: Fix leaky anchors in v4 migration page

- docs/rules/lines-between-class-members.md
As it was, one of the examples in the `lines-between-class-members` rule article was not a valid JSON because it was missing quotes.
Nothing. This is a tiny contribution, easy to verify.
> Docs: Add missing quotes

- tests/lib/rules/getter-return.js
[X] Other, please explain: Move a comment in the `getter-return` test, so that the orders of tests will make sense.
Currently, a part of the `getter-return` tests look like:
https://github.com/eslint/eslint/blob/30b76c9a13fae3dff59f7db406d6c66f11152973/tests/lib/rules/getter-return.js#L221-L226
Seeing this, it is quite natural that we think …
> Chore: Move comment to make tests more organized

- docs/rules/prefer-destructuring.md
- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
* **ESLint Version:** v7.9.0
default
<details>
```js …
```
> Fix: prefer-destructuring invalid autofix with computed property access

- docs/rules/no-inline-comments.md
- lib/rules/no-inline-comments.js
- tests/lib/rules/no-inline-comments.js
Update: Add filtering to no-inline-comments and allow Webpack magic comments 
no-inline-comments 
Fewer
**How will the change be implemented?**
New default behaviour. 
```js
const language = import(/* webpackChunkName: "my-chunk-name" */'./locale/language');
```
Reports error/warning: `Unexpected comment inline with code.(no-inline-comments)`
Not report on this kind of comment anymore.
I added all the [Webpack magic comments](https://webpack.js.org/api/module-methods/#magic-comments] keywords to the …
> Update: Add ignorePattern to no-inline-comments

- docs/rules/lines-around-comment.md
- docs/rules/no-inline-comments.md
In #13029, the author based the docs on `ignorePattern` on `lines-around-comment`, which says the option should be a "regular expression". Here I update both places to clarify that the option should be a string that will be used to construct a regular expression.
> Docs: Clarify that ignorePattern should be a string (refs #13029)

- docs/rules/no-unmodified-loop-condition.md
- docs/rules/prefer-object-spread.md
- docs/rules/valid-typeof.md
I added missing configuration comments in the documents. It's quite useful for a quick demo :)
no.
> Docs: Add configuration comments in examples

- lib/rules/function-paren-newline.js
- tests/lib/rules/function-paren-newline.js
[x] Bug fix (fixes #13728)
Added support for the `async` ArrowFunctionExpression in `function-paren-newline`. This fixes the issue where source analysis for this node type wrongly assumes that it does not have an opening parenthesis (because it thinks that in this case, opening paren is always the first token, which since ES2017 is no longer a guarantee).
No
> Update: support async arrow fn in function-paren-newline (fixes #13728)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
* **ESLint Version:** v7.10.0
default
<details>
```js …
```
> Fix: account for linebreaks before postfix `++`/`--` in no-extra-parens

- docs/rules/max-lines.md
- lib/rules/max-lines.js
- tests/lib/rules/max-lines.js
* **ESLint Version:** v7.10.0
default
<details>
```js …
```
> Fix: don't count line after EOF in max-lines

- package.json
- tests/lib/cli-engine/cli-engine.js
Refactored a test
I removed the in-memory file system from the `CLIEngine` tests and replaced it with an actual filesystem. This is important for working on simple config because the in-memory filesystem does all kinds of complicated things to "fake" a filesystem, and it's impossible to reuse that to test that simple …
> Chore: Refactor CLIEngine tests (refs #13481)

- lib/rules/no-prototype-builtins.js
- tests/lib/rules/no-prototype-builtins.js
fixes #13088
Changed `no-prototype-builtins` rule to check computed property access and report simple cases like `foo["hasOwnProperty"]("bar")`.
Also refactored the test file so that the tests can be checked by `eslint-plugin-eslint-plugin` rules.
The removed TODO suggested to just replace all lines with …
> Update: check computed keys in no-prototype-builtins (fixes #13088)

- docs/rules/space-unary-ops.md
Updated docs for `space-unary-ops` to clarify that the `words` operators are only considered when a space is *not* required for proper syntax. 
This was previous confusing, as the "incorrect" examples were ones that had optional spaces (i.e. `delete(foo)`) while the "correct" examples were ones that required spaces …
> Docs: clarify that space-unary-ops doesn't apply when space is required

- tests/lib/cli-engine/cli-engine.js
- tests/lib/cli-engine/file-enumerator.js
- tests/lib/cli.js
- tests/lib/eslint/eslint.js
[x] Other, please explain: Fix GitHub Actions test flakiness
For the last several weeks, our CI jobs have been flaky due to test hook timeouts on the Windows and macOS runners. I traced most of the failures to four `before` hooks that copy the test fixtures to a temporary directory. They usually take ~2.5s, but that occasionally spikes to tens of …
> Chore: Increase Mocha timeout for copying fixtures

- docs/developer-guide/working-with-custom-formatters.md
[The correct name of the option to specify the output format is `--format`](https://github.com/eslint/eslint/blob/v7.11.0/lib/options.js#L169-L175), but it was described as `--formatter`, so it has been fixed.
Nothing. This is a tiny contribution.
> Docs: Fix the format option name in the document

- docs/user-guide/migrating-to-7.0.0.md
I fixed typo `no-magic-number` to `no-magic-numbers` in "Migrating to v7.0.0" page of documentation.
> Docs: Fix typo in v7 migration page

- docs/developer-guide/nodejs-api.md
I was reading the Node.js API page to learn about the `CLIEngine` deprecation and I noticed that most of the links in the table of contents don't work in the website. This PR only lowercase the link references to fix those links in the website.
This said, I'm aware that currently there is the opened PR #13415 but I …
> Docs: fix broken links in Node.js API docs

- lib/rules/constructor-super.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/no-throw-literal.js
- tests/lib/rules/prefer-promise-reject-errors.js
- tests/lib/rules/utils/ast-utils.js
---
*Bug report copied from #13634.*
* **ESLint Version:** 7.7.0
* **Node Version:** 14.9.0
* **npm Version:** 6.14.7
default
<details> …
> Update: Fix && vs || short-circuiting false negatives (fixes #13634)

- tests/lib/rules/no-func-assign.js
[ X ] Other, please explain: - test
Refers #13705
Added test cases for `no-func-assign`.
> Chore: add test case for no-func-assign (refs #13705)

- docs/rules/no-func-assign.md
fixes #13705
Added more example for `no-func-assign`
> Docs: add more examples for no-func-assign (fixes #13705)

- docs/rules/no-script-url.md
- lib/rules/no-script-url.js
- tests/lib/rules/no-script-url.js
Add template literal checking in no-script-url. :)
no
> Update: check template literal in no-script-url

- docs/developer-guide/working-with-rules.md
- lib/linter/report-translator.js
- tests/lib/linter/report-translator.js
fixes #13723
Marked this change as an "Update", because it can cause some existing tests in plugins to fail.
Modified `ReportTranslator` to automatically remove the whole suggestion instance from the linting output if the suggestion's `fix` function returned `null` or an empty array/sequence.
Context:
This change …
> Update: remove suggestion if it didn't provide a fix (fixes #13723)

- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
* **ESLint Version:** v7.11.0
default
<details>
```js …
```
> Fix: prefer-destructuring invalid autofix with comma operator

- lib/rules/yoda.js
- tests/lib/rules/yoda.js
* **ESLint Version:** v7.11.0
default
<details>
```js …
```
> Fix: yoda rule autofix produces syntax errors with adjacent tokens

- lib/rules/space-before-blocks.js
- tests/fixtures/parsers/space-before-blocks/return-type-keyword-1.js
- tests/fixtures/parsers/space-before-blocks/return-type-keyword-2.js
- tests/lib/rules/space-before-blocks.js
fixes #13553
This change can produce **more** warnings in TypeScript code. It shouldn't make any difference for JS code.
Currently, `space-before-blocks` reports error in the following code:
```js
/* eslint space-before-blocks: ["error", "always"] */
function foo(): string{} // error
```
But, it doesn't report an error …
> Update: skip keyword check for fns in space-before-blocks (fixes #13553)

- lib/cli-engine/file-enumerator.js
- tests/lib/cli-engine/file-enumerator.js
When `CLIEngine` instantiates `FileEnumerator`, it explicitly passes its own `CascadingConfigArrayFactory` instance, which now includes values for `builtInRules`, `loadRules`, `eslintRecommendedPath`, and `eslintAllPath`. This is the only place that ESLint core instantiates `FileEnumerator`, so core does not rely on the …
> Fix: Pass internal config paths in FileEnumerator default (fixes #13789)

- package.json
- tests/lib/eslint/eslint.js
The bulk of our tests for rule schemas are isolated unit tests of `ConfigValidator`. This is a single test to be sure we actually run rule schema validation end-to-end and prevent cases like #13793.
Here's my checklist for the patch release tomorrow. Am I missing anything?
> Upgrade: @eslint/eslintrc to fix rule schema validation (fixes #13793)

- docs/developer-guide/working-with-rules.md
- lib/linter/timing.js
- tests/lib/linter/timing.js
[X] Add a CLI option
Implements RFC: https://github.com/eslint/rfcs/tree/master/designs/2020-timing-list-size
Enables the `TIMING` environment variable to be set to a larger number or `all` in order to show a longer list of per-rule performance metrics when running eslint from the command line.
Interested to hear ideas for improving the …
> New: Configurable List Size For Per-Rule Performance Metrics

- docs/developer-guide/working-with-custom-formatters.md
Fix a minor JS typo in the custom formatter documentation sample for detailed formatter which causes a syntax error https://eslint.org/docs/developer-guide/working-with-custom-formatters#detailed-formatter
> Docs: Fix JS syntax and doc URL in working-with-custom-formatters.md

- lib/rules/no-useless-constructor.js
- tests/fixtures/parsers/typescript-parsers/declare-class.js
- tests/lib/rules/no-useless-constructor.js
Fixes #13830 
- Do not crash on parsers which do not require class constructor to have a body
Old implementation relies that class constructor has body. Added a check to verify this before accessing the object in order to prevent null pointer. 
As discussed on the ticket, it seems to be common practice to disable this …
> Fix: no-useless-constructor (#13830)

- tests/lib/rules/no-octal-escape.js
Removes `/* eslint no-octal-escape: 0 */` comment from the `no-octal-escape` test file.
I believe this was added when some tests mistakenly had octal escapes directly in `code` strings, instead of producing code with octal escapes (e.g., `"'\1'"` instead of `"'\\1'"`).
Removed the comment.
> Chore: remove eslint comment from no-octal-escape tests

- docs/rules/no-nonoctal-decimal-escape.md
- lib/rules/index.js
- lib/rules/no-nonoctal-decimal-escape.js
- tests/lib/rules/no-nonoctal-decimal-escape.js
- tools/rule-types.json
fixes #13765
Added `no-nonoctal-decimal-escape` rule, which disallows `\8` and `\9` in string literals.
> New: Add no-nonoctal-decimal-escape rule (fixes #13765)

- docs/rules/function-call-argument-newline.md
The documentation's descriptions of options for the `function-call-argument-newline` rule use "default" for the `"never"` and `"consistent"` options, although these options are not defaults. The only default is `"always"` for this rule. If a user reads these parts of the documentation, they might incorrectly expect their desired option of `"never"` or `"consistent"` to be the default value while the tool actually uses `"always"`.
Please ensure that the word "default" is correctly used throughout this document.
> Docs: correct the function-call-argument-newline 'default' descriptions

- lib/rules/no-irregular-whitespace.js
- tests/lib/rules/no-irregular-whitespace.js
fixes #13852
~This bug fix can produce only fewer errors.~
Aside from fixing false positive from #13852, this bug fix can produce more warnings: the rule will now report irregular whitespace that starts immediately after an ignored node (template literal, string, regex, or comment). Those were false negatives in the …
> Update: fix 'skip' options in no-irregular-whitespace (fixes #13852)

- docs/rules/no-unsafe-optional-chaining.md
- lib/rules/index.js
- lib/rules/no-unsafe-optional-chaining.js
- tests/lib/rules/no-unsafe-optional-chaining.js
- tools/rule-types.json
Added a new rule `no-unsafe-optional-chaining` which proposed by @mysticatea  #13431
This rule will catch cases that may possibly TypeError when using `optional chaining`.
```js
var obj = {};
// TypeError
(obj?.foo).bar;
(obj?.foo)();
(obj?.foo)`template`;
new (obj?.foo)();
class A extends obj?.foo {};
[...obj?.foo]; …
```
> New: no-unsafe-optional-chaining rule (fixes #13431)

- lib/rules/prefer-exponentiation-operator.js
- tests/lib/rules/prefer-exponentiation-operator.js
This is similar to https://github.com/eslint/eslint/issues/12739
* **ESLint Version:** v7.15.0
default
**Please show your full …
> Fix: prefer-exponentiation-operator invalid autofix with await

- docs/developer-guide/working-with-rules.md
Updated JSON Schema links in `working-with-rules`:
* Two links are just updated to `https://` (`http://json-schema.org` doesn't redirect to `https://` so it used to end up with the "Not secure" warning).
* Understanding JSON Schema is no more maintained in the spacetelescope repo. The redirection still works but may be …
> Docs: update JSON Schema links

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
fixes #12739
Changed the `no-extra-parens` rule to not report parens around `await` if it's LHS of `**`:
```js
async function f() {
(await a) ** b // this was a false positive
} 
```
> Fix: false positive with await and ** in no-extra-parens (fixes #12739)

- lib/rules/require-atomic-updates.js
- tests/lib/rules/require-atomic-updates.js
make require-atomic-updates work in the case described by issue #11954
I am new to eslint contribution, so sorry if this looks bad.
> Fix: require-atomic-updates false positive across await (fixes #11954)

- lib/eslint/eslint.js
- lib/rules/arrow-body-style.js
- lib/rules/callback-return.js
- lib/rules/dot-location.js
- lib/rules/func-call-spacing.js
- lib/rules/no-extend-native.js
- lib/rules/no-import-assign.js
- lib/rules/no-restricted-exports.js
- lib/rules/no-this-before-super.js
- lib/rules/prefer-destructuring.js
- lib/rules/prefer-reflect.js
- lib/rules/space-unary-ops.js
- lib/rules/utils/ast-utils.js
- lib/shared/deprecation-warnings.js
- lib/shared/types.js
- tests/lib/eslint/eslint.js
[x] Other, please explain: fix typos
I found some typos in the projects.
> Chore: fix typos

- lib/rules/one-var.js
- tests/lib/rules/one-var.js
> Fix: one-var shouldn't split declaration if it isn't in a statement list

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> Fix: no-useless-escape wrong loc and fix with CRLF in template elements

- docs/rules/multiline-ternary.md
- lib/rules/multiline-ternary.js
- tests/lib/rules/multiline-ternary.js
[ x] Add autofixing to a rule
it added autofix to rule multiline-ternary
it was based on PR #12982,  thanks to @Sawtaytoes great working! 
and surely if this PR get merged, that one can be closed!
> Update: add autofix to rule multiline-ternary

- docs/rules/no-multi-str.md
Changes examples for the `no-multi-str` rule.
The examples were technically okay for this rule, but perhaps misleading. It looked like that line continuation in a string literal contributes to the string as a linebreak, while it actually has no value.
I changed the examples so that all "correct" and "incorrect" examples …
> Docs: fix examples for no-multi-str

- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
> Fix: use regexpp's default ecmaVersion in no-invalid-regexp

- lib/rules/no-control-regex.js
- tests/lib/rules/no-control-regex.js
> Update: use regexpp's default ecmaVersion in no-control-regex

- lib/rules/no-useless-escape.js
Changes a few lines where `no-useless-escape` calculates range and loc of the reported backslash.
Replaced `sourceCode.getIndexFromLoc(node.loc.start)` with `node.range[0]`.
Am I missing something, it seems unnecessary to get index from the `loc` when we have `range`?
> Chore: refactor calculating range and loc in no-useless-escape

- docs/rules/space-in-parens.md
add examples such as `foo( )` & `foo(/* bar */)`
Add incorrect & correct examples for `space-in-parens`:
- `foo( )`
- `foo(/* bar */)`
- `foo( /* bar */ )`
related to: PR #13986 - test `foo( )` with space-in-parens: ["error", "always"]
see above
> Docs: space-in-parens examples with no arguments etc.

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
* **ESLint Version:** v7.17.0
default
<details>
```js …
```
> Fix: no-extra-parens false positive with `let` identifier in for-loop

- lib/init/config-initializer.js
fixes #13978
Fixed the `--init` "upgrade/downgrade ESLint" prompt to get the expected `answers` object.
It used to crash because the argument passed into `message()` was `state`, not `answers`. Thus, `localESLintVersion` and `requiredESLintVersionRange` properties were undefined, and then `semver.ltr(undefined, …
> Fix: --init crash on question to upgrade/downgrade ESLint (fixes #13978)

- docs/rules/no-invalid-regexp.md
- tests/lib/rules/no-invalid-regexp.js
Documentation for the `no-invalid-regexp` rule is misleading since the change made in https://github.com/eslint/eslint/pull/10062. In particular, the rule doesn't use configured `ecmaVersion`.
* Fixed the docs to note that this rule validates regular expressions per the latest ECMAScript Specification.
* Updated the …
> Docs: fix no-invalid-regexp docs regarding ecmaVersion

- docs/rules/complexity.md
- lib/rules/complexity.js
- tests/lib/rules/complexity.js
complexity
more
```js
/*eslint complexity: …
```
> Update: check logical assignment operators in the complexity rule

- README.md
Following up on today's TSC meeting, this documents why we chose to disable `package-lock.json`.
> Docs: Explain why we disable lock files (refs eslint/tsc-meetings#234)

- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
* **ESLint Version:** v7.18.0
* **npm Version:** 6.14.6
default
<details>
```js …
```
> Update: fix no-invalid-regexp false negatives with no flags specified

- docs/user-guide/configuring/README.md
Fixed several links in `configuring/README.md`.
> Docs: fix broken links in configuring/README.md

- docs/rules/no-unsafe-optional-chaining.md
I added `obj.foo?.bar` as a correct example for this rule,
since it's probably the most common usage of optional chaining.
No.
#14029
> Docs: add a correct example to no-unsafe-optional-chaining (refs #14029)

- lib/rules/space-infix-ops.js
- tests/lib/rules/space-infix-ops.js
> Update: check ternary `:` even if `?` was reported in space-infix-ops

- lib/rules/indent.js
- tests/lib/rules/indent.js
resolves #13971
This update applies one more condition for the consequent to avoid extra indenting in a nested ternary expression like this:
```js
condition1
? condition2
? Promise.resolve(1)
: Promise.resolve(2)
: Promise.resolve(3)
```
Note that the condition was mostly copied from the condition that @sheerun had …
> Fix: nested indenting for offsetTernaryExpressions: true (fixes #13971)

- README.md
I clarified our policy on stylistic rule updates based on eslint/tsc-meetings#237.
> Docs: Clarify stylistic rule update policy

- lib/rules/no-useless-rename.js
- tests/lib/rules/no-useless-rename.js
* **ESLint Version:** v7.18.0
<details>
```js …
```
> Fix: no-useless-rename invalid autofix with parenthesized identifiers

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
* **ESLint Version:** v7.18.0
* **npm Version:** 6.14.6
default
<details>
```js …
```
> Update: fix `let` logic in for-in and for-of loops in no-extra-parens

- lib/rules/no-shadow.js
- tests/lib/rules/no-shadow.js
…646)
#13646 
I changed the no-shadow rule to show where where the original identifier has been defined.
I am not familiar with JavaScript, so please check whether my codes have a problem.
> Update: add shadowed variable loc to message in no-shadow (fixes #13646)

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Add a few more fields to the bug report template: one for operating system (since that is sometimes the issue)  and asking for explicit reproduction steps. I also updated the chat link to point directly to the help channel and clarified that we want people to copy-paste the actual ESLint output (since people seem not to …
> Docs: Add more fields to bug report template

- package.json
- tests/lib/cli-engine/formatters/codeframe.js
We're using `@babel/code-frame` for the `codeframe` formatter.
The latest `@babel/code-frame` version `7.12.13`, which was released yesterday, is causing failures on our CI:
https://github.com/eslint/eslint/pull/14012/checks?check_run_id=1826678459
Tests are failing because `7.12.13` produces different output for empty …
> Upgrade: pin @babel/code-frame@7.12.11

- lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
Add a condition to return `false` in `directoryExists` function if Node API returns `ENOTDIR` error
Reproduced when special custom parsers were used: `jsonc-eslint-parser` together with `eslint-plugin-markdown`. Happened during linting of JSON code fragments in Markdown document when checking virtual file paths, e.g. …
> Fix: Support ENOTDIR error code in the folder existence checking utility

- lib/init/autoconfig.js
- tests/lib/init/autoconfig.js
- tests/lib/init/config-initializer.js
fixes #14017
Fixed the `--init` autoconfig (`How would you like to define a style for your project? >  Inspect your JavaScript file(s)`) to avoid creating configs that contain deprecated core rules.
> Fix: `--init` autoconfig shouldn't add deprecated rules (fixes #14017)

- docs/rules/no-unused-expressions.md
- lib/rules/no-unused-expressions.js
- tests/lib/rules/no-unused-expressions.js
React's createElement call is side-effect free, as are most JSX pragmas.
An unused JSX element indicates a logic error in the same way any unused, side-effect free expression is.
This extension the no-unused-expression rule flags unused JSX elements unless the (new) allowJsx configuration option is set
`no-unused-expression`
More warnings; Unused JSX expressions are newly flagged
~New default behavior; new option to opt-out~
No new default behavior; new option to opt-in
```tsx
// Flagged (with opt-in)
<div />
// Unflagged
const partial …
```
> Update: add enforceForJSX option to no-unused-expressions rule

- docs/maintainer-guide/issues.md
Wrote up a draft of a new triage process for issues. This new process uses a project board and eliminates a lot of the labels we use for tracking progress. The primary goal is to separate issue management into a triage phase (done by a triage team) and then an evaluating phase (done by the dev team).
Does the process …
> Docs: Triage process

- lib/linter/linter.js
- lib/linter/node-event-generator.js
- package.json
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/linter/linter.js
- tests/lib/linter/node-event-generator.js
- tests/lib/rules/no-restricted-syntax.js
fixes #13639
This PR uses a new option in esquery to solve the crash problem with non-standard ASTs such as JSX and some queries.
> Fix: Crash with esquery when using JSX (fixes #13639)

- docs/developer-guide/selectors.md
Per the [esquery documentation](https://github.com/estools/esquery), `~` is following (but not necessarily adjacent) sibling, `+` is adjacent sibling:
> * following sibling: node ~ sibling
> * adjacent sibling: node + adjacent
Our [selectors documentation](https://eslint.org/docs/developer-guide/selectors) has it the …
> Docs: fix sibling selector descriptions

- lib/rules/max-lines-per-function.js
I fixed one word in the description of the `max-lines-per-function` rule by pluralizing it.
Please read the rule description to ensure grammar is now correct.
> Docs: pluralize 'line' to 'lines' in max-lines-per-function description

- lib/rules/indent-legacy.js
- lib/rules/no-loss-of-precision.js
- lib/rules/prefer-destructuring.js
- lib/rules/use-isnan.js
- tests/fixtures/config-extends/error.json
- tests/lib/rules/indent.js
- tests/lib/rules/no-restricted-exports.js
[X] Other, please explain: Various small fixes in comments
> Chore: improve a few comments and fix typos

- lib/cli-engine/file-enumerator.js
- tests/lib/cli-engine/file-enumerator.js
[x] Bug fix
When enumerating files, if enumerator encounters symbolic links, resolves it.
Fixes #13551 
Fixes #13615 
Maybe no.
> Update: do not ignore symbolic links (fixes #13551, fixes #13615)

- Makefile.js
- lib/cli-engine/formatters/html.js
- lib/rule-tester/rule-tester.js
- lib/rules/eol-last.js
- lib/rules/lines-around-comment.js
- lib/rules/max-lines.js
- lib/rules/object-curly-newline.js
- lib/shared/runtime-info.js
This addresses part of #14098, reducing the usage of `lodash` in the project.
I removed all uses of lodash that could easily be replaced with ES6 code.
> Chore: Reduce lodash usage

- package.json
- tests/lib/rules/no-extend-native.js
refs #13602
Updates `no-extended-native` rule to start reporting `es2021` globals. Those are, currently: `WeakRef`, `FinalizationRegistry`, and `AggregateError`.
Updated `globals` dependency in `package.json`, from `^12.1.0` to `^13.6.0`, as `12.x` doesn't have any `es2021` globals.
`no-extend-native` uses …
> Update: report es2021 globals in no-extend-native (refs #13602)

- docs/rules/indent.md
Currently, all the options in indent rule except `SwitchCase`, `FunctionDeclaration.body` and `FunctionExpression.body` can be set to "off" to disable checking. 
I was setting up linting for one of my projects and I wanted to enable indent rule for just `CallExpression` option. After adding indent rule to eslint …
> Docs: Improve documentation for indent rule

- lib/shared/runtime-info.js
- package.json
- tests/lib/shared/runtime-info.js
[ x] Add a CLI option
`eslint --env-info` print the os info, it looks like:
```bash
Environment Info:
Node version: v15.5.0
npm version: v7.3.0
Local ESLint version: v7.19.0 (Currently used)
Operating System: darwin 20.3.0
```
no.
> Update: eslint --env-info output os info

- docs/rules/object-curly-newline.md
- lib/rules/object-curly-newline.js
I changed some sentences to clarify what **inside braces** mean for this rule.
No.
> Fix: Clarify line breaks in object-curly-newline (fixes #14024)

- docs/rules/no-mixed-operators.md
- lib/rules/no-mixed-operators.js
- tests/lib/rules/no-mixed-operators.js
fixes #14223
Fixes false positives such as:
```js
/* eslint no-mixed-operators: ["error", { groups: [["&&", "||", "?:"]] }] */
a ? (b || c) : d; // false positive
(a) ? (b || c) : d; // ok
(a ? (b || c) : d); // also ok
//--------------------------------
a ? b : (c || d); // false positive
(a) ? b : (c || d); // ok
(a ? …
```
> Fix: no-mixed-operators false positives with `? :` (fixes #14223)

- docs/rules/block-scoped-var.md
All the current valid examples show hoisting the var to the function scope. This example makes is clear that this rule allows you to declare vars inside a block scope, just not use them out of that scope.
> Docs: Add valid example that shows vars in a block scope

- lib/cli.js
- tests/lib/cli.js
fixes #14202
ESLint will now return exit code 1 and show the "too many warnings" error message when the number of warnings exceeds `--max-warnings` even if the `--quiet` flag was used. ESLint will still not show the actual warnings in that case.
Marked as "Update" since it can produce exit code 1 for runs that used to …
> Update: `--quiet` should not supress `--max-warnings` (fixes #14202)

- .github/workflows/ci.yml
- lib/cli.js
- lib/options.js
- package.json
[x] Other, please explain: Since #13844 added Node 15 and with it npm v7 to the build matrix, we've had to use `--legacy-peer-deps` when running `npm install` with npm v7. This upgrades the last incompatible dependency so we can just `npm install` in any supported Node/npm version.
- Chore: Upgrade eslint-plugin-jsdoc to v25
This is a Chore …
> Chore: Upgrade eslint-plugin-jsdoc to v25 and remove --legacy-peer-deps

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
1. Added the "repro:needed" label to the template
2. Added a note to try using the default parser if they are using a custom parser.
Do the changes make sense?
> Docs: Update bug report template

- docs/rules/no-multi-assign.md
- lib/rules/no-multi-assign.js
- tests/lib/rules/no-multi-assign.js
#12545 
I added an option, `ignoreNonDeclaration`.
This option ignores multi-assign when the variable is being declared.
> Update: add ignoreNonDeclaration to no-multi-assign rule (fixes #12545)

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #14163 by checking references also.
no.
> Fix: no-unused-vars ignoreRestSiblings check assignments (fixes #14163)

- docs/developer-guide/working-with-rules.md
Fixed a minor typo in the "Providing Suggestions" section of the "Working with Rules" documentation.
Not really.
> Docs: Fix typo in suggestions section

- docs/rules/arrow-parens.md
I think this use of "braces" should have been "parens".
- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
One-word change in a doc
The word   :)
> Docs: Fix incorrect reference to "braces" in arrow-parens.md

- docs/rules/no-implicit-coercion.md
- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
This adds the `templateString` option to `no-implicit-coercion`. This makes the
rule report the following code:
```js
`${foo}`
```
For backwards compatibility, this was added as a separate option instead of as
default behaviour.
Closes #12866
> Update: Add disallowTemplateShorthand option in no-implicit-coercion

- .gitignore
[✅ ] Other, please explain:
Ignore `pnpm-lock.yaml` for `pnpm` users. We already ignore `package-lock.json` and `yarn.lock`
No
> Chore: ignore `pnpm-lock.yaml`

- lib/linter/linter.js
- tests/lib/eslint/eslint.js
> Update: lint code block with same extension but different content

- docs/developer-guide/working-with-rules.md
Fixes the `getSourceCode()` anchor ref.
> Docs: Fix anchor in 'docs/developer-guide/working-with-rules.md' 

- docs/developer-guide/working-with-rules-deprecated.md
Added a couple of callouts (title and note) to the `working-with-rules-deprecated` page to better indicate to readers that the information on the page is deprecated.
I wound up on the [working-with-rules-deprecated](https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules-deprecated.md) page …
> Docs: Adds deprecated callouts to `working-with-rules-deprecated` page.

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #14324 
Highlight the last write reference instead of just highlighting the last reference.
> Update: highlight last write reference for no-unused-vars (fixes #14324)

- lib/init/config-initializer.js
- tests/lib/init/config-initializer.js
XO is a pretty strict and popular ESLint config by Sindre Sorhus, I was surprised not to find it among the ones listed in `eslint --init`. It’s usually used through XO’s own CLI tool but this config works everywhere.
> Include XO style guide in `eslint --init`

- lib/rules/radix.js
- tests/lib/rules/radix.js
[radix](https://eslint.org/docs/rules/radix)
No.
New automated suggestion.
Does …
> Update: Add automated suggestion to `radix` rule for parsing decimal numbers

- docs/rules/require-atomic-updates.md
`result += yield;` is an incorrect code for this rule, and it's indeed in examples of incorrect code, but was also in examples of correct code.
I fixed it to `result = (yield) + result;`
> Docs: fix example for require-atomic-updates

- lib/init/config-file.js
- lib/init/config-initializer.js
- lib/init/npm-utils.js
- tests/lib/init/config-initializer.js
Fixes https://github.com/eslint/eslint/issues/14137
NO
> Fix: create `.eslintrc.cjs` for `module` type

- lib/rules/require-atomic-updates.js
- tests/lib/rules/require-atomic-updates.js
fixes #14208
Fixes false positives like:
```js
async function foo(e) {
}
async function run() {
const input = [];
const props = [];
for(const entry of input) {
const prop = props.find(a => a.id === entry.id) || null;
await foo(entry);
}
// false positive:
// Possible race condition: `const entry` might be reassigned …
```
> Fix: track variables, not names in require-atomic-updates (fixes #14208)

- lib/cli-engine/cli-engine.js
- package.json
This incorporates https://github.com/eslint/eslintrc/pull/34, which
allows fixing `CLIEngine`'s `ModuleResolver` import.
[x] Other, please explain: Core dependency upgrade
This upgrades `@eslint/eslintrc` to v0.4.1, which I just released with https://github.com/eslint/eslintrc/pull/34. This allows us to fix `CLIEngine`'s `ModuleResolver` import.
> Upgrade: eslintrc for ModuleResolver fix

- tests/lib/rules/no-sequences.js
[X] Other, please explain: - **test**
Add more test cases.
Refs https://github.com/eslint/eslint/issues/14572
No
> Chore: add more test cases for `no-sequences`

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #14325 
Make sure to report an error in the following case - 
```
let x = 0;
x++, x = 0;
x = 3;
```
No
> Update: no-unused-vars false negative with comma operator (fixes #14325)

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
fixes #14633
Fixed the logic in `arrow-body-style` rule that assumed that `{` token at a certain position must be the start of an `ObjectExpression`, but in some cases it can be `ObjectPattern`.
> Fix: arrow-body-style crash with object pattern (fixes #14633)

- docs/rules/no-sequences.md
Add more examples.
Fixes https://github.com/eslint/eslint/issues/14572
Nope
> Docs: add more examples for `no-sequences` rule

- docs/developer-guide/working-with-rules.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Fix #11989 
add a new `getPhysicalFilename()` method to the rule context object. This method will return the full path of the file on disk without any code block information.
No
> New: add `getPhysicalFilename()` method to rule context (fixes #11989)

- docs/rules/no-duplicate-imports.md
- lib/rules/no-duplicate-imports.js
- tests/lib/rules/no-duplicate-imports.js
Fix the issue here: #12758
This PR fixes a bug in the rule **no-duplicate-imports** and follows this heuristic **An import that can be merged with another import is a duplicate of that other**. So for example, if we have specific import and namespace import, these two can’t be merged. We should remove the mark import as duplicate.
Fix the issue here: #12760
This PR  fixes also a bug in the rule **no-duplicate-imports**, it removes the export is duplicate mark from exportAllDeclaration because it can’t be merged with any other import/export, but there is a case when the export can be marked as duplicated, like this example (export * from "mod"; export * from …
> Fix: no-duplicate-imports allow unmergeable (fixes #12758, fixes #12760)

- lib/rules/no-unused-vars.js
Fixes location of `// in RHS of an assignment for itself...` comment in `no-unused-vars.js`. While reviewing https://github.com/eslint/eslint/pull/14354, I noticed that the comment was misplaced, probably due to autofixing in https://github.com/eslint/eslint/commit/7ad86dea02feceb7631943a7e1423cc8a113fcfe, Also, the …
> Chore: fix comment location in no-unused-vars

- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
fixes #14623 (the accepted part)
Fixed the `no-implicit-coercion` rule to treat `String(...)` as a string value and thus not report string coercions on it.
Also added this check for the `disallowTemplateShorthand` option.
> Fix: no-implicit-coercion false positive with `String()` (fixes #14623)

- lib/linter/linter.js
- tests/lib/linter/linter.js
update the regexp to allow linebreaks.
not really.
> Update: support multiline /*eslint-env*/ directives (fixes #14652)

- docs/user-guide/configuring/language-options.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
[ x] Add something to the core
* set ecmaVersion defaults to 5, make it not depend on espree's defaults
* allow ecmaVersion => "latest"
all these changes should not affect 3rd-party parsers.
> Update: ecmaVersion defaults to 5, and allows "latest"

- lib/eslint/eslint.js
- lib/init/npm-utils.js
- lib/rule-tester/rule-tester.js
- lib/rules/comma-style.js
- lib/rules/indent.js
- packages/eslint-config-eslint/default.yml
- tests/lib/eslint/eslint.js
> Chore: add some rules to eslint-config-eslint

- docs/user-guide/configuring/language-options.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
This reverts commit 831f6b30270a37800e61e6c668bfa71a39064d2e.
it causes an issue in rule-tester(reported in https://github.com/eslint/eslint/pull/14710). there are some ways to fix it, but we have not reached consensus which way to go.
- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md). …
> Revert "Update: ecmaVersion defaults to 5, and allows "latest" (#14622)"

- docs/rules/no-fallthrough.md
- lib/rules/no-fallthrough.js
- tests/lib/rules/no-fallthrough.js
[x] Bug fix
no-fallthrough
fewer
new default
```js
switch (foo) {
case 1: {
let x = value;
console.log(value);
// falls through
}
case 2: {
doSomething();
}
}
```
warn
not warn
Now when the case consists of a single BlockStatement the code will look for the fallthrough comment to be the final comment in the case, as well where it looked previously. 
In the situation in question - i.e., when the case consists of …
> Fix: allow fallthrough comment inside block (fixes #14701)

- docs/developer-guide/nodejs-api.md
- lib/eslint/eslint.js
- tests/lib/eslint/eslint.js
Added the `ESLint#getRulesMetaForResults()` method. This method was proposed as `ESLint#getRulesMetaForReport()` but that wording was incorrect in the [RFC](https://github.com/eslint/rfcs/tree/main/designs/2021-package-exports) because it's `CLIEngine` that return a report while `ESLint` returns an array of results, so …
> New: Add ESLint#getRulesMetaForResults() (refs #13654)

- docs/developer-guide/working-with-rules.md
I just noticed another two links are broken on this page.
Before:
1. https://eslint.org/docs/developer-guide/working-with-rules#messageIds
2. https://eslint.org/docs/developer-guide/nodejs-api#Linter
After:
1. https://eslint.org/docs/developer-guide/working-with-rules#messageids
2. …
> Docs: fix two broken links

- docs/developer-guide/nodejs-api.md
I caught the correct name of the anchor tag but missed the use of parens instead of square braces.
> Docs: Fix getRulesMetaForResults link syntax

- lib/rules/dot-notation.js
- lib/rules/prefer-arrow-callback.js
- package.json
update eslint-plugin-eslint-plugin to latest, it fixes a few false positives and false negatives.(a big thanks to @bmish !❤️ )
no.
> Chore: upgrade eslint-plugin-eslint-plugin

- docs/rules/use-isnan.md
- lib/rules/use-isnan.js
- tests/lib/rules/use-isnan.js
Fix https://github.com/eslint/eslint/issues/14715
Updated `isNaNIdentifier` logic to detect `Number.isNaN` as well.
No
> Update: improve use-isnan rule to detect `Number.NaN` (fixes #14715)

- docs/user-guide/configuring/language-options.md
- lib/linter/linter.js
- lib/rule-tester/rule-tester.js
- tests/fixtures/parsers/empty-program-parser.js
- tests/lib/linter/linter.js
- tests/lib/rule-tester/rule-tester.js
[ x] Add something to the core
this is to reland https://github.com/eslint/eslint/commit/831f6b30270a37800e61e6c668bfa71a39064d2e.
I kept the ecmaVersion defaults to 5, in case we want to change espree's defaults later.
but for linter/rule-tester, anything else needs to be updated?
> Update: ecmaVersion allows "latest"

- docs/rules/new-cap.md
Fix incorrect examples and add some more examples.
Fix https://github.com/eslint/eslint/issues/12874
Fix https://github.com/eslint/eslint/pull/13037
No
> Docs: fix and add more examples for new-cap rule (fixes #12874)

- docs/developer-guide/working-with-rules.md
- docs/rules/no-inner-declarations.md
- docs/user-guide/configuring/configuration-files.md
Update some links that could be broken once https://github.com/eslint/website/pull/856 is merged.
There're some links with absolute path instead of relative one, e.g.,
```md
[`--no-eslintrc`](https://eslint.org/docs/user-guide/command-line-interface#--no-eslintrc)
```
Shall we prefer relative path?
> Docs: fix broken links

- docs/developer-guide/working-with-plugins.md
Updates the "Working with Plugins" doc to suggest a few ESLint plugins to lint ESLint plugins with. The goal is to generally increase the quality of ESLint plugins and increase the usability of ESLint plugin rules.
* [eslint](https://www.npmjs.com/package/eslint)
* …
> Docs: Suggest linting plugins for ESLint plugin developers

- lib/source-code/source-code.js
refs #14744
Refactors `SourceCode#getComments()` to retain the intended behavior when used with Espree 8 which sets `Program.start` and `Program.end` differently than Espree 7.
Skip comparing comment's start/end with `Program` node's start/end, and thus don't break the loop that should get all comments around a …
> Chore: don't check Program.start in SourceCode#getComments (refs #14744)

- package.json
This pins `"fs-teardown": "0.1.1"` to fix our CI on Node 10.12.0.
The latest 0.1.3 doesn't work on Node 10.12.0:
https://github.com/eslint/eslint/pull/14769/checks?check_run_id=2993896202
The previous 0.1.2 had a breaking change with trimming file contents. That wasn't noticed in this repo, but breaks some tests in …
> Chore: pin fs-teardown@0.1.1

- docs/developer-guide/working-with-rules.md
Perhaps the top benefit of rules providing the `meta.docs.url` property with a link to their documentation is that IDEs / code editors can then provide a helpful link on rule violations. Developers often find this link useful to better understand a violation and learn how to fix it.
However, many rule authors are …
> Docs: Mention benefit of rules providing `meta.docs.url`

- lib/rules/no-mixed-operators.js
no-mixed-operators
no
```js
const result = …
```
> Update: Improving no-mixed-operators to clarify what changes need to be made.

- lib/rules/operator-assignment.js
operator-assignment
no
```js
x = x + 3;
``` …
> Update: operator-assignment should indicate which operator can be shortened

- docs/developer-guide/nodejs-api.md
Fix a broken link. The right one would be https://eslint.org/docs/developer-guide/working-with-rules#the-context-object instead of https://eslint.org/docs/developer-guide/working-with-rules#The-Context-Object, the later one won't scroll to respective heading.
Nothing.
> Docs: fix a broken link

- lib/rules/consistent-return.js
- tests/lib/rules/consistent-return.js
refs #12334
This PR adds `loc.end` to reports in `consistent-return`
Just a small change from `loc.start` to `loc`
No
> Update: add end location to report in `consistent-return` (refs #12334)

- .github/workflows/ci.yml
[X] Other, please explain: CI related
updated `setup-node`  action to `v2` for CI node workflow.
https://github.com/marketplace/actions/setup-node-js-environment
No
> Chore: use `actions/setup-node@v2`

- docs/rules/space-after-keywords.md
- docs/rules/space-before-keywords.md
- docs/rules/space-return-throw-case.md
- docs/user-guide/configuring/configuration-files.md
Fix broken links. A follow-up of https://github.com/eslint/website/pull/861.
Nothing.
> Docs: fix multiple broken links

- lib/rules/unicode-bom.js
- tests/lib/rules/unicode-bom.js
Refs #12334
This PR adds `loc.end` to reports in `unicode-bom` rule.
no
> Chore: assertions on reporting loc in `unicode-bom` (refs #12334)

- .github/ISSUE_TEMPLATE/NEW_SYNTAX.md
Added an issue template for implementing new syntax. People keep doing this manually, so might as well bless this approach and make it easier for everyone. :)
Are there any other details that should be included on the issue?
> Docs: New syntax issue template

- Makefile.js
Prepare for the ESLint website to display an emoji/notice for rules with suggestions.
Fixes https://github.com/eslint/website/issues/859
Other part to this change: https://github.com/eslint/website/pull/860
TODO: After this is merged, remember to update https://github.com/eslint/eslint/pull/14573 to change the new usage …
> Docs: Prepare data for website to indicate rules with suggestions

- .eslintrc.js
- tests/tools/internal-rules/no-invalid-meta.js
- tools/internal-rules/no-invalid-meta.js
A few cases in our internal rule `no-invalid-meta` can be removed and replaced by:
* [eslint-plugin/prefer-object-rule](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/prefer-object-rule.md)
* [eslint-plugin/require-meta-docs-description](https://github.com/not-an-aardvark/eslint-plu …
> Chore: Simplify internal `no-invalid-meta` rule

- lib/rules/comma-style.js
- tests/lib/rules/comma-style.js
[X] Bug fix
Fix the issue here: #12756
This PR fixes a bug in the rule **comma-style**, it ignores lines that are only made of empty elements. 
This is an example:
```
const [
,
a,
b,
] = arr;
```
No.
> Fix: ignore lines with empty elements (fixes #12756)

- lib/rules/curly.js
- tests/lib/rules/curly.js
Refers https://github.com/eslint/eslint/issues/12334
Fixes https://github.com/eslint/eslint/pull/13282
No
> Update: change reporting location for `curly` rule (refs #12334)

- docs/developer-guide/selectors.md
A small documentation change to mention the workaround for the esquery issue that prevents the forward-slash character to be escaped in regular expressions, when used in `no-restricted-syntax`.
> Docs: Mention workaround for escaping the slash character in selectors

- lib/rules/comma-dangle.js
Fixes #13739 
Added `additionalItems: false` in order to allow specifying only 1 option.
Please see #13166 for discussions regarding semver handling on this (breaking) change. A revert was made on the accepted PR, so this fix is pending a new major release
> Breaking: fix comma-dangle schema (fixes #13739)

- docs/rules/no-unused-vars.md
- docs/user-guide/configuring/language-options.md
- docs/user-guide/configuring/rules.md
- lib/linter/linter.js
- lib/rules/newline-before-return.js
- lib/rules/utils/ast-utils.js
- tests/lib/linter/linter.js
- tests/lib/rules/id-blacklist.js
- tests/lib/rules/id-denylist.js
- tests/lib/rules/no-inline-comments.js
- tests/lib/rules/no-promise-executor-return.js
- tests/lib/rules/no-setter-return.js
- tests/lib/rules/no-warning-comments.js
- tests/lib/rules/require-await.js
- tests/lib/rules/utils/ast-utils.js
[ x] Add something to the core
allow all directives in line comments (fixes #14575)
there are some inline comments which were not intended as a directive, but parse as directives. I just replaced `// global xxx` => `// Global xxx`(8bd615025c5d0c5718b66f0032913c4952c798bb).
> Breaking: allow all directives in line comments (fixes #14575)

- lib/linter/linter.js
- lib/rule-tester/rule-tester.js
- tests/fixtures/rules/make-syntax-error-rule.js
- tests/fixtures/testers/rule-tester/fixes-one-problem.js
- tests/lib/linter/linter.js
- tests/lib/rule-tester/rule-tester.js
fixes #13349 (implements the final step 3)
ESLint v7 requires that a rule that produces fixes must provide `meta.fixable` property, but only if the rule provides `meta`. In other words, rules that don't provide `meta` were allowed to produce fixes.
After this change (ESLint v8.0.0), ESLint will require that a rule that …
> Breaking: require `meta` for fixable rules (fixes #13349)

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
refs #14744
Updates `RuleTester` to throw an error on any usage of `SourceCode#getComments()`.
`RuleTester` will replace `SourceCode.prototype.getComments` with a function that throws an error.
> Breaking: disallow SourceCode#getComments() in RuleTester (refs #14744)

- docs/rules/func-names.md
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-875789724
Updated documentation for the `func-names` rule to clarify that `as-needed` logic isn't tied to ES6, and added examples with class fields and logical assignment operators. 
I believe the reason to specify ES6 was an expectation that …
> Docs: add class fields in func-names documentation (refs #14857)

- docs/rules/no-multi-assign.md
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#pullrequestreview-701805427
Updated documentation for the `no-multi-assign` rule to show that it applies to class fields initializers.
Also updated description of `"ignoreNonDeclaration": true` to specify that it doesn't ignore class fields initializers.
> Docs: add class fields in no-multi-assign documentation (refs #14857)

- docs/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-866388926.
Updated the `no-extra-parens` rule to check class fields.
> Update: check class fields in no-extra-parens (refs #14857)

- docs/rules/no-console.md
Fix #14793
Update rule details to clarify this rule disallows assignments as well.
No
> Docs: improve rule details for `no-console` (fixes #14793)

- docs/rules/dot-notation.md
- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-866334741
Fixed `allowKeywords: false` option of the `dot-notation` rule to check only `Identifier` properties.
> Fix: dot-notation false positive with private identifier (refs #14857)

- docs/rules/prefer-destructuring.md
- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-874891668
Fixed the `prefer-destructuring` rule to not report private member access.
> Fix: prefer-destructuring PrivateIdentifier false positive (refs #14857)

- Makefile.js
- lib/cli-engine/formatters/tap.js
- lib/init/config-file.js
- package.json
- tests/lib/init/config-file.js
Updates dependency.
https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#400---2021-01-03
Also allow Python licenses ([OSI](opensource.org/licenses/alphabetical) approved) for transitive dependency argparse.
No.
> Upgrade: `js-yaml` to v4

- docs/rules/no-useless-computed-key.md
- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#pullrequestreview-690053478
* Fixed the `no-useless-computed-key` rule to account for specific names like `"constructor"` in class fields.
* Updated the docs with class fields.
> Fix: no-useless-computed-key edge cases with class fields (refs #14857)

- tests/lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-modules.js
[] Add something to the core
Just adding rule tests.
Adds tests to [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports) and [no-restricted-modules](https://eslint.org/docs/rules/no-restricted-modules) rules to cover relative/absolute import paths. It's important to get these test cases into place particularly because the …
> Chore: Add rel/abs path tests in `no-restricted-{imports/modules}` rules

- docs/rules/operator-linebreak.md
- lib/rules/operator-linebreak.js
- tests/lib/rules/operator-linebreak.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-874963573
Updated the `operator-linebreak` rule to account for `]` of computed class fields by finding the operator token by `value`. Also switched to searching from the right side in order to better handle language extensions (e.g., typescript …
> Fix: handle computed class fields in operator-linebreak (refs #14857)

- docs/rules/no-import-assign.md
as https://github.com/eslint/eslint/issues/14911#issuecomment-896276484, it has been supported but not documented.
> Docs: add an example `Object.assign()` for rule no-import-assign

- lib/linter/apply-disable-directives.js
- lib/linter/linter.js
- lib/linter/node-event-generator.js
- lib/rules/max-lines.js
[x] Other, please explain: Followup to #14287 to remove old syntax.
Replaced old syntax with newer syntax that was not available in Node 10.
This can be merged after support for Node 10 is dropped.
> Chore: Switch to native Array flat/flatMap

- Makefile.js
[x] Other, please explain: Fix the release script
The first attempt to release `v8.0.0-beta.0` failed when `Makefile.js` tried to call `linter.getRules()`.
https://github.com/eslint/eslint/blob/0c86b68a6e2435eb03b681b51b099b552b521adc/Makefile.js#L641
The `linter` object was removed in v8.0.0, so we need to create an instance of `Linter`.
There's …
> Chore: Fix Makefile call to linter.getRules()

- .github/workflows/ci.yml
[x] Other, please explain: Fix CI peerdep issues during prereleases
Several dev dependencies have a peer dependency on the local ESLint. Prereleases don't satisfy regular version range constraints, so the new peer dependency resolution algorithm in Node 16 rejects `v8.0.0-beta.0` as a valid peer dependency. Until we're done with prereleases, we …
> Build: Force prerelease peer dep for Node 16 in CI

- docs/developer-guide/architecture.md
The [`ESLint`](https://github.com/eslint/eslint/blob/83cc8a6823d7729297b6814a644cca770cb99dbb/lib/api.js#L17) was exposed via this pull request https://github.com/eslint/eslint/pull/12939, but it's not documented in the latest documentation yet.
Nothing.
> Docs: document ESLint api

- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
Fixes incorrect behavior in `for-of` and `for-in` when a private identifier is used in the lefthand side.
https://github.com/eslint/eslint/pull/14591#pullrequestreview-701480702
Did I miss anything?
> Fix: keyword-spacing private name compat (refs #14857)

- docs/rules/no-unreachable.md
- lib/rules/no-unreachable.js
- tests/lib/rules/no-unreachable.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#pullrequestreview-700195963 and https://github.com/eslint/eslint/pull/14591#issuecomment-874951639.
Fixed the `no-unreachable` rule to report only instance fields (i.e., not report static fields) when the constructor of a subclass doesn't call `super()`, …
> Update: fix no-unreachable logic for class fields (refs #14857)

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fix  https://github.com/eslint/eslint/issues/14866
Report `z` as unused variable for the following case - 
```
/*eslint no-unused-vars: "error"*/
var z = 0;
z=z+1, z=2;
```
No
> Update: fix no-unused-vars false negative with comma operator

- tests/lib/linter/linter.js
Adds a test for `Linter` module.
refs https://github.com/eslint/eslint/pull/14931 attempt to replace `lodash.merge` with `Object.assign`.
Added a simple test that confirms that `parserOptions` are deeply merged in `Linter`.
> Chore: add test for merging `parserOptions` in Linter

- docs/rules/prefer-named-capture-group.md
refs #14959, fixes the "When Not To Use It" section in `prefer-named-capture-group` docs.
This rule must be disabled "if you are targeting ECMAScript 2017 and/or older environments" because it enforces the use of a syntax that isn't supported in those environments, but the wording "you _can_ disable this rule" doesn't …
> Docs: fix 'When Not To Use' in prefer-named-capture-group (refs #14959)

- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#discussion_r676212379
In ESLint v7.32.0, `ignoreGlobals` option in the `camelcase` rule doesn't apply to undefined variables.
```js
/* eslint camelcase: ["error", { ignoreGlobals: true }] */
undefined_variable; // error
implicit_global = 1; // error
``` …
> Fix: camelcase ignoreGlobals shouldn't apply to undef vars (refs #14857)

- Makefile.js
- lib/cli-engine/cli-engine.js
- lib/cli-engine/hash.js
- lib/init/autoconfig.js
- lib/init/config-file.js
- lib/init/config-initializer.js
- lib/init/config-rule.js
- lib/init/npm-utils.js
- lib/init/source-code-utils.js
- lib/linter/linter.js
- lib/linter/source-code-fixer.js
- lib/rules/consistent-this.js
- lib/rules/default-case.js
- lib/rules/eqeqeq.js
- lib/rules/key-spacing.js
- lib/rules/newline-after-var.js
- lib/rules/newline-per-chained-call.js
- lib/rules/no-bitwise.js
- lib/rules/no-shadow.js
- lib/rules/object-shorthand.js
- lib/rules/one-var.js
- lib/rules/operator-assignment.js
- lib/rules/quote-props.js
- lib/rules/utils/ast-utils.js
- packages/eslint-config-eslint/default.yml
- tests/lib/rules/complexity.js
- tests/lib/rules/dot-notation.js
Enforce that the components of a jsdoc block (e.g., type, name, description) are never aligned (by being padded with extra whitespace). 
As per https://github.com/eslint/eslint/pull/14814#issuecomment-891426423 , this was to be approved if fixers were available, and the jsdoc plugin does provide a fixer here.
> Chore: Enforce jsdoc check-line-alignment (never)

- docs/rules/lines-around-comment.md
- lib/rules/callback-return.js
- lib/rules/global-require.js
- lib/rules/handle-callback-err.js
- lib/rules/id-blacklist.js
- lib/rules/indent-legacy.js
- lib/rules/lines-around-directive.js
- lib/rules/newline-after-var.js
- lib/rules/newline-before-return.js
- lib/rules/no-buffer-constructor.js
- lib/rules/no-mixed-requires.js
- lib/rules/no-new-require.js
- lib/rules/no-path-concat.js
- lib/rules/no-process-env.js
- lib/rules/no-process-exit.js
- lib/rules/no-restricted-modules.js
- lib/rules/no-sync.js
- lib/rules/require-jsdoc.js
- lib/rules/valid-jsdoc.js
Update deprecated information.
Ref: https://eslint.org/docs/rules/#deprecated
> Chore: Update deprecated information

- docs/rules/func-name-matching.md
- lib/rules/func-name-matching.js
- tests/lib/rules/func-name-matching.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-877324627
Updated the `func-name-matching` rule to:
* ignore assignments to private fields, such as `this.#x = function foo() {};`, instead of crashing (this is a bug fix).
* check and report class field definitions, e.g. `class C { foo = …
> Update: support class fields in func-name-matching (refs #14857)

- Makefile.js
- docs/developer-guide/development-environment.md
- package.json
[ ] Add auto fixing to a rule
[x] Other, please explain: Chore
Fixes https://github.com/eslint/eslint/issues/14288
remove `docs` script from `package.json`, related code, and documentation.
No
> Docs: remove `docs` script (fixes #14288)

- docs/developer-guide/scope-manager-interface.md
This is a follow-up to https://github.com/eslint/eslint-scope/pull/69
Updated `ScopeManager` documentation with the changes introduced in https://github.com/eslint/eslint-scope/pull/69.
> Docs: update ScopeManager with class fields

- docs/user-guide/migrating-to-8.0.0.md
> Docs: fix typo in migration guide

- Makefile.js
- docs/rules/indent-legacy.md
[X] Other, please explain: Add tests
I update deprecated information at https://github.com/eslint/eslint/pull/14961 and turned out we need to add some more tests.
https://github.com/eslint/eslint/pull/14961#issuecomment-903346856
>Have a This rule was deprecated... notice at the top of their rule doc
>Have `@deprecated` in their rule doc comment
> Chore: Add test that deprecated rules display a deprecated notice

- docs/rules/no-undef-init.md
- lib/rules/no-undef-init.js
- tests/lib/rules/no-undef-init.js
refs #14857, https://github.com/eslint/eslint/pull/14591#discussion_r656622751
Fixed the `no-undef-init` rule to not apply to class fields.
This reverts changes in this rule made in https://github.com/eslint/eslint/pull/14591:
* Rule: https://github.com/eslint/eslint/commit/b953a4ee12f120658a9ec27d1f8ca88dd3dfb599#diff-4 …
> Fix: no-undef-init should not apply to class fields (refs #14857)

- docs/rules/max-classes-per-file.md
- lib/rules/max-classes-per-file.js
- tests/lib/rules/max-classes-per-file.js
Allowed `max-classes` to take in an object for its options, with a new `ignoreExpressions` option alongside the existing `maxClasses`.
Fixes #14855.
These files are a few years old. Would you like me to update them to a newer format?
> Update: added ignoreExpressions option to max-classes-per-file

- docs/rules/prefer-named-capture-group.md
Fixes #15007
[x Documentation update
Added information about the non-capturing groups to `prefer-named-capture-group` rule documentation.
--
> Docs: add non-capturing groups info to prefer-named-capture-group (fixes #15007)

- docs/rules/semi.md
- lib/rules/semi.js
- tests/lib/rules/semi.js
Fixed the `semi` false positives described in:
- https://github.com/eslint/eslint/pull/14591#issuecomment-866328829
- https://github.com/eslint/eslint/pull/14591#issuecomment-874716539
- https://github.com/eslint/eslint/pull/14591#issuecomment-876244868
Did I miss anything?
> Fix: Update semi for class-fields (refs #14857)

- tests/fixtures/rules/wrong/custom-rule.js
- tests/lib/cli.js
One of the tests expects that `null.something` throws error with a certain message, but that message has been sligthly changed in the latest Node 16 and thus the test fails:
https://github.com/eslint/eslint/pull/15039/checks?check_run_id=3549061940
Fixed the test to not rely on v8 error messages.
> Chore: fix failing cli test

- docs/developer-guide/nodejs-api.md
- lib/shared/types.js
In `lib/linter/linter.js`, the `parse()` function's exception handler translates the exception's message to a `LintMessage`. It also passes through the exception's `lineNumber` and `column`, but the exception is not guaranteed to have those properties. In that case, `LintMessage.line` and `column` can be `undefined`. …
> Docs: LintMessage.line and column are possibly undefined

- docs/rules/class-methods-use-this.md
- lib/rules/class-methods-use-this.js
- tests/lib/rules/class-methods-use-this.js
1. add `enforceForClassFields` options.
- https://github.com/eslint/eslint/pull/14591#discussion_r656613541
2.Fix `exceptMethods` options to use `#` prefix for ignoring private methods 
- https://github.com/eslint/eslint/pull/14591#issuecomment-866383434
3, fix false-negative
- …
> Update: enforceForClassFields in class-methods-use-this (refs #14857)

- docs/rules/lines-between-class-members.md
- lib/rules/lines-between-class-members.js
- tests/lib/rules/lines-between-class-members.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-875113378
Fixed the `lines-between-class-members` to support semicolon-less style.
For example:
```js
/* eslint lines-between-class-members: ["error", "always"]*/
class C {
a // this is ok, although this field technically ends with the `;` below …
```
> Fix: semicolon-less style in lines-between-class-members (refs #14857)

- docs/rules/complexity.md
- lib/rules/complexity.js
- tests/lib/rules/complexity.js
refs #14857, fixes https://github.com/eslint/eslint/pull/14591#issuecomment-877346829
Update the `complexity` rule to supports class fields, in a way that the rule now treats them as functions:
* Code in class field initializers doesn't contribute to the complexity of the enclosing code (this is a bug fix).
* Code in …
> Update: support class fields in the `complexity` rule (refs #14857)

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/change.yml
- .github/ISSUE_TEMPLATE/new-rule.yml
- .github/ISSUE_TEMPLATE/rule-change.yml
Update issue templates
- Made the code of conduct warning a bit less wordy
- Added a textbox for "additional comments" on each template in case we missed something
- Fixed some of the rendering of the boxes
- Added "implement autofix" and "implement suggestions" to the rule change template
Do these changes make sense?
> Chore: Cleanup issue templates

- tests/lib/linter/node-event-generator.js
closes #14799
Added a test to confirm that #14799 has been fixed in ESLint 8 (by upgrading espree -> acorn).
> Chore: test `Property > .key` with `{ a = 1 }` pattern (fixes #14799)

- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes #15037.
Added error handling around rule listener calls in `linter.js`. The error handler wrapper is added when `safe-emitter` listeners are created. This seemed like a good place for it since we have `ruleId` easily available.
When extending caught error in try-catch of  `runRules` calls it is checked whether …
> Update: include `ruleId` in error logs of crash (fixes #15037)

- Makefile.js
Resolve `/* global target -- TODO: figure out where this is coming from and update this description */` in `Makefile.js`
> Docs: Figure out where `target` in `Makefile.js` is coming from

- Makefile.js
[x] Other, please explain: Refactor
`target.all` will run when the following command is typed:
```zsh
$ node Makefile.js
or
$ node Makefile.js all
```
> Ref: https://github.com/shelljs/shelljs/blob/0ae1dd681e2d79498c1b099e0c2763ac1a47a3a2/make.js#L44-L55
`$ node Makefile.js` <- `args.length = 0`
There is no such command: …
> Chore: Remove `target.all` from `Makefile.js`

- templates/blogpost.md.ejs
With https://github.com/eslint/website/pull/869 merged, we no longer need top-level headings directly in the markdown body, so I removed the heading from the release blog post template.
Let's get this merged before the next release. :)
> Docs: Update release blog post template

- docs/rules/no-new-func.md
- lib/rules/no-new-func.js
- tests/lib/rules/no-new-func.js
[x] Include tests for this change
[x] Update documentation for this change
The `no-new-func` rule should be able to catch calls to `Function.apply` (see the example below) concerning dynamic Function() constructor in the form of eval().
```js
var fn = Function.apply('sum', ['a', 'b', 'return a+b;']);
fn(1, 2);
```
This would allow testing libraries to comply with CSP as demonstrated in https://github.com/plotly/plotly.js/pull/5868
cc: @alexcjohnson
> Update: `no-new-func` rule catching eval case of `MemberExpression`

- lib/linter/apply-disable-directives.js
- tests/lib/linter/apply-disable-directives.js
- tests/lib/linter/linter.js
refs https://github.com/eslint/eslint/issues/14878, fixes https://github.com/eslint/eslint/pull/14617#issuecomment-892105159
This fix aims at preserving the original formatting of eslint-disable-* directives when individual rules are being removed during the autofix.
Extended the removal range for the first and the last …
> Fix: preserve formatting when rules are removed from disable directives

- docs/rules/space-before-blocks.md
- lib/rules/space-before-blocks.js
- lib/rules/switch-colon-spacing.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/space-before-blocks.js
fixes #15082
Updated `space-before-blocks` to ignore spacing after switch case colons, because that conflicts with `switch-colon-spacing`.
I marked this as "Update" although this change can produce only fewer warnings, because it changes the functionality of this rule while this wasn't a bug in the rule itself.
> Update: space-before-blocks ignore after switch colons (fixes #15082)

- lib/config/rule-validator.js
- tests/lib/config/flat-config-array.js
This implements a search in flat config when a rule ID isn't found. It searches through other plugins to see if there's a rule name matching the one specified.
Do the changes work as expected?
> Update: Suggest missing rule in flat config (fixes #14027)

- docs/user-guide/configuring/configuration-files.md
This adds a `.eslintrc.json` that shows how to set rules config (among
others). For context, see https://github.com/eslint/eslint/issues/15064
---
NOTE: this includes configuration from third-party plugins (in particular `typescript-eslint`). Feel free to replace with `{...}`-style configuration blocks from `eslint` …
> Docs: add example .eslintrc.json

- docs/user-guide/command-line-interface.md
Replace numeric rule severity with string rule severity
No
> docs: Use string rule severity in CLI examples

- lib/rules/key-spacing.js
Improves the performance of `key-spacing` rule.
I noticed that `key-spacing` takes significantly more time than other core rules (except for `indent`) while linting eslint codebase.
```
Rule                                          | Time (ms) | Relative
:---------------------------------------------|----------:|--------: …
```
> perf: don't prepare a fix for valid code in key-spacing

- docs/rules/no-use-before-define.md
- lib/rules/no-use-before-define.js
- tests/lib/rules/no-use-before-define.js
This bug fix produces only more warnings.
* **ESLint Version:** v8.0.0-rc.0
* **Node Version:** v12.22.4
* **npm Version:** v6.14.14
default …
> feat: report class evaluation TDZ errors in no-use-before-define

- package.json
- tests/bin/eslint.js
Updates @eslint/eslintrc dependency in order to include https://github.com/eslint/eslintrc/pull/61 and thus complete https://github.com/eslint/eslintrc/issues/59.
Updated package.json with `"@eslint/eslintrc": "^1.0.4"`, and fixed one test that relies on an error message from js-yaml, which has changed in js-yaml v4.
> chore: update @eslint/eslintrc to avoid different versions of `js-yaml`

- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes #15256
Change to pass 6 to eslint-scope when ecmaVersion is non number.
This allows the scope to be analyzed as ES6 if the user uses a custom parser and `ecmaVersion: latest`.
> feat: Normalize ecmaVersion to eslint-scope when using custom parser

- docs/rules/no-unused-expressions.md
- lib/rules/no-unused-expressions.js
- tests/lib/rules/no-unused-expressions.js
Refs #15016, fixes `no-unused-expressions`.
Class static blocks don't have directive prologues. Therefore, directive-like statements in class static blocks, such as `"use strict"` at the beginning of a class static block, should be reported by the `no-unused-expressions` rule.
The behavior was already correct. I only updated …
> docs: no-unused-expressions - class static blocks don't have directives

- docs/rules/lines-around-comment.md
Fixes #15292 by removing the deprecation note from `lines-around-comment` documentation.
Removed deprecation from the docs for this rule.
It seems that this was mistakenly added in https://github.com/eslint/eslint/pull/14961.
> docs: remove deprecation note from lines-around-comment

- docs/rules/block-scoped-var.md
- lib/rules/block-scoped-var.js
- tests/lib/rules/block-scoped-var.js
Refs #15016, fixes `block-scoped-var`.
This change documents examples for `block-scoped-var` with class static blocks, and adds a few tests.`
There's also a change in the code, but it's only for clarity. It doesn't change the behavior of this rule, because `var` variables defined in a static block cannot be referenced outside …
> docs: add examples for block-scoped-var with class static blocks

- docs/rules/semi.md
- lib/rules/semi.js
- tests/lib/rules/semi.js
Refs #15016, fixes `semi`.
Updated `omitLastInOneLineBlock` option in the `semi` rule to apply to class static blocks.
```js
/*eslint semi: ["error", "always", { "omitLastInOneLineBlock": true}] */
if (foo) { bar() } // ok
if (foo) { bar(); baz() } // ok
function f() { bar(); baz() } // ok
class C {
foo() { bar(); baz() } // …
```
> feat: update semi rule for class static blocks

- docs/rules/no-extra-semi.md
- lib/rules/no-extra-semi.js
- tests/lib/rules/no-extra-semi.js
Refs #15016, fixes `no-extra-semi`.
Updated the `no-extra-semi` rule to report semicolons after class static blocks.
```js
/*eslint no-extra-semi: "error"*/
class C {    
static {        
}; // error
}
```
> feat: update no-extra-semi for class static blocks

- docs/rules/keyword-spacing.md
- docs/rules/space-before-blocks.md
- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
- tests/lib/rules/semi-spacing.js
- tests/lib/rules/space-before-blocks.js
Refs #15016, fixes `keyword-spacing`.
Updated the `keyword-spacing` rule to check spacing around `static` of class static blocks.
Also added test to confirm that this doesn't conflict with `semi-spacing` and `space-before-blocks`.
> feat: update keyword-spacing for class static blocks

- docs/rules/block-spacing.md
- lib/rules/block-spacing.js
- tests/lib/rules/block-spacing.js
Refs #15016, fixes `block-spacing`.
Updated the `block-spacing` rule to apply to class static blocks.
```js
/* eslint block-spacing: error */
{foo} // applies to blocks
class C {
method() {foo} // applies to function/method bodies
static {foo} // should apply to class static blocks, too
}
```
> feat: update block-spacing for class static blocks

- docs/rules/no-lone-blocks.md
- lib/rules/no-lone-blocks.js
- tests/lib/rules/no-lone-blocks.js
Refs #15016, fixes `no-lone-blocks`.
Updated the `no-lone-blocks` rule to report lone blocks at the top level of class static blocks.
```js
class C {
static {
{ // this is a lone block
foo();
}
}
}
```
> feat: update no-lone-blocks for class static blocks

- docs/rules/class-methods-use-this.md
- lib/rules/class-methods-use-this.js
- tests/lib/rules/class-methods-use-this.js
Refs #15016, fixes `class-methods-use-this`.
Updated the `class-methods-use-this` rule to account for class static blocks.
This only fixes false negatives where use of `this` in a class static block mistakenly counts as used `this` in the enclosing context:
```js
/* eslint class-methods-use-this: error */
class A {
foo () { …
```
> feat: update class-methods-use-this for class static blocks

- docs/rules/no-eval.md
- docs/rules/no-invalid-this.md
- lib/rules/no-eval.js
- lib/rules/no-invalid-this.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-eval.js
- tests/lib/rules/no-invalid-this.js
Refs #15016, fixes `no-invalid-this` and `no-eval`.
Fixed false positives of rules `no-invalid-this` and `no-eval` in cases where `this` is used in class static blocks:
```js
class C {
static {
this; // this isn't invalid `this`
}
static {
this.eval(); // this isn't global `eval()`
}
}
```
> fix: update no-invalid-this and no-eval for class static blocks

- docs/rules/strict.md
- tests/lib/rules/strict.js
Refs #15016, fixes `strict`.
This PR documents that class static blocks do not have directives, and therefore the `strict` rule does not apply to them.
Also adds tests to confirm this behavior.
> docs: the strict rule does not apply to class static blocks

- docs/user-guide/command-line-interface.md
*This is a follow-up of a short [discussion](https://discord.com/channels/688543509199716507/688543520482394192/908764276523671582) in Discord* 
I expand the [`--debug` flag description](https://eslint.org/docs/user-guide/command-line-interface#--debug), in order to clarify that: 
- its purpose is to set ESLint to run on a …
> docs: Expand  `--debug` option description in the CLI documentation

- docs/rules/padding-line-between-statements.md
- lib/rules/padding-line-between-statements.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/padding-line-between-statements.js
Refs #15016, fixes `padding-line-between-statements`.
Updated the `padding-line-between-statements` rule to apply to the top level of class static blocks.
> feat: update padding-line-between-statements for class static blocks

- docs/rules/one-var.md
- lib/rules/one-var.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/one-var.js
Refs #15016, fixes `one-var`.
This PR fixes false positives of the `one-var` rule with option `"always"` where the rule suggests combining declarations from a class static block with declarations from the upper scope.
```js
/* eslint one-var: ["error", "always"] */
let a;
class C {
static {
let b; // false positive
}
}
``` …
> feat: update one-var for class static blocks

- docs/developer-guide/scope-manager-interface.md
- package.json
- tests/lib/rules/no-shadow.js
- tests/lib/rules/no-undef.js
Refs #15016, fixes `eslint-scope`.
Updates `eslint-scope` dependency to v7.0.0, which supports class static blocks.
Updated package.json, updated scope manager documentation, and added `no-undef` and `no-shadow` tests with class static blocks.
> feat: update eslint-scope for class static blocks

- docs/rules/prefer-const.md
- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
Refs #15016, fixes `prefer-const`
This PR fixes false negatives of the `prefer-const` rule at the top level of class static blocks.
Example of a false negative:
```js
/* eslint prefer-const: "error" */
class C {
static {
let a;
a = 0; 
}
}
```
> feat: update prefer-const for class static blocks

- docs/rules/max-statements.md
- lib/rules/max-statements.js
- tests/lib/rules/max-statements.js
Refs #15016, fixes `max-statements`.
Updated the `max-statements` rule so that it does not apply to class static blocks and does not count statements in them as statements of the enclosing function.
Before this change, the behavior of this rule was:
```js
/* eslint max-statements: ["error", 2] */
var x; // 1 …
```
> feat: update max-statements for class static blocks

- docs/rules/brace-style.md
- lib/rules/brace-style.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/brace-style.js
Refs #15016, fixes `brace-style`.
Updated the `brace-style` rule to apply to braces of class static blocks.
> feat: update brace-style for class static blocks

- docs/rules/lines-around-comment.md
- lib/rules/lines-around-comment.js
- tests/lib/rules/lines-around-comment.js
Refs #15016, fixes `lines-around-comment`.
Updated the `lines-around-comment` rule so that options `"allowBlockStart"` and `"allowBlockEnd"` apply to class static blocks.
These options already apply to both block statements and function bodies.
```js
/*eslint lines-around-comment: ["error", { "beforeLineComment": true, …
```
> feat: update lines-around-comment for class static blocks

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
Refs #15016, fixes `indent`.
This PR updates the `indent` rule to apply to class static blocks.
Also adds `StaticBlock.body` option to customize indentation level for the body of a class static block (default: 1). This option has been added to allow the bodies of the class static blocks to be aligned with the bodies of the …
> feat: update the indent rule for class static blocks

- docs/rules/complexity.md
- lib/rules/complexity.js
- tests/lib/rules/complexity.js
Refs #15016, fixes `complexity`.
Updated the `complexity` rule to apply to class static blocks. It already applies to functions and class field initializers.
> feat: update the complexity rule for class static blocks

- docs/rules/padded-blocks.md
- lib/rules/padded-blocks.js
- tests/lib/rules/padded-blocks.js
Refs #15016, fixes `padded-blocks`.
Updated the `padded-blocks` rule to apply to class static blocks.
```js
/* eslint padded-blocks: ["error", "always"] */
if (foo) { // applies to block statements
bar();
}
class C {
method() { // applies to function and method bodies
bar();
}
static { // should apply to class static blocks, …
```
> feat: update padded-blocks for class static blocks

- docs/rules/max-depth.md
- lib/rules/max-depth.js
- tests/lib/rules/max-depth.js
Refs #15016, fixes `max-depth`.
Updated the `max-depth` rule to treat class static blocks as separate contexts when calculating depth.
```js
/* eslint max-depth: ["error", 2] */
if (true) { // 1, ok
class C {
static { // does not count as a nested block, but it's still the same context
if …
```
> feat: update max-depth for class static blocks

- lib/rules/utils/ast-utils.js
- tests/lib/rules/space-unary-ops.js
- tests/lib/rules/utils/ast-utils.js
WIP
Remaining steps:
---
Fixes #14811.
[x] Other, please explain: Upgrade the espree.
This PR adds support for ES2022 private-in.
I have changed the `space-unary-ops` rule that we know needs to be changed.
I checked keyword-spacing rule, which is similar to space-unary-ops rule, but the rule already seems to work well with `return#x in obj`.
> feat: support for private-in syntax (fixes #14811)

- docs/rules/no-inner-declarations.md
- lib/rules/no-inner-declarations.js
- tests/lib/rules/no-inner-declarations.js
Refs #15016, fixes `no-inner-declarations`.
Updated the `no-inner-declarations` rule to allow declarations at the top level of class static blocks.
```js
/* eslint no-inner-declarations: ["error", "both"] */
class C {
method() {
function f() {} // ok
var x; // ok
}
static {
function f() {} // should be ok, too
var x; // …
```
> feat: update no-inner-declarations for class static blocks

- docs/rules/no-redeclare.md
- lib/rules/no-redeclare.js
- tests/lib/rules/no-redeclare.js
Refs #15016, fixes `no-redeclare`.
Updates the `no-redeclare` rule to report redeclarations in class static blocks.
```js
/* eslint no-redeclare: "error" */
class C {
static {
var a;
var a; // should be error
}
}
```
This is ready for review but marked as draft since it's using `eslint-scope` from GitHub.
> feat: update no-redeclare for class static blocks

- docs/rules/semi-style.md
- lib/rules/semi-style.js
- tests/lib/rules/semi-style.js
Refs #15016, fixes `semi-style`.
Fixed false positive in the `semi-style` rule: the last statement in a class static block should be allowed to have its semicolon on the same line when the option is `"first"`.
```js
/* eslint semi-style: ["error", "first"] */
if (foo) {  
bar(); // allowed
}
class C {
method() {
bar(); // …
```
> fix: update semi-style for class static blocks

- docs/rules/vars-on-top.md
- lib/rules/vars-on-top.js
- tests/lib/rules/vars-on-top.js
Refs #15016, fixes `vars-on-top`.
Fixed the `vars-on-top` rule to allow `var` declarations at the top of class static blocks.
```js
/*eslint vars-on-top: "error"*/
class C {
method() {
var foo; // allowed
}
static {
var foo; // should be allowed, too
}
}
```
> fix: update vars-on-top for class static blocks

- docs/rules/no-use-before-define.md
- lib/rules/no-use-before-define.js
- tests/lib/rules/no-use-before-define.js
Refs #15016, fixes `no-use-before-define`.
Updated logic related to class definition evaluation with class static blocks.
```js
/* eslint no-use-before-define: "error" */
class C {
static {
C.x = 42; // ok
}
}
const D = class {
static {
D.x = 42; // TDZ error
}
}
class E {
static {
a; // TDZ error
}
}
let a;
```
This is ready …
> feat: update no-use-before-define for class static blocks

- docs/rules/require-atomic-updates.md
- lib/rules/require-atomic-updates.js
- tests/lib/rules/require-atomic-updates.js
Fixes #11899 by adding an option to allow assignments to properties.
Added `allowProperties` option to the `require-atomic-updates` rule. When this option is set to `true`, the rule does not report assignments to properties. Default is `false`.
Also updated the documentation to clarify how this rule works.
Is the …
> feat: add `allowProperties` option to require-atomic-updates

- docs/rules/getter-return.md
Removed indentation from code example.
> docs: Dedent needlessly indented example in getter-return docs

- .github/workflows/ci.yml
[x] Other, please explain: Update CI jobs
Use node LTS version (v16) for jobs on CI.
No
> ci: use node `v16` for Verify Files

- docs/user-guide/command-line-interface.md
- lib/options.js
[x] Other, please explain: Update docs and CLI option guide to note that `--rulesdir` is deprecated. (It has been considered deprecated for some time but these docs were missing that info.)
Update docs and CLI option guide to note that `--rulesdir` is deprecated. (It has been considered deprecated for some time but these docs were missing that info.) …
> fix: mark --rulesdir option as deprecated in CLI docs

- karma.conf.js
[x] Other, please explain: Update test config to work automatically on M1 Macs.
On M1 Macs, we're able to use the Chromium binary that Puppeteer downloads as part of its install step. Prior to this change, running `npm test` on an M1 Mac would fail with "Cannot start ChromeHeadless" because it couldn't find the binary.
Should I do `os.platform !== …
> chore: Use default Chromium binary in M1 Mac tests

- README.md
- tools/update-readme.js
This fixes `tools/update-readme.js` script to stop producing multiple consecutive blank lines in README.md.
Updated `tools/update-readme.js` with a step that removes extra blank lines. Also ran it once and committed the resulting README.md.
This will fix linting, as we recently added a check for multiple consecutive blank …
> chore: fix update-readme to avoid multiple consecutive blank lines

- .github/PULL_REQUEST_TEMPLATE.md
Fix typo. `autofixing` -> `auto fixing`
I caught this via Grammarly. 
Is this correct?
> docs: fix typo in PR template

- lib/rules/max-lines-per-function.js
- tests/lib/rules/max-lines-per-function.js
Updated the max-lines-per-function rule to report only the count of those lines which exceed the specified max-lines limit, instead of reporting total lines from the start of the function to the end.
nope
> feat: report only lines that exceed the limit in max-lines-per-function

- docs/rules/no-constant-condition.md
- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
In working on #15296 I discovered a few constant expressions that that were not covered in `no-constant-condition`, so I figured I'd propose adding them here.
In working on #15296 I discovered a few constant expressions that that were not covered in `no-constant-condition`, so I figured I'd propose adding them here. This change add the ability to detect `ClassExpression` and `NewExpression`s as always truthy. I especially like that it catches the unintuitive fact that boxed primitives are always truthy.
These will now report errors:
```
if(new Foo()) {
// ...
}
if(new Number(x)) {
// ...
}
if(class {}) {
// ...
}
```
There's some overlap here with …
> feat: Treat Class/New Expressions as truthy in no-constant-condition

- docs/user-guide/configuring/language-options.md
- lib/shared/types.js
- package.json
- tests/lib/linter/linter.js
Fixes #15327
This PR updates Espree dependency to v9.2.0 to include https://github.com/eslint/espree/pull/522, documents the new parser option `allowReserved` in [specifying parser options](https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options), and adds a few linter tests for the option.
> feat: add `allowReserved` parser option

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Instead of crashing with an unhelpful message when encountering a test case that is missing `code`, or has a non-string value for `code` / `name`:
```pt
text.replace is not a function 
at ​​​sanitize​​​ ​./node_modules/eslint/lib/rule-tester/rule-tester.js:207
```
We are adding asserts with helpful output:
```
AssertionError …
```
> fix: add helpful message when test case has non-string `code`/`name`

- lib/rules/prefer-object-has-own.js
- tests/lib/rules/prefer-object-has-own.js
Resolve https://github.com/eslint/eslint/pull/15346#issuecomment-991417335
Improve autofix for the case - `return{}.hasOwnProperty.call(object, property)`
No
> fix: improve autofix of `prefer-object-has-own`

- tests/lib/rules/computed-property-spacing.js
[X] Other, please explain: Add more tests
Refers https://github.com/eslint/eslint/pull/15423
Add some more test cases in `computed-property-spacing`  for destructuring.
No
> test: add destructuring test cases for `computed-property-spacing`

- lib/rules/prefer-regex-literals.js
- tests/lib/rules/prefer-regex-literals.js
Fixes #15029
Add suggestions support to `prefer-regex-literals`
> feat: Suggestions support for `prefer-regex-literals`

- lib/rules/prefer-template.js
- tests/lib/rules/prefer-template.js
[ ] Add auto fixing to a rule
Resolve https://github.com/eslint/eslint/issues/15083
**Before**
code: `var foo = "Hello " + "world " + test` => fixed code: var foo = `${"Hello " + "world "}${test}`
**After**
code: `var foo = "Hello " + "world " + test `=> fixed code: var foo = ``Hello world ${  test}``
No
> fix: improve fixer of `prefer-template` rule

- docs/rules/no-useless-escape.md
In regex literals, `/[\[]/` and `/[a\-]/` contain useless escapes within character classes, but these cases are not very well-known, so I’ve included them. A recent Stack Overflow question (<https://stackoverflow.com/q/70322972/4642212>) prompted this PR, but of course there’s also issue #13826 _right here_: getting a linter …
> docs: Mention character classes in no-useless-escape

- lib/rules/id-match.js
- tests/lib/rules/id-match.js
Fixes #15123
Report invalid `property` names for `ObjectExpressions` when `property: true`, regardless the value of `onlyDeclaration` option.
```js
/* eslint "id-match": [
"error",
"^[^_]+$",
{
"properties": true,
"onlyDeclarations": true
}
] */
const foo = {
foo_one: 1, // error
bar_one: 2, // error
fooBar: 3 // ok
};
```
No
> feat: false negative with `onlyDeclarations` + `properties` in id-match

- tests/lib/linter/linter.js
Follow-up to #15387.
#15387 had tests with eslintrc configs only, this PR adds corresponding tests with flat config.
> test: add tests for `allowReserved` parser option with flat config

- lib/linter/linter.js
Removes unused parameter `filename` from `function getDirectiveComments` in `linter.js`.
Removed the unused parameter.
It seems that `filename` was unused from the start (`function getDirectiveComments` was added in https://github.com/eslint/eslint/commit/558ccba0fc8cafd969c7f18ff09be7fc0670536f).
`no-unused-vars` didn't report …
> refactor: remove unused parameter in `linter.js`

- docs/user-guide/configuring/rules.md
- lib/linter/apply-disable-directives.js
- lib/linter/linter.js
- tests/lib/linter/apply-disable-directives.js
- tests/lib/linter/linter.js
[X] Other, please explain: Allow `eslint-disable-next-line` directive to be of multiple lines
Fixes https://github.com/eslint/eslint/issues/14284
```js
/* eslint-disable-next-line global-require --
description on why this exception is seen as appropriate but past a 
comfortable reading line length */
const fizz = require(buzz); // ignored
/* eslint-disable-next-line 
no-alert
*/
alert("buzz"); // ignored
```
None
> feat: allow to define `eslint-disable-next-line` in multiple lines

- docs/user-guide/configuring/configuration-files.md
Fixes #14972
Some interest to make a PR was given by others in the past in the linked issue, but there hasn't been any activity from the original poster there after being asked for an update, so I decided to take a stab at fixing it. My apologies if that's considered inappropriate.
Added some wording that when searching for …
> docs: Document homedir is a configuration root

- docs/rules/no-restricted-exports.md
- lib/rules/no-restricted-exports.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-restricted-exports.js
Refs #15465, fixes `no-restricted-exports`.
Added a helper function `astUtils.getModuleExportName`, and updated `no-restricted-exports` rule to support tha new syntax.
> feat: Support arbitrary module namespace names in no-restricted-exports

- docs/rules/keyword-spacing.md
- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
Refs #15465, fixes `keyword-spacing`.
Updated `keyword-spacing` rule to check spacing around `as` in import/export specifiers.
For example, after this change each of these `as` will be reported:
```js
/* eslint keyword-spacing: "error" */
import { "a"as b } from "mod"; // Expected space(s) before "as"
export { b as"c" }; // …
```
> feat: Support arbitrary module namespace names in keyword-spacing

- lib/rules/quotes.js
- tests/lib/rules/quotes.js
Refs #15465, fixes `quotes`.
Fixed the `quotes` rule to not enforce backticks in a ModuleExportName position.
Before this change, `quotes` had false positives on `"foo"`, `"bar"`, `"baz"`, and `"qux"` in the following example:
```js
/* eslint quotes: ["error", "backtick"] */
import { "foo" as a } from "mod";
export { "bar" as …
```
> feat: Support arbitrary module namespace names in the quotes rule

- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
Refs #15465, fixes `camelcase`.
Just a small fix, for consistency.
```js
/* eslint camelcase: ["error", { ignoreImports: true }] */
import { a_b as a_b } from "mod"; // ok
import { "c_d" as c_d } from "mod"; // error
```
```js
/* eslint camelcase: ["error", { ignoreImports: true }] */ …
```
> feat: Support arbitrary module namespace names in the camelcase rule

- lib/rules/id-match.js
- tests/lib/rules/id-match.js
Fixes #15443
```js
/* eslint id-match: ["error", "^[^a]"] */
const foo = {
[a]: 1 // Error: Identifier 'a' does not match the pattern '^[^a]'
};
```
No
> feat: false negative with `property` option in `id-match`

- lib/cli-engine/cli-engine.js
Just a simple typo fix in the comments.
nope
> chore: Fixed Typo in CLI Engine

- docs/rules/no-useless-rename.md
- lib/rules/no-useless-rename.js
- tests/lib/rules/no-useless-rename.js
Refs #15465, fixes `no-useless-rename`.
Updated the `no-useless-rename` rule to work correctly with quoted module export names.
```js
/* eslint no-useless-rename: error */
import { "foo" as foo } from "mod"; // no error, false negative
export { foo as "foo" } from "mod"; // no error, false negative
export { …
```
> feat: Support arbitrary module namespace names in no-useless-rename

- docs/rules/no-restricted-imports.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
Refs #15465, fixes `no-restricted-imports`.
Updated the `no-restricted-imports` rule to correctly read quoted module export names.
```js
/*eslint no-restricted-imports: ["error", { paths: [{
name: "mod",
importNames: ["foo"]    
}]}]*/
import { "foo" as bar } from "mod"; // ok, false negative
export { "foo" } …
```
> feat: Support arbitrary module namespace names in no-restricted-imports

- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
Fixes #15467 by defining `isConstant` with `inBooleanPosition` set to `false` as meaning:
> For both string and number, if coerced to that type, the value will be constant.
Make `no-constant-condition` more correct. See #15467 for more information.
Would ESLint treat this as a breaking change? It will remove some false positives, but also -- in a few rare cases -- introduce a few false negatives.
> fix: Prevent false positives with no-constant-condition

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
* **ESLint Version:** latest
* **Node Version:** 16
* **npm Version:** 8
**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** espree
N/A
**What did you do? Please include the actual source code causing the …
> fix: Correctly consume RuleTester statics

- docs/developer-guide/contributing/pull-requests.md
- docs/developer-guide/development-environment.md
- docs/rules/no-mixed-operators.md
- docs/user-guide/command-line-interface.md
- docs/user-guide/getting-started.md
- docs/user-guide/migrating-from-jscs.md
Fixes #15518
Updating instances of shell code fences in `/docs` folder from old format ` ```sh
`
to new :` ```shell`
Updated all instances of shell code fences in the docs/ folder to ` ```shell `
The old format is not supported in the code formatter that is being used in the new website.
The ` ```shell ` is more universally …
> feat: Update shell code fences for new website

- docs/user-guide/command-line-interface.md
Updated the CLI docs to use local install install of global. We don't recommend global install and so this was confusing for new users.
Also updated some of the code fences to "bash" from "sh" for better compatibility with the new syntax highlighter in the new website.
Fixes #15498
Did I catch all of the examples?
> docs: Update CLI docs to prefer local install

- lib/rules/no-invalid-this.js
- tests/lib/rules/no-invalid-this.js
Fixes #15477.
Refactored `no-invalid-this` to use code path analysis, which is better for handling edge cases with `PropertyDefinition > *.value` and fixes the #15477 bug where `this` appears directly as a class field initializer.
> fix: no-invalid-this false positive in class field initializer

- docs/rules/array-callback-return.md
This file (and only this file in the repo) uses both `__` and `**` to create a strong emphasis. This change makes the file consistent by changing the single instance of `__` to `**`. The current version of `markdownlint` and an upcoming version of `markdownlint-cli` do/will flag this violation. The new rule can be disabled, but resolving it in this case is trivial.
More info: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md050
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-chang …
> docs: Address an upcoming violation of markdownlint rule MD050/strong-style.

- docs/user-guide/command-line-interface.md
Update typo in the comment.
N/A
> docs: Fixed typo in comment

- docs/developer-guide/nodejs-api.md
The relative link was missing the .MD extension so it wasn't working in the GitHub UI. The extension is included in the other links to that page in the doc
> chore: fix relative link

- docs/developer-guide/nodejs-api.md
- lib/cli-engine/cli-engine.js
- lib/eslint/eslint.js
- lib/linter/apply-disable-directives.js
- lib/linter/linter.js
- lib/shared/types.js
- tests/bin/eslint.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/linter/apply-disable-directives.js
- tests/lib/linter/linter.js
Implemented the RFC [2021-suppression-support](https://github.com/eslint/rfcs/tree/main/designs/2021-suppression-support).
Related issue #14784.
> feat: implement rfc 2021-suppression-support

- docs/rules/no-ex-assign.md
I spotted the verb `is` is missed in the [no-ex-assign rule's doc](https://eslint.org/docs/rules/no-ex-assign), so I just wanted to update this one.
> docs: add missed verb in `no-ex-assign` rule

- docs/rules/no-duplicate-case.md
Fixes #15552
Added 'When Not To Use It' section to docs for `no-duplicate-case`, with an example with side effects.
> docs: add 'when not to use it' section in no-duplicate-case docs

- .github/ISSUE_TEMPLATE/bug-report.yml
[x] Other, please explain: Update bug report template
https://github.com/eslint/eslint/issues/15552#issuecomment-1026368931 suggested linking the demo from our bug report template. For reproductions that use only ESLint without any plugins, someone from the team will often create one anyway, so this could save the team some time.
GitHub's issue form …
> chore: Suggest demo link in bug report template

- lib/config/flat-config-array.js
- lib/config/flat-config-helpers.js
- lib/config/rule-validator.js
- lib/rule-tester/flat-rule-tester.js
- tests/lib/config/flat-config-array.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
I implemented `FlatRuleTester` to allow folks to test their rules using flat config instead of eslintrc.
I also implemented tests for `FlatRuleTester`.
This class is not currently exported but will be when we do a developer preview.
Note: I copied over most of the `RuleTester` tests, but I did delete a block that was testing …
> feat: Implement FlatRuleTester

- docs/developer-guide/scope-manager-interface.md
Updates `scope-manager-interface` documentation with the often-used property [`Variable#scope`](https://github.com/eslint/eslint-scope/blob/ceb8bdd2cc31f67255e37a961096f9e3320abac6/lib/variable.js#L69-L73) that was missing in the docs.
Added the property to the docs.
> docs: add missing `Variable#scope` property in the scope manager docs

- .markdownlint.yml
- README.md
- docs/developer-guide/contributing/pull-requests.md
- docs/developer-guide/development-environment.md
- docs/user-guide/getting-started.md
- docs/user-guide/migrating-from-jscs.md
- docs/user-guide/migrating-to-5.0.0.md
I simply removed the use of $ as a prefix for shell commands without an output, since it is not used anywhere else than these few commands. I also modified the markdownlint config, so future $ prefixes will be removed when linting the markdown files. So to ensure consistency.
Nothing, really. It's a tiny change.
> docs: Remove the $ prefix in terminal commands

- .github/PULL_REQUEST_TEMPLATE.md
[x] Other, please explain: Fix an outdated link in the PR template
Updated an outdated link (that redirected to the OpenJS Foundation main page rather than the code of conduct page) to the code of conduct in the pull request template.
Not really.
> chore: fix outdated link to Code of Conduct in PR template

- lib/rules/function-paren-newline.js
- tests/fixtures/parsers/function-paren-newline/arrow-function-return-type.js
- tests/lib/rules/function-paren-newline.js
Fixes #15091
Fixed the code that finds the closing paren of ArrowFunctionExpression params to works the same as the code that finds the closing paren of FunctionDeclaration and FunctionExpression params. That should avoid finding a wrong paren in a typescript code with return types.
Marked as `feat` because this bug fix can …
> feat: fix bug with arrow function return types in function-paren-newline

- docs/rules/one-var.md
Refs #15592, updates documentation for `one-var` rule.
Added a correct example for `one-var` rule with the `"never"` option. The example has multiple variables declared in a for-loop initializer. This is a case where `"never"` does not require splitting into multiple declarations.
> docs: add one-var example with for-loop initializer

- package.json
Updates eslint-visitor-keys dependency to ^3.3.0.
There are no changes in eslint-visitor-keys that affect ESLint, this is just for consistency.
> chore: Upgrade to eslint-visitor-keys@3.3.0

- docs/user-guide/configuring/language-options.md
- package.json
Fixes #15580
Updates `@eslint/eslintrc` dependency to include https://github.com/eslint/eslintrc/pull/68, and updates documentation with the new `es2016`, `es2018`, `es2019`, and `es2022` environments.
~Marked as a draft because that version of `@eslint/eslintrc` hasn't been released yet.~
> feat: add `es2016`, `es2018`, `es2019`, and `es2022` environments

- package.json
- tests/lib/rules/no-eval.js
- tests/lib/rules/no-invalid-this.js
Updates `eslint-scope` to include https://github.com/eslint/eslint-scope/pull/87.
Updated package.json, and added tests for two core rules that will be affected by this change:
* `no-invalid-this` will have fewer warnings.
* `no-eval` will have more warnings.
Marked as draft as it currently uses eslint-scope from GitHub.
> feat: update eslint-scope to ignore `"use strict"` directives in ES3

- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
Fix https://github.com/eslint/eslint/issues/15572
```js
/*eslint camelcase: ["error", {"properties": "never", ignoreDestructuring: true}]*/
var { some_property } = obj; // OK
doSomething({ some_property }); // OK
```
No
> fix: false positive in `camelcase` with combined properties

- Makefile.js
When we restructured files at one point, we didn't update the `TEST_FILES` mocha pattern, so the tests in `tests/conf` are not being run.
Updated the `TEST_FILES` pattern to include `tests/conf` in test runs.
> chore: include `tests/conf` in test runs

- lib/config/flat-config-array.js
- package.json
- tests/_utils/test-lazy-loading-rules.js
- tests/fixtures/lazy-loading-rules/.eslintrc.js
- tests/fixtures/lazy-loading-rules/foo.js
- tests/lib/eslint/eslint.js
Performance improvement.
We have [`lazy-loading-rule-map`](https://github.com/eslint/eslint/blob/main/lib/rules/utils/lazy-loading-rule-map.js) which prevents loading all core rule modules when they are not necessary, and that part works well.
On the other hand, [`eslint-all.js`](https://github.com/eslint/eslint/blob/main/conf/es …
> perf: fix lazy loading of core rules

- tests/lib/cli-engine/file-enumerator.js
- tests/lib/eslint/eslint.js
I noticed we don't have any tests that would fail if there's something wrong with how is eslint passing `eslint:all` configuration to @eslint/eslintrc, or how @eslint/eslintrc handles that configuration. Such tests would be useful to catch possible regressions when there are some changes in that integration, like …
> test: add integration tests with built-in configs

- lib/linter/linter.js
Closes https://github.com/eslint/eslint/issues/15585
I think this is enough debug output, if parsing takes less <1ms then its cost is negligible anyway.
> feat: `--debug` prints time it takes to parse a file

- README.md
Updates babel links in README.md.
`babel-eslint` and `eslint-plugin-babel` packages are now deprecated and replaced by `@babel/eslint-parser` and `@babel/eslint-plugin` packages.
Updated the links.
> docs: update babel links

- docs/rules/block-spacing.md
- docs/rules/brace-style.md
- docs/rules/space-before-blocks.md
Refs https://github.com/eslint/eslint/discussions/15615
Updated documentation for three rules that control whitespace around curly braces of blocks to have links between each other in Related Rules. The rules are:
* block-spacing
* brace-style
* space-before-blocks
> docs: add links between rules about whitespace around block curly braces

- Makefile.js
- docs/developer-guide/unit-tests.md
This PR will close #15582.
It allows `npm test` to override the default mocha tests timeout of 10000ms by reading `ESLINT_MOCHA_TIMEOUT` environment variable.
> chore: read `ESLINT_MOCHA_TIMEOUT` env var in Makefile.js

- docs/developer-guide/contributing/README.md
- docs/developer-guide/contributing/pull-requests.md
Fix https://github.com/eslint/eslint/issues/15627
nothing.
> docs: update CLA information

- lib/cli-engine/cli-engine.js
- lib/cli-engine/file-enumerator.js
Load eslint:recommended and eslint:all configs via import instead file paths.
Fixes: #15575
I made changes to *cli-engine.js* and *file-enumerator.js* to pass in callbacks for getting built-in configs instead of file paths.
The main changes are in @eslint/eslintrc ([PR](https://github.com/eslint/eslintrc/pull/71)).
It should be merged and released first before changes here can be applied.
> fix: Avoid dirname for built-in configs.

- lib/rules/comma-dangle.js
- tests/lib/rules/comma-dangle.js
Fixes #15660
Extended the fix range in the `comma-dangle` rule to ensure that the element after which the comma is added/removed stays the last element after that autofix pass.
> fix: extend the autofix range in comma-dangle to ensure the last element

- docs/rules/sort-imports.md
I've added examples to docs/rules/sort-imports for the case of a single named import. Clarifying that it should be grouped with the default/single imports and not with the named/multiple imports.
I find the current behavior confusing and so do others #14259 #14570 #14735 #13655 #13222 #11159 #10878.
> docs: sort-imports add single named import example

- lib/rules/valid-typeof.js
- tests/lib/rules/valid-typeof.js
fixes #15591
check `undefined` and report
should we use `getStaticValue`?
> feat: `valid-typeof`: always ban `undefined`

- docs/user-guide/configuring/configuration-files.md
- [. ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
[. ] Documentation update
as discussed in #15670 I have added an external link to minimatch's read me in the docs
> docs: link to minimatch docs added. 

- docs/user-guide/configuring/rules.md
Closes https://github.com/eslint/eslint/issues/15662
Add clarification to how the `eslint-enable` rule works, and what to do if you want to guarantee a rule is always ignored.
> docs: Add clarification about `eslint-enable`

- docs/rules/no-constant-condition.md
- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
Identify `undefined` and `Boolean(somethingConstant)` as both being constant.
Expanded `no-constant-condition` to catch two types of additional cases:
```
if(undefined) {}
if(Boolean(1)) {}
```
> feat: Catch more cases in no-constant-condition

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fix https://github.com/eslint/eslint/issues/15611
Added a new option `destructuredArrayIgnorePattern` to the `no-unused-vars` rule.
```js
// With the following option set within eslintrc rules
// "no-unused-vars": ["error", { "destructuredArrayIgnorePattern": "^_" }],
const array = ['a', 'b', 'c'];
const [a, _b, c] = array;  // …
```
> feat: add `destructuredArrayIgnorePattern` option in `no-unused-vars`

- package.json
- tests/fixtures/ignored-paths/.eslintIgnoreWithEscapedBrackets
- tests/fixtures/ignored-paths/.eslintignoreWithEscapedBrackets
- tests/fixtures/ignored-paths/brackets/[index.js
- tests/fixtures/ignored-paths/brackets/[index].js
- tests/fixtures/ignored-paths/brackets/index.js
- tests/fixtures/ignored-paths/brackets/index].js
- tests/lib/eslint/eslint.js
Fixes #15642 by updating `@eslint/eslintrc` dependency, which in turn updates its `ignore` dependency to v5.2.0.
The root cause of the problem is a bug in ignore v4.0.6. The bug has been fixed in [v5.1.5](https://github.com/kaelzhang/node-ignore/releases/tag/5.1.5).
Updated package.json with the new version of `@eslint/eslintrc` …
> fix: escaping for square brackets in ignore patterns

- lib/rules/padding-line-between-statements.js
* **ESLint Version:** 8.11.0
* **Node Version:** 16.13.2
* **ajv version:** 8.10.0
If you run AJV in strict mode, you will get error:
```
Error: strict mode: "additionalItems" is ignored when "items" is not an array of schemas
```
see …
> chore: Error: strict mode: "additionalItems" is ignored when "items" is not an array of schemas

- docs/rules/no-invalid-this.md
- lib/rules/no-eval.js
- lib/rules/no-invalid-this.js
- tests/lib/rules/no-eval.js
- tests/lib/rules/no-invalid-this.js
This bug fix produces more warnings from the `no-eval` rule, and thus this change is marked as `feat`.
* **ESLint Version:** v8.11.0
* **Node Version:** 16.14.0
default …
> feat: fix logic for top-level `this` in no-invalid-this and no-eval

- lib/cli-engine/formatters/html.js
- lib/linter/apply-disable-directives.js
- messages/all-files-ignored.js
- messages/extend-config-missing.js
- messages/failed-to-read-json.js
- messages/file-not-found.js
- messages/no-config-found.js
- messages/plugin-invalid.js
- messages/plugin-missing.js
- messages/print-config-with-directory-path.js
- messages/whitespace-found.js
`String#trimLeft`/`String#trimRight` are defined in Annex B, for web compatibility.
We should always use `String#trimStart`/`String#trimEnd`.
Replaced all occurrences of `trimLeft` with `trimStart`, and `trimRight` with `trimEnd`.
The new methods should be available in all Node.js versions ESLint supports. …
> chore: replace `trimLeft`/`trimRight` with `trimStart`/`trimEnd`

- .eslintrc.js
Removes configurations related to `lib/init` from our `.eslintrc.js` config file. We removed `lib/init` in https://github.com/eslint/eslint/pull/15150, so that directory doesn't exist anymore and these configurations are unnecessary.
Updated `.eslintrc.js`.
> chore: remove `lib/init` from eslint config

- docs/developer-guide/nodejs-api.md
- docs/developer-guide/working-with-custom-formatters.md
- lib/cli-engine/cli-engine.js
- lib/eslint/eslint.js
- lib/shared/types.js
Fixes #15654
[x] Other, please explain: type definitions changed, see below.
* Add type `FormatterFunction`
* Rename type `Formatter` to `LoadedFormatter`
* Use `FormatterFunction` in the return type of `CLIEngine.getFormatter`
* Move type `LintResult` to shared types because it is referenced by `FormatterFunction`
* Fix a misspelling of `LintResult` in …
> docs: disambiguate types `FormatterFunction` and `LoadedFormatter`

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
* **ESLint Version:** v8.12.0
* **Node Version:** 16.14.0
default
<details>
```js …
```
> fix: invalid operator in operator-assignment messages

- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-inline-comments.js
- tests/lib/rules/utils/ast-utils.js
* **ESLint Version:** v8.13.0
* **Node Version:** 16.14.0
default
<details>
```js …
```
> fix: update `astUtils.isDirectiveComment` with `globals` and `exported`

- packages/eslint-config-eslint/default.yml
add no-constant-binary-expression to eslint-config-eslint. it was introduced in [v8.14.0](https://github.com/eslint/eslint/releases/tag/v8.14.0).
no.
> chore: enable no-constant-binary-expression in eslint-config-eslint

- docs/src/rules/no-constant-binary-expression.md
[X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
The doco had a typo, and said `x` instead of `a` in a code comment.
> Fixed typo in code comment

- docs/src/rules/no-control-regex.md
Fixes #15653
Updated documentation for `no-control-regex` to clarify the purpose of this rule.
> docs: clarify no-control-regex rule

- docs/src/rules/prefer-object-spread.md
Updated docs related to `prefer-spread` rule according to tests cases. Added missing examples of [**spread syntax**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals).
> docs: add more examples for prefer-object-spread

- docs/src/developer-guide/working-with-rules.md
Updates info about rule docs directory in `working-with-rules.md`.
Updated `docs/rules` -> `docs/src/rules`
This also adds back `.md` in the `no-extra-semi.md` example, which was I believe mistakenly removed in https://github.com/eslint/eslint/pull/15782.
> docs: update docs directory in working-with-rules

- docs/src/developer-guide/working-with-rules.md
`SourceCode#getJSDocComment()` method was marked as deprecated in ESLint v5.10.0 (PR https://github.com/eslint/eslint/pull/11145, [blog post](https://eslint.org/blog/2018/11/jsdoc-end-of-life)), but it still appears as a non-deprecated method in the [Working with Rules](https://eslint.org/docs/developer-guide/working-with-rules) …
> docs: mark `SourceCode#getJSDocComment` deprecated in working-with-rules

- docs/src/rules/no-underscore-dangle.md
- lib/rules/no-underscore-dangle.js
- tests/lib/rules/no-underscore-dangle.js
- This fix and address https://github.com/eslint/eslint/issues/15810 and adds a new option `enforceInClassFields`. 
- Added test cases and passing.
- Changed documentation accordingly.
Discussion about this fix is on https://github.com/eslint/eslint/issues/15810
> feat: add `enforceInClassFields` option to no-underscore-dangle

- templates/formatter-examples.md.ejs
https://eslint.org/docs/user-guide/formatters/ currently has two `<h1>`:
* 'Documentation' generated from the `title` key.
* 'ESLint Formatters' generated from markdown heading `#`.
Updated `title` to be 'ESLint Formatters' and removed markdown heading to avoid duplicate h1.
> docs: fix h1 heading on formatters page

- lib/rules/function-paren-newline.js
- tests/lib/rules/function-paren-newline.js
`function-paren-newline` crashes when see the code like this:
```js
new new Boolean();
```
This code has no sense, but this is correct JavaScript:
It throws [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) when trying to execute first `new` after second one returns instance …
> fix: function-paren-newline crash on "new new Foo();"

- docs/src/user-guide/configuring/configuration-files.md
- docs/src/user-guide/configuring/index.md
Change "an `.eslintrc.js`" to "a `.eslintrc.js`"
> docs: Fix some grammar issues

- docs/src/rules/no-mixed-operators.md
Refs #15870
The opening section in `no-mixed-operators` provides some examples that are not errors by default, which can be confusing for users, as in #15870.
Removed examples with conditional expressions, because this rule does not check them by default.
> docs: remove confusing examples for no-mixed-operators

- package.json
Update [`globals`](https://github.com/sindresorhus/globals/releases/tag/v13.15.0) dependency to add `structuredClone` in global variables (fix https://github.com/eslint/eslint/issues/15859).
Other global variables have been added: [globals/v13.6.0...v13.15.0](https://github.com/sindresorhus/globals/compare/v13.6.0...v13.15.0#diff …
> feat: Update global variables

- docs/.eleventy.js
- docs/src/_includes/components/docs-toc.html
- docs/src/_includes/layouts/doc.html
- docs/src/rules/block-scoped-var.md
- docs/src/rules/no-ternary.md
To get the new docs site up and running, I've made a couple changes to the way rule pages are rendered:
1. Related rules are now represented in the `related_rules` frontmatter key instead of plain markdown
1. Further reading links are now represented in the `further_reading` frontmatter key instead of plain markdown
This allows …
> chore: Refactor rule docs format

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/stale.yml
[X] Other, please explain: CI maintenance
This PR upgrades all official GitHub actions to their latest versions.
CI passes.
> Upgrade official GitHub actions to latest versions

- package.json
- tests/lib/rule-tester/rule-tester.js
https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/releases/tag/v4.2.0
it detects nested test cases, causing a build failing: https://github.com/eslint/eslint/runs/6445533712?check_suite_focus=true
no.
> chore: upgrade eslint-plugin-eslint-plugin@^4.2.0

- docs/.eleventy.js
Fixes links in the `related_rules` shortcode to work when the site is deployed to /docs.
Added `pathPrefix` to links.
> docs: fix absolute paths in related rules shortcode to work from /docs

- docs/src/rules/no-control-regex.md
- lib/rules/no-control-regex.js
- tests/lib/rules/no-control-regex.js
Fixes #15809
Updated the `no-control-regex` rule to pass the `u` flag to the `regexpp` validator when the regex has the `u` flag. As a consequence, the rule will now:
* Report Unicode code point escapes, such as `/\u{C}/u`.
* Report errors in regular expressions that were not parsable without the `u` flag, such as …
> feat: check Unicode code point escapes in no-control-regex

- .github/workflows/docs-deploy.yml
- docs/package.json
I created a workflow that will trigger a docs site deploy whenever there is a release.
Because the docs site currently deploys every time a pull request is merged, the site will always be ahead of the last release (not desirable). I switched off automatic publishing so merges won't automatically be deployed, but that means we …
> chore: Add deploy workflow for docs site

- docs/src/rules/no-misleading-character-class.md
- lib/rules/no-misleading-character-class.js
- tests/lib/rules/no-misleading-character-class.js
Continued from https://github.com/eslint/eslint/pull/15279.
Adds Unicode flag suggestion in the `no-misleading-character-class` rule.
Addressed code reviews from https://github.com/eslint/eslint/pull/15279.
> feat: add Unicode flag suggestion in no-misleading-character-class

- tests/lib/rules/no-restricted-imports.js
Adds a test.
This PR adds a test case to the `no-restricted-imports` rule to cover an edge case not accounted for—[NodeJS subpath imports](https://nodejs.org/api/packages.html#subpath-imports). No changes were made to the actual rule.
In NodeJS, you can define a subpath import by adding the following to your package.json:
``` …
```
> test: ensure no-restricted-imports works with NodeJS subpath imports

- docs/package.json
- docs/src/assets/scss/tokens/themes.scss
Use dart-sass instead of node-sass since node-sass is deprecated.
> docs: use-dart-sass instead of node-sass

- lib/shared/types.js
This PR updates the types to align with changes introduced in ESLint v8.0.0:
* Adds `RuleMeta.hasSuggestions`
* Removes `RuleMetaDocs.category` as we are no longer using this property.
Updated `lib/shared/types.js`.
> chore: update Rule typedefs

- docs/src/assets/js/components-index.js
- docs/src/assets/js/main.js
Use **addEventListener()** instead of matchMedia().addListener() since matchMedia().addListener() is deprecated.
> chore: use addEventListener instead of addListener

- lib/rules/no-octal.js
- tests/lib/rules/no-octal.js
Separated this from the other typo changes because I wasn't sure if this would be considered a breaking change. It may affect translations relying on the current messageID value
> fix: typo ocatal -> octal

- bin/eslint.js
- lib/eslint/eslint.js
- lib/rules/function-paren-newline.js
- lib/rules/max-statements.js
- lib/rules/no-constant-binary-expression.js
- lib/rules/no-implicit-coercion.js
- lib/rules/no-loop-func.js
- lib/rules/no-new-object.js
Ran cSpell across the repo and submitting PRs by folder area
> fix: cleanup typos

- docs/src/_data/languages.json
- docs/src/assets/js/focus-visible.js
- docs/src/developer-guide/nodejs-api.md
- docs/src/rules/eol-last.md
- docs/src/rules/key-spacing.md
Ran cSpell accross the repo, and submitting them by subject area
> docs: cleanup typos

- docs/src/_includes/layouts/doc.html
Added the "Resources" section to rule pages.
I only added "Rule source" and "Test source", but not "Documentation source" because we have a big "Edit Page" button right under this section. Is that okay?
> docs: Add Resources section to rule pages

- docs/package.json
- docs/src/_includes/layouts/base.njk
- docs/src/assets/js/themes.js
There are theme flashes in default and this code is not necessary at all 
Removed unwanted code that causes flashing (similar to https://github.com/eslint/new.eslint.org/pull/196/files)
Once check if flashing occurs with this preview build
> chore: avoid theme flashes

- docs/src/_data/further_reading_links.json
- docs/src/rules/prefer-exponentiation-operator.md
I changed the MDN link for Exponentiation operator
> docs: Update Exponentiation operator MDN link

- lib/rules/indent.js
- tests/lib/rules/indent.js
Fixes #15930
This bug fix can produce more warnings and is therefore marked as `feat`.
The removed lines of code had no effect (when I removed them, no test cases were failing) because [`"*"(node)`](https://github.com/eslint/eslint/blob/001b2a130f97f2e242a34ec316dc05c5fad31764/lib/rules/indent.js#L1603-L1611) overwrites …
> feat: fix indent bug with semicolon-first style

- docs/src/rules/no-undef.md
- docs/src/user-guide/command-line-interface.md
- docs/src/user-guide/configuring/ignoring-code.md
- docs/src/user-guide/configuring/index.md
- docs/src/user-guide/configuring/language-options.md
- docs/src/user-guide/configuring/plugins.md
- docs/src/user-guide/configuring/rules.md
Some links that should point to, I believe, documents from the same version, are absolute links so they always open documents from the latest version.
Changed several `https://eslint.org/docs/...` absolute links to relative ones.
> docs: change some absolute links to relative

- .github/workflows/ci.yml
- .github/workflows/docs-deploy.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- Makefile.js
- docs/.eleventy.js
- docs/src/_includes/components/nav-version-switcher.html
- docs/src/_includes/components/version-switcher.html
- docs/src/_includes/partials/versions-list.html
Implements /docs/head and /docs/latest as ways to load the docs from
the HEAD branch and from the latest release.
This change allows us to use two entrypoints for the docs site:
1. `/docs/head` - this is auto-published every time a change has been pushed to the `main` branch. Local development will also use this path prefix.
2. …
> docs: Switch to version-relative URLs

- docs/.eleventy.js
Follow-up to https://github.com/eslint/eslint/pull/15967.
I noticed that links to migration documents like `.../migrating-to-8.0.0` don't work in local previews. Because of the dots in the URL, they are interpreted as files with an extension so they are not getting the `.html` suffix appended.
Tweaked the url rewriting logic to …
> chore: tweak URL rewriting for local previews

- docs/.eleventy.js
When I run `npm start` and open `http://localhost:2023`, I'm getting:
```
Cannot GET /docs/head
```
This is because eleventy redirects to `pathPrefix`, which is `/docs/head` without a trailing slash, and we are now appending `.html` to these URLs.
I'm guessing we didn't notice this in https://github.com/eslint/eslint/pull/15967 …
> chore: add trailing slash to `pathPrefix`

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Tweaked the `no-unused-vars` rule to treat `for..of` loops and `for..in` loops the same
Sorry for the labels 🙈 not sure if this is a bug or a feature 
no-unused-vars`
Fewer
**How will the change be implemented? (New …
> fix: Make no-unused-var function the same way in for..of loops as for..in loops

- docs/.eleventy.js
- docs/package.json
- docs/src/assets/scss/docs.scss
- docs/src/library/code-blocks.md
- docs/src/rules/semi.md
Created two markdown containers: `correct` and `incorrect` that allow us to format code blocks in rule pages as either correct or incorrect.
I updated the `semi` docs and the component library page as examples of how to use the containers.
I also needed to make a similar change in the current website for compatibility: …
> docs: Add correct/incorrect containers

- docs/src/developer-guide/working-with-rules.md
- lib/linter/linter.js
- lib/linter/timing.js
Fix https://github.com/eslint/eslint/issues/15952
Not sure if it should be `feat` or `fix` 😕 .
> feat: account for rule creation time in performance reports

- lib/shared/deprecation-warnings.js
[X] Other, please explain: remove unused code from the core
This PR removes the two unused deprecation messages `ESLINT_PERSONAL_CONFIG_LOAD` and `ESLINT_PERSONAL_CONFIG_SUPPRESS` from deprecation-warnings.js. Both keys are orphaned since #13762. The file deprecation-warnings.js is not exported in package.json and is only imported internally in …
> chore: remove unused deprecation warnings

- docs/package.json
Similar to 
- https://github.com/eslint/new.eslint.org/pull/223
Can't run `images` command in parallel for the docs same applies for `start` and `build` so revamp it 
Check built version
> build: remove unwanted parallel and image-min for dev server

- docs/src/_includes/components/rule-list.macro.html
- docs/src/_includes/components/rule.macro.html
- docs/src/assets/scss/components/rules.scss
- docs/src/library/rule-list.md
Fixes two problems with 'Replaced by' lists of rules below deprecated and removed rules on the new docs site:
1. Replacement rule links are not clickable.
2. Our template treats `replacedBy` as a single rule name, but it's an array of rule names. This works by chance when there is only one replacement rule, but it doesn't work …
> chore: fix 'replaced by' rule list

- docs/.eleventy.js
- docs/src/static/robots.njk
- docs/src/static/sitemap.njk
Fixes sitemap for the new docs site.
* Changed the URLs in `<loc>` to be absolute (e.g., `https://eslint.org/docs/latest/rules/accessor-pairs`) as required by https://sitemaps.org/protocol.html.
* Fixed the code that generates `<changefreq>`. It was always empty (`<changefreq></changefreq>`), which is technically invalid against …
> chore: fix sitemap

- docs/.eleventy.js
- docs/src/_includes/layouts/base.html
Refs eslint/new.eslint.org#231
Updated the base layout to include `<meta name="robots" content="noindex">` if `process.env.BRANCH !== "latest"`.
> chore: add noindex meta tag

- .markdownlint.yml
- docs/src/developer-guide/development-environment.md
- docs/src/developer-guide/source-code.md
- docs/src/developer-guide/unit-tests.md
- docs/src/pages/rules.md
- docs/src/rules/no-irregular-whitespace.md
- docs/src/user-guide/command-line-interface.md
- docs/src/user-guide/configuring/configuration-files.md
- docs/src/user-guide/configuring/ignoring-code.md
Build setup for the new docs site does not treat indented text as code blocks.
This is observable in most examples on https://new.eslint.org/docs/head/user-guide/command-line-interface
and most notably here: https://new.eslint.org/docs/head/rules/no-irregular-whitespace#rule-details
I'm not sure where exactly is this configured, …
> docs: use only fenced code blocks

- Makefile.js
Improve robustness of internal `npm run lint` command.
In the Makefile, we run markdownlint on all of our documentation files.
We previously had a naive check to ignore files that are mentioned in `.markdownlintignore`. But this didn't handle nested `node_modules` which will be created after running `npm install` in folders like `docs/`.
In this PR, I have updated the check to use the existing [ignore](https://www.npmjs.com/package/ignore) library to correctly [filter](https://github.com/kaelzhang/node-ignore#addpatterns-arraystring--ignore-this) out the gitignore-style ignore patterns in `.markdownlintignore`.
Note that the reason we have to manually do this ignore-filtering is because [markdownlint](https://github.com/DavidAnson/markdownlint/markdownlint) does [not …
> chore: correctly use .markdownlintignore in Makefile

- docs/src/_includes/layouts/base.html
This adds `<base>` to each page so relative URLs work correctly.
Fixes #15844
Please double-check the deploy preview because this can't really be tested locally.
> docs: Add base href to each page to fix relative URLs

- docs/.eleventy.js
- docs/package.json
Making use of slugify function from old site
reference:
- https://github.com/eslint/eslint/pull/16066#issuecomment-1168689803
There is one another slugger library 
- https://github.com/eslint/eslint/blob/b6aee9591ecc2e2f5738ab8bef20faac1e05b5c3/docs/package.json#L42
that we add as filter in eleventy and have used it inside only …
> chore: use `github-slugger` for markdown anchors

- lib/linter/linter.js
- tests/lib/linter/linter.js
Especially when developing a custom rule, it's possible to return the wrong data type in the rule's `create(context)` function. In particular, this often happens when attempting to bail out of a rule early, as shown below. The user needs to use `return {};` to bail out instead of null/undefined. 
```js
meta: { …
```
> fix: throw helpful exception when rule has wrong return type

- lib/rules/indent.js
- tests/lib/rules/indent.js
This bug fix can produce more warnings.
I noticed this bug while working on https://github.com/eslint/eslint/pull/15951.
* **ESLint Version:** v8.18.0
* **Node Version:** 16.14.0
**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you …
> feat: fix handling of blockless `with` statements in indent rule

- docs/src/rules/no-restricted-imports.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
Resolves #14274 
This change expands the functionality of `no-restricted-imports` to allow restricting only specific named imports from an import pattern ban. For example, if I wanted to ban importing `Foo` from `'../../../my/relative/module'`, but importing `Bar` from the matched pattern is OK, I can now do that:
``` …
```
> feat: add importNames support for patterns in no-restricted-imports

- templates/formatter-examples.md.ejs
Updates `formatter-examples.md.ejs` to avoid markdown lint error: https://github.com/eslint/eslint/runs/7158892591
This adds a blank line after `### html`.
I tested this locally.
> chore: update formatter examples template to avoid markdown lint error

- docs/src/rules/arrow-body-style.md
- docs/src/rules/constructor-super.md
These two rules still have duplicate descriptions on the website:
* https://eslint.org/docs/latest/rules/arrow-body-style
* https://eslint.org/docs/latest/rules/constructor-super
Removed descriptions from the markdown.
It seems these descriptions were accidentally restored while fixing merge conflicts …
> docs: remove remaining duplicate rule descriptions

- docs/src/_includes/layouts/doc.html
- docs/src/assets/scss/components/rules.scss
Reference : https://github.com/eslint/eslint/issues/15977
The rule category on screen size 768px
Rule category on screen size 1024px
Rule category on screen size 1440px
Single rule-category
Pages with two rule-category
> docs: fix UI bug on rules index and details pages

- docs/src/rules/camelcase.md
- docs/src/rules/func-name-matching.md
- docs/src/rules/key-spacing.md
- docs/src/rules/max-lines-per-function.md
- docs/src/rules/max-lines.md
- docs/src/rules/no-class-assign.md
- docs/src/rules/no-compare-neg-zero.md
- docs/src/rules/no-const-assign.md
- docs/src/rules/no-continue.md
- docs/src/rules/no-eval.md
- docs/src/rules/no-extra-strict.md
- docs/src/rules/no-global-assign.md
- docs/src/rules/no-magic-numbers.md
- docs/src/rules/no-mixed-operators.md
- docs/src/rules/no-native-reassign.md
- docs/src/rules/no-restricted-exports.md
- docs/src/rules/no-restricted-globals.md
- docs/src/rules/no-restricted-imports.md
- docs/src/rules/no-restricted-modules.md
- docs/src/rules/no-restricted-properties.md
- docs/src/rules/no-unsafe-finally.md
- docs/src/rules/one-var.md
- docs/src/rules/sort-imports.md
- docs/src/rules/space-after-keywords.md
- docs/src/rules/space-unary-ops.md
- docs/src/rules/space-unary-word-ops.md
- docs/src/rules/spaced-comment.md
- docs/src/rules/spaced-line-comment.md
- docs/src/rules/strict.md
- docs/src/rules/vars-on-top.md
I noticed when we have multiple examples of correct/incorrect code as separate code blocks, only the first code block has ✓/ x.
For example https://eslint.org/docs/latest/rules/no-restricted-imports#examples
Wrapped each of the remaining code blocks in a `::: correct` / `::: incorrect` container, so that consecutive examples now …
> docs: add missing correct/incorrect containers

- docs/src/assets/js/themes.js
If theme is present in local storage then take that to highlight the theme change button else highlight the default system theme. 
Check if correct theme is highlighted in theme selector after clearing the local storage
> docs: preselect default theme

- docs/src/developer-guide/working-with-rules.md
This PR removes the `meta.docs.category` field from the `working-with-rules` page (https://eslint.org/docs/latest/developer-guide/working-with-rules). As discussed in https://github.com/eslint/generator-eslint/issues/131, it sounds like this field was historically used for grouping core rules on the website, but was bulk removed …
> docs: remove unused meta.docs.category field in working-with-rules page

- docs/src/_includes/components/docs-toc.html
Hide the `Table of Contents` section when it is content empty.
Hide the `Table of Contents` section when it is content empty.
| Before  | After  |
| ------------- | ------------- |
| <img width="600" alt="image" src="https://user-images.githubusercontent.com/30730124/177206073-fade53f1-9c9e-4da9-a2af-896b5d03352c.png">  |  <img …
> docs: don't show toc when toc content empty

- lib/linter/linter.js
- tests/lib/linter/linter.js
> feat: catch preprocess errors

- lib/rules/no-warning-comments.js
- tests/lib/rules/no-warning-comments.js
* **ESLint Version:** 8.19.0
* **Node Version:** v16.15.1
* **npm Version:** 8.11.0
<details>
```js
rules: { …
```
> fix: no-warning-comments rule escapes special RegEx characters in terms

- docs/src/_data/further_reading_links.json
- docs/src/rules/no-constant-binary-expression.md
Link to the blog post about no-constant-binary-expression in that rule's docs
Nope
> docs: Link to blog post in no-constant-binary-expression

- docs/src/maintainer-guide/governance.md
- docs/src/maintainer-guide/pullrequests.md
Added to the governance docs to mention the newly-formed website team.
Do the roles and responsibilities make sense? Are the restrictions on which pull requests they can merge reasonable?
> docs: Add website team details

- templates/blogpost.md.ejs
Updated draft blog post template
I updated the autogenerated blog post template to include `draft: true` in the frontmatter. This will prevent the blog post from being published until someone manually removes that line during the release process.
> chore: Mark autogenerated release blog post as draft

- .eslintrc.js
- package.json
- packages/eslint-config-eslint/default.yml
- packages/eslint-config-eslint/package.json
- tests/_utils/test-lazy-loading-rules.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/linter/code-path-analysis/code-path.js
- tools/fetch-docs-links.js
[ x] Other, please explain: 
`eslint-plugin-node` is no longer actively maintained. this one is just a maintained fork.
it's main improvement is better esm supports. you can see the latest releases: https://github.com/weiran-zsd/eslint-plugin-node/releases
we may transfer the fork to the new org `@eslint-community`, and rename it to …
> chore: switch to eslint-plugin-node's maintained fork

- docs/src/rules/sort-keys.md
- lib/rules/sort-keys.js
- tests/lib/rules/sort-keys.js
Fixes https://github.com/eslint/eslint/issues/12759
Add new `allowLineSeparatedGroups` option to the `sort-keys` rule.
```js
/*eslint sort-keys: ["error", "asc", {allowLineSeparatedGroups: true}]*//
var obj = {
b: 1,
c: 2,
a: 3, // no error
d: 4
};
```
See [docs preview](https://deploy-preview-16138--docs-eslint.netlify.app/rules …
> feat: add new `allowLineSeparatedGroups` option to the `sort-keys` rule

- lib/rules/key-spacing.js
- package.json
- tests/lib/rules/key-spacing.js
Fix https://github.com/eslint/eslint/issues/15914
The following code doesn't report any error anymore.
```js
/* eslint "key-spacing": [2, { "align": "value" }] */
const foo = {
"a": "bar",
"𐌘": "baz",
[𐌘]: "foo"
};
```
> feat: improve the key width calculation in `key-spacing` rule

- docs/src/user-guide/configuring/configuration-files-new.md
The text that introduces the relevant config example says "you can also shorten the configuration to this", but in the config example that follows nothing is shorter than in the previous config example. This PR fixes the config example by using a shorthand property name for `jsdoc` (which I'm assuming was the intention).
No.
> docs: use shorthand property name in example

- docs/src/rules/object-shorthand.md
- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
Fixes #15796
Added new `methodsIgnorePattern` option to the object-shorthand rule.
> feat: add `methodsIgnorePattern` option to object-shorthand rule

- docs/src/user-guide/migrating-from-jscs.md
Add anchor link for “migrating from jscs”
> docs: add anchor link for "migrating from jscs"

- docs/src/rules/no-warning-comments.md
- lib/rules/no-warning-comments.js
- tests/lib/rules/no-warning-comments.js
Fix: #16103 
Regular Expression generated for terms in function `convertToRegExp` needed the multi-line flag, and a new function in AST-utils to extract the meaningful comment text from comments by stripping decorative punctuation.
> feat: no-warning-comments support comments with decoration

- lib/linter/config-comment-parser.js
Simplifies function `parseListConfig` in the config comment parser by removing a step that removes whitespace around commas before splitting the string. This removes a polynomial-time regular expression and therefore fixes a problem reported by CodeQL on recent PRs (see https://github.com/eslint/eslint/pull/16235 and …
> refactor: simplify `parseListConfig`

- docs/src/assets/scss/components/docs-index.scss
- docs/src/assets/scss/components/docs-navigation.scss
- docs/src/assets/scss/components/index.scss
- docs/src/assets/scss/components/search.scss
- docs/src/assets/scss/docs.scss
- docs/src/assets/scss/tokens/spacing.scss
- docs/src/assets/scss/utilities.scss
Updates css for the new docs site.
We have `min-width: 1023px` in several media queries. This seems like an off-by-one error as it matches >= 1023px which was probably not the intention.
Changed `min-width: 1023px` to `min-width: 1024px` in media queries.
`max-width: 800px` in multiple places also looks suspicious, but I wasn't …
> chore: fix off-by-one `min-width: 1023px` media queries

- tests/lib/rules/no-extra-parens.js
Uncomments two `no-extra-parens` tests from https://github.com/eslint/eslint/pull/12490. The tests were commented out because parser didn't allow parentheses around the assignment target in rest properties. This has recently been fixed in Acorn (Espree PR https://github.com/eslint/espree/pull/554).
Uncommented the tests.
> test: add no-extra-parens tests with rest properties

- docs/src/rules/id-denylist.md
I added a small note to `id-denylist` documentation to clarify the usage of configuration array. It took me some time to realise the first element of the array specifies the severity of the rule even tough it also seems like one of the disallowed identifiers. So this small addition addresses the confusion. Also you can see [this …
> docs: Improve id-denylist documentation

- Makefile.js
it was crashing as eslint treat the `.eslintrc.yml` to be js.
this commit changes the generated configs to `eslint.config.js`.
refs: https://github.com/eslint/eslint/issues/16255#issuecomment-1229817918
> chore: fix `npm run perf` crashes

- Makefile.js
- docs/package.json
- docs/src/_data/eslintVersion.js
Fixes https://github.com/eslint/eslint/issues/16212
Remove dependency on root `package.json` by generating `eslintVersion.js` with the version hardcoded
Do we want to keep the ability to read the version from `process.env`? Else, we can altogether remove the `eslintVersion.js` file and always have it generated
> docs: copy & use main package version in docs on release

- Makefile.js
- eslint.config.js
`lint:docsjs` script is intended to lint `docs/.eleventy.js` file. Currently, after switching to `eslint.config.js`, it doesn't lint that file. This went unnoticed because of https://github.com/eslint/eslint/issues/16260 (the script runs `eslint docs` command; the command doesn't really lint any files in `docs`, but it …
> chore: enable linting `.eleventy.js` again

- docs/src/assets/scss/docs.scss
Just happened to see this [annoying double tap issue on mobile Safari](https://css-tricks.com/annoying-mobile-double-tap-link-issue/) when I was using my cellphone to check eslint docs.
https://user-images.githubusercontent.com/1091472/189482786-5fee5813-326c-402c-97d1-bb2c6b9fc71f.MP4
As you can see, the first tap won't open …
> docs: fix mobile Safari double tap issue

- lib/eslint/eslint-helpers.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
Glob patterns must be normalized to posix-style file paths before being passed in to globby.
Fixes #16259
I ensured that glob patterns are normalized to posix-style slashes before passing in to globby.
I also updated tests to verify that this fix worked.
> fix: Ensure that glob patterns are normalized

- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
Fix https://github.com/eslint/eslint/issues/16266
> fix: improve autofix for the `prefer-const` rule

- docs/src/user-guide/configuring/configuration-files-new.md
> docs: fix typo

- docs/src/developer-guide/source-code.md
`[https://help.github.com/articles/set-up-git/](https://help.github.com/articles/set-up-git/)` -> `<https://help.github.com/articles/set-up-git/>`
> docs: use more clean link syntax

- lib/rules/strict.js
- tests/lib/rules/strict.js
Fixes #16304
In the `strict` rule, I added `context.languageOptions.sourceType === "commonjs"` as another condition to determine whether a file is a CommonJS module.
Marked as `feat` because it changes the behavior of this rule and can produce more warnings in the flat config mode.
I wasn't sure if we should update the docs for …
> feat: account for `sourceType: "commonjs"` in the strict rule

- lib/linter/linter.js
Refs #16302, improves performance of the new config system.
Replaced object spread with `Object.assign` when merging globals in Linter.
Performance before the change:
```
Loading:
Load performance Run #1:  243.3295ms
Load performance Run #2:  241.7577ms
Load performance Run #3:  235.5167ms
Load performance Run #4:  235.3724ms …
```
> perf: switch from object spread to `Object.assign` when merging globals

- docs/src/user-guide/configuring/configuration-files-new.md
Fix https://github.com/eslint/eslint/issues/16290
> docs: fix warn severity description for new config files

- docs/src/rules/prefer-reflect.md
Due to https://github.com/eslint/eslint/issues/16305#issuecomment-1247935311 the falsely suggestion should be disclosed to users to avoid further confusion
See #16305
I am not a native english speaker, maybe the sentences and words are incorrect or inappropriate, if there are something need changes please let me know.
> docs: note false positive `Object.getOwnPropertyNames` in prefer-reflect

- package.json
Latest version of the package includes more aggressive caching.
Fixes #16302
Upgraded dependency
I upgraded `@humanwhocodes/config-array` to the latest version. This includes a [caching change](https://github.com/humanwhocodes/config-array/commit/8a7e8ab499bcbb10d7cbdd676197fc686966a64e) to cache by matching indices, similar to …
> chore: Upgrade @humanwhocodes/config-array for perf

- package.json
Removes `jsdoc` dev dependency. I believe it's unused, since we removed the `docs` script in https://github.com/eslint/eslint/pull/14971
The main goal here is to remove transitive dev-dependency `underscore`, which is currently blocking our release:
https://github.com/jashkenas/underscore/issues/2967
Edit: the problem has been …
> chore: remove `jsdoc` dev dependency

- docs/src/rules/id-length.md
- lib/rules/id-length.js
- tests/lib/rules/id-length.js
Fixes #16316
Counts graphemes instead of code units with [grapheme-splitter](https://github.com/orling/grapheme-splitter)
> feat: `id-length` counts graphemes instead of code units

- docs/src/rules/new-cap.md
`new-cap` rule supports `BigInt`, but it is undocumented.
https://github.com/eslint/eslint/blob/main/lib/rules/new-cap.js#L29
So this PR adds `BigInt` to `new-cap` docs.
> docs: add `BigInt` to `new-cap` docs

- docs/src/user-guide/configuring/ignoring-code.md
- lib/rules/lines-around-comment.js
- lib/rules/no-loss-of-precision.js
- lib/rules/no-use-before-define.js
- lib/shared/traverser.js
Ran vale to tag some duplicates. There were some other related to the JDdocs parameters that I left alone:
```
docs\.eleventy.js
65:24  error  'text' is repeated!  Vale.Repetition 
docs\src\developer-guide\nodejs-api.md
467:1  error  'class' is repeated!  Vale.Repetition 
docs\src\_includes\components\button.macro.html
10:23 …
```
> docs: remove duplicate words

- docs/src/assets/js/search.js
- docs/src/assets/scss/components/search.scss
- docs/src/user-guide/configuring/configuration-files-new.md
- lib/config/flat-config-array.js
- lib/eslint/eslint-helpers.js
- lib/eslint/flat-eslint.js
- lib/options.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/rule-tester/rule-tester.js
- Fix some minor typos in the JSDocs
- Fix typos/missing hyphens in some MD docs
- Correct bad CSS value/typo
- Correct UK spelling of "behaviour" that is shown as US spelling "behavior" in intellisense.
These could be split out to separate PRs, but I just kept the commits separate for now.
> docs: typo cleanups for docs

- docs/src/developer-guide/nodejs-api.md
Was looking at updating to the newer version of the Markdown library/CLI2 but realized that it now requires Node 14, so I just submitted the new rule fixes in the file that were flagged
> docs: MD053 unused link definitions

- Makefile.js
- docs/src/user-guide/configuring/configuration-files-new.md
- eslint.config.js
- lib/cli.js
- lib/eslint/eslint-helpers.js
- lib/eslint/flat-eslint.js
- lib/options.js
- package.json
- tests/fixtures/cli-engine/eslint.config_with_ignores2.js
- tests/fixtures/eslint.config_with_ignores.js
- tests/fixtures/eslint.config_with_ignores2.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/options.js
Refs https://github.com/eslint/eslint/issues/16264. Removes everything mentioned except for the `ignorePatterns` constructor option. I can do that in a separate PR when we are certain that the option should be removed.
- Removed all support for separate ignore files.
- Removed loading `.eslintignore` files.
- Removed …
> feat: remove support for ignore files in FlatESLint

- docs/src/developer-guide/working-with-rules.md
Provide additional documentation on conflicting fixes.
Also added additional small grammar fix.
Fixes #13721
Added additional documentation about conflicting fixes
> docs: Conflicting fixes

- .github/dependabot.yml
Noticed in https://github.com/eslint/eslint/pull/16350 that the commit message formatting check wasn't happy with the default message that Dependabot uses, so changed it so that it should be compliant for those updates to the GitHub Actions dependencies
https://docs.github.com/en/code-security/dependabot/dependabot-version-update …
> chore: use "ci" for Dependabot commit message

- docs/src/developer-guide/nodejs-api.md
- docs/src/developer-guide/working-with-custom-formatters.md
- lib/cli.js
- lib/eslint/eslint.js
- lib/eslint/flat-eslint.js
- lib/shared/types.js
- tests/lib/cli.js
This fixes #14881 by giving formatters access to the `--max-warnings` threshold when it is exceeded. The `maxWarningsExceeded` property matches [what `stylelint` uses](https://stylelint.io/developer-guide/formatters/).
I had hoped to disable ESLint's own output message if the formatter provides its own message, but that would …
> feat: Pass --max-warnings value to formatters

- tests/lib/eslint/flat-eslint.js
Follow up https://github.com/nodejs/node/pull/37302.
This PR suppress the following Node.js warning.
```console
% node -v
v18.10.0
% cd path/to/eslint
% node Makefile mocha
Running unit tests
(snip)
(node:63796) [DEP0147] DeprecationWarning: In future versions of Node.js,
fs.rmdir(path, { recursive: true }) will be removed. Use …
```
> chore: suppress a Node.js deprecation warning

- Makefile.js
- lib/config/default-config.js
- lib/eslint/eslint-helpers.js
- package.json
- tests/fixtures/ignores-directory/eslint.config.js
- tests/fixtures/ignores-relative/eslint.config.js
- tests/fixtures/ignores-self/eslint.config.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
Removes globby due to numerous issues with ignoring files and returning the correct files.
Fixes #16354
Fixes #16340
Fixes #16300
I removed `globby` and replaced it with a custom solution built upon `@nodelib/fs.walk`, which was used by `fast-glob` to walk the directory and look for matching filenames. Instead of forcing …
> feat: Swap out Globby for custom globbing solution.

- docs/src/user-guide/configuring/configuration-files-new.md
Document how to extend a plugin configuration using the new ESLint configuration file type system.
Note that I included a comment in the example coming how extending a plugin works in the new config files compared to the old ones. I did this b/c I think that there's a significant enough change in behavior here for a critical feature that it's worth an explicit call out.
Fixes #16310
[ …
> docs: Document extending plugin with new config

- docs/src/user-guide/configuring/configuration-files-new.md
- lib/cli.js
- tests/lib/cli.js
Fixes #16349 by implementing https://github.com/eslint/eslint/issues/16349#issuecomment-1259426231. 
I could use some help figuring out how/where to add tests!
> feat: Use ESLINT_USE_FLAT_CONFIG environment variable for flat config

- docs/src/_includes/layouts/base.html
- docs/src/_includes/layouts/doc.html
- docs/src/_includes/partials/docs-header.html
To keep the top border of header consistent with other pages like Team/Blog which would take up the full width of viewport.
1. Move `.docs` class to `.docs-wrapper` element
> docs: update header

- package.json
- tests/lib/eslint/flat-eslint.js
Upgrade @humanwhocodes/config-array to fix several issues with flat config ignores.
Fixes #16416
Fixes #16415
> fix: Ensure unignore and reignore work correctly in flat config.

- docs/src/rules/no-implicit-globals.md
- lib/linter/linter.js
- lib/rules/no-implicit-globals.js
- tests/lib/rules/no-implicit-globals.js
Fixes #16327
Variables specified with `/*exported variableName */` should not report errors by `no-implicit-globals`.
https://github.com/eslint/eslint/pull/16343#discussion_r978961061
> feat: `no-implicit-globals` supports `exported` block comment

- docs/src/user-guide/command-line-interface.md
> docs(command-line-interface.md): note --ignore-path not supported with flat config

- package.json
- tests/fixtures/ignores-subdirectory/eslint.config.js
- tests/lib/eslint/flat-eslint.js
This fix makes sure that ignored directories can be unignored using negated patterns inside of an 'ignores' entry.
Fixes #16414
> fix: Ensure that directories can be unignored.

- lib/eslint/flat-eslint.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
This fixes an edge case where `FlatESLint.prototype.getRulesMetaForResults([])` would return an empty `Map` instead of a plain object.
Node version: v18.11.0
npm version: v8.19.2
Local ESLint version: v8.25.0 (Currently used)
Operating System: darwin 21.6.0 …
> fix: make `getRulesMetaForResults` return a plain object in trivial case

- eslint.config.js
- lib/cli.js
- lib/eslint/flat-eslint.js
- tests/fixtures/cli/ignore-pattern-relative/.eslintrc.js
- tests/fixtures/cli/ignore-pattern-relative/eslint.config.js
- tests/lib/cli.js
Closes https://github.com/eslint/eslint/issues/16264
After fixing https://github.com/eslint/eslint/issues/16300, `--ignore-pattern` became relative to `configs.basePath`, because they were mapped to `overrideConfig.ignores`. I updated `cli.js` to map them to the `ignorePatterns` constructor option instead, so now they will be …
> fix: `--ignore-pattern` in flat config mode should be relative to `cwd`

- lib/eslint/flat-eslint.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes #16402
* `FlatESLint.prototype.getRulesMetaForResults` will now ignore messages without a `ruleId` instead of crashing with a `TypeError`.
* Unit tests for `getRulesMetaForResults` added for both `FlatESLint` and `ESLint`.
* The unit test "should return one rule meta when there is a suppressed linting error" was ported to …
> fix: ignore messages without a `ruleId` in `getRulesMetaForResults`

- .github/workflows/ci.yml
- tests/lib/shared/runtime-info.js
Node v19.0.0 has been released.
https://nodejs.org/en/blog/release/v19.0.0/
This PR adds the v19 matrix.
This PR also fixes the following tests failure when using v19.0.0.
```console
% node -v
v19.0.0
% npx mocha tests/lib/shared/runtime-info.js
(snip)
1) RuntimeInfo
environment()
log and throw an error when checking for local …
```
> build: add node v19

- lib/rules/getter-return.js
- tests/lib/rules/getter-return.js
Fixes: #16419
Fixed to check the return value of get property in Object.create.
> feat: check for Object.create() without explicit return value in getter return

- docs/.vscode/settings.json
- docs/src/pages/rules.md
- docs/src/user-guide/command-line-interface.md
- docs/src/user-guide/configuring/index.md
- docs/src/user-guide/core-concepts.md
- docs/src/user-guide/formatters/index.md
- docs/src/user-guide/integrations.md
- docs/src/user-guide/migrating-to-8.0.0.md
Add a page to the user guide about the core concepts of ESLint.
The page contains minimalistic explanations, with links out to the more detailed explanation pages. 
I intentionally kept this page pretty minimalist. Specifically, I didn't include any code examples. I decided not to include code examples to really keep this page …
> docs: Core concepts page

- lib/eslint/flat-eslint.js
- tests/fixtures/eslint.config_with_rules.js
- tests/lib/eslint/flat-eslint.js
Fixes https://github.com/eslint/eslint/issues/16341
Fixed `FlatESLint` class to use `baseConfig`.
> fix: use `baseConfig` constructor option in FlatESLint

- docs/src/developer-guide/working-with-rules.md
add some more detail and clarity to the context.getScope() docs.
Fixes #16148
nothing in particular
> docs: improve context.getScope() docs

- lib/rules/comma-dangle.js
- lib/rules/func-name-matching.js
- lib/rules/no-misleading-character-class.js
- lib/rules/prefer-regex-literals.js
- tests/lib/rules/comma-dangle.js
- tests/lib/rules/func-name-matching.js
- tests/lib/rules/no-misleading-character-class.js
- tests/lib/rules/prefer-regex-literals.js
Fixes #16442
Updates core rules that were using `context.parserOptions.ecmaVersion` to use `context.languageOptions.ecmaVersion` instead.
The rules are:
* comma-dangle
* func-name-matching
* no-misleading-character-class
* prefer-regex-literals
This ensures that the rules work as intended in flat config mode.
Marked as `feat` …
> feat: use `context.languageOptions.ecmaVersion` in core rules

- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes #16410
* In `getRulesMetaForResults`, files with an unspecified path are now treated as if they were located inside `cwd`.
* In `getRulesMetaForResults`, when a result referencing a rule has no config, we will explicitly throw an error with a descriptive message.
* Added top-level, internal functions `getPlaceholderPath` …
> fix: handle files with unspecified path in `getRulesMetaForResults`

- docs/src/user-guide/configuring/rules.md
Places the documentation related to justifications (on comment directives) in its own section so it may be more easily found from the table of contents.
Spelling and terminology used in new text
> docs: Add heading to justification explanation

- docs/.stylelintrc.json
- docs/src/assets/scss/carbon-ads.scss
- docs/src/assets/scss/components/search.scss
- docs/src/assets/scss/forms.scss
- docs/src/assets/scss/languages.scss
- docs/src/assets/scss/syntax-highlighter.scss
- docs/src/assets/scss/versions.scss
Enable the stylelint rule to remove duplicate/shadowed property values and auto-fixeed occurances.
Mostly removed duplicate values, but one or 2 were different and may have been some sort of fallback
> docs: enable stylelint declaration-block-no-duplicate-properties

- docs/.stylelintrc.json
- docs/package.json
- docs/src/_includes/layouts/base.html
- docs/src/user-guide/formatters/html-formatter-example.html
- lib/cli-engine/formatters/html.js
Add the Stylelint parsing and rules for the inline CSS in the docs templates. Alternately this could be skipped if the code is moved to the other SCSS files
> docs: use Stylelint for HTML files

- docs/.stylelintrc.json
- docs/src/assets/scss/carbon-ads.scss
Enabled the stylelint rule enforce modern colour function notation and auto-fixed with `npm run lint:fix:scss`
> docs: explicit stylelint color related rules

- docs/src/_data/rules.json
- docs/src/_data/rules_meta.json
- lib/rules/no-empty.js
- tests/lib/rules/no-empty.js
Resolve https://github.com/eslint/eslint/issues/15899
Resolve https://github.com/eslint/eslint/pull/16096
A suggestion that adds a `/* empty */` comment inside the reported empty block statement.
No
> feat: no-empty suggest to add comment in empty BlockStatement
