eslint/eslint

- lib/rules/block-scoped-var.js
- tests/lib/rules/block-scoped-var.js
> Fix: block-scoped-var reports labels (fixes #1630)

- lib/eslint.js
- lib/util/estraverse-custom.js
- package.json
- tests/lib/eslint.js
Update estraverse with custom node information JSX.
> Update: Fully enable JSX support (fixes #1640)

- lib/rules/quotes.js
- package.json
- tests/lib/rules/quotes.js
Pulling in from es6jsx branch.
> Fix: quotes rule ignores JSX literals (fixes #1477)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/generator-star.md
- lib/rules/generator-star.js
- tests/lib/rules/generator-star.js
Relates to #1617 and isn't currently ready (no docs yet), but looking for any feedback on the approach.
> new rule: star position for generators

- README.md
> Docs: Added Fitbit to the list of companies

- Makefile.js
Updating gensite script to copy browserified version of eslint as well as global config file to the site directory.
> Build: Update gensite script (Closes #1725)

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- tests/lib/cli-engine.js
Addresses the `getFormatter()` feedback in #1723.
> Update: Improve CLIEngine.getFormatter() (refs #1723)

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- tests/lib/cli-engine.js
Included count at the file level also so that it becomes easy to identify for each file.
> Update: CLIEngine results include warning and error count (fixes #1732)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/indent.md
- lib/rules/indent.js
- tests/fixtures/rules/indent/indent-invalid-fixture-1.js
- tests/lib/rules/indent.js
Added new rule: indent
merge of https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/validate-indentation.js
to eslint rule
in order to solve #1022
> New: rule indent

- conf/eslint.json
- docs/rules/README.md
- docs/rules/indent.md
- lib/rules/indent.js
- tests/fixtures/rules/indent/indent-invalid-fixture-1.js
- tests/lib/rules/indent.js
This is a re-submission of the indent rule from JSCS with proper attribution.
@mikesherov @valorkin
> New: Rule indent (fixes #1022)

- .eslintrc
- Makefile.js
- lib/cli-engine.js
- lib/eslint.js
- lib/formatters/tap.js
- lib/rules/no-unused-expressions.js
- lib/rules/space-unary-ops.js
- lib/rules/vars-on-top.js
- tests/lib/config.js
- tests/lib/traverse.js
Fix indentation issues in the ESLint project
https://github.com/eslint/eslint/pull/1698#issuecomment-72916183
it is more update than actually a fix
> Update: fix eslint indentations (fixes #1770)

- docs/rules/curly.md
- lib/rules/curly.js
- tests/lib/rules/curly.js
For the rationale and behavior of this new option, see #1812.
> New: multi-line option for the curly rule (fixes #1812)

- docs/rules/eqeqeq.md
- docs/rules/new-cap.md
- docs/rules/no-mixed-requires.md
- docs/rules/no-warning-comments.md
- docs/rules/space-unary-ops.md
FYI, I'm doing some work to make it easier to detect these problems with automated testing.
> Docs: Update pages to fix rendering of lists

- docs/developer-guide/contributing.md
> Docs: Add a missing word in the Contributing doc

- README.md
* Alphabetizes project & company usage list to prevent perceived favoritism and to make it clear how future additions should be made
* Adds CustomInk to list of companies
> Alphabetize usage list & add CustomInk

- docs/developer-guide/working-with-plugins.md
- lib/cli-engine.js
- lib/util.js
- tests/fixtures/configurations/processors.json
- tests/fixtures/processors/custom-processor.js
- tests/fixtures/processors/test/test-processor.txt
- tests/lib/cli-engine.js
Adding support for custom preprocessors.
> Update: Add support for custom preprocessors (fixes #1817)

- docs/rules/no-inner-declarations.md
- lib/rules/no-inner-declarations.js
- tests/lib/rules/no-inner-declarations.js
I added a small update to the docs too.
> Fix: allow block bindings in no-inner-declarations (fixes #1893)

- docs/rules/generator-star.md
- lib/rules/generator-star.js
- tests/lib/rules/generator-star.js
Adds a "middle" option to `generator-star` rule.
Give me a day or so to review my own stuff before merging. May have forgotten something :)
> New: generator-star middle option (fixes #1808)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-dupe-args.md
- lib/rules/no-dupe-args.js
- tests/lib/rules/no-dupe-args.js
Here's a simple solution to the `no-dupe-args` rule. It's the simplest way I could think to solve the problem. I'd love some feedback of fancier solutions :)
> New: no-dupe-args rule (fixes #1880)

- lib/rules/space-before-function-parentheses.js
- tests/lib/rules/space-before-function-parentheses.js
This will need to be rebased after #1924, but 94a053a is ready for review.
> Update: space-before-function-parentheses to support generators (fixes #1929)

- docs/rules/comma-style.md
- lib/rules/comma-style.js
- tests/lib/rules/comma-spacing.js
- tests/lib/rules/comma-style.js
> Add exceptions to eslint's comma-style rule.

- conf/eslint.json
- docs/rules/README.md
- docs/rules/generator-star-spacing.md
- docs/rules/generator-star.md
- lib/rules/generator-star-spacing.js
- tests/lib/rules/generator-star-spacing.js
If this gets merged, I'll add deprecating `generator-star` to the 1.0 task list in #1898.
> New: generator-star-spacing rule (fixes #1680, fixes #1949)

- docs/rules/handle-callback-err.md
- docs/rules/no-console.md
- docs/rules/no-octal.md
- docs/rules/no-undef.md
- docs/rules/no-wrap-func.md
- docs/rules/strict.md
Removing a few links that are no longer available and fixing links for jslinterrors.com.
> Docs: Cleaning dead links

- README.md
- docs/user-guide/configuring.md
Those are the last of them, as far as I know.
> Docs: Fixing broken links in documentation

- lib/rules/semi.js
- tests/lib/rules/semi.js
Best to reference [#2194 (comment)](https://github.com/eslint/eslint/issues/2194#issuecomment-88575851) for analysis of what needs a semicolon and what doesn't.
> Fix: semi error on export declaration (fixes #2194)

- docs/rules/no-empty.md
PR #2193 never included the documentation changes.
> Docs: no-empty fix comment change (refs #2188)

- lib/rules/block-scoped-var.js
- tests/lib/rules/block-scoped-var.js
Fixes https://github.com/eslint/eslint/issues/2242
> Fix an error with block-scoped-var when using ecmaFeature modules

- docs/rules/no-wrap-func.md
I noticed the URL on this page 404'd.
I've updated the link to point to what seems to be the new version of the article.
> Docs: Update URL in no-wrap-func.md to resolve 404

- docs/rules/padded-blocks.md
Fix a few minor grammar errors and shorten a few sentences.
> Docs: Improve grammar and style in padded-blocks.md

- docs/rules/README.md
- docs/rules/quotes.md
- lib/rules/quotes.js
- tests/lib/rules/quotes.js
Added backtick support to quotes rule as proposed in #2153
> Update: backticks support for quotes rule (fixes #2153)

- docs/developer-guide/working-with-plugins.md
> Docs: Some typos and grammar.

- docs/developer-guide/working-with-plugins.md
- lib/cli-engine.js
- lib/config.js
- lib/util.js
- tests/fixtures/configurations/plugins-with-prefix-and-namespace.json
- tests/fixtures/configurations/plugins-without-prefix-with-namespace.json
- tests/lib/cli-engine.js
- tests/lib/util.js
This PR allows plugins to be namespaced, allowing the use private npm plugins.
> allow plugins to be namespaced fixes #2360

- conf/eslint.json
- docs/rules/README.md
- docs/rules/linebreak-style.md
- lib/rules/linebreak-style.js
- tests/lib/rules/linebreak-style.js
Serves #1255 
Since this is my very first eslint rule (I thought I try since s/o put the `beginner` label there),
I'd appreciate any constructive critizism :)
> New: linebreak-style rule

- docs/user-guide/configuring.md
> Add `restParams` to `ecmaFeatures` options list

- bin/eslint.js
- docs/user-guide/command-line-interface.md
- lib/config-initializer.js
- package.json
- tests/lib/config-initializer.js
This is a WIP request for init command. I'm not really sure that eslint.js is the right place to put it in, maybe it should go into it's own file? Also please check the questions and see if we would like to add any others?
Eslint.js is currently not unittested. So I didn't create any unit tests for init either for now (I'm not really sure they are necessary either).
> WIP: Init command

- lib/rules/no-loop-func.js
- tests/lib/rules/no-loop-func.js
This PR makes `no-loop-func` rule allow functions at init parts.
> `no-loop-func` rule allows functions at init part (fixes #2427)

- Makefile.js
I have no idea if this will work, but it probably will.
Fixes #2297.
**edit:** Why are these tasks in here and not eslint/eslint.github.io?
> Fix: sanitise Jekyll interpolation during site generation (fixes #2297)

- docs/rules/one-var.md
- lib/rules/one-var.js
- tests/lib/rules/one-var.js
> Breaking: Do not check unset declaration types (Fixes #2448)

- README.md
Fixes #2478 This is necessary to unblock pull request builds. So I'm going to merge it myself.
> Docs: Fixing trailing spaces (Fixes #2478)

- lib/rules/no-duplicate-case.js
- tests/lib/rules/no-duplicate-case.js
> Fix: rule no-duplicate-case problem with CallExpressions. (fixes #2499)

- Makefile.js
fixes #2520 This should add trailing white line whenever there isn't one.
> Build: Make sure that all md files end with empty line (fixes #2520)

- lib/rules/no-shadow.js
- tests/lib/rules/no-shadow.js
> Don't throw spurious shadow errors for classes

- docs/user-guide/command-line-interface.md
- lib/cli.js
- lib/ignored-paths.js
- lib/options.js
- tests/lib/cli.js
> Adds --ignore-pattern option. (fixes #1742)

- conf/environments.js
- docs/user-guide/configuring.md
> New: Add worker environment (fixes #2442)

- .travis.yml
> Build: Add sudo:false for Travis (fixes #2582)

- lib/rules/indent.js
Previous pull request lowered coverage by one branch which was enough to get us below the threshold. Not sure how it managed to snick by Travis, but all future builds were block by this.
> Build: Unblock build by increasing code coverage

- lib/config-initializer.js
- lib/config.js
- lib/formatters/tap.js
- tests/fixtures/environments/fake.yaml
- tests/lib/cli.js
- tests/lib/config-initializer.js
- tests/lib/config-validator.js
- tests/lib/config.js
- tests/lib/formatters/checkstyle.js
- tests/lib/formatters/jslint-xml.js
- tests/lib/ignored-paths.js
- tests/lib/rules/no-void.js
Fixes #2590 This should give us a little bit of breathing room around branch coverage. This is mostly artificial tests for things that shouldn't happen, as well as some `istanbul ignore` comments for things that are either untestable or too hard to test.
In general, we have a bunch of cases where we do branching just for sanity checking. Some of the things that I commented can't possibly happen. I'm not really sure if we should just remove those branches all together.
> Fix: Improve code coverage (fixes #2590)

- lib/config.js
- tests/fixtures/config-hierarchy/shared/a/.eslintrc
- tests/fixtures/config-hierarchy/shared/b/.eslintrc
- tests/lib/config.js
this is my approach to solving the issue I found in #2592
> Fix: Shared config being clobbered by other config (fixes #2592)

- lib/rules/consistent-this.js
- tests/lib/rules/consistent-this.js
> Make “consistent-this” ignore destructuring of `this`

- docs/rules/yoda.md
- lib/rules/yoda.js
- tests/lib/rules/yoda.js
> Update: yoda onlyEquality option (fixes #2638)

- conf/environments.js
- docs/user-guide/configuring.md
- package.json
Diff: https://github.com/sindresorhus/globals/compare/v6.1.0...7.1.0
> Upgrade: Update globals and environments (fixed #2682)

- docs/rules/README.md
> Docs: Mark global-strict on by default (fixes #2629)

- package.json
This should unblock build till https://github.com/cjohansen/Sinon.JS/issues/761 gets fixed.
> Build: Pin Sinon version (fixes #2742)

- package.json
> Upgrade: globals@8.0.0 (fixes #2759)

- lib/config.js
- tests/fixtures/config-extends/package.json
- tests/lib/config.js
There are many ways to solve this issue. This is my first take on it.
Any suggestions?
> Fix: "extends" within package.json (fixes #2754)

- docs/user-guide/command-line-interface.md
@nzakas I edited your PR (#2774) from last night to fix the autocorrect, though apparently if you force push or rebase you can't reopen a PR, so I had to create a new one.
> Docs: Clarify --rule description (fixes #2773)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/array-bracket-spacing.md
- lib/rules/array-bracket-spacing.js
- tests/lib/rules/array-bracket-spacing.js
- Took the existing `space-in-brackets` rule and ripped out the `object` stuff.
- Added destructuring support
> New: array-bracket-spacing (fixes #2226)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-this-before-super.md
- lib/rules/no-this-before-super.js
- tests/lib/rules/no-this-before-super.js
I didn't use execution paths analysis.
> New: `no-this-before-super` rule (fixes #2721)

- lib/rules/no-extra-semi.js
- tests/lib/rules/no-extra-semi.js
- tests/lib/rules/semi.js
I added checking and tests into `no-extra-semi`, and added tests into `semi`.
> Fix: `no-extra-semi` in class bodies (fixes #2794)

- lib/rules/accessor-pairs.js
- lib/rules/dot-location.js
- lib/rules/no-empty-character-class.js
> Update: Add missing schema to rules (fixes #2858)

- lib/rules/yoda.js
- tests/lib/rules/yoda.js
> Fix: Yoda should ignore comparisons where both sides are constants

- lib/eslint.js
- tests/lib/eslint.js
Note that this only includes the direct parent, not the grandparent.
/cc @lo1tuma for review
> Update: Attach parent in getNodeByRangeIndex (fixes #2863)

- docs/rules/no-implied-eval.md
- lib/rules/no-implied-eval.js
- tests/lib/rules/no-implied-eval.js
> add execScript to no-eval rule (See #2873)

- docs/developer-guide/shareable-configs.md
> Fix typo in the shareable configs doc

- tests/lib/rules/no-redeclare.js
This addresses [my comment](https://github.com/eslint/eslint/issues/2953#issuecomment-120084338) in #2953 and adds a couple of trivial tests for the case that originally helped me discover this bug.
I have idea if I formatted this PR correctly, so please correct me if I need to change anything and get this merged. :)
> Update: adding some tests for no-redeclare to test named functions (fixes #2953)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-useless-call.md
- docs/rules/prefer-spread.md
- lib/rules/no-useless-call.js
- tests/lib/rules/no-useless-call.js
- tests/lib/rules/prefer-spread.js
And I modified the `prefer-spread` rule to avoid collision with this.
> New: the `no-useless-call` rule (fixes #1925)

- docs/developer-guide/working-with-rules.md
- lib/eslint.js
- lib/rule-context.js
- package.json
- tests/lib/eslint.js
> New: `context.getDeclaredVariables(node)` (fixes #2801)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-class-assign.md
- lib/rules/no-class-assign.js
- tests/lib/rules/no-class-assign.js
The implementation of this rule is almost same as #2732 :)
> New: the `no-class-assign` rule (fixes #2718)

- lib/rules/spaced-comment.js
- tests/lib/rules/spaced-comment.js
> Update: Handle CRLF line endings in spaced-comment rule - 2

- conf/eslint.json
- docs/rules/README.md
- docs/rules/id-length.md
- lib/rules/id-length.js
- tests/lib/rules/id-length.js
> New: Add id-length rule (fixes #2784)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/id-match.md
- lib/rules/id-match.js
- tests/lib/rules/id-match.js
This rule allows regular expression matching on Identifiers.
> New: add regexp-match rule (fixes #2829)

- docs/rules/new-cap.md
- lib/rules/new-cap.js
- tests/lib/rules/new-cap.js
> Update: `new-cap` supports fullnames

- lib/rules/init-declarations.js
- tests/lib/rules/init-declarations.js
> Fix: `init-declarations` ignores in for-in/of

- docs/developer-guide/nodejs-api.md
- docs/user-guide/command-line-interface.md
- lib/formatters/json.js
- tests/lib/formatters/json.js
Very basic JSON formatter that just groups messages by file. Mostly yanked from `jslint-xml` formatter.
> New: Add JSON formatter (fixes #3036)

- conf/environments.js
- docs/user-guide/configuring.md
This adds the embertest globals as an env preset.
> Update: Add embertest env (fixes #3205)

- conf/environments.js
- docs/user-guide/configuring.md
- package.json
This adds a new environment, `jest`. Here are the changes:
- `globals` dep updated to 8.3.0
- New `jest` property in `environments.js`
- Updated docs
> New: Jest environment (fixes #3212)

- docs/rules/semi.md
This should say _"if you do **not** want to …"_, right?
> Adds missing "not" to semi.md

- lib/rules/no-cond-assign.js
- tests/lib/rules/no-cond-assign.js
> Fix: `no-cond-assign` had been missing simplest pattern

- docs/rules/curly.md
- lib/rules/curly.js
- tests/lib/rules/curly.js
I'm still not sure about the name of the option. Any suggestions?
> Update: add new `multi-or-nest` option for the `curly` rule (fixes #1806)

- conf/environments.js
> Fix: `es6` env had been missing `spread` and `newTarget`

- docs/rules/spaced-comment.md
- lib/rules/spaced-comment.js
- tests/lib/rules/spaced-comment.js
Can someone spot check my logic here?
Assuming it's fine. I'll also update some docs and things before I'm done.
> Fix: Spaced Comment Exceptions Not Working (Fixes #3276)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/prefer-template.md
- lib/rules/prefer-template.js
- tests/lib/rules/prefer-template.js
> New: `prefer-template` rule

- conf/eslint.json
- docs/rules/README.md
- docs/rules/prefer-arrow-callback.md
- lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-arrow-callback.js
> New: `prefer-arrow-callback` rule

- .eslintrc
- conf/eslint.json
- docs/rules/README.md
- docs/rules/block-spacing.md
- lib/rules/block-spacing.js
- tests/lib/rules/block-spacing.js
> New: `block-spacing` rule

- docs/rules/space-infix-ops.md
- lib/rules/space-infix-ops.js
- tests/lib/rules/space-infix-ops.js
> Update: Add AssignmentPattern to space-infix-ops

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
Prototype implementation for #3339.
I'm not really happy about the configuration scheme but it gets the job done.
> Update: Separate indent options for var, let and const

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-dupe-class-members.md
- lib/rules/no-dupe-class-members.js
- tests/lib/rules/no-dupe-class-members.js
> New: `no-dupe-class-members` rule

- lib/rules/indent.js
- tests/lib/rules/indent.js
> Update: add support for semicolon in comma-first setup in indent rule

- lib/rules/no-duplicate-case.js
- tests/lib/rules/no-duplicate-case.js
> Fix: Refactor `no-duplicate-case` to be simpler and more efficient

- lib/rules/object-curly-spacing.js
- tests/lib/rules/object-curly-spacing.js
> Fix: `object-curly-spacing` shows the incorrect column for opening brace

- docs/rules/prefer-arrow-callback.md
- lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-arrow-callback.js
> Fix: `prefer-arrow-callback` false positive at recursive functions

- conf/eslint.json
- lib/rules/one-var.js
- tests/lib/rules/one-var.js
> Fix: one-var rule doesn’t have default options

- lib/rules/indent.js
- tests/lib/rules/indent.js
> Fix: `indent` does not check FunctionDeclaration nodes properly

- conf/environments.js
- docs/user-guide/configuring.md
- package.json
Adds in missing protractor variables as defined [here](https://github.com/angular/protractor/blob/e996a90644a7d2966636dd718e279fb9dc8753f9/lib/runner.js#L152-L166).
> New: Protractor environment (fixes #3457)

- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
> Fix: `brace-style` doesn't report some closing brace errors

- docs/rules/quote-props.md
- lib/rules/quote-props.js
- tests/lib/rules/quote-props.js
> Update: Add `unnecessary` option to `quote-props`

- lib/rules/indent.js
- tests/lib/rules/indent.js
> Fix: ASI indentation issue

- docs/rules/curly.md
> Docs: (curly) Fix broken code in example

- docs/rules/quote-props.md
- lib/rules/quote-props.js
- tests/lib/rules/quote-props.js
> Update : Add `keywords` flag to `consistent-as-needed` mode in `quote-props`

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-useless-concat.md
- lib/rules/no-useless-concat.js
- tests/lib/rules/no-useless-concat.js
https://github.com/eslint/eslint/issues/3506
WIP
@mysticatea @Cellule
> New: `no-useless-concat` rule (fixes #3506)

- CONTRIBUTING.md
Seems like the URL was out of date.
> correct contibuting URL

- conf/eslint.json
- docs/rules/README.md
- docs/rules/global-require.md
- lib/rules/global-require.js
- tests/lib/rules/global-require.js
Still needs docs, but feel free to review the code :)
> New: global-require rule (fixes #2318)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-restricted-syntax.md
- lib/rules/no-restricted-syntax.js
- tests/lib/rules/no-restricted-syntax.js
> New: `no-restricted-syntax` rule to forbid certain syntax

- docs/rules/valid-jsdoc.md
- lib/rules/valid-jsdoc.js
- tests/lib/rules/valid-jsdoc.js
> Add @override support for valid-jsdoc

- docs/user-guide/command-line-interface.md
- lib/options.js
With apologies to `git` for forcing a rewrite due to a crazy diff, here is my take on grouping CLI options.
Force-pushed an update right away because I wanted to add some line breaks around the sections. Sorry for any confusion.
Please weigh in with ordering or re-grouping suggestions.
Fixes #3612.
> Update: Grouping related CLI options. (fixes #3612)

- docs/rules/comma-spacing.md
- docs/rules/computed-property-spacing.md
Fixing a few broken links on the site.
> Docs: Fixing broken link in documentation

- package.json
Just for kicks, I updated the handlebars dependency to `^4.0.0` (which pulls in 4.0.1 as of when I wrote this). `npm test` passed, not sure if there is anything I can do to verify more deeply. If there is something I can/should do for extra verification, please let me know.
Fixes #3632. (Sort of-- it only fixes the original scope of the issue. Maybe a different issue could be created for the devDependencies?)
> Upgrade: Consuming handlebars@^4.0.0 (fixes #3632)

- lib/config.js
- lib/eslint.js
- lib/rules/no-invalid-regexp.js
- lib/rules/space-after-keywords.js
- tests/lib/cli-engine.js
- tests/lib/rules/space-after-keywords.js
> Fix: `space-after-keywords` not working for `catch`

- lib/eslint.js
- lib/rules/no-unused-vars.js
- tests/lib/eslint.js
- tests/lib/rules/no-unused-vars.js
> Fix: `no-unused-vars` had not been showing correct locations for `/*global`

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
> Fix: `no-extra-parens` false positive at IIFE with member accessing

- .eslintrc
- lib/ast-utils.js
- lib/eslint.js
- lib/rules/array-bracket-spacing.js
- lib/rules/comma-dangle.js
- lib/rules/constructor-super.js
- lib/rules/generator-star-spacing.js
- lib/rules/init-declarations.js
- lib/rules/no-dupe-class-members.js
- lib/rules/no-extra-parens.js
- lib/rules/no-func-assign.js
- lib/rules/no-invalid-this.js
- lib/rules/no-loop-func.js
- lib/rules/no-native-reassign.js
- lib/rules/no-param-reassign.js
- lib/rules/no-return-assign.js
- lib/rules/no-sequences.js
- lib/rules/no-shadow.js
- lib/rules/no-this-before-super.js
- lib/rules/no-unused-vars.js
- lib/rules/no-useless-call.js
- lib/rules/object-curly-spacing.js
- lib/rules/object-shorthand.js
- lib/rules/prefer-arrow-callback.js
- lib/rules/prefer-const.js
- lib/rules/prefer-spread.js
- lib/rules/spaced-comment.js
Fixes #3705.
This needs rebasing after #3703 was merged.
> Fix: Remove temporary `"allow-null"`

- lib/cli-engine.js
- tests/lib/cli-engine.js
Fixes #3750
Fixes #3746
Fixes #3748
> Fix: Glob pattern from .eslintignore not applied

- docs/rules/README.md
- docs/rules/space-return-throw-case.md
- lib/rules/space-return-throw-case.js
- tests/lib/rules/space-return-throw-case.js
> Update: Implement auto fix for `space-return-throw-case` (fixes #3732)

- docs/rules/README.md
- docs/rules/space-before-function-paren.md
- lib/rules/space-before-function-paren.js
- tests/lib/rules/space-before-function-paren.js
Update: Implement auto fix functionality for space-before-function-paren rule (fixes #3766)
> Update: Implement auto fix functionality for space-before-function-paren rule (fixes #3766)

- lib/eslint.js
- lib/testers/event-generator-tester.js
- lib/util/comment-event-generator.js
- lib/util/node-event-generator.js
- tests/lib/util/comment-event-generator.js
- tests/lib/util/node-event-generator.js
From #3559.
I refactored the traversing logic with the decorator pattern.
This modification can conflict with other features, so I separated PR.
----
Before:
```
> node Makefile.js perf
CPU Speed is 3392 with multiplier 7500000
Performance Run #1:  4449.28339ms
Performance Run #2:  4483.965085ms
Performance Run #3:  4434.058325ms
Performance Run #4:  4471.048229ms
Performance Run #5:  4430.7715339999995ms
Performance budget exceeded: 4449.28339ms (limit: 2211.0849056603774ms)
```
After:
```
> node Makefile.js perf
CPU Speed is 3392 with multiplier 7500000
Performance Run #1:  4459.112069ms
Performance Run #2:  4460.901406ms
Performance Run #3:  4406.947205ms
Performance Run #4:  4435.939423ms
Performance Run #5:  4476.988842ms
Performance budget exceeded: 4459.112069ms (limit: …
```
> Update: Refactors the traversing logic with the decorator pattern

- lib/ast-utils.js
- lib/rules/no-inline-comments.js
- lib/rules/no-warning-comments.js
- tests/lib/ast-utils.js
- tests/lib/rules/no-warning-comments.js
> Fix: `no-warning-comments` cannot be set in a configuration comment

- lib/rules/comma-dangle.js
- tests/lib/rules/comma-dangle.js
> Fix: `comma-dangle` had not been checking imports/exports

- lib/cli-engine.js
- lib/rules/id-length.js
- lib/rules/indent.js
- lib/rules/no-unused-vars.js
- tests/fixtures/rules/indent/indent-invalid-fixture-1.js
- tests/fixtures/rules/indent/indent-valid-fixture-1.js
- tests/lib/rules/indent.js
I have cleaned up the logic for function body indent and found out that it was not catching a lot of errors and also it never respected the function under a variable declaration.
Note: Multi-line issue in general still persists.
> Fix: function body indent issues (fixes #3614, fixes #3799)

- lib/eslint.js
- tests/lib/eslint.js
> Update: ESLint reports parsing errors with clear prefix. (fixes #3555)

- lib/rules/complexity.js
- tests/lib/rules/complexity.js
> Fix: Report shorthand method names in complexity rule

- lib/cli-engine.js
- lib/util/source-code-fixer.js
- tests/lib/cli-engine.js
> Fix: source code fixer does not handle undefined source code (fixes #4016)

- tests/lib/cli-engine.js
Fixes #3968.
I'm not sure this approach is correct.
> Fix: a test failure on Windows

- lib/cli-engine.js
- package.json
This also introduces a new dependency to introduce stable hashing. This resolves the cache problem. 35x perf increase for me. Relative improvement will depend on the number of files being linted.
> Fix: cache is basically not working (fixes #4008)

- package.json
Fixes #3599 by since `shared-node-browser` is added in `8.11.0`.
> Update: Upgrade globals to 8.11.0

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-magic-number.md
- lib/rules/no-magic-number.js
- tests/lib/rules/no-magic-number.js
Proposed implementation of rule no-magic-number.
Fixes issue #4027
> New: no-magic-number rule (fixes #4027)

- lib/rules/id-match.js
- tests/lib/rules/id-match.js
> Fix: id-match bug incorrectly errors on `NewExpression`

- Makefile.js
Forgot to add this line of code with the original PR.
> Build: Performance perf to not ignore jshint file (refs #3765)

- tests/lib/cli-engine.js
- tests/lib/cli.js
- tests/lib/config.js
>  Build: Fix path related failures on Windows in tests

- docs/rules/README.md
- docs/rules/global-require.md
- docs/rules/no-empty-pattern.md
- docs/rules/no-restricted-syntax.md
- docs/rules/no-useless-concat.md
- docs/rules/require-jsdoc.md
- docs/rules/space-before-keywords.md
Went in and cleaned up the documentation for a bunch of the newly-added rules.
> Docs: Update various rules docs

- lib/rules/no-magic-numbers.js
- tests/lib/rules/no-magic-numbers.js
@aruberto
And do I need to make another issue for this or is ref the old one ok?
> Fix: no-magic-numbers should ignore Number.parseInt (fixes #4167)

- lib/rules/no-extend-native.js
- tests/lib/rules/no-extend-native.js
> Fix: no-extend-native should disallow extending with Object.properties

- lib/rules/no-mixed-spaces-and-tabs.js
- tests/lib/rules/no-mixed-spaces-and-tabs.js
Ignore comments and template literals
> Fix: no-mixed-spaces-and-tabs (fixes #4189, fixes #4190)

- docs/rules/no-shadow.md
- lib/rules/no-shadow.js
- tests/lib/rules/no-shadow.js
Credits to @mirek as he did the work.
> Update: Add `allow` option to `no-shadow` rule (fixes #3035)

- lib/cli.js
- lib/logging.js
- tests/lib/cli.js
* Need some suggestions on the file name.
> Build: Do not stub console in testing (fixes #1328)

- lib/rules/valid-jsdoc.js
- lib/util/source-code.js
- tests/lib/rules/valid-jsdoc.js
- tests/lib/util/source-code.js
Not an expert in ES6, so just to make sure i covered all the scenarios here.
CC @nzakas @jacek-dargiel
> Update: Add support for class in `valid-jsdoc` rule (fixes #4279)

- docs/rules/space-before-keywords.md
> Docs: fixed typo

- docs/rules/radix.md
Refs #4048
Refs #4084
Refs #4351
> Fix: Add the missing "as-needed" documentation to the radix rule (fixes #4364)

- lib/config-initializer.js
- tests/lib/config-initializer.js
> Update: Add Popular Style Guides (fixes #4320)

- lib/rules/no-extend-native.js
- tests/lib/rules/no-extend-native.js
> Fix: `no-extend-native` crashed at empty defineProperty

- lib/rules/id-length.js
- tests/lib/rules/id-length.js
> Fix: `id-length` properties never option

- lib/file-finder.js
Issue: https://github.com/eslint/eslint/issues/4459
> Update: replace label and break with IIFE and return (fixes #4459)

- lib/rules/no-sequences.js
- lib/rules/space-after-keywords.js
- tests/lib/rules/no-sequences.js
- tests/lib/rules/space-after-keywords.js
> Update: Display errors closer to the place where fix should go 

- docs/rules/no-implicit-coercion.md
- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
Issue: https://github.com/eslint/eslint/issues/4348
> Update: no-implicit-coercion to validate AssignmentExpression (fixes #4348)

- README.md
> Docs: Load badge from HTTPS

- package.json
- tests/lib/rules/no-undef.js
> Fix: Add a RestProperty test of `no-undef`

- package.json
> Upgrade: doctrine@0.7.1 (fixes #4545)

- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
Fixes #4474 
Maybe this PR should mark as breaking.
> Update: `prefer-const` begins to cover separating init

- docs/rules/no-underscore-dangle.md
- lib/rules/no-underscore-dangle.js
- tests/lib/rules/no-underscore-dangle.js
> Add option to allow dangling underscores after `this`

- lib/rules/no-undef.js
- tests/lib/cli.js
- tests/lib/rules/no-native-reassign.js
- tests/lib/rules/no-redeclare.js
- tests/lib/rules/no-undef.js
> Breaking: Remove warnings of readonly from `no-undef`

- docs/rules/no-plusplus.md
Used correct format when using options
> Docs: Update docs/rules/no-plusplus.md

- docs/rules/object-shorthand.md
- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
Not 100% confident about the JSON Schema (first time working with it, so please bear with me) - let me know if anything needs to be changed!
> Update: Add option to ignore constructor functions in object-shorthand rule (fixes #4487)

- docs/rules/no-use-before-define.md
- lib/rules/no-use-before-define.js
- tests/lib/rules/no-use-before-define.js
Fixes #3944.
I added an object style option: `{"functions": true, "classes": true}`.
> Update: add class option to `no-use-before-define`

- lib/rules/indent.js
- tests/lib/rules/indent.js
ES6 experts in the house, Am I missing any style to declare classes?
> Update: Add class body support to `indent` rule (fixes #4372)

- lib/code-path-analysis/code-path-analyzer.js
- lib/code-path-analysis/code-path-state.js
- lib/rules/no-use-before-define.js
- tests/lib/rules/arrow-parens.js
- tests/lib/rules/global-require.js
- tests/lib/rules/no-use-before-define.js
Fixes #4280
And several invalid initialization were found.
> Update: `no-use-before-define` checks invalid initializer

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-implicit-globals.md
- lib/rules/no-implicit-globals.js
- tests/lib/rules/no-implicit-globals.js
Implementation for rule proposed in https://github.com/eslint/eslint/issues/4542.
-
CC: @nzakas @ilyavolodin @michaelficarra @mzgol
> New: Add no-implicit-globals rule (fixes #4542)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/array-callback-return.md
- lib/ast-utils.js
- lib/rules/array-callback-return.js
- packages/eslint-config-eslint/default.yml
- tests/lib/rules/array-callback-return.js
Fixes #1128 
- I exposed some function in `ast-utils.js`, and used those.
- I added this rule into `default.yml` in order to eat own dog food.
> New: `array-callback-return` rule

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- lib/config.js
- lib/file-finder.js
- lib/ignored-paths.js
- lib/load-rules.js
- lib/rules.js
- tests/lib/cli-engine.js
- tests/lib/config.js
- tests/lib/file-finder.js
- tests/lib/ignored-paths.js
- tests/lib/rules.js
Do we need to add unit tests for this? It's already tested pretty heavily in config.js file. If we do, what should they be?
> Update: Add cwd option for cli-engine (fixes #4472)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-unmodified-loop-condition.md
- lib/rules/no-unmodified-loop-condition.js
- package.json
- packages/eslint-config-eslint/default.yml
- tests/lib/rules/no-unmodified-loop-condition.js
Fixes #4523 
I added this rule to `packages/eslint-config-eslint/default.yml` in order to eat own dog food.
> New: `no-unmodified-loop-condition` rule

- docs/user-guide/command-line-interface.md
- lib/formatters/visualstudio.js
- tests/lib/formatters/visualstudio.js
Visual Studio compatible formatter
> New: Visual Studio compatible formatter (fixes #4708)

- docs/developer-guide/nodejs-api.md
- lib/eslint.js
- lib/util/source-code.js
- tests/lib/eslint.js
@IanVS @nzakas is this what is expected?
> Fix: Add source property for fatal errors (fixes #3325)

- lib/rules/indent.js
- tests/lib/rules/indent.js
@eslint/eslint-team I did solve the #4739 with this PR but then realised it kinda solves the #3456.
What do you guys think?
> Fix: Comma first issue in `indent` (fixes #4739, fixes #3456)

- lib/rules/no-extra-bind.js
- tests/lib/rules/no-extra-bind.js
Fix for a scoping bug in no-extra-bind
> Fix: Bug in no-extra-bind (fixes #4806)

- lib/eslint.js
- tests/lib/eslint.js
> Fix: env had been rewritten by modules

- docs/rules/prefer-const.md
see https://github.com/eslint/eslint/commit/37e09d96ada4b19eadc464644b8e818a00e3979d#commitcomment-15180158
> Document remedy to some prefer-const errors

- docs/rules/no-mixed-requires.md
- lib/rules/no-mixed-requires.js
- tests/lib/rules/no-mixed-requires.js
Add new option “allowCall” to support nested invocation.
> Update: Add "allowCall" option (fixes #4011)

- docs/rules/no-unneeded-ternary.md
[Issue](https://github.com/eslint/eslint/issues/4937)
> Fix: Small semantic issue in documentation example (fixes #4937)

- docs/rules/key-spacing.md
- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
Besides default (existing) options, we can specify ‘singleLine’ and ‘multiLine’ options.
> Update: Support multiLine and singleLine options (fixes #4697)

- lib/rules/padded-blocks.js
- tests/lib/rules/padded-blocks.js
Issue hasn't been yet marked as accepted, but maybe it's easier to see the code in the PR.
> Fix: Incorrect location for padded-blocks (fixes #4913)

- lib/rules/complexity.js
- lib/rules/indent.js
- lib/rules/max-depth.js
- lib/rules/max-len.js
- lib/rules/max-nested-callbacks.js
- lib/rules/max-params.js
- lib/rules/max-statements.js
- lib/rules/no-multiple-empty-lines.js
I wanted to set minimum value to 1 in some cases, but decided against that. You never know what people might want to do:-)
> Update: Add minimum value to integer values in schema (fixes #4941)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/id-blacklist.md
- lib/rules/id-blacklist.js
- tests/lib/rules/id-blacklist.js
/cc @gyandeeps @nzakas
Fixes #3358
> New: 'id-blacklist' rule (refs #3358)

- lib/config/config-validator.js
- lib/eslint.js
- lib/rule-context.js
- lib/rules/accessor-pairs.js
- lib/rules/array-bracket-spacing.js
- lib/testers/rule-tester.js
This adds support for metadata to the core, and converts 2 rules (one fixable, one not) to the new format.
> New: Add metadata to few test rules (fixes #4494)

- docs/rules/README.md
As discussed in https://github.com/eslint/eslint.github.io/pull/180, here is the updated readme doc. Let me know what I need to fix, if anything.
> Docs: Update readme for legend describing rules icons (refs #4355)

- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
> Fix: `keyword-spacing` false positive in template strings (fixes #5043)

- docs/rules/README.md
> Revert "Docs: Update readme for legend describing rules icons (refs #4355)"

- lib/rules/no-extra-bind.js
- tests/lib/rules/no-extra-bind.js
> Fix: `no-extra-bind` false positive (fixes #5058)

- Makefile.js
Fixes #5028.
- A performance test for multi files was added. 
This test is using `eslint@1.10.3` as the test target.
This repository has 450 js files in `lib` and `tests/lib` :)
- `.eslintrc` of performance tests came to turn all rules on.
This is new output of this PR:
```
> eslint@2.0.0-beta.2 perf C:\Users\t-nagashima.AD\Documents\GitHub\eslint
> node Makefile.js perf
Loading:
Load performance Run #1:  193.219655ms
Load performance Run #2:  193.38688ms
Load performance Run #3:  191.784973ms
Load performance Run #4:  191.239836ms
Load performance Run #5:  203.159501ms
Load Performance median:  193.219655ms
Single File:
CPU Speed is 3392 with multiplier 13000000
Performance Run #1:  3749.119887ms
Performance Run #2:  3758.879529ms
Performance Run #3:  3745.368525ms
Performance Run #4: …
```
> Build: Improve `npm run perf` command (fixes #5028)

- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
> Fix: `prefer-const` false positive reading before writing

- docs/developer-guide/working-with-plugins.md
- docs/user-guide/configuring.md
- lib/config/config-file.js
- tests/lib/config/config-file.js
This adds support for configs inside plugins. I think I'm lacking some positive unit tests, but I'm not sure how to create them, considering everything needs to be stubbed out.
> New: Add support for configs in plugins (fixes #3659)

- lib/rules/no-console.js
- tests/lib/rules/no-console.js
> Update: Extended no-console rule (fixes #5095)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/template-curly-spacing.md
- lib/rules/template-curly-spacing.js
- tests/lib/rules/template-curly-spacing.js
> New: `template-curly-spacing` rule (fixes #5049)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-extra-label.md
- lib/rules/no-extra-label.js
- tests/lib/rules/no-extra-label.js
> New: `no-extra-label` rule (fixes #5059)

- lib/rules/no-unexpected-multiline.js
- tests/lib/rules/no-unexpected-multiline.js
> Fix `no-unexpected-multiline` false positive

- conf/environments.js
- docs/user-guide/configuring.md
Following up from https://github.com/eslint/eslint/issues/3599
> Update: Adding environment for commonalities between node and browser

- docs/rules/prefer-template.md
> Docs: Add `quotes` to related section of `prefer-template`

- docs/rules/README.md
> Docs: Add note about only-whitespace rule for `--fix`

- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
> Fix: `key-spacing` not enforcing no-space in minimum mode

- lib/rules/no-empty-function.js
- tests/lib/rules/no-empty-function.js
> Fix: `no-empty-function` crash (fixes #5227)

- templates/needs-info.md.ejs
> Fix: ESLint Bot mentions the wrong person for extra info

- docs/user-guide/migrating-to-2.0.0.md
I added [New Rules in `"eslint:recommended"`] section.
> Docs: Update migrating-to-2.0.0.md

- docs/rules/no-magic-numbers.md
I update "no-magic-numbers" document.
> Docs:no-magic-numbers#ignorearrayindexes

- docs/rules/yield-star-spacing.md
> Docs: Update yield-star-spacing documentation for 2.0.0

- lib/rules/func-style.js
- tests/lib/rules/func-style.js
> Fix: `func-style` should ignore ExportDefaultDeclarations

- Makefile.js
> Build: `npm run perf` command should check the exit code

- lib/rules/indent.js
- tests/lib/rules/indent.js
> Fix: `indent` rule forgot about some CallExpressions

- lib/rules/constructor-super.js
- lib/rules/no-this-before-super.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/no-this-before-super.js
Fixes #5319.
@mysticatea - I'm not sure whether what I did makes sense or not so feel free to guide me. Apparently I'm not great at understanding code path analysis :)
> Fix: Crash in `constructor-super`

- lib/rules/no-self-assign.js
- tests/lib/rules/no-self-assign.js
> Fix: `no-self-assign` false positive at shorthand (fixes #5371)

- lib/rules/indent.js
- tests/lib/rules/indent.js
>  Fix: Indentation rules incorrectly flag properly indented code

- lib/rules/no-useless-constructor.js
- tests/lib/rules/no-useless-constructor.js
> Fix: `no-useless-constructor` rule crashes sometimes

- docs/rules/newline-per-chained-call.md
- lib/rules/newline-per-chained-call.js
- tests/lib/rules/newline-per-chained-call.js
> Fix:`newline-per-chained-call` should only warn on methods

- docs/rules/README.md
Forgot to update README.md
See issue #5350 / pull #5356
> Docs: README.md, prefer-const; change modified to reassigned

- docs/rules/no-new-func.md
`npm run check-commit` says "More than one commit found, please squash", but there is only one commit in this branch/PR. I guess maybe that is because it is checking my original PR.
I wasn't sure whether to even include "(refs #5451)" since the pull request portion of that PR isn't going to be submitted and since commits tagged with "Docs" are stated as not needing their own issue.
> Docs: Minor fixes in no-new-func (refs #5451)

- docs/user-guide/configuring.md
> Docs: Invalid json in `configuring.md`

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-duplicate-imports.md
- lib/rules/no-duplicate-imports.js
- tests/lib/rules/no-duplicate-imports.js
Ref #3478
My first attempt at writing a rule, seemed like a relatively low-hanging fruit :smile:
> New: `no-duplicate-imports` rule (fixes #3478)

- docs/rules/space-unary-ops.md
- lib/rules/space-unary-ops.js
- tests/lib/rules/space-unary-ops.js
In the process of implementing this, I've abstracted some of the logic for handling spaces out into their own functions, so as to make the logic easier to reason about.  Would love to hear your thoughts.
> Update: Overrides for space-unary-ops (fixes #5060)

- docs/rules/prefer-const.md
- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
> Fix: `prefer-const` false positive at non-blocked if (fixes #5610)

- docs/rules/generator-star-spacing.md
- docs/rules/generator-star.md
- docs/rules/no-lone-blocks.md
- docs/rules/no-unused-vars.md
- docs/rules/no-var.md
in 5 rule pages under ECMAScript 6
> Docs: Remove or rewrite references to former ecmaFeatures

- docs/rules/no-sequences.md
Very minor changes to no-sequence docs. ~~Can merge myself after I get the okay from a few team members~~ Just realized @nzakas commented on the issue, so will merge :)
> Docs: Update no-sequences rule docs for clarity (fixes #5536)

- lib/config/config-validator.js
- tests/lib/config/config-validator.js
- tests/lib/eslint.js
Fixes https://github.com/eslint/eslint/issues/5653
> Fix incorrect config message (fixes #5653)

- docs/user-guide/configuring.md
Remove mention of brace expansion after conversation in #5314
I added a section about the specific issue I was having. If you think it's not necessary I can remove it :+1:
> Docs: remove brace expansion from configuring.md

- lib/config/config-file.js
- tests/lib/config/config-file.js
> Fix: missing support for json sub configs

- package.json
- tests/lib/rules/no-undef.js
> Upgrade: globals 9.x (fixes #5668)

- appveyor.yml
- package.json
Added enviroment variables according to the docs: [AppVeyor](https://www.appveyor.com/docs/build-configuration#environment-variables), [Travis](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-.travis.yml)
> Build: Add phantomjs cdn to build (fixes #5666)

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Adding new options `exceptions` and `exceptionsIgnorePattern` as mentioned in #3837 . Please verify and let me know if anything more needs to be added.
( sorry for duplicate pull request , still not expert at squashing)
> Update: Add 'caughtErrors' to rule no-unused-vars (fixes #3837)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-useless-escape.md
- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> New: Rule - No useless escape (fixes #5460)

- lib/rules/no-unused-vars.js
- lib/rules/no-useless-escape.js
- tests/lib/ignored-paths.js
- tests/lib/rules/no-unused-vars.js
Recommend waiting for Travis and/or AppVeyor before merging.
> Fix: lines-around-comment in ESLint repo, part 2 (refs #5188)

- docs/rules/no-unused-vars.md
Fix: Changed article from "an" to "a" in front of "string".
> Docs: Fix: Typo

- package.json
Just bumps the release tool to the version with the bundling fix.
> Build: Fix bundling script (fixes #5680)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> Update: make `no-useless-escape` allowing line breaks (fixes #5689)

- docs/rules/no-constant-condition.md
- docs/rules/no-eval.md
- docs/rules/no-restricted-modules.md
* no-constant-condition: reduce from 5 incorrect and 3 correct code wells to 1 each and make them parallel: if, for, while, do...while, ternary
* no-eval: add example sentences for different environments
* no-restricted-modules: enclose json config in braces; Examples of **correct** code
> Docs: Edit examples for a few rules

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> Fix: no-useless-escape \B regex escape (fixes #5750)

- lib/config/config-file.js
> Fix: remove `console.dir` (fixes #5770)

- docs/user-guide/command-line-interface.md
> Docs: Add note about shell vs node glob parameters in cli

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> Update: no-useless-escape / exact locations of errors (fixes #5751)

- docs/rules/no-constant-condition.md
- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
Adding new condition to the rule 'no-constant-condition' as discussed in #5228 . More test cases can be added as part of #5693 .
> Update: Include 'typeof' in rule 'no-constant-condition' (fixes #5228)

- lib/rules/array-callback-return.js
- lib/rules/arrow-body-style.js
- lib/rules/arrow-parens.js
- lib/rules/arrow-spacing.js
- lib/rules/block-scoped-var.js
- lib/rules/block-spacing.js
- lib/rules/brace-style.js
- lib/rules/callback-return.js
- lib/rules/camelcase.js
- lib/rules/comma-dangle.js
- lib/rules/comma-spacing.js
- lib/rules/comma-style.js
- lib/rules/complexity.js
- lib/rules/computed-property-spacing.js
- lib/rules/consistent-return.js
- lib/rules/consistent-this.js
- lib/rules/constructor-super.js
- lib/rules/curly.js
- lib/rules/default-case.js
- lib/rules/dot-location.js
Add metadata to the existing rules. Batch 1. There will be roughly 11 batches in total.
The metadata was extracted out of lib/rules/README.md and I am using a jscodeshift transform to programmatically do the changes (with a few manual adjustments). [Here](https://gist.github.com/vitorbal/18f75cb8643e51c3540b344a67c4ddb3)'s the transform code, in case anyone is interested :)
> Update: Add metadata to existing rules - Batch 1 (refs #5417)

- docs/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
This reverts commit 134cb1f4f7242d47d54033843a8b4db0b48f6c03.
> Update: adds nestedBinaryExpressions for no-extra-parens rule (fixes #3065)

- lib/rules/dot-notation.js
- lib/rules/eol-last.js
- lib/rules/eqeqeq.js
- lib/rules/func-names.js
- lib/rules/func-style.js
- lib/rules/generator-star-spacing.js
- lib/rules/global-require.js
- lib/rules/guard-for-in.js
- lib/rules/handle-callback-err.js
- lib/rules/id-blacklist.js
- lib/rules/id-length.js
- lib/rules/id-match.js
- lib/rules/indent.js
- lib/rules/init-declarations.js
- lib/rules/jsx-quotes.js
- lib/rules/key-spacing.js
- lib/rules/keyword-spacing.js
- lib/rules/linebreak-style.js
- lib/rules/lines-around-comment.js
- lib/rules/max-depth.js
Add metadata to the existing rules. Batch 2 of 11.
> Update: Add metadata to existing rules - Batch 2 (refs #5417)

- docs/rules/quotes.md
- lib/rules/quotes.js
- tests/lib/rules/quotes.js
> Update: allow template literals (fixes #5234)

- README.md
> Docs: Add alberto as reviewer

- lib/config/config-initializer.js
- tests/lib/config/config-initializer.js
> Fix: Install ESLint on init if not installed (fixes #5833)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
> Fix: `no-useless-escape` false positive in JSXAttribute (fixes #5882)

- lib/cli-engine.js
- tests/lib/cli-engine.js
This turned out to be pretty easy and seems to work fairly well. The fix mode test does a good job of exercising fix mode in general, so it was simple to make the changes and see the effect on the output.
> Update: Autofixing does multiple passes (refs #5329)

- docs/rules/prefer-arrow-callback.md
- lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-arrow-callback.js
Fixes #4668.
Took over #4764 where @hax left.
> Update: Add `allowUnboundThis` option to `prefer-arrow-callback`

- lib/rules/comma-dangle.js
- lib/rules/no-dupe-args.js
- lib/rules/prefer-arrow-callback.js
- tests/lib/eslint.js
- tests/lib/rules/no-self-assign.js
- tests/lib/rules/no-unused-vars.js
Issue is still pending approval, but I'm opening this so you can see the proposed changes.
> Update: Remove workaround for espree and escope bugs (fixes #5852)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-useless-computed-key.md
- docs/rules/object-shorthand.md
- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
> New: Add `no-useless-computed-key` rule

- package.json
- tests/lib/util/comment-event-generator.js
- tests/lib/util/source-code.js
Upgrade Espree for the comment attachment fix: https://github.com/eslint/espree/issues/264
> Upgrade: espree 3.1.4

- docs/developer-guide/working-with-rules-new.md
- docs/developer-guide/working-with-rules.md
Passing `col` definitely doesn't work.
> Update docs to refer to column

- lib/rules/prefer-spread.js
- lib/rules/prefer-template.js
- lib/rules/quote-props.js
- lib/rules/quotes.js
- lib/rules/radix.js
- lib/rules/require-jsdoc.js
- lib/rules/require-yield.js
- lib/rules/semi-spacing.js
- lib/rules/semi.js
- lib/rules/sort-imports.js
- lib/rules/sort-vars.js
- lib/rules/space-before-blocks.js
- lib/rules/space-before-function-paren.js
- lib/rules/space-in-parens.js
- lib/rules/space-infix-ops.js
- lib/rules/space-unary-ops.js
- lib/rules/spaced-comment.js
- lib/rules/strict.js
- lib/rules/template-curly-spacing.js
- lib/rules/use-isnan.js
- lib/rules/valid-jsdoc.js
- lib/rules/valid-typeof.js
- lib/rules/vars-on-top.js
- lib/rules/wrap-iife.js
- lib/rules/wrap-regex.js
- lib/rules/yield-star-spacing.js
- lib/rules/yoda.js
Chore: Add metadata to existing rules - Batch 7 of 7 (refs #5417)
Last batch! 🎉
> Chore: Add metadata to existing rules - Batch 7 (refs #5417)

- conf/eslint.json
- docs/rules/README.md
- docs/rules/no-unsafe-finally.md
- lib/rules/no-unsafe-finally.js
- tests/lib/rules/no-unsafe-finally.js
> New: Rule - 'no-unsafe-finally' (fixes: #5808)

- lib/rules/no-unsafe-finally.js
- tests/lib/rules/no-unsafe-finally.js
> Fix: Removed false positives of break and continue (fixes #5972)

- README.md
I have updated the FAQs about JSHint because:
- I don't even know who Andy and Rick are, so this is not helpful information for me. I think a more direct answer is preferable.
- ESLint is quite popular, so I don't think it needs to justify its existence :).
ping @nzakas
> Docs: Update readme info about jshint

- docs/rules/comma-dangle.md
Add a sentence and a code example about diff clarity to comma-dangle docs.
> Docs: Add example of diff clarity to comma-dangle rule docs

- lib/rules/array-bracket-spacing.js
- lib/rules/arrow-parens.js
- lib/rules/arrow-spacing.js
- lib/rules/block-spacing.js
- lib/rules/comma-spacing.js
- lib/rules/comma-style.js
- lib/rules/computed-property-spacing.js
- lib/rules/curly.js
- lib/rules/default-case.js
- lib/rules/dot-location.js
- lib/rules/eol-last.js
- lib/rules/eqeqeq.js
- lib/rules/generator-star-spacing.js
- lib/rules/indent.js
- lib/rules/key-spacing.js
- lib/rules/linebreak-style.js
- lib/rules/lines-around-comment.js
- lib/rules/max-len.js
- lib/rules/new-cap.js
- lib/rules/new-parens.js
I'm splitting this in several PRs to make it easier to review. Let me know if you would prefer a single one.
> Chore: Replace deprecated calls to context - batch 1 (refs #6029)

- package.json
Prevents our CI builds from failing. Not sure if this should be tagged `Build` or `Upgrade`
> Build: Pin proxyquire to ">=1.0.0 <1.7.5" (fixes #6096)

- docs/rules/prefer-const.md
- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
Fixes #5692.
I added an option `ignoreReadingBeforeInit`.
> Update: Add an option to `prefer-const` (fixes #5692)

- lib/testers/rule-tester.js
~~Pushing this as a temporary fix for our build while we find the root issue.~~
> Fix: Replace `assert.deepEqual` by `lodash.isEqual` (fixes #6111)

- docs/rules/max-statements-per-line.md
- docs/rules/new-cap.md
- docs/rules/new-parens.md
- docs/rules/newline-after-var.md
- docs/rules/newline-before-return.md
- docs/rules/newline-per-chained-call.md
- docs/rules/no-array-constructor.md
- docs/rules/no-bitwise.md
- docs/rules/no-continue.md
- docs/rules/no-inline-comments.md
This one was fairly straight-forward. I don't believe there was anything new to add to the guidelines with these rule docs.
@pedrottimark Let me know if you find something where you disagree, however (plus anything I missed).
> Docs: Distinguish examples in rules under Stylistic Issues part 4

- lib/config.js
- lib/options.js
- tests/lib/options.js
Correct solution to what was done in #6108
> Fix: Parser merge sequence in config (fixes #6158)

- lib/rules/generator-star-spacing.js
- tests/lib/rules/generator-star-spacing.js
Fixes #6135.
In addition, this should work fine for async function as well.
> Fix: `generator-star-spacing` false positive (fixes #6135)

- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
> Update: key-spacing rule whitespace fixer (fixes: #6167)

- lib/rules/max-statements-per-line.js
- tests/lib/rules/max-statements-per-line.js
> Fix: `max-statements-per-line` false positive at exports (fixes #6264)

- docs/rules/README.md
Now I made the commit with valid name and email. Sorry for the duplication.
> Docs: Mark no-useless-rename as fixable in rules index

- tests/lib/rules/newline-before-return.js
Context: https://github.com/eslint/eslint/pull/6093
> Chore: more tests for comments at the end of blocks (refs #6090)

- docs/rules/max-lines.md
Per https://github.com/eslint/eslint/blob/master/lib/rules/max-lines.js#L40
> Docs: `max-lines option: fix `skipComments` typo

- lib/config/config-initializer.js
- lib/util/npm-util.js
- tests/lib/util/npm-util.js
The output if "guide" is selected without a package.json:
> Fix: Exit init early if guide is chosen w/ no package.json (fixes #6476)

- .travis.yml
- appveyor.yml
- package.json
Let's get the ball rolling. Anything else needed?
> Breaking: Drop support for node < 4 (fixes #4483)

- docs/rules/README.md
- docs/rules/no-native-reassign.md
- docs/user-guide/configuring.md
- lib/rules/no-native-reassign.js
- tests/lib/rules/no-native-reassign.js
Fixes #5358.
- I added a note into `user-guide/configuring.md`
- I improved the document of `no-native-reassign` by the corrections of #6395
> Docs: improve `no-native-reassign` and specifying globals (fixes #5358)

- docs/rules/no-duplicate-imports.md
Fixes #6455
Probably not perfect, but it should be a start!
/cc @aubergine10  @pedrottimark
> Docs: Rephrase documentation for `no-duplicate-imports`

- lib/rules/object-curly-spacing.js
- tests/lib/rules/object-curly-spacing.js
Long time user and fan, first time contributor. My attempt at fixing something that has been bothering me a lot lately. Looking forward to your feedback 😄
> Fix: Allow objectsInObjects exception when destructuring (fixes #6469)

- lib/rules/no-else-return.js
- tests/lib/rules/no-else-return.js
This is the requested pull request for the opened issue #6411. I also took the time to remove the warning in the file related to the rule "no-else-return". I hope this is ok.
> Better wording for the error reported by the rule "no-else-return" #6411

- lib/rules/no-useless-rename.js
- tests/lib/rules/no-useless-rename.js
> Fix: false negative of `no-useless-rename` (fixes #6502)

- README.md
- docs/maintainer-guide/governance.md
- docs/maintainer-guide/issues.md
- docs/maintainer-guide/pullrequests.md
First pass at updating the docs for the TSC.
> Docs: Update Governance Policy (fixes #6452)

- docs/user-guide/migrating-to-3.0.0.md
Draft of the migration guide for 3.0.0.
> Docs: 3.0.0 migration guide

- README.md
We still get a lot of questions about global vs. local install. This PR updates the README with better information about that.
> Docs: Update installation instructions on README

- docs/rules/no-implicit-globals.md
Convert example to use string severity.
> Docs: Use string severity in example

- .github/PULL_REQUEST_TEMPLATE.md
We've had quite a few pull requests opened recently without issues, so I'd like to see if adding a pull request template will help minimize that. This PR adds a simple template with just a few questions.
> Docs: Pull request template

- package.json
#6621
I updated the dependency to `mock-fs@3.10.0`.
The tests on Travis for Node 6.3 should be fixed.
> Upgrade: mock-fs to 3.10, fixes for Node 6.3 (fixes #6621)

- docs/user-guide/getting-started.md
> Fix: copyedit

- docs/user-guide/command-line-interface.md
Small inconsistencies and tiny inaccuracies in the CLI options documentation.
Small tweaks here and there.
I went beyond what I promised in the issue-- please let me know if any of these changes are unwanted or could be improved.
> Docs: Small tweaks to CLI documentation (fixes #6627)

- docs/rules/spaced-comment.md
- lib/rules/spaced-comment.js
- tests/lib/rules/spaced-comment.js
First time PR - looking to get some feedback on these changes!
> Update: Add `balanced` option to `spaced-comment` (fixes #4133)

- docs/rules/no-underscore-dangle.md
> Docs: Fix option typo in no-underscore-dangle (Fixes #6674)

- lib/rules/indent.js
- tests/lib/rules/indent.js
#6613 
Recurse up the AST to the first ExpressionStatement or VariableDeclaration to verify the IIEF is a top level function even if it is not at the top of the AST.
This is my first PR for this project.
> Update: relax outerIIFEBody definition (fixes: 6613)

- docs/rules/spaced-comment.md
> None
> Only documents. Add missing brackets from code examples on `spaced-comment.md`.
> Nope
> Docs: Add missing brackets from code examples

- docs/maintainer-guide/issues.md
- docs/maintainer-guide/pullrequests.md
#6009 
Added docs for when issue and PRs can be closed. Also cleaned up some old info that isn't really how we've been doing things.
Review for accuracy.
> Docs: Edit issue/PR waiting period docs (fixes #6009)

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
#5179
Updated the references in comments and docs for the Node.js CLI API options.
Verify that options are correctly named.
> Chore: Update CLIEngine option desc (fixes #5179)

- .travis.yml
#6743
Remove Node v5 from our CI
No
> Build: Remove support for Node v5 (fixes #6743)

- packages/eslint-config-eslint/default.yml
#6407 
I enabled some ES6 rules for internal use.
The options I chose for the rules
> Chore: Dogfooding ES6 rules (refs #6407)

- docs/user-guide/README.md
fix wrong path
[http://eslint.org/docs/user-guide/#rulesrules](http://eslint.org/docs/user-guide/#rulesrules)
the link does not work, it will open a dialog:
no
> Docs: fix wrong path

- docs/rules/no-void.md
Documentation copy change
Small typo: is -> in; and commas
> Update: no-void.md

- docs/maintainer-guide/issues.md
#6765
Updated the maintainer guide to describe that unaccepted issues should be closed after 21 days.
Wording is understandable.
> Docs: Update issue closing policy (fixes #6765)

- package.json
#6821 
Unpinned proxyquire.
No.
> Upgrade: proxyquire to 1.7.10 (fixes #6821)

- templates/needs-info.md.ejs
Fixes #6829.
Added link to "Proposing a Rule Change" page. Also moved bug section to its own line to improve clarity.
Nope.
> Chore: Add link to rule change guidelines in "needs info" template

- docs/rules/lines-around-comment.md
> Docs: Remove duplicate statement (fixes #6879)

- lib/config/config-initializer.js
> Update: rename "AirBnB" => "Airbnb" fixes #6968

- docs/user-guide/migrating-from-jscs.md
#5859 
Began the JSCS migration guide. This is just meant to be a starting point, don't get too worried if important stuff is missing. :)
* What other terms are important to include in "Terminology"?
* What other steps will be necessary for people to convert their configs?
* What other information would be helpful for JSCS users to get acclimated to ESLint?
@markelog @mikesherov @mdevils @hzoo @zxqfox
> Docs: Draft of JSCS migration guide (fixes #5859)

- docs/rules/no-implicit-coercion.md
> Docs: Add fixable note to no-implicit-coercion docs

- docs/rules/no-restricted-properties.md
```
```
* (n/a) I've included tests for my change
This …
> Docs: Fix examples for no-restricted-properties

- docs/developer-guide/nodejs-api.md
```
```
- ~~I've included tests for my change~~ N/A
Clarified that linter object does not process configuration at all, but rather expects a normalized …
> Docs: Clarify that linter does not process configuration (fixes #7108)

- docs/maintainer-guide/issues.md
```
```
Fixed two typos that slipped through in my last …
> Docs: Fix typos in Issues section of Maintainer's Guide

- docs/maintainer-guide/releases.md
Updated the maintainer guide release docs to better spell …
> Docs: Update release process

- docs/rules/no-implicit-coercion.md
- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
```
[X] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
```
Updated `no-implicit-coercion` so that it also …
> Update: no-implicit-coercion checks TemplateLiterals (fixes #7062)

- .github/PULL_REQUEST_TEMPLATE.md
- templates/rule-proposal.md
Updated the pull request template and rules template to …
> Docs: Update PR templates for formatting

- docs/rules/func-call-spacing.md
- docs/rules/init-declarations.md
- docs/rules/max-params.md
- docs/rules/max-statements.md
- docs/rules/new-cap.md
- docs/rules/newline-after-var.md
- docs/rules/no-implicit-globals.md
- docs/rules/no-inner-declarations.md
- docs/rules/no-mixed-requires.md
- docs/rules/no-redeclare.md
- docs/rules/no-shadow.md
- docs/rules/no-spaced-func.md
- docs/rules/one-var-declaration-per-line.md
- docs/rules/sort-keys.md
- docs/rules/space-infix-ops.md
- lib/rules/func-call-spacing.js
- lib/rules/init-declarations.js
- lib/rules/max-params.js
- lib/rules/max-statements.js
- lib/rules/new-cap.js
- lib/rules/newline-after-var.js
- lib/rules/no-implicit-globals.js
- lib/rules/no-inner-declarations.js
- lib/rules/no-mixed-requires.js
- lib/rules/no-redeclare.js
- lib/rules/no-shadow.js
- lib/rules/no-spaced-func.js
- lib/rules/one-var-declaration-per-line.js
- lib/rules/sort-keys.js
- lib/rules/space-infix-ops.js
Updated confusing / incorrect rule descriptions that refer to language keywords that instead apply to the overall concept (e.g. rules that apply to `const`, `let`, and `var`, but only include `var` in the description).
Does the grammar make sense? Are there other rules that should be added to this?
The issue this PR references has not been accepted, but I thought I'd get the ball rolling.
> Docs: Update rule descriptions (fixes #5912)

- docs/maintainer-guide/issues.md
In addition to the updated process for showing support for an issue, I moved some of the sections around in an effort to group together relevant info and hopefully …
> Docs: Update process for evaluating proposals (fixes #7156)

- docs/user-guide/configuring.md
Added documentation for ECMAScript 8/2017 to the configuring guide. Also added mention of using the 2015, 2016, and 2017 aliases for ecmaVersion.
**Is there …
> Docs: Update ecmaVersion instructions

- docs/user-guide/integrations.md
> Docs: Add Brunch plugin to integrations

- lib/eslint.js
[X] Other, please explain: Removed some unused code
> Fix: removed unused code related to scopeMap

- package.json
Upgrade Espree dependency to latest to fix async/await.
Espree to 3.3.1
No
> Upgrade: Upgrade Espree to 3.3.1

- .github/ISSUE_TEMPLATE.md
- (n/a) I've included tests for my change
There have been a few cases (e.g. https://github.com/eslint/eslint/issues/7164 and …
> Docs: add code fences to the issue template

- docs/rules/object-shorthand.md
I added a missing double quote in a string literal option.
No.
> Docs: Add missing double quote.

- README.md
Updated Readme file to add @not-an-aardvark to the development team.
No
> Docs: Add @not-an-aardvark to development team

- docs/maintainer-guide/governance.md
Listed the steps for adding a new committer or TSC member after they have been approved.
> Docs: Steps for adding new committers/TSCers

- .github/PULL_REQUEST_TEMPLATE.md
- ~~I've included tests for my change~~
- ~~I've updated documentation for my change (if appropriate)~~
This PR changes the links to sub templates in the PR template.
New links open raw data of the sub templates.
This would help to copy & paste.
> Docs: change links of templates to raw data

- tests/bin/eslint.js
This adds additional tests for `bin/eslint.js`. https://github.com/eslint/eslint/pull/7223 added …
> Chore: Add additional tests for bin/eslint.js

- docs/rules/wrap-iife.md
- lib/rules/wrap-iife.js
- tests/lib/rules/wrap-iife.js
wrap-iife
More, behind additional options
New option
**Please provide some example code …
> Update: wrap-iife supporting call and apply. Fixes #7212

- docs/user-guide/command-line-interface.md
> Docs: Updating CLI overview with latest changes

- lib/rules/no-multiple-empty-lines.js
- tests/lib/rules/no-multiple-empty-lines.js
This refactors `no-multiple-empty-lines` to be shorter and more …
> Chore: refactor `no-multiple-empty-lines`

- conf/eslint.json
- docs/rules/func-name-matching.md
- lib/rules/func-name-matching.js
- tests/lib/rules/func-name-matching.js
ref: https://github.com/eslint/eslint/issues/6065
> New: `func-name-matching` rule

- docs/rules/no-loop-func.md
Documentation change
Not sure if it will ever return, but …
> Docs: Remove broken link from no-loop-func docs

- tests/bin/eslint.js
- tests/fixtures/autofix-integration/left-pad-expected.js
- tests/fixtures/autofix-integration/left-pad.js
This adds integration tests for autofixing files, as described in …
> Chore: add integration tests for autofixing (fixes #5909)

- docs/maintainer-guide/pullrequests.md
Following today's TSC meeting, added a note that committers may merge any PR that has been …
> Docs: Relax permission for merging PRs (refs eslint/tsc-meetings#20)

- docs/rules/no-cond-assign.md
- docs/rules/no-delete-var.md
- docs/rules/no-ex-assign.md
- docs/rules/no-floating-decimal.md
- docs/rules/no-implied-eval.md
- docs/rules/no-label-var.md
- docs/rules/no-multi-str.md
- docs/rules/no-new-func.md
- docs/rules/no-obj-calls.md
- docs/rules/no-octal.md
- docs/rules/no-regex-spaces.md
- docs/rules/no-self-compare.md
- docs/rules/no-undef.md
- docs/rules/no-wrap-func.md
- docs/rules/one-var.md
- docs/rules/radix.md
- docs/rules/use-isnan.md
All links to jslinterrors.com in the docs are deleted. Fixes #7368.
See also https://github.com/jamesallardice/jslint-error-explanations/issues/39
> Docs: Remove broken links to jslinterrors.com (fixes #7368)

- docs/rules/max-len.md
- lib/rules/max-len.js
- tests/lib/rules/max-len.js
Fixes issue #3229.
Added an `ignoreRegexpsLiteral` option, added tests, and updated docs. …
> Update: Add an ignoreRegexpLiterals option to max-len (fixes #3229)

- lib/eslint.js
- lib/rule-context.js
- tests/fixtures/parsers/enhanced-parser.js
- tests/lib/eslint.js
- tests/lib/rule-context.js
#6974
Implemented `context.parserServices`
This is just a WIP prototype so people can take a look and even play with it to see if it solves some of the problems mentioned in the issue.
> New: Support enhanced parsers (fixes #6974)

- docs/rules/brace-style.md
- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
This adds a fixer for [`brace-style`](http://eslint.org/docs/rules/brace-style). Also see: …
> Update: add fixer for `brace-style` (fixes #7074)

- docs/rules/no-unexpected-multiline.md
Fixed a typo in documentation.
No.
> Fix a typo (#7442)

- Makefile.js
See https://github.com/eslint/eslint/issues/7419
This fixes a bug in URL handling when generating the site.
The build script is designed to remove .md extensions from relative links:
```markdown …
```
> Build: Ensure absolute links in docs retain .md extensions (fixes #7419)

- docs/rules/prefer-reflect.md
- lib/rules/prefer-reflect.js
- tests/lib/rules/prefer-reflect.js
Update `prefer-reflect`'s documentation, add the `deprecated` key to `prefer-reflect`'s metadata, and fix our own `conf/eslint.json` to use the replacements for the currently deprecated rules.
**Is …
> Update: Deprecate prefer-reflect (fixes #7226)

- LICENSE
Updated the copyright to be for the JS Foundation instead of jQuery Foundation
> Docs: Update copyright

- .travis.yml
- package.json
* add `node 7` support
* upgrade dev dependency - `mock-fs`
> Chore: Add Node 7 to travis ci build

- docs/developer-guide/working-with-rules.md
See https://github.com/eslint/eslint.github.io/issues/300
> Specify min ESLint version for new rule format

- lib/rules/max-statements.js
- tests/lib/rules/max-statements.js
Improves the linting message.
Finished up #7261 by changing the error message to include the function name or "this function" for anonymous functions. …
> Fix: max-statements to report function name (refs #7260)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
Additional spaces were being accounted for in the logic, I implemented a fix, trimming the escape character to have an accurate representation of the escapes given the current logic.
**Is there …
> Fix: Add support for escape char in JSX.

- CHANGELOG.md
- docs/rules/func-name-matching.md
> Docs: `func-name-matching`: update with “always”/“never” option

- docs/rules/one-var.md
adding missing quotation mark to documentation (one-var rule)
> Docs: typo fix

- docs/developer-guide/working-with-rules.md
> Fix: missing semicolon report was missing a comma

- README.md
Updated the Code of Conduct link to point to the JS Foundation website instead of the jQuery website.
Double-check that the URL is correct.
> Docs: Update code of conduct link

- tests/lib/ast-utils.js
[x] Other, please explain: Chore: Fix lint errors
Fixed `prefer-arrow-callback` errors in tests/lib/ast-utils.js.
Nothing in particular. If we can merge this quickly then hopefully there won't be conflicts or surprise lint errors.
> Chore: Fix prefer-arrow-callback lint errors

- docs/rules/require-yield.md
Replace "that have `yield` expression" by the "that have no `yield` expression" in the  **When Not To Use It**.
No.
> Docs: Fix a typo in the require-yield.md

- docs/rules/capitalized-comments.md
This fixes a spelling error in the `capitalized-comments` docs.
> Docs: fix a typo in capitalized-comments documentation

- docs/user-guide/integrations.md
> Update: Change Sails.js integration to active npm package

- docs/user-guide/configuring.md
I just noticed this and thought it would be helpful for new users who may be just getting started in this ecosystem.
Moved from https://github.com/eslint/eslint.github.io/pull/315
> Docs: link first instance of `package.json`

- package.json
- tests/lib/rules/no-undef.js
Update dependency in `package.json`.
Updated `globals` dependency to 9.14.0, added `no-undef` rule tests for some global object properties, which were added to `globals` in versions from 9.2.0 to …
> Upgrade: Update globals dependency to 9.14.0

- lib/config/config-initializer.js
- tests/lib/config/config-initializer.js
[X ] Add something to the core
https://github.com/eslint/eslint/issues/6986
I added an aditional question to allow using airbnb-base styleguide, without React.
Nothing in …
> Update: Add airbnb-base to init styleguides (fixes #6986)

- docs/user-guide/migrating-from-jscs.md
Mr Doob Code Style is now available as an npm module.
> Add eslint-config-mdcs to JSCS Migration Guide

- docs/rules/semi.md
I changed mistake in example in semi.md file
Last example in the file was marked as incorrect, but should be **correct**
> Docs: fix in semi.md example

- lib/config/config-initializer.js
Prevent including an internal flag to the generated config in `--init`.
No.
> Fix: remove internal property from config generation (fixes #7758)

- docs/rules/prefer-spread.md
Adding an example of using the spread operator per [#7802](https://github.com/eslint/eslint/issues/7802). 
Do I need to squash the commits?
> Docs: Adding an example for the spread operator to prefer-spread.md (#7802)

- lib/testers/rule-tester.js
- tests/lib/testers/rule-tester.js
This is continued from https://github.com/eslint/eslint/pull/7160. I'm making a new PR because the original repo from that PR appears to have been deleted. …
> Fix: Throw error if ruletester is missing required test scenarios

- README.md
In the FAQ section of the README, clarify that we only support ECMAScript language features that are Stage 4 proposals (per the TC39 process) and explain that we don't support Stage 3 proposals due …
> Docs: Clarify that we only support Stage 4 proposals

- lib/config.js
- lib/file-finder.js
- lib/ignored-paths.js
- lib/rule-context.js
> Chore: Refactor to use ES6 Classes (Part 2)

- docs/rules/padded-blocks.md
> Docs: `padded-blocks` `never` case (fixes #7868)

- lib/code-path-analysis/code-path-analyzer.js
- lib/code-path-analysis/code-path-segment.js
- lib/code-path-analysis/code-path-state.js
- lib/code-path-analysis/code-path.js
- lib/code-path-analysis/fork-context.js
- lib/code-path-analysis/id-generator.js
> Chore: Refactor to use ES6 Classes (Part 3)(refs #7849)

- docs/rules/space-before-blocks.md
`space-after-keywords` appears as deleted in the docs and it's confusing to reference it.
> Docs: remove reference to deleted rule

- README.md
I updated README.md with new TSC member @not-an-aardvark .
> Docs: update README.md for team

- package.json
Dependency version bump
Ensure the minimum version of Espree is v3.4.0. Acorn v4.0.5 is currently causing some issues, and we had to lock the version in Espree to v4.0.4.
Relevant issues:
- …
> Upgrade: Espree v3.4.0

- docs/developer-guide/nodejs-api.md
- docs/user-guide/command-line-interface.md
- docs/user-guide/configuring.md
Update docs regarding `--ext`
No.
> Docs: Clarify --ext only works with directories (fixes #7939)

- package.json
Upgrade `eslint-plugin-node` to latest version to get rid of install warning and benefit from updates in the library.
Update package.json
No.
> Chore: upgrade eslint-plugin-node

- lib/util/source-code-fixer.js
- tests/lib/rules/padded-blocks.js
- tests/lib/util/source-code-fixer.js
Ignore fixes with negative ranges.
I don't think https://github.com/eslint/eslint/pull/8117 is the sensible thing to do. I created a different …
> Update: ignore negative ranges in fixes

- docs/rules/nonblock-statement-body-position.md
…sition`
Remove statement about rule being fixable. This is now injected automatically in the docs.
No.
> Docs: Remove unneeded statement about autofix

- package.json
Upgrade coveralls to get rid of warning on install about using a deprecated package. Also added `^` to version.
I used "Chore" tag instead of "Upgrade" since this is a dev dependency, so it …
> Chore: upgrade `coveralls` to ^2.11.16

- docs/developer-guide/working-with-plugins.md
This lists the available properties for RuleTester cases rather than relying on a usage example.
Let me know if there's anything unclear/incorrect in the updated documentation.
> Docs: improve documentation for RuleTester cases

- docs/developer-guide/working-with-rules.md
- lib/ast-utils.js
- lib/rules/no-multiple-empty-lines.js
- lib/rules/no-unused-vars.js
- lib/rules/no-useless-escape.js
- lib/util/source-code.js
- tests/lib/ast-utils.js
- tests/lib/util/source-code.js
This implements `SourceCode.getLocFromIndex` and `sourceCode.getIndexFromLoc` as described in https://github.com/eslint/eslint/issues/8073.
> New: add SourceCode#getLocFromIndex and #getIndexFromLoc (fixes #8073)

- package.json
A few features of the `mock-fs` module are broken in Node 7.7.0+. Since our tests rely on these features, our build is currently broken. This commit temporarily updates to a patched version of `mock-fs` from GitHub in order to fix our build. (I've also made a pull request with the patch to the main mock-fs repo.)
This is intended to be a temporary fix until a new version of mock-fs with the patch included gets released to npm.
> Chore: Upgrade to a patched version of mock-fs (fixes #8177)

- Makefile.js
Fixes #8013.
We were not sorting the rules properly before dumping them to the doc files. This PR changes that.
> Sort rules before dumping them to doc files

- docs/developer-guide/code-path-analysis.md
- docs/developer-guide/code-path-analysis/README.md
- docs/developer-guide/development-environment.md
- docs/developer-guide/working-with-custom-formatters.md
- docs/maintainer-guide/README.md
- docs/rules/callback-return.md
- docs/rules/id-length.md
- docs/rules/key-spacing.md
- docs/rules/no-self-compare.md
- docs/rules/no-tabs.md
- docs/rules/no-unsafe-finally.md
- docs/rules/no-use-before-define.md
- docs/rules/no-var.md
- docs/rules/no-warning-comments.md
- docs/rules/operator-linebreak.md
- docs/rules/prefer-const.md
- docs/rules/require-jsdoc.md
- docs/rules/space-before-function-parentheses.md
- docs/user-guide/command-line-interface.md
[ x ] Documentation update
Replacement for https://github.com/eslint/eslint/pull/8200
typo fixes
n/a
> Docs: fix typos

- Makefile.js
Remove unneeded command from site generation task.
No
> Build: remove unneeded json config in demo (fixes #8237)

- package.json
`mock-fs` merged the fs.stat patch described in 0af90578 and created a new release, so now we can depend on the module from npm again instead of the version from GitHub.
> Upgrade: mock-fs to v4.2.0 (fixes #8194)

- lib/rules/func-name-matching.js
- tests/lib/rules/func-name-matching.js
[x] Bug fix
* **Node Version:** 7.7.2
default
```yml
rules:
func-name-matching: error
parserOptions:
ecmaVersion: 6
```
```js
[a] = function foo() {};
```
I expected ESLint to not crash.
ESLint crashed.
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
at isIdentifierNameES5 …
```
> Fix: func-name-matching crash on destructuring assignment to functions

- Makefile.js
Small typo in `Makefile.js` in `console.error`
Added `e`
> Fix: typo in console.error

- package.json
Upgrade doctrine to latest version
No
> Upgrade: doctrine to 2.0.0

- package.json
Upgrade mocha to get rid of last security warning on NPM install. While security issue wasn't affecting us directly, warning was annoying.
Upgrade mocha to 3.2.0
Nothing
> Upgrade: Mocha to 3.2.0

- tests/lib/rules/array-bracket-spacing.js
- tests/lib/rules/no-restricted-modules.js
- tests/lib/rules/no-restricted-properties.js
Some properties of rule tests contained typos, so the tests were not asserting what we thought they were. This updates the tests to fix the typos.
> Chore: Fix typos in test option assertions

- packages/eslint-config-eslint/default.yml
This enables `max-statements-per-line` on the ESLint codebase. There are no existing violations.
> Chore: enable max-statements-per-line on ESLint codebase

- README.md
I added soda0289 to the Development Team list in the readme!
> Docs: Add soda0289 to Development Team

- Makefile.js
- lib/ast-utils.js
- lib/eslint.js
- lib/rules/block-scoped-var.js
- lib/rules/func-names.js
- lib/rules/global-require.js
- lib/rules/no-alert.js
- lib/rules/no-console.js
- lib/rules/no-dupe-args.js
- lib/rules/no-eval.js
- lib/rules/no-loop-func.js
- lib/rules/no-redeclare.js
- lib/rules/no-undefined.js
- lib/rules/no-unmodified-loop-condition.js
- lib/rules/no-unused-vars.js
- lib/rules/no-use-before-define.js
- lib/rules/no-var.js
- lib/rules/prefer-arrow-callback.js
- lib/rules/prefer-const.js
- lib/rules/prefer-rest-params.js
- lib/rules/radix.js
- package.json
- tests/lib/eslint.js
Switches to eslint-scope for 4.0.0 per #8266
Remove escope and replaced with eslint-scope
Nope is a drop in replacement no changes to eslint
> Chore: Switch to eslint-scope from escope

- conf/eslint-recommended.js
- tests/lib/ast-utils.js
- tests/lib/config.js
Remove `ecmaFeatures` from `eslint:recommended`. It's not a top level property since eslint v2.0.0.
Should be tagged: 'Chore'? Not sure, since …
> Breaking: Remove `ecmaFeatures` from `eslint:recommended`

- conf/eslint-recommended.js
- docs/rules/no-buffer-constructor.md
- lib/rules/no-buffer-constructor.js
- tests/lib/rules/no-buffer-constructor.js
[x] New rule (https://github.com/eslint/eslint/issues/5614)
This adds the `no-buffer-constructor` rule, as described in https://github.com/eslint/eslint/issues/5614.
> New: no-buffer-constructor rule (fixes #5614)

- README.md
- docs/user-guide/configuring.md
- Adds documentation in the FAQ and `configuration.md` to clarify differences between ES6 syntax and global variables configuration.
Nope, but …
> Docs: ES6 syntax vs globals configuration (fixes #7984)

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- lib/formatters/codeframe.js
- lib/formatters/stylish.js
- tests/fixtures/configurations/single-quotes-error.json
- tests/lib/cli-engine.js
- tests/lib/formatters/codeframe.js
- tests/lib/formatters/stylish.js
Add number of fixable problems to `cli-engine` and consume it in stylish formatter. This fixes #7364 
No.
> Breaking: log number of fixable problems (fixes #7364)

- docs/user-guide/migrating-to-4.0.0.md
This adds a migration guide for 4.0.0.
~~The `eslint:recommended` section still needs to be filled in after we decide on the changes in https://github.com/eslint/eslint/issues/8236.~~
~~This assumes https://github.com/eslint/eslint/issues/7395 will be accepted.~~
Fixes https://github.com/eslint/eslint/issues/8306
Let me know if there's anything unclear, incorrect, or missing from the guide.
> Docs: add 4.0.0 migration guide (fixes #8306)

- docs/user-guide/getting-started.md
Noticed that the local installation section has some confusing wording (most likely caused by copying and pasting the global installation instructions), and wanted to clarify the language.
**Is there …
> Docs: Clarify how to run local ESLint installation

- conf/eslint-recommended.js
- docs/rules/array-bracket-newline.md
- lib/rules/array-bracket-newline.js
- tests/lib/rules/array-bracket-newline.js
All information about this rule in https://github.com/eslint/eslint/issues/6073
Maybe I missed some related rules in the documentation, I am up for suggestions.
> New rule: array-bracket-newline

- docs/user-guide/migrating-to-4.0.0.md
This updates the docs to include information about the new comment getters and their deprecated counterparts.
Is this clear enough?
> Docs: Update Migrating to v4.0.0 with new comment getters

- CHANGELOG.md
This PR updates CHANGELOG.md for the v4.0.0-alpha.1 release. We should look into why it wasn't auto-generated.
Nothing in particular!
> Docs: Update CHANGELOG.md for v4.0.0-alpha.1 release

- README.md
Fixed the link to the code of conduct in `Readme.md`
> Fix: Correct code of conduct link on Readme.md

- docs/user-guide/configuring.md
Documentation of an example regarding configuring cascading and hierarchy configuration was incorrect. This PR corrects the documentation.
This is from issue I raised …
> Docs: Configuring Cascading and Hierarchy example correction

- tests/lib/rules/no-compare-neg-zero.js
> Update:del duplicated test.

- docs/user-guide/configuring.md
add linking to typescript-eslint-parser ( #8388 )
> We can definitely add a link to the site to typescript parser, just like we have a link to babel-eslint, but creating documentation for it on the site is probably an overkill.
> docs: add typescript-eslint-parser (#8388)

- conf/eslint-recommended.js
- docs/rules/switch-colon-spacing.md
- lib/rules/switch-colon-spacing.js
- tests/lib/rules/switch-colon-spacing.js
Fixes #7981.
This PR add new rule `switch-colon-spacing` which enforces spacing style around colons of switch statements.
Please check whether the tests and the document are enough.
> New: switch-colon-spacing rule (fixes #7981)

- conf/eslint-recommended.js
- docs/rules/for-direction.md
- lib/rules/for-direction.js
- tests/lib/rules/for-direction.js
linking #8387 
A for loop with a stop condition that can never be reached, such as one with a counter that moves in the wrong direction, will run infinitely. While there are occasions when an infinite loop is intended, the convention is to construct such loops as while loops. More typically, an infinite for loop is a bug.
My English is not so good. More attention can be attached to the docs and comments. 😿
> New rule: for-direction(#8387)

- lib/config/config-file.js
- package.json
The strip-bom dependency increases the package download size and the number of dependent packages, and is only used in one place. This commit removes the dependency.
> Chore: remove strip-bom dependency (refs #8603)

- docs/about/index.md
Under Philosophy section, Every rule subsection
fixes #8600
> Docs: Rephrase in about section

- lib/code-path-analysis/code-path-state.js
- lib/rules/complexity.js
- lib/rules/indent-legacy.js
- lib/rules/max-len.js
- lib/rules/no-inner-declarations.js
- lib/rules/no-irregular-whitespace.js
- lib/rules/no-lone-blocks.js
- lib/rules/no-this-before-super.js
- lib/rules/no-use-before-define.js
- lib/rules/switch-colon-spacing.js
[ X ] Other, please explain: Code clean-up.
Fixed a few instances of dead/useless code as identified by [lgtm](https://lgtm.com), see https://lgtm.com/projects/g/eslint/eslint/alerts/ for details. …
> Chore: Fix lgtm alerts.

- lib/rules/no-unneeded-ternary.js
- tests/lib/rules/no-unneeded-ternary.js
All Information available in #8507 
In the `fixer` I checked if the nodestring is an `ConditionalExpression`. If so it will be surrounded by parentheses.
Any more tests? I couldn't think of one.
> Fix: no-unneded-ternary change code behavior after fix (fixes #8507)

- conf/eslint-recommended.js
- docs/rules/semi-style.md
- lib/rules/semi-style.js
- tests/lib/rules/semi-style.js
Fixes #8169.
This PR adds new rule `semi-style` which enforces locations.
Please check whether the tests and the document are enough.
> New: semi-style rule (fixes #8169)

- README.md
> Docs: missing paren on readme

- docs/developer-guide/contributing/pull-requests.md
This is the same as https://github.com/eslint/eslint.github.io/pull/354, but it's retargeted to the eslint repo so that it doesn't get overwritten the next time the site is generated.
> Docs: Update CLA link on Pull Requests page

- Makefile.js
The license checker had been reporting errors on master because a subdependency is licensed under the LGPL, but the LGPL is acceptable for us (see https://github.com/eslint/eslint/issues/8647).
**Is …
> Build: update license checker to allow LGPL (fixes #8647)

- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
Fix #8654 
Avoid checking object destructing when accessing an integer property.
> Fix: Don't check object destructing in integer property (fix #8654)

- .travis.yml
> Build: Add Node 8 on travis

- docs/rules/strict.md
> Add note on --fix option for strict rule

- lib/rules/no-debugger.js
- tests/lib/rules/no-debugger.js
add --fix to `no-debugger`. (fixes #8659 )
> Update: add --fix to no-debugger (fixes #8659)

- packages/eslint-config-eslint/default.yml
This updates eslint-config-eslint to remove deprecated rules in favor of their newer alternatives.
> Chore: avoid using deprecated rules on ESLint codebase

- .npmrc
This adds an .npmrc file to the project root to prevent npm from creating a package-lock.json file on install.
Also see the discussion in https://github.com/eslint/eslint/issues/8742.
**Is there …
> Chore: Prevent package-lock.json files from being created (fixes #8742)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/developer-guide/contributing/README.md
Increase visibility of the code of conduct in our documentation as well as GitHub issue/PR templates.
Did I miss any spots?
> Docs: Increase visibility of code of conduct (fixes #8758)

- .eslintrc.yml
- package.json
upgrade eslint-plugin-eslint-plugin@0.7.3, eslint-plugin-node@5.1.0
no.
> Chore: upgrade eslint-plugin-eslint-plugin & eslint-plugin-node

- packages/eslint-config-eslint/default.yml
[x] Other, please explain: 
enable rule for-direction
the rule for-direction enforce “for” loop update clause moving the counter in the right direction. Typically, violating this rule is a bug.
Ideally it can be added into `eslint:recommended`, so I'm not sure it is proper to enable it now.
> Chore: enable rule for-direction

- .github/ISSUE_TEMPLATE.md
A lot of issues get created have a huge `config` section and it makes all the user scroll a lot to get to the end and also if there are many comments on the issue. This would help a little to minimize that. You can click to expand but by default …
> Chore: Add collapsible block for config in ISSUE_TEMPLATE

- docs/rules/complexity.md
Fixed #8396 by updating documentation on [Cyclomatic Complexity](http://eslint.org/docs/rules/complexity#further-reading) to fix a broken link. Also added a few more resources to the *Further Reading* section.
I did add a few more links to the section, but if it's too crowded with that many links, I'd be happy to remove some.
> Docs: Fix Cyclomatic Complexity docs

- tests/lib/rules/getter-return.js
defineProperies => defineProperties
> Chore: fix spelling error.

- .eslintrc.yml
- package.json
upgrade `eslint-plugin-eslint-plugin@0.8.0`. some new rules were enabled as follows:
+ fixer-return (recommended)
+ no-unused-placeholders (recommended)
+ prefer-output-null
no.
> Chore: upgrade eslint-plugin-eslint-plugin@0.8.0

- lib/rules/indent-legacy.js
- packages/eslint-config-eslint/default.yml
- tests/lib/ignored-paths.js
This enables a bunch of rules on the ESLint codebase for dogfooding and style consistency. Almost all of the rules were already being followed everywhere. …
> Chore: enable additional rules on ESLint codebase

- SUPPORT.md
GitHub now displays a notice about [`SUPPORT.md` files](https://github.com/blog/2400-support-file-support) when people create new issues (similar to `CONTRIBUTING.md` files). This commit adds a file …
> Docs: Create SUPPORT.md

- package.json
This upgrades `js-yaml` to `^3.9.1`. The patch contains the fix described in https://github.com/eslint/eslint/issues/9011#issuecomment-318879745. This partially fixes https://github.com/eslint/eslint/issues/9011, in that the stack trace will now explain what's wrong with a yaml config file, rather than just saying `Error`. However, it doesn't completely resolve the issue because the stack trace still doesn't include ESLint's message about the path of the config file containing the error.
No
> Upgrade: js-yaml to 3.9.1 (refs #9011)

- docs/rules/sort-keys.md
Documentation update
Added definition for natural ordering in sort-keys document.
> Docs: Updated the sort-keys doc to add definition for natural ordering

- conf/category-list.json
- docs/user-guide/rule-deprecation.md
This updates the deprecation policy in accordance with the TSC decision from https://github.com/eslint/eslint/issues/8635.
> Docs: update rule deprecation policy (fixes #8635)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
> Fix: no-extra-parens incorrectly reports async function expressions

- docs/rules/indent.md
Updated the example for the MemberExpression option of the indent rule
to not include the comment and code about permitting any indentation in
variable declarations and assignments.
**Is there …
> Docs: Update example for MemberExpression option of indent (fixes #9056)

- docs/rules/strict.md
I clarified that setting `"globalReturn"` to false will override the behavior expected in a `node` environment.
That the behavior is …
> Docs: clarified behavior of globalReturn option (fixes #8953)

- docs/rules/object-shorthand.md
Added a closing quotation mark to the option definition on line 92.
No.
> Fix: Update object-shorthand.md to fix typo.

- package.json
> Upgrade: Espree to 3.5.0

- docs/developer-guide/working-with-plugins.md
This fixes a typo in the documentation for processors.
No
> Docs: add missing word in processor documentation

- docs/rules/quotes.md
Docs about when new lines are an auto-exclusion or not.
As per this commenter: https://github.com/eslint/eslint/issues/9069#issuecomment-323801846 …
> Docs: quotes rule - when does \n require backticks

- lib/rules/padded-blocks.js
- lib/rules/prefer-arrow-callback.js
> Chore: remove unused assignment.

- docs/rules/prefer-arrow-callback.md
Fix a currently unrendered link.
No.
> Docs: fix link format in prefer-arrow-callback.md

- Makefile.js
[x] Other, please explain: Fixing build script for documentation
> Build: Fixing issue with docs generation (Fixes #9199)

- docs/developer-guide/working-with-rules.md
This updates the rule documentation to add some missing information and details.
> Docs: improve documentation for rule contexts

- docs/rules/id-length.md
> Docs: fix wrong config in id-length example.

- docs/rules/no-restricted-globals.md
> Docs: fix wrong config in no-restricted-globals example.

- package.json
Upgraded Espree to v3.5.1 to fix #9153 
Nope.
> Upgrade: Espree v3.5.1 (fixes #9153)

- lib/util/apply-disable-directives.js
- tests/lib/linter.js
- tests/lib/util/apply-disable-directives.js
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
Fixed a bug where nested eslint disable directive created some issues. Please refer to the linked issue for examples.
* Not very clean (I …
> Fix: Handle nested disable directive correctly (fixes #9318)

- Makefile.js
This updates the `npm run lint` task to check for unused `eslint-disable` directives.
> Chore: report unused eslint-disable directives in ESLint codebase

- docs/user-guide/getting-started.md
> Docs: add installing prerequisites.

- README.md
> Docs: add installing prerequisites in readme.

- docs/rules/block-spacing.md
- lib/rules/block-spacing.js
Change the block spacing doc to explain that it's not specific to single line blocks.
> Docs: update block spacing details (fixes #8743)

- README.md
Welcome, @Aladdin-ADD & @VictorHom!
> Chore: Add Aladdin-ADD & VictorHom to README

- docs/developer-guide/development-environment.md
Amended forecast of time tests will take from a few seconds to 2 minutes, to reflect reality.
> Docs: Correct time forecast for tests.

- docs/developer-guide/code-conventions.md
> Docs: Corrected noun to verb.

- docs/rules/multiline-comment-style.md
This updates the multiline-comment-style docs to use separate code blocks for the separate options, to make the differences between the options clearer. …
> Docs: improve examples for multiline-comment-style

- docs/developer-guide/contributing/pull-requests.md
This updates one of the "good commit message" examples to ensure that it is not longer than 72 characters.
> Docs: ensure "good commit message" examples actually follow guidelines

- docs/user-guide/README.md
Added 3 migration links. Correct links requiring “.md” by adding that. Without that extension, I found those links producing a 404-status response. …
> Docs: Repair broken links and add migration links.

- README.md
Added an FAQ for the most common install/runtime problem we have :smile:
Note: I'm trying to keep this a high-level answer rather than going into a lot of detail. …
> Docs: Add FAQ for when ESLint cannot find plugin

- docs/user-guide/configuring.md
Clears confusion on usage of global and local plugins.
> Docs: Clears confusion on usage of global and local plugins.

- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
fixes #9461 
is there other edge case?
> Fix: multiline-comment-style fix produces invalid code (fixes #9461).

- .github/ISSUE_TEMPLATE.md
> Docs: Update ISSUE_TEMPLATE.md

- tests/lib/rules/object-property-newline.js
Add tests to an existing rule.
Added tests to improve coverage and relocated 2 existing tests into the appropriate section.
This PR implements step 2 of my plan to handle issue 6251 (refs #6251). …
> Chore: Add tests to cover array and object values and leading commas.

- docs/rules/no-restricted-modules.md
Changes an existing rule
the change i propose is basically rewriting the no-restricted-rule documentation for better readability and understandability and explained some basic use cases for the rule
> Fix:improve the doc for no-restricted-rule(fixes #9437)

- docs/rules/no-invalid-this.md
> Docs: Minor rephrase in `no-invalid-this`.

- .travis.yml
Node 9 was released today. This adds it to Travis.
> Build: test Node 9 on Travis

- package.json
refs #9444
upgrade `ajv@5.3.0`, which replaced `json-stable-stringify` with `json-stable-stringify-without-jsonify`
> Chore: upgrade ajv@5.3.0

- docs/rules/no-underscore-dangle.md
> Fix doc for no-underscore-dangle rule

- docs/rules/valid-typeof.md
> Docs: fix spelling in valid-typeof example

- packages/eslint-config-eslint/README.md
I updated the readme of `eslint-config-eslint` to clarify the wording. I think we should avoid using the word "default" in that context, to avoid any potential confusion about whether `eslint-config-eslint` sets any defaults for ESLint itself.
> Docs: clarify what eslint-config-eslint is

- docs/developer-guide/contributing/pull-requests.md
Rephrased the definition of the Update tag to eliminate its ambiguity.
> Docs: Disambiguate definition of Update tag

- docs/rules/lines-between-class-members.md
> Docs : Fixed a typo on lines-between-class-members doc

- package.json
Bumping the minimum viable version of Espree to v3.5.2 to ensure that the changes in today's release are in the upcoming ESLint release.
Changed the package.json. …
> Upgrade: espree v3.5.2

- README.md
> Docs: Add @platinumazure to TSC

- docs/user-guide/migrating-from-jscs.md
The multiline comment string doesn't seem to work.
Main docs page is right; JSCS migration guide appears to be wrong.
> Updating migration guide for single-line disable

- package.json
[x] Other, please explain: Upgrade doctrine dependency to take advantage of latest bugfixes in Doctrine project
Upgraded Doctrine to ^2.0.2
Not really
> Upgrade: doctrine@^2.0.2

- docs/rules/no-return-await.md
Clarifies with an example that `return await` inside an error handler is allowed by this rule.
The rule correctly implements this, but the docs didn't reflect that. …
> Docs: Adds an example with try/catch.

- README.md
Added a period to the end of one sentence.
No.
> Docs: Add missing period to the README

- tests/lib/cli-engine.js
[x] Other, please explain: Typo fix
Fixed typo in CLIEngine test name. toatl -> total
N/A
> Chore: Fix typo in CLIEngine test name

- docs/user-guide/command-line-interface.md
- lib/options.js
[x] Other, please explain: Changing CLI help message by reorganizing a few CLI options and updating associated docs, see below for more details.
* Moved "Caching" section down to bring up some more important options
* Created …
> Chore: Reorganize CLI options and associated docs

- docs/developer-guide/working-with-rules.md
* Added note about documentation file associated with every rule (in addition to implementation and test)
* Added example and explanation of `meta.docs.url` property …
> Docs: Minor tweaks to working with rules page

- docs/user-guide/configuring.md
Added ES 2018 to the list of available versions, since Espree supports it.
Nothing in particular!
> Docs: Add ES 2018 to Configuring ESLint

- docs/user-guide/configuring.md
Added CLIEngine to the documentation under [Configuration Cascading and Hierarchy](https://github.com/PiIsFour/eslint/blob/issue9526/docs/user-guide/configuring.md#configuration-cascading-and-hierarch …
> Docs: Update documentation about configuration hierarchy for CLIEngine options (fixes #9526)

- docs/rules/prefer-destructuring.md
add example with a reassignment.
[X] Other, please explain: add code example.
> Docs: Add prefer-destructuring variable reassignment example

- docs/rules/prefer-destructuring.md
Fix a typo added in https://github.com/eslint/eslint/commit/3afaff6039f4c5b3a8421b2746fb7bfa5d13ae9b
No.
> Docs: fix typo in prefer-destructuring.md example

- docs/rules/no-restricted-modules.md
In the documentation for the `no-restricted-modules` rule, I fixed typos in two references to `lodash`, and I added an extra space before each of those references. …
> Docs: Fix lodash typos, make spacing consistent

- docs/rules/no-loop-func.md
Add incorrect examples where the function within the loop refers to a variable from the outer scope that is later modified. (This contrasts with the last correct example.) …
> Docs: Add modified variable examples for no-loop-func (fixes #9527)

- Makefile.js
This updates the prerelease build to also push changes to `eslint.org` and push a release to GitHub.
Is there a reason it wasn't doing this before?
> Build: make prerelease script publish to GitHub/website

- Makefile.js
[x] Other, please explain: Fix gensite script when creating a new major version sequence.
Together with @not-an-aardvark, added two checks to create missing directories when starting a new major version release sequence.
**Is …
> Build: Gensite creates prerelease dirs if needed

- package.json
This upgrades the `eslint-release` package to `v0.11.1`.
> Upgrade: eslint-release to v0.11.1

- docs/rules/no-self-assign.md
Added Missing Quotes To Match With The Style In Other Files
> Add Missing Quotes

- README.md
I reordered the sections in the README so that it makes more sense, IMO. I moved all user related info to the top and put contributor related next. …
> Docs: Reorder README sections

- lib/cli.js
[x] Other, please explain: Adding debug information for how `process.argv` looks to ESLint
Added debug information in lib/cli.js for how arguments are passed in to the CLI (which comes from `process.argv` when called by …
> Chore: Add debug logging for CLI args as they came in

- package.json
Upgrade babelify
Upgrade babelify. I didn't include this in the previous PR because it was failing. Turned out it was because babel-core was missing (it is a peerDependency). Adding it fixed the …
> Upgrade: babelify

- docs/developer-guide/shareable-configs.md
- docs/developer-guide/working-with-rules.md
- docs/rules/max-statements-per-line.md
> Docs: fix some small errors in examples

- docs/rules/operator-linebreak.md
> Docs: fix code in operator-linebreak example.

- docs/rules/id-length.md
```js
({ prop: obj.x }) = {};  // Parsing error: Parenthesized pattern
```
> Docs: fix wrong config in id-length

- package.json
Upgrade some deps.
Upgrade major versions of cross-spawn and inquirer.
No.
> Upgrade: upgrade deps

- docs/user-guide/migrating-to-5.0.0.md
This adds a note about the changes to globals and `context._linter`.
Is there anything that could be clearer?
> Docs: update migration guide with latest changes

- CHANGELOG.md
Fixed a misspelling in the changelog.
Not really.
> Docs: Fix misspelling in changelog

- README.md
I reframed the style question in terms of Prettier, which is very popular and the source of a lot of confusion with ESLint.
No.
> Docs: Add Prettier to FAQ

- README.md
Update JSCS section in FAQ.
No.
> Docs: Update JSCS FAQ

- lib/util/module-resolver.js
small opt to improve readability
no~
> Chore: small opt to improve readability

- docs/developer-guide/contributing/new-rules.md
This wording would help me find the actual template before proposing new rule.
PR migrated from …
> Docs: make template links wording more clearer

- package.json
[X] Bug fix: fixes #10245.
This PR upgrades `eslint-scope` package to remove TDZ scopes.
This depends on `github:eslint/eslint-scope#remove-tdz-scope` in order to check no test failing. 
> Breaking: remove TDZ scopes (fixes #10245)

- docs/developer-guide/working-with-custom-formatters.md
Not familiar with the JSON formatter portion so didn't touch it
https://github.com/eslint/eslint/issues/9950
- Added fixableWarningCount and fixableErrorCount to results objects
- Removed redundant …
> Docs: Addressed first three issues (refs #9550)

- package.json
`mock-fs@4.5` adds support for Node 10.  See tschaub/mock-fs#237 for the Node 10-specific change.  See [the changelog](https://github.com/tschaub/mock-fs/blob/master/changelog.md#450) for the full list of changes since 4.4.
This should allow Node 10 to be added to the build (see #10262).
> Chore: upgrade mock-fs@4.5.0

- tests/lib/linter.js
This updates a test that was previously skipped due to https://github.com/eslint/eslint/issues/10245. Since that issue is solved, this test can be unskipped.
> Chore: unskip test for scope analysis

- docs/user-guide/integrations.md
Update a link.
Not really, it's just an updated link.
> Docs: Update link to Integrations / Build tools / Start

- docs/rules/max-classes-per-file.md
Refs:
https://github.com/eslint/eslint/pull/10163/files/02861d1c2d34ba9f36a84afc85b856e54da75467#r187752752
https://github.com/eslint/eslint/pull/10163/files/02861d1c2d34ba9f36a84afc85b856e54da75467#r187752791
> Docs: polish for max-classes-per-file rule

- lib/config/config-initializer.js
[x] Other, please explain: rm unused argument
the function defined in https://github.com/eslint/eslint/blob/8b7a70cd7d91fe4d00fed6dd6f69285368aef45a/lib/config/config-initializer.js#L289 , superfluous argument passed to …
> Chore: rm unused argument

- .travis.yml
- tests/lib/testers/no-test-runners.js
> Build: add Node v10 to travis

- README.md
Temporaryly removed the badge, since it has being disabled for a long time. 
sorry for not following the template. :(
> Docs: remove test coverage badge

- package.json
[x] Other, please explain: Upgrade to latest (alpha) espree
Upgraded espree to latest alpha.
Not really.
> Upgrade: Consume espree@4.0.0-alpha.1

- lib/rules/no-debugger.js
- tests/lib/rules/no-debugger.js
fixes #10242 
need to update docs for this change?
> Update: rm rule no-debugger autofix (fixes #10242)

- lib/rules/no-debugger.js
- tests/lib/rules/no-debugger.js
This reverts commit a6df7e6ba4989b547baad9335a142c8731f6a96d.
my apologies! I should have observed a waiting period before merging the request.
> Revert: "Update: rm rule no-debugger autofix (fixes #10242) (#10425)"

- README.md
display team members in a table, added avatars 😄 
~~The col width is not perfectly equal, so it looks a little strange.~~
~~please feel free to close if you don't like it. ❤️~~
fixed! see the above screenshot~~
> Docs: display team members in a table

- README.md
styling to be same with others. see #10433
> Docs: styling team members

- lib/rules/no-unneeded-ternary.js
- tests/lib/rules/no-unneeded-ternary.js
> Fix: add parens for yield statement (fixes #10432)

- docs/rules/no-catch-shadow.md
- lib/rules/no-catch-shadow.js
[X] Changes an existing rule: fixes #10466 
This PR deprecate the `no-catch-shadow` rule.
> Update: deprecate no-catch-shdow (fixes #10466)

- docs/developer-guide/README.md
> Docs: add missing paragraph about "custom parsers"

- docs/user-guide/configuring.md
I have added a new block explaining that is possible disable some rules only for certain files.
- Verify if the example, phrases, sentences; …
> Docs:  adding a section about disable rules for some files

- package.json
upgrade globals@11.7.0, added bigint.
no~
> Upgrade: globals@11.7.0

- docs/rules/no-irregular-whitespace.md
Provide an actionable insight on how to fix `no-irregular-whitespace` rule
The documentation change.
> no-irregular-whitespace: make it explicit that rewriting the line is a sufficient fix

- README.md
This updates the readme to let people know that they can use release issues to find information about release scheduling.
> Docs: add note about release issues to readme

- lib/config/config-validator.js
small refactor config-validator.js
a simple micro bench: http://jsben.ch/jX6IZ
> Chore: small refactor config-validator.js

- lib/rules/wrap-regex.js
- tests/lib/rules/wrap-regex.js
> Fix: wrap-regex doesn't work in some expression(fixes #10573)

- tests/lib/linter.js
[x] Other, please explain: Refactored a helper method in test/lib/linter.js.
Refactored a helper method in test/lib/linter.js to use `Array.prototype.find` in order to simplify the logic. …
> Chore: Simplify helper method in Linter tests

- Makefile.js
[x] Other, please explain: Fixing prerelease logic in blog post generation (see #10578)
Ensure a prerelease-related variable is always set prior to rendering the blog post template. …
> Build: Fix prerelease logic in blog post generation (fixes #10578)

- Makefile.js
fixes #10577 
not sure why got this error, but it did fix the issue.
> Build: fix npm run perf failing(fixes #10577)

- package.json
Bumped `ignore` to 4.0.2 for deduplication with `eslint-plugin-node`. No breaking changes except that Node.js 6 is now the minimum version.
Changelog: https://github.com/kaelzhang/node-ignore/blob/fe682e8f6f78946663855025d74c49518d564f16/CHANGELOG.md …
> Upgrade: ignore@4.0.2

- docs/rules/no-unsafe-negation.md
Removed superfluous empty `Options` section.
> Remove superfluous section from no-unsafe-negation

- docs/rules/dot-location.md
> Docs: Make marking a default option consistent with other rules

- docs/rules/no-prototype-builtins.md
it's a bit misleading -- some methods are allowed like `toString()`.
no
> Docs: fix misleading no-prototype-builtins description

- conf/eslint-recommended.js
- docs/rules/no-async-promise-executor.md
- lib/rules/no-async-promise-executor.js
- packages/eslint-config-eslint/default.yml
- tests/lib/rules/no-async-promise-executor.js
[x] New rule (https://github.com/eslint/eslint/issues/10217)
This implements the `no-async-promise-executor` rule, as described in https://github.com/eslint/eslint/issues/10217.
> New: add no-async-promise-executor rule (fixes #10217)

- docs/user-guide/configuring.md
it add the visibility of the useful configuring-rules
> Docs: add subheader in configuring/configuring-rules

- docs/rules/no-else-return.md
The other rules don't have this sample code block, so this PR makes the `no-else-return` documentation consistent with the others.
> Docs: Remove superfluous object option sample code

- lib/rules/require-atomic-updates.js
[x] Other, please explain: Fixes a require path that was incorrect after another PR was merged in (fixes master build)
Changed a require path which became incorrect after merging #10680. …
> Chore: Update require path for ast-utils

- conf/eslint-recommended.js
- docs/rules/require-unicode-regexp.md
- lib/rules/require-unicode-regexp.js
- tests/lib/rules/require-unicode-regexp.js
[X] New rule: fixes #9961.
This PR adds `require-unicode-regex` rule.
> New: require-unicode-regexp rule (fixes #9961)

- package.json
I'm not seeing it being used in the codebase, am I missing something?
> Chore: rm unused dep string.prototype.matchall

- docs/rules/no-useless-concat.md
Fix comment placement in a code example
No.
> Docs: fix comment placement in a code example

- docs/user-guide/integrations.md
* Add Brackets integration to Docs
* Unify format of Editor integrations
No
> Docs: Add Brackets Integration

- templates/bug-report.md
Copied the wrapper markdown from https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE.md.
> Chore: Add configuration wrapper markdown for the bug report template

- lib/util/source-code-fixer.js
Fixes the debug log's name to match the filename for SourceCodeFixer.
Changed debug log name.
Nope. This is just a bit of housekeeping to …
> Chore: Update debug log name to match filename

- docs/rules/complexity.md
> Docs: Update complexity.md

- docs/rules/quotes.md
`allowTemplateLiterals: false` is confusing, as users will expect it to prevent any usage of template literals. A note explaining that it does not do this has been added, along with a link to where to go for more information if that is their goal.
The note explains that it doesn't do what user's would expect, but does not explain why. That context may be useful.
> Docs: Update quotes.md

- package.json
fixes #10854 
debug@4 drop node v4(should not break eslint)
> Upgrade: debug@4 (fixes #10854)

- package.json
Bumping `table` to its newest version. The breaking change is that version 5 requires Node.js 6.
Biggest advantage is that it loses a couple of dependencies, notably `ajv-keywords` - that disaster can't happen again 😆  …
> Upgrade: table to version 5

- tests/lib/rules/space-infix-ops.js
Added some test cases with more interesting ASTs.
`((a)) + ((b))` and `(((a))) + (((b)))` are especially interesting, because this is the only …
> Chore: Add more test cases to space-infix-ops

- docs/developer-guide/README.md
The file seems to have been renamed so updating the link to point to the new file.
> Docs: Update working-with-parsers link

- docs/maintainer-guide/governance.md
Mention adding new TSC members to the ESLint TSC mailing list.
Added a step to "Adding a TSC member" portion of the governance doc.
Nothing in …
> Docs: Update steps for adding new TSC member

- docs/user-guide/configuring.md
It seems [this is already used in the codebase](https://github.com/eslint/eslint/search?l=JavaScript&q=2019) and is needed for parsing new features like [optional catch binding](https://github.com/tc39/proposal-optional-catch-binding).
No.
> Docs: update ecmaVersion to include 2019/10 values

- lib/util/source-code.js
> typo: srevices => service

- .github/ISSUE_TEMPLATE/NEW_RULE.md
currently github is report:
seems it was unexpectedly introduced in https://github.com/eslint/eslint/commit/2e52bca9e5aa24eb22d6f01afcefa819655ded78 …
> Docs: fix typo in issue-templates/new-rule

- package.json
Upgrading to Espree v5.0.0 (which removes comment attachment).
Upgrade espree from `^4.0.0` to `^5.0.0`.
> Upgrade: Espree v5.0.0

- messages/all-files-ignored.txt
[x] Other, please explain: Update error message text.
Edited `messages/all-files-ignored.txt` to make the problem more obvious to the user.
No.
> Update all-files-ignored error message to point out the problem to the user 

- lib/rules/no-irregular-whitespace.js
I updated the description to be correct (irregular whitespace is forbidden in comments by default) and match nearby rules in the rule list which didn’t elaborate.
Should I add back “outside of strings?”
> Docs: Fix no-irregular-whitespace description

- docs/rules/no-unused-expressions.md
Fixes #11169 
I just added a simple note, and I'm not sure whether it's enough or not.
> Docs: add a note for no-unused-expressions (fixes #11169)

- README.md
Fixed typo in peer depencency checking snippet `npm view ... peerDependencies` 
> Docs: fixes typo peerDepencies

- README.md
This PR adds @g-plane as a committer (🎉).  I also changed the tables to match what we have on https://eslint.org/team/, to make it clearer who community members should be reaching out to. 
**Is there …
> Docs: add @g-plane as committer

- docs/maintainer-guide/governance.md
Added a bullet point highlighting that we should get confirmation from a new committer before adding them to the team.
> Docs: clarify process for adding committers

- docs/rules/no-async-promise-executor.md
Renamed `result` to `foo` as the `const` below both of those are also called `result`.
N/A
> Rename `result` -> `foo`

- tests/lib/rules/camelcase.js
Increase test coverage
Increase test coverage in lib/rules/camelcase.js by writing test cases that hit missing branches/statements
Coverage …
> Chore: increase camelcase test coverage

- docs/rules/comma-spacing.md
Docs: Fix grammar: Spacing improve -> Spacing improves
Changed
“Spacing around commas improve readability of a list of items.”
to
“Spacing around commas improves readability of a list of items.”
**Is …
> Fix grammar: Spacing improve -> Spacing improves

- docs/rules/no-shadow-restricted-names.md
Changed
“For example, there’s nothing prevent you from writing:”
to
“For example, there’s nothing preventing you from writing:”
No.
> Fix grammar in “there’s nothing prevent you”

- docs/rules/object-curly-spacing.md
Changed “This rule enforce” to “This rule enforces”
No.
> Docs: fix grammar in “This rule enforce”

- package.json
Upgrade Espree to the latest release
No
> Upgrade: espree@5.0.1

- docs/maintainer-guide/governance.md
Added description for non-attending TSC members
Do the changes make sense?
> Docs: Add non-attending TSC member info

- package.json
- tools/update-readme.js
this is following https://github.com/eslint/eslint/pull/11453.
no.
> Chore: remove devDependency common-tags

- package.json
This updates `eslint-scope` to `^4.0.2`.
> Upgrade: eslint-scope@4.0.2

- docs/developer-guide/nodejs-api.md
Added `visualstudio` as a formatter option
> Docs: Add `visualstudio` as a formatter

- Makefile.js
[x] Other
Copy the bundled espree, which we forgot.
Nope.
> Build: copy bundled espree to website directory

- packages/eslint-config-eslint/default.yml
IMHO, this should be enabled by default.
> Chore: eslint-config-eslint enable comma-dangle functions: "never"

- .travis.yml
- makes builds go faster
- removes deprecated option
explained above
speedy builds with caching :D
> Build: update CI testing configuration

- package.json
This upgrades `eslint-scope` to v4.0.3.
> Upgrade: eslint-scope@4.0.3

- tests/lib/formatters/table.js
[X] Other, please explain
<details>
<summary>If standalone mocha command ran <code>tests/lib/formatters/table.js</code>, coloring caused to fail the tests.</summary>
```
$ mocha tests/lib/formatters/table
formatter:table
when passed no messages
1) should return a table of error and warning count with no messages
when passed a single message
2) should return a string in the correct format for errors
3) should return a string in the correct format for warnings
when passed a fatal error message
4) should return a string in the correct format
when passed multiple messages
5) should return a string with multiple entries
when passed multiple files with 1 message each
6) …
```
> Chore: fix formatters/table test

- package.json
- Version bumped the `js-yaml` dependency to fix https://www.npmjs.com/advisories/788. 
Please check whether everything still works as expected …
> Bump js-yaml to fix Denial of Servic vulnerability

- package.json
[x] Other, please explain: Dev dependency upgrade
Upgrade to `karma@^4.0.1`. This fixes some npm-reported security vulnerabilities.
This version of Karma drops support …
> Upgrade: karma@^4.0.1, drops Node 6 support, fixes vulnerability

- docs/rules/comma-dangle.md
- lib/rules/comma-dangle.js
- packages/eslint-config-eslint/default.yml
- tests/lib/rules/comma-dangle.js
> Breaking: comma-dangle enable functions: "never" (fixes #11502)

- README.md
Edited the FAQ about JSCS to reflect ESLint's belief that we are nearly 100% compatible with JSCS and no longer need the project.
See https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019 …
> Docs: README updates to reflect JSCS compat project is finished

- package.json
[x] Other, please explain: update js-yaml vendor version in package.json
I updated js-yaml package version because In the old version there was a vulnerability:  
https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129
> Upgrade: update js-yaml package to 3.13.1 version

- lib/rules/no-var.js
- tests/fixtures/parsers/typescript-parsers/declare-var.js
- tests/lib/rules/no-var.js
fixes #11441 
the issue is related to typescript.
should this be a bugfix, or enhancement?
> Fix: no-var fixed to incorrect code (fixes #11441)

- docs/user-guide/migrating-to-6.0.0.md
This adds a migration guide for v6.0.0.
Note: This is a WIP. There are still 5 changes I need to add:
* https://github.com/eslint/eslint/issues/11510
* https://github.com/eslint/eslint/issues/11423
* https://github.com/eslint/eslint/issues/9505
* https://github.com/eslint/eslint/projects/5#card-17208589
* https://github.com/eslint/eslint/issues/11473
Aside from those, are there any changes I forgot to mention?
> Docs: add v6.0.0 migration guide

- docs/rules/no-caller.md
Fixes slight grammar mistake on the no-caller docs.
N/A
> docs: fix grammar
