- docs/src/_includes/components/logo.html
Fixes a stylelint lint error.
https://github.com/eslint/eslint/pull/16465 enabled `alpha-value-notation` stylelint rule and fixed errors in `.scss` files. But after merging both https://github.com/eslint/eslint/pull/16465 and https://github.com/eslint/eslint/pull/16468 (which enables linting css in HTML) at the same time, we …
> docs: fix stylelint error

- docs/.stylelintrc.json
- docs/src/assets/scss/components/theme-switcher.scss
- docs/src/assets/scss/utilities.scss
Enabled the rule and manually cleaned up the duplicate `font-size: inherit` since the `font: inherit` is shadowing this
> docs: Stylelint declaration-block-no-shorthand-property-overrides

- docs/.stylelintrc.json
- docs/src/assets/scss/components/resources.scss
Enabled the rule and removed the one instance of `block-inline-start: 0;` which I couldn't find any documentation on. Possibly was supposed to be `margin-inline-start` or `padding-inline-start`
> docs: Stylelint property-no-unknown

- docs/src/_data/further_reading_links.json
- docs/src/rules/no-empty-static-block.md
- lib/rules/index.js
- lib/rules/no-empty-static-block.js
- tests/lib/rules/no-empty-static-block.js
- tools/rule-types.json
**If #16318 is accepted, I'll make this PR ready for review.**
[x] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
Fixes #16318 
Adds new rule `no-empty-static-block`
> feat: Add new rule `no-empty-static-block`

- docs/src/rules/no-new-native-nonconstructor.md
The [`no-new-native-nonconstructor` docs](https://eslint.org/docs/latest/rules/no-new-native-nonconstructor) currently have formatting issues because of a missing ending code fence that this PR fixes.
> docs: Add missing no-new-native-nonconstructor docs code fence

- docs/src/user-guide/getting-started.md
init config about specifying shared configs
ref https://github.com/eslint/create-config/pull/38
> docs: init config about specifying shared configs

- docs/src/rules/no-implicit-coercion.md
- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
Fixes #16373
A minimal change in `no-implicit-coercion` behavior to allow special case described in #16373:
> I'd like a special case/exception made to the rule's checks that if the * 1 is immediately followed by a / then it is not an error.
> fix: allow `* 1` when followed by `/` in no-implicit-coercion

- docs/src/_includes/components/rule.macro.html
Use the ❌ emoji to symbolize deprecated rules. This is the emoji-version of the former SVG. Emojis are preferred as they can be selected/copy-pasted, and are more consistent with the other fixable/recommended/suggestions emojis used in the [rules](https://eslint.org/docs/latest/rules/) list/index/table.
This emoji also matches the emoji for "deprecated rule" used by many top plugins ([example](https://github.com/jest-community/eslint-plugin-jest#rules)), and it's the same emoji used by [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) which I wrote.
> Use emoji instead of svg for deprecated rule symbol

- tests/fixtures/dots-in-files/a..b.js
- tests/fixtures/dots-in-files/eslint.config.js
- tests/lib/eslint/flat-eslint.js
Added a test
This test just verifies that we can have `files` pattern that include two dots in a row like "a..b.js" when using flat config.
Closes #16038
Nope.
> chore: Add tests to verify #16038 is fixed

- docs/src/_data/languages.json
In the language page https://eslint.org/docs/latest/languages.html the link that is rendering the users to the japanese translation page of ESlint, is not working.
So as a fix i did change the language code from **jp** to **ja** in data.
> docs: fix route of japanese translation site

- docs/src/rules/no-obj-calls.md
- lib/rules/no-obj-calls.js
- tests/lib/rules/no-obj-calls.js
Fixes #16393
`no-obj-call` supports `Intl` objects.
Implementation is simple, so please focus tests and docs.
> feat: `no-obj-calls` support `Intl`

- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
Fixes #16490
* Changed the logic in rule `key-spacing` to ensure that properties whose value starts on a new line are not grouped with any previously defined properties.
* Moved around function `isKeyValueProperty` in key-spacing.js to comply with lint settings.
* Added unit tests to rule `key-spacing`.
* Extended some existing …
> feat: do not group properties in `key-spacing` if value starts on a new line

- lib/eslint/eslint-helpers.js
- tests/lib/eslint/flat-eslint.js
Addresses https://github.com/eslint/eslint/pull/16462#pullrequestreview-1168561292.
When there are multiple unmatched patterns, both ESLint and FlatESLint throw an error containing information about only one pattern. The error can be either that the pattern doesn't match any files or that it matches only ignored files.
The …
> fix: throw error for first unmatched pattern

- docs/src/assets/js/main.js
- docs/src/assets/scss/components/toc.scss
Closes https://github.com/eslint/eslint/issues/16312
1. Make the table of contents sticky on desktop:
2. Highlight respective menu item in table of contents (light blue area is for demonstration only, not included in code):
> docs: make toc sticky on desktop

- lib/eslint/eslint-helpers.js
- tests/fixtures/dot-files/.a.js
- tests/fixtures/dot-files/.c.js
- tests/fixtures/dot-files/b.js
- tests/fixtures/dot-files/eslint.config.js
- tests/lib/eslint/flat-eslint.js
Previously, glob patterns didn't match dot files and couldn't be changed while we were using globby for flat config. Because we moved to our own glob search, we can now include dot files in our searches automatically.
Note that `ConfigArray` was [already matching](https://github.com/humanwhocodes/config-array/blob/main/src/config …
> fix: Ensure that dot files are found with globs.

- docs/src/rules/no-magic-numbers.md
- lib/rules/no-magic-numbers.js
- tests/lib/rules/no-magic-numbers.js
Fixes #16228
Added new option `ignoreClassFieldInitialValues` to the `no-magic-numbers` rule.
> feat: add `ignoreClassFieldInitialValues` option to no-magic-numbers

- docs/src/user-guide/configuring/rules.md
Add short introduction to the Configuring Rules page and minor content tweaks throughout the page.
Part of https://github.com/eslint/eslint/issues/16473
> docs: Add Rules page intro and content tweaks

- docs/src/user-guide/command-line-interface.md
Changes to Command Line Interface page:
- add introduction 
- small copy edits throughout page
Part of https://github.com/eslint/eslint/issues/16473
> docs: Command Line Interface intro and tweaks

- docs/src/developer-guide/selectors.md
This is a follow-up to https://github.com/eslint/eslint/pull/14675#discussion_r650371457.
Updates https://eslint.org/docs/latest/developer-guide/selectors#known-issues section.
The current version is a bit confusing because `[value=/some\/path/]` contains an unescaped backslash character while the suggested workaround …
> docs: clarify esquery issue workaround

- docs/.eleventy.js
- docs/src/_includes/components/rule-categories.macro.html
- docs/src/_includes/components/rule.macro.html
Switch from the 🛠 (hammer and wrench) to 🔧 (wrench) emoji to represent auto-fixable rules.
Why?
- The wrench could be considered simpler, "less busy", and a "more straightforward" emoji to indicate the desired meaning
- I used [eslint-ecosystem-analyzer](https://github.com/bmish/eslint-ecosystem-analyzer) to count usages of each emoji across the top 1,000 ESLint plugins, and found the wrench to be vastly more popular:
| Emoji | Number of Files in Top 1,000 ESLint Plugins | 
| --- | --- | 
| 🔧 | 607 |
| 🛠 | 15 | 
As a result of the greater popularity of the wrench emoji, I have also adopted it in [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) which is used in the top 15+ ESLint plugins ([example output](https://github.com/jest-community/eslint-plugin-jest#rules)). …
> docs: switch to wrench emoji for auto-fixable rules

- docs/src/user-guide/configuring/ignoring-code.md
Add introduction and copy edits to Ignoring Files page
Partial fix of #16473
> docs: add intro and edit ignoring files page

- docs/src/user-guide/configuring/language-options.md
Add introduction to Language Options page with additional copy/formatting tweaks throughout page.
Partial fix to #16473
> docs: Language Options page intro and tweaks

- Makefile.js
Recently published version of [marked](https://www.npmjs.com/package/marked) parses frontmatter as a header. That breaks our rule doc headers check (see https://github.com/eslint/eslint/pull/16563).
Updated `Makefile.js` to pass doc text without frontmatter to `marked`.
> chore: fix rule doc headers check

- docs/src/user-guide/configuring/configuration-files-new.md
- docs/src/user-guide/configuring/configuration-files.md
Clean up page copy and add small introductions on pages [Configuration Files](https://eslint.org/docs/latest/user-guide/configuring/configuration-files) and[ Configuration Files (New)](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new)
Notes: 
- Updated many verbs to be present tense from future …
> docs: Update configuration file pages

- docs/src/assets/js/search.js
Fixed search bar clear icon flickering and disappearance issue
Fixed #16584 
https://user-images.githubusercontent.com/42532987/204045234-0cc21b88-d866-48e2-b5b6-a3d8733777b1.mp4
> docs: fix searchbar clear button

- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
Fixes #16573
Previously, the no-invalid-regexp rule skipped flag validation for regexps with non-literal pattern.
This PR fixes the rule so that flags are validated no matter what the pattern is.
The schema could be updated, adding a separate messageId for invalid flags, but I didn't do so - to stay focused and not to break …
> fix: In no-invalid-regexp, validate flags also for non-literal patterns

- docs/src/assets/js/search.js
Debounced the search results to reduce the number of API calls
https://user-images.githubusercontent.com/42532987/204058551-4cd22983-34b1-4628-9132-4b0ae81494c1.mp4
https://user-images.githubusercontent.com/42532987/204058560-ec2a2b9c-6683-4f92-a1b8-0639984d7b59.mp4
> docs: perf debounce the search query

- lib/rules/prefer-named-capture-group.js
- tests/lib/rules/prefer-named-capture-group.js
[x] Add autofix to a rule
Fixes #16530
Adds `meta.hasSuggestions` to `prefer-named-capture-group` for two suggestions:
* Changing a capture group to named: e.g. `(?<temp1>a)`
* Changing a capture group to non-named: e.g. `(?:a)`
I don't work with named capture groups much in regular expressions, so I'm not highly confident there aren't edge cases I …
> feat: `prefer-named-capture-group` add suggestions

- docs/src/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
Resolve https://github.com/eslint/eslint/issues/16386
Examples of **correct** code:
```js
/* eslint no-extra-parens: ["error", "all", { "allowParensAfterCommentPattern": "@type" }] */
const span = /**@type {HTMLSpanElement}*/(event.currentTarget);
if (/** @type {Foo | Bar} */(options).baz) console.log('Lint free');
foo(/** @type …
```
> feat: add `allowParensAfterCommentPattern` option to no-extra-parens

- .github/CODEOWNERS
> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must be visible and it must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.
> docs: add docs codeowners

- docs/src/rules/camelcase.md
Refs https://github.com/eslint/eslint/issues/16604.
Documentation for the `camelcase` rule is missing an example where `properties: "never"` allows assignments to properties.
Added an example.
> docs: add a property assignment example for camelcase rule

- docs/src/developer-guide/working-with-plugins.md
- docs/src/user-guide/configuring/configuration-files.md
- docs/src/user-guide/configuring/index.md
- docs/src/user-guide/configuring/plugins.md
- renamed 'Configuring Plugins' page to 'Configuring Plugins & Parsers' b/c plugins separate from parsers
- note: didn't change page name b/c didn't want to break the existing URL path before we have redirects set up
- added intro section to page
- small copy edits throughout page
- move section order to make clear that …
> docs: Configuring Plugins page intro, page tweaks, and rename

- docs/src/user-guide/configuring/configuration-files.md
> docs: Fix anchor in URL

- docs/src/rules/no-unused-vars.md
Refs #16616
In `no-unused-vars` docs, [options](https://eslint.org/docs/latest/rules/no-unused-vars#options) are ordered as follows:
1. vars
1. varsIgnorePattern
1. args
1. ignoreRestSiblings
1. argsIgnorePattern
1. destructuredArrayIgnorePattern
1. caughtErrors
1. caughtErrorsIgnorePattern
This order looks confusing, especially …
> docs: reorder options in no-unused-vars

- lib/rules/no-var.js
- tests/lib/rules/no-var.js
Fixes #16610
In the `no-var` rule, I fixed the logic that checks whether a variable has a reference in TDZ to skip references in the variable initializer if the initializer is a function definition.
> fix: autofix recursive functions in no-var

- docs/.eleventy.js
- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- lib/rules/comma-dangle.js
- lib/rules/multiline-ternary.js
- lib/rules/no-else-return.js
- lib/rules/no-unneeded-ternary.js
- packages/eslint-config-eslint/default.yml
- tests/fixtures/rules/custom-rule.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/config/flat-config-array.js
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/linter/code-path-analysis/code-path.js
- tests/lib/linter/linter.js
- tests/lib/rules/no-unused-vars.js
- tests/lib/rules/prefer-const.js
- tests/lib/rules/utils/ast-utils.js
- tests/lib/shared/config-validator.js
- tests/lib/source-code/source-code.js
- tests/tools/eslint-fuzzer.js
- tools/fuzzer-runner.js
This is a test-only PR that helps prepare for:
* RFC: [RFC-85](https://github.com/eslint/rfcs/tree/main/designs/2021-schema-object-rules) (https://github.com/eslint/rfcs/pull/85)
* RFC implementation: https://github.com/eslint/eslint/pull/16614
This PR only touches tests (and minor change to rule tester). It updates HUNDREDS of …
> refactor: migrate off deprecated function-style rules in all tests

- docs/src/_data/links.json
- docs/src/user-guide/command-line-interface.md
- lib/options.js
Standardized the documentation for CLI commands.
Used the general format: 
````md
Short description of option 
* **Alias**: If applicable add short command alias (ex: `-mo`)
* **Argument Type**:  "No Argument." or argument data type and short description as necessary.
**Multiple Arguments**: "Yes"/"No". If argument type …
```
> docs: CLI documentation standardization

- package.json
Update [`globals`](https://github.com/sindresorhus/globals/compare/v13.15.0...v13.19.0) dependency to:
- https://github.com/sindresorhus/globals/pull/191
- https://github.com/sindresorhus/globals/pull/193
- https://github.com/sindresorhus/globals/pull/192
- https://github.com/sindresorhus/globals/pull/194
- …
> feat: update globals

- .npmrc
- package.json
On the recently released Node v19.3.0, we're getting a lot of errors related to loading `eslint-plugin-internal-rules`, which is in our package.json specified as `"eslint-plugin-internal-rules": "file:tools/internal-rules"`. Node v19.3.0 is the first version that includes npm v9, and the cause of the problem seems to be the new …
> ci: fix npm v9 problem with `file:`

- lib/rules/no-return-await.js
- tests/lib/rules/no-return-await.js
Add suggestion to `no-return-await`, see #16632 
I've added a suggestion for removing `await` before `return` to the rule `no-return-await` and adapted the tests for all failing cases to ensure that the correct suggestion is generated.
The change itself should be straight forward. I'm unsure if the `createErrorList` function I …
> feat: add suggestion for no-return-await

- lib/config/default-config.js
- package.json
- tests/lib/eslint/flat-eslint.js
We have several tests that were ignored back when we were waiting for fast-glob fixes. Because we no longer use fast-glob, the tests now work.
Test updates
There were several tests that we were ignoring for `FlatESLint` due to bugs in `fast-glob`. Now that we no longer use `fast-glob`, we can make these tests run.
I changed the …
> fix: Ensure flat config unignores work consistently like eslintrc

- Makefile.js
- eslint.config.js
- tests/lib/eslint/flat-eslint.js
After https://github.com/eslint/eslint/pull/16579, `docs/**` ignore pattern matches directory `docs/`, so `!docs/.eleventy.js` doesn't really unignore `docs/.eleventy.js` file because the file is in an ignored directory.
This is observable in our CI: https://github.com/eslint/eslint/actions/runs/3717239694/jobs/6304407905 …
> chore: update ignore patterns in `eslint.config.js`

- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
Fixes #16674
This PR fixes a bug introduced in a previous change in the `key-spacing` rule that would cause certain properties to be erroneously excluded from a group.
Specifically, a property having its value wrapped in parentheses was treated as not continuing the previous group if the value started on a different line than …
> feat: group properties with values in parentheses in `key-spacing`

- docs/src/_includes/layouts/base.html
- docs/src/assets/scss/tokens/typography.scss
Fixed missing country flags in the language selector on the docs page
|Before (windows) | After (windows) |
|----|----|
|![image](https://user-images.githubusercontent.com/42532987/209392592-539602f7-d832-4128-aa45-ccd9f0728bfe.png)|![image](https://user-images.githubusercontent.com/42532987/209392624-f9e54652-05c5-4fff-b8ee-2e90 …
> docs: country flag missing in windows

- docs/src/user-guide/configuring/configuration-files-new.md
I reckon it's ambiguous to say `all files` here.
Clarifying the `files` property of configuration object.
> docs: clarify files property of configuration object

- docs/src/rules/no-undefined.md
Add a function call example on how to skip parameters the safe way
Add Examples for dunction parameter skipping
> docs: Add function call example for no-undefined

- docs/src/rules/no-underscore-dangle.md
- lib/rules/no-underscore-dangle.js
- tests/lib/rules/no-underscore-dangle.js
* **ESLint Version:** `main` branch
* **Node Version:** v16.14.0
default
<details>
```js …
```
> feat: check assignment patterns in no-underscore-dangle

- templates/formatter-examples.md.ejs
Closes https://github.com/eslint/eslint/issues/16676
Change ejs tag from `<%=` to `<%-`.
> fix: do not escape code block of text language

- docs/.eleventy.js
- docs/src/_plugins/md-syntax-highlighter.js
- docs/src/assets/scss/syntax-highlighter.scss
- templates/formatter-examples.md.ejs
A follow-up pull request as we discussed in https://github.com/eslint/eslint/pull/16636#issuecomment-1353732929. Thanks @amareshsm for raising that issue which was introduced by my pull request.
1. refractor syntax highlighting code to minimize changes of CSS.
2. Add `font-variant-ligatures: none;` rule to fix a UI issue under …
> docs: optimize code block structure

- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
Aims to fix https://github.com/eslint/eslint/issues/16576.
This change appends query string with config file's `mtime` to its URL in order to force reload of the config file when it has been changed since the last load.
Marked as draft as this approach doesn't seem to work with CJS config files.
> fix: new instance of FlatESLint should load latest config file version

- lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-arrow-callback.js
Fixes #16718
Changed the autofix behavior of the `prefer-arrow-callback` rule. When converting a regular function to an arrow-style function, the fix will now add an arrow (`=>`) right after the closing parenthesis of the parameter list rather than before the function body.
This serves to avoid a syntax error when the function …
> fix: syntax error in `prefer-arrow-callback` autofix

- lib/rules/prefer-regex-literals.js
- tests/lib/rules/prefer-regex-literals.js
[x] Other, please explain: Add suggestions to a rule
fixes #16516 
```js
new RegExp(/a/, 'g'); 
// suggestions
/a/g;
```
In this case, this change will make two suggestions. - https://github.com/eslint/eslint/issues/16516#issuecomment-1305776045
```js
new RegExp(/a/i, 'g');
// suggestions
/a/g;
/a/ig;
```
> feat: add suggestions for redundant wrapping in prefer-regex-literals

- templates/bug-report.md
- templates/rule-change-proposal.md
- templates/rule-proposal.md
The issue templates are essentially more advanced versions of the ones that were being (redundantly) maintained in the `templates` directory.  <strike>Used relative paths instead instead of hardcoding `eslint/eslint/HEAD` because that makes it easier to review a branch that makes any direct changes to the referenced …
> chore: sync templates/*.md files with issue templates

- Makefile.js
- docs/.eleventy.js
- docs/src/_data/config.json
- docs/src/_includes/components/nav-version-switcher.html
- docs/src/_includes/components/version-switcher.html
- docs/src/_includes/partials/versions-list.html
Resolve https://github.com/eslint/eslint/issues/16041
- Update `Makefile.js` to push to the `next` branch during prerelease.
- Update the docs site to use `pathPrefix` of `/docs/next/` when deployed from the `next` branch. 
- Update the drop-down to include “NEXT” beneath “HEAD”.
> docs: deploy prerelease docs under the `/docs/next/` path

- docs/src/rules/no-fallthrough.md
- lib/linter/linter.js
- lib/rules/no-fallthrough.js
- lib/shared/directives.js
- tests/lib/linter/linter.js
- tests/lib/rules/no-fallthrough.js
Fixes https://github.com/eslint/eslint/issues/16650
Fallthrough comment pattern detection was incorrectly matching to `ESLint` directives.
Abstracts logic from main `linter.js` file to detect directives.  That detection now takes precedence over fallthrough comment pattern detection, regardless of whether the default pattern or …
> fix: ignore directives for no-fallthrough

- docs/src/rules/space-before-function-paren.md
The `space-before-function-paren` page links to two related rules, but they are both marked as having been removed. They both point to `keyword-spacing` as their replacement, so this PR replaces the two related rules with that one related rule.
Having a nice weekend!
> Replace removed related rules with one valid rule

- docs/src/integrate/nodejs-api.md
https://github.com/eslint/eslint/issues/16666
Added a basic example for eslint lintText API in eslint node docs.
No
> docs: add example for nodejs lintText api

- README.md
- docs/src/use/configure/configuration-files.md
- docs/src/use/configure/ignore.md
- docs/src/use/getting-started.md
- docs/src/use/migrating-from-jscs.md
- docs/src/use/migrating-to-3.0.0.md
- docs/src/use/migrating-to-7.0.0.md
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
Consistently use 'an .eslint' rather than 'a .eslint' throughout project.
"a .eslint" -> "an .eslint"
this change came from https://github.com/eslint/eslint/pull/16510#discussion_r1021793537
> docs: 'a .eslint' -> 'an .eslint'

- docs/src/rules/no-restricted-exports.md
- lib/rules/no-restricted-exports.js
- tests/lib/rules/no-restricted-exports.js
Resolve https://github.com/eslint/eslint/issues/15617
* `"restrictDefaultExports"` is an object option with boolean properties to restrict certain default export declarations. The option works only if the `restrictedNamedExports` option does not contain the `"default"` value. The following properties are allowed:
* `direct`: …
> feat: add `restrictDefaultExports` option to no-restricted-exports rule

- docs/src/contribute/code-of-conduct.md
Created code of conduct page, per the [updated IA](https://github.com/eslint/rfcs/pull/97/files)
Resolves #16763
> docs: Code of Conduct page

- docs/src/rules/no-multiple-empty-lines.md
This PR adding back missing empty lines, which accidentally removed via https://github.com/eslint/eslint/commit/db28f2c9ea6b654f615daf2f7e6f1a2034b85062#diff-bb702378ac043bca3c41565355c85509c8bf26510156a27be567f42eb10744cd (thanks to mdjermanovic provides this information: …
> docs: Fix examples in no-multiple-empty-lines rule

- docs/src/rules/no-multiple-empty-lines.md
This PR remove the extra line numbers of the example in `no-multiple-empty-lines` rule.
Closes #16841
> docs: Remove extra line numbers in example

- docs/src/use/configure/ignore.md
- docs/src/use/configure/index.md
- docs/src/use/configure/parser.md
- docs/src/use/configure/plugins.md
Split out page for 'Configure a Parser'
Resolves #16762
> docs: Configure a Parser page

- docs/src/use/command-line-interface.md
> docs: fix typo command-line-interface.md

- lib/eslint/eslint-helpers.js
Removed unused functions.
The `directoryExists` and `fileExists` functions are not used so I removed them.
> chore: Remove unused functions

- lib/rules/array-element-newline.js
It seems the `array-element-newline` rule schema has a `items : [...]` property without its `type : "array"` associated property. I compared to another rule structurally almost similar `comma-dangle` having it and json-schema language doesn't seem to accept a single `items` property for an array object.  
I added `type: …
> chore: type property to array-element-newline schema added

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
Fixes #16850
Added an exception to the rule `no-extra-parens`. Parentheses around a single identifier will no longer be reported if the identifier is the LHS of an assignment with `=`, `&&=`, `||=` or `??=` and the RHS being an anonymous class or function or an arrow function.
> fix: false positive with assignment in `no-extra-parens`

- docs/src/contribute/contribute-core-rule.md
- docs/src/contribute/core-rules.md
- docs/src/contribute/governance.md
- docs/src/contribute/index.md
- docs/src/extend/custom-rules.md
- docs/src/extend/index.md
Resolves https://github.com/eslint/eslint/issues/16648
> docs: split rules documentation

- .github/workflows/stale.yml
- docs/src/maintain/review-pull-requests.md
Update stale bot
Adjusted the stale bot settings to have lower thresholds. My intent here is to not let issues and PRs get so stale that all the context is lost and participants are long gone.
Do these settings make sense?
> chore: Update stale bot settings

- docs/src/extend/custom-formatters.md
- docs/src/extend/custom-parsers.md
- docs/src/extend/custom-rules.md
- docs/src/extend/index.md
- docs/src/extend/plugins.md
- docs/src/extend/ways-to-extend.md
Ways to Extend ESLint page. Summarize the various extension types.
created Ways to Extend ESLint page
Resolves #16810
> docs: Ways to Extend ESLint page

- docs/src/extend/shareable-configs.md
light copy edits on the Shareable Configs page
Resolves #16815
> docs: Shareable configs page edits and expansion

- package.json
the new released esquery v1.4.1 breaks eslint.
related: 
* https://github.com/eslint/eslint/issues/16896
* https://github.com/estools/esquery/issues/135
To wait and see if it can be fixed in esquery, I set it as a draft.
> fix: pin esquery v1.4.0 (fixes #16896)

- package.json
Upgrades to esquery@1.4.2, which brings performance improvements: https://github.com/estools/esquery/pull/134, per [Speeding up the JavaScript ecosystem - eslint](https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-3/).
`npm run test:performance` before:
```
> eslint@8.34.0 test:performance
> node Makefile.js perf …
```
> perf: upgrade to esquery@1.4.2

- docs/.eleventy.js
- docs/package.json
Support markdown anchor with unicode
close https://github.com/eslint/zh-hans.docs.eslint.org/issues/92
> docs: support unicode anchors

- .github/workflows/ci.yml
[x] Other, please explain: CI
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
No
> ci: use LTS node version in workflows

- docs/src/extend/custom-formatters.md
cleanup/expansion of the custom formatter page.
cleaned up and expanded custom formatter page
Resolves #16885
> docs: Custom Formatters page cleanup/expansion

- docs/src/rules/lines-around-comment.md
- lib/rules/lines-around-comment.js
- tests/lib/rules/lines-around-comment.js
> feat: add `afterHashbangComment` option to `lines-around-comment` rule

- lib/rules/no-control-regex.js
- lib/rules/no-extra-boolean-cast.js
- lib/rules/no-extra-parens.js
- lib/rules/no-implied-eval.js
- lib/rules/no-import-assign.js
- lib/rules/no-invalid-regexp.js
- lib/rules/no-misleading-character-class.js
- lib/rules/no-obj-calls.js
- lib/rules/no-promise-executor-return.js
- lib/rules/no-regex-spaces.js
- lib/rules/no-setter-return.js
- lib/rules/no-useless-backreference.js
- lib/rules/prefer-exponentiation-operator.js
- lib/rules/prefer-named-capture-group.js
- lib/rules/prefer-object-spread.js
- lib/rules/prefer-regex-literals.js
- lib/rules/require-unicode-regexp.js
- lib/rules/wrap-iife.js
- lib/source-code/source-code.js
- lib/source-code/token-store/index.js
- package.json
- tests/lib/rules/no-invalid-regexp.js
> feat: use @eslint-community dependencies

- docs/src/extend/custom-parsers.md
Custom Parsers page cleanup/expansion
Resolves #16813
> docs: Custom Parsers cleanup/expansion

- .eslintignore
- .eslintrc.js
- docs/postcss.config.js
- docs/tools/validate-links.js
- eslint.config.js
- tools/fetch-docs-links.js
Currently, in the `docs` folder we're linting only `docs/.eleventy.js`. This PR changes ignore patterns so that we'll lint all js files that are directly in `docs/` and all js files under `docs/tools/`.
Changed ignore patterns in our eslint config files, and fixed lint errors in the two files that are included in js linting …
> chore: lint more js files in docs

- docs/src/extend/custom-formatters.md
Fixes an estree link in the custom formatters page.
Fixed the link.
> docs: fix estree link in custom formatters docs

- lib/config/flat-config-array.js
- tests/lib/config/flat-config-array.js
This implements a check for a 'meta' key on parsers and processors that contains information to help flat config serialize these objects for use with caching and also --print-config on the command line.
I also allowed the `name` and `version` properties at the top level of parsers and processors because some parsers, [including …
> feat: Serialize parsers/processors in flat config

- docs/src/rules/multiline-comment-style.md
- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
multiline-comment-style
[ ] Generate fewer warnings
[x] Implement autofix
[x] Implement suggestions
[x] A new option
[ ] A new default behavior
[ ] Other
**Please provide some example code that this change will …
> feat: Add `checkJSDoc` option to multiline-comment-style

- docs/src/maintain/index.md
- docs/src/maintain/manage-issues.md
- docs/src/maintain/manage-releases.md
- docs/src/maintain/review-pull-requests.md
- docs/src/maintain/working-groups.md
Copy edits throughout Maintain ESLint docs
Resolves #16938
> docs: Copy edits on Maintain ESLint docs

- docs/src/rules/guard-for-in.md
Adds an example to the correct code for the guard-for-in rule that uses Object.hasOwn
Fixes #16981
- [ X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Added an example to the `guard-for-in` rule docs to display best practice of using `Object.hasOwn`. Addresses #16981 …
> docs: Add example to guard-for-in docs.

- docs/src/rules/guard-for-in.md
Describes the different checks that can be used to satisfy guard-for-in and links prefer-object-has-own as a related rule.
- [ X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Follows up on example added in #16983. Describes the different checks that can be used to …
> docs: Describe guard options for guard-for-in.

- docs/src/maintain/index.md
- docs/src/maintain/manage-issues.md
- docs/src/maintain/manage-releases.md
- docs/src/maintain/overview.md
- docs/src/maintain/review-pull-requests.md
- docs/src/maintain/working-groups.md
> docs: 'How ESLint is Maintained' page

- .github/ISSUE_TEMPLATE/change.yml
Updated issue template
Removed the "triage" label from the change request template. We don't really use this label any more and this was the only remaining template where it was automatically added. 
Related: https://github.com/eslint/eslint-github-bot/pull/191
> chore: Remove triage label from template

- docs/src/use/configure/configuration-files-new.md
- lib/config/default-config.js
- lib/config/flat-config-array.js
- lib/config/flat-config-schema.js
- tests/lib/config/flat-config-array.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/linter/linter.js
Changes languageOptions.parser to disallow string values. Now parsers must always be an object.
Fixes #16930
Do the test and documentation updates make sense?
> feat: languageOptions.parser must be an object.

- lib/source-code/token-store/utils.js
- tests/fixtures/parsers/all-comments-parser.js
- tests/lib/source-code/token-store.js
---
This PR fixes an issue with some `SourceCode` methods that is causing unexpected behavior when the source code contains no tokens but one or more comments. The [`SourceCode`](https://eslint.org/docs/latest/extend/custom-rules#contextgetsourcecode) type is part of the public API and is used by virtually all rules, although …
> fix: `getFirstToken`/`getLastToken` on comment-only node

- docs/src/extend/custom-processors.md
Clean up and expansion of the Custom Processors page. 
Resolves #16814
> docs: Custom Processors cleanup and expansion

- docs/src/extend/plugins.md
- lib/config/flat-config-array.js
- tests/lib/config/flat-config-array.js
Updates `FlatConfigArray` to look for meta information on plugins when serializing a config.
Fixes #16284
Does the plugin name/version string format make sense?
> feat: Use plugin metadata for flat config serialization

- docs/.stylelintrc.json
- docs/src/assets/scss/components/alert.scss
- docs/src/assets/scss/components/theme-switcher.scss
- docs/src/assets/scss/components/toc.scss
- docs/src/assets/scss/foundations.scss
- docs/src/assets/scss/tokens/spacing.scss
- docs/src/assets/scss/tokens/typography.scss
reincarnate https://github.com/eslint/eslint/pull/16467
reincarnate https://github.com/eslint/eslint/pull/16467
This is bascially https://github.com/eslint/eslint/pull/16467 but a verified version. I once did removed the rule and checked the scss manually. inspired from base work (https://github.com/eslint/eslint/pull/16467) so …
> docs: remove duplicate scss

- docs/src/_includes/layouts/base.html
- docs/src/_includes/layouts/doc.html
- docs/src/assets/js/scroll-up-btn.js
- docs/src/assets/scss/docs.scss
- docs/src/assets/scss/print.scss
Added a back to top button on docs pages for below 1400px screen size and gave it a classname 'scroll-up-btn', added the scroll up button related JS (made a new file) and CSS.
<details>
<summary>for light mode</summary>
</details>
<details>
<summary>for dark mode</summary>
</details>
PR is related to the issue #16932.
> docs: add back to top button

- docs/src/rules/semi.md
> docs: Fixed typos in `semi.md`

- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
[x] Bug fix
I was playing around with RuleTester and I broke the test by changing the `setDefaultConfig` function to use `defaultConfig = { rules: {}, ...config }`.
Previously the method threw because `defaultConfig.rules` will throw due to property access on `null`. The test was passing before because it wasn't asserting the error message.
This PR simply updates the method so that it handles `null` explicitly and updates the test as appropriate.
> fix: correctly handle `null` default config in `RuleTester`

- docs/src/rules/id-match.md
Fixed a typo and added `const` & `let` to the list of declarations.
> docs: fix typos and missing info

- lib/rules/require-unicode-regexp.js
- tests/lib/rules/require-unicode-regexp.js
[ ] `@typescript-eslint/parser`
[ ] `@babel/eslint-parser`
[ ] `vue-eslint-parser`
[ ] `@angular-eslint/template-parser`
[ ] `Other`
<details>
```json
{ …
```
> fix: do not report on `RegExp(...args)` in `require-unicode-regexp`

- docs/src/rules/no-new.md
Delete the second unnecessary instance.
> docs: Removed the second object instance for the "no-new" rule

- docs/src/rules/no-div-regex.md
- lib/rules/no-div-regex.js
This PR clarifies the usage of the `no-div-regex` rule. I thought it would be helpful to replace a confusing formulation involving "division operators" with a more accurate description of what the rule does.
> docs: Clarify `no-div-regex` rule docs

- docs/src/extend/plugins.md
- docs/src/rules/callback-return.md
- docs/src/rules/global-require.md
- docs/src/rules/handle-callback-err.md
- docs/src/rules/no-buffer-constructor.md
- docs/src/rules/no-mixed-requires.md
- docs/src/rules/no-new-require.md
- docs/src/rules/no-path-concat.md
- docs/src/rules/no-process-env.md
- docs/src/rules/no-process-exit.md
- docs/src/rules/no-restricted-modules.md
- docs/src/rules/no-sync.md
- docs/src/use/configure/language-options.md
- docs/src/use/integrations.md
- docs/src/use/migrate-to-8.0.0.md
- docs/src/use/migrating-to-7.0.0.md
It was brought to my attention, https://github.com/webpro/knip/pull/115#issuecomment-1494087920, that the ESLint docs still point people to `mysticatea/eslint-plugin-node` rather than `eslint-community/eslint-plugin-n`.
While fixing that I looked through most external links in the docs to find which were moved to a new home such …
> docs: Update/remove external links, eg. point to `eslint-community`

- docs/src/use/configure/configuration-files-new.md
- docs/src/use/configure/configuration-files.md
1. Updated the note on the new config file page to indicate that it's feature complete.
2. Added a note on the old config file page to indicate that we are transitioning to a new config system.
Is the wording clear enough?
> docs: Mention new config system is complete

- lib/source-code/source-code.js
Refs discussion under https://github.com/eslint/eslint/pull/17059#discussion_r1158423563.
In my opinion, the current JSDoc description of `SourceCode#getDeclaredVariables` is misleading because it suggests that this method returns `getScope(node).variables`. Considering the name of this method, that would make sense for readers, …
> chore: update description of `SourceCode#getDeclaredVariables`

- lib/rules/no-lone-blocks.js
- lib/rules/no-lonely-if.js
- lib/rules/no-unused-expressions.js
- lib/rules/valid-typeof.js
- lib/rules/wrap-regex.js
- lib/rules/yoda.js
While reviewing https://github.com/eslint/eslint/pull/17059, I noticed that several rules use `SourceCode#getAncestors` just to get the parent or grandparent node. This logic probably originates from time when nodes didn't have the `parent` property.
Since it's more efficient and more common in core rules to simply use the …
> refactor: remove unnecessary use of `SourceCode#getAncestors` in rules

- lib/source-code/token-store/utils.js
Improve performance
Changed token store's `utils.search` function logic to use binary search. This reduces the time complexity of the function from linear to logarithmic time, and results in a performance gain for sufficiently large arrays of tokens.
References #16962
To measure the performance improvement, I considered the time …
> perf: Binary search in token store `utils.search`

- docs/src/maintain/manage-issues.md
Clarifies how to add something to the tsc agenda.
Does this make sense and match your understanding?
> docs: Clarify how to add to tsc agenda

- docs/src/extend/custom-rules.md
- lib/linter/linter.js
- lib/source-code/source-code.js
- package.json
- tests/lib/rules/no-unused-vars.js
- tests/lib/rules/prefer-const.js
- tests/lib/source-code/source-code.js
Implements `SourceCode#markVariableAsUsed()` and sets `context.markVariableAsUsed()` to use it.
Refs #16999
I'm not sure of how I implemented this method. I started out by passing in an `Identifier` node because we can use that to get the scope and determine if it's a declared variable. This also seemed like it would be the most …
> feat: Implement `SourceCode#markVariableAsUsed()`

- docs/src/extend/custom-rules.md
Recently, we had multiple PRs targeting same parts of `docs/src/extend/custom-rules.md`. This PR fixes a few things that were lost in rebases.
> docs: Fix formatting in Custom Rules docs

- README.md
> docs: add mastodon link in readme

- docs/src/use/configure/configuration-files-new.md
I've added a note about how to enable native globals as discussed in https://github.com/eslint/eslint/discussions/17101#discussioncomment-5706223
I think the wording is pretty clear, but let me know if not.
> docs: explain how to include predefined globals

- docs/src/extend/custom-rules.md
Corrected the docs to state that either way option schemas are specified, they should no longer include severities. This has been the behaviour [since ESLint 2.x](https://github.com/eslint/eslint/blob/9d1b8fc60cc31f12618e58c10a2669506b7ce9bf/docs/src/use/migrating-to-2.0.0.md?plain=1#L10-L30)! (git blame shows that these lines …
> docs: Fix custom rule schema docs

- lib/rules/id-length.js
- lib/rules/key-spacing.js
- lib/shared/string-utils.js
- tests/lib/shared/string-utils.js
Improves performance of the `key-spacing` rule when used with options that [enforce alignment](https://eslint.org/docs/latest/rules/key-spacing#align) of keys/values.
Similar to the logic we already have in the `id-length` rule, the `key-spacing` rule will now use `grapheme-splitter` only on non-ASCII strings. For ASCII strings, …
> perf: don't use `grapheme-splitter` on ASCII strings in key-spacing rule

- docs/src/rules/semi.md
- lib/rules/semi.js
- tests/lib/rules/semi.js
Resolve https://github.com/eslint/eslint/issues/17035
1. This PR adds a new `omitLastInOneLineClassBody` option to the `semi` rule. The following code will not throw any error now:
```js
/*eslint semi: ["error", "always", { "omitLastInOneLineClassBody": true}] */
export class SomeClass{
logType(){
console.log(this.type);
}
} …
```
> feat: add new `omitLastInOneLineClassBody` option to the `semi` rule

- docs/src/extend/custom-rules.md
- lib/linter/linter.js
- tests/fixtures/testers/rule-tester/no-test-filename
- tests/lib/linter/linter.js
Refers #16999
This PR creates `context.filename` and deprecates `context.getFilename()`.
Did I miss any reference?
> feat: add `filename` to the rule context

- docs/src/extend/custom-rules.md
- docs/src/integrate/nodejs-api.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Refers #16999 
This PR creates `context.cwd` and deprecates `context.getCwd()`.
Did I miss any references?
> feat: add `cwd` to rule context

- docs/src/extend/custom-rules.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Refers #16999 
This PR creates `context.physicalFilename` and deprecates context.getPhysicalFilename().
Did I miss any references?
> feat: add `physicalFilename` property to the rule context

- lib/config/flat-config-schema.js
- messages/invalid-rule-options.js
- messages/invalid-rule-severity.js
- messages/shared.js
- tests/lib/config/flat-config-array.js
- tests/lib/linter/linter.js
Adds a couple of new error messages for flat config schema parsing.
Fixes #17056
* Unit tests don't seem to cover the full error messages - is this something you'd want added in?
* Please bikeshed my error messages 😄 I'm not confident in them, and mostly based them off the legacy config system's.
* Additionally, this removes the …
> feat: improve flat config errors for invalid rule options and severities

- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
If findConfigFile() can't find eslint.config.js, it now returns undefined instead of throwing an error.
Fixes #17150
Did I miss any edge cases?
> fix: Ensure FlatESLint#findConfigFile() doesn't throw.

- lib/eslint/flat-eslint.js
followup of https://github.com/eslint/eslint/pull/17151#discussion_r1185750069
> refactor: locateConfigFileToUse returns an Error object

- lib/rules/indent.js
- package.json
Improves performance of the `indent` rule. Makes the build faster.
This PR changes the underlying implementation of `BinarySearchTree` in the `indent` rule to a plain array. The name `BinarySearchTree` is changed to `IndexMap` to avoid confusion now that a tree-like structure is no longer used. I also renamed a few other …
> perf: Store indent descriptors in a plain array

- lib/shared/string-utils.js
- package.json
- tests/lib/shared/string-utils.js
Switch `grapheme-splitter` to `graphemer`.
```
> new (require("grapheme-splitter"))().countGraphemes("👩‍🦰👩‍👩‍👦‍👦🏳️‍🌈")
4
> new (require("graphemer").default)().countGraphemes("👩‍🦰👩‍👩‍👦‍👦🏳️‍🌈")
3
```
Use `Intl.Segmenter` when available.
> fix: switch `grapheme-splitter` to `graphemer`

- tests/bench/large.js
- tests/performance/jshint.js
[ X ] Other, please explain:
fix: License issues with old jshint. Updates to current license of jshint
closes https://github.com/eslint/eslint/issues/17143
> document relicensing of jshint, fix license

- lib/eslint/flat-eslint.js
Fixes return type in JSDoc of internal function `findFlatConfigFile`. When it doesn't find a file, `find-up` returns `undefined`, not `null.`
Fixed JSDoc.
> chore: Fix return type of `findFlatConfigFile`

- lib/eslint/eslint-helpers.js
- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
Adds missing validation for `ignorePatterns` constructor option of the `FlatESLint` class.
Updated `function processOptions` to throw a readable message when `ignorePatterns` is not a non-empty string, an array of non-empty strings, or `null`.
I'm not sure if this option should be accepting `string` value as that could be …
> fix: validate `ignorePatterns` constructor option in `FlatESLint` class

- lib/cli.js
- lib/eslint/flat-eslint.js
- lib/unsupported-api.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/unsupported-api.js
- Moved `shouldUseFlatConfig` from `lib/cli.js` to `lib/eslint/flat-eslint.js` and exposed it via exports
- Removed `findFlatConfigFile` from exports in `lib/eslint/flat-eslint.js` since it was only used to build `shouldUseFlatConfig` in `lib/cli.js`
- Exposed `shouldUseFlatConfig` via `lib/unsupported-apis.js`
- Added tests for …
> feat: expose `shouldUseFlatConfig`

- docs/src/extend/custom-processors.md
- lib/cli-engine/cli-engine.js
- lib/eslint/eslint-helpers.js
- lib/eslint/flat-eslint.js
- lib/linter/apply-disable-directives.js
- lib/linter/config-comment-parser.js
- lib/linter/linter.js
- lib/linter/report-translator.js
- lib/shared/types.js
- tests/lib/cli-engine/cli-engine.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/linter/linter.js
- tests/tools/eslint-fuzzer.js
[x] Other, please explain: Update JSDoc types
Fix #16968, changing runtime code as little as possible. First, this updates the `LintMessage` type to match the most common implementation. It also combines some undefined types or duplicate definitions into `LintMessage` so everything references the single definition. Finally, it normalizes the few remaining …
> fix: unify `LintMessage` type

- docs/src/use/configure/configuration-files-new.md
- lib/config/default-config.js
- lib/eslint/eslint-helpers.js
- tests/lib/eslint/flat-eslint.js
Fixes #17113
Changed the default ignore pattern to `**/node_modules/`, updated tests, and added an example of how to unignore a directory in node_modules.
> feat: change default ignore pattern to `**/node_modules/` in flat config

- tests/lib/rules/utils/ast-utils.js
Follow up to https://github.com/eslint/eslint/pull/17059.
Updates `ast-utils` tests to use `SourceCode#getDeclaredVariables()` instead of now-deprecated `context.getDeclaredVariables()`. Also updates two tests that were using `context.getTokenBefore()`.
Updated tests.
> chore: don't use deprecated `context` methods in `ast-utils` tests

- lib/rules/no-useless-return.js
- tests/lib/rules/no-useless-return.js
Fixes https://github.com/eslint/eslint/issues/7481
Implemented the solution as suggested in https://github.com/eslint/eslint/pull/16593#discussion_r1042004643
No
> feat: correct no-useless-return behaviour in try statements

- lib/eslint/eslint-helpers.js
- tests/fixtures/cli-engine/node_modules_cleaner.js
- tests/lib/eslint/flat-eslint.js
Node version: v18.16.0
npm version: v9.5.1
Local ESLint version: v8.41.0 (Currently used)
Operating System: darwin 22.2.0
none …
> fix: Correct ignore message for "node_modules" subfolders

- tests/lib/eslint/flat-eslint.js
While reviewing https://github.com/eslint/eslint/pull/17142, I noticed we didn't have tests where `eslint.config.js` is missing. In particular, a test that would confirm that `FlatESLint` lint methods should throw if a config file was not found.
Added a few tests for `FlatESLint#lintText()` and `FlatESLint#lintFiles()`.
> test: Add `FlatESLint` tests with missing config files

- package.json
- tests/lib/eslint/flat-eslint.js
Fixes #17103
Upgraded `@humanwhocodes/config-array` dependency to include https://github.com/humanwhocodes/config-array/commit/5ed9c2c1a13afb42cd7e9d3b1b247761cb7aa040 fix, and added tests.
~Marked as draft as it uses `@humanwhocodes/config-array` from GitHub while waiting for the release …
> fix: Config with `ignores` and without `files` should not always apply

- lib/rules/no-irregular-whitespace.js
In the `no-irregular-whitespace` rule, this removes an `Identifier` listener that is essentially a no-op since the `removeInvalidNodeErrorsInIdentifierOrLiteral` function has effects only when it's given a string literal node (the `typeof node.value === "string"` condition) or a regex literal node (the `Boolean(node.regex)` …
> refactor: remove `Identifier` listener in no-irregular-whitespace

- docs/src/rules/no-irregular-whitespace.md
- lib/rules/no-irregular-whitespace.js
- tests/lib/rules/no-irregular-whitespace.js
Currently you can use irregular whitespace with rule options in strings: https://eslint.org/docs/latest/rules/no-irregular-whitespace#options
Sometimes I use non-breaking spaces also in JSX text. It would be nice to have this option in `no-irregular-whitespace` rule.
Nope
no-irregular-whitespace
None of this. I added one more option to rule.
Currently I cannot do that:
```jsx
<div>Some text with irregular spaces</div>
```
Currently, if I use non-breaking spaces in JSX text, I get the …
> feat: add `skipJSXText` option to `no-irregular-whitespace` rule

- docs/src/use/configure/configuration-files-new.md
This PR corrects the `ignores` option documentation as suggested [here](https://github.com/eslint/eslint/issues/17103#issuecomment-1539070844) and [here](https://github.com/eslint/eslint/issues/17213#issuecomment-1568929991) and in the [2023-06-01 TSC Meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2023/2023-06-01 …
> docs: Improve `ignores` documentation

- docs/src/use/configure/configuration-files-new.md
Re-adds documentation change from https://github.com/eslint/eslint/pull/17184 that was removed in https://github.com/eslint/eslint/pull/17227.
Copy & paste.
> docs: update flat config default ignore patterns

- docs/src/extend/code-path-analysis.md
- docs/src/extend/custom-rules.md
Resubmitting the docs changes from https://github.com/eslint/eslint/commit/10022b1f4bda1ad89193512ecf18c2ee61db8202 and https://github.com/eslint/eslint/commit/a1d561d18ed653b56bddbfb1bab1ebe957293563.
Refs #17225
> docs: Resubmit getScope/getDeclaredVariables docs

- docs/src/rules/semi.md
As per https://github.com/eslint/eslint/pull/17105#issuecomment-1582569269
No
> docs: add new `omitLastInOneLineClassBody` option to the `semi` rule

- lib/rules/block-scoped-var.js
- tests/lib/rules/block-scoped-var.js
Fixes https://github.com/eslint/eslint/issues/17244
In the `block-scoped-var` rule, I added the location info of declarations to reported messages. This should clarify cases where there are multiple errors on the same reference, and seems useful in general.
> feat: add declaration loc to message in block-scoped-var

- docs/src/extend/custom-rules.md
- docs/src/use/migrate-to-8.0.0.md
- docs/src/use/migrating-to-5.0.0.md
Done b/c need to have OSS license apply to them.
See #17225
Resubmitted docs for custom rules updates, which were originally merged in #16906. 
Nothing in this PR has hasn't already been reviewed. Just copy-paste of files from #16906. Worth giving this a sanity check to make sure I didn't mess anything up though. 
see also …
> docs: Resubmit custom rules update docs

- docs/src/extend/plugins.md
Resubmits the docs from PR https://github.com/eslint/eslint/pull/16992
No
> docs: resubmit `Create Plugins` documentation

- docs/src/extend/custom-processors.md
https://github.com/eslint/eslint/pull/17076#issuecomment-1582563239
No
> docs: resubmit `Custom Processors` documentation

- docs/src/extend/code-path-analysis.md
- docs/src/extend/custom-rules.md
- docs/src/integrate/nodejs-api.md
credits: https://github.com/snitin315
Refs:
* https://github.com/eslint/eslint/issues/17225
it contains the docs changes in following PRs [as suggested](https://github.com/eslint/eslint/pull/17290#issuecomment-1592759455):
* https://github.com/eslint/eslint/pull/17108
* https://github.com/eslint/eslint/pull/17106
* https://github.com/eslint/eslint/pull/17111
* https://github.com/eslint/eslint/pull/17107
[ …
> docs: resubmit custom-rules doc changes

- docs/src/rules/semi.md
credits: https://github.com/alundiak
Refs:
* https://github.com/eslint/eslint/issues/17225
* https://github.com/eslint/eslint/pull/17012
> docs: resubmit pr17012 doc changes

- docs/src/rules/quotes.md
- lib/rules/quotes.js
- tests/lib/rules/quotes.js
see #17022
This PR implements two changes in the `quotes` rule:
* Fixed detection of directive prologues to account for parentheses around string literals, e.g. differentiate `"use strict";` from `("use strict");`. This can cause the rule to report new problems in certain cases.
* Changed the logic that determines whether an …
> feat: directive prologue detection and autofix condition in `quotes`

- docs/src/rules/no-extra-semi.md
- lib/rules/no-extra-semi.js
- tests/lib/rules/no-extra-semi.js
References #16988
This PR disables the autofix for the `no-extra-semi` rule if removing the semicolon could cause the following statement to become a directive. For example:
```js
function foo({ bar })
{
; // no autofix!
"use strict";
}
```
The autofix is disabled:
* Only if a semicolon is followed by an `ExpressionStatement` …
> fix: Remove `no-extra-semi` autofix before potential directives

- lib/cli-engine/cli-engine.js
- lib/eslint/flat-eslint.js
- lib/rules/accessor-pairs.js
- lib/rules/array-element-newline.js
- lib/rules/grouped-accessor-pairs.js
- lib/rules/indent.js
- lib/rules/max-len.js
- lib/rules/no-loss-of-precision.js
- [X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
[ X] Other, please explain:
made various performance improvements to various parts of the code mainly based around removing unnecessary object creation and overhead from the functional tools (map, filter, reduce)
> perf: various performance improvements

- docs/src/use/configure/configuration-files-new.md
- tests/fixtures/promise-config/a.js
- tests/fixtures/promise-config/eslint.config.js
- tests/lib/eslint/flat-eslint.js
Fixes https://github.com/eslint/eslint/issues/16864, Fixes https://github.com/eslint/eslint/issues/16580
Officially adds support for exporting Promises from `eslint.config.js` files. Technically, this was already working.
Note that this doesn't mean that a config object inside the config array can be a Promise, just that …
> feat: allow flat config files to export a Promise

- lib/eslint/flat-eslint.js
Removes unnecessary code in `flat-eslint.js`.
`function processLintReport` uses only `results` property from the second argument. This removes code that calculates other (unused) properties, which mostly originates from `cli-engine.js` and is unnecessary in `flat-eslint.js`:
* stats per run: FlatESLint/ESLint, unlike CLIEngine, …
> refactor: remove unnecessary code in `flat-eslint.js`

- lib/rules/logical-assignment-operators.js
- lib/rules/prefer-exponentiation-operator.js
- lib/rules/utils/ast-utils.js
- tests/fixtures/parsers/typescript-parsers/boolean-cast-with-assertion.js
- tests/fixtures/parsers/typescript-parsers/exponentiation-with-assertion-1.js
- tests/fixtures/parsers/typescript-parsers/exponentiation-with-assertion-2.js
- tests/fixtures/parsers/typescript-parsers/exponentiation-with-assertion-3.js
- tests/fixtures/parsers/typescript-parsers/exponentiation-with-assertion.js
- tests/fixtures/parsers/typescript-parsers/logical-assignment-with-assertion.js
- tests/fixtures/parsers/typescript-parsers/logical-with-assignment-with-assertion-1.js
- tests/fixtures/parsers/typescript-parsers/logical-with-assignment-with-assertion-2.js
- tests/fixtures/parsers/typescript-parsers/logical-with-assignment-with-assertion-3.js
- tests/fixtures/parsers/typescript-parsers/member-call-expr-with-assertion.js
- tests/fixtures/parsers/typescript-parsers/unneeded-ternary-1.js
- tests/fixtures/parsers/typescript-parsers/unneeded-ternary-2.js
- tests/lib/rules/logical-assignment-operators.js
- tests/lib/rules/no-extra-boolean-cast.js
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-unneeded-ternary.js
- tests/lib/rules/prefer-exponentiation-operator.js
#17173
This PR changes the `getPrecedence` util so that it assumes all unknown nodes have the lowest possible precedence.
This means that lint rules will assume the unknown nodes require parentheses when evaluating or creating fixes.
I have included some test cases for TS code to validate the behaviour works as intended.
> feat: treat unknown nodes as having the lowest precedence

- docs/src/rules/no-unused-labels.md
- lib/rules/dot-notation.js
- lib/rules/no-restricted-modules.js
- lib/rules/no-unused-labels.js
- lib/rules/prefer-regex-literals.js
- lib/rules/utils/ast-utils.js
- lib/rules/valid-typeof.js
- lib/rules/yoda.js
- tests/lib/rules/no-unused-labels.js
- tests/lib/rules/utils/ast-utils.js
References #16988
This PR disables the autofix for the `no-unused-labels` rule if removing a label could cause the following statement to become a directive. For example:
```js
/* eslint no-unused-labels: "error" */
UnusedLabel: "use strict"; // There should be no autofix!
```
Following the changes in this PR, the autofix will …
> fix: Remove `no-unused-labels` autofix before potential directives

- docs/src/extend/custom-parsers.md
- docs/src/extend/custom-rules.md
- tests/lib/linter/linter.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Refs #16999, fixes task "Copy parserServices to SourceCode".
`SourceCode#parserServices` already existed, but was undocumented. This effectively only deprecates `context.parserServices` in favor of `SourceCode#parserServices`.
* Marked `context.parserServices` deprecated in the docs.
* Added documentation for …
> feat: Move `parserServices` to `SourceCode`

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #17299
The PR fixes the no-unused-vars rule for the logical assignment operator input.
The  logical assignment operator are `??=`, `||=`, `&&=` now.
I have chosen to use regular expressions to validate logical assignment operators. However, I am unsure if there is a better way to implement it.
> fix: no-unused-vars false positive with logical assignment operators

- tests/lib/rules/no-case-declarations.js
A (minor) perf improvement
Improved heuristic for the rule, if there are no `consequents` or if the `case` block contains a block statement, then we can determine that the rule does not need to be executed.
I benchmarked this with the `TIMING` env variable but sadly I didn't see any improvements, leaving this up to the …
> test: More test cases for no-case-declarations

- docs/src/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
```js
a && b ? foo : bar
```
Such code may not be clear to readers who do not know enough about priorities, whether it is
```js
(a && b) ? foo : bar
```
or
```js
a && (b ? foo : bar)
```
To better express the priority, one may choose to add parentheses to it and use `no-mixed-operators` rule with `groups: [['||' , '&&', '?:']]` …
> feat: add ternaryOperandBinaryExpressions option to no-extra-parens rule

- docs/src/use/configure/language-options.md
- package.json
Upgrades `@eslint/eslintrc` to the latest v2.1.0 to add `es2023` and `es2024` environments.
Fixes #17298
Updated package.json and the docs.
> feat: add `es2023` and `es2024` environments

- lib/rules/indent.js
- tests/lib/rules/indent.js
Fixes #17316
This bug fix can generate more warnings from the `indent` rule in existing code, so marked as `feat`.
Removed a condition that causes indentation not to be applied to `if` in else-if positions.
Please check if this change could cause any unwanted behavior. All existing tests are passing after this change, so I'm not …
> feat: fix indent rule for else-if

- .eslintrc.js
- eslint.config.js
- packages/eslint-config-eslint/eslintrc.js
- packages/eslint-config-eslint/index.js
- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
moving jsdoc settings to eslint-config-eslint, so it's not needed to add it in other repos.
> chore: move jsdoc settings to eslint-config-eslint

- docs/src/rules/prefer-destructuring.md
Fixes #17327
Added the following examples for the prefer-destructing rule:
* invalid: `bar.baz = array[0];`
* valid: `[bar.baz] = array;`
> docs: add more prefer-destructuring examples with array destructuring

- lib/linter/report-translator.js
- tests/lib/linter/linter.js
- tests/lib/linter/report-translator.js
Fixes #16716
Updated `report-translator` to always create new `fix` objects and `fix.range` arrays. This ensures that lint messages do not share same instances, which could be problematic for processors that mutate these objects.
Added unit tests for `report-translator`, and one higher-level `linter` test that specifically …
> fix: provide unique `fix` and `fix.range` objects in lint messages

- lib/unsupported-api.js
- tests/lib/unsupported-api.js
Adds a `LegacyESLint` class to `/use-at-your-own-risk` as a transitional class meant to ease migration to flat config in ESLint v9.0.0.
fixes #17340
> feat: Expose LegacyESLint in unsupported API

- docs/src/extend/custom-rules.md
[] Other, please explain:
While reading the documentation on how rules are configured and specifying options schemas on custom rules, it wasn't clear to me exactly how the two kinds of schema values (object/array) were applied, and I spent a few hours tearing my hair out trying to make a custom object schema work before delving into the code and realising …
> docs: Expand rule options schema docs

- docs/.eleventy.js
- docs/src/assets/js/main.js
- docs/src/assets/scss/docs.scss
- docs/src/rules/no-implicit-globals.md
- docs/src/rules/no-restricted-imports.md
Adds a [markdown-it-container `render`](https://github.com/markdown-it/markdown-it-container#api) method for `:::correct` and `:::incorrect` blocks that adds a playground link. That link is hidden when not focused or hovered.
* Is this a visual design that brings you joy?
* From …
> docs: add playground links to correct and incorrect code blocks

- lib/rules/no-loop-func.js
- tests/lib/rules/no-loop-func.js
Node version: v18.16.0
npm version: v9.5.1
Local ESLint version: v8.44.0 (Currently used)
Operating System: win32 10.0.23493
[ ] …
> fix: Update no-loop-func to not overlap with no-undef

- lib/config/flat-config-schema.js
- messages/eslintrc-incompat.js
- tests/lib/config/flat-config-array.js
- tests/lib/rule-tester/flat-rule-tester.js
Includes some keys to catch known eslintrc keys when they appear in flat config. This throws a specific error that the ESLint CLI can then output a more helpful message about.
refs #17370
Did I miss any top-level keys?
(Note: we can probably do more to do things like catch the different in `plugins` format, just wanted to get …
> feat: Improve config error messages

- docs/src/use/configure/migration-guide.md
Fixes `Ignoring Files` section in config migration guide.
Fixed some incorrect details.
> docs: fix Ignoring Files section in config migration guide

- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes #17343
Updated `FlatESLint#getRulesMetaForResults` to ignore unknown rules.
> fix: FlatESLint#getRulesMetaForResults shouldn't throw on unknown rules

- docs/src/use/configure/migration-guide.md
This PR extends the migration guide with information on how to replace `eslint-env` configuration comments in files when switching from eslintrc to flat config.
Please, check my comments in the PR. I haven't found anything specific about how to deal with `eslint-env` comments in the discussions I reviewed, so I'm sorry if I went …
> docs: Migrating `eslint-env` configuration comments

- lib/rules/no-invalid-regexp.js
- package.json
- tests/lib/rules/no-invalid-regexp.js
Update `@eslint-community/regexpp` to v4.6.0
Refs #17223
This PR modifies the `no-invalid-regexp` rule and adds support for regexp `v` flag.
> feat: `no-invalid-regexp` support `v` flag

- lib/rules/no-useless-backreference.js
- tests/lib/rules/no-useless-backreference.js
Refs #17223
This PR modifies the `no-useless-backreference` rule and adds support for regexp `v` flag.
> feat: `no-useless-backreference` support `v` flag

- lib/rules/prefer-regex-literals.js
- lib/rules/utils/regular-expressions.js
- tests/lib/rules/prefer-regex-literals.js
Refs #17223
This PR modifies the `prefer-regex-literals` rule and adds support for regexp `v` flag.
> feat: `prefer-regex-literals` support `v` flag

- lib/rules/no-regex-spaces.js
- tests/lib/rules/no-regex-spaces.js
Refs #17223
This PR modifies the `no-regex-space` rule and adds support for regexp `v` flag.
> feat: `no-regex-spaces` support `v` flag

- docs/src/rules/no-misleading-character-class.md
- lib/rules/no-misleading-character-class.js
- lib/rules/utils/regular-expressions.js
- tests/lib/rules/no-misleading-character-class.js
Refs #17223
This PR modifies the `no-misleading-character-class` rule and adds support for regexp `v` flag.
> feat: `no-misleading-character-class` support `v` flag

- lib/rules/prefer-named-capture-group.js
- tests/lib/rules/prefer-named-capture-group.js
Refs #17223
This PR modifies the `prefer-named-capture-group` rule and adds support for regexp `v` flag.
> feat: `prefer-named-capture-group` support `v` flag

- lib/rules/no-control-regex.js
- tests/lib/rules/no-control-regex.js
Refs #17223
This PR modifies the `no-control-regex` rule and adds support for regexp `v` flag.
> feat: `no-control-regex` support `v` flag

- docs/src/_data/further_reading_links.json
- docs/src/_data/rules.json
- docs/src/_data/rules_meta.json
- docs/src/rules/no-return-await.md
- lib/rules/no-return-await.js
- packages/js/src/configs/eslint-all.js
The original intent of this rule no longer applies due to the fact Javascript now handles native `Promises` differently. It can no be slower to remove `await` rather than keeping it.
Fixes #17345
[] Add something to the core
Deprecate `no-return-await`.
> feat: deprecate no-return-await

- docs/src/rules/no-empty-character-class.md
- lib/rules/no-empty-character-class.js
- tests/lib/rules/no-empty-character-class.js
Refs #17223
Updates `no-empty-character-class` to report nested empty character classes.
Before this change, this rule was reporting _some_  but not all empty nested character classes, depending on how its own parsing happened to work with the new syntax. Since the syntax becomes too complicated for analyzing patterns with a …
> feat: `no-empty-character-class` support `v` flag

- .github/workflows/add-to-triage.yml
- docs/src/contribute/work-on-issue.md
- docs/src/maintain/manage-issues.md
Infrastructure
Adds PRs to the triage project so we can manage issues and PRs in one place.
I also updated the triaging documentation to explicitly mention pull requests.
Related PRs:
* https://github.com/eslint/espree/pull/580
* https://github.com/eslint/eslintrc/pull/121
* https://github.com/eslint/eslint-visitor-keys/pull/54 …
> chore: Add PRs to triage project

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
Refs #17223
This PR modifies the `no-useless-escape` rule and adds support for regexp `v` flag.
> feat: `no-useless-escape` support `v` flag

- docs/src/extend/custom-processors.md
- docs/src/extend/plugins.md
- docs/src/use/configure/migration-guide.md
Added a warning box to the Plugin and Custom Processor docs noting that the file extension-named processor feature has been removed in flat configuration, and therefore will be completely removed in ESLint v9.
Plugin authors need to be aware that when converting to/implementing new flat configs, they can no longer rely on this …
> docs: File extension named processor deprecation

- docs/src/rules/constructor-super.md
- docs/src/rules/no-dupe-class-members.md
I added TypeScript information to the docs.
No.
The `no-dupe-class-members` rule helpfully documents that if you are using TypeScript, then you don't have to enable the rule. This is fantastic! However, there are many other ESLint rules that are also pointless if you are using TypeScript, but they are not documented. So this is the first step in solving that problem.
I want to document all rules that are covered by the TypeScript compiler, and this PR is the first step in doing so.
In my next PR I would like to reduce the text duplication that I am introducing with this PR by using some kind of auto-filled template. I envision something like:
```
{{ TypeScript 2377 }}
```
Which would output the following text during the actual website build:
```
It is safe to …
```
> docs: update with TypeScript info

- docs/src/extend/custom-parsers.md
- docs/src/extend/custom-processors.md
- docs/src/extend/plugins.md
Added `metadata` descriptions to `custom-parsers.md` and `custom-processors.md`. I don't know if `metadata` object is also implemented for formatters, if so I am happy to add a section covering that, too.
The current `meta` sections are mostly copied from `plugins.md`. Frankly I don't know if `meta` object helps ESLint cache the …
> docs: add metadata for parser/processor

- docs/src/use/configure/language-options.md
I added Supplementary explanations to the docs 
Motivation
After reading the explanation, I thought that having a summary at the end would be helpful for better comprehension. Therefore, I added a summarizing section at the end of the text. This may assist readers who might have had difficulty understanding the earlier parts or …
> docs: update with "Specifying Parser Options"

- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-eval.js
- tests/lib/rules/no-invalid-this.js
`no-eval` and `no-invalid-this`
[X] Generate fewer warnings
[ ] Implement suggestions
[ ] A …
> feat: update regex for methods with `thisArg`

- docs/src/_data/further_reading_links.json
- docs/src/rules/require-unicode-regexp.md
Address review comments in https://github.com/eslint/eslint/pull/17402
> docs: update `require-unicode-regexp.md` as following up #17402

- docs/src/use/configure/configuration-files-new.md
I had a very confusing time reading the ESLint docs today so I think this extra warning section will really help ESLint users who are migrating.
No.
> docs: document lack of config file names

- docs/package.json
Refers #14827
This updates the names of the scripts in package.json to be consistent with the [new standard](https://eslint.org/docs/latest/contribute/package-json-conventions).
Is there any script we need to update in Netlify/jenkins?
> chore: standardize npm script names

- lib/rules/no-new-wrappers.js
- tests/lib/rules/no-new-wrappers.js
Node version: v20.5.0
npm version: v9.8.0
Local ESLint version: v8.46.0 (Currently used)
Operating System: darwin 22.5.0
[ ] …
> fix: do not report on shadowed constructors in `no-new-wrappers`

- docs/src/rules/no-promise-executor-return.md
- lib/rules/no-promise-executor-return.js
- tests/lib/rules/no-promise-executor-return.js
- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
[x ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
- Allow void in `no-promise-executor`
- Update relevant documentation
- Add auto fix that adds a `void` in front of the returned expression (open for debate)
- Update relevant tests
Edge cases that I might have not …
> feat: Allow `void` in rule `no-promise-executor-return`

- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
[x] Other, please explain: RuleTester no longer creates empty `valid` or `invalid` test suites
Fix #17455 by only calling `RuleTester.describe` for `valid` and `invalid` if they have respective test cases.
The outer test suite with the rule name is always created even if there are no valid or invalid test cases as the `RuleTester#run` call is useless …
> feat: rule tester do not create empty valid or invalid test suites

- docs/src/use/configure/configuration-files-new.md
Fixes #17355
Fixed a code example that shows how to include a flat config from a plugin in a config file. The name of the plugin config was changed to match an actual flat config - rather than an eslintrc config - exported by `eslint-plugin-jsdoc`.
> docs: fix example of flat config from plugin

- docs/src/use/configure/rules.md
Updated the disable rules section giving advice to the developer so that it is not abused in the codebase.
Fixes #16754
> docs: advice for inline disabling of rules

- lib/linter/code-path-analysis/code-path-segment.js
Slight refactor and JSDoc cleanup
Updated the JSDoc for `CodePathSegment` to better explain what's going on. Also refactored one method.
Do the explanations make sense?
> chore: Refactor and document CodePathSegment

- docs/src/rules/for-direction.md
- lib/rules/for-direction.js
- tests/lib/rules/for-direction.js
Node version: v20.5.1
npm version: v9.8.0
Local ESLint version: v8.47.0 (Currently used)
Operating System: darwin 22.5.0
[ ] …
> feat: correct update direction in `for-direction`

- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
Without this fix, I get a misguided warning in IntelliJ IDEA that the "new-style" rule defintition on line 14 from [this example in the documentation](https://eslint.org/docs/latest/extend/custom-rule-tutorial#step-6-write-the-test) does not match the type `Function`  — it should accept both the legacy `Function` and new style, object-based `Rule` definitions.
[ ] Add something to the …
> fix: RuleTester JSDoc and deprecations

- docs/src/contribute/core-rules.md
- docs/src/contribute/governance.md
- docs/src/contribute/package-json-conventions.md
- docs/src/contribute/pull-requests.md
- docs/src/contribute/report-security-vulnerability.md
- docs/src/contribute/work-on-issue.md
- As discussed in https://github.com/eslint/eslint.org/pull/461#discussion_r1290339543 
- Added `fetch:*` scripts to package.json conventions.
- Added package.json convention to the navigation.
No
> docs: add `fetch` script to package.json conventions

- docs/src/rules/no-param-reassign.md
The documentation page for [no-param-reassign](https://eslint.org/docs/latest/rules/no-param-reassign#rule-details) currently references a consideration for mutating the arguments object. Which, is valid in "sloppy mode". But, if I'm reading [this MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_ …
> docs: no-param-reassign mention strict mode

- docs/src/_includes/layouts/doc.html
- docs/src/rules/constructor-super.md
- docs/src/rules/getter-return.md
- docs/src/rules/no-const-assign.md
- docs/src/rules/no-dupe-args.md
- docs/src/rules/no-dupe-class-members.md
- docs/src/rules/no-dupe-keys.md
- docs/src/rules/no-func-assign.md
- docs/src/rules/no-import-assign.md
- docs/src/rules/no-invalid-this.md
- docs/src/rules/no-new-symbol.md
- docs/src/rules/no-obj-calls.md
- docs/src/rules/no-redeclare.md
- docs/src/rules/no-setter-return.md
- docs/src/rules/no-this-before-super.md
- docs/src/rules/no-undef.md
- docs/src/rules/no-unreachable.md
- docs/src/rules/no-unsafe-negation.md
This is a follow-up on my last PR, #17423.
@nzakas mentioned in the ESLint Discord server that we should move forward with reducing the duplication introduced with my last PR by using a frontmatter template, which this PR includes.
Additionally, I also documented the remaining known ESLint core rules that conflict with the TypeScript compiler.
When doing this PR, I noticed that the rules pages have inconsistent formatting.
Rules randomly have either 1, 2, 3, or 5 newlines after the frontmatter.
This kind of thing makes it difficult for people to contribute, as it makes finding the proper style non-trivial.
I propose that docs should be formatted using Prettier (or dprint), in the same way that the @typescript-eslint project does.
> docs: add typescript template

- docs/src/rules/lines-between-class-members.md
- lib/rules/lines-between-class-members.js
- tests/lib/rules/lines-between-class-members.js
Fixes https://github.com/eslint/eslint/issues/17082
The `lines-between-class-members` can now expect an object with a property named `enforce` as the first option.
* `Object`: An object with a property named `enforce`. The enforce property should be an array of objects, each specifying the configuration for enforcing empty lines …
> feat: add new `enforce` option to `lines-between-class-members`

- docs/src/rules/no-promise-executor-return.md
Add `/*eslint-env es6*/` to examples so that ESLint can report errors on ES6 syntax.
Without this, the playground doesn't show any errors on the incorrect code example when we click on `Open in Playground` button.
- [Before Demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcHJvbWlzZS1leGVjdXRvci1yZXR1cm46IFwiZXJyb3JcIiov …
> docs: update `no-promise-executor-return` examples

- docs/src/rules/array-callback-return.md
- lib/rules/array-callback-return.js
- tests/lib/rules/array-callback-return.js
Added a new option called `allowVoid` to the `array-callback-return` rule which allow `void` operator to be used in `forEach` callback return. This option will work only with `checkForEach: true` option.
```js
/*eslint array-callback-return: ["error", { checkForEach: true, allowVoid: true }]*/
myArray.forEach(item => void …
```
> feat: allowVoid option in array-callback-return

- docs/src/rules/logical-assignment-operators.md
In `logical-assignment-operator` rule [page](https://eslint.org/docs/latest/rules/logical-assignment-operators#enforceforifstatements) an `incorrect` tag is placed wrong. because of that code within the tag isn't opening in the playground.
> docs: fix incorrect tag's place

- lib/rules/no-misleading-character-class.js
- tests/lib/rules/no-misleading-character-class.js
close #17537
Fixed incorrect message and changed to not suggest u flag, when Unicode code point escapes were included.
> fix: wrong suggestion and message in `no-misleading-character-class`

- docs/src/rules/prefer-arrow-callback.md
Added correct/incorrect tagged fences around code examples in the docs of `prefer-arrow-callback`.
> docs: Add correct/incorrect tags to `prefer-arrow-callback`

- docs/src/_data/rules.json
- docs/src/_data/rules_meta.json
- docs/src/rules/no-array-constructor.md
- docs/src/rules/no-new-object.md
- docs/src/rules/no-new-wrappers.md
- docs/src/rules/no-object-constructor.md
- lib/rules/index.js
- lib/rules/no-new-object.js
- lib/rules/no-object-constructor.js
- packages/js/src/configs/eslint-all.js
- tests/lib/rules/no-object-constructor.js
- tools/rule-types.json
[X] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
Fixes #17517
This PR deprecates the `no-new-object` rule and adds a new rule `no-object-constructor` as discussed in #17517.
The new rule is differs from the old one in these aspects:
- `new Object` is only reported when invoked without arguments.
- `Object()` call expressions are reported as well.
- The new rule has …
> feat: add rule `no-object-constructor`, deprecate `no-new-object`

- docs/src/rules/jsx-quotes.md
- docs/src/rules/keyword-spacing.md
- docs/src/rules/no-extra-parens.md
- docs/src/rules/no-inline-comments.md
- docs/src/rules/no-irregular-whitespace.md
- docs/src/rules/no-unused-expressions.md
This PR aims to make JSX code examples in rule docs loaded with the correct parser options in the playground. Opening any of these code examples in the playground results currently in a parser error, because JSX is not enabled by default.
* Added `{ "ecmaFeatures": { "jsx": true } }` to the parser options of examples that …
> docs: Fix and standardize JSX code examples

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
When I initially added deprecation warnings to `RuleTester` for `context` methods that have been moved to `SourceCode`, I missed the newest ones. This PR adds the remaining four deprecated methods.
We also have deprecated methods like `getCwd()`, `getSourceCode()`, `getFilename()` and `getPhysicalFilename()`, and I wasn't sure …
> fix: Ensure all RuleTester tests all deprecated context methods

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Updated RuleTester to emit a deprecation warning whenever `context.parserServices` is used.
The `context.parserServices` property has been deprecated but we weren't warning about it with `RuleTester`, so I added that check.
Because there was already a test using `context.parserServices`, I modified that test to check for the …
> fix: Ensure deprecated context.parserServices warns

- lib/config/flat-config-schema.js
- lib/linter/linter.js
- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- lib/source-code/source-code.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/linter/linter.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
- tests/lib/source-code/source-code.js
The original intent of this commit was to implement `SourceCode#getInlineConfig()` as described in the [Language Plugins RFC](https://github.com/eslint/rfcs/blob/main/designs/2022-languages/README.md). However, once I started to implement this feature I realized that the design in the RFC wouldn't work and I had to make some …
> feat: Implement SourceCode#applyInlineConfig()

- lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/flat-rule-tester.js
Fixes #17577
[x] Other, please explain: Flat Rule Tester bug fix
Add `files: ["**/*.*"]` to the default shared config of the flat rule tester.
Adjusted the static methods `setDefaultConfig` to make sure `files` is always set and `resetDefaultConfig`.
I decided to use object spread rather than defining the same properties because of the file pattern which …
> feat: flat-rule-tester make sure default config always matches

- lib/linter/code-path-analysis/code-path.js
Refactored and added comments
Continuing my refactoring and documenting of code path analysis with `CodePath`. I cleaned up the JSDoc comments, added comments to help explain what the logic is doing, and refactored a bit of code.
Please double check lines 301-end of file to make sure those explanations make sense.
> chore: Refactor and document CodePath

- docs/src/rules/logical-assignment-operators.md
- lib/rules/logical-assignment-operators.js
- tests/lib/rules/logical-assignment-operators.js
fixes #17096
This PR fixes logical-assignment-operators to report associativity logical expressions with three or more operands.
> feat: logical-assignment-operators to report expressions with 3 operands

- docs/src/use/command-line-interface.md
- docs/src/use/configure/ignore.md
- lib/cli.js
- lib/eslint/eslint-helpers.js
- lib/eslint/flat-eslint.js
- lib/options.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
- tests/lib/options.js
This is related to https://github.com/eslint/rfcs/pull/90 and https://github.com/eslint/eslint/issues/15010
- Added --no-warn-ignored CLI option
- Removed inconsistent warnIgnored defaults **for FlatESLint**, now it always defaults to `true` regardless if you're using CLI, or `lintFiles()`, or `lintText()`.
- Updated warning …
> feat: Add `--no-warn-ignored` CLI option for flat config

- docs/src/rules/multiline-ternary.md
I have thought of a new way to implement the multiline-ternary.
I have moved the ? and : below the logical expression to make it more readable and understandable in cases were logical expressions get more complex.
Also this way has a look of a tree to know where the first "IF" statement starts and where it finishes.
> docs: Add more examples for multiline-ternary

- tests/lib/linter/linter.js
Fixes several Linter tests under `"Linter with FlatConfigArray"` to really use Linter in the flat config mode.
`Linter#verify()` needs `configType: "flat"` constructor option AND the second, `config` argument to trigger the flat config mode. Without the `config` argument, `Linter#verify()` still works in the eslintrc mode …
> test: fix flat config linter tests to use Linter in flat config mode

- lib/linter/code-path-analysis/code-path-state.js
- tests/fixtures/code-path-analysis/logical--and-qq.js
- tests/fixtures/code-path-analysis/logical--if-mix-and-qq-1.js
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
I changed the generated code path for `&&` expressions that are the left-hand operand of `??` expressions so that they show the short-circuiting of nullish values. I updated old tests that were producing incorrect results, as well.
I also did some more refactoring and added more comments with my understanding of what is …
> fix: Ensure correct code path for && followed by ??

- lib/linter/apply-disable-directives.js
- lib/linter/config-comment-parser.js
- tests/lib/linter/config-comment-parser.js
- tests/lib/linter/linter.js
This PR fixes the suppression directive comment so that it can parse rule names like string literals using quotes.
fixes #17598
> fix: `eslint-disable` to be able to parse quoted rule names

- lib/config/flat-config-schema.js
- tests/lib/config/flat-config-array.js
- tests/lib/linter/linter.js
Fixes https://github.com/eslint/eslint/issues/17570
Updated `function assertIsRuleSeverity` to ensure that rule severities are case-sensitive in flat config.
This means that configurations such as `"no-alert": "Off"` or `"no-alert": ["Error"]` will be invalid.
This also applies to inline configuration comments. For example, `/* …
> fix: make rule severity case-sensitive in flat config

- docs/src/rules/unicode-bom.md
Updated some code examples of the `unicode-bom` rule to include a real BOM character where required. This is necessary to make the these examples correct or incorrect as expected, with respect to the rule reporting a problem or not.
The only minor inconvenience I see with change is that it introduces a visible character at the …
> docs: Fix examples in `unicode-bom`

- docs/src/rules/no-trailing-spaces.md
Updated code examples of the `no-trailing-spaces` rule to include real whitespace rather than placeholders where expected. This is especially necessary to make the invalid code example really invalid.
> docs: Add real whitespace to `no-trailing-spaces` examples

- docs/src/_data/further_reading_links.json
- docs/src/rules/no-irregular-whitespace.md
Fixed outdated info and code examples in the `no-irregular-whitespace` rule docs.
The Mongolian Vowel Separator lost its Zs status quite a while ago [in Unicode 6.3](https://www.unicode.org/versions/Unicode6.3.0/#Database_Changes), so it can no longer be used as a token separator in JS code today. I fixed a code example that was …
> docs: Update `no-irregular-whitespace` and fix examples

- templates/formatter-examples.md.ejs
On the formatters page, I added syntax highlighting for some formatters (not all) and I'm pretty-printing the JSON output. 
I intentionally did not attempt to format the XML because we will be removing those formatters for v9.0.0, and that would require an extra dependency that we'd just end up removing.
fixes #17505
> docs: Enable pretty code formatter output

- docs/.eleventy.js
- docs/src/rules/eol-last.md
- docs/src/rules/no-multiple-empty-lines.md
Fixes #17627
Removed the last newline character from the code of Playground links in rule examples.
Fixed examples of the rules `eol-last` and `no-multiple-empty-lines`.
> docs: Remove trailing newline from the code of Playground links

- docs/src/rules/arrow-body-style.md
- docs/src/rules/function-paren-newline.md
- docs/src/rules/id-match.md
- docs/src/rules/indent.md
- docs/src/rules/lines-around-directive.md
- docs/src/rules/max-statements-per-line.md
- docs/src/rules/max-statements.md
- docs/src/rules/no-multiple-empty-lines.md
- docs/src/rules/one-var.md
Fixed some examples I noticed while reviewing recent changes in the rules docs.
> docs: fix examples for several rules

- docs/src/extend/plugin-migration-flat-config.md
Added a migration guide for plugins to implement flat config. This focuses on the `configs` key but also touches on everything else that plugins can export.
Fixes #17242
Did I miss any details? Do the examples make sense?
ping @bradzacher @JoshuaKGoldberg
> docs: Plugin flat config migration guide

- lib/rules/no-object-constructor.js
- tests/lib/rules/no-object-constructor.js
Node version: v20.8.0
npm version: v10.1.0
Local ESLint version: v8.51.0 (Currently used)
Global ESLint version: v8.51.0
Operating System: darwin 23.0.0
[ ] …
> fix: add preceding semicolon in suggestions of `no-object-constructor`

- docs/src/integrate/nodejs-api.md
- docs/src/use/command-line-interface.md
- docs/src/use/configure/configuration-files-new.md
- lib/linter/apply-disable-directives.js
- lib/options.js
- tests/lib/linter/apply-disable-directives.js
- tests/lib/linter/linter.js
This PR changes the core to also report unused `eslint-enable` comments when using the `report-unused-disable-directive` option.
This PR changes the core to also report unused `eslint-enable` comments when using the `report-unused-disable-directive` option.
An `eslint-enable comment` that does not unsuppress by an …
> feat: report-unused-disable-directive to report unused eslint-enable

- tests/lib/eslint/flat-eslint.js
Fixes FlatESLint tests for caching.
I noticed that some flat-eslint tests for caching were failing when run directly, in a clean clone of the repo.
To reproduce locally:
```bash
rm -r tmp
node node_modules/mocha/bin/_mocha tests/lib/eslint/flat-eslint.js
```
```
1) FlatESLint
lintFiles()
cache
should create the cache file inside …
```
> test: fix FlatESLint tests for caching

- docs/src/use/command-line-interface.md
- lib/cli.js
- package.json
1. Updated the CLI documentation to indicate which options are eslintrc-only.
1. Added an error message on the CLI when using flat config and there is a CLI option error that points to the documentation.
Fixes #17652
> docs: Add note about invalid CLI flags when using flat config.

- lib/rules/no-object-constructor.js
- tests/lib/rules/no-object-constructor.js
Node version: v21.0.0
npm version: v10.2.0
Local ESLint version: v8.52.0 (Currently used)
Global ESLint version: v8.52.0
Operating System: darwin 23.0.0
[ ] …
> fix: add `;` after JSX nodes in  `no-object-constructor` autofix

- docs/src/_includes/components/rule-categories.macro.html
- docs/src/use/core-concepts.md
Per the issue, added _Report Fixers_ and _Report Suggestions_ as sections in the _Core Concepts_ page. Also switched the _Rules_ page link about suggestions to point to the new core conception subheading instead of the custom rules docs.
Fixes https://github.com/eslint/eslint.org/issues/479.
I personally call them rule "reports" …
> docs: explained rule fixers and suggestions

- docs/.eleventy.js
- docs/src/rules/indent-legacy.md
- docs/src/rules/indent.md
- docs/src/rules/max-len.md
- docs/src/rules/no-mixed-spaces-and-tabs.md
- docs/src/rules/no-tabs.md
Fixes #17629
This PR updates the code examples in several rule documentation pages where tab characters are required to show how the rule works.
The approach used here consists in inserting tab characters where appropriate and wrapping the code blocks into `markdownlint-*` HTML comments, so that the tabs are not flagged or …
> docs: Fix tabs in rule examples

- bin/eslint.js
- tests/bin/eslint.js
- tests/fixtures/bin/eslint.config-promise-tick-throws.js
Currently, when an unhandled exception happens before the main task is completed, the main task overwrites the exit code, so there can be a scenario where eslint exits with zero (i.e., success) although there was an unhandled exception. 
Reproduction is [this test](https://github.com/eslint/eslint/blob/3aec1c55ba2c6d2833e1c0afe0a …
> fix: ensure that exit code for fatal errors is not overwritten

- lib/rules/no-prototype-builtins.js
- tests/lib/rules/no-prototype-builtins.js
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule proposal.md))
[ ] Changes an existing rule ([template (https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[x] Add autofix to a rule
Suggest a fix e.g. `a.hasOwnProperty(b) -> Object.prototype.hasOwnProperty.call(a, b)` according to the [`no-prototype-builtins` documentation](https://eslint.org/docs/latest/rules/no-prototype-builtins):
> To avoid subtle bugs like this, it’s better to always call these methods from `Object.prototype`. For example, …
> feat: Add suggestions for no-prototype-builtins

- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes `ESLint` class tests for the caching feature.
Same as https://github.com/eslint/eslint/pull/17658, just for the `ESLint` class.
> test: fix ESLint tests for caching

- docs/src/assets/scss/docs.scss
changed the position of return to top button in content page to avoid the overlapping of link buttons or other functional components of docs page.
for mobile or tab screen size the position is not changed.
Fixes #17646
> docs: change position of return to top button

- .github/renovate.json5
[x] Other, please explain: GitHub automation
Creates a `.github/renovate.json5` file based on:
* Discussion in https://github.com/eslint/eslint/issues/15726
* Docs in https://docs.renovatebot.com/configuration-options/#packagerules
* The existing typescript-eslint file at https://github.com/typescript-eslint/typescript-eslint/blob/7826910d8c6ba4d2d40b8d55f …
> chore: add .github/renovate.json5

- Makefile.js
- docs/src/library/link-card.md
- docs/src/rules/prefer-destructuring.md
- docs/src/rules/template-tag-spacing.md
- package.json
[x] Other, please explain: Dep upgrade
Fixes https://github.com/eslint/eslint/pull/17732
Upgrade `markdownlint` to the latest version
> chore: upgrade `markdownlint` to 0.31.1

- lib/rules/no-console.js
- tests/lib/rules/no-console.js
Fixes #17493
Added suggestions to the `no-console` rule. Added appropriate tests too.
Incorporated feedback from https://github.com/eslint/eslint/pull/17542#discussion_r1319839007.
> feat: Add suggestions to no-console

- docs/src/rules/for-direction.md
- lib/rules/for-direction.js
- tests/lib/rules/for-direction.js
- [for-direction rule](https://eslint.org/docs/latest/rules/for-direction)
```js
for (var i = 0; 10 > i; i--) {
}
for (var i = 0; 10 >= i; i--) {
}
for (var i = 10; 10 < i; i++) {
}
for (var i = 10; 0 <= i; i++) {
}
```
The `for-direction` rule checks **only** for the condition with the counter i.e. `i` on the **_left side_** of the binary expression `i < 10` like:
```js
for (var i = 0; i < 10; i++) {
}
``` 
The rule adds more warnings for …
> feat: for-direction rule add check for condition in reverse order

- lib/cli-engine/lint-result-cache.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes #13507
Updated `getCachedLintResults()` to return cloned lint results instead of the ones that `file-entry-cache` references. This should ensure that changes to these objects will not be accidentally stored in the cache file when `reconcile()` is called. 
* All 4 test cases (2 for the FlatESLint class, and 2 equivalent for …
> fix: Ensure that extra data is not accidentally stored in the cache file

- docs/src/rules/no-unused-vars.md
some examples inside the `correct` tag of `no-unused-vars` rule docs are showing errors, so just fixed them by adding some relevant code and updated the docs page a bit.
[Example1 in playground](https://eslint.org/play/#eyJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsic291cmNlVHlwZSI6Im1vZHVsZSJ9fSwidGV4dCI6Ii8qZXNsaW50IG5vLXVudXNlZC12YXJ …
> docs: update and fix examples for `no-unused-vars`

- docs/.eleventy.js
- docs/src/assets/scss/docs.scss
- docs/tools/markdown-it-rule-example.js
- tools/check-rule-examples.js
Closes #17602
This PR removes the "Open in Playground" buttons from examples code blocks in the docs of removed rules. Removed rules cannot be tested in the Playground.
> docs: remove "Open in Playground" buttons for removed rules

- tests/lib/cli.js
Several `cli` tests that were intended to run in both eslintrc and flat config modes were actually running in eslintrc mode twice due to hardcoded `false` as the return value of `shouldUseFlatConfig`.
Fixed those tests to run in both config modes.
> chore: fix several `cli` tests to run in the intended flat config mode

- docs/src/rules/no-restricted-imports.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
Added a new option in `no-restricted-imports` rule that enable to use regex pattern to restrict a particular import name that matches a given regex pattern.
Fixes #17303
> feat: importNamePattern option in no-restricted-imports

- lib/rules/no-promise-executor-return.js
- tests/lib/rules/no-promise-executor-return.js
Avoid producing the suggestion that is known to be invalid syntax, as invalid syntax in suggestions will no longer be allowed as a result of:
* https://github.com/eslint/eslint/pull/16639
Original code (flagged by rule):
```js
() => new Promise(() => function () {});
```
Suggestion (invalid syntax):
```js
() => new Promise(() => …
```
> fix: suggestion with invalid syntax in no-promise-executor-return rule

- README.md
In the section "Does Prettier replace ESLint", it was mentioned that ESLint has stylistic rules, however these rules have been [deprecated recently](https://eslint.org/blog/2023/10/deprecating-formatting-rules/).
> docs: remove mention about ESLint stylistic rules in readme

- docs/src/rules/capitalized-comments.md
- docs/src/rules/no-buffer-constructor.md
- docs/src/rules/no-implicit-globals.md
- docs/src/rules/strict.md
- lib/linter/config-comment-parser.js
- lib/linter/linter.js
- lib/source-code/source-code.js
- tests/fixtures/bad-examples.md
- tests/lib/linter/config-comment-parser.js
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
This PR hardens the validation of code examples in rule docs to ensure that each code block contains an inline configuration comment for the respective rule. Rules in code examples are enabled with configuration comments, so a code example without a configuration comment is likely a mistake.
In order to pass the build, I had to …
> docs: check config comments in rule examples

- docs/src/extend/ways-to-extend.md
Update ESLint Typescript Parser URL
> docs: update link in ways-to-extend.md

- .github/ISSUE_TEMPLATE/docs.yml
[x] Other, please explain: GitHub repository improvement
* Adds a `.github/ISSUE_TEMPLATE/docs.yml` issue template for a `documentation` issue
* Switches the sibling `change.yml` to use the 🚀  emoji, so to not intersect with the `docs.yml` 📝 
I asked in `#contributors` on Discord and was given a 👍 to throw together this PR: …
> chore: add GitHub issue template for docs issues

- lib/eslint/flat-eslint.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
Node version: v20.10.0
npm version: v10.2.3
Local ESLint version: Not found
Global ESLint version: v8.55.0
Operating System: linux 6.1.0-10-arm64
[ ] `@typescript-eslint/parser` …
> fix: `TypeError: fs.exists is not a function` on read-only file system

- docs/src/rules/no-restricted-properties.md
- lib/rules/no-restricted-properties.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-restricted-properties.js
Fixes: #16412
Added a function in ast-utils.js to get all the properties used in VariableDeclarator, AssignmentExpression, AssignmentPattern & ArrowFunctionExpression. Previously, it only used to get the 1st one. Sorry for https://github.com/eslint/eslint/pull/17804, I accidentally clicked the push button.
> feat: fix no-restricted-properties false negatives with unknown objects

- lib/config/flat-config-schema.js
- tests/lib/config/flat-config-schema.js
- tests/lib/eslint/flat-eslint.js
Fixes #17665
This PR fixes an issue that would cause a stack overflow when configuration `settings` or `parserOptions` contain a circular reference.
The fix uses a two-dimensional map in the `deepMerge` function to keep track of the results previously created when merging pairs of arguments. If the same pair of arguments is …
> fix: allow circular references in config

- lib/api.js
- lib/rule-tester/index.js
- tests/lib/api.js
Swap APIs.
This PR changes the `ESLint` and `RuleTester` exports to point to `FlatESLint` and `FlatRuleTester`, respectively. We will do the internal renaming in a separate PR.
Refs #13481
> feat!: Swap FlatESLint-ESLint, FlatRuleTester-RuleTester in API

- lib/config/flat-config-array.js
- tests/lib/config/flat-config-array.js
Fixes #17488
Removed support for `"eslint:recommended"` and `"eslint:all"` string configurations in flat config arrays.
Seems there are no changes in the docs needed as we removed the mention of string configs when we released the `@eslint/js` package.
> feat!: drop support for string configurations in flat config array

- docs/src/rules/no-invalid-regexp.md
- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
[x] Generate more warnings
[ ] Generate fewer warnings
[ ] Implement suggestions
[ ] A new option
[x] A new default behavior
[ ] Other
**Please provide some …
> feat!: `no-invalid-regexp` make allowConstructorFlags case-sensitive

- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- tests/fixtures/testers/rule-tester/suggestions.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Added logic to the two rule tester classes to assert that no suggestion contains the same hydrated description as a previous suggestion in the same error. 
Was the consensus for asserting on the rule's _actual_ reported suggestions or _expected_? I went with _actual_ to start because that feels more comprehensive. Relevant: …
> feat!: assert suggestion messages are unique in rule testers

- docs/src/extend/code-path-analysis.md
- lib/linter/code-path-analysis/code-path.js
- lib/rule-tester/flat-rule-tester.js
- lib/rule-tester/rule-tester.js
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Removed `CodePath#currentSegments` along with associated checks in `RuleTester` and `FlatRuleTester`. Also updates related documentation.
fixes #17457
> feat!: Remove CodePath#currentSegments

- lib/cli.js
- lib/eslint/flat-eslint.js
- tests/bin/eslint.js
- tests/lib/cli.js
- tests/lib/eslint/flat-eslint.js
Updates `shouldUseFlatConfig()` to return `true` unless the `ESLINT_USE_FLAT_CONFIG` environment variable is `"false"`.
Also ensures the CLI emits a warning when eslintrc is used.
Refs #13481
> feat!: Update shouldUseFlatConfig and CLI so flat config is default

- tests/lib/cli.js
Fix unit tests.
The test suite for `cli.execute` in  `tests/lib/cli.js` is defined twice, once for eslintrc and once for flat config:
https://github.com/eslint/eslint/blob/0dd9704c4751e1cd02039f7d6485fee09bbccbf6/tests/lib/cli.js#L110
This PR updates the test logic so that when the tests run in flat config mode, `FlatESLint` is …
> test: ensure that CLI tests run with FlatESLint

- docs/src/rules/max-lines.md
updated the `max-lines` docs to count the eslint directive comments in the correct/incorrect example too.
Fixes #17830
> docs: updated examples of `max-lines` rule

- lib/linter/config-comment-parser.js
- lib/linter/linter.js
- lib/source-code/source-code.js
- tests/lib/linter/linter.js
- tests/lib/source-code/source-code.js
Parsing 'exported' comment using parseListConfig.
Fixes https://github.com/eslint/eslint/issues/17622.
In the [docs](https://eslint.org/docs/latest/rules/no-unused-vars#exported), only information about the name entries.
However, when processing `/* exported */` comments, Linter uses `parseStringConfig` function, making it …
> fix!: Parsing 'exported' comment using parseListConfig

- tests/lib/linter/linter.js
Fixes recently committed tests that were still using now-removed `context.getScope()`.
`context.getScope` -> `context.sourceCode.getScope`
> chore: fix getting scope in tests

- packages/eslint-config-eslint/base.js
- packages/eslint-config-eslint/eslintrc.js
[x] Other, please explain: Change eslint-config-eslint
Avoid breaking the list being in the JSDoc comment below. 
```js
/**
* The method does 2 things:
* * Thing 1
* * Thing 2
*/
const x = () => {}
```
ref https://github.com/eslint/eslint-github-bot/pull/201#discussion_r1434588743
> chore: use jsdoc/no-multi-asterisks with allowWhitespace: true

- lib/cli-engine/cli-engine.js
- lib/linter/linter.js
- lib/rule-tester/rule-tester.js
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/linter/code-path-analysis/code-path.js
- tests/lib/linter/linter.js
- tests/lib/linter/rules.js
- tests/lib/rules/utils/ast-utils.js
- tests/lib/shared/config-validator.js
- tests/lib/source-code/source-code.js
- tests/tools/eslint-fuzzer.js
- tools/fuzzer-runner.js
Made flat config mode the default for `Linter` and updated associated code.
Refs #13481
> feat!: Switch Linter to flat config by default

- tests/lib/linter/linter.js
In the Linter tests, I removed one `linter = new Linter()` line. This line creates an instance that ends up being unused because the variable is later assigned a new instance in [`beforeEach`](https://github.com/eslint/eslint/blob/3826cdf89294d079be037a9ab30b7506077b26ac/tests/lib/linter/linter.js#L61-L63). It just causes …
> chore: remove creating an unused instance of Linter in tests

- docs/src/extend/custom-processors-deprecated.md
- docs/src/extend/custom-processors.md
- docs/src/extend/plugin-migration-flat-config.md
- docs/src/extend/plugins.md
- docs/src/use/configure/migration-guide.md
Updated the plugin documentation to be the correct format for flat config.
Refs #13481
Did I miss anything?
> docs: Update Create a Plugin for flat config

- docs/src/use/index.md
- docs/src/use/migrate-to-9.0.0.md
Updates the Migrate to v9.x document to include changes made in https://github.com/eslint/eslint/commit/60dea3e3abd6c0b6aab25437b2d0501b0d30b70c
* Added `no-new-native-nonconstructor` to the list of rules that have been enabled in `eslint:recommended`, and `no-new-symbol` to the list of rules that have been removed from …
> docs: update `eslint:recommended` section in Migrate to v9.x

- docs/.eleventy.js
- package.json
- packages/eslint-config-eslint/package.json
Recently released eslint-plugin-n v16.6.0 has added some new globals, including `btoa`, and our CI is now failing because `no-redeclare` reports an error on a `/* global btoa */` comment. This fixes the lint error.
* Fixed the lint error by removing the `/* global btoa */` comment.
* Updated package.json to make sure everyone …
> chore: upgrade eslint-plugin-n@16.6.0

- docs/src/use/migrate-to-9.0.0.md
Adds details about https://github.com/eslint/eslint/commit/fb81b1cb78d2692a87fd3591fdc0f96b0c95e760 to the v9 migration guide.
Added following sections:
* Function-style rules are no longer supported
* `meta.schema` is required for rules with options
> docs: add function-style and `meta.schema` changes to v9 migration guide

- docs/src/_data/rules.json
- docs/src/_data/rules_meta.json
- lib/rules/no-inner-declarations.js
- packages/eslint-config-eslint/base.js
- packages/eslint-config-eslint/eslintrc.js
- packages/js/src/configs/eslint-recommended.js
Refs #15576
Removed  `no-inner-declarations` rule from the `eslint:recommended` configuration.
I also ran the script to update rules data files for the docs site, to include all recent changes.
> feat!: remove `no-inner-declarations` from `eslint:recommended`

- docs/src/integrate/nodejs-api.md
- lib/eslint/eslint-helpers.js
- lib/eslint/eslint.js
- tests/_utils/test-lazy-loading-rules.js
- tests/lib/eslint/legacy-eslint.js
Follow up to https://github.com/eslint/eslint/pull/17914, makes a few more updates.
* Added and removed some constructor options in the API docs.
* Fixed a few tests and comments.
* Updated debug namespace in the ESLint class module.
> docs: update API docs

- lib/config/flat-config-schema.js
- tests/lib/config/flat-config-schema.js
Fixes #17820
Node version: v21.5.0
npm version: v10.2.4
Local ESLint version: v8.56.0 (Currently used)
Operating System: darwin 23.1.0
[ ] …
> fix: deep merge behavior in flat config

- docs/src/use/migrate-to-9.0.0.md
Updated the "Migrate to v9" guide to include `RuleTester` changes.
> docs: Add RuleTester changes to migrate to v9 guide

- docs/src/use/migrate-to-9.0.0.md
Added sections to the migration guide for:
- `/* exported */` parsing
- dropping support for string configs in flat config
> docs: Add exported and string config notes to migrate to v9 guide

- docs/src/_data/config.json
- docs/src/_data/eslintVersion.js
- docs/tools/validate-links.js
Enables `NEXT` in version selectors.
* Set `config.showNextVersion` to `true` to enable `NEXT` in version selectors (see https://github.com/eslint/eslint/commit/66694136b67277c050bd27f60050779687a88c9f).
* Updated `eslintVersion` to read from `config.version`, because `pkg.version` will soon become `9.0.0-alpha.0`.
* If we merge …
> docs: show `NEXT` in version selectors

- .github/workflows/ci.yml
- .github/workflows/update-readme.yml
Temporary solution for prerelease versions
Prerelease versions of `eslint` will likely need to be installed using `npm install --force`, because some of the dependencies and dev dependencies have `eslint` as a peer dependency, and prereleases most likely won't satisfy those range constraints.
I prepared this so that we can …
> ci: use `--force` flag when installing eslint

- docs/src/_data/config.json
This intentionally targets the `latest`  branch.
Enables `NEXT` in version selectors on https://eslint.org/docs/latest/
Set `config.showNextVersion` to `true`.
This should be merged after we finish `v9.0.0-alpha.0` release.
> docs: show NEXT in version selectors on the `latest` branch

- docs/package.json
Remove an unused dependency.
This PR removes rimraf as a dev dependency from docs/package.json.
I noticed that rimraf is showing up on the [Renovate dashboard](https://github.com/eslint/eslint/issues/17733) as pending update, but it's apparently not used anywhere.
Feel free to close this PR if rimraf is still being used in a way …
> chore: remove unused dependency rimraf

- docs/src/integrate/nodejs-api.md
- docs/src/use/migrate-to-9.0.0.md
Updates Linter API for v9.
* Updated Linter API in the Node.js API Reference document.
* Added Linter API changes to the v9 migration guide.
> docs: Update Linter API for v9

- Makefile.js
Fixes our release process to update docs files when publishing prereleases, the same as when publishing regular releases.
https://github.com/eslint/eslint/issues/17883#issuecomment-1872420068 
https://github.com/eslint/eslint/issues/17893#issuecomment-1873327372
Merged prerelease-specific logic from `function generatePrerelease` …
> build: update docs files when publishing prereleases

- docs/src/use/configure/migration-guide.md
Updated the config migration guide to explain why CLI flags were removed and what to use instead.
> docs: Update removed CLI flags migration

- docs/src/use/migrate-to-9.0.0.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes #17381
Updated `Linter` to align the behavior of `/* eslint */` rule configuration comments with the way rule configs are merged in the config array. In particular, a configuration comment with only severity should retain options from the config.
I updated the v9 migration guide, but this should be also described somewhere …
> fix!: configuration comments with just severity should retain options

- docs/src/rules/no-unused-vars.md
- docs/src/use/migrate-to-9.0.0.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
* **Node version: 21.1.0**
* **npm version: 10.2.0**
* **Local ESLint version: latest**
* **Global ESLint version: latest**
* **Operating System: windows**
[ ] …
> fix!: no-unused-vars `varsIgnorePattern` behavior with catch arguments

- package.json
- tests/lib/rules/no-eval.js
- tests/lib/rules/no-undef.js
- tests/lib/rules/no-use-before-define.js
Upgrades eslint-scope to include https://github.com/eslint/eslint-scope/pull/116 and https://github.com/eslint/eslint-scope/pull/118.
Updated package.json and added a few tests that show different behavior of some rules with eslint-scope v8 (the tests would fail with eslint-scope v7).
Marked as draft because it currently uses …
> fix!: upgrade eslint-scope@8.0.0

- docs/src/use/migrate-to-9.0.0.md
Adds `context.getAncestors()`, `context.getDeclaredVariables()`, `context.getScope()`, and `context.markVariableAsUsed()` to the  v9 migration guide in the "Removed multiple context methods" section.
Updated v9 migration guide.
> docs: Add more removed `context` methods to migrate to v9 guide

- docs/src/use/migrate-to-9.0.0.md
- lib/cli.js
- tests/lib/cli.js
Fixes https://github.com/eslint/eslint/issues/17660
No
> fix!: handle `--output-file` for empty output when saving to disk

- docs/src/extend/custom-rules.md
Fixes https://github.com/eslint/eslint/issues/17968
In the section https://eslint.org/docs/latest/extend/custom-rules#accessing-code-paths, the number of code-path events is incorrectly stated as five. I have changed it to seven.
> docs: fix number of code-path events on custom rules page

- lib/rules/no-misleading-character-class.js
- tests/lib/rules/no-misleading-character-class.js
> fix: `no-misleading-character-class` edge cases with granular errors

- conf/ecma-version.js
- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes #15366
I added configuration for the latest ECMAScript version to ESLint and updated Linter to use it instead of `espree.latestEcmaVersion` when resolving `"latest"` value of `languageOptions.ecmaVersion`.
I didn't change the eslintrc logic:
https://github.com/eslint/eslint/blob/95075251fb3ce35aaf7eadbd1d0a737106c13ec6/lib/ …
> feat: maintain latest ecma version in ESLint

- docs/src/use/migrate-to-9.0.0.md
added entry in v9 migration guide for the changes in `no-inner-declarations` rule.
Comment of issue [17855](https://github.com/eslint/eslint/pull/17885#pullrequestreview-1811819229)
> docs: migration guide entry for `no-inner-declarations`

- docs/src/use/configure/plugins.md
Added documentation on how to load plugins from local files and how to create a virtual plugin to load a specific rule from disk.
Is this clear?
> docs: Add sections on non-npm plugin configuration

- README.md
- Updated README.md to clarify that ECMAScript 2024 is the default (in the new config system) and support is ongoing until the spec is finalized.
- Removed mention about environments, not relevant for the new config.
> docs: Update note about ECMAScript support

- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Fixes https://github.com/eslint/eslint/issues/17962
No
> fix: handle absoulte file paths in `RuleTester`

- docs/src/rules/valid-typeof.md
the usual structure of rules docs file is -- rule details < examples < options < option name < examples.
changed the `valid-typeof` rule docs to follow the same. and changed it's options description a bit.
> docs: update valid-typeof rule

- docs/src/rules/sort-keys.md
Currently the options listing for `sort-keys` says there are 3 properties, however this is not accurate. I have updated this to be generic so it does not have to be modified if new properties are added.
It appears that the 4th property `allowLineSeparatedGroups` was added via https://github.com/eslint/eslint/pull/16138 & relates …
> docs: Update sort-keys options properties count

- docs/src/use/migrate-to-9.0.0.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
Fixes #15261
Updated `no-restricted-imports` to check all config entries that have a matching `name` instead of checking just the last one.
Matching entries produce errors separately from each other. I believe this is the simplest yet the most flexible solution, but a downside may be that in some cases the rule produces multiple …
> feat!: no-restricted-imports allow multiple config entries for same path

- lib/linter/code-path-analysis/code-path.js
- lib/rules/no-this-before-super.js
- tests/lib/linter/code-path-analysis/code-path.js
- tests/lib/rules/no-this-before-super.js
Fixes #17605
This PR fixes some false negatives in the no-this-before-super rule.
> feat: fix false negatives in `no-this-before-super`

- .github/workflows/ci.yml
- docs/.eleventy.js
- package.json
- packages/eslint-config-eslint/package.json
This PR intentionally targets the `v8.x` branch.
Enables CI for the `v8.x` branch.
Updated `ci.yml`.
> ci: Enable CI for `v8.x` branch

- docs/src/extend/custom-rules.md
Clarify the difference between how rule `meta.docs` properties are used for core rules and custom rules.
This just tweaks the wording to clarify how these properties are used today.
Semi-related issue: https://github.com/eslint/eslint/issues/17842
> docs: tweak explanation for meta.docs rule properties

- docs/src/rules/no-unused-vars.md
- docs/src/use/migrate-to-9.0.0.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Changes the default value for the `no-unused-vars` rule's `caughtErrors` option from `"none"` to `"all"`.
Fixes #17974.
> feat!: `no-unused-vars` default caughtErrors to 'all'

- package.json
- tests/bin/eslint.js
- tests/fixtures/bin/eslint.config-invalid-key.js
- tests/lib/config/flat-config-array.js
Refs https://github.com/eslint/eslint/issues/17966, backport https://github.com/eslint/eslint/pull/17980 to v8
No
> fix: Ensure config keys are printed for config errors

- lib/rule-tester/flat-rule-tester.js
- tests/lib/rule-tester/flat-rule-tester.js
Refs https://github.com/eslint/eslint/issues/17966, backports fix for https://github.com/eslint/eslint/issues/17989 to v8.
No
> fix: handle absolute file paths in `FlatRuleTester`

- docs/src/rules/no-useless-computed-key.md
- docs/src/use/migrate-to-9.0.0.md
- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
Fixes #18042
This PR changes the default value of the `enforceForClassMembers` option in the `no-useless-computed-key` rule to `true`.
Since this is a breaking change in v9, I've updated the migration guide.
> feat!: default for `enforceForClassMembers` in `no-useless-computed-key`

- docs/src/extend/custom-rules.md
Fixes #18069
- Add docs for `languageOptions`
- Mark `parserPath` as removed
- Mark the root `parserOptions` as deprecated
No
> docs: document languageOptions and other v9 changes for context

- docs/src/use/command-line-interface.md
Update the `--fix` CLI doc to link to the core concept doc on fixability.
Ideally, one doc on a topic links to the other docs on the same topic, so users can find all relevant context.
* https://eslint.org/docs/latest/use/command-line-interface#--fix
* https://eslint.org/docs/latest/use/core-concepts#rule-fixes
Inspired by:
* …
> docs: link from `--fix` CLI doc to the relevant core concept

- docs/src/rules/lines-around-comment.md
- tests/fixtures/bad-examples.md
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
Node version: v21.6.0
npm version: v10.2.4
Local ESLint version: v9.0.0-alpha.2 (Currently used)
Operating System: darwin 23.3.0
[ ] …
> docs: fix malformed `eslint` config comments in rule examples

- docs/src/integrate/nodejs-api.md
- lib/api.js
- lib/eslint/eslint.js
- lib/eslint/legacy-eslint.js
- tests/lib/api.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/legacy-eslint.js
- Added the `loadESLint()` method to the public API.
- Added `configType` to both `ESLint` and `LegacyESLint`.
- Added tests for all of the above.
- Added docs to the Node.js API document.
refs #18075
closes #18088
> feat: Add loadESLint() API method for v9

- docs/src/use/migrate-to-9.0.0.md
- lib/linter/index.js
- lib/linter/interpolate.js
- lib/linter/report-translator.js
- lib/rule-tester/rule-tester.js
- tests/fixtures/testers/rule-tester/messageId.js
- tests/fixtures/testers/rule-tester/suggestions.js
- tests/lib/linter/interpolate.js
- tests/lib/rule-tester/rule-tester.js
[x] Other, please explain: Rule Tester
Fixes #18016.
Added a check for errors and suggestions which provide a `messageId` but not specify a `data` property.
This check makes sure that the replaced message has no placeholders as the required `data` properties were provided.
- I copied the regular expression from `interpolate.js`; maybe the regular …
> feat!: Rule Tester checks for missing placeholder data in the message

- docs/src/integrate/nodejs-api.md
- lib/api.js
- lib/eslint/eslint.js
- lib/eslint/flat-eslint.js
- tests/lib/api.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/flat-eslint.js
**Note:** Intentionally sent to v8.x branch.
- Added the `loadESLint()` method to the public API.
- Updated the `shouldUseFlatConfig()` function accept an optional `cwd` argument.
- Added `configType` to both `ESLint` and `FlatESLint`.
- Added tests for all of the above.
- Added docs to the Node.js API document.
refs #18075
> feat: Add loadESLint() API method for v8

- docs/src/rules/func-name-matching.md
- docs/src/rules/lines-around-comment.md
- tests/fixtures/bad-examples.md
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
Multiple rule configuration comments in the same example may lead to the conclusion that it is possible to reconfigure the rule for a part of the code, which is not true because the last comment applies to the entire code.
* Updated `tools/check-rule-examples.js` to disallow multiple rule configuration comments.
* Updated …
> docs: Disallow multiple rule configuration comments in the same example

- packages/eslint-config-eslint/README.md
- packages/eslint-config-eslint/package.json
Refs https://github.com/eslint/eslint.org/pull/512#discussion_r1481031901
Adds `base` export in the `eslint-config-eslint` package.
Configs exported from the main and cjs entry points are intended for files that run in Node.js, and therefore cannot be readily used for files that don't run in Node.js, like browser scripts or …
> chore: export `base` config from `eslint-config-eslint`

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
[x] Other, please explain: 
Fix https://github.com/eslint/eslint/issues/16620
> [Notes regarding `pull_request_target` event](https://github.com/actions/labeler?tab=readme-ov-file#notes-regarding-pull_request_target-event). It requires the workflow file to be present at the main branch.
For testing purposes, you can play create PRs in my forked repo - …
> ci: add PR labeler action

- README.md
Fix spelling: `diffent` -> `different`.
> chore: fix spelling mistake in README.md

- docs/package.json
- docs/src/_data/eslintNextVersion.js
- docs/src/_includes/components/nav-version-switcher.html
- docs/src/_includes/components/version-switcher.html
- docs/src/_includes/partials/versions-list.html
Ensured that the version number is displayed instead of NEXT in the dropdown on the docs site. This is accomplished by either reading the version locally (on the `next` branch) or fetching the version from GitHub.
fixes #17943
I'm pulling the `package.json` from the `next` branch, but wasn't sure if it should be `main`. I don't …
> docs: Show prerelease version in dropdown

- docs/src/integrate/nodejs-api.md
Removed an obsolete reference to .eslintignore in the documentation of the `ESLint` constructor options.
> docs: fix `ignore` option docs

- lib/eslint/eslint.js
- tests/lib/eslint/eslint.js
Fixes #17621
This PR adds functionality in `ESLint.#lintFiles()` to cancel parallel tasks after an error occurs. The tasks spawn by `Promise.all()` contain only one asynchronous operation, which is the file access by `readFile`, where each task reads a different file. If an error occurs in one of the tasks, the other pending …
> fix: stop linting files after an error

- docs/src/rules/no-fallthrough.md
`no-fallthrough` rule docs says
>By default, this rule does not require a fallthrough comment after an empty case only if the empty case and the next case are on the same line or on consecutive lines.
docs already has an example with `consecutive lines` and this PR adds the example with the `same line` condition.
> docs: add inline cases condition in `no-fallthrough`

- docs/src/rules/complexity.md
- lib/rules/complexity.js
- tests/lib/rules/complexity.js
Fixes: #18060
In addition to the existing patterns that increase complexity I’ve added the following:
* `ChainExpression` to increase the complexity by one for every optional chain expression that is encountered
* `AssignmentPattern` to increase the complexity by one for every default value assignment in function parameters or …
> feat: update complexity rule for optional chaining & default values

- lib/config/rule-validator.js
- tests/lib/config/flat-config-array.js
Fix https://github.com/eslint/eslint/issues/17364
NA
> fix: improve error message for invalid rule config

- docs/src/use/migrate-to-9.0.0.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes https://github.com/eslint/eslint/issues/18132
Updated code that processes `/*eslint*/` comments (both in flat and eslintrc modes) to check if the rule has already been configured by another comment. In that case, the previous comment still applies, while the duplicate is reported as a lint error.
This doesn't cover cases …
> feat!: disallow multiple configuration comments for same rule

- CONTRIBUTING.md
Updated a link on the Contributing page. [HackerOne](https://hackerone.com/eslint) is no longer accepting submissions and security vulnerabilities should be reported using a GitHub advisory form, so I replaced the link to HackerOne with the link to open a GitHub advisory.
Alternatively, we could point users to the relevant …
> docs: replace HackerOne link with GitHub advisory

- docs/src/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
`no-unused-vars`
[x] Generate fewer warnings
[ ] Implement suggestions
[x] A new option
[ ] A …
> feat: add `ignoreClassWithStaticInitBlock` option to `no-unused-vars`

- eslint.config.js
- tests/lib/rules/no-invalid-this.js
Refs https://github.com/eslint/eslint/issues/18160
Removes uses of `lodash.merge` in non-production code.
Replaced use of `lodash.merge` with other methods in `eslint.config.js` of this project and tests for the `no-invalid-this` rule.
> chore: Remove some uses of `lodash.merge`

- docs/src/extend/plugins.md
- lib/cli.js
- tests/fixtures/plugins/node_modules/@scope/eslint-plugin-example.js
- tests/fixtures/plugins/node_modules/eslint-plugin-hello-cjs/index.js
- tests/fixtures/plugins/node_modules/eslint-plugin-hello-cjs/package.json
- tests/fixtures/plugins/node_modules/eslint-plugin-hello-esm/index.js
- tests/fixtures/plugins/node_modules/eslint-plugin-hello-esm/package.json
- tests/fixtures/plugins/node_modules/eslint-plugin-no-default-export/index.js
- tests/fixtures/plugins/node_modules/eslint-plugin-no-default-export/package.json
- tests/lib/cli.js
Fixes #18159 
The changes in this PR relate to how the CLI option `--plugin` works in flat config mode:
* When a plugin is loaded, the `default` property of the imported module is now used. This aligns the plugin loading behavior with eslintrc and with the recommendations for creating a custom plugin.
* A specific error message …
> fix: load plugins in the CLI in flat config mode

- docs/src/rules/no-fallthrough.md
- lib/rules/no-fallthrough.js
- tests/lib/rules/no-fallthrough.js
fixes #18182
https://github.com/eslint/eslint/issues/18182
Add option (disabled by default) to report unused fallthrough comments in no-fallthrough.
Changes are pretty straightforward I think.
PS this is my first PR to ESLint! very exciting
> feat: add `reportUnusedFallthroughComment` option to no-fallthrough rule

- CHANGELOG.md
- tests/bin/eslint.js
> chore: fix some comments

- docs/tools/prism-eslint-hook.js
This PR fixes an issue in the docs build process that is causing some incorrect rule examples in the `indent` and `indent-legacy` rules to be displayed without red markers for errors, for example [here](https://eslint.org/docs/next/rules/indent#functiondeclaration).
This is due to a `TypeError` that occurs because of an …
> build: fix TypeError in prism-eslint-hooks.js

- docs/src/use/migrate-to-9.0.0.md
- lib/linter/code-path-analysis/code-path-analyzer.js
- lib/linter/linter.js
- lib/rules/constructor-super.js
- lib/rules/no-this-before-super.js
- lib/rules/no-useless-return.js
- lib/source-code/source-code.js
- tests/lib/linter/linter.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/no-useless-return.js
- Moved AST traversal out of `Linter` and into `SourceCode#traverse()`. 
- Updated `no-useless-returns`, `constructor-super`, and `no-this-before-super` to they still work. These rules were also tested against v8.57.0 to ensure that such changes would be backwards compatible.
- Updated the v9 migration guide
Refs #16999 
I …
> feat!: move AST traversal into SourceCode

- docs/src/rules/sort-imports.md
---
Made 4 test cases of the below. It could be more straightforward.
```
incorrect with default option ignore false
correct   with default option ignore false
correct   with ignore true
incorrect with ignore true
```
- ignoreCase
- ignoreDeclarationSort
- ignoreMemberSort
- Should be checked whether test cases are correct.
> docs: Clarify the description of `sort-imports` options

- docs/src/rules/use-isnan.md
- lib/rules/use-isnan.js
- tests/lib/rules/use-isnan.js
made the rule `use-isnan` to report NaN in `indexOf` and `lastIndexOf` with fromIndex
now rule will report following code-
```js
var foo = myArray.indexOf(NaN, 1);
var bar = myArray.lastIndexOf(NaN, 1);
```
Fixes: #18161
> feat: use-isnan report NaN in `indexOf` and `lastIndexOf` with fromIndex

- lib/rules/constructor-super.js
- tests/lib/rules/constructor-super.js
* **Node version:** 20.9.0
* **npm version:** 10.2.0
* **Local ESLint version:** v9.0.0-rc.0
* **Global ESLint version:** no
[ ] …
> fix: `constructor-super` false positives with loops

- Makefile.js
- package.json
<s>Re-enabled WebdriverIO tests.</s> Added npm script `test:wdio` to run the WebdriverIO test locally.
WebdriverIO has been running smoothly in CI for the last couple of months. Shall we try to re-enable it for tests in Jenkins? Or maybe just for local tests?
> chore: add npm script to run WebdriverIO test

- docs/src/rules/strict.md
- tests/fixtures/bad-examples.md
- tests/fixtures/good-examples.md
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
While testing https://github.com/eslint/eslint.org/pull/509, I noticed that one example for the `strict` rule has `"ecmaVersion": 6` in the configuration. This works mostly well because `6` is an alias for `2015`, but when the example is opened in the Playground, nothing is selected in the ECMA Version list:
1. Updated the …
> docs: fix `ecmaVersion` in one example, add checks

- docs/src/use/configure/configuration-files.md
added the information that flat config doesn't ignore files or directories with name starts from dot.
some issue had been opened that mentions this #18214 and #18236
> docs: add info about dot files and dir in flat config

- docs/src/use/migrate-to-9.0.0.md
- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
The Json schema of the camelCase rule validate that the first element is a string instead of validating that it's an array of string
Correct the Json Schema
Nope
> fix!: correct `camelcase` rule schema for `allow` option

- package.json
Updated `@humanwhocodes/config-array` so that we see config names in config validations errors.
fixes #18231
refs #18252
> feat: Show config names in error messages

- docs/src/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
`no-unused-vars`
Example 1:
```js
/* eslint no-unused-vars: ["error", { "varsIgnorePattern": "^_" }] */
const _a = 5;
const _b = _a + 5
```
Example 2:
```js
/* eslint no-unused-vars: ["error", { "argsIgnorePattern": "^_" }] */
function foo(_a) {
return _a + 5
}
```
Example 3:
```js
/* eslint no-unused-vars: ["error", { "destructuredArrayIgnorePattern": "^_" }] */
const [ a, _b ] = items;
console.log(a + _b);
```
Example 4:
```js
/* eslint no-unused-vars: ["error", { "caughtErrorsIgnorePattern": "^_" }] */
try {}
catch(_err) { …
```
> feat: Add `reportUsedIgnorePattern` option to `no-unused-vars` rule

- lib/source-code/token-store/backward-token-cursor.js
- lib/source-code/token-store/cursors.js
- lib/source-code/token-store/forward-token-comment-cursor.js
- lib/source-code/token-store/forward-token-cursor.js
- package.json
After adding support for `exports.key = value` (next to `module.exports`), [Knip's integration tests against ESLint](https://github.com/webpro/knip/actions/runs/8565238201/job/23473008829) failed, since the ESLint codebase contains a few instances of `exports` (without `module.`) that are written in the ambiguous CommonJS style …
> chore: upgrade knip

- lib/rules/no-lone-blocks.js
- tests/fixtures/parsers/typescript-parsers/no-lone-blocks/await-using.js
- tests/fixtures/parsers/typescript-parsers/no-lone-blocks/using.js
- tests/lib/rules/no-lone-blocks.js
Made a trivial change that future-proofs `no-lone-block` for declaration kinds other than `var`, `let`, and `const`. (namely, adds tests for `using` and `await using`, but should be compatible with any kind of VariableDeclaration cooked up in the future).
fixes https://github.com/eslint/eslint/issues/18204
> fix: Support `using` declarations in no-lone-blocks

- bin/eslint.js
- docs/src/use/command-line-interface.md
- docs/src/use/configure/configuration-files.md
- lib/options.js
- tests/lib/options.js
Added the `--inspect-config` CLI flag only in flat config mode. I also updated the docs and relevant tests.
I updated the CLI docs to use the flag config output.
It looks like we don't have any real tests for the functionality like `--init`, so I opted not to add any for this either.
fixes #18255
> feat: Add --inspect-config CLI flag

- docs/src/use/command-line-interface.md
Added eslintrc-only note to `--rulesdir` copied from other args deprecated as of v9
Fixes potential confusion for pre-v9 users who bumped and use invalid args similar to #18280 (also probably a good idea to indicate to users who bumped that eslintrc is not even supported anymore in error msg if eslintrc was being used)
> docs: add eslintrc-only note to `--rulesdir`

- .github/workflows/ci.yml
- .github/workflows/docs-ci.yml
- .github/workflows/update-readme.yml
- docs/netlify.toml
Update the build process
Updated CI workflows and Netlify build to not use the `--force` flag when running `npm install`.
The `--force` flag was added in #17921 to allow installing prerealeses. Not that v9.0.0 final has been released, the flag should be no longer needed.
> build: do not use `--force` flag to install dependencies

- docs/src/rules/linebreak-style.md
- docs/tools/code-block-utils.js
This PR fixes an issue in the examples of the `linebreak-style` rule, which are supposed to show the differences between Unix style LF line breaks vs. Windows style CRLF line breaks.
Because of our [.gitattributes](https://github.com/eslint/eslint/blob/v9.0.0-rc.0/.gitattributes) repo settings, CRLF line breaks are converted to …
> docs: fix `linebreak-style` examples

- packages/eslint-config-eslint/base.js
- packages/eslint-config-eslint/package.json
Replaces `eslint-plugin-eslint-comments` with the latest version of `@eslint-community/eslint-plugin-eslint-comments` which provides a flat config export.
Updated `eslint-config-eslint`.
> chore: @eslint-community/eslint-plugin-eslint-comments v4.3.0

- docs/src/use/command-line-interface.md
- lib/options.js
Updated descriptions of the `--ignore-pattern` CLI flag to clarify that `.eslintignore` only applies in eslintrc mode. In the new config system, ignore patterns are defined in the config.
> docs: indicate eslintrc mode for `.eslintignore`

- conf/globals.js
see the discussion: https://github.com/sindresorhus/globals/pull/213#issue-2142294092
In eslintrc, eslint was using the npm package `globals`. However, in the new config (aka flat config) eslint does not rely on `globals` but maintains its own es globals.
In the newly released globals v15. it moved the `Intl` from …
> feat: add `Intl` in es6 globals

- docs/src/_data/eslintVersions.js
- docs/src/_data/helpers.js
- docs/src/_data/layout.js
- docs/src/_data/rules_categories.js
- docs/src/_data/site.js
- eslint.config.js
Includes `docs/src/_data` files in js linting.
Updated ignore patterns in `eslint.config.js` to not ignore files in `docs/src/_data`, and fixed reported lint errors in those files.
> chore: lint `docs/src/_data` js files

- bin/eslint.js
- lib/cli.js
- lib/eslint/eslint.js
- tests/lib/cli.js
Environment Info:
Node version: v20.11.0
npm version: v10.4.0
Local ESLint version: v9.0.0 (Currently used) 
Operating System: win32 10.0.19045
Espree
1. Ran `--inspect-config` using `.eslintrc.js`
2. Ran `--inspect-config` with `-c other.config.js`
1. ESLint should report an error and not open …
> fix: --inspect-config only for flat config and respect -c

- .github/workflows/ci.yml
- .gitignore
- lib/eslint/eslint.js
- package.json
- tests/fixtures/emfile/eslint.config.js
- tools/check-emfile-handling.js
File read operations that throw an EMFILE or ENFILE error will be automatically retried.
I also added a test that runs only in CI to save us time locally. There was an error with the abort handling that I had to fix in order to make the test pass.
fixes #18301
> fix: EMFILE errors

- lib/linter/apply-disable-directives.js
- lib/linter/linter.js
- lib/source-code/source-code.js
- tests/lib/linter/apply-disable-directives.js
Refactor
Continues the work on implementing language plugins by moving directive gathering into `SourceCode`. The changes here primarily affect the flat config path.
I also renamed parts of directive processing to better reflect the reality that some languages might not use comments for directives and instead use actual syntax, …
> refactor: Move directive gathering to SourceCode

- docs/src/rules/no-constant-condition.md
- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
`no-constant-condition`
[x] Generate fewer warnings
[ ] Implement suggestions
[ ] A new …
> feat: allow `while(true)` in `no-constant-condition`

- docs/src/use/configure/migration-guide.md
I'm trying to not get too much frustrated with the migration & migration guides.. so I thought I could contribute on the issues I have faced, hopefully they're welcome 🙏 
Added a note about the required instalation of the `globals` package (docs don't [make it clear that globals is not a magic …
> docs: include notes about globals in migration-guide

- lib/shared/string-utils.js
- package.json
[X] Other, please explain: replace a dependency with a native implementation.
See the discussion in #17835
Fixes #17835
Replaced [graphemer](https://www.npmjs.com/package/graphemer) with the native [`Segments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/segment/Segments) implementation provided by …
> feat: replace dependency graphemer with `Intl.Segmenter`

- lib/eslint/eslint-helpers.js
- tests/lib/eslint/eslint.js
Fixes #18250
I replaced [`util.promisify`](https://github.com/eslint/eslint/compare/issue-18250?expand=1#diff-87d53094b12d82e4c11a0e1167d79cf2f471d2f5e5ebb6fc483e891f9dc87a5aL27) around `fs.walk` with a plain promise. In this way, the promise can be rejected not only when the implicit callback provided by `util.promisify` …
> fix: do not crash on error in `fs.walk` filter

- lib/config/flat-config-array.js
- package.json
- tests/lib/config/flat-config-array.js
Upgraded `@humanwhocodes/config-array` to include new error details, then updated `FlatConfigArray` to use that info to produce an error message containing the index of the config that caused the error.
fixes #18259
I used the terms "original", "base", and "user-defined" to differentiate between the different parts of the config …
> feat: Provide helpful error message for nullish configs

- README.md
- bin/eslint.js
- docs/src/use/getting-started.md
- messages/no-config-found.js
refs: https://github.com/eslint/eslint/issues/18369, https://github.com/eslint/eslint/discussions/18361,
We've received a few reports generated configs seem to be eslintrc format, so I've updated the documentation to use the latest version.
> fix: use @eslint/create-config latest

- lib/linter/linter.js
- lib/source-code/source-code.js
- tests/lib/linter/linter.js
It replaced {} with `Object.create(null)` to avoid accessing properties on the `Object prototype`.
fixes #18363
[ x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
Not sure if I should write a test for eslintrc as well: it's deprecated and will eventually be removed.
> fix: do not throw when defining a global named __defineSetter__

- docs/src/rules/no-eval.md
Unless you already know about indirect and direct eval (as I did not when I first read this), the current wording does not make it clear that direct eval is a unique syntactic behavior that behaves like no other part of JS. The whole section was completely meaningless to me when I first read it.
I think that using quotes implies …
> docs: update wording regarding indirect eval

- docs/src/use/configure/configuration-files.md
- closes #18418
Change destined for [v9 > Configuration Files > Configuration File Resolution](https://eslint.org/docs/latest/use/configure/configuration-files).
The sentence
> If none of the files are not found, it checks the parent directory for each file.
is changed to the following, removing the word "not":
> If none of the …
> docs: fix grammar in configuration file resolution

- docs/src/use/configure/migration-guide.md
Update the eslintrc to flat config migration guide with the release of 9.0.0.
I changed ["Configuration Migration Guide"](https://eslint.org/docs/latest/use/configure/migration-guide) to reflect that ESLint 9.0.0 has been released.
Not sure of this is the best wording. It's unclear how this is different from usage in v8, as …
> docs: reflect release of v9 in config migration guide

- lib/eslint/eslint.js
- package.json
- tests/lib/eslint/eslint.js
Fixes #18407
Updated `@humanwhocodes/retry` dependency to the latest v0.2.4 that includes the fix for #18407 and added a test that fails with v0.2.3.
Also updates `lib/eslint/eslint.js` to use `require("fs/promises")` instead of `require("fs").promises`.
> fix: don't crash when `fs.readFile` returns promise from another realm

- docs/src/rules/no-return-await.md
update deprecation notice of `no-return-await` rule.
Fixes: #18166
> docs: update deprecation notice of `no-return-await`

- docs/src/rules/no-misleading-character-class.md
- lib/rules/no-misleading-character-class.js
- tests/lib/rules/no-misleading-character-class.js
Fixes #15080 
This PR adds an option to allow escape sequences in regexp character classes to the `no-misleading-character-class` rule. The new option only has effect on nodes whose source location can be statically determined with our tools. These are the same nodes that report granular errors:
* regular expression literals
* …
> feat: add option `allowEscape` to `no-misleading-character-class` rule

- docs/src/rules/no-unreachable.md
Closes: #18378
I've updated the documentation for `no-unreachable` to clarify that TypeScript will only consider unreachable code an error if configured to do so.
I checked whether there are any differences in behaviour between TypeScript an ESLint. The only one I found was in this case:
```ts
try {
return;
} …
```
> docs: Clarify usage of `no-unreachable` with TypeScript

- docs/src/rules/no-restricted-exports.md
- lib/rules/no-restricted-exports.js
- tests/lib/rules/no-restricted-exports.js
…ed-exports`
Made changes to add support for #18360 
I feel there should be alot more test cases which needs to be added, can add that based on review insights.
> feat: add `restrictedNamedExportsPattern` to `no-restricted-exports`

- docs/src/use/configure/migration-guide.md
- docs/src/use/configure/plugins.md
- docs/src/use/troubleshooting/index.md
- docs/src/use/troubleshooting/v9-rule-api-changes.md
- Added a troubleshooting page for `context.getScope is not a function` error
- Updated the config migration guide to mention the compatibility utility
- Updated the configure plugin page to mention both the compatibility utility and `FlatCompat`
> docs: Add troubleshooting info for plugin compatibility

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
Fixes #18441
Check for comments between the last key token and the value in the property node.
> fix: don't remove comments between key and value in object-shorthand

- docs/src/maintain/manage-issues.md
Added a section to the "Manage Issues and Pull Requests" page explaining how to request feedback from the TSC, including usage of the "tsc waiting" label as agreed in the 2024-05-16 TSC meeting.
> docs: explain how to use "tsc waiting" label

- lib/eslint/eslint.js
- messages/config-file-missing.js
- messages/eslintrc-incompat.js
- tests/bin/eslint.js
- Added additional URLs to several error messages related to configuration errors.
- Added a nice message for when a config file isn't found, as it seems like some people are just installing ESLint v9 without doing any migration first and are confused when the config file isn't found.
> fix: Improve config error messages

- lib/rules/func-style.js
- tests/lib/rules/func-style.js
* **Node version:** v20.12.0
* **npm version:** 10.5.0
* **Local ESLint version:** v9.3.0
* **Global ESLint version:** no
[ ] …
> fix: `func-style` false positive with arrow functions and `super`

- docs/src/use/command-line-interface.md
- lib/cli.js
like @eslint/create-config (https://github.com/eslint/eslint/issues/18369), it may use an outdated version, this commit forces to use the latest version.
fixes https://github.com/eslint/eslint/issues/18481
- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
is there …
> fix: use `@eslint/config-inspector@latest`

- docs/src/rules/func-style.md
- lib/rules/func-style.js
* Say "function expressions assigned to variables" in some cases for clarity
* Prefer `const` over `var` in examples
* Some tidying/rewording
* Add a note saying the lint does not apply to all functions
Fixes: #18474
> docs: clarify func-style

- docs/src/use/configure/plugins.md
- lib/eslint/eslint.js
- tests/lib/eslint/eslint.js
Fixes #18493
Closes #15949
* Fixed #18493 by changing the code block filter condition to `configs.getConfig(blockFilename) !== void 0`.
* Updated documentation and added tests for #15949.
> fix: skip processor code blocks that match only universal patterns

- docs/src/rules/no-loop-func.md
- lib/rules/no-loop-func.js
- tests/lib/rules/no-loop-func.js
Fixes https://github.com/eslint/eslint/issues/16902
```js
var arr = [];
for (var i = 0; i < 5; i++) {
arr.push((f => f)((() => i)())); // OK
}
for (var i = 0; i < 5; i++) {
arr.push((() => {
return (() => i)(); // OK
})());
}
for (var i = 0; i < 5; i++) {
arr.push((f => f)(() => i)); // Error
}
for (var i = 0; i < 5; i++) { …
```
> feat: ignore IIFE's in the `no-loop-func` rule

- lib/config/flat-config-array.js
- lib/eslint/eslint-helpers.js
- lib/eslint/eslint.js
- lib/rule-tester/rule-tester.js
- package.json
Replace a dependency
This PR replaces the dependency `@humawhocodes/config-array` with `@eslint/config-array` in the current version. The new dependency includes breaking changes: the method `ConfigArray.isFileIgnored()` has new semantics (see https://github.com/eslint/rewrite/pull/7). To ensure that everything works like …
> refactor: switch to `@eslint/config-array`

- docs/src/use/command-line-interface.md
Closes https://github.com/eslint/eslint/issues/18521.
Updates https://eslint.org/docs/latest/use/command-line-interface#--ext section with a link to https://eslint.org/docs/latest/use/configure/migration-guide#--ext to improve discoverability.
> docs: add link to migration guide for `--ext` CLI option

- docs/src/use/configure/configuration-files.md
Fixes #18475
Added two sections to the configuration files docs explaining how to lint files with a given extension or without extension.
Clarified other parts of the documentation about `files` and `ignores`.
> docs: specifying files with arbitrary or no extension

- Makefile.js
Changed the command for npm test script.
Changed the command line for `c8 check-coverage`:
* Fixed the spelling of the CLI flags `--statements`, `--branches` and `--functions` (see [documentation](https://github.com/bcoe/c8/tree/v7.14.0?tab=readme-ov-file#checking-coverage)). Unfortunately, c8 silently ignores invalid options, …
> ci: fix CLI flags for c8, raise thresholds

- lib/eslint/eslint-helpers.js
- tests/lib/eslint/eslint.js
Node version: v20.12.0
npm version: 10.5.0
Local ESLint version: v9.4.0
Global ESLint version: no
Operating System: windows
[ ] `@typescript-eslint/parser`
[ ] …
> fix: Don't lint same file multiple times

- docs/src/use/configure/ignore.md
closes https://github.com/eslint/eslint/issues/18562
I found this behavior to be very surprising and numerous maintainers also agreed in https://github.com/eslint/eslint/issues/17213
I don't know if there are other callout boxes you use besides "important". I saw that used on another page, so used the same one, but perhaps …
> docs: add callout box for unintuitive behavior

- eslint.config.js
- packages/eslint-config-eslint/README.md
- packages/eslint-config-eslint/base.js
- packages/eslint-config-eslint/formatting.js
- packages/eslint-config-eslint/package.json
Updates `eslint-config-eslint`. Extracts formatting rules into separate config.
Moved formatting rules from `base` config to the new `formatting` config and added an export for it.
Since our projects already use 3 different configurations from `eslint-config-eslint`, it would be complicated to make all combinations with and …
> chore: extract formatting rules into separate config

- docs/src/use/migrate-to-9.0.0.md
Added mention of using `eslint-transforms` to address some developer-focused changes.
This PR depends on https://github.com/eslint/eslint.org/pull/576.
> docs: Add mention of eslint-transforms to v9 migration guide

- lib/eslint/eslint-helpers.js
- messages/all-matched-files-ignored.js
* **Node version:** v20.12.0
* **npm version:** 10.5.0
* **Local ESLint version:** `main` branch
* **Global ESLint version:** no
[ ] …
> fix: message template for all files ignored

- docs/src/integrate/nodejs-api.md
- lib/eslint/eslint.js
Refs #18563.
`baseConfig` and `overrideConfig` options of the ESLint constructor can also be arrays of config objects.
Updated Node.js API Reference docs and JSDoc.
> docs: `baseConfig` and `overrideConfig` can be arrays

- package.json
- tests/lib/eslint/eslint.js
Fixes #18550
Updated `@eslint/config-array` dependency to v0.16 which includes https://github.com/eslint/rewrite/pull/50 and added a test that fails with v0.15.
> fix: treat `*` as a universal pattern

- docs/src/use/configure/configuration-files.md
Updated the configuration files documentation with the information that `"*"` is treated as a universal `files` pattern.
> docs: update info about universal `files` patterns

- tests/lib/rules/no-misleading-character-class.js
Removes unused disable directive to fix a lint error in CI.
Removed disable directive for `internal-rules/multiline-comment-style` that was added because of a bug in Acorn (https://github.com/acornjs/acorn/issues/1275) that was fixed in the newly-released version.
It seems that the bug fix didn't help with the …
> chore: remove unused eslint-disable directive

- docs/src/use/command-line-interface.md
- docs/src/use/configure/ignore.md
Adds a section about Including `.gitignore` files using `@eslint/compat`'s utility `includeIgnoreFile`.
Added the section to `ignore.md`, and a link to it into the `--ignore-path` CLI section.
> docs: add section about including `.gitignore` files

- lib/languages/js/source-code/source-code.js
- lib/linter/config-comment-parser.js
- lib/linter/linter.js
- tests/lib/languages/js/source-code/source-code.js
- tests/lib/linter/config-comment-parser.js
- tests/lib/linter/linter.js
- tools/check-rule-examples.js
* **Node version:** v20.12.0
* **npm version:** v10.5.0
* **Local ESLint version:** v9.5.0
* **Global ESLint version:** no
[ ] …
> fix: correct locations of invalid `/* eslint */` comments

- lib/eslint/eslint.js
- tests/lib/eslint/eslint.js
When converting `ignorePatterns` (`--ignore-pattern`), which are relative to `cwd`, to patterns relative to `basePath`, we were prepending `path.relative(basePath, cwd)`.
On Windows, this was producing a mix of `\` and `/` as path separators in the result. For example, if the config file is in the root, and you run `eslint …
> refactor: use `/` separator when adjusting `ignorePatterns` on Windows

- lib/languages/js/source-code/source-code.js
- lib/linter/linter.js
Refactor
I've been trying to tighten up the expected interfaces for language plugins, and I realized that the `node` property on inline configs is actually never used except to retrieve the location, so I switched the interface to just return `loc` instead.
I can't think of a scenario where we'd need anything other than the …
> refactor: Return value of applyInlineConfig()

- docs/src/integrate/nodejs-api.md
- docs/src/use/command-line-interface.md
- lib/cli.js
- lib/eslint/eslint-helpers.js
- lib/eslint/eslint.js
- lib/eslint/legacy-eslint.js
- lib/linter/linter.js
- lib/options.js
- lib/shared/flags.js
- lib/shared/logging.js
- tests/lib/cli.js
- tests/lib/eslint/eslint.js
- tests/lib/eslint/legacy-eslint.js
- tests/lib/linter/linter.js
- tests/lib/options.js
Adds feature flags to:
- CLI options
- `ESLint` class
- `Linter` class
- Documentation for above
fixes #18458
Setting as a draft until we decide if we want an RFC for this feature.
> feat: Implement feature flags

- lib/linter/linter.js
Small refactors.
- Updated so `Linter` will fall back to `language.visitorKeys` if `sourceCode.visitorKeys` is not present.
- Updated `Linter` with a better check for an uninitialized `SourceCode` object.
> refactor: Use language.visitorKeys and check for non-JS SourceCode

- docs/src/integrate/nodejs-api.md
This reverts commit 0583c87c720afe0b9aef5367b1a0a77923eefe9d.
Reverted the parent commit 0583c87c720afe0b9aef5367b1a0a77923eefe9d which I accidentally pushed to main.
> docs: revert `loadESLint` does not support option `cwd`

- docs/src/integrate/nodejs-api.md
This PR removes a code example from the `loadESLint()` API docs. The example was using an unsupported option `cwd`, suggesting that `loadESLint()` could be used to determine the `ESLint` constructor for a specified directory.
> docs: `loadESLint` does not support option `cwd`

- lib/languages/js/index.js
- lib/linter/linter.js
Refs https://github.com/eslint/json/pull/1#discussion_r1662614339
Moves "Parsing error: " prefix adding into Linter so every language doesn't have to implement it.
> refactor: move "Parsing error" prefix adding to Linter

- docs/src/rules/no-restricted-imports.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
Fix https://github.com/eslint/eslint/issues/18536
```js
/*eslint no-restricted-imports: ["error", { patterns: [{
"importNamePattern": "_Enum$",
"regexGroup": "@app/(?!(api/enums$)).*"
}]}]*/
// error
import { Foo_Enum } from '@app/api';
import { Bar_Enum } from '@app/api/bar';
import { Baz_Enum } from '@app/api/baz';
import { …
```
> feat: add `regex` option in `no-restricted-imports`

- lib/linter/node-event-generator.js
- tests/lib/linter/node-event-generator.js
Refs https://github.com/eslint/eslint/issues/16999, https://github.com/eslint/json/pull/4#issuecomment-2208674059
With the current version of ESLint, selectors like `Element > String` or `Element + Element` don't work with the `@eslint/json` language plugin as ESLint passes an empty ancestry to esquery because the calculations …
> refactor: don't use `parent` property in `NodeEventGenerator`

- lib/rules/no-unused-vars.js
- package.json
- tests/lib/rules/no-unused-vars.js
Node version: v22.3.0
npm version: v10.8.1
Local ESLint version: v9.6.0 (Currently used)
Operating System: darwin 23.5.0
[ ] …
> fix: destructuring in catch clause in `no-unused-vars`

- docs/src/assets/scss/components/search.scss
fix search input styles
Changes made:
1. Fixed the search text overlapping with the close icon
2. Correct the position of the close icon
3. Adjusted the positioning of the search results dropdown
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/b1065c46-0ae2-4841-b0f8-d4d …
> docs: fix search input stylings

- package.json
- tests/lib/eslint/eslint.js
Fixes #18706
Updated `@eslint/config-array` dependency to v0.17.1 to include https://github.com/eslint/rewrite/pull/92 and added two tests that are failing with v0.17.0.
> fix: `basePath` directory can never be ignored

- docs/src/_data/flags.js
- docs/src/pages/flags.md
- docs/src/use/formatters/index.md
- docs/src/use/integrations.md
- docs/src/use/migrate-to-9.0.0.md
- docs/src/use/troubleshooting/index.md
- lib/cli.js
- lib/linter/linter.js
- lib/shared/flags.js
- templates/formatter-examples.md.ejs
- tests/lib/cli.js
- tests/lib/eslint/eslint.js
- tests/lib/linter/linter.js
- `Linter` now validates `flags` and throws an error for any inactive or unknown flags. Previously, these flags were ignored, which made it difficult to track down problems.
- Added a new "Feature Flags" page that dynamically populates the available feature flags and shows how to use them.
> fix: Throw error when invalid flags passed

- lib/rules/require-await.js
- lib/rules/utils/ast-utils.js
- tests/lib/rules/require-await.js
Fixes #18713
#18713
The `require-await` rule now includes a suggestion to remove the `async` keyword.
No.
> feat: add suggestion to `require-await` to remove `async` keyword

- .github/ISSUE_TEMPLATE/bug-report.yml
Added ids to text areas to allow it to be prefilled when submitting issues from playground. part of https://github.com/eslint/eslint.org/issues/598
- should we fill the error message as well or since submitting playground URL is fine we won't need it?
> chore: add ids to github issue templates

- README.md
- docs/src/extend/custom-parsers.md
- docs/src/extend/scope-manager-interface.md
- docs/src/use/configure/configuration-files.md
- docs/src/use/configure/parser-deprecated.md
- docs/src/use/configure/parser.md
- docs/src/use/core-concepts/glossary.md
- docs/src/use/core-concepts/index.md
Updated several links to the [`eslint/js`](https://github.com/eslint/js) repo, formerly `eslint/espree` and `eslint/eslint-scope`.
> docs: update links to `eslint/js` repo

- docs/src/_includes/components/search.html
copy of https://github.com/eslint/eslint.org/pull/615
> chore: add tab index to powered by algolia text

- eslint.config.js
When I run `npx eslint .`, I'm getting the following error:
```
Oops! Something went wrong! :(
ESLint: 9.9.0
TypeError: Error while loading rule 'yml/no-empty-document': Cannot read properties of undefined (reading 'defineCustomBlocksVisitor')
Occurred while linting C:\projects\eslint\.c8rc
at Object.create …
```
> chore: use eslint-plugin-yml on yaml files only

- lib/linter/linter.js
- lib/services/parser-service.js
Refactor
Extracted the parsing logic from `Linter` into a new class, `ParserService`. I envision this as a step towards the core rewrite, where the API is made up of smaller classes rather than giant ones that do everything. 
Notes:
- I anticipate there being constructor arguments to this class in the future, which is why it's a …
> refactor: Extract parsing logic from Linter

- lib/config/config.js
- lib/config/flat-config-array.js
- package.json
- tests/lib/config/flat-config-array.js
Extracted the normalization and validation of individual config objects into a `Config` class.
Up to this point, all of that logic was contained inside of `FlatConfigArray`, meaning any time we wanted a normalized and validated config object, we had to first create a `FlatConfigArray` even if we already had all of the config …
> refactor: Config class

- .github/ISSUE_TEMPLATE/bug-report.yml
- To prefill description with the configuration of playground we need to add these ids.
- Shall I add ids to fields that we dont use as well? so that we dont have to add it in future?
> chore: added missing ids

- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
`no-invalid-regexp` rule  doesn't report duplicate flags that are allowed by the `allowConstructorFlags` option.
```js
/*eslint no-invalid-regexp: ["error", { "allowConstructorFlags": ["a"] }]*/
new RegExp('.', 'aa'); // not reported
```
made the rule to report these flags
Fixes #18748
> feat: report duplicate allowed flags in `no-invalid-regexp`

- lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-invalid-regexp.js
Added a separate error message for duplicate flags (only those are valid and allowed flags) in `no-invalid-regexp` rule.
> feat: add error message for duplicate flags in `no-invalid-regexp`

- lib/linter/apply-disable-directives.js
- lib/linter/linter.js
- tests/lib/linter/apply-disable-directives.js
Refactors code for removing unused disable directives to not use `Node#value` (`Comment#value`) as this property might not exist on nodes/tokens/comment that are used for directives in other languages.
I noticed this while working on https://github.com/eslint/json/issues/21. For example, eslint would crash while trying to remove …
> refactor: don't use `node.value` when removing unused directives

- docs/src/extend/custom-formatters.md
Fixes #18856
Updated custom formatted docs with the fact that `ruleId` and `nodeType` can be `null`.
I think that specifying `result` and `messages` objects in custom formatters docs is redundant because we could just link to [LintResult type](https://eslint.org/docs/latest/integrate/nodejs-api#-lintresult-type). I'll open a …
> docs: specify that `ruleId` can be `null` in custom formatter docs

- docs/src/integrate/nodejs-api.md
Refs #18821
Updated `LoadedFormatter` type docs as per https://github.com/eslint/eslint/issues/18821#issuecomment-2312708811
Since we now publish types, https://github.com/eslint/eslint/pull/18872 should be finished as well to close the issue.
> docs: clarify `resultsMeta` in `LoadedFormatter` type

- lib/shared/types.js
- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Updated type declarations.
Fixes #18821
* Added type `FormatterFunction`. The `context` argument is no longer marked as optional.
https://github.com/eslint/eslint/blob/adcc50dbf1fb98c0884f841e2a627796a4490373/lib/shared/types.js#L244-L250
* Updated type `ResultsMeta`. This is the type of the second argument passed to a …
> feat: add type `FormatterFunction`, update `LoadedFormatter`

- lib/linter/linter.js
- lib/source-code/source-code.js
- tests/lib/linter/linter.js
Fixes #18363 on the v8.x-dev branch
Applied commit eeec41346738afb491958fdbf0bcf45a302ca1b7 to the v8.x-dev branch.
> fix: do not throw when defining a global named `__defineSetter__`

- lib/eslint/flat-eslint.js
- tests/lib/eslint/flat-eslint.js
Fixes #18732 on the v8.x-dev branch
Applied changes from PR #18736 to the v8.x-dev branch.
> fix: add logic to handle fixTypes in the lintText() method

- lib/types/rules/stylistic-issues.d.ts
> fix: add missing types for `camelcase` options

- lib/types/rules/best-practices.d.ts
> fix: add missing types for `no-empty-function` options

- lib/types/rules/best-practices.d.ts
> fix: add missing types for `no-implicit-coercion` options

- lib/types/rules/possible-errors.d.ts
> fix: add missing types for `no-misleading-character-class` options

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Update types
1. Added `language` to `Linter.Config`
2. Added `languages` to `ESLint.Plugin`
3. Added type tests for both changes
This is just a first step towards fully supporting languages through the type system. At the least, it lets people create plugins containing the `languages` key. We will need to continue tweaking this …
> feat: Add language to types

- lib/linter/linter.js
- lib/linter/vfile.js
- lib/services/processor-service.js
- tests/lib/eslint/eslint.js
- tests/lib/linter/linter.js
- tests/lib/linter/vfile.js
This extracts processor logic into `ProcessService`:
- Created `ProcessorService`
- Refactored `Linter` to use `ProcessorService`
- Added `rawBody` to `VFile`
- Updated `VFile` tests
The biggest difference is that `ProcessorService` takes a `VFile` and returns an array of `VFile`s (or strings for legacy compat). This makes it …
> refactor: Extract processor logic into ProcessorService

- lib/types/rules/possible-errors.d.ts
> fix: add missing types for `no-extra-boolean-cast` options

- lib/types/rules/best-practices.d.ts
> fix: add missing types for `no-param-reassign` options

- lib/types/rules/best-practices.d.ts
[x] Other, please explain: Types update
Fixed type definition for `prefer-object-has-own` rule, it was released in [v8.5.0](https://github.com/eslint/eslint/releases/tag/v8.5.0)
> docs: correct `prefer-object-has-own` type definition

- lib/types/rules/ecmascript-6.d.ts
> fix: add missing types for `no-restricted-exports` rule

- lib/types/rules/best-practices.d.ts
> fix: add missing types for `no-unused-expressions` rule

- lib/types/rules/best-practices.d.ts
> fix: add missing types for `no-sequences` rule

- lib/types/rules/variables.d.ts
> fix: add missing types for `no-shadow` rule

- lib/types/rules/stylistic-issues.d.ts
> fix: add missing types for `no-underscore-dangle` rule

- lib/types/rules/possible-errors.d.ts
> fix: add missing types for `no-unsafe-negation` rule

- lib/types/rules/ecmascript-6.d.ts
> fix: add missing types for `object-shorthand` rule

- lib/types/rules/possible-errors.d.ts
> fix: add missing types for `require-atomic-updates` rule

- docs/src/rules/complexity.md
- lib/rules/complexity.js
- tests/lib/rules/complexity.js
Implements an option to use the modified cyclomatic complexity, where a switch statement only increases the value by 1 regardless of how many case statements it contains.
Fixes #18885
See proposal in #18885
Implements an option to use the modified cyclomatic complexity, where a switch statement only increases the value by 1 …
> feat: Implement modified cyclomatic complexity

- docs/src/rules/id-match.md
Fixes a typo in `id-match` rule docs page.
`"oHungarianNotation"` to `"HungarianNotation"`
> docs: fix typo in `id-match` rule

- docs/src/use/configure/configuration-files.md
Refs https://github.com/eslint/eslint/issues/18975. Clarifies that global ignores should be used to exclude `.js` files.
Updated `configuration-files.md`
> docs: Clarify how to exclude `.js` files

- Makefile.js
- lib/cli-engine/formatters/stylish.js
- package.json
Dependency cleanup. Mainly, replacing `strip-ansi` with native `stripVTControlCharacters` from [Node API](https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr) which is available since Node 16.11.0.
- Replaces `strip-ansi` usage with `util.stripVTControlCharacters`
- Remove `strip-ansi` requirement.
> refactor: replace strip-ansi with native module

- docs/src/_includes/layouts/base.html
Updated the banner to indicate that ESLint v8.x has reached its end of life (EOL).
similar to https://github.com/eslint/eslint.org/pull/643
As stated in the [PR](https://github.com/eslint/eslint.org/pull/643), we should merge this on October 5.
> docs: Updates for v8 EOL

- knip.jsonc
In the Knip configuration, we had added the `eslint-config-eslint` dependency to the ignore dependencies section to avoid warnings about it being unused. However, I've recently noticed that we are no longer receiving warnings for `eslint-config-eslint` as an unused dependency. Instead, we're now getting warnings for unused items …
> chore: remove unused ignore dependency

- docs/src/rules/no-restricted-imports.md
Closes https://github.com/eslint/eslint/issues/18991.
Updated `no-restricted-imports` docs with an example of how `importNamePattern` option can be used to allow only side-effect imports.
> docs: Add example with side-effect imports to no-restricted-imports

- docs/src/integrate/nodejs-api.md
- lib/config/default-config.js
- lib/eslint/eslint.js
- lib/types/index.d.ts
- tests/lib/eslint/eslint.js
Fix https://github.com/eslint/eslint/issues/18619
```js
const { ESLint } = require("eslint");
const configs = [ ...ESLint.defaultConfig ];
```
No
> feat: export `ESLint.defaultConfig`

- docs/src/use/command-line-interface.md
Fixes #19005
Replaced `--ext` with `--global` in examples of passing multiple values to a CLI option.
I chose `--global`  for simplicity.
> docs: Update examples of passing multiple values to a CLI option

- docs/src/use/configure/configuration-files.md
- lib/config/config-loader.js
- tests/fixtures/ts-config-files/ts/eslint.undefined.config.ts
- tests/lib/eslint/eslint.js
- Drop support for jiti versions prior to v2
- Improve the error message in a special case
- Add unit tests for when jiti is outdated or not found
Support for jiti v2 was added in PR #18954, but jiti v1.21 is still supported. This can lead to a confusing error message when a project with jiti v1.21 tries to use a TypeScript …
> feat: drop support for jiti v1.21

- lib/types/rules/best-practices.d.ts
- lib/types/rules/ecmascript-6.d.ts
- lib/types/rules/possible-errors.d.ts
- lib/types/rules/stylistic-issues.d.ts
As per https://github.com/eslint/eslint/pull/17696
Updates type definitions for deprecated rules.
No
> docs: update deprecated rules type definitions

- tools/check-emfile-handling.js
[x] Other, please explain: cleanup in test
Remove the test directory (`tmp/emfile-check`) before and after the test.
Before, because it might contain files from previous runs. `ulimit` values aren't constant, so the actual amount of files might be bigger than the test generates.
After, because we shouldn't waste inodes (and space, depending on filesystem) …
> test: ensure tmp directory cleanup in `check-emfile-handling.js`

- lib/eslint/eslint-helpers.js
If there's a directory with considerable amount of files (I encountered it at 150_000), pushing them at once exceeds call stack limit.
`Array.prototype.push.apply(filePaths, result.value);` without spread operator would fail as well.
Performance.
I've tried different `CHUNK_SIZE`s between 512 and 10000, and the time curve wasn't …
> fix: avoid call stack overflow while processing globs

- docs/src/use/configure/migration-guide.md
Followup to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735 and https://github.com/eslint/eslint/issues/18928, where `@types/eslint` was removed from DefinitelyTyped
Happy to reword (eg. to mentioning the ESLint project or the `eslint/eslint` repo), in case referring to the directory is the wrong way to explain …
> docs: change link from @types/eslint to lib/types

- lib/types/rules/stylistic-issues.d.ts
Add deprecation notice on some stylistic issues deprecated rules
On `lib/types/rules/stylistic-issues.d.ts` there are some deprecated rules 
that do not have `@deprecated` marker, even if on documentation they are marked as so:
- [indent](https://eslint.org/docs/latest/rules/indent)
- …
> docs: add deprecation on `indent`, `quotes` and `semi` rule types

- package.json
Fixes https://github.com/eslint/eslint/issues/19101
Updated `@humanwhocodes/retry` dependency to v0.4.1, which includes the fix (https://github.com/humanwhocodes/retry/pull/40).
I tested locally that the debug logs don't appear unless `DEBUG` is set to `@hwc/retry`.
> fix: upgrade @humanwhocodes/retry@0.4.1 to avoid debug logs

- lib/eslint/eslint-helpers.js
- lib/rule-tester/rule-tester.js
- package.json
- tests/lib/config/flat-config-array.js
- tests/lib/eslint/eslint.js
- tests/lib/languages/js/source-code/source-code.js
- tests/lib/linter/linter.js
- tests/lib/rule-tester/rule-tester.js
- tests/lib/rules/utils/ast-utils.js
Update a dependency
fixes #18575
This PR updates `@eslint/config-array` to version `^0.19.0` and adds unit tests to check that files on different drives are correctly ignored on Windows, which closes #18575.
The changes in `lib/eslint/eslint-helpers.js` remove unused logic that is probably a leftover of previous refactorings and …
> fix: ignore files on a different drive on Windows

- docs/src/integrate/nodejs-api.md
- Add `messageId` property to `LintMessage`, `SuppressedLintMessage` and `Linter.verify`
- Add optional `messageId` and `data` properties to suggestion types
Closes #19119
No
> docs: add missing messageId property and suggestion properties

- docs/src/rules/no-useless-computed-key.md
- tests/lib/rules/no-useless-computed-key.js
Closes #12048
This PR documents that `no-useless-computed-key` also applies to object patterns. I added several tests to confirm the behavior.
`['__proto__']` in object patterns is a false negative. Shall we fix it or leave the behavior as is?
> docs: add `no-useless-computed-key` examples with object patterns

- docs/src/extend/languages.md
- lib/config/config.js
- lib/languages/js/index.js
- lib/linter/linter.js
- tests/lib/config/flat-config-array.js
- Added support for `Language#normalizeLanguageOptions()`
- Moved normalization logic from `linter.js` into `js/index.js`
- Updated the docs about language plugins
fixes #19037
I left duplicates of `isEspree()` and `normalizeEcmaVersionForLanguageOptions()` in `linter.js` and `js/index.js`. The ones in `linter.js` can be removed …
> feat: Implement Language#normalizeLanguageOptions()

- docs/src/rules/no-restricted-syntax.md
Refs https://github.com/eslint/json/issues/55
Updates `no-restricted-syntax` docs with a note that it can be used with any language.
> docs: note that `no-restricted-syntax` can be used with any language

- packages/eslint-config-eslint/package.json
[X ] Other, please explain:
Hello,  
I’ve added the `repository.directory` property to `eslint-config-eslint/package.json`.  
This property is already exist in `js/package.json` but it's missing in `eslint-config-eslint/package.json`.
https://github.com/eslint/eslint/blob/d46059410a0e02b98067aa31975c25fd8d0d1c2b/packages/js/package.json#L19-L22 …
> chore: add `repository.directory` property to `package.json`

- docs/src/integrate/nodejs-api.md
Hello, 
As mentioned in https://github.com/eslint/eslint/pull/19175#issuecomment-2499964354, I've deleted unnecessary horizontal rule(`---`) in `v8.x` branch too.
This is the follow up PR of #19175.
Nope!
> docs: delete unnecessary horizontal rule(`---`) (v8.x) (follow up)

- docs/src/_includes/components/search.html
> chore: update algolia referrer

- docs/src/use/configure/debug.md
Hello, I've fixed a typo in `debug.md`.
I think `"` is a typo. It should be <code>`</code>.
Nope!
> docs: fix a typo in `debug.md`

- docs/src/rules/sort-keys.md
- lib/rules/sort-keys.js
- tests/lib/rules/sort-keys.js
Fixes #19153
Added `ignoreComputedKeys` option in `sort-keys` rule.
> feat: Add `ignoreComputedKeys` option in `sort-keys` rule

- docs/src/rules/sort-keys.md
Replaced the title of `caseSensitive` option from `insensitive` to `caseSensitive` in `sort-keys` rule docs.
Seems it wasn't updated in #6800 while the creation of rule.
> docs: fix `caseSensitive` option's title of `sort-keys`

- docs/src/_data/rules_meta.json
- lib/rules/no-compare-neg-zero.js
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
Hello,
Although `-0` is wrapped in an inline code block using backticks in the official documentation, it is missing in the `description` property of the `no-compare-neg-zero.js` rule. So, I added it.
Here’s a screenshot of the official documentation.
https://eslint.org/docs/latest/rules/no-compare-neg-zero
It’s just a simple …
> docs: add backtick in `-0` in `description` of `no-compare-neg-zero`

- docs/src/rules/no-async-promise-executor.md
Hello,
I've added a missing backtick for the inline code block in `no-async-promise-executor.md`.
It was included in the paragraph above but was missing in the one below. (Please refer to the screenshot below.)
Nope!
> docs: add missing backtick to `no-async-promise-executor`

- docs/src/rules/no-unreachable.md
Hello,
I’ve switched the word order in `no-unreachable.md` for **consistency**.
The documentation consistently uses the order `return`, `throw`, `continue`, and `break`, as shown in the screenshot below. However, the sentence I modified was not following this pattern.
> docs: switch the order of words in `no-unreachable`

- docs/src/assets/scss/syntax-highlighter.scss
- docs/src/assets/scss/tokens/themes.scss
Fixes https://github.com/eslint/eslint.org/issues/665. Corresponds to https://github.com/eslint/eslint.org/pull/666.
I swapped out the hardcoded comment colors with the closest theme tokens that had sufficient contrast.
<table>
<thead>
<tr>
<th>Mode
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>Light</td> …
> docs: use higher contrast color tokens for code comments

- docs/src/rules/eqeqeq.md
Hello,
I've added missing backticks to `eqeqeq.md`.
`===` and `!==` should be wrapped in backticks(inline code blocks) like the screenshot below.
Nothing.
> docs: add missing backticks to `eqeqeq`

- docs/src/rules/no-restricted-syntax.md
Updated `no-restricted-syntax` docs with the CSS language.
> docs: add CSS language to `no-restricted-syntax`

- docs/src/rules/func-style.md
Hello,
I've added missing backticks to `func-style.md`.
While `undefined` is a code-related value, it was not marked with backticks (inline code block), so I added them.
> docs: add missing backticks to `func-style`

- lib/linter/source-code-fixer.js
- tests/lib/linter/source-code-fixer.js
No need for providing the template. So I skipped it.
This PR adds a simple check in `linter.source-code-fixer` incasing `message.fix` equals to `null` or `undefined` which might cause the linter throw. 
There is a reproduction repo https://github.com/pany-ang/issue-eslint-config.
Or you can just remove the check, run the tests …
> fix: fix crash when `message.fix` is nullish

- lib/shared/flags.js
Hello, I've added missing backticks to `flags.js`.
While `eslint.config.js` is consistently wrapped in backticks throughout the documentation, it was missing in `flags.js`.
- E.g., `eslint.config.js` is wrapped in backticks throughout the documentation like the screenshot below.
> chore: add missing backticks to `flags.js`

- lib/rules/no-unused-vars.js
- tests/lib/linter/linter.js
- tests/lib/rules/no-unused-vars.js
added suggestion to `no-unused-vars` rule.
Fixes: #17545
> feat: add suggestions to `no-unused-vars`

- docs/src/assets/js/search.js
1. The `clearSearchResults` function was being triggered when clicking on the input field, which was unnecessary. A check has been added to prevent this.
| **Before** | **After** |
|------------|-----------|
| `if (e.target !== resultsElement) clearSearchResults();` | ```if (e.target !== resultsElement && e.target !== …
```
> docs: Refactor search result handling with better event listener cleanup

- docs/src/integrate/nodejs-api.md
Closes #19261
Fixed description of `ESLint` class constructor option `overrideConfigFile` in Node.js API docs. Allowed values are `null`, `true`, and string values. `false` is not allowed, so `boolean` was wrong. Also updated the description of how these values are interpreted.
> docs: fix description of `overrideConfigFile` option

- docs/src/extend/plugins.md
- docs/src/rules/id-match.md
- docs/src/rules/no-array-constructor.md
- docs/src/rules/no-console.md
Hello, 
I've added missing backticks in various parts of the documentation.
Here is the list of changes I've made:
1. **`docs/src/extend/plugins.md`**  
The properties `name` and `version` are part of an object, so they need backticks.
2. **`docs/src/rules/id-match.md`**  
`id-match` is also a property and requires backticks.
3. …
> docs: add missing backticks in various parts of the documentation

- docs/src/rules/no-shadow-restricted-names.md
- lib/rules/no-shadow-restricted-names.js
- tests/lib/rules/no-shadow-restricted-names.js
Fixes #19271
Updated `no-shadow-restricted-names` rule to also check imports and class names.
Also updated it to report on all defs as that seems to have been the intention according to the tests.
> feat: check imports and class names in `no-shadow-restricted-names`

- docs/src/use/configure/configuration-files.md
- lib/cli.js
- lib/config/config-loader.js
- lib/eslint/eslint.js
- lib/shared/flags.js
- tests/fixtures/ts-config-files/helper.ts
- tests/lib/eslint/eslint.js
This PR marks support for TypeScript config files as a stable feature as discussed in the [2024-12-12 TSC meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2024/2024-12-12.md#when-do-we-want-to-mark-eslintconfigts-as-stable).
* TypeScript config loading is now always enabled.
* The lookup logic for default config …
> feat: unflag TypeScript config files

- docs/src/rules/no-loop-func.md
Added Limitation section in `no-loop-func` rule that stats: 
>The rule cannot identify whether the function instance is just immediately invoked and then discarded, or possibly stored for later use.
Fixes #19120
> docs: add limitation section in `no-loop-func`

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Node version: v22.12.0
npm version: v10.9.0
Local ESLint version: v9.17.0 (Currently used)
Operating System: darwin 24.1.0
[ ] …
> fix: correct `overrideConfigFile` type

- docs/src/_data/rules_meta.json
- docs/src/rules/sort-imports.md
- lib/rules/sort-imports.js
Hello,
I've added missing backticks to `sort-imports`.
I believe the word `import` should be wrapped in backticks, as it represents a declaration.
I've also updated `@fileoverview` to sync with the `description` property.
> docs: add missing backticks to `sort-imports`

- docs/.eleventy.js
- docs/src/rules/jsx-quotes.md
- docs/src/rules/keyword-spacing.md
- docs/src/rules/no-extra-parens.md
- docs/src/rules/no-inline-comments.md
- docs/src/rules/no-irregular-whitespace.md
- docs/src/rules/no-unused-expressions.md
- docs/src/rules/space-before-keywords.md
- docs/tools/markdown-it-rule-example.js
- docs/tools/prism-eslint-hook.js
- tests/fixtures/good-examples.md
- tools/check-rule-examples.js
Updates docs site generator to treat configs after `::: correct`/`::: incorrect` as `languageOptions` instead of legacy `parserOptions`. This aligns rule example configs with the current config format and thus makes it easier to reason about them.
* Updated code that underlines lint errors in rule examples accordingly.
* Updated …
> docs: switch rule examples config format to `languageOptions`

- docs/src/rules/no-useless-computed-key.md
- docs/src/rules/no-useless-concat.md
- docs/src/rules/no-useless-return.md
Rewrited var using const in following rule examples:
- `no-useless-computed-key`
- `no-useless-concat`
- `no-useless-return`
Related Issue:  https://github.com/eslint/eslint/issues/19240
I used `const` instead of `var` and renamed some variables to avoid reuse. I'm not sure if the new variable names are appropriate, so please …
> docs: rewrite `var` using `const` in rule examples

- docs/src/rules/no-ex-assign.md
- docs/src/rules/no-func-assign.md
- docs/src/rules/no-irregular-whitespace.md
- docs/src/rules/no-new-native-nonconstructor.md
- docs/src/rules/no-obj-calls.md
Replaced `var` with `let` and `const` in following rule examples:
`no-ex-assign`
`no-func-assign`
`no-irregular-whitespace`
`no-new-native-nonconstructor`
`no-obj-calls`
Ref #19240
> docs: replace `var` with `let` and `const` in rule example

- docs/src/rules/no-else-return.md
Hello,
I've added missing backticks to `no-else-return.md`.
The `return` is consistently used throughout the documentation as a word for statement. 
Therefore, I believe adding backticks is more accurate!
> docs: add missing backticks to `no-else-return`

- docs/src/rules/comma-spacing.md
- docs/src/rules/consistent-this.md
- docs/src/rules/id-length.md
- docs/src/rules/id-match.md
- docs/src/rules/no-iterator.md
- docs/src/rules/no-multi-assign.md
- docs/src/rules/no-octal-escape.md
- docs/src/rules/no-self-compare.md
Rewrite the rule examples to replace `var` with `let` and `const`.
Related Issue ref - https://github.com/eslint/eslint/issues/19240
I’ve started working on some of the rules and have rewritten a few examples using `let` and `const`. However, in certain cases, I can't use `let` or `const` because they don't allow redeclaring …
> docs: rewrite examples with var using let and const

- docs/src/_data/rules_meta.json
- lib/rules/default-case-last.js
Hello,
I've added missing backticks to `default-case-last.js`.
The `switch` statement is consistenly wrapped in backticks all around documentation.
> docs: add missing backticks to `default-case-last`

- docs/src/rules/no-void.md
Hello,
I've added missing backticks to `no-void.md`.
I believe that `void` should be wrapped in backticks.
> docs: add missing backticks to `no-void`

- packages/js/src/index.js
Hello,
In the `package.json` of the `@eslint/js` package, we have a `name` property set to `@eslint/js`.
https://github.com/eslint/eslint/blob/36ef8bbeab495ef2598a4b1f52e32b4cb50be5e2/packages/js/package.json#L2
However, in the `src/index.js` file of the same package, we explicitly write `@eslint/js` again, even though we could …
> chore: extract package `name` from `package.json` for public interface

- docs/.eleventy.js
- docs/src/_data/eslintVersions.js
- docs/src/_data/sites/en.yml
- docs/src/_data/sites/zh-hans.yml
- docs/src/_includes/layouts/doc.html
Made the `Edit this page` to link to different branches according to the following data:
1. Docs at `/docs/latest` should point their edit buttons at the `latest` branch
2. Docs at `/docs/next` should point their edit buttons at the `main` branch
3. Docs at `/docs/head` should point their edit buttons at the `main` branch
1. …
> docs: `Edit this page` button link to different branches

- docs/src/rules/no-prototype-builtins.md
- docs/src/rules/no-setter-return.md
- docs/src/rules/no-sparse-arrays.md
- docs/src/rules/no-undef.md
- docs/src/rules/no-unexpected-multiline.md
Replaced `var` with const in following rules examples:
`no-prototype-builtins`
`no-setter-return`
`no-sparse-arrays`
`no-undef`
`no-unexpected-multiline`
Fixes #19240
> docs: replace `var` with `const` in rule examples

- docs/src/use/command-line-interface.md
- docs/src/use/configure/configuration-files.md
This PR reverts an accidental change in #18784 that reintroduced a removed part in the documentation about TypeScript Configuration Files.
> docs: revert accidental changes in TS config files docs

- tests/lib/eslint/eslint.js
Fix tests
This PR fixes a unit test that is failing in Node.js v22.13.0 on Windows. The failure can be observed for example in this CI run:
https://github.com/eslint/eslint/actions/runs/12757605004/job/35735176134
The error seems related to the handling of paths such as `B:\` (a drive's root directory) in certain file system …
> test: fix failing test in Node.js v22.13.0

- .github/workflows/ci.yml
- Makefile.js
- lib/types/rules/best-practices.d.ts
- lib/types/rules/deprecated.d.ts
- lib/types/rules/ecmascript-6.d.ts
- lib/types/rules/node-commonjs.d.ts
- lib/types/rules/possible-errors.d.ts
- lib/types/rules/strict-mode.d.ts
- lib/types/rules/stylistic-issues.d.ts
- lib/types/rules/variables.d.ts
- package.json
- packages/eslint-config-eslint/base.js
- tools/update-rule-type-headers.js
Fix types
Refs #18912
* Added a script to keep the TSDoc comments on top of rule type declarations in sync with the rule metadata. The script will automatically update the rule description, the recommended notice, `@since` and `@see` tags, and it will add a deprecation notice if not already present. It will throw an error if the …
> fix: sync rule type header comments automatically

- docs/src/use/getting-started.md
Updated the config example to make it almost match with default config .
- [ X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
- The default generated config of eslint was very different from the one mentioned in the getting started section of doc.
- I replaced this with …
> docs: update getting-started config to match default generated config

- docs/src/rules/object-shorthand.md
- docs/src/rules/prefer-promise-reject-errors.md
- docs/src/rules/prefer-rest-params.md
- docs/src/rules/prefer-spread.md
- docs/src/rules/prefer-template.md
Replaced `var` with const in following rules examples:
`object-shorthand.md`
`prefer-promise-reject-errors.md`
`prefer-rest-params.md`
`prefer-spread.md`
`prefer-template.md`
Refs https://github.com/eslint/eslint/issues/19240
> docs: replace var with const in rule examples

- docs/src/rules/arrow-body-style.md
- docs/src/rules/no-unmodified-loop-condition.md
- docs/src/rules/no-unsafe-optional-chaining.md
- docs/src/rules/no-useless-backreference.md
- docs/src/rules/use-isnan.md
Replaced `var` with `let` and `const` in following rule examples
`arrow-body-style`
`no-unmodified-loop-condition`
`no-unsafe-optional-chaining`
`no-useless-backreference`
`use-isnan`
Refs #19240
> docs: replace `var` with `let` and `const` in rule examples

- docs/src/integrate/nodejs-api.md
Clarified that `overrideConfig` is applied after anything in the configuration file.
fixes #https://github.com/eslint/eslint/issues/19279
> docs: Clarify overrideConfig option

- docs/src/use/getting-started.md
fixed order of manual setup of eslint installation in getting started page currently its => 1. 1. 2. 3.
The issue occurs after we added the new `tabs` component in #18784
> docs: fix order of installation steps in getting started

- docs/src/rules/capitalized-comments.md
- docs/src/rules/comma-dangle.md
- docs/src/rules/consistent-this.md
- docs/src/rules/indent-legacy.md
- tests/fixtures/bad-examples.md
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
Adds more checks for rule examples:
* `correct` examples should have no lint errors.
* `incorrect` examples should have one or more lint errors reported by the rule, and no other errors.
* Inline configurations (`/* eslint */`) should have valid options for the rule.
* `languageOptions` configurations after …
> docs: additional checks for rule examples

- .github/workflows/stale.yml
[x] Other, please explain: internal GHA workflow work
Added `permissions: read-all` to `.github/workflows/stale.yml` per https://github.com/eslint/eslint/issues/19356#issuecomment-2605433950.
The individual `stale` job _should_ still have write permissions overriding the workflow setting. _Should_.
> chore: add permissions: read-all to stale.yml workflow

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
* **Node version:** v22.11.0
* **npm version:** v10.9.0
* **Local ESLint version:** v9.19.0
* **Global ESLint version:**
[ ] …
> fix: `arrow-body-style` crash with single-token body

- lib/rules/consistent-this.js
- tests/lib/rules/consistent-this.js
Ensure that the module scope is checked for references.
fixes #19244
This is a little quick-and-dirty to fix the bug. I think this rule could use a larger refactor because this seems like an inefficient way to check for these references, but I don't have time to dig too deep at the moment.
> fix: Ensure module scope is checked for references in `consistent-this`

- lib/config/config.js
- messages/config-serialize-function.js
Updated the error message that is displayed when a function value can't be serialized. There's a special message when it's a parser vs. any other key.
fixes #19322
> fix: Better error message for unserializable parser

- messages/eslintrc-plugins.js
Updated the error message that's displayed when eslintrc-style plugins are found in a config. Hopefully this will give more of a clue of what to look for.
It turned out to be very difficult to get more information about the location of the error in the config array because this error is thrown during validation, which happens …
> fix: Clearer error message for wrong plugin format

- docs/src/rules/prefer-destructuring.md
- docs/src/rules/radix.md
- docs/src/rules/sort-keys.md
- docs/src/rules/sort-vars.md
- docs/src/rules/symbol-description.md
replaced `var` with `const` and `let` in rules examples
`prefer-destructuring`
`radix`
`sort-keys`
`sort-vars`
`symbol-description`
Refs #19240
> docs: replace `var` with `const` and `let` in rules

- docs/src/rules/no-eval.md
- docs/src/rules/no-nested-ternary.md
- docs/src/rules/no-ternary.md
- docs/src/rules/no-undefined.md
- docs/src/rules/no-unneeded-ternary.md
replaced var with const and let in rules examples
`no-eval`
`no-nested-ternary`
`no-ternary`
`no-undefined`
`no-unneeded-ternary`
Refs https://github.com/eslint/eslint/issues/19240
> docs: replace var with let and const in rules docs

- docs/src/rules/no-plusplus.md
- docs/src/rules/no-proto.md
- docs/src/rules/no-regex-spaces.md
- docs/src/rules/no-restricted-globals.md
- docs/src/rules/no-restricted-modules.md
- docs/src/rules/no-restricted-syntax.md
Refs #19240
Replaced var with const or let in following rules examples:
no-plusplus.md
no-proto.md
no-regex-spaces.md
no-restricted-globals.md
no-restricted-modules.md
no-restricted-syntax.md
Refs #19240
> docs: rewrite some examples with var using let and const

- lib/config/config-loader.js
- tests/fixtures/empty-config-file/cjs/eslint.config.cjs
- tests/fixtures/empty-config-file/cjs/foo.js
- tests/fixtures/empty-config-file/esm/eslint.config.empty-array.mjs
- tests/fixtures/empty-config-file/esm/eslint.config.mjs
- tests/fixtures/empty-config-file/esm/eslint.config.null.mjs
- tests/fixtures/empty-config-file/esm/eslint.config.zero.mjs
- tests/fixtures/empty-config-file/esm/foo.js
- tests/lib/config/config-loader.js
- tests/lib/eslint/eslint.js
Ensured consistent behavior when an empty CJS config file is loaded vs. an empty ESM config file. It now no longer throws an error in any situation and instead emits a warning.
fixes #19044
> fix: Emit warning when empty config file is used

- docs/src/_data/flags.js
- docs/src/pages/flags.md
- lib/eslint/eslint.js
- lib/linter/linter.js
- lib/shared/flags.js
- tests/lib/cli.js
- tests/lib/eslint/eslint.js
- tests/lib/linter/linter.js
Fixes #19337
* Updated behavior of inactive flags as per https://github.com/eslint/eslint/issues/19337#issuecomment-2608050058.
* Added CLI, ESLint class, and Linter class tests for all scenarios.
* Updated docs with the flags policies.
* Updated data for the list of flags on the flags docs page to filter out test-only ones as …
> feat: change behavior of inactive flags

- .github/workflows/types-integration.yml
- lib/types/index.d.ts
- package.json
- tests/lib/types/types.test.ts
Types update.
This PR reformulates some types exported by `eslint` in terms of the types exported from `@eslint/core`. This will allow better compatibility with language plugins and allow us to start de-duplicating types.
I did my best to ensure that these type changes are backwards compatible, but please do double-check:
- …
> fix: Bring types in sync with @eslint/core

- lib/config/rule-validator.js
- messages/config-plugin-missing.js
- tests/lib/config/flat-config-array.js
To modify the error message for missing plugin in config, created a new file `config-plugin-missing` to store message related to possible reasons of the error.
Message is kind of similar to what suggested in https://github.com/eslint/eslint/issues/19254#issuecomment-2598909936 which is
```
Oops! Something went wrong! :(
ESLint: …
```
> chore: better error message for missing plugin in config

- messages/config-plugin-missing.js
Follow-up to https://github.com/eslint/eslint/pull/19402.
The output lists common causes of the problem, but doesn't say what the problem is:
```
Oops! Something went wrong! :(
ESLint: 9.20.1
Common causes of this problem include:
1. The "foo" plugin is not defined in your configuration file.
2. The "foo" plugin is not defined …
```
> fix: update missing plugin message template

- docs/src/assets/js/search.js
Ref: https://github.com/eslint/eslint.org/pull/694#discussion_r1951260449
when the search input field loses focus the current selection range is saved. This saved selection is then restored when the input regains focus.
Ref: https://github.com/eslint/eslint.org/pull/694#discussion_r1951260449
> docs: Restore the carrot to the position where the search input was lost

- lib/languages/js/source-code/source-code.js
- tests/lib/languages/js/source-code/source-code.js
Adds an `if` for the case of a falsy AST in `JS`'s `SourceCode` > `validate` function.
Uses a more generalized, succinct error message than what I originally suggested in the issue. I found this one to align more with the rest of them.
> fix: improve error message for falsy parsed JS AST

- lib/rules/no-console.js
- tests/lib/rules/no-console.js
fixes #19477
Added a new message without placeholders to the `no-console` rule. The new message will be used for suggestions to remove method calls on `console` when the method name is computed.
> fix: improve message for `no-console` suggestions

- lib/rules/class-methods-use-this.js
- tests/lib/rules/class-methods-use-this.js
Continues #19431.
Adds tests to show that `class-methods-use-this` works with TypeScript syntax. Interestingly, there weren't any code changes in the rule itself needed besides `meta.(dialects,language)`. It doesn't support any of typescript-eslint's TypeScript-syntax-specific options and so the core logic is still the same. …
> feat: support TypeScript syntax in `class-methods-use-this`

- tests/lib/rule-tester/rule-tester.js
This test won't pass on local
When I work on #19499, I noticed this test won't pass.
The actual error is
```
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
actual expected
"Av'somethid using variables named 'foo'." (WITH COLORS)
```
I guess it passed because it's different on CI.
No.
> test: fix an assertion failure

- lib/config/default-config.js
- lib/rule-tester/rule-tester.js
- tests/lib/rule-tester/rule-tester.js
Stop applying default ignores to RuleTester.
Fixes #19471
No
> fix: allow `RuleTester` to test files inside `node_modules/`

- docs/src/rules/require-unicode-regexp.md
This PR updates the `require-unicode-regexp` documentation to clarify that when both the `i` flag and `\w` are used, adding the `u` flag may change behavior due to Unicode case folding. 
Closes #19474 
- Added an exception section explaining this case.
- Included an example demonstrating the difference in behavior.
Please check …
> docs: `require-unicode-regexp` add note for `i` flag and `\w` 

- docs/src/rules/no-dupe-keys.md
- lib/rules/no-dupe-keys.js
- tests/lib/rules/no-dupe-keys.js
Fixes #19504
Updated `no-dupe-keys` rule to ignore proto setter syntax in object literals.
> fix: `no-dupe-keys` false positive with proto setter

- docs/src/use/troubleshooting/circular-fixes.md
- docs/src/use/troubleshooting/index.md
- lib/linter/linter.js
- tests/lib/linter/linter.js
Fixes https://github.com/eslint/eslint/issues/17609.
Updated `Linter#verifyAndFix()` to check if the produced fix in a pass is the same as in the second previous pass, and in that case stop and emit a warning about conflicting rules.
> feat: circular autofix/conflicting rules detection

- docs/src/rules/no-useless-assignment.md
- lib/rules/no-useless-assignment.js
- lib/types/rules/best-practices.d.ts
- tests/lib/rules/no-useless-assignment.js
* **Node version:** latest
* **npm version:** latest 
* **Local ESLint version:** latest
* **Global ESLint version:** latest
[ ] …
> fix: reporting variable used in catch block in `no-useless-assignment`

- docs/.eleventy.js
- docs/src/rules/default-param-last.md
- lib/rules/default-param-last.js
- tests/fixtures/bad-examples.md
- tests/lib/rules/default-param-last.js
- tests/tools/check-rule-examples.js
- tools/check-rule-examples.js
Starts on #19173.
Updates `default-param-last` to account for TypeScript syntax features as handled in the [`@typescript-eslint/default-param-last`](https://typescript-eslint.io/rules/default-param-last) extension rule:
* Class parameter properties
* Type annotations
Includes tests equivalent to what the extension rule currently …
> feat: support TypeScript syntax in `default-param-last`

- .trunk/trunk.yaml
Quick fix for #19355's failures:
```plaintext
conf/replacements.json
-:-  fmt  Incorrect formatting, autoformat by running 'trunk fmt'  prettier
conf/rule-type-list.json
-:-  fmt  Incorrect formatting, autoformat by running 'trunk fmt'  prettier
```
Trunk is still configured to run on specifically those files on `main`, so it's using its default settings. But we're going with a different set of customizations in #19354.
This PR disables Prettier in Trunk altogether (i.e. removing the _"un-ignore the `conf/*.json` files"_ line). Prettier will be re-enabled in #19354.
> chore: temporarily disable prettier in trunk

- .git-blame-ignore-revs
-   [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Fast follows #19355 by adding a [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view). This way the …
> chore: added .git-blame-ignore-revs for Prettier via trunk fmt

- .c8rc
- .github/renovate.json5
- .prettierrc.json
- .trunk/trunk.yaml
- docs/package.json
- eslint.config.js
- knip.jsonc
Update the build
I noticed that after #19354 running `node bin/eslint` was reporting errors for `.json` files that were not caught by Trunk in CI, so I updated the Trunk config to lint and auto-format JSON files as …
> chore: format JSON files in Trunk

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Currently, the types of plugins such as `@eslint/json` are not compatible with `ESLint.Plugin` because of a [module augmentation](https://github.com/eslint/eslint/blob/v9.22.0/lib/types/index.d.ts#L49-L64) on `"@eslint/core"` that defines additional deprecated methods on the `RuleContext` type. The additional methods modify all …
> fix: move deprecated `RuleContext` methods to subtype

- docs/.eleventy.js
- docs/package.json
Updates docs site generator to underline lint errors in rule examples with TypeScript code.
Updated `languageOptions` for `ts` and `tsx` code blocks to use `@typescript-eslint/parser`.
> docs: show red underlines in TypeScript examples in rules docs

- docs/tools/prism-eslint-hook.js
While reviewing https://github.com/eslint/eslint/pull/19493, I noticed that the docs site code that lints rule examples for the purpose of underlining errors gets a parsing error when checking TypeScript examples of …
> docs: don't pass filename when linting rule examples

- lib/rules/no-loss-of-precision.js
- tests/lib/rules/no-loss-of-precision.js
[`@typescript-eslint/no-loss-of-precision/`](`https://typescript-eslint.io/rules/no-loss-of-precision/`) is already deprecated in favor of the core rule, just added test cases and updated the rule meta.
> feat: support TS syntax in `no-loss-of-precision`

- docs/src/rules/no-dupe-class-members.md
- lib/rules/no-dupe-class-members.js
- tests/lib/rules/no-dupe-class-members.js
Refs #19173 
- [Rule Reference](https://typescript-eslint.io/rules/no-dupe-class-members/)
- TypeScript allows method overloads, where multiple method signatures can be declared but only one implementation exists.
```ts …
```
> feat: support TS syntax in `no-dupe-class-members`

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
This pull request changes the type of the `options` property in `Rule.RuleContext` from `unknown[]` to `any[]`. I checked the `@types/eslint` types and the `options` property was specified to have type `any[]` in [the …
> fix: use `any[]` type for `context.options`

- docs/src/rules/no-restricted-properties.md
- lib/rules/no-restricted-properties.js
- tests/lib/rules/no-restricted-properties.js
This PR adds a new `allowObjects` option to the `no-restricted-properties` rule, allowing users to globally restrict a property while making exceptions for specific objects.
Closes #19348
> feat: add allowObjects option to no-restricted-properties

- docs/src/rules/no-undef-init.md
Updated `when not to use` section of `no-undef-init` rule docs by adding example of variable declaration with uninitialized and initialized with `undefined`.
Fixes #19623
> docs: update `no-undef-init` when not to use section

- lib/linter/node-event-generator.js
- tests/lib/linter/node-event-generator.js
> fix: `nodeTypeKey` not being used in `NodeEventGenerator`

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Fix https://github.com/eslint/eslint/issues/19633
> fix: update `RuleTester.run()` type

- docs/src/use/configure/migration-guide.md
This PR removes a double space in the docs that was caused by incorrect usage of the `npx_tabs` macro.
> docs: fix double space in command

- lib/linter/esquery.js
- lib/linter/node-event-generator.js
- package.json
- tests/lib/linter/esquery.js
Refactor
This refactors the ESQuery selector evaluation done by `NodeEventGenerator`. Previously, it would traverse the selector AST three times to collect different data. This refactor combines those three traversals …
> refactor: One-shot ESQuery selector analysis

- lib/rule-tester/rule-tester.js
- lib/shared/serialization.js
- tests/lib/rule-tester/rule-tester.js
- tests/lib/shared/serialization.js
Fixes #19646
Updated `isSerializable` (`lib/shared/serialization.js`) to not cause a stack overflow error when the passed object has circular references, and in that case return `false` because objects with circular references are not JSON-serializable.
Also updated `freezeDeeply` (in `lib/rule-tester/rule-tester.js`) to to not …
> fix: don't crash on tests with circular references in `RuleTester`

- docs/tools/markdown-it-rule-example.js
- docs/tools/prism-eslint-hook.js
- lib/languages/js/index.js
- lib/linter/linter.js
- lib/rule-tester/rule-tester.js
- lib/services/processor-service.js
- lib/shared/types.js
- tools/check-rule-examples.js
Fix internal types
In the ESLint code, the types `LanguageOptions` and `Rule` are currently being used for both language-generic types (which now have equivalents in the core types) and for JavaScript-specific types. This PR resolves the ambiguities as follows:
* For language-generic language options, the type `LanguageOptions` …
> chore: disambiguate internal types `LanguageOptions` and `Rule`

- lib/eslint/eslint.js
- tests/lib/eslint/eslint.js
This PR modifies the cache file deletion logic to check if the cache file exists before attempting to delete it.
Closes #19647
> fix: check cache file existence before deletion

- docs/src/_data/further_reading_links.json
- docs/src/rules/no-shadow-restricted-names.md
- lib/rules/no-shadow-restricted-names.js
- lib/types/rules.d.ts
- tests/lib/rules/no-shadow-restricted-names.js
- Added a new `reportGlobalThis` option to the `no-shadow-restricted-names` rule.
- Updated the rule’s schema, implementation, and documentation to support and describe the new option.
- Updated the TypeScript types to include the new option.
- Added tests.
Closes #19658
> feat: add reportGlobalThis to no-shadow-restricted-names

- docs/src/use/configure/combine-configs.md
Fixes #19683
Fixes wording on https://eslint.org/docs/latest/use/configure/combine-configs
"Insert the array directly into your _exported array_" is technically incorrect, as the array is passed to `defineConfig()` which then spreads it into the exported array.
> docs: fix wording in Combine Configs

- tests/lib/mcp/mcp-server.js
Fix the output of `npm test`
I noticed that the deprecation warning printed by ESLint when it finds an `.eslintignore` file was being printed to stderr during the MCP server tests, breaking the output of `npm test`. So I replaced `process.emitWarning` with a stub in the tests.
Before:
```shell
$ npm test 
> eslint@9.26.0 test
> …
```
> test: mock `process.emitWarning` to prevent output disruption

- docs/src/integrate/nodejs-api.md
- lib/cli-engine/cli-engine.js
- lib/config/config-loader.js
- lib/eslint/eslint.js
- lib/eslint/legacy-eslint.js
- lib/linter/linter.js
- lib/shared/types.js
- tools/eslint-fuzzer.js
This PR replaces usages of the `ConfigData` type with `Config` for flat config objects, or with `FlatConfigArray` for flat config arrays. At the same time it removes `ConfigData` and another related type from `lib/shared/types.js` in favor of the TypeScript definitions for eslintrc objects. I tagged this with `docs:` because …
> docs: fix internal usages of `ConfigData` type

- docs/src/use/suppressions.md
Refs https://github.com/eslint/eslint/discussions/19677#discussioncomment-13009945, 1.
Fixed the wording about unused suppressions. They don't cause a warning but an error and non-zero exit code.
> docs: clarify that unused suppressions cause non-zero exit code

- lib/cli-engine/cli-engine.js
- lib/eslint/eslint.js
- lib/eslint/legacy-eslint.js
- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Updates `ESLint.DeprecatedRuleUse` to include the `info` property.
The TypeScript type `ESLint.DeprecatedRuleUse` is the equivalent of the internal type `DeprecatedRuleInfo`.
https://github.com/eslint/eslint/blob/8ed32734cc22988173f99fd0703d50f94c60feb8/lib/shared/types.js#L124-L130
In #19238 the `info` property was added to …
> fix: add `info` to `ESLint.DeprecatedRuleUse` type

- lib/cli-engine/cli-engine.js
- lib/linter/linter.js
- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Updates `Linter.ParserOptions` to include the `allowReserved` property.
This PR adds the `allowReserved` property to the `Linter.ParserOptions` and updates local typedefs of `ParserOptions` to import the TypeScript type instead of the internal type from `lib/shared/types.js` (which does include the property).
`allowReserved` is …
> fix: add `allowReserved` to `Linter.ParserOptions` type

- lib/services/suppressions-service.js
- the suppressions system introduced by https://github.com/eslint/eslint/pull/19159 doesn't enforce a consistent ordering of filenames or rule identifiers
- this can cause unnecessary `git` churn and even `git` conflicts when multiple contributors to a project submit changes that include generated changes to the eslint-suppressions.json file
- this PR uses the pre-existing dependency upon https://www.npmjs.com/package/json-stable-stringify-without-jsonify to sort the keys in the suppressions data just prior to writing the JSON file
- nope
- the existing test coverage for suppressions passes without issues
> fix: sort keys in eslint-suppressions.json to avoid git churn

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Updates type `Linter.ESLintParseResult` with the correct name of the `service` property.
This PR replaces the incorrect property name `parserServices` with `services` in the properties of the `Linter.ESLintParseResult` type. This is the return type of `parseForESLint()`. The correct property name is `services`. …
> fix: correct `service` property name in `Linter.ESLintParseResult` type

- docs/src/use/integrations.md
Adding Neovim to the editor integrations information.
Nope.
> docs: Add Neovim to editor integrations

- lib/languages/js/source-code/source-code.js
Hello, 
In this PR, I've correct types and tighten type definitions in `SourceCode` class.
Some types were incorrect, and others were too loosely defined, so I’ve corrected them.
> fix: correct types and tighten type definitions in `SourceCode` class

- conf/rule-type-list.json
- docs/src/_data/rules.json
Hello,
While looking into [`replacements.json`](https://github.com/eslint/eslint/blob/main/conf/replacements.json#L18-L20), I noticed that `space-in-brackets` was replaced by `object-curly-spacing`, `array-bracket-spacing`, and `computed-property-spacing`.
However, `computed-property-spacing` was missing from both …
> fix: correct mismatched removed rules

- docs/src/pages/flags.md
- lib/cli.js
- lib/eslint/eslint.js
- lib/shared/flags.js
- tests/lib/cli.js
- tests/lib/eslint/eslint.js
Added the ability to set `ESLINT_FLAGS` environment variable to set flags in the CLI.
fixes #19100
> feat: Allow flags to be set in ESLINT_FLAGS env variable

- docs/src/use/configure/configuration-files.md
It was bothering me that under the heading of "Specifying `files` and `ignores`" we didn't have an example that showed `files` and `ignores` immediately. So I added than and cleaned up some of the wording around it.
> docs: Clean up configuration files docs

- docs/src/rules/no-return-await.md
Upfront recommendation in the docs against not using this rule anymore.
A lot of rules have valid reasons to not use them, but in this case I don't see any reason anymore to even entertain this rule. Since this was a rule that made sense previously, it would be nice if now referencing it or glancing back at it, that it would …
> docs: upfront recommend against using the no-return-await rule

- lib/types/rules.d.ts
https://github.com/eslint/eslint/issues/19721#issuecomment-2898098135
Modify curly types as per @ntnyq.
There's 47 other conflicting types between `eslint-typegen`'s output and `eslint/rules`. I think that means we should automate the creation of `eslint/rules`, but it's notable that `eslint-typegen`'s output has much less …
> fix: curly types

- docs/src/rules/no-unassigned-vars.md
- lib/rules/no-unassigned-vars.js
- tests/lib/rules/no-unassigned-vars.js
This PR fixes a false positive in the `no-unassigned-vars` rule that occurred when using `let` or `var` declarations inside `declare module` blocks in TypeScript.
Such declarations are part of module interface definitions and are not expected to be assigned. However, the rule currently does not account for the `declare` modifier …
> fix: avoid false positive in `no-unassigned-vars` for declare module

- docs/src/extend/scope-manager-interface.md
`implicit` field of the global scope was not described in the Scope Manager Interface docs.
Updated the docs with this field. Also fixed the `node` type for `ImplicitGlobalVariable` defs.
> docs: add global scope's `implicit` field to Scope Manager docs

- lib/rules/no-use-before-define.js
This PR adds the missing `language` and `dialects` properties to the meta object of `no-use-before-define`. The rule was updated to support TypeScript syntax in #19566, but we forgot to add the new fields.
> fix: add `language` and `dialects` to `no-use-before-define`

- lib/languages/js/source-code/source-code.js
- tests/lib/languages/js/source-code/source-code.js
Hello,
In this PR, I've improved the time complexity of `getLocFromIndex`.
> 1. We should be caching every index's location after it's calculated.
> 1. We should keep track of every index that begins a new line when we find it
> 1. We may be able to use the loc property on nodes to cheat when calculating some locations
> 1. …
> perf: improve time complexity of `getLocFromIndex`

- tests/fixtures/code-path-analysis/if-4.js
- tests/fixtures/code-path-analysis/if-5.js
- tests/fixtures/code-path-analysis/switch--cases-2.js
- tests/fixtures/code-path-analysis/try--try-catch-3.js
- tests/fixtures/code-path-analysis/try--try-catch-finally-2.js
- tests/fixtures/code-path-analysis/try--try-catch-finally-3.js
- tests/fixtures/code-path-analysis/try--try-finally-2.js
- tests/fixtures/code-path-analysis/try--try-finally-4.js
- tests/fixtures/code-path-analysis/try--try-finally-5.js
- tests/lib/linter/code-path-analysis/code-path-analyzer.js
- tests/lib/linter/code-path-analysis/code-path.js
Updates code path analysis tests to use `Linter` in flat config mode instead of eslintrc mode. We'd need to do this sooner or later since the eslintrc mode will be removed in ESLint v10.
Updated `code-path.js` and `code-path-analyzer.js` tests.
> test: switch to flat config mode in code path analysis tests

- lib/services/suppressions-service.js
- tests/bin/eslint.js
When using --prune-suppressions, remove suppressions for files that don't exist on disk.
Fixes #19778
> feat: prune suppressions for non-existent files

- docs/src/extend/rule-deprecation.md
Clarify that the rule `meta.deprecated` property can be provided as either a boolean or an object.
The current documentation is conflicting:
- https://eslint.org/docs/latest/extend/custom-rules indicates that the property can be a boolean or an object
> deprecated: (boolean | DeprecatedInfo) Indicates whether the rule has been …
> docs: clarify that boolean is still allowed for rule `meta.deprecated`

- lib/shared/runtime-info.js
- tests/lib/shared/runtime-info.js
Modified the `--env-info` command to use `process.version` instead of spawning `node --version` to get the Node.js version.
Fixes #19848
> fix: use `process.version` in `--env-info`

- lib/rules/utils/ast-utils.js
- tests/lib/rules/no-array-constructor.js
- tests/lib/rules/no-object-constructor.js
Node version: v24.2.0
npm version: v11.3.0
Local ESLint version: v9.24.0 - v9.29.0
Global ESLint version:
Operating System: darwin 24.5.0
[ ] `@typescript-eslint/parser`
[ ] …
> fix: remove unnecessary semicolon from fixes

- lib/rules/no-unused-vars.js
Description:  
Corrects a typo in the comment within the no-unused-vars rule, improving code clarity and documentation.
> docs: typo in comment for unused variables handling

- docs/src/rules/no-duplicate-imports.md
- lib/rules/no-duplicate-imports.js
- lib/types/rules.d.ts
- tests/lib/rules/no-duplicate-imports.js
Added a new allowSeparateTypeImports option to the no-duplicate-imports rule that allows a type import alongside a value import from the same module in TypeScript files.
Closes #19834
> feat: add `allowSeparateTypeImports` option to `no-duplicate-imports`

- lib/languages/js/source-code/source-code.js
- tests/lib/languages/js/source-code/source-code.js
Hello,
In this PR, I've added handling logic for `null`-type `loc` to the `getIndexFromLoc` method.
Currently, passing `null` to `getIndexFromLoc` results in an unrelated error because accessing `loc.line` throws when `loc` is `null`.
So, I’ve updated the error message to more precisely indicate that an incorrect type was passed …
> fix: handle `null` type `loc` in `getIndexFromLoc` method

- docs/src/rules/valid-jsdoc.md
The usejsdoc.org is redirecting to a gambling site, can you check on that.
Check the usejsdoc url its redirecting to a gambling site.
> docs: update jsdoc's link

- docs/src/rules/no-const-assign.md
- lib/rules/no-const-assign.js
- lib/types/rules.d.ts
- tests/lib/rules/no-const-assign.js
Refs #19792, adds support for explicit resource management to the `no-const-assign` rule.
Updates the `no-const-assign` rule to report on modifying `using` and `await using` variables.
> feat: support explicit resource management in `no-const-assign`

- docs/src/rules/init-declarations.md
- lib/rules/init-declarations.js
- tests/lib/rules/init-declarations.js
Refs #19792, adds support for explicit resource management to the `init-declarations` rule.
Updated the `init-declarations` rule to not report on initializing `using` and `await using` variables when the option is `"never"`, because these variables must be initialized.
> feat: support explicit resource management in `init-declarations`

- docs/src/rules/no-undef-init.md
- lib/rules/no-undef-init.js
- tests/lib/rules/no-undef-init.js
Refs #19792, adds support for explicit resource management to the `no-undef-init` rule.
Updates the `no-undef-init` rule to not report on initializing `using` and `await using` variables to `undefined`.
Omitting the initializer would be a syntax error. Whether or not it makes sense to unconditionally initialize `using` and …
> feat: support explicit resource management in `no-undef-init`

- docs/src/rules/no-loop-func.md
- lib/rules/no-loop-func.js
- tests/lib/rules/no-loop-func.js
Refs #19792, adds support for explicit resource management to the `no-loop-func` rule.
Updates the `no-loop-func` rule to not report on references to `using` and `await using` variables, because they are constant.
For `using`/`await using` variables declared inside the loop body, it might make sense to warn when they are …
> feat: support explicit resource management in `no-loop-func`

- docs/src/use/configure/ignore.md
The odd sentence was missed in #19487. This PR brings those parts in line with the current examples which use `globalIgnores()`.
> docs: fix mismatch between `globalIgnores()` code and text

- lib/eslint/eslint.js
- tests/fixtures/emfile/eslint.config.js
- tools/check-emfile-handling.js
Added retry logic to the `outputFixes` method to handle EMFILE errors when writing autofix results. This prevents ESLint from crashing if the system runs out of file descriptors during autofix operations.
Fixes #19924
> fix: retry on EMFILE when writing autofix results

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Fix #19942
This PR removes oudated types `ParserOptions.ecmaFeatures.experimentalObjectRestSpread`.
> fix: remove outdated types in `ParserOptions.ecmaFeatures`

- tests/lib/rules/utils/ast-utils.js
Updates ast-utils tests to use `Linter` in flat config mode instead of eslintrc mode. We'd need to do this sooner or later since the eslintrc mode will be removed in ESLint v10.
Updated `ast-utils.js` tests.
> test: switch to flat config mode in `ast-utils` tests

- lib/types/index.d.ts
Simplify type definitions.
Refs: eslint/rewrite#177
Related PRs: eslint/css#203, eslint/json#121, eslint/markdown#471
* Refactored the type definition of `JSRuleDefinition` using the core [`CustomRuleDefinitionType`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L598-L631) type.
* Redefined …
> refactor: use `CustomRuleDefinitionType` in `JSRuleDefinition`

- tests/tools/eslint-fuzzer.js
- tools/eslint-fuzzer.js
- tools/fuzzer-runner.js
Updates eslint-fuzzer to use `Linter` in flat config mode instead of eslintrc mode. We'd need to do this sooner or later since the eslintrc mode will be removed in ESLint v10.
Updated eslint-fuzzer and its tests to use Linter in flat config mode.
> test: switch to flat config mode in eslint-fuzzer

- Makefile.js
- knip.jsonc
- tools/generate-formatter-examples.js
Updates release process to use `ESLint` class instead of the old `CLIEngine` class when generating formatters docs.
Extracted generating formatters docs into a separate file to be able to run it synchronously and updated it to use the `ESLint` class. This ensures correctness of formatter examples in ESLint v9 (when using the …
> build: use `ESLint` class to generate formatter examples

- tools/check-emfile-handling.js
**Problem**: 
On Linux and macOS, the command ulimit -n checks the maximum number of files that can be opened at one time. However, if this setting is set to "unlimited," the script will try to convert the string "unlimited" to a number and will fail (resulting in NaN) and will not correctly calculate the number of files to use …
> fix: Fixed potential bug in check-emfile-handling.js

- docs/.eleventy.js
Enabled `open in playground` button for TypeScript code examples.
Can be merged once https://github.com/eslint/eslint.org/pull/714 is finished.
> docs: playground button for TypeScript code example

- docs/src/use/configure/configuration-files.md
Updated text from "by add a rules property" to "by adding a rules property"
changed "by add a rules property" to "by add**ing** a rules property"
> docs: fix typo in the "Configuring Rules" section

- docs/src/use/core-concepts/index.md
Spelling error sharable -> shareable
- [x ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Fixed a spelling error: sharable -> shareable
> docs: Fix typo in core-concepts/index.md

- .github/workflows/stale.yml
Hi,
Currently, the `stale.yml` workflow is not working for the following reasons:
https://github.com/eslint/eslint/actions/runs/16978244500
---
I think this error is caused by a mismatch between the top-level permissions and the reusable workflow's permissions.
The top-level permissions are set to `read`, but the reusable …
> ci: fix `stale.yml`

- lib/rules/no-loss-of-precision.js
- tests/lib/rules/no-loss-of-precision.js
Fixed https://github.com/eslint/eslint/issues/19957
> fix: allow scientific notation with trailing zeros matching exponent

- lib/types/rules.d.ts
Fixes types for the `patterns` option of the `no-restricted-imports` rule.
* A patterns object should be valid without either of `importNames`, `importNamePattern`, `allowImportNames` or `allowImportNamePattern` specified. For example, `"no-restricted-imports": [2, { patterns: [{ group: ["foo"] }] }]` was invalid before this …
> fix: correct types for `no-restricted-imports` rule

- lib/types/index.d.ts
- tests/lib/types/types.test.ts
Fix types
refs #18771
Added `before` and `after` properties to test case base type (`RuleTester.ValidTestCase`). Support for `before` and `after` in test cases was added in [ESLint v9.12.0](https://github.com/eslint/eslint/releases/tag/v9.12.0) following the proposal in [this RFC …
> fix: add `before` and `after` to test case types

- lib/rules/no-eval.js
- lib/rules/strict.js
Updated rules to use `context.languageOptions.parserOptions` instead of deprecated `context.parserOptions`.
> refactor: remove deprecated `context.parserOptions` usage across rules

- lib/rules/no-empty-static-block.js
- tests/lib/rules/no-empty-static-block.js
- Added fixable suggestions to insert `/* empty */` inside empty static blocks.
- Updated highlighting so that only the opening and closing braces `{}` are marked, instead of the entire static block.
Closes #20054
> feat: implement suggestions for no-empty-static-block

- tests/fixtures/configurations/cwd/eslint.config.js
- tests/lib/eslint/eslint.js
Removes `tests/lib/eslint/eslint.config.js` fixture config file. When lookup from config file becomes default behavior in v10, this config would apply to files in `tests/lib/eslint/` when linting this project, which is not what we want. Also, it seems that VSCode by default already applies the nearest config file, so I was …
> test: remove `tests/lib/eslint/eslint.config.js`

- packages/eslint-config-eslint/package.json
Updates `eslint` peer dependency in the `eslint-config-eslint` package. Since the config now enables the new `preserve-caught-error` rule which has been added in just-released ESLint v9.35.0, the range needs to be updated to `^9.35.0`. 
Updated eslint-config-eslint's package.json.
> chore: update `eslint` peer dependency in `eslint-config-eslint`

- lib/rules/preserve-caught-error.js
- lib/types/rules.d.ts
This PR refactors `preserve-caught-error` to use `meta.defaultOptions` instead of a manual `|| {}` fallback.
> refactor: use `meta.defaultOptions` in `preserve-caught-error`

- eslint.config.js
Updates eslint config for this project to disallow use of deprecated `type` property in core rule tests.
Refs https://github.com/eslint/eslint/issues/19029, https://github.com/eslint/eslint/pull/20093.
Configured `no-restricted-syntax` to disallow the mentioned use of deprecated `type` property.
This won't be able to catch all …
> chore: disallow use of deprecated `type` property in core rule tests

- lib/rules/no-misleading-character-class.js
- lib/rules/require-unicode-regexp.js
This PR refactors `no-misleading-character-class` and `require-unicode-regexp` to use `defaultOptions` instead of runtime fallbacks.
> refactor: use `defaultOptions` in rules

- lib/types/rules.d.ts
This PR adds the missing rule option types in `rules.d.ts`.
Related links:
- https://eslint.org/docs/latest/rules/id-match
- https://eslint.org/docs/latest/rules/id-length
Besides, does ESLint accept rule option changes for deprecated rules? 
Cause there are many missing rule option types for them.
> fix: add missing rule option types

- lib/rules/preserve-caught-error.js
- tests/lib/rules/preserve-caught-error.js
Node version: v22.19.0
npm version: v10.9.3
Local ESLint version: v9.35.0 (Currently used)
Global ESLint version: v9.35.0
Operating System: darwin 24.6.0
[ ] …
> feat: correct `preserve-caught-error` edge cases

- lib/rules/preserve-caught-error.js
- tests/lib/rules/preserve-caught-error.js
The `preserve-caught-error` rule was producing false positives when a caught error was re-thrown using a quoted or computed static `"cause"` key. For example:
```js
try {
doSomething();
} catch (error) {
throw new Error("Something failed", { "cause": error });
}
```
Previously, the rule only recognized unquoted identifier keys …
> feat: `preserve-caught-error` should recognize all static "cause" keys
