docs/rules/id-match.md
The documentation is making use of a non ascii character to delimit the citation from its author. As the file is not utf-8 encoded, it ends up with the missing character glyph when displayed. This PR sets the correct encoding (UTF-8) on the file.
=> Fix: use correct encoding for id-match.md (fixes #3246)

lib/eslint.js, tests/lib/eslint.js, tests/lib/rules/no-invalid-this.js
Fixes #3254.
I found there is the same problem at `CatchClause`, I fixed it.
=> Fix: `context.getScope()` in blockBindings

lib/rules/accessor-pairs.js, tests/lib/rules/accessor-pairs.js
Fixes #3262.
Checks whether or not each object literal is a property descriptor.
=> Fix: `accessor-pairs` false positive

docs/user-guide/command-line-interface.md, lib/formatters/unix.js, tests/lib/formatters/unix.js
I wrote the formatter described in #2991 and the tests for it, and released it under the same free license as eslint. I hope you will consider distributing it with eslint, as it follows a standardized format adopted by most linters and editors.
=> New: added unix-style formatter (fixes #2991)

lib/rules/no-invalid-this.js, tests/lib/rules/no-invalid-this.js
=> Fix: `no-invalid-this` had been missing jsdoc comment.

lib/eslint.js, tests/lib/eslint.js
Fixes #2134.
- `es6` enables es6 features.
- `node` enables `globalReturn`.
This logic is simple searching with regular expressions.
=> Fix: `eslint-env` in comments had not been setting `ecmaFeatures`

lib/rules/indent.js, tests/lib/rules/indent.js
This might be a bit of a blatant fix but didn't break any existing tests so I guess it is okay.
=> Fix: Indent rule errors if an array literal starts a new statement (fixes #3328)

docs/rules/README.md
Remove "off by default" that has no meaning since all rules are off by default since 1.0.0.
=> Docs: remove note outdated in 1.0.0

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
fixes #3370 
For the case of imports with a default import and multiple named imports, the rule was only checking the last specifier. This change makes it check the first named import and last named import specifiers' tokens instead.
For any existing tests with the format `import defaultImport, {onlyOneNamedImport} from x` I added an additional test with the format `import defaultImport, {oneNamedImport, anotherNamedImport} from x`.
=> Fix: object curly spacing incorrectly warning for import with default and multiple named specifiers

docs/rules/linebreak-style.md
Add a "Compatibility" section to the linebreak-style rule documentation. In JSCS the rule is called 'validateLineBreaks' and it would be helpful for people migrating to ESLint to know this.
=> Docs: Add "Compatibility" section to linebreak-style

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
For #3324 
Depends on https://github.com/eslint/espree/pull/186 being merged first + new version
=> Fix: trailing commas in object-curly-spacing for import/export (fixes #3324)

package.json
I'm torn between a `Fix:` tag and an `Upgrade:` tag. I preferred `Fix:` since it resolves an issue but okay with `Upgrade:` as well.
=> Upgrade: bump `espree` dependency to `2.2.4` (fixes #3403)

.travis.yml, docs/user-guide/command-line-interface.md, lib/config.js, lib/options.js, package.json, tests/lib/cli.js, tests/lib/config.js
This PR implements a new CLI feature discussed in https://github.com/eslint/eslint/issues/2543#issuecomment-102441119:
> It might make sense to let `-c` accept a shareable config
For example, if a sharable config `eslint-config-foo` is installed in the project's `node_modules` directory, `eslint` CLI can directly load it with the `--config` flag like below:
```
eslint --config foo .
```
or,
```
eslint --config eslint-config-foo .
```
=> New: enable `-c` flag to accept a shareable config (fixes: #2543)

lib/rules/no-duplicate-case.js, tests/lib/rules/no-duplicate-case.js
In EcmaScript after the `case` token there can be any valid expression,
in particular this switch was raising a false `no duplicate case` positive:
```
switch(['a','b'].toString()){
case (['a','b']).toString():
console.log('right');
break
case (['a']).toString():
console.log('not right');
break
}    
```
in this case is because the [getHash function](https://github.com/eslint/eslint/blob/master/lib/rules/no-duplicate-case.js#L21-L35) does not handle ArrayExpression nodes;
the [if else cascade](https://github.com/eslint/eslint/blob/master/lib/rules/no-duplicate-case.js#L22-L34) exit without matching, so the function returns `undefined`.
This happens for every node types that isn't checked.
In order to fix this I wrote a more strong getHash function, which just serialize the AST expression …
=> Fixes `no duplicate case` for Array#toString (and possibly all un handled ES 2015 syntax)

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
=> Fix: `valid-jsdoc` test does not recognize aliases for `@param`

lib/rules/indent.js, tests/lib/rules/indent.js
May not be the greatest fix for #3329 but it at least avoids double checking Array and Object expressions with conflicting rules so fixing the "infinite" or "unfixable" state that is caused by setting the `VariableDeclarator` option.
Now I'd argue that this is also the expected behavior but I leave that decision to the reviewers and the author of the issue.
=> Fix: Indent rule errors with array of objects (fixes #3329)

docs/rules/no-multi-spaces.md
Fix typo in the documentation of no-multi-spaces
Works with eslint v1.0.0 and rule in .eslintrc
Refs #3298
=> Docs: Fix typo: exception label

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: exclude `AssignmentExpression` and `Property` nodes from extra indentation on first line

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
=> Fix: "key-spacing" crashes eslint on object literal shorthand properties

docs/rules/spaced-comment.md, lib/rules/spaced-comment.js, tests/lib/rules/spaced-comment.js
=> Update: separate options for block and line comments in `spaced-comment` rule

docs/rules/id-length.md, lib/rules/id-length.js, tests/lib/rules/id-length.js
As discussed in #3450, thanks!
=> Added "properties" option to `id-length` rule to ignore property names

lib/rules/sort-vars.js, tests/lib/rules/sort-vars.js
Fixes #3474
Also, a good follow-up would be to add checking inside destructuring patterns.
=> Fix: sort-vars rule fails when memo is undefined

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: `indent` rule does not indent when doing multi-line chain calls

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: `indent` shouldn't check the last line unless it is a punctuator

lib/rules/prefer-template.js, tests/lib/rules/prefer-template.js
Fixes #3507.
Now, `TemplateLiteral` nodes are handled as literal.
So concatenations of template strings and strings are not warned by this rule.
=> Fix: `prefer-template` had not been handling TemplateLiteral as literal node

lib/rules/no-empty-label.js, tests/lib/rules/no-empty-label.js
=> Update: Add quotes around the label in  `no-empty-label` error reports

docs/rules/operator-linebreak.md, lib/rules/operator-linebreak.js, tests/lib/rules/operator-linebreak.js
=> Fix: Detect ternary operator in operator-linebreak rule

docs/developer-guide/shareable-configs.md
Added in documentation on how a package can dynamically use extends from local files.
Might resolve #3102 for certain use cases.
=> Docs: Added information on dynamic package configs and local config resolution (refs #3102)

lib/rules/quote-props.js, tests/lib/rules/quote-props.js
=> Fix: `quote-props` rule should ignore computed and shorthand properties

lib/rules/no-inline-comments.js, tests/lib/rules/no-inline-comments.js
I'd like to be able to use inline comments to disable eslint rules, but to disallow any other type of inline comment.
This change allows that configuration.
=> Allowing inline comments to disable eslint rules.

docs/rules/no-constant-condition.md
Seems worthwhile to show `for(;;)` as a legal way to do an infinite loop under this rule (and it is called out as a valid case in the unit tests for this rule).
No issue available.
=> Docs: Including for(;;) as valid case in no-constant-condition

conf/environments.js, package.json
=> Update: Use `globals` module for the `commonjs` globals (fixes #3606)

README.md, docs/developer-guide/shareable-configs.md, docs/developer-guide/working-with-plugins.md, docs/rules/comma-style.md, docs/user-guide/command-line-interface.md
npmjs.org has been moved to npmjs.com now.
=> Docs: Replace to npmjs.com

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: `indent` should only indent chain calls if the first call is single line

lib/rules/quote-props.js, tests/lib/rules/quote-props.js
```bash
$> eslint -v
v1.3.1
```
Having the following `.eslintrc`:
```json
{
"ecmaFeatures": {
"experimentalObjectRestSpread": true
},
"rules": {
"quote-props": [2, "consistent"]
}
}
```
And using object rest spread syntax:
```javascript
var x = {a: 1};
({...x});
```
Results in the following stacktrace when running `eslint`:
```bash
/Code/node_modules/eslint/lib/rules/quote-props.js:130
if (key.type === "Literal" && typeof key.value === "string") {
^
TypeError: Cannot read property 'type' of undefined
at /Code/node_modules/eslint/lib/rules/quote-props.js:130:20
at Array.forEach (native)
at checkConsistency (/Code/node_modules/eslint/lib/rules/quote-props.js:122:25)
at EventEmitter.ObjectExpression (/Code/node_modules/eslint/lib/rules/quote-props.js:171:17)
at emitOne (events.js:77:13)
at …
```
=> Fix: `quote-props` should not crash for object rest spread syntax (fixes #3595)

conf/eslint.json, docs/rules/README.md, docs/rules/space-before-keywords.md, lib/rules/space-before-keywords.js, tests/lib/rules/space-before-keywords.js
Enforce spacing before keywords... 
* `if`, `else`, `for`, `while`, `do`, `switch`, `try`, `catch`, `finally`, `with`, `return` and `throw` (w.r.t. [space-after-keywords](eslint/blob/master/lib/rules/space-after-keywords.js) and [space-return-throw-case](eslint/blob/master/lib/rules/space-return-throw-case.js))
* as well as `function`, `yield`, `class`, `super`, variable declarations and label statements
=> New: `space-before-keywords` rule (fixes #1631)

docs/user-guide/command-line-interface.md, lib/cli.js, lib/options.js, tests/fixtures/max-warnings/.eslintrc, tests/fixtures/max-warnings/six-warnings.js, tests/lib/cli.js, tests/lib/options.js
User can now specify `--max-warnings` CLI option. If no errors are found but warning count exceeds the specified value, ESLint will exit with an error. If option is not specified, ESLint will continue to exit with an error if and only if at least one error is found in linted files.
Fixes #2769. Includes unit tests and docs.
=> New: Add --max-warnings flag to CLI (fixes #2769)

lib/rules/no-dupe-keys.js, tests/lib/rules/no-dupe-keys.js
At Facebook, our linters only warn you about issues on lines that you changed. This caused an issue for us because the line number for a duplicate key in an object had the line number of the *start* of the object instead of the actual duplicate key. For example:
```javascript
var foo = { // this was where the error was reported
bar: 1,
// ...
// possibly many other lines here
// ...
bar: 1, // this line was added
};
```
=> Fix: line number for duplicate object keys error (fixes #3573)

.eslintrc, docs/rules/no-useless-concat.md, docs/rules/prefer-template.md, lib/ast-utils.js, lib/rules/no-useless-concat.js, lib/rules/prefer-template.js, tests/lib/rules/no-useless-concat.js, tests/lib/rules/prefer-template.js
Fixes #3575, #3589.
- Removed handling literals of non strings from `no-useless-concat`.
- Added covering those into `prefer-template`.
- Added `isStringLiteral` utility into ast-utils.js.
- Added `no-useless-concat` into `.eslintrc` for ESLint project.
cc/ @hzoo @Dashed
=> Fix: `no-useless-concat` false positive at numbers

.gitignore, Makefile.js, docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, lib/cli-engine.js, lib/cli.js, lib/options.js, package.json, tests/fixtures/cache/src/fail-file.js, tests/fixtures/cache/src/test-file.js, tests/lib/cli-engine.js, tests/lib/cli.js, tests/lib/file-finder.js
This is the first draft of adding a cache to Eslint.
- The basic detection of a changed file is deferred to file-entry-cache.
- The file cache is stored in the current working directory (`process.cwd()`) where the command is executed. The file created is called `.eslintcache`
- The cache only stores files that successfully passed validation. The ones that failed are removed to guarantee they will be processed the next run.
an easy way to test is run this in the project
```bash
./bin/eslint.js lib/ --cache # this will take 3.5s aprox
./bin/eslint.js lib/ --cache # this will take 150ms aprox. Obviously because the results are cached
./bin/eslint.js lib/ --cache # this will take 200ms aprox. 
```
=> New: Implement cache in order to only operate on changed files since previous run. (fixes #2998)

lib/rules/quote-props.js, tests/lib/rules/quote-props.js
Changes made:
- Crete a test to check if the following code returns an error as described in [ESLint docs][1]:
```js
/*eslint quote-props: [2, "consistent-as-needed", {"keywords": true}]*/
var x = {
while: 1, // `while` is a reserved word. This should return an error but it doesn't.
volatile: "foo"
};
```
- Implement behavior to return an error if previous case occurs
[1]: http://eslint.org/docs/rules/quote-props.html#consistent-as-needed
Fixes #3636
=> Fix: `consistent-as-needed` mode with `keyword: true` (fixes #3636)

docs/rules/README.md, docs/rules/no-unneeded-ternary.md, lib/rules/no-unneeded-ternary.js, tests/lib/rules/no-unneeded-ternary.js
Add ability to check for `x ? x : y` pattern, which can be rewritten as `x || y`. Adds `noDefaultAssignment` option to `no-unneeded-ternary` rule. Defaults to off for backwards compatibility. Closes #3232.
=> Update: Check for default assignment in no-unneeded-ternary (fixes #3232)

docs/developer-guide/working-with-plugins.md
Pretty self-explanatory. Fixes #3648.
=> Docs: Fixing typos in plugin processor section. (fixes #3648)

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: Indent rule VariableDeclarator doesn't apply to arrow functions

lib/rules/comma-dangle.js, tests/lib/rules/comma-dangle.js
Fixes #3627.
I refactored this rule for simple flow.
=> Fix: `comma-dangle` with `"always"`/`"always-multiline"` false positive after a rest element

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
Fixes #3658.
I refactored:
- I merged processes of `ObjectExpression` and `ObjectPattern`.
- I simplified the process of `ImportDeclaration`.
- I fixed missing process of a tailing comma for `ExportNamedDeclaration`.
- And I made using `SourceCode` object.
=> Fix: `object-curly-spacing` had been crashing on an empty object pattern

lib/cli-engine.js, tests/lib/cli-engine.js
=> Fix: Incorrectly warning about ignored files

docs/developer-guide/working-with-rules.md, lib/eslint.js, tests/lib/eslint.js
Also added a bunch of unit tests which do pass under the old version of the code, to show previously undocumented assumptions.
Some other notes:
1. I intentionally moved the message interpolation code *below* the code that checks if the rule is even on in the first place. I didn't see a lot of point in running regexes over the message if it wasn't even going to be used. If this is a problem, I can move it back.
2. Rather than iterating over keys and constructing a `new RegExp` each time, I chose to run a general regex over the whole pattern and do lookup from there. I [tested on jsperf][1] and it said my approach was loads faster, but I don't know how good my test cases are and furthermore I was testing my browser rather than Node. If anyone has any good tips on how to perf-test in Node, …
=> Fix: Allow leading/trailing whitespace in rule message parameters. (fixes #3690)

.eslintrc, lib/rules/eqeqeq.js, tests/lib/rules/eqeqeq.js
=> Fix: Eqeqeq rule with no option does not warn on 'a == null' (fixes #3699)

lib/eslint.js, tests/lib/eslint.js
I'm not sure if this is the best way to do it, but it fixes #3700 and doesn't break anything else. I've also added a unit test that fails without this change and passes with.
=> Fix: make getScope acquire innermost scope (fixes #3700)

Makefile.js
Using `.slice` to handle presence or absence of newline. Let me know if it's too magical.
Fixes #3706.
=> Build: check-commit now checks commit message length. (fixes #3706)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Fixes #3714.
`\b` (word boundary) could not be used to check boundaries if a variable name includes `$` at the edge.
So I make checking manually with espree.
=> Fix: `no-unused-vars` had been crashed at `/*global $*/`

docs/developer-guide/nodejs-api.md
Looks like this list got overlooked when `html` and `unix` were added.
=> Docs: Add new formatters to API docs

ISSUE_CREATE.md
I'd like to shorten the autoposting comment because I don't think people are reading it in its current state.
=> Docs: Shorten and simplify autocomment for new issues

lib/cli-engine.js, lib/cli.js, tests/lib/cli-engine.js
This change fixes both the documented parameter name and the default setting
in the configuration object for the `CLIEngine`. The CLI takes a `--cache`
argument, which gets translated into `useCache`, however the CLIEngine
defaulted to using `options.cache` but then checked for `options.useCache`.
Hopefully this should prevent other developers from being confused!
=> Fix CLIEngine default cache parameter

docs/user-guide/command-line-interface.md
Code fences must be on their own line.  Was causing the entire rest of the page to be rendered as code.
=> Docs: Fix closing code fence on cli docs

docs/rules/semi-spacing.md, lib/rules/semi-spacing.js, tests/lib/rules/semi-spacing.js
Fixes #3721.
I made `semi-spacing` ignoring spacing which is after semicolons if the semicolon is before a closing parenthesis (`}` or `)`).
=> Fix: `semi-spacing` had conflicted with `block-spacing`

docs/rules/no-lonely-if.md
Add examples to clarify that nested `if`-`else` is treated the same as a nested `if`.
=> Docs: Add if-else example (fixes #3722)

docs/rules/key-spacing.md, lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
=> Update: `key-spacing` should allow 1+ spaces before/after colon

docs/rules/block-scoped-var.md, tests/lib/rules/block-scoped-var.js
This addresses my concerns in #3791 about how the desired behaviour for variables redeclared in sibling blocks was unclear.
Added in a couple of extra examples of if/else in docs to clarify that blocks don't have to be direct descendants/ancestors of each other to count as outside scope.
Also added in a few more tests that ensure this behaviour is properly defined and tested.
=> Docs: add a couple more examples + tests for block-scoped-var (fixes #3791)

lib/rules/space-before-keywords.js, tests/lib/rules/space-before-keywords.js
Fixes #3756 (`class` keyword & object literal shorthand method).
=> Fix: `space-before-keywords` fails to handle class keyword & object literal shorthand method (fixes #3756)

tests/lib/cli-engine.js
Use `fs.realPathSync` to fix the tests when running in OSX
=> Fix: tests fail due to differences in temporary paths. (fixes #3778)

lib/rules/semi-spacing.js, tests/lib/rules/semi-spacing.js
Currently this fix just ignore whether the semicolon is spaced after or not if it's at the line beginning. Should we force a code style here too?
See #1983 for detailed discussion.
=> Fix: false alarm of semi-spacing with semi set to never

docs/rules/space-before-blocks.md, lib/rules/space-before-blocks.js, tests/lib/rules/space-before-blocks.js
Fixes #3769.
I made `space-before-blocks` ignoring spacing which is between `=>` and `{`.
I don't address #1338 in this PR.
I thought it can resolve #1338 that to ignore spacing merely if the previous token is a keyword.
But `class` keywords are not handled by `space-after-keywords`, so we need think about a ClassExpression `var Foo = class{ };`.
BTW, 72 is too short to include two rule names...
=> Fix: `space-before-blocks` had conflicted `arrow-spacing`

bin/eslint.js, docs/user-guide/command-line-interface.md, lib/options.js, tests/lib/options.js
Works the same as `DEBUG=eslint:*` without the funky syntax.
=> New: Add --debug flag to CLI (fixes #2692)

lib/config.js, tests/fixtures/config-hierarchy/overwrite-ecmaFeatures/.eslintrc, tests/fixtures/config-hierarchy/overwrite-ecmaFeatures/child/.eslintrc, tests/lib/config.js
Fixes #3735.
env-specified globals and ecmaFeatures had been handled after all
hierarchy configs merged. So it could not overwrite the parent config
with child's env-specified configs correctly.
This PR moves the process for env-specified config to the `loadConfig`
function. As the result, it can handle child's env-specified configs in
the regular overwriting process.
=> Fix: env-specified ecmaFeatures had been wrong

Makefile.js, docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, templates/formatter-examples.md.ejs
Adds a step to `gensite` to generate a page showing examples of all built-in formatters.
Also breaks apart lists of formatters in a few places, at @gyandeeps' suggestion in https://github.com/eslint/eslint/pull/3736#issuecomment-139436594.
I'm not sure if user-guide is the best place to put the new page, and whether or not you'd like a link to this new page in the menu or from anything other than those I've added to the formatters.  
Any feedback/suggestions would be welcome!
=> Build: Generate formatter example docs (fixes #3560)

docs/developer-guide/working-with-rules.md, lib/ast-utils.js, lib/rules/array-bracket-spacing.js, lib/rules/block-spacing.js, lib/rules/comma-spacing.js, lib/rules/computed-property-spacing.js, lib/rules/no-spaced-func.js, lib/rules/object-curly-spacing.js, lib/rules/semi-spacing.js, lib/rules/space-before-blocks.js, lib/rules/space-before-function-paren.js, lib/rules/space-before-keywords.js, lib/util/source-code.js, tests/lib/ast-utils.js, tests/lib/rules/no-spaced-func.js, tests/lib/rules/space-before-function-paren.js, tests/lib/util/source-code.js
Not sure about the function name, but `isTokenSpaced()` wasn't quite right, so I went with `isSpaceBetweenTokens()`. Alternative suggestions welcome.
=> Fix: space checking between tokens (fixes #2211)

docs/rules/space-before-blocks.md, lib/rules/space-before-blocks.js, tests/lib/rules/space-before-blocks.js
Add an optional configuration for `space-before-blocks` that allows the user to distinguish between a function's block and a keyword's block.
address #3758 
my local tests are suffering from #3778 but were otherwise fine.
changes i made:
- added branching logic to be able to detect if the block came from a function. this is accomplished by checking the type of the node's parent. after identification, the requirement for 'if a space is needed' is assigned based on the appropriate config option. 
- Backwards compatibility is supported: the user can enter both `always`/`never` to apply the check to both cases, or the newly added configuration object to apply the check to one or the other.
- added explanation in the docs with examples
- boatloads of tests to check nearly every path the user …
=> Update: Add configuration option to `space-before-blocks` (fixes #3758)

lib/cli-engine.js, tests/lib/cli-engine.js
cache will be skipped if 
- config changed
- plugins version changed
=> Fix: invalidate cache when config changes. (fixes #3770)

lib/rules/func-style.js, tests/lib/rules/func-style.js
Fixes #3819
I made the `func-style` rule ignoring arrow functions which have
`ThisExpression` even if it's `declaration` mode.
Incidentally, I replaced `context.getAncestors().pop()` with
`node.parent`.
=> Fix: `func-style` had been warning arrows with `this`

docs/rules/no-nested-ternary.md, docs/rules/no-ternary.md, docs/rules/no-unneeded-ternary.md
Adds references between all ternary rules.
=> Docs: Add related ternary links (refs #3835)

lib/rules/no-dupe-args.js, tests/lib/rules/no-dupe-args.js
Fixes #3867.
I changed the check process with using `escope.Variable`.
=> Fix: `no-dupe-args` had been wrong for nested destructuring

docs/rules/space-before-keywords.md, lib/rules/space-before-keywords.js, tests/lib/rules/space-before-keywords.js
Fixes #3789 to allow keywords to be preceded by an opening curly brace. For example, previously this would throw an error:
```js
/* eslint space-before-keywords: [2, "always"] */
<Foo onClick={function bar() {}} /> /*error Missing space before keyword "function".*/
```
Users should use the [block-spacing](/eslint/eslint/blob/master/docs/rules/block-spacing.md) rule if they wish to enforce keyword spacing in these types of scenarios.
The trade-off of offloading this to `block-spacing` is that if the user doesn't use `block-spacing` but has `space-before-keywords` enabled, the following would pass:
```js
/* eslint space-before-keywords: [2, "always"], block-spacing: 0 */
if (foo) {return bar; }
```
Ideally, to cater for these type of odd scenarios `block-spacing` could support similar …
=> Fix: `space-before-keywords`; allow opening curly braces (fixes #3789)

lib/rules/space-before-keywords.js, tests/lib/rules/space-before-keywords.js
Fixes #3854.
I made `space-before-keywords` ignoring methods, getters, and setters.
=> Fix: `space-before-keywords` had been wrong on getters

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
.eslintrc:
```json
{
"valid-jsdoc": [2, {
"prefer": {
"returns": "return"
}
}]
}
```
When jsdoc missing `@return` and `@returns`, warn message will be:
```
Missing JSDoc @return for function  valid-jsdoc
// NOT:
Missing JSDoc @returns for function  valid-jsdoc
```
=> Update: warn message use @return whe prefer.returns=return (refs #3872)

conf/environments.js, docs/user-guide/configuring.md, package.json, tests/fixtures/configurations/env-nashorn.json, tests/fixtures/globals-nashorn.js, tests/lib/cli.js
This PR adds new env `nashorn` to support the global variables of the Java 8 Nashorn JavaScript Engine.
=> Update: Add env 'nashorn' to support Java 8 Nashorn Engine (fixes #3874)

docs/rules/no-self-compare.md
`isNaN` gives surprising results unless you also check the `typeof` the variable is `number`. Explicitly calling this out in the documentation so people don't end up writing broken checks:
```
isNaN('derp') // true
isNaN({}); // true
isNaN(undefined) // true
```
=> Add note about typeof check for isNaN

Makefile.js, package.json
**Output:**
```sh
> node Makefile.js perf
CPU Speed is 2793 with multiplier 7500000
Performance Run #1:  1868.417686ms
Performance Run #2:  1840.1341579999998ms
Performance Run #3:  1878.664651ms
Performance Run #4:  1850.484123ms
Performance Run #5:  1843.7707209999999ms
Performance budget ok:  1850.484123ms (limit: 2685.2846401718584ms)
Load performance Run #1:  291.835235ms
Load performance Run #2:  290.304513ms
Load performance Run #3:  298.500252ms
Load performance Run #4:  292.96055ms
Load performance Run #5:  300.357205ms
Load Performance median :  292.96055ms
```
=> Build: Add load performance check inside perf function (fixes #3994)

lib/cli-engine.js, tests/lib/cli-engine.js
Sorry in advance for a PR that does not include any tests. The problem I came across was an extremely weird edge-case that I have not been able to reproduce manually. However, I think my fix is pretty simple and the rationale should make sense regardless.
At the point where my change has been made (ie: `executeOnFile()`), there is a `fs.realpathSync()` call that was throwing in the case described by #3978. The file in question was known by ESLint to be ignored, but the realpath call was happening before the early return. I've changed it to exit early once the file is known to be ignored, before running the risk of `fs.realpathSync()` throwing an uncaught exception.
I'm sure there are other (edge) cases where this `fs.realpathSync()` could throw in this small window, but this prevents …
=> Ignored files should not throw errors during CLI

lib/rules/no-invalid-this.js, tests/lib/rules/no-invalid-this.js
=> Fix: `no-invalid-this` had been missing globals in node

lib/rules/no-redeclare.js, lib/rules/no-shadow.js, tests/lib/rules/no-redeclare.js, tests/lib/rules/no-shadow.js
Fixes #3971.
When there is a special scope (`globalReturn` or `modules`), no longer
`no-redeclare` reports redeclarations of built-in globals. And when
that, `no-shadow` reports shadowing of built-in globals.
=> Fix: `no-redeclare` and `no-sahadow` for builtin globals

docs/rules/jsx-quotes.md
I went with `html` so there's still highlighting, but I can just remove the tag entirely if someone objects.
=> Docs: Re-tag JSX code fences (fixes #4020)

conf/environments.js, docs/user-guide/configuring.md, tests/fixtures/configurations/env-webextensions.json, tests/fixtures/globals-webextensions.js, tests/lib/cli.js
As per [Chrome’s documentation](https://developer.chrome.com/extensions/api_index), [Opera’s documentation](https://dev.opera.com/extensions/index.html), and [Firefox’s documentation](https://wiki.mozilla.org/WebExtensions), and the [globals project](https://github.com/sindresorhus/globals/pull/55).
=> Add WebExtensions globals.

docs/rules/curly.md, lib/rules/curly.js, tests/lib/rules/curly.js
Here is an attempt to add a `"consistent"` option to the `"curly"` rule. As it could be applied on any of the `"multi*"` options, I chose to add it as a flag in a separate option.
This patch makes the rule code slightly more complicated as we have to make an additional pass on the `if` branches to make sure no block statement appears in a branch below.
Let me know what you think about it. It may be usefull to have a `"consistent"` option without enforcing a particular style (no `"all"` nor `"multi"`...), but I'm not sure what would be the right way to do this: putting `null` as first option? or accepting `"consistent"` as first option?
=> New: add "consistent" option to the "curly" rule (refs #2390)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Fixes #4047.
If function expressions or arrow function expressions were exported,
these parameters had been not reported by `no-unused-vars`.
=> Fix: `no-unused-vars` had been missing some parameters

docs/rules/comma-dangle.md
Fix a minor misspelling (an -> a). Also, reading paragraphs is pretty hard in order to figure out options, so I refactored the options to be on a bullet list.
=> Improve comma-dangle documentation

lib/eslint.js, lib/rules/no-multi-spaces.js, tests/lib/eslint.js
Fixed both core and no-multi-spaces rule.
=> Fix: message templates fail when no parameters are passed (fixes #4080)

docs/rules/README.md
Seems like it's intended for the rules to be alphabetized but some are out of order.
=> Docs: Alphabetize Rules lists

docs/rules/lines-around-comment.md, lib/rules/lines-around-comment.js, tests/lib/rules/lines-around-comment.js
Added the following exceptions to the `lines-around-comment` rule:
* `allowObjectStart`
* `allowObjectEnd`
* `allowArrayStart`
* `allowArrayEnd`
See #2965
**Edit:** I updated the commit message to be less than 72 characters long, that seems to be a new requirement here. Not much I can fit in when `Update: "lines-around-comment" (fixes #2965)` already takes up 44/72 chars. :stuck_out_tongue:
=> Update: added exceptions for objects and arrays in `lines-around-comment` rule (fixes #2965)

docs/developer-guide/working-with-rules.md, lib/testers/rule-tester.js, tests/lib/testers/rule-tester.js
RuleTester now allows string errors for "invalid" test cases. Also added some test cases to prevent non-object, non-string errors and to ensure incorrect error messages result in assertion failures.
Diff looks a little weird in the `lib/testers/rule-tester.js` file. All I'm really doing is wrapping the existing assertions in an `if`/`else if`.
Also added some documentation. Hope it looks okay.
Fixes #4117.
=> Update: RuleTester allows string errors in invalid cases (fixes #4117)

lib/rules/prefer-arrow-callback.js, tests/lib/rules/prefer-arrow-callback.js
Fixes #4095.
The rule should not warn function expressions if these are use of implicit `arguments`, `super`, or `new.target`.
=> Fix: `prefer-arrow-callback` had been wrong at arguments

docs/developer-guide/shareable-configs.md
Adds missing single quote to docs. Same as: https://github.com/eslint/eslint.github.io/pull/150
=> Docs: Add missing single-quote

lib/rules/no-magic-numbers.js, tests/lib/rules/no-magic-numbers.js
Currently following code is considered as error: ```var foo = -42;```
I don't think it should
=> Fix: no-magic-numbers: variable declarations (fixes #4192)

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
:warning: **do not merge** :warning: Once #4219 is in, I'll rebase this on top of master.
Please take a look at lines 186 and 194 in the tests. These were previously testing that comma-first style was explicitly not supported. I'd like some confirmation that this is **not** a breaking change, that those tests were merely asserting a current behavior and not necessarily the intended behavior, which is what they've been changed to test.
=> Fix: Support comma-first style in key-spacing (fixes #3877)

conf/eslint.json, docs/rules/README.md, docs/rules/no-arrow-condition.md, lib/rules/no-arrow-condition.js, tests/lib/rules/no-arrow-condition.js
This PR implements the `no-arrow-condition` rule as discussed in #3280.
I took the majority of the code from [this plugin](https://github.com/Jxck/eslint-plugin-arrow-function) which I had already modified slightly for my personal use case to add an option I'll describe below. I thought it would be easier to discuss in this PR rather than #3280 since the tests/docs do the best job of explaining what the option does.
By default this rule will warn about any case where the author uses `=>` but the intent might not be clear.
```js
/*eslint no-arrow-condition: 2*/
/*eslint-env es6*/
// All lines will produce warnings
if (a => 1) {}
while (a => 1) {}
for (var a = 1; a => 10; a++) {}
a => 1 ? 2 : 3
(a => 1) ? 2 : 3
var x = a => 1 ? 2 : 3
var x = (a) => 1 ? 2 : 3
```
I added an option …
=> New: Add rule no-arrow-condition (fixes #3280)

lib/testers/rule-tester.js, tests/fixtures/testers/rule-tester/modify-ast-at-first.js, tests/fixtures/testers/rule-tester/modify-ast-at-last.js, tests/fixtures/testers/rule-tester/modify-ast.js, tests/lib/testers/rule-tester.js
Fixes #4156
I defined `@@ast-getter-before-run` and `@@ast-getter-after-run` rules to get AST.
This is working but implementation-dependent (`for-in` loop iterates properties in the same order as added).
If this is not accepted, I will think an other way.
=> Update: RuleTester come to check AST was not modified

docs/rules/README.md, docs/rules/comma-spacing.md, lib/rules/comma-spacing.js, tests/lib/rules/comma-spacing.js
I'm not sure how to handle the last cases with comments : 
```
{
code: "myfunc(404, true/* bla bla bla */ , 'hello');",
output: "myfunc(404, true/* bla bla bla */, 'hello');",
errors: [
{
message: "There should be no space before ','.",
type: "Punctuator"
}
]
},
{
code: "myfunc(404, true/* bla bla bla */ /* hi */, 'hello');",
output: "myfunc(404, true/* bla bla bla *//* hi */, 'hello');",
errors: [
{
message: "There should be no space before ','.",
type: "Punctuator"
}
]
}
```
doesn't work, it is removing the comments.
=> Add fix option to comma-spacing (fixes #4232)

docs/rules/eol-last.md, docs/rules/no-multiple-empty-lines.md, lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
Currently there is no way to specify a rule for having one (and only
one) ending newline. Using eol-last only checks if there is at least
one newline.
This patch adds an optional `maxEOF` option to no-multiple-empty-lines
rule. When set, blank lines at the end are treated differently from
lines within the file. When `maxEOF` is omitted, the rule's original
behaviour does not change.
For instance, requiring one and only one newline at the end of file can
be achieved using:
{
eol-last: 2,
no-multiple-empty-lines: [ 2, { max: 2, maxEOF: 1 } ]
}
=> Update: Add `maxEOF` to no-multiple-empty-lines (fixes #4235)

docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, lib/cli-engine.js, lib/cli.js, lib/options.js, tests/lib/cli-engine.js
This is a first pass. @nzakas I guess is done in a way that can be backwards compatible and won't require the introduction of a new --flag
but we might want to consider deprecating `--cache-file` and change it to `--cache-location`, since now that name makes more sense.
so basically:
```bash
eslint src/**/*.js --cache --cache-file='/Users/name/.eslintcache/' # notice the final `path.sep`
```
will create a cache file like this
```bash
/Users/name/.eslintcache/.cache_hashOfCWD # where hashOfCWD is the hash of the directory  /path/to/my/project
```
This will allow reuse a single location for the caches from different projects and still receive the benefits of the cache
=> Update: --cache-file can take a directory where to store the cache. Fixes #4241

docs/user-guide/configuring.md
Hey,
I've spent some time on debugging why files ignored by my .gitignore are not ignored by eslint and found out that rules like
```
*.min.js
```
doesn't work here if file is in subfolder. Rule which works both for .gitignore and .eslintignore is
```
**/*.min.js
```
There may be more differences, so I've added link to minimatch docs instead of listing them.
=> Update docs about using gitignore

tests/lib/util/glob-util.js
Removing the test for leading slash for now, because it's unclear what the correct behavior is here.
=> Fix: Make tests compatible with Windows (fixes #4315)

conf/eslint.json, docs/rules/README.md, docs/rules/no-case-declarations.md, lib/rules/no-case-declarations.js, tests/lib/rules/no-case-declarations.js
This rule disallows lexical declarations in case/default clauses.
=> New: Add no-case-declarations rule (fixes #4278)

docs/rules/semi.md
In the current state of the semi rules docs, the example code for not using semicolon is mispresented as a reason to use semicolon. Here is the original example code from the docs:
```js
return
{
name: "ESLint"
}
```
A person who always uses semicolons will expect that this will return an object, and will notice that there’s a semicolon missing. They might fix it, so that it looks like this:
```js
return
{
name: "ESLint"
};
```
Now, it makes perfect sense to a semicolon person, but what actually happens is that a `;` will be inserted after the `return`. Now, this is not a reason to use semicolons, but a reason to use ESLint to check for missing semicolons.
<br>
The current documentation also describe the effective behavior in the wrong way:
> Effectively, an object literal is created in …
=> Docs: Clarify that ASI can cause problem whether semicolons are used or not

lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
The message returned was a bit confusing as it says "Multiple blank lines not allowed." even when multiple blank lines are allowed. Minor update to the message to include the number of blank lines allowed.
=> Fix: Update the message to include number of lines (fixes #4342)

lib/rules/radix.js, tests/lib/rules/radix.js
This makes the radix rule disallow using the second parameter to parseInt
when it's 10. Other values are allowed.
=> Update: Make radix accept a "as-needed" option (fixes #4048)

docs/developer-guide/working-with-rules.md, lib/eslint.js, tests/lib/eslint.js, tests/lib/rule-context.js
Also updated docs to note that either node or loc (or both) must be supplied. Code will now throw clearer message if neither is supplied and will not throw TypeError if node is not supplied.
Fixes #4220.
Also, is this potentially a breaking change? I ask because it used to be impossible to report without a node, so formatters could probably implicitly assume that nodeType would be present. That is no longer the case. No tests failed so I assume the standard formatters are fine, but third-party formatters may potentially be broken with this change. Unlikely, I know, but wanted to raise the issue for your consideration.
Finally, I'd like to note that there is no test file for `lib/rule-context.js`. Most of those functions are passthroughs but some are not so straightforward (e.g., …
=> Fix: eslint.report can be called w/o node if loc provided (fixes #4220)

lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
Right now, if *no-multiple-empty-lines* has a `max` value of 1, the message reads:
> "More than 1 blank line**s** not allowed."
This PR singularizes "line" when `max` is 1:
> "More than 1 blank line not allowed."
=> Fix: Display singular/plural version of "line" in message

docs/rules/arrow-body-style.md, lib/rules/arrow-body-style.js, tests/lib/rules/arrow-body-style.js
Reverts eslint/eslint#4420 because it's a breaking change.
=> Revert "Update: Allow empty arrow body (fixes #4411)"

lib/rules/eqeqeq.js
Fixes #4423.
This provides an alternative fix for #4321 and will allow for a less risk-averse alternative to the change performed in #4329.
See #4373 for more info.
=> Fix: eqeqeq autofix avoids clashes with space-infix-ops (fixes #4423)

lib/rules/curly.js, tests/lib/rules/curly.js
Fixes #4362 
This rule is reporting correct error, but that location was the head of `IfStatement` node even if about `else` block.
I fixed the location of when it's `else` block.
=> Fix: `curly` warns wrong location for `else`

docs/rules/semi.md
no-space-before-semi is deprecated and replaced with semi-spacing, so link to that instead.
=> Replace link to deprecated rule with newer rule

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
While the options themselves are unchanged from the proposal in #4229, the behavior of the schema in this PR differs slightly from that of the example in the issue thread. The proposed schema would have allowed configuring the JSX exception in conjunction with `"function"` mode, which would never check JSX elements in the first place and could lead to confusion. The schema in this PR only permits configuring the JSX exception when the rule is in `"all"` mode and actually checking JSX elements.
I observed no performance difference of this PR compared to master.
=> Update: Add JSX exceptions to no-extra-parens (fixes #4229)

docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, lib/cli-engine.js, lib/cli.js, lib/eslint.js, lib/options.js, tests/fixtures/disable-inline-config.js, tests/lib/cli-engine.js, tests/lib/cli.js, tests/lib/eslint.js, tests/lib/options.js
Closes #3901.
This adds a `disallowInlineConfig` option, off by default, that disables
inline configuration in comments of a particular file.
This disable:
* `/*eslint-disable*/`
* `/*eslint-enable*/`
* `/*global*/`
* `/*eslint*/`
* `/*eslint-env*/`
=> New: Disallow inline rule configuration option

lib/ast-utils.js, lib/eslint.js, lib/rule-context.js, lib/rules/consistent-this.js, lib/rules/indent.js, lib/rules/lines-around-comment.js, lib/rules/new-cap.js, lib/rules/no-alert.js, lib/rules/no-catch-shadow.js, lib/rules/no-label-var.js, lib/rules/no-shadow.js, lib/rules/no-spaced-func.js, lib/rules/no-undef.js, lib/rules/no-use-before-define.js, lib/rules/operator-linebreak.js, lib/rules/space-before-function-paren.js, lib/rules/spaced-comment.js, lib/testers/rule-tester.js
This was separated from #3559 
- `RuleContext` method definitions are moved to outside of the constructor. `RuleContext` object is created many times, so that constructor should be as simple as possible. (`lib/rule-context.js`)
- Construction of a regular expression object which depends on rule's options is moved to outside of `getNodeIndent` function. The function is called many times and to create dynamic regular expression object is slow. (`lib/rules/indent.js`)
- Avoid calling `Function#apply` as possible. (`lib/eslint.js` and `lib/rule-context.js`)
- Avoid calling `SourceCode#getTokens`. A CPU Profiler said that function is slow a bit. (`lib/rules/no-spaced-func.js` and `lib/rules/space-before-function-paren.js`)
**Before** (`npm run perf` for multiple files)
```
CPU Speed is 3392 …
```
=> Fix: Improves performance (refs #3530)

lib/rule-context.js
This reverts the perf work in `rule-context.js`. All other perf changes remain.
=> Fix: Revert freezing context object (refs #4495)

lib/rules/no-spaced-func.js, tests/lib/rules/no-spaced-func.js
Fixes #4508
If the `callee` is enclosed with parentheses and arguments parentheses
are omitted, `no-spaced-func` had been crashed.
=> Fix: `no-spaced-func` had been crashed

lib/rules/eqeqeq.js, tests/lib/rules/eqeqeq.js
Finding range for ==/!= instead of assuming it is next token
Fixes #4540.
I'm open to feedback on whether there might be a simpler way for me to do what I'm doing. I found a way to get a good token array, but if SourceCode or token-store have other tricks I can do to make this even simpler, I would love to hear about it.
=> Fix: Bugfix for eqeqeq autofix (fixes #4540)

lib/rules/curly.js, tests/lib/rules/curly.js
Wanted to also include for-of, having done the work to add for-in to the `curly` rule.
=> Fix: Add for-of to `curly` rule (fixes #4571)

conf/eslint.json, docs/rules/README.md, docs/rules/yield-star-spacing.md, lib/rules/space-unary-ops.js, lib/rules/yield-star-spacing.js, tests/lib/rules/space-unary-ops.js, tests/lib/rules/yield-star-spacing.js
This change removes checking of yield* operators from the space-unary-ops rule, and adds a new yield-star-spacing rule to check spacing around the * in yield* expressions.
=> Breaking: Implement yield-star-spacing rule (fixes #4115)

lib/rule-context.js
This reverts commit bec6c9b0e2edca5f5bc99a7abc13b6f62a9a5411, which froze the context object and broke `eslint-plugin-react`. This is a performance enhancement plus security measure.
=> Breaking: Freeze context object (fixes #4495)

docs/user-guide/command-line-interface.md, docs/user-guide/configuring.md, lib/ignored-paths.js, tests/lib/ignored-paths.js
Pretty self-explanatory, extends the built-in ignore to include `bower_components/` . Docs & unit tests updated. Had to resubmit the PR as I had accidentally deleted my fork.
Original PR discussion can be found in #3552
=> Breaking: added bower_components to default ignore (fixes #3550)

Makefile.js, docs/rules/consistent-return.md, lib/config/config-initializer.js, lib/eslint.js, lib/formatters/checkstyle.js, lib/rules/callback-return.js, lib/rules/comma-spacing.js, lib/rules/consistent-return.js, lib/rules/consistent-this.js, lib/rules/key-spacing.js, lib/rules/no-alert.js, lib/rules/no-control-regex.js, lib/rules/no-implicit-coercion.js, lib/rules/space-unary-ops.js, lib/rules/vars-on-top.js, tests/lib/rules/consistent-return.js
Refs #3530, Fixes #3373.
This PR includes #3559.
I applied the code path analysis to the `consistent-return` rule.
If there were one or more `ReturnStatement`s which returned a value, this rule checks whether the last code path returns a value.
=> Fix: `consistent-return` comes to checking the last path.

CODE_OF_CONDUCT.md
This is based largely on the jQuery Code of Conduct, which some changes made to make it more appropriate for ESLint. As we don't have the strength of a foundation behind us, we aren't able to do some things, but I think the overall message here is clear.
=> Docs: Add Code of Conduct (fixes #3095)

docs/rules/no-extra-semi.md
=> Docs: no-extra-semi no longer refers to deprecated rule (fixes #4598)

lib/cli-engine.js, lib/util/source-code.js, packages/eslint-config-eslint/default.yml
Just want to make sure, I want to change the eslint-config-eslint package, right? Not the conf/eslint.json (which I believe represents "Recommended" rules)? Let me know if I goofed.
=> Build: Consume no-underscore-dangle allowAfterThis option (fixes #4599)

lib/config/config-file.js, package.json, tests/lib/config/config-file.js
Currently eslint will load the config stored in a project's package.json using `require`.  The downside to this is that the json is cached in `require.cache`.  Thus, if eslint is executed twice in the same process, and the config has changed in the interim, it will not read the new config.  For an example of this causing a downstream bug in the wild see https://github.com/AtomLinter/linter-eslint/issues/349
Closes #4611 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/eslint/eslint/4610)
=> Do not implicitly cache `package.json`

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
Previously, this rule would warn about excess parentheses even when they were syntactically significant and removing them would alter the meaning of a program. There are three applicable productions in the grammar with the restriction `[no LineTerminator here]`:
```
ReturnStatement[Yield]:
return [no LineTerminator here] Expression;
return [no LineTerminator here] Expression[In, ?Yield];
ThrowStatement[Yield]:
throw [no LineTerminator here] Expression[In, ?Yield];
YieldExpression[In]:
yield [no LineTerminator here] * AssignmentExpression[?In, Yield]
yield [no LineTerminator here] AssignmentExpression[?In, Yield]
```
If the expression following a `return`, `throw`, or `yield` is on a new line, it must be wrapped in parentheses, and this rule should not warn. It should, however, still check …
=> Fix: Handle forbidden LineTerminators in no-extra-parens (fixes #4229)

lib/rules/constructor-super.js, tests/lib/rules/constructor-super.js
Refs #3530.
This PR includes #3559.
I applied the code path analysis to the `constructor-super` rule.
If a class inherited a base class, this rule comes to checking whether the constructor calls `super()` once in every code path.
=> Fix: `constructor-super` with the code path analysis

lib/rules/no-fallthrough.js, tests/lib/rules/no-fallthrough.js
Refs #3530, Fixes #4246.
This PR includes #3559.
I applied the code path analysis to the `no-fallthrough` rule.
This rule comes to checking correctly `return`, `throw`, `break`, and `continue` in nested blocks.
=> Fix: `no-fallthrough` with the code path analysis

lib/rules/no-this-before-super.js, tests/lib/rules/no-this-before-super.js
Refs #3530.
This PR includes #3559.
I applied the code path analysis to the `no-this-before-super` rule.
This rule comes to checking whether it never use `this` and `super` before a call of `super()` in every code path of constructors.
=> Fix: `no-this-before-super` with the code path analysis

conf/environments.js, docs/user-guide/migrating-to-2.0.0.md, package.json, tests/lib/config/config-file.js, tests/lib/config/config-ops.js, tests/lib/eslint.js
This upgrades to `globals@8.14.0`, which has separate `es5` and `es6` environments. Only ES5 global variables are considered builtin now, and ES6 global variables are supplied as part of the `es6` environment.
=> Breaking: Remove ES6 global variables from builtins (fixes #4085)

tests/lib/options.js
Refs #4507.
This won't fix the issue, but it does add a few unit tests for known working cases. I hope that any fix we or optionator will do to fix the issue will be accompanied by appropriate unit test cases similar to these ones. Kind of unfortunate that nobody caught the lack of unit tests when we made the type change, but oh well.
=> Fix: Adding options unit tests for --ignore-pattern (refs #4507)

docs/user-guide/configuring.md, docs/user-guide/migrating-to-2.0.0.md, lib/config.js, lib/config/config-file.js, lib/file-finder.js, tests/lib/config.js, tests/lib/file-finder.js
* Added `package.json` as a lowest priority configuration file
* Changed signature of `FileFinder` constructor to only take one parameter (either a string or an array of strings)
* Modified the logic for `FileFinder`. Before it would retrieve directory listing for every configuration file type, which can add up quickly for deeply nested directory without configuration files. Performance improvement is negligible on a small project, but can be noticeable on large projects with a lot of subfolders.
* Modified documentation and added a step into migration guide.
=> Breaking: Treat package.json like the rest of configs (fixes #4451)

package.json
NSP has reported a security vulnerability with old versions of uglify-js, one of which is used by handlebars < 4.0.5.
https://nodesecurity.io/advisories/48
This update changes eslint's minimum handlebars version up from 4.0.0 to 4.0.5.
=> Upgrade: Handlebars to >= 4.0.5 for security reasons (fixes #4642)

docs/user-guide/command-line-interface.md, lib/options.js, package.json, tests/lib/options.js
Updates optionator from 0.6.0 to 0.7.1
Multiple ignore patterns must be specified by using the flag multiple
times, not by using a comma (since the pattern could include a comma)
=> Fix: Use oneValuePerFlag for --ignore-pattern option (fixes #4507)

lib/rules/max-len.js, tests/lib/rules/max-len.js
max-len incorrectly assumed that all tab characters would be the same width as the tab stops (`tabWidth`).
The new `computeLineLength()` determines the width of each tab to be the number of spaces to the next tab stop.
`computeLineLength()` can handle `tabWidth === 0` but it doesn't check that `tabWidth` is a positive integer. I wasn't sure if you wanted this validated, and if invalid input should throw or be silently rounded and made positive.
=> Fix: max-len rule overestimates the width of some tabs (fixes #4661)

docs/rules/no-invalid-this.md, lib/ast-utils.js, tests/lib/rules/no-eval.js, tests/lib/rules/no-invalid-this.js
Fixes #4669
I fixed `astUtils.isDefaultThisBinding`.
`no-eval` also is using this, so I added a test to `no-eval` as well.
=> Fix: `no-invalid-this` allows this in static method

conf/eslint.json, docs/rules/README.md, docs/rules/no-confusing-arrow.md, lib/rules/no-confusing-arrow.js, tests/lib/rules/no-confusing-arrow.js
This PR implements `no-confusing-arrow`. This rule implements the part of `no-arrow-condition` that isn't currently covered by `no-constant-condition`.
I'll submit another PR deprecating `no-arrow-condition` which will then close #4417.
=> New: Add no-confusing-arrow rule (ref #4417)

lib/config/config-ops.js, tests/lib/config/config-ops.js
Fixes #4682
```js
var result = ConfigOps.merge({}, src);
```
Even if `result` is modified, `src` should keep the original value.
`npm run perf` was around the same result between before and after.
=> Fix: ensure `ConfigOps.merge` do a deep copy

conf/replacements.json, docs/rules/README.md, docs/rules/no-arrow-condition.md, docs/user-guide/migrating-to-2.0.0.md
This PR deprecates the `no-arrow-condition` rule in favor of `no-confusing-arrow` (#4687) and [`no-constant-condition`](http://eslint.org/docs/rules/no-constant-condition.html).
=> Breaking: deprecate `no-arrow-condition` rule (fixes #4417)

docs/rules/max-len.md, lib/rules/max-len.js, tests/lib/rules/max-len.js
This allows for separate line length restrictions for source and comments.
For example, allowing source lines to be up to 100 characters wide, while restricting comments to 80 for readability.
=> Add a commentLength option to the max-len rule

docs/rules/max-len.md
* Add missed quotes(`"`) in json code examples at  `max-len.md`.
=> Docs: fix small typos in code examples

bin/eslint.js
I didn't remove any of the logging, I just changed `debug` command to not include `code-path` logs. This way, people can still get path analysis logs by running `DEBUG=eslint:*`
=> Fix: Remove path analysis from debug log (fixes #4631)

package.json
This fixes the installation errors noted in #4760. The errors were being thrown by `chokidar@0.8.1`, which is a dependency of an older version of `beefy`. Updated `beefy` to `^2.0.0` and installed without errors. Also tested that `npm run profile` still runs correctly (and in fact is no longer throws a 404 for the favicon!).
=> Upgrade: beefy to ^2.0.0, fixes installation errors (fixes #4760)

docs/user-guide/configuring.md
Make it really easy to figure out that you can't specify file extensions in the config files. For the slow such as myself.
https://github.com/eslint/eslint/issues/4701
=> Docs: Add section on file extensions to user-guide/configuring

docs/developer-guide/working-with-rules.md, docs/rules/no-else-return.md, docs/rules/no-negated-in-lhs.md, docs/rules/space-in-parens.md
the reason of the change in docs/rules/no-else-return.md: 
both rule/index.md (no-else-return - disallow else after a return in an if)  and  this whole file describe  'return before else' not 'return in esle'
=> Docs: fix typos, suggests

docs/rules/space-before-blocks.md, lib/rules/space-before-blocks.js, tests/lib/rules/space-before-blocks.js
Labeled breaking, since the new option is required by the schema.
=> Update: configuration for classes in space-before-blocks (fixes #4089)

docs/developer-guide/working-with-rules.md
I'd seen this mentioned in code review recently, so I decided to track down one possible cause.
This doesn't add it to JS files on the assumption that we'll do it like we've done previously and add the header as we go, but I can add it to them too if we want.
=> Docs: Add license header to Working with Rules guide

lib/config/config-validator.js, tests/lib/config/config-validator.js
Previously, an empty schema `[]` would allow any number and type of options after the severity. It will now warn if options are passed to rules that don't accept options.
=> Fix: Empty schemas forbid any options (fixes #4789)

docs/rules/README.md
The short description contradicted the readme of the no-console rule, which mentions that the rule should not be used in the node environment. It seems the browser environment was meant here instead.
=> Documentation fix

docs/rules/no-magic-numbers.md, lib/rules/no-magic-numbers.js, tests/lib/rules/no-magic-numbers.js
Adds a new config options ```ignoreArrayIndexes``` for the ```no-magic-numbers``` rule. (#4370)
No breaking changes.
Further improvements and code clean-up discussions via #4616.
=> New: 'ignoreArrayIndexes' option for 'no-magic-numbers' (fixes #4370)

docs/user-guide/command-line-interface.md, lib/options.js, package.json, tests/lib/options.js
Updated Optionator to version 0.8.0
Changed the type of the --max-warnings flag from 'Number' to 'Int'
An error will now be displayed if a non-integer value is supplied
=> Fix: Change max-warnings type to Int (fixes #4660)

docs/rules/no-bitwise.md, lib/rules/no-bitwise.js, tests/lib/rules/no-bitwise.js
Mostly useful for allowing the NOT operator for code like ~[1, 2, 3].indexOf(1), which is something where using bitwise operators makes sense. I know there are no docs attached, but mainly was wondering if these kinds of features get accepted.
Usage would be along the line of `no-bitwise: [2, { allow: [ '~' ] }]`
edit: clean new PR from #4738
edit: related to #4742
=> Update: optionally allow bitwise operators (fixes #4742)

docs/user-guide/migrating-to-2.0.0.md
Updates the migration guide for the no-arrow-condition which references itself instead of the no-constant-condition as a way of gaining the same functionality
=> Docs: fix migration guide for no-arrow-condition rule

package.json
Fixes npm install warning for deprecated version of lodash
=> Updating optionator dep to 0.8.1 (fixes #4851)

docs/rules/operator-linebreak.md, lib/rules/operator-linebreak.js, tests/lib/rules/operator-linebreak.js
To support "ignore" in overrides for specific operator/s.
=> Update: Add "ignore" override for operator-linebreak (fixes #4294)

conf/eslint.json, conf/replacements.json, docs/rules/README.md, docs/rules/keyword-spacing.md, docs/rules/space-after-keywords.md, docs/rules/space-before-keywords.md, docs/rules/space-return-throw-case.md, docs/user-guide/migrating-to-2.0.0.md, lib/rules/keyword-spacing.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/keyword-spacing.js
refs #1338, fixes #3869, fixes #3878, fixes #4006, fixes #4585.
This PR creates a new rule `keyword-spacing`, merged from `space-after-keywords`, `space-before-keywords`, and `space-return-throw-case`.
And `space-after-keywords`, `space-before-keywords`, and `space-return-throw-case` rules get deprecated.
=> Breaking: merges keyword spacing rules

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
This makes it so the code below passes the `valid-jsdoc` rule:
```js
/* eslint valid-jsdoc: 2 */
/**
* Creates a new thing.
* @interface
*/
function Thing() {}
```
Fixes #4860.
=> Fix: do not require a @return tag for @interface (fixes #4860)

bin/eslint.js
Tested manually and seems to be working.
=> Fix: Set proper exit code for Node > 0.10 (fixes #4691)

docs/rules/valid-jsdoc.md
This is an attempt to simplify the docs for `requireReturn`.
=> Docs: clarify `requireReturn` option for valid-jsdoc rule (fixes #4859)

package.json, tests/lib/rules/valid-jsdoc.js
This adds support for type expressions (only member expressions) with `@this`.  For example:
```js
/**
* @this {some.name}
*/
// expects to be called with some.name as this
}
```
Previously, only "name paths" were supported.  The type expression support comes with `doctrine@1.1.0`.  Here is the complete list of changes that comes with this upgrade: https://github.com/eslint/doctrine/compare/v0.7.1...v1.1.0
=> Add support for type expressions with @this

docs/rules/quote-props.md
Is this correct?
It previously suggested that it does the opposite, i.e. that when it's `true` you can leave keywords unquoted.
=> Modify "unnecessary" flag docs in quote-props

lib/formatters/stylish.js
There is a long-standing solarized bug [1] where gray text is invisible
on the dark theme.
Since solarized is a popular theme, follow Chalk's advice [2] and use 'dim' rather than 'gray'.
Works well for me on Solarized Light, Solarized Dark and the default Ubuntu theme but am unable to try it on iTerm.
[1] https://github.com/altercation/solarized/issues/220
[2] https://github.com/chalk/chalk/issues/40
=> Fix: gray text was invisible on Solarized Dark theme (fixes #4886)

packages/eslint-config-eslint/README.md
Hello
This markdown uses a missing footnote `npm-url` and the badge is rendered in a broken way in github UI. This change fixes it.
Thanks,
=> Docs: Fix missing footnote

package.json, packages/eslint-config-eslint/default.yml, packages/eslint-config-eslint/package.json
Fixes #4909.
And pins `js-yaml` as the same version as eslint.
=> Fix: remove duplicate of eslint-config-eslint

docs/rules/space-before-blocks.md, lib/rules/space-before-blocks.js, tests/lib/rules/space-before-blocks.js
Fixes #1338.
No longer `space-before-blocks` rule catches spacing preceded by a keyword in order to avoid to conflict with `keyword-spacing` rule.
I moved some tests to valid from invalid.
=> Breaking: `space-before-blocks` ignores after keywords

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
=> Fix: no-extra-parens ExpressionStatement restricted prods (fixes #4902)

conf/eslint.json, docs/rules/README.md, docs/rules/sort-imports.md, lib/rules/sort-imports.js, tests/lib/rules/sort-imports.js
New 'sort-imports' rule that checks the sorting for 
- member syntax group
- member name
- multiple member names within one import declaration.
To be consistent with the `sort-vars` rule, the rule
- uses the same sorting (default JavaScript string compare).
- supports `ignoreCase` config option. 
No auto fix implemented. We can discuss this, I think it is a little bit tricky with this grouping stuff.
This is my first rule implementation, so please review the code carefully, I am happy for every review comment.
=> New: 'sort-imports' rule (refs #3143)

lib/util/source-code.js, tests/lib/rules/valid-jsdoc.js
Without this change, a function expression as an object property could be assigned the wrong comment block.
```
/**
* This documents the assignment to `foo`, not the function expression for `bam`.
*/
var foo = new Bar({
bam: function() {
return 'baz';
}
});
```
Fixes #4900.
=> Correct JSDoc for function expression on object property

docs/rules/valid-jsdoc.md, lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
@nzakas @ilyavolodin This is what I am thinking when it comes to this enhancement.
CC: @janmarek 
Please share your views on the approach and the option setup.
=> Update: Add `preferType` option to `valid-jsdoc` rule (fixes #3056)

docs/developer-guide/working-with-rules.md, lib/eslint.js, lib/rule-context.js, tests/lib/eslint.js, tests/lib/rule-context.js
Wanted to get something in code to discuss around #3670.
One notable diversion from discussion: used `parserName` on `RuleContext` directly vs. mutating the exported `parser` object to add `parser.name`.
I believe this satisfies my use case. Wanted to get it in the queue for 2.0.
Tasks:
=> New: provide parsing faculties via RuleContext (fixes #3670)

lib/testers/rule-tester.js
This is how it looks now:
```
$ mocha tests/lib/rules/no-console.js
no-console
valid
√ Console.info(foo) (39ms)
invalid
√ console.log(foo)
√ console.error(foo)
√ console.info(foo)
4 passing (56ms)
```
=> Update: Add describe around rule tester blocks (fixes #4907)

docs/rules/README.md, docs/rules/jsx-quotes.md, lib/rules/jsx-quotes.js, tests/lib/rules/jsx-quotes.js
This is another take to #4377 after #4374 was left undone.
As discussed [here](https://github.com/eslint/eslint/pull/4374#discussion_r49568098) It looks like this rule can only fail in a simple case, that is: external quotes are wrong, and no literal quotes appear inside:
"..." → prefer-single → fail
'...' → prefer-double → fail
I couldn't find any counterexample to this, given the JSX grammar.
If any literal quote appears inside, it will make the rule pass even if the external quotes are not the preferred ones.
The proposed fix for a failing rule is then:
- `str.replace(/"/g, "'")` (for prefer-single)
- `str.replace(/'/g, "\"")` (for prefer-double)
Escaped quotes (e.g. `"&quot;"` and `'&#39;'`) don't add anything to this, since they are left as they are, and the JSX compiler will escape …
=> Make jsx-quotes fixable

docs/rules/no-unexpected-multiline.md, lib/rules/no-unexpected-multiline.js, tests/lib/rules/no-unexpected-multiline.js
Checks and reports function expression being treated as tagged template accidently.
=> Update: Report unexpected tagged template (fixes #4210)

lib/rules/global-require.js, tests/lib/rules/global-require.js
More or less copied the approach of `no-alert`. I'm wondering if `isShadowed()` could join ast-utils (or some other utility file), but that's for another day.
=> Fix: global-require no longer warns if require is shadowed (fixes #4812)

docs/user-guide/migrating-to-2.0.0.md, lib/rules/no-eval.js, lib/rules/no-invalid-this.js, lib/rules/no-redeclare.js, lib/rules/no-use-before-define.js, tests/lib/rules/no-eval.js
- Update rules:
- no-eval (and add a 'module' test similar to the 'strict mode' test)
- no-invalid-this
- no-redeclare
- no-use-before-define
- Update 'migrating-to-2.0.0.md'
NB: The 'strict' rule was updated in #4948.
=> Update: Rules should get `sourceType` from Program node (fixes #4960)

lib/rules/no-dupe-class-members.js, tests/lib/rules/no-dupe-class-members.js
Fixes #4981
method names can be IdentifierName, StringLiteral, and NumericLiteral: http://tc39.github.io/ecma262/#prod-LiteralPropertyName
In estree, StringLiteral and NumericLiteral are expressed by Literal node.
=> Fix: `no-dupe-class-members` false positive (fixes #4981)

lib/util/source-code.js, tests/lib/rules/valid-jsdoc.js, tests/lib/util/source-code.js
Without this change, comment blocks for function expressions in call expressions are not validated.
Fixes #4964.
=> Use comment block for function expression in a call expression

lib/util/source-code.js
fixes #4989
It's hard to create tests for this, but we can confirm this on coverage.
Before: https://coveralls.io/builds/4758352/source?filename=lib%2Futil%2Fsource-code.js#L270
After: https://coveralls.io/builds/4760985/source?filename=lib%2Futil%2Fsource-code.js#L272
=> Fix: `getNodeByRangeIndex` performance issue (fixes #4989)

docs/developer-guide/nodejs-api.md, docs/developer-guide/working-with-rules.md, docs/user-guide/migrating-to-2.0.0.md, lib/eslint.js, lib/util/source-code-fixer.js, lib/util/source-code.js, tests/fixtures/utf8-bom.js, tests/lib/rules/no-irregular-whitespace.js, tests/lib/util/source-code-fixer.js, tests/lib/util/source-code.js
Fixes #4878.
- `eslint.verify()` API came to strip BOM before parsing.
- `hasBOM` property was added into `SourceCode` object.
- `SourceCodeFixer.applyFixes()` came to insert BOM to the head of output if `sourceCode.hasBOM` is `true`.
> This diff becomes more readable if you add `?w=1`.
=> Fix: Supports Unicode BOM (fixes #4878)

lib/formatters/tap.js, tests/lib/formatters/tap.js
The current implementation display only one message.
=> Fix: multiple message in TAP formatter (fixes #4975)

docs/rules/no-unused-vars.md
Small fix: exported comment has no effect when `ecmaFeatures.globalReturn` is `true` (see [here](https://github.com/eslint/eslint/blob/v1.10.3/lib/eslint.js#L953) in the code).
=> Docs: Fix description of exported comment

docs/rules/README.md, docs/rules/strict.md, lib/rules/strict.js, tests/lib/rules/strict.js
- **strict.js**: `sourceType: "module"` now overrides the rule option 'never'. (All other rule options were already overridden.) This changes the problem message from "Strict mode is not permitted" to "'use strict' is unnecessary inside of modules".
- **tests/strict.js**: Add a test for `sourceType: "module"` with the rule option 'never'. (There already were tests for `sourceType: "module"` with the 'global' and 'function' options.)
- **rules/README.md** and **strict.md**:
- Clarify that the 'strict' rule concerns strict-mode directives, not strict mode itself.
- Mention that ECMAScript modules are always in strict mode.
- Document that `sourceType: "module"` overrides the rule options.
- Consistent use of *strict-mode directive* instead of the previous mix of names:
- Use Strict …
=> Update: Module overrides all 'strict' rule options (fixes #4936)

docs/rules/valid-jsdoc.md, lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
This just adds one additional check to see if a JSDoc comment is for a class constructor to avoid showing an error if the constructor lacks the `@return` tag.
=> Update: valid-jsdoc to not require `@return` in constructors (fixes #4976)

docs/rules/strict.md
Fix an incorrect link in **strict.md** (and improve the link by adding the relevant fragment).
=> Docs: Fix link in strict.md (fixes #5026)

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Fixes #5024
If the singular `WriteReference` of a variable is being in a condition of a loop, this rule came to skip the variable.
=> Fix: `prefer-const` false positive in a loop condition (fixes #5024)

docs/rules/spaced-comment.md, lib/rules/spaced-comment.js, tests/lib/rules/spaced-comment.js
Fixes #4969 
Fixes #5030
This pull request adds autofix to spaced-comment rule that respects all current options and fixes the error messages to account for `markers`. Fixing both issues separately could unnecessarily complicate the code, hence, I bundled them together.
=> Update:  add autofix support for spaced-comment (fixes #4969, fixes #5030)

docs/rules/no-bitwise.md, lib/rules/no-bitwise.js, tests/lib/rules/no-bitwise.js
Fixes #4873
Adds an option `int32Hint` to `no-bitwise` rule that allows using bitwise OR for type casting/hinting with `0`.
=> Update: add int32Hint option to `no-bitwise` rule (fixes #4873)

docs/rules/no-extra-boolean-cast.md, lib/rules/no-extra-boolean-cast.js, tests/lib/rules/no-extra-boolean-cast.js
Fixes #3650, warning for code such as
```javascript
if (Boolean(foo)) {
// ...
}
```
=> Update: Check for extra Boolean calls in no-extra-boolean-cast (fixes #3650)

docs/rules/no-multiple-empty-lines.md, lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
Update no-multiple-empty-lines rule to also warn about blank lines at the beginning of a file. (For issue #5045)
=> Update: Remove blank lines at beginning of files (fixes #5045)

docs/rules/no-restricted-imports.md, docs/rules/no-restricted-modules.md
Replace joyent github org with nodejs in some links in docs.
=> Docs: Replace joyent org with nodejs

docs/rules/consistent-this.md, lib/rules/consistent-this.js, tests/lib/rules/consistent-this.js
Added option to the rule `consistent-this` for adding extra allowed aliases for certain cases where it is acceptable to have more than 1 single name for assignments of `this`.
https://github.com/eslint/eslint/issues/4492
https://github.com/eslint/eslint/issues/5039
=> Update: Add extra aliases to consistent-this rule (fixes #4492 #5039)

docs/user-guide/configuring.md
The entire line can be safely removed because the effects on exit code are already discussed at the top of the section.
=> Docs: Remove reference to rules enabled by default (fixes #5100)

docs/rules/valid-jsdoc.md
Fix jsdoc param names to match function param names in `docs/rules/valid-jsdoc.md`
=> Docs: Fix jsdoc param names to match function param names

docs/rules/no-invalid-regexp.md
Since it seems that it's no longer possible to configure individual ES6 features, the example config from the rule docs has been replaced with the link to the config page that explains how to set the ecmaVersion setting.
=> Docs: Replace ecmaFeatures setting with link to config page

conf/eslint.json, docs/rules/README.md, docs/rules/no-empty-label.md, docs/rules/no-label-var.md, docs/rules/no-labels.md, docs/rules/no-unused-labels.md, lib/rules/no-unused-labels.js, tests/lib/rules/no-unused-labels.js
Fixes #5052.
Refs #5042.
This rule may be good one for `"eslint:recommended"` instead of `no-empty-label`.
=> New: `no-unused-labels` rule (fixes #5052)

docs/rules/no-loop-func.md, lib/rules/no-loop-func.js, tests/lib/rules/no-loop-func.js
Fixes #5044.
This PR adds a check of references which refer to upper variables from functions in a loop. The `no-loop-func` rule comes to warn the function only if there are unsafe reference. The unsafe reference is a reference that the referred variable can be modified after the function.
=> Fix: reduced `no-loop-func` false positive (fixes #5044)

conf/eslint.json, docs/rules/README.md, docs/rules/no-self-assign.md, lib/rules/no-self-assign.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/no-self-assign.js
fixes #4729.
I add this rule into `eslint-config-eslint/default.yml` to eat own dog food.
This also may be good one for `eslint:recommended`. If accepted, I can include this in #5103.
=> New: `no-self-assign` rule (fixes #4729)

lib/rules/sort-imports.js, tests/lib/rules/sort-imports.js
fixes #5130.
Just I added null checks since the `getFirstLocalMemberName` function can return `null`.
=> Fix: `sort-imports` crash (fixes #5130)

lib/ignored-paths.js, tests/lib/ignored-paths.js
This was a bit messy - the tests that tested for looking up to parent directories weren't really testing anything, so when I made the change, they still passed. I fixed them so they actually tested something. :)
=> Fix: find ignore file only in cwd (fixes #5087)

lib/testers/rule-tester.js, tests/lib/testers/rule-tester.js
Just a simple grammar fix in rule-tester messages: "Should have 1 errors but had 0" -> "Should have 1 error but had 0"
=> Fix: Handle singular case in rule-tester error message

docs/rules/strict.md, docs/user-guide/configuring.md, lib/eslint.js, lib/rules/strict.js, package.json, tests/lib/eslint.js, tests/lib/rules/no-eval.js, tests/lib/rules/no-invalid-this.js, tests/lib/rules/no-lone-blocks.js, tests/lib/rules/strict.js
- **configuring.md** Add the new parser option `ecmaFeatures.impliedStrict`.
- **lib/eslint.js** Pass `ecmaFeatures.impliedStrict` to Escope. (No change was required to pass it to the parser.)
- **tests/lib/eslint.js** Test that a parsing error is thrown when parsing sloppy code in implied strict mode. 
- **strict.md** Mention that implied strict mode overrides the 'strict' rule options.
- **lib/rules/strict.js**
- Implied strict mode overrides the 'strict' rule options (but is itself overridden if `sourceType` is 'module').
- New message for each strict-mode directive in implied strict mode:
*'use strict' is unnecessary when implied strict mode is enabled.*
- **tests/lib/rules/*.js**
- **strict** Test that implied strict mode overrides the 'strict' rule options (but is itself overridden …
=> Update: 'implied strict mode' ecmaFeature (fixes #4832)

docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, lib/formatters/table.js, package.json, tests/lib/formatters/table.js
New formatter uses "table" package to format ESlint output in a ANSI/ASCII table.
=> New: Added "table" formatter (fixes #4037)

docs/rules/block-spacing.md, docs/rules/complexity.md, docs/rules/constructor-super.md, docs/rules/handle-callback-err.md, docs/rules/no-class-assign.md, docs/rules/no-const-assign.md, docs/rules/no-dupe-class-members.md, docs/rules/no-extra-bind.md, docs/rules/no-implicit-coercion.md, docs/rules/no-implicit-globals.md, docs/rules/no-lone-blocks.md, docs/rules/no-new-symbol.md, docs/rules/no-proto.md, docs/rules/no-reserved-keys.md, docs/rules/no-restricted-imports.md, docs/rules/no-this-before-super.md, docs/rules/no-unused-vars.md, docs/rules/no-useless-call.md, docs/rules/no-warning-comments.md, docs/rules/prefer-arrow-callback.md, docs/rules/prefer-const.md, docs/rules/prefer-reflect.md, docs/rules/prefer-rest-params.md, docs/rules/prefer-spread.md, docs/rules/prefer-template.md, docs/rules/require-jsdoc.md, docs/rules/require-yield.md, docs/rules/sort-imports.md, docs/rules/sort-vars.md, docs/rules/use-isnan.md
Baby step to avoid merge conflicts at an especially busy time.
Affects only 7 anchors (see below).
- Replaced “Rule details” (4 occurrences) with “Rule Details” (215 occurrences)
- no-extra-bind.md
- no-lone-blocks.md
- require-jsdoc.md
- require-yield.md
- Replace “When Not to Use It” (19 occurrences) with “When Not To Use It” (110 occurrences)
- block-spacing.md
- complexity.md
- constructor-super.md
- no-class-assign.md
- no-const-assign.md
- no-dupe-class-members.md
- no-implicit-coercion.md
- no-implicit-globals.md
- no-new-symbol.md
- no-reserved-keys.md
- no-restricted-imports.md
- no-this-before-super.md
- no-unused-vars.md
- no-useless-call.md
- prefer-arrow-callback.md
- prefer-const.md
- prefer-reflect.md
- prefer-spread.md
- prefer-template.md
- Replace “When not to use it” (1 …
=> Docs: Correct obvious inconsistencies in rules h2 elements

lib/rules/padded-blocks.js, tests/lib/rules/padded-blocks.js
This allows comments that occur on the same line as the opening or closing brace.
By refactoring the `getCommentsInNode` method as part of this change, I was able to throw in a slight (~6%) performance bump. Before:
```
Single File:
CPU Speed is 2200 with multiplier 13000000
Performance Run #1:  4078.844035ms
Performance Run #2:  4145.123632ms
Performance Run #3:  4228.349988ms
Performance Run #4:  4022.783567ms
Performance Run #5:  4196.384683ms
Performance budget ok:  4145.123632ms (limit: 5909.090909090909ms)
Multi Files (450 files):
CPU Speed is 2200 with multiplier 39000000
Performance Run #1:  10260.395154ms
Performance Run #2:  10054.932538ms
Performance Run #3:  9980.401873ms
Performance Run #4:  10205.057365ms
Performance Run #5:  10123.912088ms
Performance budget ok: …
```
=> Fix: Allow same-line comments in padded-blocks (fixes #5055)

lib/ast-utils.js, lib/code-path-analysis/code-path-analyzer.js, lib/code-path-analysis/code-path-state.js, lib/rules/no-extra-label.js, tests/fixtures/code-path-analysis/block-and-break-1.js, tests/fixtures/code-path-analysis/block-and-break-2.js, tests/fixtures/code-path-analysis/block-and-break-3.js, tests/fixtures/code-path-analysis/block-and-break-4.js, tests/fixtures/code-path-analysis/while--break-nest-2.js, tests/lib/rules/no-unreachable.js
Fixes #5171
Code Path Analysis comes to handle labels with other than loops and switches correctly.
Before, it has been handling `break` statements on loop contexts and switch contexts. But now, it's handling `break` statements on the independent `break` contexts stack.
=> Fix: code path analysis and labels (fixes #5171)

docs/user-guide/command-line-interface.md, lib/cli.js, lib/options.js, tests/lib/cli.js, tests/lib/options.js
Hey!
As stated in the issue #5099, I did start to work on a version of the `--print-config` flag that would allow filtering the output (ie: `$ eslint --print-config env,rules some-file.js`) and everything worked well except that I couldn't figure out how to output the whole config when no value were passed to the flag. I've been playing around with different configurations for `optionator`, such as setting the type to `Boolean | [String]` but no luck so far.
In any case I've deleted the extra code for now as @nzakas requested for a dump of the whole config only.
PS: no idea on how to write more meaningful tests for that one!
=> New: Add a --print-config flag (fixes #5099)

docs/developer-guide/nodejs-api.md, lib/eslint.js
=> Docs: Clarify parameter documentation for `api.verify`

lib/rules/arrow-spacing.js
=> Docs: Correct `arrow-spacing` overview.

docs/rules/README.md
=> Docs: Remove periods in rules' README for consistency.

docs/rules/no-whitespace-before-property.md, lib/rules/no-whitespace-before-property.js, tests/lib/rules/no-whitespace-before-property.js
Rule ignores whitespace inside brackets and correctly reports property name
=> Fix: no-whitespace-before-property ignores whitespace inside brackets (fixes #5167)

docs/user-guide/configuring.md, lib/config/config-file.js, tests/lib/config/config-file.js
It turns out we weren't in too bad a situation. I believe this should solve most of the outstanding issues we have with parser and config locations.
@albertosantini can you try this branch and see if it works for the global install use case? (It's impossible to write a test for that.)
=> Fix: Config file relative paths (fixes #5164)

conf/eslint.json, docs/rules/README.md, docs/rules/no-empty-function.md, docs/rules/no-empty.md, lib/rules/no-empty-function.js, lib/rules/no-empty.js, tests/lib/rules/no-empty-function.js, tests/lib/rules/no-empty.js
Fixes #5161
And I removed `methods` option from `no-empty` rule. It's replaced with new `no-empty-function` rule.
I has not modified the migration guide 1 to 2 because the removed option had been added in 2.0.0 pre-release.
=> Breaking: new `no-empty-function` rule (fixes #5161)

CONTRIBUTING.md, README.md
Someone mentioned that we don't do a good job of pointing out contribution guidelines anywhere. So, this PR adds links in the README and in `CONTRIBUTING.MD`.
=> Docs: Add links for issue documentation

lib/rules/indent.js, tests/lib/rules/indent.js
Indent was behaving incorrectly when there's an array on a separate deep
inside a variable declaration with an expression node wrapping it as the
parent.
=> Fix: `indent` on variable declaration with separate array (fixes #5237)

docs/rules/README.md
In going through the list of rules, I found that they were mostly sorted alphabetically within each category, but there were a few rules that were out of place.  This PR corrects that.
There were a number of cases where one rule name is a prefix of another rule name (e.g., `semi` and `semi-spacing`).  In all but one of the cases, the shorter (prefix) name appeared after the longer name.  When sorting, the prefix would normally come first, so that is what I did here.  If you'd rather have the prefix names come after the longer versions, I can update this PR accordingly, and fix the remaining case that had the opposite order.
Note that the diff gets confused in a few places, but all I did was re-order rules; I made no wording changes to any of the rule descriptions.
=> Correct alphabetical ordering in rule list

docs/rules/jsx-quotes.md
Most other rule doc pages define the rule config above each example, so I did the same for the jsx-quotes doc page.
I don't know if it's going to be an issue, but the rule needs to be configred with "parserOptions.ecmaFeatures.jsx = true" for it to work. I think this can't be set on a file basis, so it can't be included in the examples. But maybe it should be mentioned in a paragraph before the examples?
=> Docs: Add rule config above each example in jsx-quotes

docs/rules/max-len.md
Removed the `commentLength` option from the min-len rule doc page as it's not being used in the rule code and also fails the schema validation if someone tries to use it.
=> Docs: Remove option that is not being used in max-len rule

docs/rules/require-jsdoc.md
`MethodDefinition` and `ClassDeclaration` options must be set to true for the examples to be correct in require-jsdoc rule doc page.
=> Docs: Fix rule config above examples for require-jsdoc

docs/rules/keyword-spacing.md
From https://gitter.im/eslint/eslint?at=56c06da7fa79226456fa478e
=> Docs: fix the default value of `keyword-spacing`'s overrides option.

lib/util/npm-util.js, tests/lib/util/npm-util.js
Refs because this fixes only one bug found. There's at least one more lingering.
Given a `package.json` missing `dependencies` or `devDependencies`:
```json
{
"name": "my-package",
"version": "1.2.3"
}
```
`npm-util`'s `check` method would read in the `package.json` file and attempt to call `Object.keys()` on `undefined`, which throws. This handles the case where either `dependencies` or `devDependencies` are not provided.
=> Fix: Popular style init handles missing package.json keys (refs #5243)

lib/rules/newline-after-var.js, tests/lib/rules/newline-after-var.js
fixes #5277 
It comes to check whether the next token of a variable declaration node is `}` or not.
It's meaning the end of a block.
=> Fix: `newline-after-var` crash on a switch statement (fixes #5277)

lib/eslint.js
Refs #5104 (specifically https://github.com/eslint/eslint/issues/5104#issuecomment-184236204)
=> Docs: Fix incorrect `api.verify` JSDoc for `config` param

lib/config/config-initializer.js, lib/util/npm-util.js, tests/lib/config/config-initializer.js
This also prevents needing to pass the `callback` to each function, instead letting it be handled within the `prompt` function.  Any error at any point in the processing should now be caught and displayed.
=> Fix: Consolidate try/catches to top levels (fixes #5243)

docs/rules/newline-per-chained-call.md, lib/rules/newline-per-chained-call.js, tests/lib/rules/newline-per-chained-call.js
=> Fix: Skip computed members in `newline-per-chained-call`

templates/pr-create.md.ejs, tests/templates/pr-create.md.ejs.js
This updates our pull request message to do some basic checks:
1. Commit message format (tag, issue reference, length)
1. CLA signature
1. Number of commits
If there are no problems, the comment is just "LGTM". :)
Right now, it can't check commit messages because the bot needs to do a separate request to get that information. I'll update the bot to do so once this is merged.
Also, I'll update the bot to run this on every pull request, not just on those without a CLA (as it is now).
=> Docs: Update PR creation bot message

lib/code-path-analysis/code-path-segment.js, lib/code-path-analysis/code-path-state.js, lib/code-path-analysis/code-path.js, lib/rules/constructor-super.js, lib/rules/no-this-before-super.js, tests/lib/code-path-analysis/code-path.js, tests/lib/rules/constructor-super.js, tests/lib/rules/no-this-before-super.js
fixes #5261.
Consideration of loops in those rules has been lacking.
I added a method which traverses every segment in a code path
(`codePath.traverseSegments(options, callback)`) into CodePath
prototype. Those rules come to handle loops by using this method.
Handling loops of a code path is complex :(
I'd like to investigate more simple way in future.
Note: Other rules which are using code path (`no-fallthrough`,
`no-unreachable`, and `consistent-return`) are not related to this bug.
These are checking whether some statements are reachable or not.
Reachability is calculated correctly.
=> Fix: `constructor-super` and `no-this-before-super` false (fixes #5261)

lib/rules/sort-imports.js, tests/lib/rules/sort-imports.js
fixes #5305.
When sorting members, this rule should ignore the default specifiers.
=> Fix: `sort-imports` warned between default and members (fixes #5305)

docs/rules/no-implicit-coercion.md
This replicates the work in #5322, but adheres to the guidelines for contributing.
=> Docs: Correct option name in `no-implicit-coercion` rule

docs/user-guide/configuring.md
Do we still want to recommend using it when it's deprecated now? (Or we can note that instead of removing it)
=> Docs: remove esprima-fb from suggested parsers

lib/rules/no-multi-spaces.js, tests/lib/rules/no-multi-spaces.js
I've added `\t` to the list of negated characters to the regular expression that determines whether the multiple spaces that are being detected should be reported or not.
Thus, in case smart tabs are being used like in the following case, the rule won't throw an error anymore.
```javascript
\t\t var one = 1,
\t\t\s\s two = 2;
```
The only shortcoming of this fix that I can see is when a tab is used within an expression, and directly after the tab, multiple spaces have been added. In that case, the rule won't be able to report an error. For instance:
```javascript
var a =\t\s\s1;
```
However, seeing as that using tabs inline is not a practice anyways, I don't think that's an issue. Do let me know if you think otherwise!
=> Fix: no-multi-spaces conflicts with smart tabs (fixes #2077)

Makefile.js, templates/pr-create.md.ejs, tests/templates/pr-create.md.ejs.js
Also makes sure the template test is run as part of `npm test`.
=> Build: Fix commit message validation (fixes #5340)

docs/rules/prefer-const.md, lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
As discussed in issue #5350; the prefer-const rule triggers if a let declaration is never reassigned. Update the error message, tests and documentation accordingly.
=> Update: prefer-const; change modified to reassigned (fixes #5350)

docs/rules/callback-return.md, docs/rules/func-style.md, docs/rules/no-ex-assign.md, docs/rules/no-extra-label.md, docs/rules/no-floating-decimal.md, docs/rules/no-invalid-regexp.md, docs/rules/no-invalid-this.md, docs/rules/no-label-var.md, docs/rules/no-mixed-requires.md, docs/rules/no-multiple-empty-lines.md, docs/rules/no-restricted-imports.md, docs/rules/no-throw-literal.md, docs/rules/no-undef.md, docs/rules/no-undefined.md, docs/rules/no-unneeded-ternary.md, docs/rules/space-unary-ops.md, docs/rules/spaced-comment.md, docs/rules/vars-on-top.md
Here is the current order (with frequency) of 8 headings at depth 2 in rules as a result of this pull request:
Rule Details 221
Options 91
Environments 2
Known Limitations 4
When Not To Use It 136
Compatibility 8
Further Reading 63
Related Rules 71
Recommend next step: Before we pick up the h3-grade sandpaper, let’s continue the discussion in https://github.com/eslint/eslint.github.io/issues/108 how to give the code examples some ❤️
Summary of 18 changed files:
* move Compatibility to follow When Not To Use It
- no-floating-decimal.md
* move When Not To Use It to precede Related Rules
- no-extra-label.md
- no-unneeded-terniary.md
* move Further Reading to precede Related Rules
- no-label-var.md
* replace Gotchas with Known Limitations
- callback-return.md
* change depth of Known …
=> Docs: Achieve consistent order of h2 in rule pages

docs/rules/valid-typeof.md
=> Docs: Add missing `symbol` type into valid list

bin/eslint.js, lib/config/plugins.js, messages/plugin-missing.txt, package.json
This is a super-simple attempt at what @btmills was suggesting. I'm trapping missing plugin errors and printing a nice message instead. Thoughts welcome.
=> Update: Better error message for plugins (refs #5221)

package.json, tests/lib/config/config-file.js
This also removes the dependency on multiple temp dir modules.
Fixes: #5338
=> Fix: Cleanup temp files from tests (fixes #5338)

lib/testers/rule-tester.js, tests/lib/testers/rule-tester.js
Fixes #5369: Improves the error message when forgetting the `errors` field in the invalid tests when using `rule-tester`.
I added the name of the tested rule in the error message because neither the stack trace nor the rule-tester 'error logger' specifies where the error occurred.
=> Update: Improve error message for rule-tester (fixes #5369)

lib/rules/constructor-super.js, tests/lib/rules/constructor-super.js, tests/lib/rules/no-this-before-super.js
Fixes #5394
When checking whether a call of `super()` exists in every previous code path, if there is a looped path, it went to wrong `false` value.
I made skipping looped previous paths.
=> Fix: `constructor-super` false positive after a loop (fixes #5394)

conf/eslint.json, docs/rules/README.md, docs/rules/no-restricted-globals.md, lib/rules/no-restricted-globals.js, tests/lib/rules/no-restricted-globals.js
Implementation of the new rule no-restricted-globals to disallow specific global variables usage. As explained in #3966, some globals defined by environments may be unwanted, so here is a rule to make sure they aren't used.
I have many usages in mind:
* prevent the usage of the deprecated `event` variable defined by the `"browser"` environment
* force the usage of a non native `Promise` implementation even if it is defined in the environment
* prevent the inadvertent usage of `fdescribe` or `fit` in a `"jasmine"` environment
The implementation is pretty straightforward. It is done in two steps: first, check variables defined outside of the current global scope (ex: made global via the eslint configuration), then check variables not defined at all.
=> New: no-restricted-globals rule implementation (fixes #3966)

.github/ISSUE_TEMPLATE.md
First pass at an issue template in a new .github/ directory (see https://github.com/blog/2111-issue-and-pull-request-templates). Also moved CONTRIBUTING.md to new directory.
I like the idea of keeping these GitHub specific files out of the root directory of the project and in their own directory, but let me know what you think.
=> Docs: Add Issue template (fixes #5313)

docs/rules/consistent-return.md, lib/ast-utils.js, lib/rules/consistent-return.js, tests/lib/rules/consistent-return.js
This PR makes the change requested in #5379 using the implementation outlined by @mysticatea in https://github.com/eslint/eslint/issues/5379#issuecomment-187997133 as I understood it.  If it missed the mark, please let me know and I'll update it.
It makes the exclusion of constructors unconditional, as it is for `no-invalid-this`.  If an option for conditional exclusion would be preferable, let me know what you'd prefer for name and behavior.
Note: This commit also exposes `isES5Constructor` from `ast-utils` so that it can be used by `consistent-return`.  If that is inappropriate or should be handled differently, let me know.
Thanks for considering,
Kevin
=> Update: Exclude ES5 constructors from consistent-return (fixes #5379)

tests/lib/rules/keyword-spacing.js
Fixes #5405.
espree v3.1.0 came to raise a syntax error correctly at `yield` keywords inside of arrow functions.
Then `keyword-spacing` rule never conflicts with `arrow-spacing`, so I just removed those tests.
=> Fix: remove tests which have invalid syntax (fixes #5405)

docs/rules/no-console.md
The docs for `no-console` appear to be missing the `allow` option, added in #5111.
I used similar wording to the `allow` option in the `no-bitwise` rule.
=> Docs: Missing allow option in  docs

tests/lib/config/config-initializer.js
To check this change, you can make the modification to `max-statements` as suggested by @btmills in https://github.com/eslint/eslint/issues/5381#issue-135846328, then run `npm test`.  You should see a multitude of errors, as well as the overall test status.
=> Fix: Prevent crash from swallowing console.log (fixes #5381)

docs/rules/no-irregular-whitespace.md, lib/rules/no-irregular-whitespace.js, tests/lib/rules/no-irregular-whitespace.js
The `no-irregular-whitespace` rule is unduly limiting "irregular"
whitespace to string literals alone (despite a comment at the top
of the file indicating otherwise).  This prevents non-English
speakers from commenting their code in their own language.  For
instance, French language mandates (half-width, but hey) unbreakable
whitespace before two-part punctuation marks (in effect: `;`, `:`,
`?` and `!`), and this rule prevents them from doing so.
This commit fixes that.  Technically, it required choosing a different
parsing path as the existing use cases: apparently the rule
infrastructure only triggers `'Program`' entities after any potential
top-of-file comment block (or perhaps Esprima does this), and because
of the way the `no-irregular-whitespace` rule is originally written,
getting …
=> Fix: Allow irregular whitespace in comments. Fixes #5368.

lib/cli-engine.js, tests/lib/cli-engine.js
Fallback to `process.cwd()` if `options.cwd` is unavailable, as is the case when `getFormatter` is called a static function.
=> Fix: `getFormatter` throws an error when called as static (fixes #5378)

docs/rules/no-unused-vars.md
=> Docs: Specify results of `no-unused-var` with different `args` options

docs/developer-guide/working-with-rules.md
Currently the "Rule Unit Tests" section of the "Working with Rules" document does not give any information on how to specify parser options. I've written a quick section using examples from `espree@3.x`-style configurations. Please let me know if I've goofed anywhere.
=> Docs: Add parserOptions to RuleTester section of working-with-rules

docs/developer-guide/working-with-rules.md
The section "The Context Object" in the "Working with Rules" document incorrectly lists `ecmaFeatures` as a key/value pair available on the context object. My understanding is that `parserOptions` is what is now exposed.
I have corrected the list entry and linked to the parse options section in the user guide "Configuration" document. Please let me know if I've goofed.
=> Docs: Replace ecmaFeatures with parserOptions in working-with-rules

package.json, tests/lib/rules/no-undef.js
fixes #5420.
I upgraded escope to 3.5.0 and added a test.
=> Fix: `no-undef` false positive at new.target (fixes #5420)

Makefile.js
~~This reverts commit b32ddad494c9d766aa71144dcccecd040246b040.~~ **edit**: Not anymore!
@BYK and @mysticatea can you explain the reasoning behind #5279 and #5280? We can't differentiate between a successful and unsuccessful performance test based on exit code alone - the exit code is 1 either way.
=> Build: Stop checking exit code in performance tests (fixes #5330)

docs/rules/comma-dangle.md, docs/rules/no-cond-assign.md, docs/rules/no-console.md, docs/rules/no-constant-condition.md, docs/rules/no-control-regex.md, docs/rules/no-dupe-args.md, docs/rules/no-dupe-keys.md, docs/rules/no-duplicate-case.md, docs/rules/no-empty-character-class.md, docs/rules/no-empty.md, docs/rules/no-ex-assign.md, docs/rules/no-extra-boolean-cast.md, docs/rules/no-extra-parens.md
First of two pull requests for rules under **Possible Errors**.
* comma-dangle: add **Options**; move default option first in list; replace status 1 with 2
* no-cond-assign: simplify paragraphs about options; **Related Rules** no-extra-parens
* no-constant-condition rewrite rule details
* no-dupe-args: rewrite rule details; add example of correct code
* no-duplicate-case: rewrite introduction and rule details; move intro example to incorrect code and make correct code parallel; *sorry this rule wins hash-of-changes prize for this batch*
* no-empty: rewrite sentence about comment; include both line and block comments in correct code
* no-extra-parens: replace h4 Fine-grained control with h3 conditionalAssign; **Related Rules** no-cond-assign
=> Docs: Distinguish examples in rules under Possible Errors part 1

docs/user-guide/migrating-to-2.0.0.md
The 2.0.0 migration guide does not list steps for migrating ecmaFeatures to parserOptions for RuleTester tests. I have added some quick steps; please let me know if I've goofed.
=> Docs: Add RuleTester parserOptions migration steps

docs/rules/no-extra-semi.md, docs/rules/no-func-assign.md, docs/rules/no-inner-declarations.md, docs/rules/no-invalid-regexp.md, docs/rules/no-irregular-whitespace.md, docs/rules/no-negated-in-lhs.md, docs/rules/no-obj-calls.md, docs/rules/no-regex-spaces.md, docs/rules/no-sparse-arrays.md, docs/rules/no-unexpected-multiline.md, docs/rules/no-unreachable.md, docs/rules/use-isnan.md, docs/rules/valid-jsdoc.md, docs/rules/valid-typeof.md
Second of two pull requests for rules under **Possible Errors**.
What do you think about the wording of these example sentences?
* valid-jsdoc: Examples of incorrect/correct code for a sample of `"preferType"` options
* no-func-assign: Examples of incorrect code for this rule, unlike the corresponding rule in JSHint
* no-unreachable: Examples of correct code for this rule, because of JavaScript function and variable hoisting:
* no-inner-declarations: split general correct code to be specific for functions and both
* no-unexpected-multiline: changed ordered to unordered list in Rule Details
* valid-jsdoc: when any of the following is true: changed ordered to unordered list in Rule Details;
added eslint comment in code examples for preferType
=> Docs: Distinguish examples in rules under Possible Errors part 2

Makefile.js, docs/rules/.gitattributes
Also removed `.gitattributes' file, since it was preventing me from running `gensite` and we are not linting examples anymore. @IanVS correct me if I'm wrong, but it's no longer needed, right?
=> Build: Add additional linebreak to docs (fixes #5464)

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
Pretty simple fix in the end, just needed to ensure the whole ObjectExpression was passed to the line count checker.
=> Fix: key-spacing checks ObjectExpression is multiline (fixes #5479)

docs/rules/README.md, docs/rules/linebreak-style.md
I believe autofixing was added (https://github.com/eslint/eslint/pull/3983) but never documented.
=> Docs: Document linebreak-style as fixable

docs/rules/accessor-pairs.md, docs/rules/array-callback-return.md, docs/rules/block-scoped-var.md, docs/rules/complexity.md, docs/rules/consistent-return.md, docs/rules/curly.md, docs/rules/default-case.md, docs/rules/dot-location.md, docs/rules/dot-notation.md, docs/rules/eqeqeq.md, docs/rules/guard-for-in.md, docs/rules/no-alert.md, docs/rules/no-caller.md, docs/rules/no-case-declarations.md, docs/rules/no-div-regex.md, docs/rules/no-else-return.md
1 of 4 pull requests for rules under **Best Practices** Have a good week end!
This gets us to 25% of the rules. We might finish in about 4 weeks and celebrate April Rules day.
What do you think about the wording of these example sentences?
* complexity: Examples of incorrect/correct code for a maximum of 2
* dot-notation: Examples of correct code for the sample `{ "allowPattern": "^[a-z]+(_[a-z]+)+$" }` option
* accessor-pairs: Options unordered list with default option first; delete json
* array-callback-return: add eslint comments to example code
* block-scoped-var: delete redundant code in introduction; rename functions to merge code fences in examples; add third function to correct code
* complexity: add Options heading
* curly: move …
=> Docs: Distinguish examples in rules under Best Practices part 1

lib/rules/no-unmodified-loop-condition.js, tests/lib/rules/no-unmodified-loop-condition.js
Fixes #5445.
Previously, this rule has been checking whether every BinaryExpression was modified or not. But this way has been reporting wrong warnings in chaining binary expression (e.g. `foo + bar < baz`).
Now, this rule came to check whether the chain of BinaryExpressions was modified or not.
=> Fix: `no-unmodified-loop-condition` false positive (fixes #5445)

docs/rules/README.md, docs/rules/callback-return.md, docs/rules/handle-callback-err.md, docs/rules/no-comma-dangle.md, docs/rules/no-mixed-requires.md, docs/rules/no-restricted-imports.md, docs/rules/no-restricted-modules.md
Adding items suggested per https://github.com/eslint/eslint/pull/5451#issuecomment-192680197 as well as well as one additional reference in `no-restricted-modules.md`.
=> Docs: Replace all node references to Node.js which is the official name

docs/rules/README.md
Fixable rules are mostly limited to whitespace fixes; indicate no-reserved-keys replacement as quote-props
=> Docs: Minor README clarifications

docs/rules/no-lone-blocks.md
Had been wondering whether labels would be problematic, so wanted to show they weren't (unless included themselves within a block).
=> Docs: no-lone-blocks - show non-problematic (and problematic) label

docs/rules/no-confusing-arrow.md, lib/ast-utils.js, lib/rules/no-confusing-arrow.js, lib/rules/no-extra-parens.js, tests/lib/ast-utils.js, tests/lib/rules/no-confusing-arrow.js
=> Update: add `allowParens` option to `no-confusing-arrow`

lib/rules/newline-before-return.js, tests/lib/rules/newline-before-return.js
I think problem occurs because sourceCode.getComments(node).leading miscalculates, this is a quick fix.
=> Fix: newline-before-return: bug with comment (fixes: 5480)

docs/user-guide/command-line-interface.md, lib/cli.js, lib/config.js, lib/options.js, tests/fixtures/passing-es7.js, tests/lib/cli.js
Per https://github.com/eslint/eslint/issues/5495#issuecomment-194060514
This PR adds `--parser-options` to the CLI - it should allow for setting any value that can be set in `.eslintrc`.
=> New: add `--parser-options` to CLI (fixes #5495)

docs/rules/no-unused-expressions.md
Avoid using string as example of unusable since it could be a directive depending on context
=> Docs: no-unused-expressions - add more edge unusable and usable examples

lib/config/config-validator.js, tests/lib/config/config-validator.js, tests/lib/eslint.js
This pull request lets ESLint throw an "invalid configuration" error when a user specifies a severity level with a non-number or non-string value. (fixes https://github.com/eslint/eslint/issues/5499)
**Current behavior:**
```sh
$ echo "" | eslint --rule "semi: [['error']]" --stdin
```
**After merging this PR:**
```sh
$ echo "" | eslint --rule "semi: [['error']]" --stdin
CLI:
Configuration for rule "semi" is invalid:
Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed `[ "error" ]`).
```
=> Fix: validate the type of severity level (fixes: #5499)

.github/ISSUE_TEMPLATE.md
Per discussion in chat, it seems like it might be worthwhile to separate the parser question from configuration. As it is, people will sometimes only include parser information.
I phrased the configuration line as a request rather than a question-- please let me know if I should change that.
=> Docs: Separate parser and config questions in issue template

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
Fixes #5537, fixes #5538.
`object-curly-spacing` was blindly checking the penultimate token for
`objectsInObjects` and `arraysInObjects` options and it was confusing
computed member expressions and function expressions with array and
object expressions respectively. This patch adds a type check for the
penultimate tokens owner node.
=> Fix: object-curly-spacing doesn't know types

docs/rules/prefer-template.md
=> Docs: Make `prefer-template` examples consistent.

lib/rules/no-useless-constructor.js, tests/lib/rules/no-useless-constructor.js
Fixes #5573 
I refactored this rule for readability.
The cause is that checking the type of `body[0].expression` and the length of `superArgs` were lacking.
=> Fix: `no-useless-constructor` clash (fixes #5573)

package.json, tests/lib/eslint.js
=> Fix: Ensure allowing `await` as a property name (fixes #5564)

lib/options.js
Actually I edited a JavaScript file but the change is just a typo fix of the CLI help message. I think the help message is a part of documentation so I tagged the commit as `Docs`.  But if it is wrong and I need to create a issue for this PR, I'll do it.
=> Docs: Fix typo in CLI help message

lib/cli-engine.js, lib/util/hash.js, package.json, tests/lib/cli-engine.js
Fixes #5522. Removes the dependency on the `crypto` module, which is not available when node is built with the `--without-ssl` flag.
=> Update: replace MD5 hashing of cache files with MurmurHash (fixes #5522)

docs/rules/no-restricted-globals.md, docs/rules/no-undef-init.md, docs/rules/no-undef.md, docs/rules/no-unused-vars.md
* no-restricted-globals: delete json which had syntax error highlight on the colon, maybe because not enclosed in braces; replace example sentences (rule was introduced in ESLint 2.3.0 after #5375 was merged)
* no-undef-init: added example sentence under When Not To Use It; added correct code for eslint-disable-line configuration comment
* no-undef: add details to example sentences and adjust grammar
* no-unused-vars: simplify details sentence; replace h3 Exported Variables with exported, which is the actual keyword; added h4 vars: local correct code
=> Docs: Distinguish examples in rules under Variables part 2

docs/rules/no-loop-func.md, docs/rules/no-magic-numbers.md, docs/rules/no-multi-spaces.md, docs/rules/no-multi-str.md, docs/rules/no-native-reassign.md, docs/rules/no-new-func.md, docs/rules/no-new-wrappers.md, docs/rules/no-new.md, docs/rules/no-octal-escape.md, docs/rules/no-octal.md, docs/rules/no-param-reassign.md, docs/rules/no-process-env.md, docs/rules/no-proto.md, docs/rules/no-redeclare.md, docs/rules/no-return-assign.md, docs/rules/no-script-url.md
3 of 4 pull requests for rules under **Best Practices**
This gets us to 40% of the rules.
* no-magic-numbers: replace out-of-bounds index [3] with last [2] and add examples for some options
* no-multi-spaces: simplify description of exceptions option; reorganize example code for option
* no-param-reassign *the cut-and-paste winner for this batch*: move first example code pair to Rule Details; move example code for default option first
* no-redeclare: delete json and move sentence; delete redundant incorrect code for browser environment
Add to missing examples:
* no-native-reassign: correct code for this rule; correct code for sample exceptions option
* no-script-url: correct code for this rule
=> Docs: Distinguish examples in rules under Best Practices part 3

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Refs #5284.
This PR makes `prefer-const` rule not changing variables' scope.
I will send another PR to add `prefer-smaller-scope` rule later (another day).
=> Fix: `prefer-const` got to not change scopes (refs #5284)

lib/rules/max-len.js, tests/lib/rules/max-len.js
Older pull request(#5585) failed to push changes to travis , so created this again . 
We are considering `ignoreComments` and `maxCommentLength`  alone to see if comments need to be considered. As these two are false , the comments is empty array and trailing comments are not stripped. 
Fix : Added this condition also along with other two. If any of the three are true, we are considering the comments in our calculation.
=> Fix: respect 'ignoreTrailingComments' in max-len rule (fixes #5563)

lib/rules/brace-style.js, tests/lib/rules/brace-style.js
Fixes #5197.
`brace-style` was ignoring almost all `allman` checks when
`allowSingleLine` option was set. It was also ignoring closing brace
errors when there was a body error with a single-line body.
=> Fix: `brace-style` erroneously ignoring certain errors

lib/ignored-paths.js, lib/util/glob-util.js, tests/fixtures/glob-util/node_modules/dependency.js, tests/fixtures/ignored-paths/.eslintignoreWithUnignoredDefaults, tests/lib/ignored-paths.js, tests/lib/util/glob-util.js
This PR changes the default ignores from:
```
/node_modules/
/bower_components/
```
to:
```
/node_modules/*
/bower_components/*
```
as suggested by @alberto in https://github.com/eslint/eslint/issues/5410#issuecomment-189542288.  
However, I'm keeping `this.ig.default` so that we can continue avoiding showing warning messages for files in those folders.
To allow custom-specified ignore patterns to override the defaults, the custom patterns will be added to the defaults as well.  A warning will only be shown if a file is ignored by custom ignore rules but not by default.
=> Fix: Allow default ignored files to be unignored (fixes #5410)

docs/rules/no-self-assign.md, docs/rules/no-self-compare.md, docs/rules/no-sequences.md, docs/rules/no-throw-literal.md, docs/rules/no-unmodified-loop-condition.md, docs/rules/no-unused-expressions.md, docs/rules/no-unused-labels.md, docs/rules/no-useless-call.md, docs/rules/no-useless-concat.md, docs/rules/no-void.md, docs/rules/no-warning-comments.md, docs/rules/no-with.md, docs/rules/radix.md, docs/rules/strict.md, docs/rules/vars-on-top.md, docs/rules/wrap-iife.md, docs/rules/yoda.md
4 of 4 pull requests for rules under **Best Practices** plus strict under **Strict Mode**
* no-unused-expressions has much cut-and-paste: for options all code paths must have side effects; move incorrect/correct code pairs together for options
* no-useless-call: Replace p with h2 Known Limitations; reverse order of its examples to incorrect/correct
* no-warning-comments has much cut-and-paste: simplify introduction and Rule Details; delete json, info about error level, and examples of config without code
* radix: delete redundant p and json after ul under Options
* vars-on-top: split incorrect code to make it parallel with correct code
* wrap-iife has much cut-and-paste: Swap introduction sentence and Rule Details paragraph; replace statement …
=> Docs: Distinguish examples in rules under Best Practices part 4

lib/rules/radix.js, tests/lib/rules/radix.js
Fixes #5639.
I made this rule relying on escope's variables to handle shadowings.
=> Fix: `radix` rule false positive at shadowed variables (fixes #5639)

conf/eslint.json, docs/rules/README.md, docs/rules/max-statements-per-line.md, lib/rules/max-statements-per-line.js, tests/lib/rules/max-statements-per-line.js
Added new rule (`max-statements-per-line`) to enforce a maximum number of statements per line.
=> New: max-statements-per-line (fixes #5424)

docs/rules/callback-return.md, docs/rules/global-require.md, docs/rules/handle-callback-err.md, docs/rules/no-mixed-requires.md, docs/rules/no-new-require.md, docs/rules/no-path-concat.md, docs/rules/no-process-exit.md, docs/rules/no-restricted-modules.md, docs/rules/no-sync.md
A pull request for rules under **Node.js and CommonJS**
This gets us to 50% of the rules. About 7 pull requests to go. Hang in there.
What do you think about the wording of these example sentences?
* Example of **correct** code for this rule, **but** it is probably a mistake:
* Example of **incorrect** code for this rule, **but** it is probably not a mistake:
* Examples of **correct** code for the default `"err"` parameter name:
* Examples of **correct** code for a sample `"error"` parameter name:
* Examples of **incorrect** code for a sample module:
* callback-return: move examples from Rule Details to Options; change capitalization in h3 from title case to sentence case
* global-require: delete period in main heading; delete json and You …
=> Docs: Distinguish examples in rules under Node.js and CommonJS

README.md
Also added a paragraph indicating criteria for when we will consider those features for ESLint rules (i.e., when it has been added to the ECMAScript standard).
I added the extra paragraph somewhat on a whim-- let me know if it should be struck.
=> Docs: Remove ES2016 from experimental section of README

docs/rules/no-empty-function.md, docs/rules/no-empty-pattern.md, docs/rules/no-eq-null.md, docs/rules/no-eval.md, docs/rules/no-extend-native.md, docs/rules/no-extra-bind.md, docs/rules/no-extra-label.md, docs/rules/no-fallthrough.md, docs/rules/no-floating-decimal.md, docs/rules/no-implicit-coercion.md, docs/rules/no-implicit-globals.md, docs/rules/no-implied-eval.md, docs/rules/no-invalid-this.md, docs/rules/no-iterator.md, docs/rules/no-labels.md, docs/rules/no-lone-blocks.md
2 of 4 pull requests for rules under **Best Practices**
What do you think about the wording of these example sentences?
* no-implicit-globals: Examples of correct code for this rule with `"parserOptions": { "sourceType": "module" }` in the ESLint configuration:
* no-invalid-this: Examples of incorrect code for this rule in strict mode:
* no-long-blocks: Examples of correct code for this rule with es6 environment and strict mode via `"parserOptions": { "sourceType": "module" }` in the ESLint configuration or `"use strict"` directive in the code:
The 2 items below which have **Reviewers** questions deserve a careful look please.
* no-empty-function: add eslint-env comments; delete json
* no-empty-pattern: add js to code fences in introduction
* …
=> Docs: Distinguish examples in rules under Best Practices part 2

lib/cli-engine.js
In the current versions of node path.* can be called on any arbitrary
value and will return an empty string on invalid input.
As of node v6 path will assert that values passed to it are strings,
and as such will throw on `undefined`
This commit moved the logic of using `path.extname` inside of the
processText  function in `lib/cli-engine.js`. so that it will not call
`path.extname` if a filename is not passed.
This change should not affect any other parts of the system, and the
test suite is 100% working on node v4, v5, and master.
fixes #5678
=> fix: don't use path.extname with undefined value

conf/cli-options.js, lib/cli-engine.js, tests/lib/cli-engine.js
=> Fix: make the default of `options.cwd` in runtime (fixes #5694)

docs/user-guide/configuring.md
We no longer use minimatch for ignore patterns, instead using `ignore`
to match `.gitignore` format exactly.
=> Docs: Remove mention of minimatch for .eslintignore

README.md
Reorder questions so that ES questions appear together, and the full question about support (`Does ESLint support JSX?`) appears before the others.
=> Docs: Reorder FAQ in README

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
This will cause validation errors if a parameter with a default values
does not have a JS Doc param field.
This is the absolute smallest change to make this work and could be extended much further. I intend to do that at a later point but wanted to get these changes in tiny bit by tiny bit.
=> Update: Basic valid-jsdoc default parameter support (fixes #5658)

lib/rules/valid-jsdoc.js
Latest PR merge had this issue in it. Fixing it now so that the build on master starts working.
=> Fix: Lint issue with `valid-jsdoc` rule (refs #5188)

docs/rules/no-multiple-empty-lines.md
When the severities were changed to strings in 09659d6f7e4e06bf602f0e5ea74bd378a048a21d, the information about the properties for the `no-multiple-empty-lines` was not updated.
=> Docs: Correct explanation about properties

package.json
Picks up where https://github.com/eslint/eslint/pull/5731 left off.
=> Fix: Old Chalk.JS deprecated method (fixes #5716)

package.json, tests/lib/rules/valid-jsdoc.js
~~The doctrine changes that fix this have been merged (https://github.com/eslint/doctrine/pull/158). Waiting on the next release so I can bump up the version here.~~ All set!
fixes #5612
=> Fix: Update doctrine to allow hyphens in JSDoc names (fixes #5612)

lib/rules/lines-around-comment.js, tests/lib/rules/lines-around-comment.js
When `allowBlockStart`/`allowBlockEnd` are true, comments at the start/end
of a switch case are treated the same as if they were in a block.
Example:
```
/* eslint lines-around-comment: ["error", {beforeLineComment: true, allowBlockStart:true}] */
switch ('foo') {
case 'foo':
// Previously failed because no preceding newline and not first line of block
break;
}
```
=> Fix: Treat SwitchCase like a block in lines-around-comment (fixes #5718)

docs/rules/sort-imports.md
=> Docs: Typo in `sort-imports`

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
Introduces deep and more robust `preferType` checks to `valid-jsdoc`.
Fixes #5745, fixes #5746.
=> Fix: valid-jsdoc crash w/ Field & Array Type

docs/rules/no-param-reassign.md, lib/rules/no-param-reassign.js, tests/lib/rules/no-param-reassign.js
- Change error message if rule triggers from prop side effect
vs from setting param directly.
This fixes #5705.
=> Improve no-param-reassign props: true msg

docs/rules/complexity.md, docs/rules/max-depth.md, docs/rules/max-nested-callbacks.md, docs/rules/max-params.md, docs/rules/max-statements.md, lib/rules/complexity.js, lib/rules/max-depth.js, lib/rules/max-nested-callbacks.js, lib/rules/max-params.js, lib/rules/max-statements.js, tests/lib/rules/complexity.js, tests/lib/rules/max-depth.js, tests/lib/rules/max-nested-callbacks.js, tests/lib/rules/max-params.js, tests/lib/rules/max-statements.js
Add the option name `max` to all rules that currently accept an option
name `maximum` and add deprecation notes to the docs of each of those
rules.
=> Update: Deprecate option `maximum` in favor of `max` (fixes #5685)

docs/rules/prefer-const.md, lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Fixes #5594.
I added `mixed` option, default is `true`.
```json
{
"prefer-const": ["error", {"mixed": true}]
}
```
If `{"mixed": false}` is specified, this rule groups variables by destructuring, then doesn't warn variables in destructuring if the variables are a mix of reassigned and never reassigned.
=> Update: `destructuring` option of `prefer-const` rule (fixes #5594)

lib/rules/vars-on-top.js, tests/lib/rules/vars-on-top.js
Fixes #5711 
The `vars-on-top` rule complained about `export`ed variables, even though they were at the top of a file.
=> Fix: vars-on-top conflicts with `export`

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
As per the discussion in #3065 (and my duplicate request in #5587), this introduces an option for `no-extra-parens` to allow for parens to be used in binary expressions.
```js
x = a || (b && c);
```
This was done by simply ignoring the BinaryExpression nodes when the option is set, which kinda seems too good to be true, however all the tests (of valid and invalid code) seem to pass, so ... :tada: yay? It's quite possible that I've missed a test case here.
There was also a typo in the docs for the `conditionalAssign` option, which described usage when set to `true`, but it should read `false`.
=> Update: adds nestedBinaryExpressions for no-extra-parens rule (fixes #3065)

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: indent rule uses wrong node for class indent level (fixes #5764)

docs/rules/space-before-function-paren.md, lib/rules/space-before-function-paren.js, tests/lib/rules/space-before-function-paren.js
This allows a configuration where you can enforce
space-before-function for named functions, say, while letting
anonymous functions use spaces or not, without error either way.
Without this change, enabling this rule for one or the other of
named/anonymous, but not both, was impossible.
Fixes #4127
=> Add an 'ignore' option to space-before-function-parens.

docs/rules/array-bracket-spacing.md, docs/rules/arrow-spacing.md, docs/rules/block-spacing.md, docs/rules/comma-spacing.md, docs/rules/computed-property-spacing.md, docs/rules/eol-last.md, docs/rules/generator-star-spacing.md, docs/rules/indent.md, docs/rules/jsx-quotes.md, docs/rules/keyword-spacing.md, docs/rules/linebreak-style.md, docs/rules/no-extra-semi.md, docs/rules/no-multi-spaces.md, docs/rules/no-spaced-func.md, docs/rules/no-trailing-spaces.md, docs/rules/object-curly-spacing.md, docs/rules/quotes.md, docs/rules/semi-spacing.md, docs/rules/semi.md, docs/rules/space-after-keywords.md, docs/rules/space-before-blocks.md, docs/rules/space-before-function-paren.md, docs/rules/space-before-keywords.md, docs/rules/space-in-parens.md, docs/rules/space-infix-ops.md, docs/rules/space-return-throw-case.md, docs/rules/space-unary-ops.md, docs/rules/spaced-comment.md, docs/rules/template-curly-spacing.md, docs/rules/yield-star-spacing.md
I added backticks so `--fix` has code style. Without them, double hyphen appeared as en dash 😢
=> Docs: Add code backticks to sentence in fixable rules

docs/user-guide/configuring.md
I personally was looking for info on disabling rules for an entire file (an edge case, I know, but a valid one, in my opinion) and thought we could make this clearer.
Also made whitespace padding in comments consistent throughout the file while I was at it.
=> Docs: Clarify disable inline comments

docs/rules/constructor-super.md, lib/code-path-analysis/code-path-segment.js, lib/rules/constructor-super.js, tests/fixtures/code-path-analysis/if-5.js, tests/lib/rules/constructor-super.js
Fixes #5449 .
This PR was squashed from 2 commits:
- d93552a86098bb4690d230142a87f8a4e98c14ac Fixes a bug of code path analysis. I found it while I wrote this change.
- 2497bf7f42a71c6570023ef05661827447af8ec5 Improves the behavior for classes which inherit from a non-constructor.
- The error message for classes which inherit from a non-constructor is improved.
- `"Unexpected 'super()' because 'super' is not a constructor."`
- The lacking `super()` cases for classes which inherit from a non-constructor are now invalid cases.
- Enhancements the check whether a class inherits from a constructor or not.
=> Fix: improve `constructor-super` errors for literals (fixes #5449)

docs/rules/space-before-function-paren.md
I was confused about whether es6-style functions were considered named
or anonymous.
I also fixed a typo that had gotten in there.
=> Docs: fix the examples for space-before-function-paren.

docs/rules/no-fallthrough.md, lib/rules/no-fallthrough.js, tests/lib/rules/no-fallthrough.js
So this PR adds the `commentPattern` option to `no-fallthrough` rule which may be a string or a regular expression string and which overrides the default `/falls?\s?through/i` RegEx for switch-case fallthrough comment. If no option is specified, the default pattern for fallthrough comment is used.
=> Update: `commentPattern` option for `no-fallthrough` rule (fixes #5757)

docs/rules/README.md
For each rule doc, I made the title consistent with the description in the README.md file. Since I also made some grammar changes for better consistency between rules, I want to make sure those changes are acceptable as well.
=> Docs: Make rule descriptions more consistent

docs/developer-guide/working-with-rules-new.md, lib/eslint.js, lib/rules/array-bracket-spacing.js
This adds a new page that explains new configuration for rules. This is a clone of working-with-rules with corrected information about rule layout.
=> Docs: Add a new page for working with rules (refs #5417)

docs/rules/array-bracket-spacing.md, docs/rules/block-spacing.md, docs/rules/brace-style.md, docs/rules/camelcase.md, docs/rules/comma-spacing.md, docs/rules/comma-style.md, docs/rules/computed-property-spacing.md, docs/rules/consistent-this.md, docs/rules/eol-last.md, docs/rules/func-names.md
The first 10 rules under **Stylistic Issues**
Something new in this smaller batch is first attempt at more consistency under **Options**. After some feedback, I will add to the guidelines.
@scriptdaemon If you have time, please critique the changed sentences and bulleted lists under **Options** (and anything else, of course). I applied some of what I am learning through the work you and alberto have done with rule descriptions.
* array-bracket-spacing: delete period in heading; default option first in ul; delete json; delete obsolete sentence about first/last element; move built-in exception from Rule Detail to Options; move Exceptions up to Options
* block-spacing: delete period in heading; delete json; rewrite options
* brace-style: delete …
=> Docs: Distinguish examples in rules under Stylistic Issues part 1

lib/rules/newline-before-return.js, tests/lib/rules/newline-before-return.js
Issue isn't accepted yet, but I wanted to put something together while it was still fresh in my mind.
My assumption is that there's no need to call this out in the rule documentation. Please let me know if I should.
=> Fix: newline-before-return handles return as first token (fixes #5816)

lib/util/module-resolver.js
For some reason, Jest loads modules differently and `module.paths` isn't present. There's no good way to test because Node includes `module.paths` by default. Just including this workaround to help Jest users out.
=> Fix: Check that module.paths exists (fixes #5791)

docs/rules/func-style.md, docs/rules/id-blacklist.md, docs/rules/id-length.md, docs/rules/id-match.md, docs/rules/indent.md
The second batch of (5) rules under Stylistic Issues.
The next batch will be bigger; I just didn't have as much time today as I had hoped. Depending on how this PR goes, I might just add the next 5-10 directly to this instead of a separate batch.
@pedrottimark There were a lot of differences in these rules from your latest updates, so could you give this a thorough look?
One concern before this gets merged: For options that don't have an explicit name, where should we put the code examples (apologies if this is answered in one of your issues / PRs)?
I found some more inconsistencies between some rules here and other rules, e.g. for the `id-match` rule, the `properties` object property option takes either `true` or `false`, but in other rules it takes `always` or `never`. This is outside …
=> Docs: Distinguish examples in rules under Stylistic Issues part 2

docs/user-guide/command-line-interface.md, lib/options.js
Since `inline-config` defaults to `true`, it's printed as `--no-default config` in `eslint -h`, and the description doesn't match the option.
=> Docs: Fix message for `inline-config` option

docs/rules/computed-property-spacing.md
Docs: Removed incorrect example for "computed-property-spacing"
=> Docs: Removed incorrect example

docs/rules/README.md
Make each paragraph which directly follows a h1 or h2 heading fit in one line at 600px width, so the rules index page is more inviting and usable on tablets.
Less text also helps readers for whom English is not first language.
However, sentences which merely restate the preceding headings could be confusing or frustrating, so please push back it I cut too much or lost meaning while rewriting in parallel grammatical form.
=> Docs: Reduce length of paragraphs in rules index

docs/rules/default-case.md, lib/rules/default-case.js, tests/lib/rules/default-case.js
This PR adds the `commentPattern` option to `default-case` rule which may be a string or a regular expression string and which overrides the default comment pattern.
If no option is specified, the default comment pattern is used.
The strict comparison of a trimmed comment with the "no default" string is replaced by the `^no default$` regular expression test for consistency.
=> Update: `commentPattern` option for `default-case` rule (fixes #5803)

docs/rules/no-extend-native.md
Change the severity in an example that I missed in a previous PR from integer to string.
=> Docs: Fix severity type in example

docs/rules/README.md
As briefly discussed in chat: since `sort-imports` checks ES6-specific functionality, it fits better under 'ECMAScript 6' as its primary category.
Reasoning: if a user doesn't use any ES6 features, they should be able to ignore everything in the 'ECMAScript 6' category only rather than go through each rule individually to check.
=> Docs: Move `sort-imports` to 'ECMAScript 6'

templates/pr-create.md.ejs, tests/templates/pr-create.md.ejs.js
This just removes the CLA check from our bot. We will rely completely on the jQuery bot from now on.
=> Chore: Remove CLA check from bot

README.md
Also made the Markdown a little more organized via judicious use of line breaks.
=> Docs: Fix missing delimiter in README links

lib/rules/constructor-super.js, lib/rules/no-this-before-super.js, tests/lib/rules/constructor-super.js, tests/lib/rules/no-this-before-super.js
Fixes #5894.
`segInfoMap[segment.id]` doesn't have information objects of unreachable segments.
I make this rule ignoring accesses of `this` on unreachable paths.
- Those are not executed.
- Those are warned by `no-unreachable`.
And I found the same issue on `constructor-super`, then I fixed it.
=> Fix: `no-this-before-super` crash on unreachable paths (fixes #5894)

docs/rules/comma-dangle.md, docs/rules/no-cond-assign.md, docs/rules/no-console.md, docs/rules/no-constant-condition.md, docs/rules/no-control-regex.md, docs/rules/no-debugger.md, docs/rules/no-dupe-args.md, docs/rules/no-dupe-keys.md, docs/rules/no-duplicate-case.md, docs/rules/no-empty.md
The first 10 rules under **Possible Errors**
Here are additional changes:
* comma-dangle: rewrite more precise contrast *same* versus *different* line instead of single versus multiple lines
* no-cond-assign: ambiguous assignment operators in test conditions
* no-console: methods of the `console` object
* no-constant-condition: constant expression as a test condition; move typeof into original example code
* …
=> Docs: Describe options in rules under Possible Errors part 1

README.md
PR with the same language for getting-started page of eslint.github.io: https://github.com/eslint/eslint.github.io/pull/248
=> Docs: Clarify init sets up local installation (fixes #5874)

docs/rules/jsx-quotes.md, docs/rules/key-spacing.md, docs/rules/keyword-spacing.md, docs/rules/linebreak-style.md, docs/rules/lines-around-comment.md, docs/rules/max-depth.md, docs/rules/max-len.md, docs/rules/max-nested-callbacks.md, docs/rules/max-params.md, docs/rules/max-statements.md
Refactored and simplified a lot of examples to fit under the relevant options. Also removed one reference to a deprecated rule.
Where options have been deprecated, examples should no longer reference the deprecated option, nor should the option be listed among the available options. However, a note with the following format should be placed at the bottom of its respective option summary:
**Deprecated:** The object property `maximum` is deprecated; please use the object property `max` instead.
=> Docs: Distinguish examples in rules under Stylistic Issues part 3

Makefile.js, lib/logging.js, lib/timing.js, packages/eslint-config-eslint/default.yml, tests/lib/cli-engine.js, tests/lib/config/config-initializer.js
Some assumptions I made:
1. Makefile.js can do whatever it wants with the console
1. lib/logging.js can do whatever it wants with the console
1. lib/timing.js can do whatever it wants with the console (BUT let me know if it should pull in lib/logging.js instead)
1. The remaining files (all of which were unit tests) can use sinon sandboxes to stub console methods and have them be reliably restored, which happens to skirt the rule
Let me know if anything seems fishy. Thanks!
=> Fix: Enable no-console rule in eslint-config-eslint (refs #5188)

tests/lib/rules/indent.js
There are two test cases for the `indent` rule where it appears that
newlines were intended but not included. This change adds them.
=> Fix: Add missing newlines to test cases (fixes #5947)

docs/rules/valid-jsdoc.md, lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
Allow @return(s) without return keyword in function when @abstract/virtual is present
My first ESLint PR, please be gentle 😛
=> New: Use process @abstract when processing @return (fixes #5941)

lib/rules/no-useless-call.js, lib/rules/no-useless-concat.js, lib/rules/no-useless-constructor.js, lib/rules/no-useless-escape.js, lib/rules/no-var.js, lib/rules/no-void.js, lib/rules/no-warning-comments.js, lib/rules/no-whitespace-before-property.js, lib/rules/no-with.js, lib/rules/object-curly-spacing.js, lib/rules/object-shorthand.js, lib/rules/one-var-declaration-per-line.js, lib/rules/one-var.js, lib/rules/operator-assignment.js, lib/rules/operator-linebreak.js, lib/rules/padded-blocks.js, lib/rules/prefer-arrow-callback.js, lib/rules/prefer-const.js, lib/rules/prefer-reflect.js, lib/rules/prefer-rest-params.js
Chore: Add metadata to existing rules - Batch 6 of 7 (refs #5417)
=> Chore: Add metadata to existing rules - Batch 6 (refs #5417)

docs/rules/object-shorthand.md, lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
This PR makes it so that ESLint correctly warns on computed methods for the `object-shorthand` method. The rule will now warn for the following when `object-shorthand` is set to `methods` or `always`:
```js
var foo = {
[bar]: function() {}
}
```
It continues not to warn in instances where the function is named, and never warns for anything related to computed properties.
I didn't see a sensible place for me to insert this update in the docs, but it's pretty minor so I wasn't sure it really warranted one anyways.
=> Update: object-shorthand lints computed methods (fixes #5871)

CONTRIBUTING.md
Before submitting #5977 I had signed the old CLA from before joining the jQuery Foundation, as it was still referenced in the contribution guidelines file.
@IanVS made me aware of the move on gitter.
Related issue about removing the CLA from eslint.org: https://github.com/eslint/eslint.github.io/issues/254
=> Docs: Update CLA link

docs/user-guide/command-line-interface.md, lib/options.js, tests/lib/options.js
- Remove misleading default value of true; --color isn't actually passed through unless explicitly provided
- Display both --color and --no-color in help message and update verbiage accordingly
=> Fix: Clarify color option (fixes #5928)

docs/rules/no-control-regex.md, lib/rules/no-control-regex.js, tests/lib/rules/no-control-regex.js
Regex'es defined with literal syntax were not handled as expected.
During the check we get the the regex from node and turn it to string,
then check if it contains control characters as in it. But
`regex.toString()` produces different outputs for literals and regexp
objects. Added another check, now it works as expected.
New check also interfered with the rule itself during `npm run lint`, I
had to use disable-line in the rule itself. I am not very proud of it.
=> Fix: no-control-regex literal handling fixed. (fixes #5737)

lib/config/autoconfig.js, tests/fixtures/autoconfig/source-with-comments.js, tests/lib/config/autoconfig.js
Autoconfig was crashing when pre-existing inline ESLint comments were resulting in linting errors.
Now, the config comments will still be applied (likely causing the rule to be unable to be configured), but the process will not crash.
=> Fix: Avoid autoconfig crashes from inline comments (fixes #5992)

docs/rules/prefer-arrow-callback.md
The document says **correct** examples, but those are incorrect examples.
=> Docs: Fix a wrong examples' header of `prefer-arrow-callback`.

docs/rules/arrow-parens.md
If they're not, quotes are turned into smart quotes / non-ASCII things that are ~~impossible~~impractical to copy & paste.
=> Config example belongs in code block

docs/rules/newline-per-chained-call.md
Add a sentence and a code example about diff readability to newline-per-chained-call docs.
I also updated the existing examples to use double quotes instead of single quotes!
=> Docs: Add example of diff readability to newline-per-chained-call

lib/cli-engine.js, lib/cli.js, tests/fixtures/formatters/broken.js, tests/lib/cli-engine.js
Fix for issue #5977 
If a formatter is broken, the exception telling you that it was broken would be swallowed by the catch block, and the error reporting would tell you that it could not find the formatter.
This fix means that any exception, that is not a result of the formatter module not being found, will be re-thrown.
=> Do not swallow exceptions in CLIEngine.getFormatter

docs/rules/no-delete-var.md, docs/rules/no-dupe-args.md, docs/rules/no-octal-escape.md, docs/rules/no-octal.md, docs/rules/no-with.md
Wording changed from the possibilities discussed in the issue, as often happens while editing 😐
Additional changes include making the main heading and first sentence under Rule Details consistent with description in rules index.
Agree with the idea https://github.com/eslint/eslint/issues/5485#issuecomment-215253380 to make “strict mode” a hyperlink. Instead of to the `strict` rule, it will be to a not-yet-written section, possibly in Configuring ESLint, which describes all the things that cause ESLint to parse code in strict mode:
* `"use strict";` in code
* `parserOptions.sourceType = "module"` in config
* `parserOptions.ecmaFeatures.impliedStrict = true` in config
Any others?
=> Docs: mention parsing errors in strict mode (fixes #5485)

conf/eslint.json, docs/rules/README.md, docs/rules/object-property-newline.md, lib/rules/object-property-newline.js, tests/lib/rules/object-property-newline.js
Add a new rule `object-property-newline` that is a port from JSCS requireObjectKeysOnNewLine.
=> New: Add new rule `object-property-newline` (fixes #5667)

lib/rules/max-statements-per-line.js, tests/lib/rules/max-statements-per-line.js
Previously `if (x) var y = 1; else var z = 1;` was allowed, now it isn't.
=> Breaking: Count blockless else in max-statements-per-line (fixes #5926)

docs/rules/no-irregular-whitespace.md, lib/rules/no-irregular-whitespace.js, tests/lib/rules/no-irregular-whitespace.js
`no-irregal-whitespace` ignores string literals correctly, but doen't regular expressions.  It is popular in Japan to include zenkaku-space (`\u3000`) in string literals or regular expressions.
Also check that the node is a regular expression in `removeInvalidNodeErrorsInIdentifierOrLiteral()`.  I also added test for this.
- Node.js v5.6.0
- OS X 10.11.4
=> no-irregal-whitespace incorrectly reported error in a regular expression

docs/developer-guide/working-with-rules-new.md, docs/developer-guide/working-with-rules.md
* bulleted list of rule files so it would be easy to add rule doc
* bulleted lists of meta properties (see #5417) and illustrated them in the first source file example
* use terms visit (verb) and visitor (noun) discussed in #5843 @jfmengels Can you please critique?
* use terms event and handler for code path analysis @mysticatea Can you please critique?
* illustrate visitors and handlers from `array-callback-return` in the second source file example
=> Docs: Organize meta and describe visitor in Working with Rules

README.md
Two changes:
* The value representing the error level may not be a number, so I just say "first value" here
* There are three error levels but six total representations of error levels, so I just changed "the three values" to "these values" when referring to the list of error codes.
=> Docs: Clarify rule example in README since we allow string error levels

lib/rules/no-sequences.js, tests/lib/rules/no-sequences.js
=> Fix: `no-sequences` false negative at arrow expressions (fixes #6082)

lib/eslint.js, tests/lib/eslint.js
Throw an error when a rule uses `fix` but has no `meta.fixable` property set. As discussed in #5970.
=> Fix: throw when rule uses `fix` but `meta.fixable` not set (fixes #5970)

docs/rules/object-shorthand.md, lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
This PR adds the `avoid-quotes` option discussed in #3366 to prevent the recommendation for object method shorthand in cases where 1) the key is a string literal, and 2) the key would be an invalid identifier if not stringified.
After going through this, I tend to feel that that is probably not the right approach, even though it solves the problem as stated in the PR. I thin kit would be better to have this new option for `object-shorthand` prevent warning on *any* stringified key, and have `quote-props` actually validate shorthand property keys (right now it just bails out early). Those two together would do a better job of specifying whether something is an "improperly" formatted key.
Thoughts?
=> Update: Adds an avoid-quotes option for object-shorthand (fixes #3366)

lib/rules/comma-style.js, tests/lib/rules/comma-style.js
Checks to see if the token right before the comma is a closing parens and uses that token if it is. ~~Also updated the calls on the context object to the current API.~~ Didn't realize @alberto was doing the same thing - his PR was merged today so I just rebased.
=> Fix: comma-style accounts for parens in array (fixes #6006)

docs/rules/one-var-declaration-per-line.md
Updated docs to indicate the actual default. Fixed wording from `around a variable initialization` to `around each variable initialization`.
=> Docs: Correct default for `one-var-declaration-per-line` (fixes #6017)

docs/rules/one-var-declaration-per-line.md
The example made it appear like this rule can be used to enforce initializations in the same line as other vars, but it doesn't.
=> Docs: Improve showcase example in `one-var-declaration-per-line`

lib/rules/no-return-assign.js, tests/lib/rules/no-return-assign.js
Fixes #5913.
I modified the logic of this rule.
This will handle assignment expressions, then check their ancestor nodes.
=> Fix: `no-return-assign` warning nested expressions (fixes #5913)

docs/rules/no-empty-character-class.md, docs/rules/no-ex-assign.md, docs/rules/no-extra-boolean-cast.md, docs/rules/no-extra-parens.md, docs/rules/no-extra-semi.md, docs/rules/no-func-assign.md, docs/rules/no-inner-declarations.md, docs/rules/no-invalid-regexp.md, docs/rules/no-irregular-whitespace.md, docs/rules/no-negated-in-lhs.md
The next 10 rules under **Possible Errors**
Here are additional changes:
* no-empty-character-class: add Known Limitations; delete Related Rules link to removed rule
* no-ex-assign: make examples parallel
* no-extra-parens: add links to rules with potential conflicts which are ignored
* no-irregular-whitespace: move examples from Rule Details to Options; change indent from 2 to 4
* no-negated-in-lhs: rewrite …
=> Docs: Describe options in rules under Possible Errors part 2

Makefile.js
Prerequisite to stage 1 described in https://github.com/eslint/eslint/issues/5774#issuecomment-216530450
During verification step of rule docs files, match the rule id in the main heading **either**
*   in original format: at the end, enclosed in parentheses
require or disallow trailing commas (comma-dangle)
*   in new format: at the beginning, followed by a colon
comma-dangle: require or disallow trailing commas
Short-term goal: After all rule docs files have been converted to the new format, its regexp pattern will be removed from the verification step.
Long-term goal: Instead of verification, the build process will automatically generated the heading from rule metadata, see https://github.com/eslint/eslint/issues/5774#issuecomment-216996951
EDIT: But must remember that **removed** …
=> Build: Match rule id at beginning of heading (refs #5774)

docs/rules/generator-star.md, docs/rules/global-strict.md, docs/rules/no-arrow-condition.md, docs/rules/no-comma-dangle.md, docs/rules/no-empty-class.md, docs/rules/no-empty-label.md, docs/rules/no-extra-strict.md, docs/rules/no-reserved-keys.md, docs/rules/no-space-before-semi.md, docs/rules/no-wrap-func.md, docs/rules/space-after-function-name.md, docs/rules/space-after-keywords.md, docs/rules/space-before-function-parentheses.md, docs/rules/space-before-keywords.md, docs/rules/space-in-brackets.md, docs/rules/space-return-throw-case.md, docs/rules/space-unary-word-ops.md, docs/rules/spaced-line-comment.md
The rest of stage 1 described in https://github.com/eslint/eslint/issues/5774#issuecomment-216530450 which was dependent on #6089
For 18 removed rules:
* Update the description in the main headings and move the rule identifier to the beginning (for similarity with the rules index).
* Display the **X** glyphicon at the left of the removed/replaced sentences.
* Make the sentences consistent in wording (they are already similar).
Extra change to space-in-brackets: deleted link to computed-property-spacing because it was not on the rules index and because lack of any mention of computed properties in the doc suggests that they were out of the scope of the removed rule
=> Docs: Update headings of rules under Removed (refs #5774)

Makefile.js, tests/templates/pr-create.md.ejs.js
#6109 `split(/\r?\n/)` always returns the first line of the commit if there's multiple lines or just one line.
Same logic as `templates/pr-create.md.ejs`:
```js
// get just the first line of the commit message
var log = meta.commits[0].commit.message.split(/\r?\n/g)[0];
```
https://github.com/eslint/eslint/blob/master/templates/pr-create.md.ejs#L23
=> Build: Use split instead of slice/indexOf for commit check (fixes #6109)

lib/config.js, tests/fixtures/configurations/es6.json, tests/lib/cli.js
#6104 Moves parser and parserOptions merging from step 2 to step 5.
=> Fix: Merge various command line configs at the same time (fixes #6104)

lib/rules/no-loop-func.js, tests/lib/rules/no-loop-func.js
Fixes #6130.
In `let` variable's cases, `getTopLoopNode` finds a loop node which directly contains the `let` declaration or exists after the `let` declaration. But, if there is not such loop node, `no-loop-func` had been crashing.
=> Fix: `no-loop-func` crashed (fixes #6130)

lib/ast-utils.js, tests/lib/rules/consistent-return.js
As discussed in #6085, the previous case-matching code was overly liberal in matching these punctuation characters, which are not commonly used to begin constructor names.  In the case that they are used, such uses may be excluded from the relevant rules using inline configuration.
Fixes: #6085
=> Fix: Exclude _ and $ from isES5Constructor (fixes #6085)

lib/rules/no-irregular-whitespace.js
The bulk of the expense from running `no-irregular-whitespace` comes from visiting each `Identifier` - not the work performed while visiting, just the act of visiting.
This change optimizes the rule for the common case of not having any irregular whitespace. It's really cheap to test the entire source for the irregular characters before creating the visitors, and then only create them if there are any irregular characters. A few more changes include: creating the regexs only created once, and using `test` instead of `match` where possible, among others.
Before:
```
$ for i in {1..5}; do TIMING=1 ./bin/eslint.js --no-eslintrc --rule 'no-irregular-whitespace: 1' lib; done
Rule                    | Time (ms) | Relative
:-----------------------|----------:|--------:
no-irregular-whitespace | …
```
=> Fix: Optimize no-irregular-whitespace for the common case (fixes #6116)

docs/user-guide/configuring.md
Make it clear that you need to do more than just enable JSX to get useful linting when JSX is used.
=> Docs: Clarify JSX option usage

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
=> Fix: `valid-jsdoc` false positive at default parameters (fixes #6097)

docs/rules/no-obj-calls.md, docs/rules/no-regex-spaces.md, docs/rules/no-sparse-arrays.md, docs/rules/no-unexpected-multiline.md, docs/rules/no-unreachable.md, docs/rules/no-unsafe-finally.md, docs/rules/use-isnan.md, docs/rules/valid-typeof.md
The next 8 rules under **Possible Errors**
I am leaving valid-jsdoc for later because it has complicated changes to review and because there are open pull requests and issues which affect it.
Here are additional changes:
* no-obj-calls: modify examples
* no-regex-spaces: move `RegExp` constructor example from correct code to false negative under Known Limitations
* use-isnan: modify second example of correct code …
=> Docs: Describe options in rules under Possible Errors part 3

conf/cli-options.js, tests/fixtures/configurations/parser/.eslintrc.json, tests/fixtures/configurations/parser/custom.js, tests/lib/cli-engine.js, tests/lib/config.js
Not sure how to add tests for this, submitting because it's probably breaking badly for a lot of people.
I think it won't break anything if no parser is specified, since it is set by `lib/eslint.js`, but please review @eslint/eslint-team
=> Fix: Remove default parser from CLIEngine options (fixes #6182)

lib/rules/max-statements-per-line.js, tests/lib/rules/max-statements-per-line.js
Fixes #6173, 
Fixes #6153.
I rewrote the traversal logic of this rule.
Before, it uses a `for` loop in BlockStatement handler.
After this PR, it uses ESLint's traversing. So this rule gets addressing nested nodes correctly.
=> Fix: `max-statements-per-line` false positive (fixes #6173, fixes #6153)

lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
BOF and EOF variables now set as intended and BOF can be larger than max option
=> Fix: no-multiple-empty-lines BOF and EOF defaults (fixes #6179)

docs/rules/consistent-return.md, lib/rules/consistent-return.js, tests/lib/rules/consistent-return.js
Adds a new option to the `consistent-return` rule to treat `return undefined;` and `return void [...];` the same as `return;`
=> Update: Add treatUndefinedAsUnspecified option (fixes #6026)

conf/eslint.json, docs/rules/README.md, docs/rules/no-prototype-builtins.md, lib/rules/no-prototype-builtins.js, tests/lib/rules/no-prototype-builtins.js
This is the new rule proposed in #2693 by @sindresorhus. This rule, when enabled, will prevent calling the following `Object.prototype` built-ins directly on an object:
- hasOwnProperty
- isPrototypeOf
- propertyIsEnumerable
Instead, the rule prompts developers to use `Object.prototype.{property}.call`.
There are a few things I need to improve, and would love input on.
1. Should there be any options for this rule?
2. Should any more built-ins be added besides the 3 listed above?
3. Need suggestions for a better message to provide in `context.report` - the current one likely isn't clear enough
4. Need suggestions of `Related Rules`
Of course, any other feedback is also welcome :)
=> New: Disallow use of Object.prototype methods on objects (fixes #2693)

docs/user-guide/README.md, docs/user-guide/rule-deprecation.md
Made a first pass at capturing this for the official docs. Thoughts @eslint/eslint-team?
Thoughts I had while writing it out:
* Should we be more specific about what "for the next year" means? i.e. include specific dates?
* I initially liked "Backwards Compatibility" better, but now I'm wonder if it should just cut to the chase and say "Deprecated Rules".
=> Docs: Add rule deprecation section to user guide (fixes #5845)

lib/cli-engine.js, tests/fixtures/rules/make-syntax-error-rule.js, tests/lib/cli-engine.js
Refs #6233.
I added `break` statement into the multipass fixing loop.
This prevents deleting the text.
It would make `fixedResult` at least 1 time even if there is a syntax error from the first time.
=> Fix: lost code in autofixing (refs #6233)

docs/rules/arrow-body-style.md
I think the 19 ❤️ s [here](https://github.com/eslint/eslint/issues/5498#issuecomment-193251152) indicate that this rule could use an extra example or 2.
=> Added example for issue #5498

lib/rules/comma-dangle.js, tests/lib/rules/comma-dangle.js
Fixes #6233.
In an original way, it was a bit hard that it gets proper position to add a comma in a common logic since traversal direction is different (→/←) for each fork.
=> Fix: `comma-dangle` wrong autofix (fixes #6233)

conf/eslint.json, docs/rules/README.md, docs/rules/unicode-bom.md, lib/rules/unicode-bom.js, tests/lib/rules/unicode-bom.js
Add a new rule that allows or disallows the Unicode Byte Order Mark (BOM) depending on the option chosen. References Github issue #5502
=> New: `unicode-bom` rule to allow or disallow BOM (fixes #5502)

lib/rules/vars-on-top.js, tests/lib/rules/vars-on-top.js
Fixes #6210.
Just added a null check.
The declaration property is nullable by [spec](https://github.com/estree/estree/blob/master/es6.md#exportnameddeclaration)
=> Fix: `vars-on-top` crashs at export declarations (fixes #6210)

docs/rules/arrow-parens.md
Docs: The output value in the arrow-parens docs is wrong.  The arrow function reference is truthy, and it's not immediately invoked.  The output log is "truthy value returned".
=> Update: arrow-parents.md to show appropriate output value of if statement

lib/rules/object-property-newline.js, tests/lib/rules/object-property-newline.js
Syntax that wasn't handled correctly / caused errors to be thrown:
- computed keys spanning multiple lines
- experimental object spread
=> Fix: Incorrect object-property-newline behavior (fixes #6207)

.travis.yml, templates/pr-create.md.ejs, tests/templates/pr-create.md.ejs.js
This removes the commit count check from both Travis and the bot since we always squashing PRs now.
It still checks the first commit message to ensure it's the correct format.
=> Build: Don't check commit count (fixes #5935)

lib/config/config-ops.js, lib/eslint.js, package.json, tests/lib/eslint.js
Fixes #6224.
It came to use Optionator to parse the comments by the same way as parsing CLI option. But Optionator cannot parse commaless notation, so there is a fallback for that.
Also, I just reordered requirements by file paths.
=> Fix: failed to parse `/*eslint` comments by colon (fixes #6224)

docs/rules/valid-jsdoc.md
The last rule under **Possible Errors**
**Hint**: The diff gets confusing after the bulleted list under Rule Details. At that point, you might click **View** and compare the markdown view to the Web site: http://eslint.org/docs/rules/valid-jsdoc
@nzakas EDIT can you verify that the rule details are clear, options list is correct, and examples are relevant, because I am just now learning JSDoc
@scriptdaemon your …
=> Docs: Describe options in rules under Possible Errors part 4

lib/ignored-paths.js, lib/util/glob-util.js, tests/lib/ignored-paths.js
=> Update: Improve perf not traversing default ignored dirs (fixes #5679)

lib/rules/no-useless-rename.js, tests/lib/rules/no-useless-rename.js
I had a couple of options here-- either compare the type explicitly, or just look for the absence of a `key` property. I went with the former to be safe, but I can certainly amend to the latter if people think that is better.
At this point I've only handled destructuring-- not sure yet if this is an issue in import or export. I'll investigate that and update this PR if needed. (EDIT: Seems those use a `*` token instead. In addition, that seems to be standard ES2015. So I assume we're good-- speak up if I missed something.)
=> Fix: no-useless-rename handles ExperimentalRestProperty (fixes #6284)

lib/rules/no-useless-rename.js
Sorry, this one should fix it for real. I manually tested it using `babel-eslint`.
=> Fix: `no-useless-rename` false positive in babel-eslint (fixes #6266)

docs/rules/no-lonely-if.md, docs/rules/no-mixed-spaces-and-tabs.md, docs/rules/no-multiple-empty-lines.md, docs/rules/no-negated-condition.md, docs/rules/no-nested-ternary.md, docs/rules/no-new-object.md, docs/rules/no-plusplus.md, docs/rules/no-restricted-syntax.md, docs/rules/no-spaced-func.md, docs/rules/no-ternary.md
Another straight-forward batch.
@pedrottimark Let me know if anything catches your eye.
=> Docs: Distinguish examples in rules under Stylistic Issues part 5

docs/rules/callback-return.md, lib/rules/callback-return.js, tests/lib/rules/callback-return.js
~~The one caveat about solving this problem this way is that it must match exactly - i.e. `object().method` is not the same thing as `object.method`. This seems to me like a reasonable tradeoff to solve this issue right now, though maybe it could be made much smarter in the future.~~ Updated, no longer relevant.
=> Update: callback-return allows for object methods (fixes #4711)

conf/eslint.json, docs/rules/README.md, docs/rules/object-curly-newline.md, lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-newline.js
Fixes #6072 (and #6205).
The issue has not been accepted yet, but I made this PR for a reference.
I'd like to see feedback, then if it can do, I'd like to add `accepted` label.
=> New: `object-curly-newline` (fixes #6072)

docs/developer-guide/working-with-custom-formatters.md
=> Typo fix 'colum' -> 'column'

docs/developer-guide/code-conventions.md
Highlights:
* File overview section: Removed notes about copyright
* Strict mode: Rewrote guidelines to favor global "strict" mode
* Other tweaks: Fixed ambiguity about for statement spacing
I removed everything to do with copyright from that section. Now that we are in the jQuery foundation, we have decided to just use the "author" field and no copyright or license.
Our repository [enforces global "strict"](https://github.com/eslint/eslint/blob/89580a40557093184b5e164b7ef284670d47090b/packages/eslint-config-eslint/default.yml#L94), but the code conventions imply that we should have ["strict" mode in functions](https://github.com/eslint/eslint/blob/89580a40557093184b5e164b7ef284670d47090b/docs/developer-guide/code-conventions.md#strict-mode).
My assumption is that those conventions have …
=> Docs: Code conventions improvements

docs/rules/strict.md
The only rule under **Strict Mode**
Additional changes:
* Display (removed) X icon at the left of the sentence for the earlier default option. What do you think?
* Moved the `"never"` option to be the last active option, so it does not separate `"global"` and `"function"` from `"safe"` **Hint**: The diff gets confusing after **safe**. At that point, you might click **View** and compare the markdown view to the Web …
=> Docs: Describe options in rule under Strict Mode

docs/about/index.md
EDIT: Ah crap, the commit summary is too long. Whoever reviews this, feel free to squash with a different message, or let me know if you want me to force-push to fix the message.
=> Docs: Remove reference to numeric configuration from About page (fixes #6309)

.eslintignore, Makefile.js, conf/eslint-all.js, lib/config/config-file.js, tests/lib/config/config-file.js
This adds a new option to allow a user to extend `eslint:all` in order
to enable all rules by default.
=> New: Add `eslint:all` option (fixes #6240)

docs/rules/arrow-body-style.md, lib/rules/arrow-body-style.js, tests/lib/rules/arrow-body-style.js
Arrow functions that return object literals can look very similar to arrow functions with brace bodies.  Some syntactic ambiguity can be avoided by disallowing block-style arrow functions in favour of ES5 function expressions.
**Outcome**
The following patterns are considered problems:
```
/*eslint arrow-body-style: ["error", "never"]*/
/*eslint-env es6*/
let foo = () => {
return 0;
};
let foo = (retv, name) => {
retv[name] = true;
return retv;
};
```
The following patterns are not considered problems:
```
/*eslint arrow-body-style: ["error", "never"]*/
/*eslint-env es6*/
let foo = () => 0;
let foo = () => ({ key: 0 });
```
=> Update: Add never option to arrow-body-style (fixes #6317)

conf/eslint.json, docs/rules/README.md, docs/rules/no-mixed-operators.md, lib/ast-utils.js, lib/rules/no-extra-parens.js, lib/rules/no-mixed-operators.js, tests/lib/rules/no-mixed-operators.js
Fixes #6023.
This PR is a reference for discussion.
=> New: `no-mixed-operators` rule (fixes #6023)

docs/developer-guide/working-with-plugins.md
Following the discussion we had in (#6227), I'm adding a section about how to customize RuleTester to work with different test runners like AVA. Didn't go into too much detail, as I figure you'll probably need to go and read the code anyway. At least people will now know that it's possible.
Let me know if you have suggestions on how to improve this.
(PS: If you found this by searching for AVA, I wrote the following package to allow RuleTester to be used with AVA https://github.com/jfmengels/eslint-ava-rule-tester)
=> Docs: Add section about customizing RuleTester (fixes #6227)

docs/user-guide/configuring.md
For this docs counterpart to #6248 let’s aim for about 3 steps of critique:
1. Baseline with only **placeholder** content for `"eslint:all"`
* Critique a new **structure** for Extending Configuration Files that is adapted from new structure under Options in rule docs: bulleted list of `extends` property values followed by level-3 headings with an example of configuration.
* Critique reorganization and rewriting of existing **content**. Is it correct, clear, and complete in context? For example, this section is the target of the link about `"eslint:recommended"` on the rules index page. In particular, can whoever has expert knowledge ( @IanVS ? :) help me with the paragraph about “ESLint resolves a relative path…”
2. Baseline improvements plus **first draft** of new content about …
=> Docs: Describe values under Extending Configuration Files (refs #6240)

docs/developer-guide/working-with-plugins.md
I included an example of a short-form plugin rule configuration and a long-form plugin rule configuration-- let me know if that seems excessive.
=> Docs: Clarified how plugin rules look in plugin configs (fixes #6346)

docs/user-guide/configuring.md
Agreed with the user that this could be clearer, figured I could take a few minutes to try to make it better :)
=> Docs: clarify usage of inline disable comments (fixes #6335)

docs/rules/no-mixed-operators.md
There are a few broken links in the documentation for the [no-mixed-operators](http://eslint.org/docs/rules/no-mixed-operators) rule on the eslint.org website. All of the links for `no-extra-parens` are incorrectly pointing at a non-existent `.md` file. 
The links work correctly from within github; they're only broken on the website. I'm assuming this is because the website generator can't handle reference links being used instead of inline links. If my assumption is correct, then this PR should fix it :D
=> Docs: Fix broken links in no-mixed-operators

docs/rules/object-curly-newline.md
A "Related Rules" link pointed to the wrong rule.
=> Docs: Fix wrong link in object-curly-newline

docs/rules/README.md, docs/rules/no-multiple-empty-lines.md, lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
Multiple empty lines rule fixer. Removes empty lines at beginning, middle or end of file. An array of lines is created along with an array of range starts. This is required to define the deletion ranges from line indices.
=> Update: no-multiple-empty-lines fixer (fixes #6225)

docs/developer-guide/nodejs-api.md
=> Update docs to make `fix` param more clear in NodeJS API

lib/rules/newline-per-chained-call.js, tests/lib/rules/newline-per-chained-call.js
fixes #6340.
- Changed the message to `Expected line break before 'PropertyName'.`  
- Property is shorter than object if it's chained.
- The error locations are at properties, so it's more consistent.
=> Fix: improve `newline-per-chained-call` message (fixes #6340)

docs/user-guide/configuring.md
Fix 3 copy-and-paste mistakes, my bad.
* The 2 links to command-line-interface were broken. The `./` prefix seems to be needed (at least in local testing) because of the redirect from old location?
* More consistent for the link to rules index to be relative instead of absolute.
=> Docs: Fix links in Configuring ESLint

lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-newline.js
Fixes #6381.
I modified the rule to use comments also to check whether an object literal is multiline or not.
=> Fix: `object-curly-newline` multiline with comments (fixes #6381)

docs/rules/README.md, docs/rules/padded-blocks.md, lib/rules/padded-blocks.js, tests/lib/rules/padded-blocks.js
Note this doesn't deal with differences in linebreaks or keeping correct indentation, since it seems there is consensus in leaving that to subsequent fix passes.
=> Update: Add autofix for `padded-blocks` (fixes #6320)

docs/developer-guide/contributing/reporting-bugs.md
A gitter chat link was added to the same paragraph in Change Requests https://github.com/eslint/eslint.github.io/pull/217
=> Docs: Add gitter chat link to Reporting Bugs

docs/developer-guide/code-path-analysis.md, docs/developer-guide/code-path-analysis/README.md
Maybe was for a different markdown-to-HTML converter to produce a page TOC?
Looks like we have a duplicate doc to sort out too.
=> Docs: Delete empty table of links from Code Path Analysis

docs/rules/space-before-blocks.md
Made `classes` key consistent with all other option keys which are quoted..
=> Docs: Quoted "classes" option key (fixes #6440)

lib/rules/accessor-pairs.js, lib/rules/array-bracket-spacing.js, lib/rules/default-case.js, lib/rules/no-mixed-operators.js, lib/rules/no-prototype-builtins.js, lib/rules/no-script-url.js, lib/rules/no-unsafe-finally.js, lib/rules/object-curly-newline.js, lib/rules/unicode-bom.js
Avoid losing some improvements to descriptions in rules index when we generate it automatically.
=> Chore: Fix rule meta description inconsistencies (refs #5417)

package.json, tests/lib/eslint.js
Fixes #6013.
This syntax error came to be raised since Acorn 3.2.0. This syntax error prevents a false positive of `no-undef` rule.
RuleTester fails always on syntax errors, so I added this test into `tests/lib/eslint.js`.
=> Fix: add test for a syntax error (fixes #6013)

docs/rules/max-params.md
Original meaning inferred from earlier statements in the file, the header for the immediate example, and the code for the rule itself (on line 49). The docs described the default value as `4`, but the actual default value is `3`.
=> Docs: Fix typo in max-params examples

lib/rules/padded-blocks.js, tests/lib/rules/padded-blocks.js
For #6454, keep the leading spaces/tabs instead of deleting up to the `nextToken`. Fixes/adds tests.
=> Fix: Keep indentation when fixing `padded-blocks` "never" (fixes #6454)

lib/config/config-file.js, tests/fixtures/config-file/extends-chain-2/parser.eslintrc.json, tests/fixtures/config-file/extends-chain-2/relative.eslintrc.json, tests/lib/config/config-file.js
Fixes #6450 
I'm not sure this fix is correct or not. I want to get any insights about `getBaseDir`.
And actually, this new test does not make sense. The test succeeds as well before this fix. The issue's error seems to be appeared only if eslint is installed to another package. I'm not sure how to write tests for this fix...
=> Fix: wrong baseDir (fixes #6450)

lib/cli-engine.js
The "processed" identifier is not read from anywhere within executeOnFiles. All tests pass after removing it.
=> Remove dead code in excuteOnFiles

docs/rules/strict.md, lib/rules/strict.js, tests/lib/rules/strict.js
Fixes #6405.
I didn't remove warnings for functions with a non-simple parameter list as I followed https://github.com/eslint/eslint/issues/6377#issuecomment-226193450
- `function foo(a = 0) { 'use strict' }` is always warned: "'use strict' directive inside a function with non-simple parameter list throws a syntax error since ES2016."
- `function foo(a = 0) { }` is warned under `function` option: "Wrap this function in a function with 'use strict' directive."
=> Fix: `strict` rule reports a syntax error for ES2016 (fixes #6405)

docs/rules/README.md, docs/rules/object-shorthand.md
The contributing instructions ask for each PR to have an issue as well. I am happy to do that, but in this case it seemed sufficiently trivial that a separate issue was not necessary.
This is a follow-up to #6418.
=> Docs: Mark object-shorthand as fixable.

Makefile.js, docs/developer-guide/nodejs-api.md, lib/cli-engine.js, lib/cli.js, tests/lib/cli-engine.js
added a warnIgnored parameter to executeOnText similar to the existing executeOnFile function.  the check is for an explicit `false` parameter so this doesn't break existing code
=> Fix: add warnIgnored flag to CLIEngine.executeOnText (fixes #6302)

lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
Fixes #6429.
I refactored the logic flow. The new flow has 3 parts.
1. Check whether it should be ignored always or not.
2. Check for concise properties.
3. Check for longform properties.
Then I fixed it for #6429.
=> Fix: false negative of `object-shorthand` (fixes #6429)

docs/rules/arrow-body-style.md, docs/rules/arrow-parens.md, docs/rules/generator-star-spacing.md
Fixing typos that were identified in an earlier PR.
=> Docs: Fixing typos #5446

docs/rules/no-dupe-class-members.md, docs/rules/no-new-symbol.md, docs/rules/no-restricted-imports.md, docs/rules/no-this-before-super.md, docs/rules/no-useless-computed-key.md, docs/rules/no-useless-constructor.md, docs/rules/no-var.md
This PR replaces #6487.
1. Ensure each doc has "Examples" heading, and that each
option-specific example pair also has a suitable heading.
2. Ensure text above examples is consistent as per #5446
This PR does not attempt to address issues other than
those stated above; such issues will be dealt with on
subsequent sweeps of the docs detailed in #6444..
Note: Skipped no-duplicate-imports due to #6455, will
come back to that one at later date.
=> Docs: Consistent example headings & text pt2 #5446

docs/rules/prefer-rest-params.md, docs/rules/prefer-spread.md, docs/rules/prefer-template.md, docs/rules/require-yield.md, docs/rules/sort-imports.md, docs/rules/template-curly-spacing.md, docs/rules/yield-star-spacing.md
Final batch of es6 docs for this sweep!
1. Ensure each doc has "Examples" heading, and that each
option-specific example pair also has a suitable heading.
2. Ensure text above examples is consistent as per #5446
This PR does not attempt to address issues other than
those stated above; such issues will be dealt with on
subsequent sweeps of the docs detailed in #6444..
=> Docs: Consistent example headings & text pt4 (refs #5446)

docs/rules/prefer-reflect.md
Just a single doc in this batch due to variance in changes:
Headings were already present, however they were
over-complicated; I separated out the old (ES3/5) feature
from the heading and put it in a block quote to distinguish
it from the new (Reflect API) feature.
As per previous batches, ensured text above examples is
consistent as per #5446
This PR did not focus on issues other than those stated
above; such issues will be dealt with on subsequent
sweeps of the docs detailed in #6444.
=> Docs: Consistent example headings & text pt3 (refs #5446)

docs/developer-guide/contributing/pull-requests.md
Did a bit of cleanup for stuff that no longer applies:
* Removed references to squashing commits since we do that for you
* Added reference to developer guide in the rebase section
=> Docs: Update pull request steps (fixes #6474)

CONTRIBUTING.md
This gets CONTRIBUTING.md and README.md in sync in terms of providing guidance for different types of issues.
=> Docs: Add "Proposing a Rule Change" link to CONTRIBUTING.md

docs/rules/max-lines.md
Current docs contains invalid samples of `max-lines` rules configuration:
`eslint max-lines: ["error", 2, {"skipComments": true}]`
should be
`eslint max-lines: ["error", {"max":2, "skipComments": true}]`
=> chore(docs): fix max-lines samples (fixes #6516)

docs/rules/README.md, docs/rules/arrow-parens.md, lib/rules/arrow-parens.js, tests/lib/rules/arrow-parens.js
This PR adds auto fix for arrow-parens rule. It removes the params as-needed and adds them when set to always.
=> Update: Add fixer for arrow-parens (fixes #4766)

docs/rules/README.md, lib/rules/comma-dangle.js, lib/rules/no-native-reassign.js, lib/rules/no-unsafe-finally.js
Because `comma-dangle` is removed from `"eslint:recommended"` in ESLint 3.0.0:
* Move from Possible Errors to Stylistic Issues in the rules index
* Change `recommended` from `true` to `false` in rule `meta` data
Because `no-native-reassign` and `no-unsafe-finally` are added to `"eslint:recommended"`
* Change `recommended` from `false` to `true` in rule `meta` data
=> Chore: Update index and `meta` for `"eslint:recommended"` (refs #6403)

docs/rules/README.md, docs/rules/prefer-const.md, lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
This time, I remembered to update the docs 😄 !
@nzakas told me that it's ok if the fixer does not catch every case. I tried to stay away from the cases where it would be less obvious how the user would want to have the issue be fixed; let me know if you think are some more cases I should try to handle.
I also improved the grammar on the error message for `prefer-const`.
=> Update: Add fixer for prefer-const (fixes #6448)

lib/config.js, messages/no-config-found.txt, tests/fixtures/source-code-util/.eslintrc.json, tests/lib/config.js
Pulled in @IanVS' commit and added a few of my own to reorganize things a bit. I'm *fairly* sure this is ready, but let me know if I can organize things better (or if I should revert some of my last commits).
Organization stuff:
* Created new sub-describe in tests for cases where local and personal config does not exist (throws unless no-eslintrc or unless there is at least one rule key/value pair)
* Tried to make lib/config.js getLocalConfig() have fewer exit points. At the end is an if statement setting up the throw condition, and immediately after that is an unconditional return.
Thanks in advance for any feedback.
Ping @IanVS, @nzakas
=> Breaking: Error thrown/printed if no config found (fixes #5987)

docs/rules/no-unused-vars.md, lib/config/environments.js, lib/rules/no-unused-vars.js, tests/lib/config/environments.js, tests/lib/rules/no-unused-vars.js
Fixes #6348.
`no-unused-vars` comes to ignore a read of a modification of itself.
- A read in RHS of an assignment to itself (e.g. `a = a + 1`)
- A read in LHS of an assignment (e.g. `a += 1`)
- Increments/Decrements (e.g. `a++`)
Those are ignored only if those exist at the direct child of an
ExpressionStatement node. This is in order to avoid false positive such
`foo(a = a + 1)`
=> Update: `no-unused-vars` ignores read it modifies itself (fixes #6348)

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
Partly fixes #6259. I've only added support for IIFEs and not for the other forms of full-file closures described [here](https://contribute.jquery.org/style-guide/js/#full-file-closures) because I don't know much about the other forms.
Some questions for people who know a bit more about eslint:
* Do I need to add anything to the `indent-valid-fixture-1.js` or `indent-invalid-fixture-1.js` test files?
* Any thoughts on the option name?
* There are some [crazy ways](http://stackoverflow.com/a/23925102/874671) of writing IIFEs, should we support them all?
=> Update: Implement IndentOuterIIFE option for indent rule (fixes #6259)

docs/rules/no-regex-spaces.md, lib/rules/no-regex-spaces.js, tests/lib/rules/no-regex-spaces.js
Fixes #3586, making it so a single string literal in a `RegExp` constructor is also checked for multiple consecutive spaces.
=> Update: Check strings in RegExp constructors for `no-regex-spaces` (fixes #3586)

docs/developer-guide/working-with-plugins.md, docs/developer-guide/working-with-rules-deprecated.md, docs/developer-guide/working-with-rules.md
Switch over to new rule format for the docs and leave reference to deprecated rules around.
=> Docs: Update rule docs for new format (fixes #5417)

tests/lib/config.js
This was the simplest fix. I'm sure that some refactoring is in order, but I wanted to keep things simple pre-3.0.0.
=> Fix: lib/config.js tests pass if personal config exists (fixes #6559)

docs/rules/no-trailing-spaces.md, docs/rules/no-underscore-dangle.md, docs/rules/no-unneeded-ternary.md, docs/rules/no-whitespace-before-property.md, docs/rules/object-curly-newline.md
Found some time to get a quick batch in.
`object-curly-newline` has the option to have separate configurations for object literals and destructuring assignments. My mind is drawing a blank, did we have any specific way to handle options for this kind of case?
@pedrottimark Mind giving this a look?
Slowly and surely... :smiley:
=> Docs: Distinguish examples in rules under Stylistic Issues part 6

lib/rules/max-len.js, tests/lib/rules/max-len.js
Fixes #6564.
This corrects a bug in the `isFullLineComment` helper function, which was incorrectly identifying non-commented lines of code as full-line comments if they were preceded by a commented line of the same length.
=> Fix: false negative of `max-len` (fixes #6564)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Also clean jsdocs for internal helpers
=> Fix: make `no-unused-vars` ignore for-in loops (fixes #2342)

lib/cli-engine.js, lib/config/config-file.js, lib/util/path-util.js, package.json
=> Chore: remove path-is-absolute in favor of the built-in (fixes #6598)

lib/rules/indent.js, tests/lib/rules/indent.js
This should make the `outerIIFEBody` option work as intended:
1. Make sure the indent is a multiplier, not a set number of spaces.
2. Fix false positive top-level IIFE detection.
=> Fix: Make outerIIFEBody work correctly (fixes #6585)

docs/rules/id-length.md
Changed 2 typos:
exceptions accepts array,
was max property instead of exception property.
=> Docs: rules\id-length ###exceptions typos (fixes #6397)

docs/rules/no-unused-vars.md, lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
Fixes #6576.
I added a check to check whether the Identifier of a read reference exists inside of a function node which can be used later or not.
"can be used later" is meant:
- the function is assigned to a variable.
- the function is bound to a property, and the object can be used later.
- the function is bound to an argument of a function call.
If a reference exists in a function which can be used later, the reference is read when the function is called.
=> Fix: `no-unused-vars` false positive around callback (fixes #6576)

docs/developer-guide/contributing/pull-requests.md
The newly added pull request template states that "all pull requests require an **accepted** issue." However, the contributing docs are no clear on that point. People should have a chance to become aware of this information before they submit the pull request, not after they've done on the work and are about to submit a PR.
I updated the docs to clarify that a PR requires an **accepted** issue.
I'm not clear on what makes an issue accepted. I'm assuming a contributor adds an accepted tag to the issue, but the greater question is what are the criteria for having an issue accepted?
=> Docs: Note that PR requires ACCEPTED issue (refs #6568)

docs/rules/semi.md
Hello :wave:,
I found out that the last resource of the [semi rule](http://eslint.org/docs/rules/semi.html) documentation page doesn't exist anymore. I couldn't find any backup of it online either, so I think it's good to remove it from the documentation?
Since this is about the docs, and not eslint itself, I haven't filled out the issue template. Sorry if that was wrong.
=> Docs: Removed non-existing resource

docs/user-guide/migrating-to-3.0.0.md
ESLint 3.0.0 migration guide, in section "Requiring Configuration to Run", mentions a `useSpecificConfig` option which is not part of the public API. The correct option is `configFile` (already mentioned).
I removed the incorrect text. I also decided to augment the remaining text with info on how to pass in configuration files (or equivalent) via CLIEngine as well as CLI.
Let me know if the extra text is too much.
NOTE: There is also an issue where `baseConfig` is not sufficient to suppress the No Config error message. This pull request intentionally does *not* address that problem. When I fix that issue (in a separate pull request), I …
=> Fix: Remove  reference from 3.0.0 migration guide (refs #6605)

docs/rules/key-spacing.md, lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
This configuration allows specifying how spacing should work when aligning values via a new `alignment` property.
Example Configuration using the new `alignment` property:
```json
"key-spacing": [2, {
"singleLine": {
"beforeColon": false,
"afterColon": true
},
"multiLine": {
"beforeColon": false,
"afterColon": true,
"align": "colon"
},
"align": {
"beforeColon": true,
"afterColon": true
}
}]
```
The following alignment would throw no errors: 
```js
var obj = {
_origin  : 0,
_x       : 1,
callback : function(cb) {
cb();
},
a  : 1,
bc : 2
d  : function() {
//...
},
o: {
internal : true,
int      : 1
}
};
```
Tests were added showing that it should work with both `align: colon` and `align: value` .
------------------------------------------------------------
This allows eslint users (like …
=> New: Adding new key-space config (fixes #5613)

conf/eslint.json, docs/rules/README.md, docs/rules/multiline-ternary.md, lib/rules/multiline-ternary.js, tests/lib/rules/multiline-ternary.js
Wasn't sure if I should use Node 4-compatible ES6 features as I wrote this or not, but it's a simple rule and will be easy to convert later on as part of [this issue](https://github.com/eslint/eslint/issues/6407) if we want to
=> New: multiline-ternary rule (fixes #6066)

docs/user-guide/migrating-to-3.0.0.md, lib/config.js, tests/lib/config.js
When using CLIEngine, specifying baseConfig was not enough to prevent a No Config Found exception from being thrown. This change will ensure that no exception is thrown if baseConfig is provided to CLIEngine.
Check if baseConfig is present in lib/config.js before throwing an exception, plus test, plus change to migration guide.
Not 100% sure if baseConfig should be checked for at least one key, like "rules" is. Assumption is that baseConfig is null/undefined by default, and so an empty object still represents a conscious user decision to provide a config (even if empty). If this is a bad assumption, let me know.
=> Fix: Do not throw exception if baseConfig is provided (fixes #6605)

lib/testers/rule-tester.js, tests/lib/testers/rule-tester.js
Fixes https://github.com/eslint/eslint/issues/6532
=> Fix: Use default assertion messages for rule tester messages

lib/cli-engine.js, tests/lib/cli-engine.js
#6611
Previously, `executeOnText()` would lint an ignored file if `warnIgnored` was `false`. I changed it so that it always ignores files that should be ignored and only outputs a warning when `warnIgnored` is `true`.
=> Fix: Warning behavior for executeOnText (fixes #6611)

docs/rules/max-len.md
#6637
Replace "code points" by "code units" in the rule explanation.
I guess not.
=> Docs: Correct a term in max-len.md (refs #6637)

docs/developer-guide/nodejs-api.md, docs/developer-guide/working-with-rules.md, lib/eslint.js, lib/testers/rule-tester.js, tests/fixtures/testers/rule-tester/no-var.js, tests/lib/eslint.js, tests/lib/testers/rule-tester.js
This PR adds the capability to include range information into the lint result.
This is `(refs #3307)` since I will tweak the range of core rules later.
This PR has 3 changes.
- Lint Result
- RuleContext#report()
- Rule Tester
This PR will add `endLine` and `endColumn` property to the lint result.
- `endColumn` - the end column of the range on which the error occurred (this property is omitted if it's not range).
- `endLine` - the end line of the range on which the error occurred (this property is omitted if it's not range).
This PR will update `RuleContext#report()`. The `loc` property of a report item comes to allow a range object such as `{start: {line: 1, column: 1}, end: {line: 1, column: 4}}`. This form is same as `ASTNode#loc` and `Token#loc`. For example.
```js
return { …
```
=> New: `endLine` and `endColumn` of the lint result. (refs #3307)

lib/config/config-initializer.js, tests/lib/config/config-initializer.js
#6656 
`eslint-config-standard` peer depends on `eslint-plugin-promise`, so
let's install that for users.
Nothing. Just so you know, you guys are awesome 👍
=> Fix: Install required eslint plugin for "standard" guide (fixes #6656)

docs/rules/prefer-template.md
An example in prefer-template was marked as correct when it's indeed is incorrect.
Changed the word.
Nope.
=> Docs: fix incorrect example being mark as correct

.gitignore, Makefile.js, lib/internal-rules/internal-no-invalid-meta.js, lib/rules/.eslintrc.yml, lib/rules/no-prototype-builtins.js, lib/rules/no-unsafe-finally.js, lib/rules/no-useless-computed-key.js, tests/lib/internal-rules/internal-no-valid-meta.js
Add a custom rule to verify that all core rules have the correct `meta` property format.
As discussed in #6383 this is just an internal custom rule for now and not a plugin.
I modified the Makefile's lint task so it find our "internal rules" directory. Feedback welcome on a better folder name.
=> Chore: add internal rule that validates meta property (fixes #6383)

docs/user-guide/integrations.md
Documentation update.
Added another integration link.
--
No problem if you don't accept changes of this nature; I noticed the existing linked pre-commit hook linted the on-disk contents of a staged file rather than just the staged changes. My script only lints the staged changes.
=> Docs: Add another pre-commit hook to integrations

docs/developer-guide/working-with-rules.md, docs/rules/newline-after-var.md, docs/rules/newline-before-return.md, docs/rules/no-labels.md, docs/rules/no-magic-numbers.md, docs/rules/no-undefined.md, docs/rules/space-unary-ops.md
docs fixed
fix typos,wrong path,backticks. 
for example: in the rule [no-undefined](http://eslint.org/docs/rules/no-undefined)
no
=> Docs: fix typos,wrong path,backticks

lib/eslint.js
Performance improvement
Combining two subsequent RegEx `replace`s with one `replace`.
Yes, the RegEx.
=> chore: combine multiple RegEx replaces with one

lib/ast-utils.js, lib/rules/no-empty.js, lib/rules/no-labels.js, lib/rules/no-unmodified-loop-condition.js, lib/rules/no-unused-vars.js, lib/rules/quotes.js, tests/lib/ast-utils.js, tests/lib/rules/no-unused-vars.js
Fixes #6646.
`no-unused-vars` comes to mark (as used) self-modification inside of a loop because the reference inside of a loop can be used in the next iteration.
=> Fix: `no-unused-vars` false positive in loop (fixes #6646)

docs/rules/README.md, docs/rules/no-var.md, lib/rules/no-var.js, tests/lib/rules/no-var.js
=> Update: make `no-var` fixable (fixes #6639)

bin/eslint.js
#6677 
I removed the exitCode variable and made each block set process.exitCode directly.
Confirm the exitCode is set correctly by running
echo var a | eslint --stdin --rule no-var:error --no-eslintrc --no-ignore && echo good!
<codegood</code> should **not** get echoed after this patch is applied.
Previously exitCode was set at the end of bin/eslint.js but the callback
executed for --stdin was asynchronous.
The asynchronous callback was setting exitCode after process.exitCode
had already been assigned.
This removes the exitCode variable and just gets each block to set
process.exitCode directly.
=> Fix incorrect exitCode when eslint is called with --stdin

lib/formatters/checkstyle.js, lib/formatters/jslint-xml.js, lib/formatters/junit.js, lib/util/xml-escape.js, tests/lib/formatters/checkstyle.js, tests/lib/formatters/jslint-xml.js, tests/lib/formatters/junit.js
#6673 
Fix XML escape with ASCII control characters
When generating XML report with control characters (like "\b" or "\n", they
are sometimes used in JavaScript object keys and will cause messages.),
some XML parser like SAX will crash.
Escape these characters will avoid crashing.
=> Fix: Escape control characters in XML.

lib/rules/multiline-ternary.js
3rd time's a charm!
I forgot to remove the fixable key from multiline-ternary's metadata when we decided to not autofix for the rule. This should be removed. Sorry for the oversight!
Remove the key
N/A
=> Chore: Remove fixable key from multiline-ternary metadata (fixes #6683)

lib/rules/spaced-comment.js, tests/lib/rules/spaced-comment.js
- The issue is that the `balanced` option in the `spaced-comment` rule is incorrectly being applied to line comments instead of only block comments
- Fixes #6689
- Two small changes that cause only block comments to report `balanced` errors
- Two tests that fail prior to changes and pass afterward
My stunning good looks
=> Fix: `balanced` false positive in `spaced-comment` (fixes #6689)

docs/rules/func-names.md, lib/rules/func-names.js, tests/lib/rules/func-names.js
#6616 `func-names` `never` option prevented having recursive functions.
Skipped recursing functions.
`isFunctionName` is duplicated in a few other places. Should we move to a utils file? Where?
=> Fix: Allow named recursive functions (fixes #6616)

conf/eslint-all.js, tests/conf/eslint-all.js
#6687 
Filter files by `.js` extension
No.
This replaces #6685 since the fix wasn't correct, and we might want to include this in a patch release tomorrow.
=> Fix: `eslint:all` causes regression in 3.1.0 (fixes #6687)

docs/rules/no-underscore-dangle.md, lib/rules/no-underscore-dangle.js, tests/lib/rules/no-underscore-dangle.js
Previous PR got confused with a merge and so I recreated it here. See #6355 
Update: Same as the "allowAfterThis" option, but for the ES2015 'super' keyword. fixes #6355
=> Update: Added 'allowSuper' option to no-underscore-dangle rule (fixes #6355)

docs/rules/indent.md, lib/rules/indent.js, tests/fixtures/rules/indent/indent-invalid-fixture-1.js, tests/fixtures/rules/indent/indent-valid-fixture-1.js, tests/lib/rules/indent.js
The end user can choose whether and how much to indent.
```js
foo()
.bar
.baz()
```
vs.
```js
foo()
.bar
.baz()
```
and so forth...
=> Update: Check indentation for multi-line chained properties (refs #1801)

docs/rules/valid-jsdoc.md
#5231
Added a note explaining that Google Closure-style type hints don't work as expected with `valid-jsdoc`.
Verify that the description is clear.
=> Docs: Clarify Closure type hint expectation (fixes #5231)

docs/developer-guide/working-with-rules.md
#4810, #6709
Added descriptions for `parser`, `settings`, and `globals` to test descriptions. Also added mention of using `line` and `column` for invalid tests.
=> Docs: describe all RuleTester options (fixes #4810)

lib/rules/space-infix-ops.js, tests/fixtures/parsers/flow-stub-parser.js, tests/lib/rules/space-infix-ops.js
#5211 (continues work of #6519)
Created a custom stub parser to test that type annotations will no longer trigger `space-infix-ops`. 
=> Ensure that space-infix-ops doesn't fail for Flow type annotations

lib/rules/no-use-before-define.js, tests/lib/rules/no-use-before-define.js
Fixes #6699.
This PR makes the rule handling `ForInStatement.right` and `ForOfStatement.right` as the initializer of variables.
=> Fix: `no-use-before-define` false negative on for-in/of (fixes #6699)

lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-newline.js
Typo in the error report messages of `object-curly-newline` (#6725).
Fixed the typo and adjusted the tests.
Should we also remove the "this" in the sentence? i.e.:
`Unexpected line break after this opening brace.`
vs.
`Unexpected line break after opening brace.`
=> Fix: Correct grammar in object-curly-newline reports (fixes #6725)

lib/rules/no-unreachable.js, tests/lib/rules/no-unreachable.js
Fixes #6583.
This PR makes `no-unreachable` rule merging the warnings of consecutive unreachable statements.
I used ES Classes and Template Literals in this PR.
=> Update: merge warnings of consecutive unreachable nodes (fixes #6583)

docs/user-guide/command-line-interface.md
#4943
Added a warning that using `--cache` and then not using it will result in the cache file being deleted.
Make sure the description is accurate.
=> Docs: Clarify cache file deletion (fixes #4943)

lib/rules/no-unused-vars.js, tests/lib/cli-engine.js, tests/lib/rules/no-unused-vars.js, tests/lib/util/source-code.js
Issue #6738
I added a period to the end of the message for `no-unused-vars`.
The other rules in ESLint seem to end their messages with a period, but `no-unused-vars` doesn't, so this PR attempts to change that.
=> Include period at end of no-unused-vars message

.travis.yml
Reverts eslint/eslint#6744
This was merged a bit too hastily. We can't drop support for Node 5 without a major release.
=> Revert "Build: Remove support for Node v5 (fixes #6743)"

docs/rules/func-names.md
*This is a docs PR, so no issue filed.* The `func-names` examples were missing the `"always"` and `"never"` mode options from the config comments in their examples.
I added the `"always"` and `"never"` mode options to the config comments in the examples.
When there is a default option (in this case `"always"`), do we want to specify it explicitly in the examples (`/*eslint func-names: ["error", "always"]*/`) or leave the default implicit (`/*eslint func-names: "error"*/`)? I followed the [comma-style docs](http://eslint.org/docs/rules/comma-style) here and made the `"always"` examples explicit.
=> Docs: Add options to func-names config comments

docs/user-guide/configuring.md
Doc-only pull request, no accepted issue
Other block comments in this file follow the pattern of a space after the opening `/*` and before the closing `*/`; this one was spaced inconsistently so I modified it to match the spacing shown on the others.
Nope, should be a quick one.
=> Fix inconsistent spacing inside block comment

docs/user-guide/configuring.md
#6742 - The issue was initially closed as working as designed, then reopened as a documentation bug because we didn't include anything about disabling plugin rules in the "Disabling Rules with Inline Comments" section of the configuring guide.
I added an example showing how to disable a plugin rule with an inline comment.
Is the example too specific? Elsewhere we just use `plugin1/rule1` as the example.
=> Docs: Add plugin example to disabling with comments guide (fixes #6742)

tests/lib/rules/no-control-regex.js
#6438 
toString prints out different outputs for /\x01/ and "/\x01/". Because
of that behavior, no-control-regex rule was broken before(fixed on 141b778).
During the fix for #5737 I added a test to cover the case I wrote for fix. Which
was also passing when the fix was not there. The test was on a string
literal unfortunately which was not covering the test case where regex
is written on a literal (like /\x01/). Changed the tests to make sure it
covers the literal regex's as expected.
=> Chore: Updated no-control-regex tests to cover all cases (fixes #6438)

conf/eslint.json, docs/rules/no-tabs.md, lib/rules/no-tabs.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/no-tabs.js, tests/lib/rules/no-underscore-dangle.js
New rule named `no-tabs`
created a new rule.
nothing specific
Need suggestions on:
1. Error message
2. Should we activate this rule for eslint project
=> New: `no-tabs` rule (fixes #6079)

README.md
Since JSCS has reached end of life and JSCS recommends people with issues to use ESLint, we should do the same here.
=> Docs: Update JSCS status in README

Makefile.js
#6791
https://github.com/eslint/eslint/pull/6658 mistakenly removed a line that output the frontmatter into the Jekyll pages which resulted in 404s on eslint.org. This PR simply adds that line back in.
=> Build: Fix site generation (fixes #6791)

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
https://github.com/eslint/eslint/issues/6797
Turn `MemberExpression` option of the `indent` rule to be off by default.
The `MemberExpression` option should be opt-in as it is a breaking
change.
=> Fix: Make MemberExpression option opt-in (fixes #6797)

README.md
https://github.com/eslint/eslint/issues/6795#issuecomment-236325346
> I don't think anyone is suggesting the default be 0 or 1 just that any default was set. But according to the policy that will happen. I think we just need to signal that if you don't want a "breaking change / breaking lint build" (in terms of other projects) you should be using ~ in package.json for ESLint since it can be surprising.
> @hzoo that's a good point. Want to put together a PR for the readme with that suggestion?
A docs change to the readme to suggest using ~ so users don't get unexpected changes.
--
Wording can be changed, maybe mention what I said about it being surprising otherwise.
aside: another thing I …
=> Docs: clarify minor releases and suggest using `~ to version

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
#6795 (continues work from #6796)
Just rebased.
Nope. #6796 was already approved, this just eliminates the merge conflicts.
=> Fix: ignore MemberExpression in VariableDeclarators (fixes #6795)

Makefile.js, conf/category-list.json, conf/eslint.json, docs/rules/no-extend-native.md, docs/rules/no-global-assign.md, docs/user-guide/configuring.md, lib/rules/no-global-assign.js, packages/eslint-config-eslint/default.yml, tests/lib/cli.js, tests/lib/rules/no-global-assign.js
#6586 
Duplicate and rename `no-native-reassign` to `no-global-assign` and mark the former as deprecated.
Let me know if the deprecation messages are enough and if the commit message and tag are correct for this kind on change.
=> New: `no-global-assign` rule (fixes #6586)

conf/eslint-all.js
Fixes #6734.
Also, I changed the way which enumerates core rules to a use of existing `loadRules` function.
=> Update: make `eslint:all` excluding deprecated rules (fixes #6734)

docs/rules/camelcase.md, lib/rules/camelcase.js, tests/lib/rules/camelcase.js
Fixes #6755 
Calmecase rule now doesn't report an error if camelcased identifier is imported with a camecased alias. Otherwhise it reports an error as expected.
=> Fix: camelcase rule fix for import declarations (fixes #6755)

docs/user-guide/getting-started.md
Referencing the discussion at https://github.com/eslint/eslint/issues/6732
Updated the Getting Started documentation with the changes made to the Readme in https://github.com/eslint/eslint/commit/66de9d859d65f64305890c108d7a1704d8dc5e9a
=> Docs: Update Getting Started w/ Readme installation instructions

conf/eslint.json, docs/rules/no-negated-in-lhs.md, docs/rules/no-unsafe-negation.md, lib/rules/no-negated-in-lhs.js, lib/rules/no-unsafe-negation.js, tests/lib/rules/no-negated-in-lhs.js, tests/lib/rules/no-unsafe-negation.js
Fixes #2716.
This PR adds `no-unsafe-negation` rule, and deprecates `no-negated-in-lhs` rule.
`no-unsafe-negation` rule is:
- It reports `!` expression in the left operand of relational expressions (`in` or `instanceof`).
- It's fixable. The fixing would enclose the relational expression except `!`. (`!a in b` → `!(a in b)`)
This PR should follow #6746 for the deprecation way.
=> New: `no-unsafe-negation` rule (fixes #2716)

docs/rules/no-new-symbol.md
It refers to [a comment in #6825](https://github.com/eslint/eslint/pull/6825#discussion_r73200235)
I removed "constructor" word from the rule overview.
n/a
=> Docs: Remove incorrect "constructor" statemant from `no-new-symbol` docs

lib/cli-engine.js, lib/config/autoconfig.js, lib/config/config-initializer.js, lib/config/config-ops.js, lib/eslint.js, lib/ignored-paths.js, lib/rules/indent.js, lib/rules/lines-around-comment.js, lib/rules/new-cap.js, lib/rules/operator-linebreak.js, lib/rules/require-jsdoc.js, lib/rules/strict.js, lib/util/module-resolver.js, lib/util/source-code-util.js, lib/util/source-code.js, tests/lib/config/autoconfig.js, tests/lib/config/config-ops.js
Use native function rather than a polyfill from `lodash`. This way we are more native bound than library bound :smile: 
Replaced `lodash.assign` with native `Object.assign`. As a result of this i was able to get rid of `lodash` in many modules.
nothing specific
=> Chore: use native `Object.assign` (refs #6407)

docs/rules/arrow-parens.md, lib/rules/arrow-parens.js, tests/lib/rules/arrow-parens.js
The when-brace option allows to require parens for arrow functions whose body is
wrapped into curly braces like the following:
```js
(a) => {}
```
Otherwise, its behavior remains identical then with the as-needed option.
=> Add a 'requireForBlockBody' modifier to the 'arrow-parens' rule (fixes #6557)

docs/rules/no-self-assign.md, lib/ast-utils.js, lib/rules/array-callback-return.js, lib/rules/no-alert.js, lib/rules/no-extra-bind.js, lib/rules/no-self-assign.js, tests/lib/ast-utils.js, tests/lib/rules/no-self-assign.js
Fixes #6718.
This PR fixes `no-self-assign` rule to warn properties.
Also, there is a few refactoring (those commits are separated.). I added a function to get the property name of a MemberExpression node (e.g. `a.b` and `a["b"]`) into `ast-utils.js` because this logic is used in multiple places.
=> 	Update: add `props` option to `no-self-assign` rule (fixes #6718)

docs/rules/no-invalid-this.md, lib/ast-utils.js, tests/lib/rules/no-invalid-this.js
Fixes #6824.
This PR fixes the false positive of `no-invalid-this` rule. (reduces warnings)
```js
var Foo = function() { this; }
```
If an anonymous function is assigned to a variable that the name starts with uppercase, the rule comes to handle the function as a constructor (i.e. `this` in the function is valid.).
This is similar to an existing behavior; a function that the name starts with uppercase is handled as a constructor.
=> Fix: `no-invalid-this` false positive (fixes #6824)

lib/config/config-initializer.js, tests/lib/config/config-initializer.js
#6843 Updates the peerDependencies of eslint-config-airbnb for the `--init` option.
Updated the array of plugins to include the new peerDependencies.
Nothing in particular. As mentioned in https://github.com/eslint/eslint/issues/6843#issuecomment-237647498, I kept this short and to the point.
I propose we discuss having an automated way of keeping these in sync on a separate issue, if need be.
=> Fix: update peerDependencies of airbnb option for `--init` (fixes #6843)

docs/rules/object-shorthand.md, lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
Please review my implementation for https://github.com/eslint/eslint/issues/5438.
=> New: Add consistent and ..-as-needed to object-shorthand (fixes #5438)

docs/rules/no-constant-condition.md, lib/rules/no-constant-condition.js, tests/lib/rules/no-constant-condition.js
#5726 Add check for the void operator to the `no-constant-condition` rule
I added the check for the rule, updated the rule description, and added a bunch of tests for all the cases I could think of.
Are there any more test cases I could add?
=> Update: validate void operator in no-constant-condition (fixes #5726)

lib/rules/newline-after-var.js, tests/lib/rules/newline-after-var.js
Fixes #6834.
This PR fixes false positive of `newline-after-var` rule for semicolon-less style.
var foo = 1
;(a || b).doSomething()
If the last token of variable declaration is semicolon and the semicolon is on a different line from the previous token of the semicolon, the rule comes to compare line between the previous token and the next statement.
=> Fix: `newline-after-var` false positive (fixes #6834)

lib/internal-rules/internal-no-invalid-meta.js, tests/lib/internal-rules/internal-no-valid-meta.js
#6848: `internal-no-invalid-meta` was throwing an error when it ran on a rule in the old format.
I changed `internal-no-invalid-meta` so it now reports a linting error when the rule is in the old format, instead of throwing an unrecognizable error.
=> Fix: don't throw if rule is in old format (fixes #6848)

conf/eslint.json, docs/rules/func-call-spacing.md, docs/rules/keyword-spacing.md, docs/rules/no-spaced-func.md, docs/rules/no-unexpected-multiline.md, lib/rules/func-call-spacing.js, lib/rules/no-spaced-func.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/func-call-spacing.js, tests/lib/rules/keyword-spacing.js, tests/lib/rules/no-spaced-func.js
#6080 - support [requireSpacesInCallExpression](http://jscs.info/rule/requireSpacesInCallExpression) and [disallowSpacesInCallExpression](http://jscs.info/rule/disallowSpacesInCallExpression) by replacing the `no-spaced-func` rule with a new `func-call-spacing` rule having `"never"` (default) or `"always"` modes.
Copied the `no-spaced-func` rule, named the new rule `func-call-spacing`, and added support for `"never"` and `"always"` options.
1. I haven't touched `no-spaced-func`. What's the proper way to indicate that it's deprecated in favor of `func-call-spacing`?
2. For compatibility with JSCS `requireSpacesInCallExpression`, `"always"` …
=> New: func-call-spacing rule (fixes #6080)

Makefile.js
Build failure on windows for lint runs.
Rather than getting all the files and then sending them individually to eslint. we will now just send the glob pattern and let eslint figure out the files.
I think the cause of the issue was that we were exceeding the limit on how many things can be passed as arguments from cmd line.
Nothing specific
=> Chore: Fix glob for core js files for lint (fixes #6870)

lib/rules/max-lines.js, tests/lib/rules/max-lines.js
It makes `max-lines` report the actual number of lines along with the limit.
I altered the report message and updated `max-lines` test suite.
Report output. May it be better?
Instead of reporting only that `max` value has been exceeded
it now also reports how many lines there is in the file.
=> Update: make `max-lines` report the actual number of lines (fixes #6766)

lib/rules/no-control-regex.js, tests/lib/rules/no-control-regex.js
Fixes #6293 - this makes the `no-control-regex` error message more useful by including the control characters that were found.
I changed the "has control characters" boolean to a "get control characters" list, and converted that list of characters into a display string (ie, `"\x00"` to `"\\x00"`.
Nothing I can think of.
=> Update: improve error message in `no-control-regex`

lib/rules/no-dupe-keys.js, tests/lib/rules/no-dupe-keys.js
Fixes #6801.
This PR fixes a false negative between a normal property and a getter/setter.
In addition, I upgrade code by ES2015.
=> Fix: `no-dupe-keys` false negative (fixes #6801)

.eslintrc.yml, Makefile.js, lib/cli.js, lib/config/config-file.js, lib/ignored-paths.js, lib/rules/indent.js, lib/util/npm-util.js, package.json, tests/lib/cli-engine.js, tests/lib/util/npm-util.js
Refs #6407.
This PR enables [eslint-plugin-node] to lint our codebase.
plugins:
- node
extends:
- "plugin:node/recommended"
This would help us:
- To early warn a use of unsupported ecma features in Node 4.
- To warn a use of deprecated API.
- To early warn invalid paths in `require(...)`.
- To early warn paths which are not included in dependencies in `require(...)`.
Also, this PR removes some uses of deprecated API.
- `util.isArray`
- `fs.existsSync`
[eslint-plugin-node]: https://www.npmjs.com/package/eslint-plugin-node
=> Chore: use eslint-plugin-node (refs #6407)

conf/eslint.json, docs/rules/sort-imports.md, docs/rules/sort-keys.md, docs/rules/sort-vars.md, lib/rules/sort-keys.js, package.json, tests/lib/rules/sort-keys.js
Fixes #6076.
This PR adds `sort-keys` rule.
- This PR is sharing 1st commit d02e595aefae42c96495fc479357554610e5003b with #6721. This commit adds `astUtils.getStaticPropertyName` function.
- This `sort-keys` implement sorts simple computed properties (e.g., `let obj = {a: 1, [b]: 2}`) similar to JSCS. This would help a use of symbols.
- This `sort-keys` implement ignores non-simple computed properties (e.g., `let obj = {a: 1, [b + c]: 2}`).
- I ported most tests from JSCS.
- I added a dependency, `natural-compare`, JSCS are using.
=> New: `sort-keys` rule (fixes #6076)

lib/rules/no-dupe-keys.js, tests/lib/rules/no-dupe-keys.js
Fixes #6886.
`Property` nodes exist on `ObjectPattern` nodes. It needs to avoid those.
=> Fix: `no-dupe-keys` type errors (fixes #6886)

docs/rules/new-cap.md, lib/rules/new-cap.js, tests/lib/rules/new-cap.js
ref: https://github.com/eslint/eslint/issues/5187
adds regex options for exceptions to newIsCap and capIsNew
=> Update: Add regex support for exceptions (fixes #5187)

lib/rules/prefer-rest-params.js, tests/lib/rules/prefer-rest-params.js
Fixes #5990.
This PR makes `prefer-rest-params` rule relaxing.
New behavior ignores `arguments` which is accessing non-computed property (e.g. `arguments.length`).
- Ignores:
- `arguments.length`
- `arguments.callee`
- Still errors:
- `arguments`
- `foo(arguments)`
- `arguments[0]`
- `arguments[i]`
- `arguments[Symbol.iterator]`
=> Update: `prefer-rest-params` relax for member accesses (fixes #5990)

Makefile.js, package.json
#6884 
* Added `ci-release` script
* ~~Added `gh-release` script~~
Ensure changes in `Makefile.js` make sense.
=> Build: Add CI release scripts (fxies #6884)

docs/rules/object-shorthand.md
Minor documentation issue. The option values for the `object-shorthand` rule were listed twice, but when the new `consistent` and `consistent-as-needed` values were added only the second list was updated.
Rather than update the first list with the new option values, I just got rid of it. It seemed unnecessary to have two lists given that the first list was right above the second list.
Global warming
=> Docs: Update options in `object-shorthand`

docs/rules/no-template-curly-in-string.md
**What issue does this pull request address?** N/A (docs update)
This clarifies the documentation for the `no-template-curly-in-string` rule. Escaping the quotes in the description makes it seem like the rule might be looking for actual escaped quotes in the string, when it is simply looking for quotes surrounding the string.
**Is there anything you'd like reviewers to focus on?** No
=> Docs: clarify rule details for no-template-curly-in-string

Makefile.js
eslint/eslint.github.io#268 and #6888 : optimize rule doc page title so the name of the rule comes first.
E.g. for the `template-curly-spacing` rule:
From:
`Rule template-curly-spacing - ESLint - Pluggable JavaScript linter`
To:
`template-curly-spacing - Rules - ESLint - Pluggable JavaScript linter`
Modified the `gensite` task so that the `title` in the frontmatter for each rule doc page is using the new format described above.
=> Build: optimize rule page title for small browser tabs (fixes #6888)

lib/rules/no-tabs.js, lib/rules/no-template-curly-in-string.js
Scrolling through http://eslint.org/docs/rules, I found two descriptions that began with uppercase letters, while all the rest were lowercase.
I changed the two inconsistent descriptions to begin with lowercase letters.
For the curious, here's how I ran a quick check to be sure I didn't miss any:
```js
Array.from(document.querySelectorAll('tr td:last-child p'))
.map(p => p.innerText)
.filter(description =>
description[0].toLowerCase() !== description[0]
)
```
=> Docs: Change rule descriptions for consistent casing

lib/eslint.js, tests/lib/eslint.js
Thoughts on this approach? The way `verify()` works doesn't seem to make it easy to test this particular change. Is there something else I could spy on?
=> Update: add support for ecmaVersion 20xx (fixes #6750)

conf/eslint.json, docs/rules/class-methods-use-this.md, lib/rules/class-methods-use-this.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/class-methods-use-this.js
Add  `class-methods-use-this` rule.
Created a brand new rule
* I have activated the rule for `eslint` repo since we have started using class syntax now.
Credit to Patrick Williams (@pwmckenna) who created the rule but was not able to finish the work on it. (#5152)
=> New: `class-methods-use-this` rule (fixes #5139)

README.md
Updated per TSC meeting 2016-08-18.
=> Docs: Update semantic versioning policy

lib/rules/no-trailing-spaces.js, tests/lib/rules/no-trailing-spaces.js
Fixes #6933.
If `skipBlankLines` option is enabled, counting total length for blank lines was lacking.
=> Fix: `no-trailing-spaces` wrong fixing (fixes #6933)

docs/rules/valid-typeof.md, lib/rules/valid-typeof.js, tests/lib/rules/valid-typeof.js
#6698
This PR adds a `requireStringLiterals` option to `valid-typeof`, to enforce comparisons to string literals.
**Is there anything you'd like reviewers to focus on?** Not really
I noticed that #6698 hasn't been marked as "accepted" yet, but it seemed like there was enough support that it was worth making this PR. I realize that I'll probably have to wait for that issue to get accepted before this PR gets merged, though.
=> Update: `requireStringLiterals` option for `valid-typeof` (fixes #6698)

lib/ignored-paths.js, lib/util/glob-util.js, lib/util/glob.js, package.json, tests/lib/ignored-paths.js
As #6710 discussed, I create a subclass of `glob.GlobSync` to skip certain glob process according to .gitignore rules.
- inherits `glob.GlobSync` and overrides `_readdir`, special thanks to the good idea of @mysticatea. But there are several detail things we should aware of, see the inline comments of the commit.
- change `ignoredPaths.getIgnoredFoldersGlobPatterns()` -> `ignoredPaths.getIgnoredFoldersGlobChecker()`, and now it will return a function.
Do I need to create a specific test cases file for `lib/glob.js`? Or just testing it with `glob-util.js` is ok? I did create a test file, because I thought there was much duplication with …
=> Fix: Improves perf of globbing by inheriting glob.GlobSync (fixes #6710)

lib/rules/no-cond-assign.js, tests/lib/rules/no-cond-assign.js
#6908 
Stops checking to see if an assignment is within a condition if the assignment is wrapped in a call expression, making the behavior consistent between "except-parens" and "always"
I noticed that the behavior depends on whether the configuration is set to "always" or "except-parens". If configured to "except-parens" the behavior was as expected in the bug report. "always" is more strict.
This might be a breaking change. I actually moved one of the unit tests from invalid to valid. But we should probably discuss that in the issue.
=> Fix: no-cond-assign within a function expression (fixes #6908)

conf/eslint.json, docs/rules/symbol-description.md, lib/rules/symbol-description.js, tests/lib/rules/symbol-description.js
#6778
I implemented `symbol-description` rule
- whether rule is supposed to be recommended or not
- in which group (Best practices or ES6) should this rule be placed in
TODO:
=> New: `symbol-description` rule (fixes #6778)

lib/config/plugins.js, lib/rules.js, messages/plugin-missing.txt, tests/lib/config/plugins.js, tests/lib/rules.js
Refs #6362.
This PR just adds the support of `@scope/plugin/rule`-style rule specifiers.
=> Fix: enable `@scope/plugin/ruleId`-style specifier (refs #6362)

package.json, tests/fixtures/cache/src/file-to-delete.js, tests/fixtures/cache/src/test-file2.js, tests/lib/cli-engine.js
It allows cache file to keep non used files in the cache between executions of eslint, also files that don't exist anymore are removed from the cache both when loaded and when saved.
- updated file-entry-cache to 2.0.0
- added unit tests to cover the expected functionality
- correctness of the tests
- Also would be nice to review also this https://github.com/royriojas/file-entry-cache/commit/408374d0398533db237cde3fef1ad509ed2dab39 where the actual removal of non found files happen.
cc. @IanVS
=> New: do not remove non visited files from cache. (Fixes #6780)

lib/rules/object-curly-spacing.js, tests/fixtures/parsers/object-curly-spacing/flow-stub-parser-never-invalid.js, tests/fixtures/parsers/object-curly-spacing/flow-stub-parser-never-valid.js, tests/lib/rules/object-curly-spacing.js
Fixes #6940.
This PR changes the way to find '}' token.
I followed #6723 about the way of tests.
=> Fix: `object-curly-spacing` for type annotations (fixes #6940)

docs/rules/object-curly-spacing.md, docs/rules/one-var-declaration-per-line.md, docs/rules/one-var.md, docs/rules/operator-assignment.md, docs/rules/operator-linebreak.md, docs/rules/padded-blocks.md, docs/rules/quote-props.md, docs/rules/quotes.md, docs/rules/require-jsdoc.md, docs/rules/semi.md
Documentation update.
Documentation update.
* `one-var`
* Combined the object properties for each object option. Willing to reconsider if desired.
* Added language for using one of three different options
* `quote-props`
* Do we have special language for object options that only apply based on choices of previous options? My only concern with this rule, I believe.
@pedrottimark Got another batch for ya.
=> Docs: Distinguish examples in rules under Stylistic Issues part 7

lib/rules/indent.js, tests/lib/rules/indent.js
#6956
Previously, only the first `else` statement in a chain would be checked for correct indentation. This PR fixes the issue by recursively checking nodes in `else if` chains to ensure that all nodes have the right indentation.
=> Fix: false negative of `indent` with `else if` statements (fixes #6956)

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Fixes #5837.
This PR makes `prefer-const` warning used variables by `context.markVariableAsUsed(name)` API, **on except global scope**.
`/*exported*/` comments also are using `eslintUsed`.
I thought `prefer-const` should not warn `foo` in the following code.
```js
/*exported foo*/
let foo = 1
```
`prefer-const` still ignore used global variables by `context.markVariableAsUsed(name)` API (since `/*exported*/` comment is applied to only global variables).
But this PR will improve the issue.
In most cases, the variables that `react/jsx-use-vars` marks are on Node.js/CommonJS scope or Module scope.
**EDIT:** This needs **minor** bump since this will increase warnings.
=> Fix: `prefer-const` false negative about `eslintUsed` (fixes #5837)

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
#6944 
This adds an autofixer to `no-extra-parens`, allowing it to be fixed automatically with the `--fix` option.
#6944 has not been marked as accepted yet, so this PR shouldn't be merged until it is.
It's probably worth double-checking [this logic](/eslint/eslint/blob/185da9e73f9542e6fe54995e9a10f218724149fa/lib/rules/no-extra-parens.js#L279-L285) to make sure there are no other special cases that need to be addressed.
=> Update: add fixer for no-extra-parens (fixes #6944)

docs/rules/indent.md
Because the indentation is specified to `2`. For beginners, It will be better if set `SwitchCase` to `1`.
=> Docs: Update the example of SwitchCase

docs/rules/no-extra-parens.md
=> Docs: Fix minor typo in no-extra-parens doc

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
fixes https://github.com/eslint/eslint/issues/6691
i didn't add anything to docs because the current docs seem to imply this option already. let me know if that's needed though!
=> Fix: Allow separate mode option for multiline and align (fixes #6691)

conf/eslint.json, docs/rules/line-comment-position.md, lib/rules/line-comment-position.js, tests/lib/rules/line-comment-position.js
#6077 
Created new rule `line-comment-position`
- The regular expression. I modified the original proposal to make some of the patterns only match for exact words, to try to match what JSCS does.
- The documentation. I have been working on and off on this one for a long time, so I may have developed some blindness.
- Should I put the regular expression as is in the docs to indicate the exact default ignore patterns?
=> New: `line-comment-position` rule (fixes #6077)

docs/rules/no-restricted-modules.md
Added a missing word
The missing word
=> Docs: Add missing 'to' in no-restricted-modules

docs/rules/new-parens.md, lib/rules/new-parens.js, tests/lib/rules/new-parens.js
Fixes #6997.
This PR changes the logic of `new-parens`.
Old logic counts parentheses in a `NewExpression` node. Then OK if it's 2 or more.
New logic checks a token (except `)`) preceded by the callee of a `NewExpression`. Then OK if the token is an opening parenthesis and is inside of the `NewExpression` node.
NOTE: this needs minor bump.
=> Fix: `new-parens` false negative (fixes #6997)

lib/eslint.js, tests/fixtures/parsers/stub-parser.js, tests/lib/eslint.js
ref: https://github.com/eslint/eslint/issues/5344
let me know if i need to update anything in the docs!
edit: moved the test into the "custom parser" describe since it was failing in the browser
=> Update: Pass file path to parse function

conf/eslint.json, docs/rules/no-restricted-properties.md, lib/rules/no-restricted-properties.js, tests/lib/rules/no-restricted-properties.js
https://github.com/eslint/eslint/issues/3218
Added a rule to disallow certain method calls on specific objects. For example `describe.only` in mocha.
Nope, should be pretty straight forward.
Extra thanks to @willklein. This is essentially all his code. I just updated it to the new syntax and made it pass the tests.
=> New: no-restricted-properties rule (fixes #3218)

docs/rules/sort-vars.md
Documentation readability
* Made incorrect and correct examples for sort-var clearer
* Simplified description of options, _including clarifying the default behavior_.
No.
=> Docs: Clean up sort-var

lib/eslint.js, tests/lib/eslint.js
Issue #6988.
Tightened up a regular expression to filter out brace characters from rule message parameters, since those are the delimiters used.
Is this approach okay? I could also just have the *first* character not be an open brace, but I don't know if that's just more complexity for not a lot of gain.
=> Fix: Rule message placeholders can be inside braces (fixes #6988)

lib/config/plugins.js, messages/whitespace-found.txt, tests/lib/config/plugins.js
Issue #6854 
Added a check to see if white-space is in the plugin name before requiring plugins and throw an error if white-space is found. Also added test. 
Not exactly sure on the wording of the error messages. Will update if needed.
=> Update: Throw error if whitespace found in plugin name (fixes #6854)

docs/rules/no-magic-numbers.md, lib/rules/no-magic-numbers.js, tests/lib/rules/no-magic-numbers.js
#4616 
This causes `no-magic-numbers` to report cases where variables are reassigned to magic numbers:
```js
var foo;
foo = 1234;
```
Since `no-magic-numbers` had a test ensuring the opposite behavior, this might be considered a breaking change rather than a bugfix.
=> Update: no-magic-numbers false negative on reassigned vars (fixes #4616)

lib/rules/no-regex-spaces.js
Issue #7052
no-regex-spaces now uses internal rule message formatting. (This was previously blocked until #7041 was merged.)
Nah, should be pretty self-explanatory.
=> Chore: no-regex-spaces uses internal rule message format (fixes #7052)

conf/eslint.json, docs/rules/prefer-numeric-literals.md, lib/rules/prefer-numeric-literals.js, tests/lib/rules/prefer-numeric-literals.js
ref: https://github.com/eslint/eslint/issues/6068
=> New: `prefer-numeric-literals` rule (fixes #6068)

docs/rules/new-parens.md, lib/rules/new-parens.js, tests/lib/rules/new-parens.js
#6994
This adds a --fix option for `new-parens`, as described in #6994.
~~#6994 has not been accepted yet (needs one more 👍), so this should not be merged yet.~~ (edit: #6994 is accepted now.)
=> Update: add fixer for new-parens (fixes #6994)

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
#6052
This adds additional options to the `indent` rule, to allow for custom indentation on function parameters and bodies.
There's an edge-case with `{parameters: "first"}` where the first parameter is not on the same line as the function declaration. At the moment, the rule does not check the first parameter in this case, but still ensures that all the other parameters line up with the first parameter:
```js
/*eslint indent: ["error", 2, {"FunctionDeclaration": {"parameters": "first"}}]*/
// valid:
function foo(
bar, baz,
qux) {
qux();
}
// also valid:
function foo(
bar, baz,
qux) {
qux();
}
```
This case was also discussed …
=> Update: add more `indent` options for functions (fixes #6052)

docs/rules/wrap-regex.md, lib/rules/wrap-regex.js, tests/lib/rules/wrap-regex.js
#7013 
This adds a fixer for the `wrap-regex` rule by surrounding regular expressions literals with parentheses, as described in #7013.
Nothing in particular. ~~#7013 has not been accepted yet, so this PR should not be merged yet.~~
=> Update: add fixer for wrap-regex (fixes #7013)

docs/user-guide/configuring.md
None, this is a documentation-only pull request.
Reading the docs, it is not clear why ESLint's parser will stop complaining about ES6 specifics when `es6` env is set and `ecmaVersion: 6` is omitted.
It is actually done [on purpose](https://github.com/eslint/eslint/blob/e1187285f137d685bcfc9e2a771fa059ef9637a9/conf/environments.js#L98-L103), but the documentation didn't mention this at all.
N/A
=> [Docs] Clarify that `es6` env also sets `ecmaVersion` to 6

lib/rules/no-implicit-coercion.js, tests/lib/rules/no-implicit-coercion.js
The rule was checking that the `Literal` is not a number in the case of `+foo` (so it would not warn for `+42`), but was not doing the same for strings.
=> Fix: no-implicit-coercion string concat false positive (fixes #7057)

docs/rules/newline-before-return.md, lib/rules/newline-before-return.js, tests/lib/rules/newline-before-return.js
#5958 Add auto-fixing for "newline-before-return" rule.
Added a fixer for all the cases that can be safely fixed, i.e. when the return statement does not have a comment attached to it.
I did some refactorings so I could re-use the logic that the rule already uses to calculate the number of preceding lines of a given return statement. The fixer uses that same logic to determine if the return statement is safe to fix or not.
I added a couple of questions as comments in the diff. Otherwise, nothing in particular.
=> Update: add fixer for newline-before-return (fixes #5958)

lib/rules/no-console.js, tests/lib/rules/no-console.js
Fixes #7010, semver-patch.
This PR changes the way to find `console` accesses.
The new way uses escope variables.
As a result, `no-console` rule comes to distinguish shadowing correctly.
=> Fix: `no-console` ignores user-defined console (fixes #7010)

docs/rules/dot-notation.md, lib/rules/dot-notation.js, tests/lib/rules/dot-notation.js
#7014 
This adds a fixer for the [`dot-notation`](http://eslint.org/docs/rules/dot-notation) rule, as described in #7014. It does not make any fix if the original code contains comments in the property-brackets, or between the dot and the property name.
```js
foo[/* comment */ "bar"] // not fixed
foo. /* comment */ while // also not fixed
```
#7014 has not been marked as accepted yet, so this PR should not be merged before that happens.
=> Update: add fixer for dot-notation (fixes #7014)

docs/rules/comma-style.md, lib/rules/comma-style.js, tests/lib/rules/comma-style.js
Introduce auto-fix for `comma-style` rule.
Fix the position of comma.
This is just a proof of concept PR. 
**UPDATE:**
Its ready for review and merge.
=> Update: auto-fix for `comma-style`  (fixes #6941)

docs/rules/prefer-arrow-callback.md, lib/rules/prefer-arrow-callback.js, tests/lib/rules/prefer-arrow-callback.js
#7002
This allows errors reported by the `prefer-arrow-callback` rule to be autofixed, matching the behavior described in #7002.
I'm unsure about whether [this check](/not-an-aardvark/eslint/blob/75affc68ea7162a912046ba2580f3e6919b117b7/lib/rules/prefer-arrow-callback.js#L257-L262) is correct. The intention is to detect whether the current parser configuration supports arrow functions, to avoid causing SyntaxErrors if ES6-mode is off. However, there might be a better/more complete way to do this.
~~#7002 has not been marked as accepted, so this PR should not be merged yet.~~ (edit: #7002 is now marked as accepted.)
=> Update: add fixer for prefer-arrow-callback (fixes #7002)

docs/rules/max-len.md, lib/rules/max-len.js, tests/lib/rules/max-len.js
#5805
- added `getAllStrings` and `getAllTemplateLiterals` to source-code
- grouped both by line number in `max-len`, and ignored lines that contained strings/template literals, matching the options
The overall approach.
=> New: `max-len`: `ignoreStrings`+`ignoreTemplateLiterals` (fixes #5805)

lib/util/glob-util.js, tests/fixtures/cli-engine/hidden/.hiddenfolder/double-quotes.js, tests/lib/cli-engine.js, tests/lib/util/glob-util.js
#4828
The main change here is to set an option on node_glob to return dotfiles from glob patterns (anything other than explicitly passed files).   In order for dotfiles to actually be linted, though, a negating ignore pattern like `!.*` will need to be used to override the default ignore behavior.
This turned out to be a bit more involved than just returning hidden files from our glob patterns.  That's because we were _not_ ignoring dotfiles by default in all cases, only when an `options` object was provided to `listFilesToProcess`, which was nearly always.  Except, it turns out, in the test `"should not return hidden files for standard glob patterns"`.  That _was_ okay, because globs would …
=> Fix: Allow linting of .hidden files/folders (fixes #4828)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, docs/developer-guide/contributing/new-rules.md, docs/developer-guide/contributing/pull-requests.md, docs/developer-guide/contributing/reporting-bugs.md, docs/developer-guide/contributing/rule-changes.md, docs/maintainer-guide/pullrequests.md, templates/bug-report.md, templates/pr-create.md.ejs, templates/rule-change-proposal.md, templates/rule-proposal.md, tests/templates/pr-create.md.ejs.js
#7015
1. Updated all the references to requiring an issue for PRs.
1. Updated the PR bot to not check for issues in commit messages.
1. Updated issue templates and created new templates for various things.
What do you think about the various templates? I tried to balance the need for getting important information into the pull request with not overwhelming people.
=> Docs: Update so issues are not required (fixes #7015)

docs/user-guide/integrations.md
Add a link to awesome-eslint in the integrations page. I think they do a good job at curating a bunch of integrations for ESLint, and they seem to have good traction, so I believe it would be helpful to suggest people to take a look in there as well.
I added a new section to the end of the integrations page that suggests awesome-eslint as another source for useful ESLint integrations.
Wording suggestions, I guess.
=> Docs: Add link to awesome-eslint in integrations page

docs/maintainer-guide/issues.md
Thoughts on this approach? Our Issue triaging section is starting to look like a wall of text. I'm hoping that separating out the information and using more bullet points makes the information easier to parse.
=> Docs: Add info about closing accepted issues to docs (fixes #6979)

lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
#7086 
Changed column to be 0-based instead of 1-based
=> Fix: Return correct column number for no-multiple-empty-lines (fixes #7086)

docs/rules/no-floating-decimal.md, lib/rules/no-floating-decimal.js, tests/lib/rules/no-floating-decimal.js
#7070
This adds an autofixer for the [`no-floating-decimal`](http://eslint.org/docs/rules/no-floating-decimal) rule.
Nothing in particular. #7070 has not been marked as accepted yet, so this PR should not be merged before that happens.
=> Update: add fixer for no-floating-decimal (fixes #7070)

lib/rules/arrow-spacing.js, tests/lib/rules/arrow-spacing.js
Fixes #7079.
Original logic does traversing to right from the head of arrow function nodes, so it's going to stop at `=>` token in default parameters.
New logic does traversing to left from the head of arrow function body.
Semver-minor: this fix can increase warnings.
=> Update: fix false negative of `arrow-spacing` (fixes #7079)

docs/rules/line-comment-position.md
```
```
Docs for `line-comment-position` rule states …
=> Doc for `line-comment-position` rule states `above` instead of `beside`

docs/rules/guard-for-in.md
Explains why a naive `foo.hasOwnProperty(key)` call is a bad idea in the `guard-for-in` page. Resolves #7071.
Hopefully prevents future users from being as confused as I was :) (or, maybe worse, ignoring the obscure `{}.hasOwnProperty.call(foo, key)` syntax)
=> Docs: Elaborate on `guard-for-in` best practice (resolves #7071)

docs/rules/valid-typeof.md, lib/rules/valid-typeof.js, tests/lib/rules/valid-typeof.js
#7078
This prevents the `valid-typeof` rule from reporting comparisons between two `typeof` expressions (e.g. `typeof foo === typeof bar`) when the `requireStringLiterals` option is enabled.
This makes the option name `requireStringLiterals` a bit misleading, but it upholds the spirit behind the option (that `typeof` comparisons should be statically verifiable). #7078 also contains some discussion on this.
=> Fix: Don't report comparisons of two typeof expressions (fixes #7078)

Makefile.js
```
```
This removes the check for an issue reference in …
=> Chore: Don't require an issue reference in check-commit npm script

docs/rules/space-before-blocks.md
```
```
This makes phrasing more consistent with other rules, and helps the site publisher set the appropriate icons and background colors for these examples.
=> Docs: Distinguish examples for space-before-blocks

docs/rules/eol-last.md, lib/rules/eol-last.js, tests/lib/rules/eol-last.js
In short, `eol-last`'s behavior could thus far only enforce that files ended with an OS-specific EOL. The rule's negation (i.e. that files should not end with an EOL) wasn't possible.
This PR adds a `"none"` option to `eol-last` which adds a way to check that a file doesn't end with an EOL, which fixes issue #6938. Additionally, there's also a fixer and some tests.
Here's a short overview of changes:
- Replaced ternary check of options with object access
- Initialized `location` with both `column` and `line` directly (note that `line` is now set by `sourceCode.lines.length` instead of performing a `.split("\n")`)
- Divided `checkBadEOF`'s code flow into two paths, where one path treats different operating systems' EOLs just like before, while the other path treats enforcing their absence …
=> Update: Add `always`/`never` option to `eol-last` (fixes #6938)

docs/rules/quotes.md
```
```
- [X ] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull- …
=> Docs: Fixes examples for allowTemplateLiterals

lib/rules/line-comment-position.js, tests/lib/rules/line-comment-position.js
```
```
Re: bug report template: See issue #7100.
Added test case given in #7100, and fixed the typo in the rule. …
=> Fix: line-comment-position "above" string option now works (fixes #7100)

docs/rules/class-methods-use-this.md, lib/rules/class-methods-use-this.js, tests/lib/rules/class-methods-use-this.js
```
```
`class-methods-use-this`
Fewer.
**How will the change be …
=> Update: `class-methods-use-this`: add `exceptions` option (fixes #7085)

packages/eslint-config-eslint/default.yml
```
```
* (n/a) I've included tests for my change
As recommended on Gitter, this enables the `typeof: true` option for `no-undef` in `eslint-config-eslint`. It …
=> Chore: Enable `typeof` check for `no-undef` rule in eslint-config-eslint

lib/rules/indent.js, tests/lib/rules/indent.js
#6731 
Essentially added `LogicalExpressions` to the whitelist of multiline cases for object assignments. 
Yeah, It was mentioned in the issue thread that this rule has issues with multiline statements, this is a very simple fix to the specific scenario in #6731 I think people would agree that this https://github.com/eslint/eslint/blob/f4fcd1e6730b8355fbf071240dfdeb419cc93be2/lib/rules/indent.js#L648 segment could use some love via refactoring
=> Fix: include LogicalExpression in indent length calc (fixes #6731)

docs/rules/no-regex-spaces.md, lib/rules/no-regex-spaces.js, tests/lib/rules/no-regex-spaces.js
=> Update: add fixer for `no-regex-spaces`

lib/rules/indent.js, tests/lib/rules/indent.js
#4274
This updates the `indent` rule to parse both tabs and spaces as indent characters, regardless of which character lines are supposed to have. For example, if a line is supposed to be indented with two spaces, and it starts with two spaces followed by a tab, the line will get reported because the tab isn't supposed to be there. (Previously, the line would not get reported because the tab wasn't considered an indentation character in "spaces mode".)
Since it now has the ability to detect both spaces and tabs, the rule can also give more detailed error messages, e.g. `Expected indentation of 8 spaces but found 4 spaces and 2 tabs.`
This PR also updates the `getNodeIndent` function to only …
=> Update: Make `indent` report lines with mixed spaces/tabs (fixes #4274)

lib/rules/max-len.js, tests/lib/rules/max-len.js
```
```
See https://github.com/eslint/eslint/issues/7125 for template answers …
=> Fix: `max-len`: `ignoreTemplateLiterals`: handle 3+ lines (fixes #7125)

package.json, tests/lib/rules/no-dupe-args.js, tests/lib/rules/no-redeclare.js
This removes tests that were failing due to the update to Espree 3.2.0. (See #7169)
These tests contained code that had a SyntaxError according to the ES spec, but …
=> Upgrade: espree to 3.2.0, remove tests with SyntaxErrors (fixes #7169)

docs/rules/quote-props.md, lib/rules/quote-props.js, tests/lib/rules/quote-props.js
```
```
This adds a fixer for `quote-props`, as described …
=> Update: add fixer for quote-props (fixes #6996)

lib/rules/eol-last.js, tests/lib/cli-engine.js, tests/lib/eslint.js
```
[X] Bug fix
[ ] New rule
[ ] Changes an existing rule
```
* **ESLint Version:** 3.5.0
* **Node Version:** 6.5.0
* **npm Version:** 3.10.7
default
See source code below, it contains the configuration.
Check below.
The following file should report an issue at line 2, column 16.
```js
/* eslint eol-last: [1, "always"] */
var a = "test";
``` …
=> Fix: Report columns for `eol-last` correctly (fixes #7136)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
```
```
See #7124.
- ~~I've updated documentation for my change (if appropriate)~~
This PR solves a problem in combination of `{args: "after-used"}` and …
=> Update: fix `no-unused-vars` false negative (fixes #7124)

lib/rules/quotes.js, tests/lib/rules/quotes.js
```
```
See the template of #7084.
the spec of JSX AST is here: …
=> Update: fix `quotes` rule's false negative (fixes #7084)

docs/rules/no-restricted-properties.md, lib/rules/no-restricted-properties.js, tests/lib/rules/no-restricted-properties.js
```
```
See #7137 for template answers.
This allows the `object` or `properties` option to be omitted for `no-restricted-properties`.
For more information on the …
=> Update: Make `no-restricted-properties` more flexible (fixes #7137)

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
[X] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
`valid-jsdoc` currently throws a `TypeError` when it encounters a `FieldType` that contains a key with a missing value. This is because `type.value` is actually …
=> Fix: valid-jsdoc does not throw on FieldType without value (fixes #7184)

lib/rules/no-restricted-properties.js, tests/lib/rules/no-restricted-properties.js
```
```
See #7147 for the template answers.
This allows `no-restricted-properties` to report errors from destructuring patterns. …
=> Update: Let `no-restricted-properties` check destructuring (fixes #7147)

tests/lib/rules/generator-star-spacing.js
- ~~I've updated documentation for my change (if appropriate)~~
This PR adds some tests to ensure `generator-star-spacing` rule does not crash on async functions. …
=> Chore: add tests for `generator-star-spacing` and async (refs #7101)

lib/rules/arrow-parens.js, tests/lib/rules/arrow-parens.js
* **Node Version:** 6.6.0
* **npm Version:** 3.10.3
```json
{
"parserOptions": {
"ecmaVersion": 8
}
}
``` …
=> Update: Ensure `arrow-parens` handles async arrow functions correctly

lib/rules/no-unused-expressions.js, tests/lib/rules/no-unused-expressions.js
* **Node Version:** 6.6.0
* **npm Version:** 3.10.3
```json
{
"parserOptions": {
"ecmaVersion": 8
}, …
```
=> Fix: Handle await expressions correctly in `no-unused-expressions`

lib/rules/prefer-arrow-callback.js, tests/lib/rules/prefer-arrow-callback.js
See #7101 for context. This allows the fixer for `prefer-arrow-callback` to emit async arrow functions. At the moment the fixer always emits regular arrow …
=> Fix: Handle async functions correctly in `prefer-arrow-callback` fixer

lib/rules/array-callback-return.js, tests/lib/rules/array-callback-return.js
See #7101 for context. This is one of the rule fixes that prevents incorrect behavior now that we can support async functions.
This fix updates …
=> Fix: Don't report async/generator callbacks in `array-callback-return`

lib/rules/valid-typeof.js, tests/lib/rules/valid-typeof.js
See #7166 for a description of the bug.
This allows `valid-typeof` to detect comparisons to template literals.
```js
/* eslint valid-typeof: 2 */
typeof foo === …
```
=> Update: Allow template string in `valid-typeof` comparison (fixes #7166)

docs/rules/keyword-spacing.md, lib/rules/keyword-spacing.js, tests/lib/rules/keyword-spacing.js
* **Node Version:** 6.3.0
* **npm Version:** 3.8.9
- default
- nothing
**What did you do? Please include the …
=> Update: `keyword-spacing` supports async/await (refs #7101)

lib/ast-utils.js, lib/rules/no-whitespace-before-property.js, tests/lib/ast-utils.js, tests/lib/rules/no-whitespace-before-property.js
* **Node Version:** 6.6.0
* **npm Version:** 3.10.3
default
none
**What did you do? Please include the actual …
=> Fix: Handle number literals correctly in `no-whitespace-before-property`

lib/ast-utils.js, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
* **Node Version:** 6.3.0
* **npm Version:** 3.8.9
- default
- nothing
**What did you do? Please include the …
=> Update: `no-extra-parens` supports async/await (refs #7101)

docs/rules/prefer-template.md, lib/rules/prefer-template.js, tests/lib/rules/prefer-template.js
This adds a fixer for `prefer-template`, as described in #6978.
We should make sure that the logic for …
=> Update: add fixer for `prefer-template` (fixes #6978)

lib/rules/space-unary-ops.js, tests/lib/rules/space-unary-ops.js
See #7101 for context. Now that async functions can be parsed by `acorn`, this fix allows [`space-unary-ops`](http://eslint.org/docs/rules/space-unary-ops) to detect `await` expressions.
**What rule do you want to …
=> Update: Allow `space-unary-ops` to handle await expressions

docs/rules/strict.md, lib/rules/strict.js, tests/lib/rules/strict.js
This adds a fixer for `strict`. The fixer removes unnecessary `'use strict';` directives. Other errors reported by the `strict` rule are not fixed, to avoid …
=> Update: add fixer for `strict` (fixes #6668)
