eslint/eslint

- docs/rules/operator-linebreak.md
> Docs: Default option from `operator-linebreak` is `after`and not always

- CHANGELOG.md
- docs/rules/class-methods-use-this.md
The option is named "exceptMethods", not "exceptions"
¯\\\_(ツ)\_/¯
> Docs: `class-methods-use-this`: fix option name

- docs/rules/eol-last.md
Correct desire eol-last value after this pull request https://github.com/eslint/eslint/pull/6952
nope :)
> correct eol-last desire value documentation

- .eslintignore
- Makefile.js
- bin/eslint.js
[x] Other, please explain: Make sure we're linting bin/eslint.js
Ensured bin/eslint.js was linted (by adding a `bin/**/*.js` glob to Makefile.js and removing a line from .eslintignore). Then fixed lint errors.
I turned off `no-console` and `no-process-exit` for the file, since we allow those in bin/eslint.js. Let me know if that's not okay (e.g., `console.log` invocations could be replaced by requiring and using the logger file we have).
Also, this …
> Chore: Lint bin/eslint.js

- Makefile.js
Fixes https://github.com/eslint/eslint.github.io/issues/288.
We currently strip the .md extension from all URLs, but we actually do want to send users to the template .md files on GitHub in this case.
**What …
> Build: Do not strip .md extension from absolute URLs

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
See https://github.com/eslint/eslint/issues/7229 for more info on the bug.
Previously, the …
> Update: Fix `no-extra-parens` false negative (fixes #7229)

- Makefile.js
- bin/eslint.js
- tests/bin/.eslintrc.yml
- tests/bin/eslint.js
See #7213 for template answers.
This updates `bin/eslint.js` to treat stdin errors like all other …
> Fix: Use error templates even when reading from stdin (fixes #7213)

- lib/rules/indent.js
- tests/lib/rules/indent.js
See https://github.com/eslint/eslint/issues/7248
This updates `indent` to not report lines that …
> Fix: avoid indent and no-mixed-spaces-and-tabs conflicts (fixes #7248)

- docs/rules/yoda.md
- lib/rules/yoda.js
- tests/lib/rules/yoda.js
This adds a fixer for [`yoda`](http://eslint.org/docs/rules/yoda). When `yoda` reports that a binary expression should be flipped, the fixer can flip the sides of …
> Update: for `yoda`, add a fixer

- docs/rules/dot-location.md
- lib/rules/dot-location.js
- tests/lib/rules/dot-location.js
This adds an autofixer for [`dot-location`](http://eslint.org/docs/rules/dot-location).
Given a `MemberExpression` where the dot is in the wrong location, the fixer …
> Update: Add a fixer for `dot-location`

- docs/rules/wrap-iife.md
- lib/rules/wrap-iife.js
- tests/lib/rules/wrap-iife.js
This adds a fixer for [`wrap-iife`](http://eslint.org/docs/rules/wrap-iife).
If the IIFE has no surrounding parentheses, the fixer surrounds it with parentheses. …
> Update: add fixer for `wrap-iife`

- docs/rules/lines-around-directive.md
- lib/rules/lines-around-directive.js
- tests/lib/rules/lines-around-directive.js
This adds a fixer for [`lines-around-directive`](http://eslint.org/docs/rules/lines-around-directive).
If the rule reports a missing newline, the fixer adds the …
> Update: add fixer for `lines-around-directive`

- docs/rules/no-useless-computed-key.md
- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
This adds a fixer for [`no-useless-computed-key`](http://eslint.org/docs/rules/no-useless-computed-key).
The fixer removes the square brackets around unnecessary …
> Update: add fixer for `no-useless-computed-key`

- lib/rules/indent.js
- tests/lib/rules/indent.js
See #7249
This ensures that `indent` handles the parameters of nested function declarations and …
> Update: Ensure `indent` handles nested functions correctly (fixes #7249)

- docs/user-guide/configuring.md
"Parser options" section in "configuring" doc has an intro …
> Docs: Adding missing ES8 reference to configuring

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
See #7250 for template.
- ~~I've updated documentation for my change (if appropriate)~~
I had changed the `after-used` option's behavior in #7143 in order to fix …
> Fix: `no-unused-vars` false positive (fixes #7250)

- docs/rules/no-undef-init.md
- lib/rules/no-undef-init.js
- tests/lib/rules/no-undef-init.js
This adds a fixer for [`no-undef-init`](http://eslint.org/docs/rules/no-undef-init).
The fixer replaces `var x = undefined;` with `var x;`. It does not apply a fix …
> Update: add fixer for `no-undef-init`

- docs/rules/prefer-numeric-literals.md
- lib/rules/prefer-numeric-literals.js
- tests/lib/rules/prefer-numeric-literals.js
This adds a fixer for [`prefer-numeric-literals`](http://eslint.org/docs/rules/prefer-numeric-literals).
When given a function call such as `parseInt('123', 16)`, …
> Update: add fixer for `prefer-numeric-literals`

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
This PR fixes issue #7214.
`object-shorthand`'s `consistent-as-needed` rule was failing when keys were either numbers or quoted strings. We (@ahuth and I) fixed …
> Fix: object-shorthand's consistent-as-needed option (issue #7214)

- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
https://github.com/eslint/eslint/issues/7272
no-implic-coercion now only makes recommendations and will not attempt to fix anything using the `~` operator.
**Is …
> Fix: no-implicit-coercion should not fix ~. Fixes #7272

- lib/rules/comma-dangle.js
- tests/lib/rules/comma-dangle.js
See #7291
Previously, `comma-dangle` would report the location of …
> Fix: Use the correct location for `comma-dangle` errors (fixes #7291)

- docs/rules/no-extra-bind.md
- lib/rules/no-extra-bind.js
- tests/lib/rules/no-extra-bind.js
This adds a fixer for [`no-extra-bind`](http://eslint.org/docs/rules/no-extra-bind). The fixer removes the unnecessary calls to `.bind` that the rule reports.
**Is …
> Update: add fixer for `no-extra-bind`

- docs/rules/curly.md
- lib/rules/curly.js
- tests/lib/rules/curly.js
```
```
This introduces a fixer for the …
> Update: add fixer for `curly`

- lib/rules/semi.js
- tests/lib/rules/semi.js
[] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[X] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
semi
more (with `"never"`)
Change to behavior of `"never"` option
**Please provide some …
> Don't require semicolons before unary operators

- docs/rules/no-lonely-if.md
- lib/rules/no-lonely-if.js
- tests/lib/rules/no-lonely-if.js
This adds a fixer for [`no-lonely-if`](http://eslint.org/docs/rules/no-lonely-if). When it encounters an `if` statement as the only statement in an `else` block, …
> Update: add fixer for `no-lonely-if`

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
See https://github.com/eslint/eslint/issues/7305
This updates …
> Fix: avoid `object-shorthand` crash with spread properties (fixes #7305)

- lib/cli.js
- lib/options.js
- package.json
- tests/lib/cli.js
- tests/lib/options.js
Changing behavior of a CLI option (--print-config).
Since --print-config operates on one file, …
> Fix: Reworking/improving optionator configuration for --print-config

- docs/rules/max-len.md
- lib/rules/max-len.js
- tests/lib/rules/max-len.js
Also see: https://github.com/eslint/eslint/issues/2370
[`max-len`](http://eslint.org/docs/rules/max-len)
Fewer
**How will the change be …
> Update: Use characters instead of code units for `max-len`

- lib/rules/no-multiple-empty-lines.js
- tests/lib/rules/no-multiple-empty-lines.js
See https://github.com/eslint/eslint/issues/7312
This commit is …
> Update: Fix false negative of `no-multiple-empty-lines` (fixes #7312)

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
- tests/lib/util/source-code.js
The same amount
The error message will change for the …
> Update: Improve the error messages for `no-unused-vars` (fixes #7282)

- docs/rules/one-var-declaration-per-line.md
- lib/rules/one-var-declaration-per-line.js
- tests/lib/rules/one-var-declaration-per-line.js
This adds a fixer for [`one-var-declaration-per-line`](http://eslint.org/docs/rules/one-var-declaration-per-line). It inserts a …
> Update: add fixer for `one-var-declaration-per-line`

- lib/rules/comma-dangle.js
- tests/lib/rules/comma-dangle.js
See https://github.com/eslint/eslint/issues/7297
This fixes …
> Fix: Don't require commas after rest properties (fixes #7297)

- docs/rules/prefer-spread.md
- lib/rules/prefer-spread.js
- tests/lib/rules/prefer-spread.js
This adds a fixer for [`prefer-spread`](http://eslint.org/docs/rules/prefer-spread).
```js
foo.apply(null, bar);
foo.bar.apply(foo, qux); …
```
> Update: add fixer for `prefer-spread`

- lib/testers/rule-tester.js
* **Node Version:** 6.3.0
* **npm Version:** 3.8.9
- default
- https://www.npmjs.com/package/eslint-config-mysticatea
1. Clone https://github.com/mysticatea/eslint-plugin-node
2. `npm install`
3. `mocha tests/lib/rules/*.js --watch --reporter progress`
4. Edit a `.js` file in the repo.
Mocha re-runs all tests.
```
$ mocha tests/lib/rules/*.js …
```
> Fix: `RuleTester` didn't support `mocha --watch`

- lib/rules/yoda.js
- tests/lib/rules/yoda.js
See https://github.com/eslint/eslint/issues/7326
This updates the …
> Fix: Handle parentheses correctly in `yoda` fixer (fixes #7326)

- lib/rules/prefer-template.js
- tests/lib/rules/prefer-template.js
See https://github.com/eslint/eslint/issues/7330
This updates the …
> Update: Make the `prefer-template` fixer unescape quotes (fixes #7330)

- tests/lib/cli-engine.js
- tests/lib/cli.js
- tests/lib/config.js
- tests/lib/config/config-file.js
- tests/lib/config/config-initializer.js
- tests/lib/config/config-ops.js
- tests/lib/eslint.js
- tests/lib/ignored-paths.js
- tests/lib/rules/complexity.js
- tests/lib/rules/keyword-spacing.js
- tests/lib/rules/max-lines.js
- tests/lib/rules/no-control-regex.js
- tests/lib/rules/no-empty-function.js
- tests/lib/rules/no-invalid-this.js
- tests/lib/rules/no-multiple-empty-lines.js
- tests/lib/util/glob-util.js
- tests/lib/util/source-code-fixer.js
- tests/lib/util/source-code-util.js
- tests/templates/pr-create.md.ejs.js
Chore: using the new prefer-template autofix to start converting files so we can enable prefer-template in the ESLint repo. Originally discussed here. …
> Chore: run prefer-template autofixer on test files

- docs/developer-guide/nodejs-api.md
- docs/developer-guide/working-with-custom-formatters.md
- lib/cli-engine.js
- tests/lib/cli-engine.js
This PR refers to #7098.
Add a source property containing the entire file contents as a string into the linting results for each file …
> Update: add source property to LintResult object (fixes #7098)

- docs/rules/no-useless-escape.md
- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
`no-useless-escape` is currently missing support for checking template literals (most likely because the rule was created before …
> Update: no-useless-escape checks template literals (fixes #7331)

- .github/PULL_REQUEST_TEMPLATE.md
> Chore: Update pull request template (refs eslint/tsc-meetings#20)

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
See https://github.com/eslint/eslint/issues/7351
This updates …
> Fix: Don't report setter params in class bodies as unused (fixes #7351)

- lib/rules/id-length.js
- tests/lib/rules/id-length.js
Corrected the `MemberExpression` check on the parent node when determining assignment to an object property.
Nope.
> Fix: id-length rule incorrectly firing on member access (fixes #6475)

- docs/rules/space-before-function-paren.md
- lib/rules/space-before-function-paren.js
- tests/lib/rules/space-before-function-paren.js
- [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren)
- In espree, this does not change errors. 
- This may increase errors if someone …
> Update: `space-before-function-paren` supports async/await (refs #7101)

- docs/rules/comma-dangle.md
- lib/rules/comma-dangle.js
- tests/lib/rules/comma-dangle.js
- [comma-dangle](http://eslint.org/docs/rules/comma-dangle)
- This increases warnings by opt-in.
**How will the change be implemented? (New option, new default behavior, …
> Update: `comma-dangle` supports trailing function commas (refs #7101)

- docs/developer-guide/working-with-rules.md
Over on [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules), there has been some discussion about being able to detect deprecated rules in order to [not report them as unused](https://github.com/sarbbottam/eslint-find-rules/issues/172) and to [report when they are still being used](https://github.com/sarbbottam/eslint-find-rules/issues/188).
In order to implement those features, there needs to be a way to detect that a rule has been deprecated.  Core ESLint rules that are deprecated are marked as such in their metadata, but this property is not currently documented.
This PR adds documentation about the meta property so that plugin authors can see that it is something they can use on their rules.
> Docs: Document the deprecated meta property

- docs/developer-guide/nodejs-api.md
Fixed a broken link to the `stylish` formatter in the "Node.js API" docs.
Nope.
> Docs: Fix broken link for stylish formatter

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
See https://github.com/eslint/eslint/issues/7383
This updates `no-useless-escape` to not report escaped characters in tagged template literals, because the backslash is visible to the tag function. …
> Fix: Allow useless escapes in tagged template literals (fixes #7383)

- lib/rules/comma-dangle.js
- tests/fixtures/parsers/comma-dangle/object-pattern-1.js
- tests/fixtures/parsers/comma-dangle/object-pattern-2.js
- tests/fixtures/parsers/comma-dangle/return-type-1.js
- tests/fixtures/parsers/comma-dangle/return-type-2.js
- tests/lib/rules/comma-dangle.js
See #7370 for the template.
Since c8796e98af6804cccc947ab3e3b06d884a8d035f, `comma-dangle` rule have been confused by type annotations.
This PR modifies the rule as supporting type annotations correctly. (it just removes optimization code.)
This follows #6723 about the way to test type annotations.
The AST was created by `babel-eslint` of http://astexplorer.net/ .
> Fix: `comma-dangle` was confused by type annotations (fixes #7370)

- docs/rules/arrow-body-style.md
- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
This adds a fixer for [`arrow-body-style`](http://eslint.org/docs/rules/arrow-body-style).
```js
/* eslint arrow-body-style: [2, "as-needed"] */
var foo = () => { …
```
> Update: add fixer for `arrow-body-style`

- docs/developer-guide/nodejs-api.md
Made sure that a `fatal` property is always present on every `message`.
It came up while looking at the docs for programmatic usage (#7362), which erroneously included `fatal: false`. While `if …
> Add information about `fatal` property to lint message documentation

- docs/rules/indent.md
Added additional explanation for the `MemberExpression` option in the Indent rule to make it more clear that there are many options for setting indent to something other than `2` when using …
> Docs: add additional examples/explanation for MemberExpressions indent

- docs/rules/class-methods-use-this.md
The documentation for `class-methods-use-this` starts with the following statement:
> If a class method does not use this, it can *safely* be made a static function.
The inclusion of the word "safely" here may give some developers the impression that they can simply add the `static` keyword to any functions reported as errors by this rule.
As we know though, making a function static means that the function can no longer be called on an *instance* of the class, and must be called on the *class* itself.
Though the existing code examples **do** show this, I felt that it wasn't immediately clear to the reader that making an existing function static …
> Docs: Fix typo and explain static func calls for class-methods-use-this

- docs/rules/camelcase.md
- lib/rules/camelcase.js
- tests/lib/rules/camelcase.js
See https://github.com/eslint/eslint/issues/7363
This updates `camelcase` to allow `NewExpression`s with non-camelcase identifiers. Previously, `CallExpression`s were allowed but `NewExpression`s …
> Fix: avoid `camelcase` false positive with NewExpressions (fixes #7363)

- lib/cli-engine.js
- lib/config/config-file.js
- lib/eslint.js
- packages/eslint-config-eslint/default.yml
- tests/lib/cli-engine.js
- tests/lib/eslint.js
- tests/lib/rules/comma-dangle.js
- tests/lib/rules/jsx-quotes.js
- tests/lib/rules/key-spacing.js
- tests/lib/rules/new-cap.js
- tests/lib/rules/no-invalid-regexp.js
- tests/lib/rules/no-useless-escape.js
Chore, see overview section below.
As per the discussion [here](https://github.com/eslint/eslint/pull/7357#discussion_r83376369), I've turned the `no-useless-escape` rule on and fixed all the …
> Chore: Enable `no-useless-escape`

- Makefile.js
See https://github.com/eslint/eslint/issues/7426
This updates `Makefile.js` to add quotes around the linting glob patterns. This ensures that the globs get handled by ESLint's glob parser, rather …
> Build: ensure that all files are linted on bash (fixes #7426)

- lib/rules/indent.js
- tests/lib/rules/indent.js
This PR fixes: https://github.com/eslint/eslint/issues/7366 and possibly https://github.com/eslint/eslint/issues/7320.
Updated indent.js and tests to ensure support for function bodies inside of …
> Fix: support for MemberExpression with function body.

- lib/rules/func-name-matching.js
- tests/lib/rules/func-name-matching.js
[`func-name-matching`](https://github.com/eslint/eslint/issues/7391)
It adds an "always"/"never" string option so that the things it …
> Update: `func-name-matching`: add “always/never” string (fixes #7391)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
See #7122 for the template.
This PR changes `no-extra-parens` as reporting parentheses around octal integer literals.
```js
(0123).a    // Gratuitous parentheses around expression.
```
> Update: fix false negative of `no-extra-parens` (fixes #7122)

- lib/rules/indent.js
- lib/rules/yoda.js
- tests/lib/rules/indent.js
Fix: Return statement spacing. Fix for indent rule. (fixes: #7164)
[X] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
indent rule won't check return statement spacing. Here is failing example:
```
function() { …
```
> Fix: Return statement spacing. Fix for indent rule. (fixes #7164)

- docs/rules/newline-after-var.md
- lib/rules/newline-after-var.js
- tests/lib/rules/newline-after-var.js
This adds a fixer for [`newline-after-var`](http://eslint.org/docs/rules/newline-after-var).
```js
/* eslint newline-after-var: [2, "always"] */
var foo = 1;
bar();
var foo = 1; …
```
> Update: add fixer for `newline-after-var` (fixes #5959)

- lib/ast-utils.js
- lib/config/config-file.js
- lib/eslint.js
- lib/rules/arrow-body-style.js
- lib/rules/curly.js
- lib/rules/keyword-spacing.js
- lib/rules/no-empty-character-class.js
- lib/rules/no-lonely-if.js
- lib/rules/no-useless-escape.js
- lib/rules/no-warning-comments.js
- lib/rules/semi.js
- lib/util/glob-util.js
- tests/lib/rules/no-useless-escape.js
See https://github.com/eslint/eslint/issues/7424
This updates `no-useless-escape` to verify whether a character needs to be escaped based on its position in a regular expression. Previously, …
> Update: Fix `no-useless-escape` false negative in regexes (fixes #7424)

- package.json
`mock-fs` release 3.12.0 broke master. Everything is fine for 3.11.0
Issue created because of this change: https://github.com/tschaub/mock-fs/pull/141 …
> Chore: Pin mock-fs dev dependency

- package.json
- tests/lib/util/glob-util.js
Upgraded `shelljs` to `^0.7.0` from `^0.6.0`.
Made a change in unit test fixture setup due to a breaking change to `cp` function.
Docs: https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.6-to- …
> Upgrade: Shelljs to ^0.7.5 (fixes #7316)

- docs/developer-guide/nodejs-api.md
- docs/user-guide/command-line-interface.md
- lib/formatters/codeframe.js
- package.json
- tests/lib/formatters/codeframe.js
Implements the `codeframe` formatter, which closely resembles the default JSCS formatter. Here are some screenshots of how it looks like under different circumstances:
When only errors are reported:
When errors and warnings are reported:
When only warnings are reported:
When a parsing error is reported:
When an error that has no line/column is reported:
- Is this a "`Core`" or a "`New`" change? I was not sure :(
- I took the liberty of suggesting a name for the formatter that is not "JSCS", as I believe it would be a confusing name after a year or two from now. More than happy to …
> New: Codeframe (JSCS) formatter (fixes #5860)

- lib/rules/array-bracket-spacing.js
- tests/fixtures/parsers/array-bracket-spacing/flow-destructuring-1.js
- tests/fixtures/parsers/array-bracket-spacing/flow-destructuring-2.js
- tests/lib/rules/array-bracket-spacing.js
Original issue: #4753
Per `comma-dangle`, `object-curly-spacing`, and #7436, it appears that these updates can belong in ESLint now.
In `array-bracket-spacing`, if a type annotation is present, take the last token and the penultimate token before the type annotation.
This code is slightly different from the code in `eslint-plugin-babel`. The code there just steps backward until it finds a `]`. Here I instead look at the token immediately before the beginning of the type annotation. This avoids issues when the …
> Fix: Support type annotations in array-bracket-spacing

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
[`indent`](http://eslint.org/docs/rules/indent)
The rule produces more warnings by opt-in.
**How will the change be implemented? (New option, new default behavior, …
> Update: Add `CallExpression` option for `indent` (fixes #5946)

- docs/rules/no-useless-return.md
`no-useless-return` is fixable, but it is missing the "this rule is fixable" message that all the other rules have on the docs page. This PR adds that message. …
> Docs: add the "fixable" icon for `no-useless-return`

- lib/rules/prefer-reflect.js
Update rule metadata to stop it from crashing build.
Update rule's metadata
No
> Build: Fix prefer-reflect rule to not crash site gen build

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
See https://github.com/eslint/eslint/issues/7472
This updates `no-useless-escape` to allow digit characters to be escaped in regular expressions. Escaped digits can either be backreferences or octal …
> Fix: allow escaped backreferences in `no-useless-escape` (fixes #7472)

- lib/rules/no-useless-return.js
- tests/lib/rules/no-useless-return.js
See https://github.com/eslint/eslint/issues/7477
This ensures that if a `return` statement has an argument, and it's on the same code path as another return statement, the first return statement is not considered to be a useless return.
> Fix: `no-useless-return` false positive on conditionals (fixes #7477)

- lib/rules/indent.js
- tests/lib/rules/indent.js
See https://github.com/eslint/eslint/issues/7484
This fixes an issue where array indentation was calculated incorrectly for MemberExpression nodes.
It does this by removing some outdated logic from …
> Fix: incorrect `indent` check for array property access (fixes #7484)

- docs/rules/no-extra-boolean-cast.md
- lib/rules/no-extra-boolean-cast.js
- tests/lib/rules/no-extra-boolean-cast.js
This adds a fixer for [`no-extra-boolean-cast`](http://eslint.org/docs/rules/no-extra-boolean-cast).
``` js
if (!!foo);
if (Boolean(bar));
Boolean(!!baz);
if (foo);
if (bar); …
```
> Update: add fixer for `no-extra-boolean-cast`

- lib/rules/lines-around-directive.js
- tests/lib/rules/lines-around-directive.js
See https://github.com/eslint/eslint/issues/7450
This allows `lines-around-directive` to correctly handle directives that have a trailing semicolon on a different line.
``` js
'use strict'
; [1, 2, 3].map(foo)
```
This is _semver-minor_ with our semver policy, because it can cause more warnings to be reported in cases like this:
> Update: Fix `lines-around-directive` semicolon handling (fixes #7450)

- Makefile.js
Make sure deprecated rules that have no `meta.docs.replacedBy` property don't break the build. This PR is also related to https://github.com/eslint/eslint.github.io/pull/308.
I've made it so the `generateRuleIndexPage()` function uses an empty array as a default when it finds a deprecated rule that has no `meta.docs.replacedBy` property.
Nothing in particular, I think.
> Build: handle deprecated rules with no 'replacedBy' (refs #7471)

- docs/rules/require-jsdoc.md
- lib/rules/require-jsdoc.js
- tests/lib/rules/require-jsdoc.js
[ x ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
* Add support for `ArrowFunctionExpression` nodes for `require-jsdoc` rule.
It will produce more warnings only when the option if set to …
> Update: Add `ArrowFunctionExpression` support to `require-jsdoc` rule

- lib/rules/curly.js
- tests/lib/rules/curly.js
[x] Bug fix
* **ESLint Version:** 3.9.1
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8
default
(none)
```js
/* eslint curly: ["error", "multi-line"] */
if (foo) bar()
; [1, 2, 3].map(baz)
```
I expected no errors to be reported, because `bar()` is typically considered to be a single-line statement in this context (even though it has a semicolon on a different line)
```
3:1 - Expected { …
```
> Fix: `curly` false positive with no-semicolon style

- docs/developer-guide/nodejs-api.md
I just noticed `severity` being there twice. Then I though to double check what the output actually is, and it's quite different, so I changed the whole thing.
**What changes did you …
> Docs: Update example of results returned from `executeOnFiles`

- docs/rules/no-restricted-imports.md
- docs/rules/no-restricted-modules.md
- lib/rules/no-restricted-imports.js
- lib/rules/no-restricted-modules.js
- package.json
- tests/lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-modules.js
`no-restricted-imports` and `no-restricted-modules`
More, only when the "patterns" option is set.
**How will the change be implemented? (New …
> Update: `no-restricted-{imports,modules}`: add “patterns” (fixes #6963)

- lib/rules/arrow-parens.js
- tests/fixtures/parsers/arrow-parens/identifer-type.js
- tests/fixtures/parsers/arrow-parens/return-type.js
- tests/lib/rules/arrow-parens.js
See #7406 for the template.
If there is a type annotation, we cannot remove parentheses around parameters of arrow functions. But `arrow-parens` has warned those.
``` js
(a: T) => a;
(a): T => a;
```
This PR fixes the bug.
I generated the ASTs with type annotations by http://astexplorer.net/
> Fix: `arrow-parens` supports type annotations (fixes #7406)

- tests/lib/rules/indent.js
While working on a bug fix, https://github.com/eslint/eslint/issues/7320, I found that in one of my PR's for the indent rule a few weeks ago, I included an incorrect test and wanted to remove it …
> Chore: Remove incorrect test from indent.js.

- docs/developer-guide/working-with-plugins.md
`RuleTester` accepts an optional argument with default options for tests, but the argument is currently undocumented. This PR adds documentation for that option.
> Docs: Document the optional defaults argument for RuleTester

- lib/testers/rule-tester.js
- tests/lib/testers/rule-tester.js
[X ] Other, please explain: Change in rule-tester.
[issue 6106](https://github.com/eslint/eslint/issues/6106)
Removed the overwriting message in the assert.equal statement. …
> Chore: "Error type should be" assertion in rule-tester (fixes 6106)

- docs/user-guide/configuring.md
Updated the docs to explain how config options are merged from base configs.
There was a lot of …
> Update docs to explain config option merging

- lib/rules/space-infix-ops.js
- tests/lib/rules/space-infix-ops.js
See https://github.com/eslint/eslint/issues/7525
This updates `space-infix-ops` to handle `in` and `instanceof` correctly. Due to a bug, it previously did not report any cases with `in` or …
> Update: fix in/instanceof handling with `space-infix-ops` (fixes #7525)

- docs/rules/curly.md
- lib/rules/curly.js
- tests/lib/rules/curly.js
Fixes https://github.com/eslint/eslint/issues/7538
Fixes the curly rule under the "multi-or-nest" setting, includes tests, and updates docs with an example …
> Fix: Curly rule doesn't account for leading comment (fixes #7538)

- bin/eslint.js
This modifies bin/eslint.js to set process.exitCode rather than using `process.exit()` on an error.
`process.exit()` is [a bit unsafe](https://nodejs.org/api/process.html#process_process_exit_code) …
> Chore: Use process.exitCode instead of process.exit() in bin/eslint.js

- Makefile.js
- conf/eslint.json
- docs/rules/no-return-await.md
- lib/rules/no-return-await.js
- tests/lib/rules/no-return-await.js
Inside an `async function`, `return await` is useless. Since the return value of an `async function` is always wrapped in `Promise.resolve`, `return await` doesn't actually do anything except add an extra …
> New: `no-return-await` rule. (fixes #7537)

- lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-body-style.js
[`arrow-body-style`](http://eslint.org/docs/rules/arrow-body-style)
The same amount
This will change the default behavior.
```js
/* eslint arrow-body-style: "error" */
foo(bar => {
return baz;
}, qux);
```
It reports an error. With the `--fix` option, it fixes the code to:
```js
foo(bar => 
baz
, qux);
```
It will still report an error. With …
> Update: avoid creating gratuitous whitespace in `arrow-body-style` fixer

- Makefile.js
- tests/.eslintrc.yml
- tests/bin/.eslintrc.yml
- tests/conf/eslint-all.js
- tests/lib/.eslintrc
- tests/templates/.eslintrc
This fixes an issue where files in `tests/conf` weren't getting linted. It also gets rid of a few redundant `.eslintrc` files that only contain `{env: {mocha: true}}` in favor of a single file in …
> Chore: ensure that files in tests/conf are linted

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
See https://github.com/eslint/eslint/issues/7574
This fixes several bugs in `object-shorthand`'s autofixing.
* Previously, if an object had a computed key that was anything other than an identifier …
> Fix: syntax errors created by `object-shorthand` autofix (fixes #7574)

- docs/rules/func-names.md
- lib/rules/func-names.js
- tests/lib/rules/func-names.js
`func-names`
Fewer, when `uninferred` is in use rather than `always`.
New option
``` js
var foo = function(){};
```
It will error because the function has no name. While true for ES5, in ES6 the function will be given a name based on the variable it is assigned to.
If `uninferred` is used instead, it will not recognize this as an error.
**Please check each item to ensure …
> Update: Allow `func-names` to recognize inferred ES6 names (fixes #7235)

- tests/lib/rules/object-shorthand.js
This cleans up the `object-shorthand` tests by adding some whitespace, using default parserOptions to reduce clutter, and creating constants for the errors. The rule itself is not changed.
**Is there …
> Chore: make the `object-shorthand` tests more readable

- docs/rules/comma-style.md
- lib/rules/comma-style.js
- lib/testers/rule-tester.js
- tests/lib/rules/comma-style.js
comma-style
More.
This change adds new default behavior to `comma-style`, and includes new options to disable the default behavior. I'm happy to reverse the defaults (so that the new behavior is opt-in), but started with opt-out for consistency with the existing code.
``` js
import {
A
, B
} from 'source';
const [
quux
, baz
] = "a b".split(" ");
const {
push
, pop
} = Array.prototype;
const foo = ([
a
, b
]) => {
return a * b;
}
function bip(a
, b) { return a - b } …
```
> Gh 7470 comma style for functions calls and imports

- lib/rules/no-useless-return.js
- tests/lib/rules/no-useless-return.js
See https://github.com/eslint/eslint/issues/7583
When `no-useless-return` encounters an unreachable code path segment, it backtracks from that code path segment until it finds a segment that is reachable. If that reachable segment is a `return` statement, the `return` statement is considered to not be useless.
If an entire loop was unreachable, the rule would continue "backtracking" in circles forever, because it was always able to find an unreachable code path segment preceding the current one. This resulted in a stack overflow.
```js
/* eslint no-useless-return: …
```
> Fix: no-useless-return stack overflow on unreachable loops (fixes #7583)

- lib/rules/no-return-await.js
- tests/lib/rules/no-return-await.js
See https://github.com/eslint/eslint/issues/7581
`no-return-await` is intended to flag redundant uses of `await` in returned values. However, if `return await` is used within a `try` block, the …
> Fix: handle try/catch correctly in `no-return-await` (fixes #7581)

- docs/rules/no-tabs.md
- lib/rules/no-tabs.js
No logged issue, I just noticed that the new docs for `no-tab` weren't as "professional" as the rest.
Updated to match existing docs standards and improve the readability of the content.
No
> Docs: Update no-tabs to match existing standards & improve readbility

- docs/rules/curly.md
Accidentally wrote the wrong example in my previous PR in https://github.com/eslint/eslint/pull/7539. Fixed it so it now correctly shows a good and bad example for having a comment inside an `if` …
> Docs: Fix example for curly "multi-or-nest" option

- lib/rules/indent.js
- tests/lib/rules/indent.js
See https://github.com/eslint/eslint/issues/7573
This fixes the `indent` autofixer to avoid throwing an error on global return values.
The autofixer is intended to replace all the indentation before …
> Fix: `indent` crash on parenthesized global return values (fixes #7573)

- lib/rules/key-spacing.js
- tests/lib/rules/key-spacing.js
https://github.com/eslint/eslint/issues/7603
This updates the `key-spacing` autofixer to be aware of comments. Previously, it would remove whitespace from the *token* before/after the colon, but if there was a comment between the token and the colon, it would remove text from the edge of the comment instead, causing a syntax error.
> Fix: syntax error after `key-spacing` autofix with comment (fixes #7603)

- lib/rules/indent.js
- tests/fixtures/rules/indent/indent-valid-fixture-1.js
- tests/lib/rules/indent.js
See https://github.com/eslint/eslint/issues/7604
Note: This builds off of https://github.com/eslint/eslint/pull/7596, please merge that first.
Previously, the `indent` autofixer didn't account for …
> Fix: correctly handle commented code in `indent` autofixer (fixes #7604)

- docs/rules/no-extra-parens.md
Without this exact wording, the following code example was not styled properly.
> Docs: fix wording in docs for no-extra-parens config

- docs/rules/operator-linebreak.md
In the documentation examples for the `operator-linebreak` rule, fixed a property key with a missing quote mark.  `+="` → `"+="`
No.
> Docs: add missing quote mark (+=" → "+=")

- Makefile.js
- package.json
Updating a devDependency in package.json.
Updated markdownlint dependency to 0.3.1, enabled resultVersion 1 for more detailed reporting.
No
> Upgrade: Update markdownlint dependency to 0.3.1 (fixes #7589)

- lib/rules/quotes.js
- tests/lib/rules/quotes.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7610
This updates `quotes` to avoid fixing template literals that are in directive position, so that the fixer doesn't accidentally enable strict mode.
> Fix: Prevent `quotes` from fixing templates to directives (fixes #7610)

- .gitattributes
[x] Other, please explain: Ensure JavaScript files are checked out with LF line endings
Adding `eol=lf` to .gitattributes for JS files.
Motivation: On my setup, files are checked out with CRLF line endings. eslint-plugin-node has a rule node/shebang which checks for LF line endings. In order to do any development, I have to run `dos2unix` on bin/eslint.js and then stash those changes when checking out other branches. This PR ensures that bin/eslint.js is checked out with LF line endings, so I don't have to work around the node/shebang rule.
Hopefully Travis and AppVeyor will continue to pass. Also feel free to …
> Chore: Ensure JS files are checked out with LF

- conf/eslint.json
- docs/rules/require-await.md
- docs/rules/require-yield.md
- lib/ast-utils.js
- lib/rules/require-await.js
- tests/lib/ast-utils.js
- tests/lib/rules/require-await.js
This rule disallows `async` functions which have no `await` expression.
Async functions which have no `await` expression may be the unintentional result of refactoring.
See #6820 also.
[X] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)
**Provide 2-3 code examples that this rule will warn about:**
``` js
/*eslint require-await: error*/
//------------------------------------------------------------------------------ …
```
> New: `require-await` rule (fixes #6820)

- lib/ast-utils.js
- lib/rules/no-useless-escape.js
- tests/lib/ast-utils.js
- tests/lib/rules/no-useless-escape.js
See https://github.com/eslint/eslint/issues/7643.
* Add `getLocationFromRangeIndex` and `getRangeIndexFromLocation` functions to `ast-utils`. This allows a rule to easily convert `{line: 5, column: 3}` to an absolute index in the file, and vice versa.
* Fix an off-by-one bug in the error locations for template literals. This was happening because we use the same logic to parse escape characters in `TemplateElement` nodes and string literals. However, we were parsing `node.value.raw` for string literals, which includes the surrounding quotes. `TemplateElement` nodes …
> Fix: incorrect location for `no-useless-escape` errors (fixes #7643)

- docs/rules/arrow-spacing.md
- docs/rules/constructor-super.md
- docs/rules/no-arrow-condition.md
- docs/rules/no-class-assign.md
- docs/rules/no-comma-dangle.md
- docs/rules/no-confusing-arrow.md
- docs/rules/no-const-assign.md
- docs/rules/no-empty-class.md
- docs/rules/no-empty-label.md
- docs/rules/no-eval.md
- docs/rules/no-extra-strict.md
- docs/rules/no-reserved-keys.md
- docs/rules/no-space-before-semi.md
- docs/rules/no-useless-escape.md
- docs/rules/no-wrap-func.md
- docs/rules/object-shorthand.md
- docs/rules/semi-spacing.md
- docs/rules/space-after-function-name.md
- docs/rules/space-after-keywords.md
- docs/rules/space-before-function-parentheses.md
- docs/rules/space-before-keywords.md
- docs/rules/space-in-brackets.md
- docs/rules/space-in-parens.md
- docs/rules/space-infix-ops.md
- docs/rules/space-return-throw-case.md
- docs/rules/space-unary-ops.md
- docs/rules/space-unary-word-ops.md
- docs/rules/spaced-comment.md
- docs/rules/spaced-line-comment.md
- docs/rules/wrap-regex.md
Some examples showed in the rules docs has outdated examples without highlight so I've updated them in order to enable it. I've also change the order in some examples and change some minimum text to …
> Docs: Enable example highlighting in rules examples (ref #6444)

- docs/rules/sort-imports.md
- lib/rules/sort-imports.js
- tests/lib/rules/sort-imports.js
This adds a fixer for [`sort-imports`](http://eslint.org/docs/rules/sort-imports).
It only sorts `ImportSpecifiers`, and does not sort multiple import statements. Sorting multiple import statements …
> Update: add fixer for `sort-imports`

- lib/rules/quotes.js
- tests/lib/rules/quotes.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7646
This updates the newline detection in `quotes`. `quotes` needs to detect whether a raw template literal contains a newline, so that it can determine whether it should suggest that the template literal be fixed to another quote type. However, it previously detected newlines by searching for LF characters in the *cooked* `TemplateElement` value. As a result, if the template literally contained `\n`, it wouldn't get reported.
The previous behavior also had a few other bugs:
* It incorrectly reported/fixed template literals that contained other characters recognized as newlines in JS (`\r`, `\u2028`, or …
> Update: fix false negative of `quotes` with \n in template (fixes #7646)

- docs/rules/operator-assignment.md
- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
This adds a fixer for [`operator-assignment`](http://eslint.org/docs/rules/operator-assignment).
```js
/* eslint operator-assignment: error */
foo.bar = foo.bar + baz;
foo.bar += baz;
```
```js
/* eslint operator-assignment: [error, "never"] */
foo |= bar;
foo = foo | bar;
```
Caveats:
* The following cases can't be fixed:
```js
/* eslint operator-assignment: error */
// fixing this would change the execution order of bar.valueOf() and foo.valueOf(),
// if the function is defined for both of them
foo = bar * foo;
// fixing this would cause a `foo.bar` getter to activate only once, instead of twice. …
```
> Update: add fixer for `operator-assignment`

- docs/rules/array-bracket-spacing.md
This fixes a spelling error in the array-bracket-spacing docs.
No, nothing in particular
> Docs: Fix a typo in array-bracket-spacing documentation

- lib/rules/capitalized-comments.js
- tests/lib/rules/capitalized-comments.js
https://github.com/eslint/eslint/issues/7663
Added a test to confirm that `// ` would cause `capitalized-comments` to terminate `eslint` with a `TypeError`.
Added code to make sure that …
> Fix: captialized-comments fatal error fixed (fixes #7663)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
[x] Bug fix
* **Node Version:** 7.2.0
* **npm Version:** 3.10.9
default
none
```js
/* eslint no-useless-escape: error */
var foo = "foo\ bar"; // Note: There is a \u2028 character after the backslash.
```
No errors.
```
3:15  error  Unnecessary escape character: \   no-useless-escape
```
This updates …
> Fix: Allow \u2028 and \u2029 as string escapes in no-useless-escape

- docs/rules/spaced-comment.md
I removed the indentation of the JSON code blocks.
Double-check if this really fixes the issue. I don't know how to test it locally, I tried …
> Docs: Fix code-blocks in spaced-comment docs

- Makefile.js
- templates/blogpost.md.ejs
If a commit message contains a string that matches one of ESLint's rule names, it will automatically get converted to a link to the rule's documentation page when generating the blogpost.
For example, the following changelog
```markdown
* 1234567 Fix: `no-undef` bug
* 7654321 Update: add option to no-unused-vars
* aaaaaaa Chore: refactor `no-undefined`
```
...will now get converted to this in the blogpost:
```markdown
* 1234567 Fix: [`no-undef`](/docs/rules/no-undef) bug
* 7654321 Update: add option to [no-unused-vars](/docs/rules/no-unused-vars)
* aaaaaaa Chore: refactor [`no-undefined`](/docs/rules/no-undefined)
``` …
> Build: include links to rule pages in release blogpost

- docs/user-guide/integrations.md
After further testing, sails-hook-lint has been determined to be the best Sails.js integration available.
> Update: Use sails-hook-lint for Sails integration

- docs/developer-guide/contributing/pull-requests.md
As pointed out in https://github.com/eslint/eslint/issues/7589#issuecomment-260212518, our pull request guide incorrectly states that an issue is required for all non-documentation changes. This removes the reference to that requirement.
We already mention needing an issue for core/breaking changes in ["Getting Started"](https://github.com/eslint/eslint/blob/f80c278a1c64ae8291678bc8f9269d022314da3d/docs/developer-guide/contributing/pull-requests.md#getting-started), so I think we can just remove the reference here.
> Docs: Remove incorrect info about issue requirements from PR guide

- lib/config/config-validator.js
- tests/lib/config/config-validator.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7690
This updates `config-validator.js` to avoid option validation when a rule is disabled. This ensures that `some-rule: off` is always a valid way to disable a rule, and it doesn't throw a schema error if the rule requires options when enabled.
> Fix: don't validate schemas for disabled rules (fixes #7690)

- docs/rules/capitalized-comments.md
- lib/rules/capitalized-comments.js
- tests/lib/rules/capitalized-comments.js
This adds a fixer for [`capitalized-comments`](http://eslint.org/docs/rules/capitalized-comments). The fixer works by changing the letter case of the first character of the comment.
> Update: add fixer for `capitalized-comments`

- docs/developer-guide/working-with-rules.md
Some of the guidelines for fixes were incorrect or misleading now that multipass autofix exists. This updates the docs to describe how multipass autofixing works, and also changes some of the autofix guidelines to account for multipass fixing.
> Docs: improve the documentation for the autofix API

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
See https://github.com/eslint/eslint/issues/7473
This adds an `ArrayExpression` and `ObjectExpression` option to the `indent` rule, as described in https://github.com/eslint/eslint/issues/7473.
> Update: add `indent` options for array and object literals (fixes #7473)

- tests/lib/rules/arrow-body-style.js
- tests/lib/rules/arrow-parens.js
- tests/lib/rules/arrow-spacing.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/generator-star-spacing.js
- tests/lib/rules/no-class-assign.js
- tests/lib/rules/no-confusing-arrow.js
- tests/lib/rules/no-const-assign.js
- tests/lib/rules/no-dupe-class-members.js
- tests/lib/rules/no-duplicate-imports.js
- tests/lib/rules/no-new-symbol.js
- tests/lib/rules/no-restricted-imports.js
- tests/lib/rules/no-this-before-super.js
- tests/lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-constructor.js
- tests/lib/rules/no-useless-rename.js
- tests/lib/rules/no-var.js
- tests/lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-const.js
- tests/lib/rules/prefer-numeric-literals.js
- tests/lib/rules/prefer-rest-params.js
- tests/lib/rules/prefer-spread.js
- tests/lib/rules/prefer-template.js
- tests/lib/rules/require-yield.js
- tests/lib/rules/rest-spread-spacing.js
- tests/lib/rules/sort-imports.js
- tests/lib/rules/symbol-description.js
- tests/lib/rules/template-curly-spacing.js
- tests/lib/rules/yield-star-spacing.js
Many of ESLint's rules are only relevant to ES6 code. The tests for some of those rules currently use "{ parserOptions: { ecmaVersion: 6 } }" for each individual test case, rather than specifying a default object as an argument to the `RuleTester` constructor. This PR updates those tests to avoid boilerplate from repeating the same parserOptions over and over.
> Chore: Avoid parserOptions boilerplate in tests for ES6 rules

- docs/rules/operator-linebreak.md
The default behavior for `operator-linebreak` is to use the `"after"` option with overrides for the `?` and `:` operators. However, the documentation incorrectly implied that the overrides were always present when using the `"after"` option, which is not the case. The overrides are part of the default configuration, but they aren't related to the `"after"` option.
(fixes https://github.com/eslint/eslint/issues/7459)
> Docs: clarify the default behavior of `operator-linebreak` (fixes #7459)

- docs/rules/no-obj-calls.md
- lib/rules/no-obj-calls.js
- tests/lib/rules/no-obj-calls.js
[x] Bug fix
See #7700 
I updated [`no-obj-calls`](https://github.com/eslint/eslint/blob/master/lib/rules/no-obj-calls.js) to account for the new global `Reflect` introduced in ECMAScript 2015. This reports an error about the Reflect() call, because it's a global object property and not a function.
> Fix: no-obj-calls does not report errors for Reflect (fixes #7700)

- lib/cli-engine.js
- lib/eslint.js
- lib/rules.js
- tests/lib/cli-engine.js
- tests/lib/cli.js
- tests/lib/eslint.js
- tests/lib/rules.js
Added 3 new API methods.
* `getRules` to `linter`
* `version` to `linter`
* `version` to `CLIEngine`
There's one failing test in the eslint.js file. I honestly don't know how to fix it, since it's only a problem when testing all of the ESLint files. If testing `eslint.js` file by itself, everything passes. This is due to us never cleaning loaded rules (and not having any abilities to clean loaded rules from inside eslint.js file). Any suggestions are welcome. PR is also missing documentation changes. I'll add them once I figure out how to fix failing test.
> New: Additional APIs (fixes #6256)

- conf/eslint.json
- docs/rules/no-await-in-loop.md
- lib/rules/no-await-in-loop.js
- tests/lib/rules/no-await-in-loop.js
This rule disallows the use of `await` within the body of a loop.
[ ] Enforces code style
[x] Warns about a potential error
[ ] …
> New: Add no-await-in-loop rule

- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7712
Due to https://github.com/ternjs/acorn/issues/487, espree does not throw a syntax error for duplicate `let` or `const` declarations. Previously, the `prefer-const` rule assumed that a `let` variable would always have exactly one declaration. This adds a sanity check to avoid reporting (and possibly creating incorrect autofixes from) a `let` variable if it has more than one declaration.
> Fix: Allow duplicated let declarations in `prefer-const` (fixes #7712)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7727
This updates `indent` to correctly handle nested arrays and CallExpressions when the `first` option is used.
In order to determine the desired offset of an array, the rule was checking the offset of the parent node. If the parent node was an array, the offset of the array was multiplied by `options.ArrayExpression`. However, this would result in an expected indentation of `NaN` for that array.
The fix handles this by explicitly checking for an option of `first`, and computing the new node's offset accordingly.
Admittedly, this isn't the most elegant solution. If we kept track of nodes' offsets from each other …
> Fix: indent "first" option false positive on nested arrays (fixes #7727)

- lib/rules/yoda.js
- tests/lib/rules/yoda.js
See #7676 for the template.
The `yoda` rule has a false positive and a false negative.
This PR fixes those bugs.
- c62b847c9d84363663d267c6804700735ffe29b4 fixed the false negative about computed properties in the range check.
```js
/*eslint yoda: [error, never, {exceptRange: true}] */
if (0 <= a.b && a[b] < 10) {}
```
The `yoda` rule has been handling `a.b` and `a[b]` as the same then it determines the condition is a range check wrongly. As the result, it should warn the `0 <= a.b` but does not warn it. After this PR is applied, the `yoda` rule will warn the `0 <= …
> Update: fix false positive/negative of yoda rule (fixes #7676)

- templates/blogpost.md.ejs
Previously, if a rule name in a commit message was surrounded by backticks, the generated URL in the blogpost would also contain backticks around the rule name, resulting in a 404. This updates the blogpost generator to avoid outputting the backticks in URLs.
> Build: avoid creating broken rule links in the blogpost

- docs/rules/no-restricted-globals.md
- docs/rules/no-restricted-properties.md
- docs/rules/no-restricted-syntax.md
Ensured that `no-restricted-globals`, `no-restricted-properties`, and `no-restricted-syntax` all linked to each other in their documentation.
I'm not sure `no-restricted-syntax` really fits with `no-restricted-globals` and `no-restricted-properties`, but there was already a link between `no-restricted-properties` and `no-restricted-syntax`. Should I instead remove `no-restricted-syntax` from the other two rules? `no-restricted-syntax` points to rules like `no-debugger` which it supersedes.
> Docs: Rules restricting globals/properties/syntax are linked together

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7732 and https://github.com/eslint/eslint/issues/7733
This fixes a regression in`indent` in which if a configuration did not specify a value for the `CallExpression` option, it would get interpreted as `CallExpression: first` for object and array arguments.
I think we should add some additional fixtures or smoketests to the indent rule, even if the fixture contains a large codebase in itself. The rule has several hundred tests, but it seems like we're still missing cases. If we add more fixtures, we can be more confident that a particular change isn't going …
> Fix: `indent` regression with function calls (fixes #7732, fixes #7733)

- docs/rules/guard-for-in.md
- docs/rules/no-extra-parens.md
- docs/rules/no-prototype-builtins.md
- docs/rules/prefer-rest-params.md
Updating documentation for `no-prototype-builtins`
I thought rather than encouraging people to use `{}.prototype.hasOwnProperty.call` it would …
> Use `Object.prototype` in examples

- templates/blogpost.md.ejs
In the latest blogpost (see [here](https://github.com/eslint/eslint.github.io/blob/0709ac422ed42219219887e9468ca867ed18f4f4/_posts/2016-12-12-eslint-v3.12.1-released.md#documentation)), the word "restricting" in a commit message caused a link to be created to the [`strict`](http://eslint.org/docs/rules/strict) rule documentation.
This commit fixes the issue by requiring a word boundary to be present around the rule name for a URL to be inserted.
> Build: Don't create blogpost links from rule names within other words

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix
This updates `indent` to apply array/object offsets even when they don't have a VariableDeclarator parent.
This builds off of https://github.com/eslint/eslint/pull/7734, so it should not be merged until that PR is merged. Since this bug is not a regression, it might be better to do a patch release with only https://github.com/eslint/eslint/pull/7734 rather than rushing this PR.
> Fix: indent bug with AssignmentExpressions (fixes #7747)

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/7744
This refactors object-shorthand's autofixing logic to avoid code duplication, and fixes the following issues:
* Shorthand async methods would cause a syntax error when fixed to longform properties
* Longform properties with parenthesized computed keys would cause a syntax error when fixed to shorthand properties
> Fix: syntax errors from object-shorthand autofix (fixes #7744)

- docs/rules/no-useless-escape.md
This updates a `no-useless-escape` docs example to remove (what I think is) accidental escaping.
Technically both versions would be correct, but I think the updated version more clearly indicates what the rule is doing.
> Docs: fix unclear example for no-useless-escape

- conf/eslint.json
- docs/rules/prefer-destructuring.md
- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
This rule ensures that all object property access and array index accesses are done through [ES6 destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_ass …
> New: `prefer-destructuring` rule (fixes #6053)

- lib/rules/semi.js
- tests/lib/rules/semi.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7782)
This updates `semi` to detect template literals and regular expressions correctly.
This should not get reported as an error:
```js
/* eslint semi: [error, "never"] */
var foo = 1; // semicolon is required here, otherwise this would be a tagged template.
`bar`
var baz = 1; // semicolon is required here, otherwise this would be parsed as division.
/qux/
```
Previously, the rule was detecting `/` characters, but it was only looking for a single-character token with the value `'/'`, due to a bug in the logic that handles `++` and `--` tokens. The rule was not detecting `` ` `` characters at all.
**Is there …
> Fix: `semi` false positive before regex/template literals (fixes #7782)

- lib/rules/func-call-spacing.js
- tests/lib/rules/func-call-spacing.js
See #7787.
With `"func-call-spacing": ["error", "never"]`, ensure that autofixing only occurs if there are no line terminators in the spacing. This is to avoid conflicts with …
> Fix: func-call-spacing "never" doesn't fix w/ line breaks (fixes #7787)

- lib/config/config-ops.js
- lib/config/environments.js
- lib/util/source-code.js
These cases were not caught when we enabled the `prefer-arrow-callback` rule because they use `this`, but the `this`-binding is unnecessary because these functions are called with the binding of the outer scope.
> Chore: replace unnecessary function callbacks with arrow functions

- docs/developer-guide/working-with-rules.md
Documentation update
The placeholder sample on http://eslint.org/docs/developer-guide/working-with-rules is actually missing the placeholder, as it's being interpreted as a variable by the site builder:
This code snippet was correctly marked as "raw" for `working-with-rules-deprecated.md` (in #6551) but the same change wasn't applied to the non-deprecated version.
> Docs: Wrap placeholder sample in {% raw %}

- docs/developer-guide/README.md
Removed .html extensions from links in the main developer-guide page, to conform to how we write links in other documentation pages.
Not …
> Docs: Remove .html extensions from links in developer-guide

- lib/rules/consistent-return.js
- tests/lib/rules/consistent-return.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7790)
This updates `consistent-return` to avoid reporting inconsistent returns in the `constructor` function of a `ClassExpression` or `ClassDeclaration`. The rule already ignores ES5 constructor functions, but it hadn't been updated to account for ES6 constructors yet.
> Fix: consistent-return shouldn't report class constructors (fixes #7790)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7789)
']' is only allowed to be unescaped in regular expressions when the engine implements Annex B, a legacy part of the ECMA262 spec which is only normative for browsers. In engines that do not implement Annex B, regular expressions like /]/ are a syntax error. Since ESLint can't tell what engine the code will run on, it shouldn't consider escaping ] to be "useless" since it's only useless on engines that implement Annex B, and only in regular expressions that don't contain the unicode flag. (For example, the regular expression /]/u is a syntax error even on engines that implement Annex B.)
This updates …
> Fix: Relax no-useless-escape's handling of ']' in regexes (fixes #7789)

- docs/developer-guide/architecture.md
* The `cli` description stated that `bin/eslint.js` calls `process.exit()`, but this is no longer correct (this changed in 759525e1b0dffa44d8aa9f073d8f709ea4bbb794).
* The `eslint` description stated that the traverser emits events with the `:after` suffix when exiting nodes, but it actually emits events with the `:exit` suffix (this changed in f1f453d9370ca522e9765c7731e13d3c4fb75be1).
> Docs: update outdated info in Architecture page

- docs/rules/no-var.md
- lib/ast-utils.js
- lib/rules/no-unused-vars.js
- lib/rules/no-useless-return.js
- lib/rules/no-var.js
- tests/lib/ast-utils.js
- tests/lib/rules/no-var.js
* **ESLint Version:** 3.12.2
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8
default
```js
module.exports = …
```
> Fix: Disable no-var autofixer in some incorrect cases in loops

- lib/rules/no-return-await.js
- tests/lib/rules/no-return-await.js
`no-return-await`
More
```js
async function foo1() {
return (0, 1, await …
```
> Update: no-return-await with with complex `return` argument (fixes #7594)

- lib/rules/no-implied-eval.js
- tests/lib/rules/no-implied-eval.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7821)
This updates the function name matcher in `no-implied-eval` to ensure that a match like `setTimeout` matches the entire name of the function rather than a substring. This prevents the rule from reporting functions like `setTimeoutFooBar`.
> Fix: no-implied-eval false positive on 'setTimeoutFoo' (fixes #7821)

- docs/rules/operator-linebreak.md
- lib/rules/operator-linebreak.js
- tests/lib/rules/operator-linebreak.js
This adds a fixer for [`operator-linebreak`](http://eslint.org/docs/rules/operator-linebreak). The fixer modifies the whitespace around an operator to ensure that the operator is in the right place.
```js
/* eslint operator-linebreak: [error, "after"] */
foo
&& bar;
foo &&
bar;
```
The fixer can handle comments when there is a single linebreak around the operator, but it doesn't perform a fix when there is a comment and two linebreaks around the operator.
```js
/* eslint operator-linebreak: [error, "after"] */
foo // comment
&& bar;
foo && // comment
bar;
// ---
foo
&&
bar;
foo &&
bar; …
```
> Update: add fixer for `operator-linebreak`

- tests/bin/eslint.js
This adds some integration tests for ESLint's behavior relating to cache files.
Two of the tests are currently failing. This should get fixed when a new version of `flat-cache` is published. (See the discussion in https://github.com/eslint/eslint/issues/7748.)
> Chore: add integration tests for cache files (refs #7748)

- lib/rules/no-multiple-empty-lines.js
This updates `no-multiple-empty-lines` to use the `astUtils.getRangeIndexFromLocation` function to convert a line number to a range index instead of reimplementing the functionality. The current logic in the rule was implemented before `getRangeIndexFromLocation` was added.
> Chore: use ast-utils helper functions in no-multiple-empty-lines

- lib/rules/no-multiple-empty-lines.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7803)
This updates the `.reduce` function in `no-multiple-empty-lines` to avoid creating a new large array for every line in a file. 
Before:
```bash
(master)$ TIMING=1 bin/eslint.js --no-eslintrc --rule 'no-multiple-empty-lines: error' test-data.js
Rule                    | Time (ms) | Relative
:-----------------------|----------:|--------:
no-multiple-empty-lines |  1364.584 |   100.0%
```
After:
```bash
(no-multiple-empty-lines-perf)$ TIMING=1 bin/eslint.js --no-eslintrc --rule 'no-multiple-empty-lines: error' test-data.js
Rule                    | Time (ms) | Relative …
```
> Fix: no-multiple-empty-lines perf issue on large files (fixes #7803)

- lib/rules/new-parens.js
- tests/fixtures/fixture-parser.js
- tests/fixtures/parsers/typescript-parsers/new-parens.js
- tests/lib/rules/arrow-parens.js
- tests/lib/rules/new-parens.js
This is a bug fix that changes the way the new-paren rule works.
It exploits the invariant that parentheses can only be omitted if there are no arguments, and in this case, the last two tokens have to be `(` and `)`
> Adapt new-paren rule so that it can handle TypeScript

- docs/rules/capitalized-comments.md
- lib/rules/capitalized-comments.js
- tests/lib/rules/capitalized-comments.js
Only applies when `ignoreConsecutiveComments` option is enabled.
See issue #7831.
Ensure that all consecutive comments are ignored (with `ignoreConsecutiveComments: true` option), even if first …
> Fix: capitalized-comments: Ignore consec. comments if first is invalid

- docs/rules/object-property-newline.md
- lib/rules/object-property-newline.js
- tests/lib/rules/object-property-newline.js
This adds an autofixer for [`object-property-newline`](http://eslint.org/docs/rules/object-property-newline), as described in https://github.com/eslint/eslint/issues/7740.
> Update: add fixer for object-property-newline (fixes #7740)

- lib/rules/no-useless-return.js
- tests/lib/rules/no-useless-return.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7855)
This updates `no-useless-return` to avoid circular backtracking through unreachable loops.
This is similar to https://github.com/eslint/eslint/issues/7583, but it's a different issue. (There are two places in `no-useless-return` where unreachable segments are traversed, and the fix for https://github.com/eslint/eslint/issues/7583 only addressed one of the places.)
> Fix: no-useless-return stack overflow on loops after throw (fixes #7855)

- docs/rules/object-shorthand.md
- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
See https://github.com/eslint/eslint/issues/7564
This adds an `avoidExplicitReturnArrows` option to `object-shorthand`, as discussed in https://github.com/eslint/eslint/issues/7564.
~~Don't merge yet. There are still a few things left to do:~~
* Bikeshed about the option name?
* ~~Add documentation for the option~~
* ~~Wait for https://github.com/eslint/eslint/pull/7745 to get merged (this PR builds off of that commit)~~
> Update: add object-shorthand option for arrow functions (fixes #7564)

- docs/rules/no-unneeded-ternary.md
- lib/ast-utils.js
- lib/rules/no-unneeded-ternary.js
- tests/lib/ast-utils.js
- tests/lib/rules/no-unneeded-ternary.js
This adds a fixer for `no-unneeded-ternary`.
```js
var foo = bar === 1 ? true : false;
var baz = qux ? qux : boop;
var foo = bar === 1;
var baz = qux || boop;
```
This also adds a …
> Update: add fixer for `no-unneeded-ternary`

- lib/rules/prefer-const.js
- tests/lib/rules/prefer-const.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7852)
This updates `prefer-const` to autofix destructuring assignments with the `destructuring: any` option if all of the declarations in the destructuring pattern are fixable.
Previously, destructuring assignments were only fixed when the `destructuring` option was set to `all`, or when there was exactly one variable declared in the assignment. It looks like this was due to a limitation of passing `node` as a single parameter to a `report` function -- the function couldn't determine whether the other variables declared in the destructuring assignment were also fixable, so it only performed a fix if there was …
> Fix: Ensure prefer-const fixes destructuring assignments (fixes #7852)

- docs/rules/no-extra-label.md
- lib/rules/no-extra-label.js
- tests/lib/rules/no-extra-label.js
This adds a fixer for [`no-extra-label`](http://eslint.org/docs/rules/no-extra-label).
```js
A: while (true) {
break A;
}
while (true) {
break;
}
```
> Update: add fixer for no-extra-label

- lib/rules/no-extra-label.js
- tests/lib/rules/no-extra-label.js
[x] Bug fix
* **ESLint Version:** 3.13.0
* **Node Version:** 7.3.0
* **npm Version:** 3.10.10
default
(none)
```js
/* eslint no-extra-label: error */
A: while (true) {
break A;
while (true) {
break A;
}
}
```
I expected an error to be reported on line 2, and the code to be fixed to
```js
/* eslint no-extra-label: error */
A: while (true) {
break;
while (true) {
break A;
}
}
```
An error was …
> Fix: no-extra-label autofix should not remove labels used elsewhere

- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7881)
This updates `prefer-destructuring` to avoid reporting compound assignments such as `foo += bar.foo`, since these assignments can't be replaced with destructuring assignments.
> Fix: prefer-destructuring reporting compound assignments (fixes #7881)

- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7869)
This makes a few changes to `brace-style`:
* It unifies the logic for all types of braced statements into a single function. Previously, there was a lot of code duplication, which led to inconsistencies like https://github.com/eslint/eslint/issues/7869 and https://github.com/eslint/eslint/issues/7869#issuecomment-270802875.
* It changes the report type to report the curly brace token itself, rather than a node in the general vicinity. For example, the previous version of the rule would report the `IfStatement` node here:
```js
/* eslint brace-style: error */
if (foo) {
// ...lots of code
bar(); } // <-- …
```
> Update: refactor brace-style and fix inconsistencies (fixes #7869)

- lib/config/autoconfig.js
- lib/config/config-rule.js
- lib/rule-context.js
- lib/util/comment-event-generator.js
- lib/util/rule-fixer.js
- tests/lib/util/rule-fixer.js
Update constructor functions to use ES6 classes. Also, changed one constructor function (rule-fixer.js) to a plain object since it does not have any internal state. …
> Chore: update to use ES6 classes (refs #7849)

- docs/rules/no-alert.md
- lib/ast-utils.js
Fixed a few typos and improved formatting.
No.
> Fix: A few typos

- lib/ast-utils.js
- tests/lib/rules/no-multiple-empty-lines.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7893)
This fixes an issue where `astUtils.getLocationFromRangeIndex` and `astUtils.getRangeIndexFromLocation` were using a regular expression susceptible to catastrophic backtracking. The match would take quadratic time in the length of the last line of the file. Since the file in https://github.com/eslint/eslint/issues/7893 contains a 1.5 million character source map URL on the last line, rules like `no-multiple-empty-lines` would hang when using ast-utils to split the file into lines.
This issue only applies to files without trailing newlines, and is only noticable when the last line of the file contains more …
> Fix: catastrophic backtracking in astUtils linebreak regex (fixes #7893)

- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7608)
This updates `brace-style` to validate `ClassBody` nodes.
~~This builds on the changes in https://github.com/eslint/eslint/pull/7870. This PR should not be merged until https://github.com/eslint/eslint/pull/7870 is merged.~~
~~In the meantime, see the second commit of this PR for the changes that are relevant to this issue.~~
> Update: ensure brace-style validates class bodies (fixes #7608)

- docs/user-guide/configuring.md
In the eqeqeq example, the word `warning` was used
instead of `warn`
> Fix: Correct typos in configuring.md

- lib/rules/no-extra-boolean-cast.js
- tests/lib/rules/no-extra-boolean-cast.js
[X] Bug fix for #7912 
I've change autofixer in no-extra-boolean-cast rule for "Redundant Boolean call" to include brackets if the inner part is an expression.
> Fix: add parentheses in no-extra-boolean-cast autofixer (fixes #7912)

- lib/config/autoconfig.js
- tests/fixtures/autoconfig/source-with-comments.js
Fixes #7860 
I added a check during auto-config to ensure that the rule name throwing an error is in the error registry.
No, it's …
> Fix: Ignore inline plugin rule config in autoconfig (fixes #7860)

- docs/rules/no-case-declarations.md
PR for the following issue https://github.com/eslint/eslint/issues/6716
I added two examples where no-case-declarations are used correctly, one declaration outside the switch-statement and one using …
> Docs: Improve examples for no-case-declarations (fixes #6716)

- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
[x] Bug fix
* **Node Version:** 7.3.0
* **npm Version:** 3.10.10
default
(none)
```js
/* eslint no-useless-computed-key: error */
({ ['__proto__']: [] }) instanceof Array;
```
I expected no error to be reported, because using `'__proto__'` directly as the object key would set the value of `Object.getPrototypeOf(theObject)`, and the expression's value would change from `false` to `true`.
**What actually happened? Please include the actual, raw …
> Fix: no-useless-computed-key false positive with `__proto__`

- docs/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
- New option added to `no-extra-parens` rule: `ignoreJSX`, with options available:
- `"all"`: All JSX components are ignored
- `"multiline"`: Multiline JSX components are ignored
- `"single-line"`: Single line JSX components are ignored
Please review everything thoroughly, the rule was already quite complex and I am new to working with rules in ESLint.
> Update: add ignoreJSX option to no-extra-parens (Fixes #7444)

- lib/rules/func-call-spacing.js
- tests/lib/rules/func-call-spacing.js
[x] Bug fix (see #7923)
Updated a regular expression in the `func-call-spacing` rule source to match the line terminator characters `"\r"`, `"\u2028"` and `"\u2029"` along with `"\n"`. This has the effect of disallowing those characters as separators when the option `"always"` is used without `"allowNewlines"`.
Nothing that shouldn't be clear.
> Fix: func-call-spacing does not recognize all line terminators (fixes #7923)

- conf/eslint.json
- docs/rules/prefer-promise-reject-errors.md
- lib/ast-utils.js
- lib/rules/no-throw-literal.js
- lib/rules/prefer-promise-reject-errors.js
- packages/eslint-config-eslint/default.yml
- tests/lib/ast-utils.js
- tests/lib/rules/no-throw-literal.js
- tests/lib/rules/prefer-promise-reject-errors.js
[x] New rule
See https://github.com/eslint/eslint/issues/7685
This adds the `no-reject-literal` rule as discussed in https://github.com/eslint/eslint/issues/7685, and enables it in the ESLint repo for dogfooding.
Some of the logic from this rule is shared with `no-throw-literal`, so that logic has been moved out of `no-throw-literal` and into `ast-utils.js`.
I'm wondering whether we should have the rule report object expressions, e.g.
```js
Promise.reject({ foo: 1 });
```
Advantages of reporting that case:
* `{ foo: 1 }` cannot be an instance of `Error`.
Disadvantages of reporting that case:
* `{ foo: 1 }` is not …
> New: `prefer-promise-reject-errors` rule (fixes #7685)

- docs/rules/no-else-return.md
- lib/rules/no-else-return.js
- tests/lib/rules/no-else-return.js
Added a fixer for the `no-else-return` rule, updated documentation, and updated tests.
> Fixes #7863; Add fixer for no-else-return

- conf/eslint.json
- docs/rules/no-multi-assign.md
- lib/rules/no-multi-assign.js
- tests/lib/rules/no-multi-assign.js
It should disallow writing lines like `a = b = c = d;`
**What category of rule is this?** (place an "X" next to just one item)
[X] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an …
> New: New rule no-multi-assign to prevent using multiple assignments per statement

- lib/rules/no-var.js
- tests/lib/rules/no-var.js
Fixes #7950
I changed the autofix of `no-var` rule.
Currently, It have auto-fixed declarations even if the variables which are defined by the declaration is referred from TDZ. It causes new `ReferenceError`s.
This PR adds the check the variables is not referred from TDZ before auto-fixing.
As a result, the following cases gets no-fixed.
```js
var a = a;
var a = b, b = 0;
var {c = c} = {};
var {d = e, e} = {};
foo(f);
var f = 0; // is referred before this declaration.
foo(() => g)
var g = 0; // might be referred before this declaration.
``` …
> Fix: `no-var` does not fix if causes ReferenceError (fixes #7950)

- docs/rules/prefer-promise-reject-errors.md
"It is considered good practice to only *pass* instances of the built-in `Error` object *to the `reject()` function"*
Nope. Just a typo. And …
> Docs: typo in prefer-promise-reject-errors

- tests/lib/rules/no-undefined.js
[x] Other, please explain: Adding tests to `no-undefined` which weren't covered, without changing the rule's behavior. (Specifically, assignments to or redeclarations of undefined)
Added test cases for `no-undefined`
No, this should be pretty straightforward. I'm separating this out from the bugfix for #7964 because I didn't want to make the squash/merge process a hassle.
> Chore: Adding assignment/redeclaration tests to no-undefined (refs #7964)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
Check the element if its exists before exploring its properties.
nothing specific
> Fix: indent rule crash on sparse array with object (fixes #7959)

- lib/rules/no-var.js
- tests/lib/rules/no-var.js
[x] Bug fix (https://github.com/eslint/eslint/issues/7961)
This updates the `no-var` autofixer to avoid fixing variable declarations in single-line if/while/etc. statements, because `let` declarations are not allowed there.
This is not a particularly urgent fix -- the bug has existed since `no-var` became autofixable in July. If we do a patch release this week then we might as well include this fix, but I don't think this bug warrants a patch release on its own.
> Fix: no-var autofix syntax error in single-line statements (fixes #7961)

- docs/user-guide/getting-started.md
Prior context here:
https://github.com/eslint/eslint.github.io/issues/324
This PR adds a youtube embed of an ESLint Tutorial Video to the `Getting started` docs page.
@ilyavolodin I don't have strong …
> Add ESLint tutorial embed & links to `Getting started` docs page

- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/7974)
This updates `brace-style` to use node-specific checks for braces next to `catch`, `finally`, and `else` keywords. Previously, the rule would simply detect any `catch`, `finally`, or `else` keyword that followed a closing curly brace, but that had a false positive if these keywords were used as class method names.
> Fix: brace-style false positive for keyword method names (fixes #7974)

- conf/eslint.json
- docs/rules/template-tag-spacing.md
- lib/rules/template-tag-spacing.js
- tests/lib/rules/template-tag-spacing.js
[ X ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
This rule is very similiar to `func-call-spacing` in the way it will enforce spacing between [template tags](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_tem …
> New: `template-tag-spacing` rule (fixes #7631)

- docs/rules/no-use-before-define.md
- lib/rules/no-use-before-define.js
- tests/lib/rules/no-use-before-define.js
[x] Changes an existing rule (see https://github.com/eslint/eslint/issues/7111)
This adds a `variables` option to `no-use-before-define` rule. When the option is set to `false`, the rule allows variables to be used before they are defined if the declaration is in an upper scope.
I'm concerned that there might be edge-cases that I didn't account for in the tests. It would be useful to double-check the tests and double-check that there aren't any special cases where this logic will work incorrectly.
> Update: add "variables" option to no-use-before-define (fixes #7111)

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
[x] Bug fix
* **Node Version:** 7.4.0
* **npm Version:** 4.0.5
default
```yml
rules:
operator-assignment: error
parserOptions:
ecmaVersion: 7
```
```js
foo = foo ** bar;
```
I expected an error to be reported, suggesting that the code use a compound operator.
No error was reported.
This updates `operator-assignment` …
> Update: ensure operator-assignment handles exponentiation operators

- lib/rules/func-name-matching.js
- packages/eslint-config-eslint/default.yml
This enables [`no-unneeded-ternary`](http://eslint.org/docs/rules/no-unneeded-ternary) on the ESLint codebase for dogfooding.
The (one) change in this PR was made with ESLint's autofixer.
> Chore: enable no-unneeded-ternary on ESLint codebase

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
[X] Changes an existing rule ([template]
no-unused-vars
fewer
```js
var data = { type: 'coordinates', x: 0, y: 0 };
var { type, ...coordinates } = data;
console.log(coordinates);
```
Errors that `type` is unused.
`type` will be considered to be passively used. Meaning that although it is not used afterwards, it's existence effects the declaration of …
> Update: no-unused-vars to account for rest property omissions

- lib/rules/no-unused-vars.js
Fixes a linting error introduced by the merge of #7986.
Fixed the linting error.
I don't think so
> Chore: fix no-else-return lint error (refs #7986)

- lib/util/glob.js
This updates `glob.js` to avoid doing feature detection for the `Symbol` global. According to [node.green](http://node.green/), `Symbol` has existed since Node 0.12, so it's not necessary to feature-test for it.
> Chore: avoid unnecessary feature detection for Symbol

- docs/rules/brace-style.md
This updates a misleading section in the `brace-style` documentation. It looks like this section was added when the brace-style rule only supported the 1tbs option, and the section hasn't been updated since then.
> Docs: Fix misleading section in brace-style documentation

- docs/rules/object-curly-newline.md
It looks like the curly braces got turned into square brackets between the incorrect and correct code examples.
See commit message.
> Fix typo in object-curly-newline.md

- packages/eslint-config-eslint/default.yml
This enables template-tag-spacing for dogfooding. There are no existing violations with the default "never" option, and 37 existing violations with the "always" option.
> Chore: enable template-tag-spacing on ESLint codebase

- lib/rules/no-var.js
- tests/lib/rules/no-var.js
* **ESLint Version:** 3.14.1
* **Node Version:** 6.9.4
* **npm Version:** 3.8.8
- default
- nothing
```js
for (var i = 0; i < 10; ++i) {
foo(i)
}
```
```bash
$ eslint test.js --env es6 --rule no-var:error --fix --no-eslintrc --no-ignore
```
The `var` declaration is fixed then no errors.
``` …
```
> Fix: no-var should fix ForStatement.init

- lib/ast-utils.js
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
Fix bug https://github.com/eslint/eslint/issues/7978
No.
> Fix: `no-extra-parens` incorrect precedence (fixes #7978)

- lib/rules/no-undefined.js
- tests/lib/rules/no-undefined.js
[x] Bug fix
See #7964.
Fixed no-undefined to ensure that property keys (non-computed) were not incorrectly flagged. Although property keys are Identifier nodes, non-computed property keys are really strings at the end of the day.
Well, that's where we started, but then we decided to ensure that destructuring and import/export were handled correctly. In order to do that more reliably and (hopefully) ensure the rule keeps up with no syntax, I decided to refactor to use escope variables. This ended up improving performance by about 80% (at least when the rule is run on our codebase), so that's a huge win. (Identifer visitor was hit a lot, so even the performance penalty …
> Update: no-undefined handles properties/classes/modules (fixes #7964)

- lib/rules/semi-spacing.js
- tests/lib/rules/semi-spacing.js
[x] Bug fix
* **Node Version:** 7.5.0
default
```yml
rules:
semi-spacing: error
parserOptions:
sourceType: module
```
```js
import foo from 'bar' ;
export {foo} ;
```
I expected errors to be reported because there is space before the semicolons.
No errors were reported.
This updates …
> Update: ensure semi-spacing checks import/export declarations

- docs/rules/no-unused-labels.md
- lib/rules/no-unused-labels.js
- tests/lib/rules/no-unused-labels.js
This adds a fixer for [`no-unused-labels`](http://eslint.org/docs/rules/no-unused-labels).
```js
foo: while (true) {}
while (true) {}
```
> Update: add fixer for no-unused-labels

- docs/developer-guide/shareable-configs.md
There is a typo in the phrase "read from a file".
No
> Docs: fix a typo in Shareable Configs documentation

- docs/rules/generator-star-spacing.md
#8027 
In file _generator-star-spacing.md_, Made changes in an example of Options from 
`"generator-star-spacing": ["error", {"before": false, "after": true}]` 
to 
`"generator-star-spacing": …
> Docs: Change the generator-star-spacing options example (fixes #8027)

- lib/ast-utils.js
- lib/rules/brace-style.js
- lib/rules/no-lone-blocks.js
- lib/rules/no-useless-return.js
- lib/rules/no-var.js
There are currently three types of nodes that can contain a list of statements:
* `Program`
* `BlockStatement`
* `SwitchCase`
Several rules have to check for these node types, and sometimes they do it incorrectly (see https://github.com/eslint/eslint/issues/8047). This commit puts the node types in a constant in `ast-utils`.
> Chore: unify checks for statement list parents

- lib/rules/no-extra-boolean-cast.js
- tests/lib/rules/no-extra-boolean-cast.js
As outlined in #7977, autofixing is not performed when:
* `Boolean` is called with more than one argument.
* `Boolean` is called with a spread element as the first argument.
And `!Boolean()` now …
> Fix: no-extra-boolean-cast incorrect Boolean() autofixing (fixes #7977)

- lib/ast-utils.js
- lib/rules/eqeqeq.js
- tests/lib/ast-utils.js
- tests/lib/rules/eqeqeq.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/8020)
This fixes the detection of `null` literals in `eqeqeq`, to prevent it from treating unicode/sticky regexes like `null` in Node 4. When parsing values that cannot be represented in the current environment (e.g. unicode regexes in Node 4), the result is a `Literal` node with `node.value === null`. The `eqeqeq` rule assumed that any literal node with `node.value === null` is a `null` literal.
This also adds a `isNullLiteral` function to `ast-utils.js` to prevent other rules from making the same mistake.
> Update: improve null detection in eqeqeq for ES6 regexes (fixes #8020)

- lib/util/source-code.js
When generating a list of tokens and comments, the `SourceCode` constructor previously concatenated the list of tokens and the list of comments, and sorted the result. For a file with `n` tokens and `n` comments, this takes `O(nlog(n))` time. However, since the token and comment lists are already sorted, they can be merged in `O(n)` time.
The performance impact of this change is most noticeable on large files, since they have a large number of tokens. When linting [test-data.js](https://gist.github.com/mysticatea/2fca6bc8c2194f75e4808a884a1e351a) (48000 lines) with no rules enabled, this improved overall performance by about 15-20%.
**Is …
> Chore: improve performance of SourceCode constructor

- lib/util/source-code-fixer.js
- tests/lib/util/source-code-fixer.js
This PR refactors the way of autofix.
The current way is:
1. Makes the array of characters.
- This creates many string instances.
2. Applies fixes to the array with `Array#splice` in reverse.
- `Array#splice` is a `O(n)` operation, then it's repeated as many times as the number of fixes.
3. Joins the array.
The new way of this PR is:
1. Makes the fixed string by concatenation (`+=`). It concatenates "the part followed by a fix" and "the text of the fix" by turns.
As a result, the performance of autofix improved from `O(n×m)` to `O(n+m)`. (`n` is the number of characters, `m` is the number of fixes)
I measured it by [this …
> Chore: simplify and improve performance for autofix

- docs/rules/no-unused-vars.md
Added a comment about not being able to use the line comment format and a code example for correct usage of /* exported variableName */ to fix #7998. …
> Docs: Add documentation for /* exported */ (fixes #7998)

- lib/code-path-analysis/code-path-state.js
- lib/config/autoconfig.js
- lib/config/config-file.js
- lib/eslint.js
- lib/rules/capitalized-comments.js
- lib/rules/comma-spacing.js
- lib/rules/constructor-super.js
- lib/rules/default-case.js
- lib/rules/eqeqeq.js
- lib/rules/id-blacklist.js
- lib/rules/id-length.js
- lib/rules/id-match.js
- lib/rules/no-cond-assign.js
- lib/rules/no-extend-native.js
- lib/rules/no-extra-parens.js
- lib/rules/no-inner-declarations.js
- lib/rules/no-lone-blocks.js
- lib/rules/object-property-newline.js
- lib/rules/strict.js
- packages/eslint-config-eslint/default.yml
This enables operator-linebreak on the ESLint codebase, with the default configuration. All of the changes were made with ESLint's autofixer.
> Chore: enable operator-linebreak on ESLint codebase

- package.json
[X] Other, please explain: fixes #7799 
This PR fixes a failing test about absolute path on Windows.
I'm not sure why, but I confirmed #7799 is fixed if I upgrade `mock-fs`.
If anyone can explain this mechanism, I'm glad.
> Upgrade: mock-fs

- lib/testers/rule-tester.js
This PR changes the timing to define rules for tests.
Because `tests/lib/rules.js` resets rules in `beforeEach` handler, `RuleTester.define` does not work the following case.
```
$ mocha "tests/lib/rules.js" "tests/lib/rules/no-unused-vars.js" --reporter progress
```
<details><summary>Result:</summary>
```
[▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]
207 passing (888ms)
3 failing
1) no-unused-vars valid /*eslint use-every-a:1*/ var a;:
Error: undefined line 1:
Configuration for rule "use-every-a" is invalid:
Cannot read property 'meta' of undefined
at Object.validateRuleOptions …
```
> Chore: fix the timing to define rules for tests

- lib/rules/unicode-bom.js
- tests/lib/rules/unicode-bom.js
See issue [#8083](https://github.com/eslint/eslint/issues/8083)
Insert BOM at specific location using `fixer.insertTextBeforeRange()` instead before node. Because node range doesn't include comments. …
> Fix: unicode-bom fixer insert BOM in appropriate location (fixes #8083)

- lib/token-store/index.js
- lib/token-store/utils.js
- tests/lib/token-store.js
* **Node Version:** 7.3.0
* **npm Version:** 3.8.9
- default
- nothing
I traversed tokens and comments by `token = sourceCode.getTokenAfter(token, { includeComments: true })`.
```js
(function(a, /*b,*/ c){})
```
- It traverses 11 tokens.
- It traverses 10 tokens …
> Fix: `getTokenAfter` was wrong

- docs/maintainer-guide/governance.md
Adding a note about TSC meetings requiring a quorum of more than half of the TSC being present at meetings in order to vote on any agenda items.
Updated governance documentation to clarify that TSC …
> Docs: Add TSC meeting quorum requirement

- tests/lib/util/source-code.js
I changed the description for two tests covering `source-code.js`
Not really. In trying to figure out how to write a fixer for …
> Incorrect source code test text

- docs/developer-guide/working-with-rules.md
- lib/token-store/backward-token-comment-cursor.js
- lib/token-store/backward-token-cursor.js
- lib/token-store/cursor.js
- lib/token-store/cursors.js
- lib/token-store/decorative-cursor.js
- lib/token-store/filter-cursor.js
- lib/token-store/forward-token-comment-cursor.js
- lib/token-store/forward-token-cursor.js
- lib/token-store/index.js
- lib/token-store/limit-cursor.js
- lib/token-store/padded-token-cursor.js
- lib/token-store/skip-cursor.js
- lib/token-store/utils.js
- tests/lib/token-store.js
Added an options object to `sourceCode.getTokenByRangeStart()` with an `includeComments` property.
Does this implementation seem correct? The …
> Update: Add includeComments to getTokenByRangeStart (fixes #8068)

- lib/rules/no-lone-blocks.js
- tests/lib/rules/no-lone-blocks.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8047)
This updates `no-lone-blocks` to report block statements in SwitchCase nodes. As described in https://github.com/eslint/eslint/issues/8047, it does not report blocks if they are the *only* statement in SwitchCase nodes.
> Update: make no-lone-blocks report blocks in switch cases (fixes #8047)

- lib/testers/rule-tester.js
- tests/lib/rules/spaced-comment.js
- tests/lib/testers/rule-tester.js
Ensure `output` is checked when `errors` is a number in `RuleTester`.
The change revealed a couple of tests in `spaced-comments` where the output was wrong (there is no output because there is a …
> Fix: check output in RuleTester when errors is a number (fixes #7640)

- lib/rules/block-spacing.js
- lib/rules/capitalized-comments.js
- lib/rules/key-spacing.js
- lib/rules/line-comment-position.js
- lib/rules/lines-around-comment.js
- lib/rules/lines-around-directive.js
- lib/rules/max-lines.js
- lib/rules/no-unused-labels.js
- lib/rules/object-curly-newline.js
- lib/rules/operator-linebreak.js
- lib/rules/padded-blocks.js
[x] Other, please explain: Chore
Updating instances of:
*  `sourceCode.getTokenOrCommentBefore(node)` ->  `sourceCode.getTokenBefore(node, { includeComments: true })`
*  `sourceCode.getTokenOrCommentAfter(node)` -> …
> Chore: use updated token iterator methods

- lib/rules/quotes.js
- tests/lib/rules/quotes.js
[x] Bug fix
* **Node Version:** 7.5.0
default
```yml
rules:
quotes: error
parserOptions:
ecmaVersion: 6
```
I absentmindedly spammed `` ` `` while working on something else, and I ended up with something like this:
`````js
````
`````
This is a tagged template literal, where the tag is the first ``` `` ``` and the quasi is the second ``` `` ```.
I expected the first ``` `` ``` to be reported, since it can be in double …
```
> Update: fix quotes false negative for string literals as template tags

- docs/rules/key-spacing.md
Added missing quotes to the `key-spacing` option list
> Fix: Small typos

- tests/lib/rules/comma-dangle.js
- tests/lib/rules/computed-property-spacing.js
- tests/lib/rules/newline-after-var.js
Several rule test files have typos preventing output from being asserted properly. This commit fixes the typos.
These typos were discovered with the [`consistent-output`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/090091e0d36b2a739dbee736ccf732ea2c9f10ab/docs/rules/consistent-output.md) rule.
> Chore: fix output assertion typos in rule tests

- tests/lib/rules/indent.js
- tests/lib/rules/no-redeclare.js
- tests/lib/rules/no-shadow.js
- tests/lib/rules/prefer-const.js
- tests/lib/rules/sort-imports.js
Several tests for rules have invalid syntax due to redeclared lexical variables. Previously, Acorn did not raise a syntax error for this, but it will probably check this in the next release now that https://github.com/ternjs/acorn/issues/487 is fixed. This commit updates the tests to remove the invalid syntax.
> Chore: fix invalid redeclared variables in tests

- docs/rules/arrow-parens.md
> fix typo in arrow-parens.md

- lib/rules/padded-blocks.js
- lib/util/source-code-fixer.js
- tests/lib/rules/padded-blocks.js
- tests/lib/util/source-code-fixer.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8116)
The padded-blocks rule sometimes produces a fix range where the start index of the range is larger than the end index. Due to the changes in fcc38db469d987e97b668675bf7822c7c0, when source-code-fixer encountered such a range, it would output the text between the end index and the start index twice. This commit ensures that source-code-fixer behaves the same way as it previously did when it encounters an inverted fix range (it should act as if the start and end indices were equal). In the future, we should also update padded-blocks to avoid producing inverted fix ranges.
**Is there anything you'd like reviewers …
> Fix: duplicated autofix output for inverted fix ranges (fixes #8116)

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #8119 .
This PR makes `ignoreRestSiblings` option of `no-unused-vars` rule covering arguments.
> Fix: `ignoreRestSiblings` option didn't cover arguments (fixes #8119)

- docs/developer-guide/working-with-plugins.md
- lib/testers/rule-tester.js
- tests/lib/testers/rule-tester.js
Updated RuleTester to allow the use of regular expressions for matching rule messages, instead of just plain strings
Fixes #7837
> New: Allow regexes in RuleTester (fixes #7837)

- lib/rules/keyword-spacing.js
- tests/fixtures/parsers/typescript-parsers/decorator-with-class-methods.js
- tests/fixtures/parsers/typescript-parsers/decorator-with-class.js
- tests/fixtures/parsers/typescript-parsers/decorator-with-keywords-class-method.js
- tests/fixtures/parsers/typescript-parsers/decorator-with-static-class-methods.js
- tests/fixtures/parsers/typescript-parsers/keyword-with-arrow-function.js
- tests/lib/rules/keyword-spacing.js
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ X] Other, please explain:
https://github.com/eslint/eslint/issues/8110
Allow keyword-spacing rule to find the first token better by skipping over decorators, generated by typescript, and not including symbol keyword when …
> Fix: Improve keyword-spacing typescript support (fixes #8110)

- docs/rules/no-param-reassign.md
- lib/rules/no-param-reassign.js
- tests/lib/rules/no-param-reassign.js
This adds code, tests, and documentation to the `no-param-reassign` rule to implement the `ignoredPropertyAssignmentsFor` option exactly as proposed by @platinumazure in [this comment](https://github.com/eslint/eslint/issues/6505#issuecomment-269525748)).
Obviously this is very similar to #6504, but was written independently so as not to merge non-CLA'd code into the ESLint codebase. Please let me know if you have any questions or change requests, thanks!
Fix #6505
> Add option to ignore property in no-param-reassign

- docs/rules/sort-imports.md
I removed the "fixable" statement from the `sort-imports` rule, as it is not actually supported (see #6866).
Nope.
> Docs: Add details about "--fix" option for "sort-imports" rule

- lib/testers/rule-tester.js
- tests/lib/testers/rule-tester.js
[x] Bug fix (#8142)
This updates `RuleTester` to correctly handle test cases where `code` is an empty string. Previously, this would either result in a test called `[object Object]` or throw an error, depending on the version of Mocha.
This also adds tests to assert the suite/testcase names when using RuleTester.
> Fix: Make RuleTester handle empty-string cases gracefully (fixes #8142)

- docs/rules/lines-around-comment.md
Remove incorrect line stating `lines-around-comment` can disallow empty lines.
No.
> Docs: `lines-around-comment` doesn't disallow empty lines

- conf/eslint-recommended.js
- docs/rules/nonblock-statement-body-position.md
- lib/rules/nonblock-statement-body-position.js
- tests/lib/rules/nonblock-statement-body-position.js
[x] New rule (see https://github.com/eslint/eslint/issues/6067)
This implements `nonblock-body-position` as described in https://github.com/eslint/eslint/issues/6067.
I decided to make `beside` the default, because I think it's better for preventing errors like this:
```js
if (foo)
bar();
baz(); // <-- probably a bug
```
However, I would be fine with making `below` the default as specified in https://github.com/eslint/eslint/issues/6067 if others feel differently about this.
> New: nonblock-statement-body-position rule (fixes #6067)

- lib/rules/no-else-return.js
- lib/rules/no-extra-semi.js
- lib/rules/no-useless-return.js
- lib/rules/semi.js
- lib/testers/rule-tester.js
- lib/util/fix-tracker.js
- tests/fixtures/autofix/return-conflicting-fixes.expected.js
- tests/fixtures/autofix/return-conflicting-fixes.js
- tests/fixtures/autofix/semicolon-conflicting-fixes.expected.js
- tests/fixtures/autofix/semicolon-conflicting-fixes.js
- tests/lib/cli-engine.js
- tests/lib/rules/no-else-return.js
- tests/lib/rules/no-useless-return.js
- tests/lib/util/fix-tracker.js
See #7928 and #8026 for details.
As discussed in #7928, this commit modifies the `no-else-return`,
`no-useless-return`, `semi`, and `no-extra-semi` rules to generate fix commands
with a larger range …
> Fix: Add a utility to avoid autofix conflicts (fixes #7928, fixes #8026)

- lib/rules/no-use-before-define.js
* Documentation Update *
Add missing space to docs in `create` function
> Docs Add missing space to `create` in `no-use-before-define`

- lib/rules/padded-blocks.js
- tests/lib/rules/padded-blocks.js
Thi is an alternative to https://github.com/eslint/eslint/pull/8145 covering some edge cases.
Ignore the tokens and comments starting on the same line as the brace, and repeat until there is a token …
> Fix: padded-blocks autofix problems with comments

- docs/rules/lines-around-comment.md
- lib/ast-utils.js
- lib/rules/capitalized-comments.js
- lib/rules/line-comment-position.js
- lib/rules/lines-around-comment.js
- tests/lib/rules/lines-around-comment.js
`lines-around-comment`
Fewer
New default behaviour and new …
> Update: ignore eslint comments in lines-arount-comment (fixes #4345)

- lib/rules/space-unary-ops.js
- tests/lib/rules/space-unary-ops.js
* **ESLint Version:** 3.16.1
* **Node Version:** 6.9.4
* **npm Version:** 3.10.10
``` …
```
> Fix: Don't autofix `+ +a` to `++a` in space-unary-ops

- docs/rules/line-comment-position.md
- lib/rules/line-comment-position.js
- tests/lib/rules/line-comment-position.js
`line-comment-position`
The same.
New option name …
> Update: deprecate `applyDefaultPatterns` in `line-comment-position`

- tests/lib/rules/brace-style.js
- tests/lib/rules/indent.js
- tests/lib/rules/key-spacing.js
- tests/lib/rules/lines-around-comment.js
- tests/lib/rules/object-shorthand.js
- tests/lib/rules/semi.js
- tests/lib/rules/sort-imports.js
- tests/lib/rules/spaced-comment.js
- tests/lib/rules/strict.js
Add output property to tests on fixable rules. Some had no fixes and should have a `null` value, other where missing the fixed output.
I will …
> Chore: add missing `output` property to tests

- .eslintrc.yml
- lib/internal-rules/internal-no-invalid-meta.js
- lib/rules/no-invalid-regexp.js
- lib/rules/no-restricted-properties.js
- lib/rules/no-return-await.js
- lib/rules/object-shorthand.js
- lib/rules/prefer-destructuring.js
- lib/rules/yoda.js
- package.json
- tests/lib/internal-rules/internal-no-invalid-meta.js
- tests/lib/rules/prefer-destructuring.js
This adds [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) for linting some of our rules and tests.
The following rules are enabled:
* [no-deprecated-report-api](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/no-deprecated-report-api.md) prohibits the deprecated `context.report(node, message)` API. (The autofixer for this rule was used in https://github.com/eslint/eslint/pull/7763.)
* [report-message-format](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/report-message-format.md) enforces a consistent format for report …
> Chore: add eslint-plugin-eslint-plugin

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
Correct autofix when the expression has parenthesis
No
> Fix: `operator-assignment` with parenthesized expression (fixes #8190)

- lib/rules/nonblock-statement-body-position.js
- tests/lib/rules/nonblock-statement-body-position.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8202)
The nonblock-statement-body-position rule is intended to compare the *start* line of a statement with the end line of the previous token. Due to a typo, it was comparing the *end* line of the statement instead, which caused false positives for multiline statements.
> Fix: nonblock-statement-body-position multiline error (fixes #8202)

- package.json
[X] Other, please explain: fixes #8207
This PR changes the notation which requires SSH to using HTTPS.
There are environments which can not use SSH for WAN.
> Build: change mock-fs path without SSH (fixes #8207)

- lib/config/config-file.js
- tests/lib/config/config-file.js
PR https://github.com/eslint/eslint/pull/8100 modified the message when there was an error loading a plugin or config, but didn't account for other possible errors. In this case, `babel-eslint` was …
> Fix: wrong comment when module not found in config (fixes #8192)

- lib/rules/no-global-assign.js
set recommended true for no-global-assign
tried to fix issue #8215
>  set recommended true for no-global-assign

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
Fixes #8175.
This PR fixes the overlooking of `no-extra-parens` around spread operators and super classes.
```js
//✘ BAD
let a = [ ...(b) ]
let b = { ...(c) }
class A extends (B) { }
//✔ GOOD
class C extends (D,E) { } // Allow this parentheses. 
// `SequenceExpression` is not a `LeftHandSideExpression`, 
// so if the parentheses are removed then will get a syntax error.
class F extends (await G()) { } // Arrow this parentheses.
```
- The argument of spread operators is an `AssignmentExpression`. So parentheses around the argument of spread operators should be always extra.
- The super class of `ClassDeclaration`/`ClassExpression` is an `LeftHandSideExpression`. If a super class is a …
> Update: no-extra-parens overlooked spread and superClass (fixes #8175)

- lib/rules/no-extra-parens.js
Based on the discussions [here](https://github.com/eslint/eslint/pull/8209#discussion_r104966785), I renamed some of the methods in the `no-extra-parens` rule to have a more clear prefix.
See above. …
> Chore: rename no-extra-parens methods

- lib/rules/func-name-matching.js
- tests/lib/rules/func-name-matching.js
[x] Bug fix
* **Node Version:** 7.7.2
default
```yml
rules:
func-name-matching: error
parserOptions:
```
```js
({ [null]: function foo() {} })
```
I expected ESLint to not crash.
ESLint crashed.
```
Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
at isIdentifierNameES6 …
```
> Fix: func-name-matching crash on non-string literal computed keys

- lib/rules/sort-vars.js
- tests/lib/rules/sort-vars.js
[x] Bug fix
* **Node Version:** 7.7.2
default
```yml
parserOptions:
rules:
sort-vars: [error, { ignoreCase: true }]
```
```js
var {a} = 1, b;
```
I expected ESLint to not crash.
ESLint crashed.
```
Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at …
```
> Fix: sort-vars crash on mixed destructuring declarations

- lib/util/traverser.js
- tests/lib/util/traverser.js
This converts `Traverser` (our wrapper around estraverse) into an ES6 class. Since `Traverser` is not a public API, this should not be a breaking change.
This also adds tests for `Traverser` (there were no tests before).
Based on `npm run perf` numbers, this improves end-to-end performance by 4%. :tada:
Looking at the history of the `Traverser` wrapper, I see that it was introduced to fix https://github.com/eslint/eslint/issues/5476 (a bug which broke a lot of projects that used babel-eslint). I'm not sure I understand the exact circumstances that caused that bug, but we should make sure …
> Chore: convert Traverser to ES6 class (refs #7849)

- lib/rules/no-useless-escape.js
- tests/lib/rules/no-useless-escape.js
[x] Bug fix
* **Node Version:** 7.7.2
default
```yml
rules:
no-useless-escape: error
parserOptions:
```
```js
`\a```
```
I expected the `\a` to be reported as a useless escape.
No errors were reported.
This fixes a check in `no-useless-escape` for tagged template literals. …
```
> Update: fix false negative of no-useless-escape in template literal tags

- lib/formatters/stylish.js
- tests/lib/formatters/stylish.js
Use the precalculated error and warning count in stylish
Is there a reason why we weren't doing this before?
> Chore: use precalculated counts in stylish formatter

- docs/developer-guide/selectors.md
- docs/developer-guide/working-with-rules.md
- docs/rules/no-restricted-syntax.md
- lib/eslint.js
- lib/rules/no-new-func.js
- lib/rules/no-new.js
- lib/rules/no-process-exit.js
- lib/rules/no-restricted-syntax.js
- lib/rules/no-sync.js
- lib/testers/rule-tester.js
- lib/util/node-event-generator.js
- package.json
- tests/lib/code-path-analysis/code-path-analyzer.js
- tests/lib/rules/no-restricted-syntax.js
- tests/lib/util/comment-event-generator.js
- tests/lib/util/node-event-generator.js
This updates node-event-generator to allow rules to listen for selectors. It also updates the implementation of a few simple rules to use this feature.
Before traversal begins, all the selectors needed by the active rules are gathered and passed to `node-event-generator`. When a node is entered, `node-event-generator` checks whether the node matches each selector using esquery, and emits the selector if so. Since this implementation detects shallow matches for a given node rather than getting all matches in the AST for a selector, it only needs to do one AST traversal.
~~This PR is not yet complete. Remaining things to do:~~
* ~~Decide …
> New: allow rules to listen for AST selectors (fixes #5407)

- docs/rules/no-unused-expressions.md
- lib/rules/no-unused-expressions.js
- tests/lib/rules/no-unused-expressions.js
See #7632.
Added a new option `allowTemplateTags` to the `no-unused-expressions` rule. It allows tagged template literals, but not untagged template literals, to stand as ExpressionStatements without …
> Update: Add allowTaggedTemplates to no-unused-expressions (fixes #7632)

- docs/rules/no-restricted-syntax.md
The `no-restricted-syntax` docs had a reference to itself in the "Related rules" section, which I removed.
Nope.
> Docs: remove self-reference in no-restricted-syntax docs

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
* **Node Version:** 7.6.0
- default
- nothing
```
$ echo "let a = [ ...(b, c) ]" | eslint --stdin --env es6 --rule "no-extra-parens:2" --no-eslintrc --no-ignore
```
No errors.
```
<text>
1:14  error  Gratuitous parentheses around expression  no-extra-parens
✖ 1 problem (1 error, 0 warnings)
```
This PR fixes …
> Fix: false positive of no-extra-parens about spread and sequense

- tests/lib/config/config-file.js
This converts the internal StubModuleResolver resolver function into an ES6 class.
Unlike the modules described in https://github.com/eslint/eslint/issues/8231, StubModuleResolver is not exposed as part of the public API, so this is not a breaking change.
> Chore: convert StubModuleResolver in config tests to ES6 class

- lib/ignored-paths.js
- tests/fixtures/ignored-paths/.eslintignoreWithUnignoredDefaults
- tests/lib/ignored-paths.js
This is a performance improvement, but should not be a change to linting functionality.  This is similar to avoiding glob resolution within `node_modules`.  With this change, `node-glob` will not …
> Fix: Ignore hidden folders when resolving globs (fixes #8259)

- lib/code-path-analysis/code-path-analyzer.js
- lib/code-path-analysis/debug-helpers.js
- tests/fixtures/code-path-analysis/for--direct-nest.js
- tests/fixtures/code-path-analysis/for-in--direct-nest.js
- tests/fixtures/code-path-analysis/for-of--direct-nest.js
- tests/fixtures/code-path-analysis/if-3.js
- tests/fixtures/code-path-analysis/if-6.js
- tests/fixtures/code-path-analysis/logical--if-and-3.js
- tests/fixtures/code-path-analysis/logical--if-or-3.js
- tests/fixtures/code-path-analysis/while--direct-nest.js
- tests/lib/rules/constructor-super.js
Fixes #8248.
This PR fixes the broken code path about the direct nest of same kind loops.
The fix is below. Other diffs are for tests.
```diff
@@ -512,13 +512,8 @@ function processCodePathToExit(analyzer, node) {
break;
}
-    /*
-     * Skip updating the current segment to avoid creating useless segments if
-     * the node type is the same as the parent node type.
-     */
-    if (!dontForward && (!node.parent || node.type !== node.parent.type)) {
-
-        // Emits onCodePathSegmentStart events if updated.
+    // Emits onCodePathSegmentStart events if updated. …
```
> Fix: broken code path of direct nested loops (fixes #8248)

- docs/developer-guide/selectors.md
This fixes an incorrect example in the selector documentation.
~~After this is merged, I'd like to make the commit on the live site too, so that we can fix the examples on the live site before the next release.~~ (edit: this has been updated on the live site)
> Docs: fix incorrect selector examples

- tests/lib/util/node-event-generator.js
Previously, there were insufficient tests for alphabetical selector sorting in the case where selectors had equal specificity. There were also no tests for emitting a selector whose type could not be inferred while exiting the AST.
> Chore: improve test coverage for node-event-generator

- lib/rules/no-param-reassign.js
- tests/lib/rules/no-param-reassign.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8279)
This updates no-param-reassign to stop traversing up the AST if it encounters a Property node where the variable reference is part of the key.
This fix keeps the general strategy of the rule in place. However, while I haven't investigated it in depth, the rule strategy seems a bit fragile -- it reports any reference to a variable on the left side of an assignment, excluding some specific cases such as computed properties. It's possible there are more cases like this that cause false positives -- if so, we might want to rethink how this rule is implemented. …
> Fix: no-param-reassign false positive on destructuring (fixes #8279)

- lib/rules/space-before-function-paren.js
This commit refactors the space-before-function-paren rule to avoid using different variables for each option. This should make the options easier to change in the future. It also updates the rule listeners to use selectors.
> Chore: refactor space-before-function-paren rule

- lib/rules/arrow-body-style.js
- lib/rules/arrow-parens.js
- lib/rules/comma-dangle.js
- lib/rules/comma-spacing.js
- lib/rules/comma-style.js
- lib/rules/curly.js
- lib/rules/lines-around-directive.js
- lib/rules/new-parens.js
- lib/rules/no-cond-assign.js
- lib/rules/no-extra-parens.js
- lib/rules/no-extra-semi.js
- lib/rules/no-sequences.js
- lib/rules/object-curly-spacing.js
- lib/rules/semi-spacing.js
- lib/rules/semi.js
- lib/rules/space-in-parens.js
This updates core rules to use the new `ast-utils` token-classification functions rather than checking token values on their own.
> Chore: update token logic in rules to use ast-utils

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8293)
This updates the operator-assignment autofixer to handle parenthesized values correctly. The fix in 41e3d9ce08b1a7f1f97d878a439b0143d19c7084 handles cases where expressions like `x = (x + y)` are parenthesized, but it handles cases like `x = x + …
> Fix: operator-assignment autofix errors with parentheses (fixes #8293)

- tests/lib/rules/no-unexpected-multiline.js
Put the line and column location of the errors inside the error object, where they belong.
No.
> Chore: Incorrect error location properties in tests

- lib/formatters/codeframe.js
- tests/lib/formatters/codeframe.js
Chore. See below.
Updated the codeframe formatter to use the precalculated error and warning counts, just like it was done in https://github.com/eslint/eslint/pull/8251. …
> Chore: use precalculated counts in codeframe formatter

- tests/lib/config/config-initializer.js
- tests/lib/util/path-util.js
sinon started complaining noisily about using a deprecated call:
```
sinon.stub(obj, 'meth', fn) is deprecated and will be removed from the public API in a future version of sinon.
Use stub(obj, …
```
> Chore: update sinon calls to deprecated API.

- lib/rules/no-else-return.js
- tests/lib/rules/no-else-return.js
[x] Bug fix
default
```yml
rules:
no-else-return: error
```
```js
while (foo)
if (bar)
return;
else
baz();
```
I expected no error to be reported.
The rule reported an error and recommended fixing the code to
```js
while (foo)
if (bar)
return;
baz();
```
However, this code doesn't work the same way, because `baz()` …
> Fix: no-else-return false positive for ifs in single-statement position

- lib/rules/quotes.js
- tests/lib/rules/quotes.js
[x] Bug fix
default
```yml
parserOptions:
ecmaVersion: 6
rules:
quotes: [error, backtick]
```
```js
class Foo {
'bar'() {}
}
```
I expected no errors to be reported, because replacing that string with a template literal would result in a syntax error.
```
2:3  error  Strings must use backtick  quotes
``` …
> Fix: quotes false positive with backtick option in method names

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
[x] Bug fix
default
```yml
parserOptions:
ecmaVersion: 6
rules:
object-shorthand: erorr
```
```js
({ foo: (function() {}) });
```
I expected the code to be autofixed to
```js
({ foo() {} });
```
The code was autofixed to invalid syntax:
```js
({ foo() {}) });
```
The …
> Fix: object-shorthand autofix produces errors on parenthesized functions

- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
[x] Bug fix
```yml
rules:
dot-notation: error
```
```js
foo[('bar')];
```
I expected eslint to autofix the code to
```js
foo.bar;
```
eslint autofixed the code to invalid syntax:
```js
foo[.bar]
```
This commit updates the dot-notation autofixer logic to ensure that parenthesized …
> Fix: dot-notation autofix produces errors on parenthesized computed keys

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix
default
```yml
parserOptions:
ecmaVersion: 6
rules:
```
```js
for (foo of(bar));
```
I expected the code to be fixed to valid syntax:
```js
for (foo of bar);
```
The code was autofixed to invalid syntax:
```js
for (foo ofbar);
``` …
> Fix: no-extra-parens invalid autofix in for-of statements

- lib/config/config-rule.js
- tests/fixtures/config-rule/schemas.js
- tests/lib/config/config-rule.js
[x] Bug fix
```js
const ruleConfigs = require("eslint/lib/config/config-rule").createCoreRuleConfigs();
```
I expected all the configs in `ruleConfigs` to be valid.
Some of the configs were invalid. For example:
```js
console.log(ruleConfigs["id-match"]);
// => [ 2, [ 2, { properties: true } ], [ 2, { properties: false } ] ]
```
Previously, the `config-rule` logic for …
> Fix: don't generate invalid options in config-rule

- lib/rules/comma-style.js
- tests/lib/rules/comma-style.js
[x] Bug fix
default
```yml
rules:
comma-style: error
```
```js
[(foo),
,
bar]
```
I expected the code to be fixed to
```js
[(foo),,
bar]
```
The fixer produced invalid syntax:
```js
[(foo,),
bar]
```
Previously, the autofixer would produce invalid syntax if it …
> Fix: comma-style autofix produces errors on parenthesized elements

- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
[x] Bug fix
default
```yml
rules:
dot-notation: error
```
```js
1['toString']
```
I expected the autofixer to produce valid syntax:
```js
1 .toString
```
The autofixer produced invalid syntax:
```js
1.toString
```
Previously, when fixing a computed property access …
> Fix: dot-notation autofix produces invalid syntax for integer properties

- lib/eslint.js
- tests/lib/eslint.js
default
N/A
```
const eslint = require("eslint");
const config = {}; …
```
> Fix: `eslint.verify` should not mutate config argument (fixes #8329)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix
default
```yml
parserOptions:
ecmaVersion: 6
rules:
```
```js
() => ({ foo: 1 }).foo;
```
I expected no error to be reported.
An error was reported. The rule suggested fixing the code to
```js
() => { foo: 1 }.foo
```
which is invalid syntax. …
> Fix: no-extra-parens false positive with objects following arrows

- lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-implicit-coercion.js
[x] Bug fix
default
```yml
rules:
no-implicit-coercion: error
```
```js
typeof+foo
```
I expected the code to get autofixed to
```js
typeof Number(foo)
```
The code was autofixed to
```js
typeofNumber(foo)
```
Previously, the no-implicit-coercion rule would convert …
> Fix: no-implicit-coercion invalid autofix with consecutive identifiers

- lib/rules/no-useless-computed-key.js
- tests/lib/rules/no-useless-computed-key.js
[x] Bug fix
default
```yml
rules:
no-useless-computed-key: error
```
```js
({ get[0]() {} });
```
I expected the code to be autofixed to
```js
({ get 0() {} });
```
The code was autofixed to
```js
({ get0() {} });
```
Previously, the no-useless-computed-key autofixer …
> Fix: no-useless-computed-key invalid autofix for getters and setters

- lib/config/plugins.js
- package.json
- tests/lib/config/plugins.js
[x] Bug fix (https://github.com/eslint/eslint/issues/6874)
Previously, if a plugin threw an error on load, ESLint would display the "missing plugin" error message. This was confusing for plugin developers, because it would be difficult to distinguish between an installation error and a broken plugin.
This fix avoids the confusion by treating the errors as fatal and crashing with a stack trace if a plugin throws when it loads, as described in https://github.com/eslint/eslint/issues/7668#issuecomment-263148418.
> Fix: don't classify plugins that throw errors as "missing" (fixes #6874)

- docs/rules/linebreak-style.md
This commit adds a note to the linebreak-style docs about how git handles linebreaks on windows, and suggests using a `.gitattributes` file to control git's behavior.
(refs https://github.com/eslint/eslint/pull/7823)
> Docs: add note about git's linebreak handling to linebreak-style docs

- lib/rules/prefer-const.js
- tests/fixtures/parsers/babel-eslint5/destructuring-object-spread.js
- tests/lib/rules/prefer-const.js
This fixes a false-positive with `prefer-const` and the `destructuring: "all"` option. Essentially, the option was not taking into account destructurings that contained a rest operator.
The original bug-report is here: …
> Fix: prefer-const false positive with object spread (fixes #8187)

- lib/util/glob-util.js
- tests/lib/util/glob-util.js
This fixes https://github.com/eslint/eslint/issues/8362 where an empty pattern would cause eslint to run on the whole filesystem. I changed `glob-util` to make it ignore empty patterns.
**Is there …
> Fix: ignore empty path in patterns (fixes #8362)

- lib/rules/no-native-reassign.js
- lib/rules/no-negated-in-lhs.js
- lib/rules/no-unsafe-negation.js
no-unsafe-negation was added to eslint:recommended in https://github.com/eslint/eslint/pull/7467, but this is not reflected in the docs. This commit updates the docs to indicate that no-unsafe-negation is in eslint:recommended.
Similarly, no-negated-in-lhs and no-native-reassign have not been in eslint:recommended since #7467, so this commit updates the docs to indicate that.
(refs https://github.com/eslint/eslint/issues/8370)
> Docs: clarify that no-unsafe-negation is in eslint:recommended

- lib/rules/operator-assignment.js
- tests/lib/rules/operator-assignment.js
[x] Bug fix
default
```yml
rules:
operator-assignment: [error, never]
```
```js
foo *= bar + baz
```
I expected the code to be autofixed to
```js
foo = foo * (bar + baz)
```
The code was autofixed to
```js
foo = foo * bar + baz
```
Previously, the operator-assignment …
> Fix: don't modify operator precedence in operator-assignment autofixer

- docs/rules/no-restricted-syntax.md
- lib/rules/no-restricted-syntax.js
- tests/lib/rules/no-restricted-syntax.js
This PR updates the `no-restricted-syntax` rule to support custom messages, like discussed in #8298.
This is a non-breaking enhancement to the rule. …
> Update: add new schema to no-restricted-syntax (fixes #8298)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix
```yml
parserOptions:
sourceType: module
rules:
```
```js
export default (function() {}).foo;
({}).hasOwnProperty.call(foo, bar);
```
No error should be reported, because removing the parentheses would be a syntax error.
Errors were reported for both lines.
``` …
```
> Fix: no-extra-parens false positive with functions in default exports

- lib/rules/padded-blocks.js
- tests/lib/rules/padded-blocks.js
Changed defaults for `padded-blocks` to lint classes and switches with `always` and `never`.
No.
> Breaking: change defaults for padded-blocks (fixes #7879)

- lib/config/plugins.js
- tests/lib/config/plugins.js
[x] Bug fix (https://github.com/eslint/eslint/issues/6362)
This fixes the bug described in https://github.com/eslint/eslint/issues/6362. A reference to a scoped plugin in a config file now needs to include the scope in order to find the plugin.
Not really -- the existing comment in the code described the fix very well :smile:
> Breaking: disallow scoped plugin references without scope (fixes #6362)

- lib/rules/space-before-function-paren.js
- tests/lib/rules/space-before-function-paren.js
[x] Changes an existing rule (see https://github.com/eslint/eslint/issues/8267)
This updates the `asyncArrow` option for space-before-function-paren to be consistent with the other options in the rule. Previously, the user had to explicitly opt-in to async arrow function checking, for backwards compatibility.
~~This builds on the changes in https://github.com/eslint/eslint/pull/8284, so it should not be merged until https://github.com/eslint/eslint/pull/8284 is merged. (For the changes that were introduced in this PR, ignore the first commit.)~~
~~Also, this should not be merged until …
> Breaking: tweak space-before-function-paren default option (fixes #8267)

- lib/cli-engine.js
This converts CLIEngine to an ES6 class. This will not break clients that were using CLIEngine as documented, but it could break clients that are relying on undocumented behavior in CLIEngine (e.g. enumerable methods).
Also see: https://github.com/eslint/eslint/issues/8231
> Breaking: convert CLIEngine to ES6 class (refs #8231)

- Makefile.js
- conf/cli-options.js
- docs/rules/no-multi-spaces.md
- lib/config/autoconfig.js
- lib/eslint.js
- lib/rules/capitalized-comments.js
- lib/rules/id-length.js
- lib/rules/max-len.js
- lib/rules/new-parens.js
- lib/rules/newline-before-return.js
- lib/rules/no-multi-spaces.js
- lib/rules/no-unmodified-loop-condition.js
- lib/rules/prefer-arrow-callback.js
- lib/rules/valid-jsdoc.js
- lib/timing.js
- lib/util/module-resolver.js
- tests/lib/config/config-file.js
- tests/lib/config/config-initializer.js
- tests/lib/ignored-paths.js
- tests/lib/rules/no-await-in-loop.js
- tests/lib/rules/no-else-return.js
- tests/lib/rules/no-multi-spaces.js
- tests/lib/rules/no-self-assign.js
- tests/lib/rules/no-useless-return.js
This PR makes `no-multi-spaces` check for multiple spaces around inline comments (which it currently completely ignores). This change will increase the number of warnings by default. I do think this …
> Breaking: no-multi-spaces check around inline comments (fixes #7693)

- lib/eslint.js
- tests/lib/eslint.js
Also see: https://github.com/eslint/eslint/issues/8004
Previously, rules could specify an endLine and endColumn in a report. However, when a rule reported a node without explicitly giving a location, only the start location of the node was included in the final report object. This commit updates the report-handling logic to ensure that the end location of the node is also included.
This is considered a potentially-breaking change because if a rule specifies a very large node to report, the report range will be very large, which could cause a poor user experience in editor integrations (e.g. if hundreds of lines are highlighted).
**Is there …
> Breaking: infer endLine and endColumn from a reported node (fixes #8004)

- lib/token-store/index.js
- lib/util/source-code.js
This converts SourceCode to an ES6 class. This will not break clients that were using SourceCode as documented, but it could break clients that are relying on undocumented behavior in SourceCode (e.g. enumerable methods).
Also see: https://github.com/eslint/eslint/issues/8231
> Breaking: convert SourceCode to ES6 class (refs #8231)

- lib/testers/rule-tester.js
This converts RuleTester to an ES6 class. This will not break clients that were using RuleTester as documented, but it could break clients that are relying on undocumented behavior in RuleTester (e.g. enumerable methods).
Also see: https://github.com/eslint/eslint/issues/8231
> Breaking: convert RuleTester to ES6 class (refs #8231)

- lib/ignored-paths.js
- tests/fixtures/ignored-paths/.eslintignoreForDifferentCwd
- tests/lib/ignored-paths.js
https://github.com/eslint/eslint/issues/6759
These changes will cause the `ignorePath`'s directory to be used to resolve the patterns in the `ignorePath`, regardless of the `cwd`.  This matches the …
> Breaking: Resolve patterns from .eslintignore directory (fixes #6759)

- lib/rules/no-multiple-empty-lines.js
- tests/lib/rules/no-multiple-empty-lines.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8401)
Previously, no-multiple-empty-lines would crash if it tried to remove a trailing newline followed by a space from the end of a file. This commit fixes the crash.
> Fix: no-multiple-empty-lines crash on space after last \n (fixes #8401)

- lib/rules/space-unary-ops.js
- tests/lib/rules/space-unary-ops.js
[x] Bug fix
default
```yml
rules:
space-unary-ops: error
```
```js
foo.bar ++;
```
I expected an error to be reported.
No error was reported.
Previously, space-unary-ops would always evaluate the spacing between the first and second tokens of an UpdateExpression (e.g. …
> Update: fix space-unary-ops behavior with postfix UpdateExpressions

- lib/util/traverser.js
- tests/lib/util/traverser.js
Fixes #7129. Modified `estraverse.VisitorKeys` to include type annotation traversal.
Do you think these tests are adequate? I initially had a …
> Breaking: Traverse into type annotations (fixes #7129)

- docs/rules/indent.md
- lib/config/autoconfig.js
- lib/config/config-file.js
- lib/config/config-rule.js
- lib/rules/comma-spacing.js
- lib/rules/comma-style.js
- lib/rules/indent.js
- lib/rules/newline-before-return.js
- lib/rules/no-inner-declarations.js
- lib/testers/rule-tester.js
- tests/bin/eslint.js
- tests/fixtures/rules/indent/indent-invalid-fixture-1.js
- tests/fixtures/rules/indent/indent-valid-fixture-1.js
- tests/lib/cli-engine.js
- tests/lib/code-path-analysis/code-path-analyzer.js
- tests/lib/eslint.js
- tests/lib/rules/indent.js
- tests/lib/rules/no-constant-condition.js
- tests/lib/util/source-code.js
Fixes https://github.com/eslint/eslint/issues/1801, fixes https://github.com/eslint/eslint/issues/3737, fixes https://github.com/eslint/eslint/issues/3845, fixes https://github.com/eslint/eslint/issues/6007, fixes https://github.com/eslint/eslint/issues/6571, fixes https://github.com/eslint/eslint/issues/6670, fixes https://github.com/eslint/eslint/issues/6813, fixes https://github.com/eslint/eslint/issues/7242, fixes https://github.com/eslint/eslint/issues/7274, fixes https://github.com/eslint/eslint/issues/7320, fixes https://github.com/eslint/eslint/issues/7420, fixes …
> Update: rewrite `indent` (fixes #1801, #3737, #3845, #6007, ...16 more)

- lib/rules/no-multi-spaces.js
- tests/lib/rules/no-multi-spaces.js
[x] Bug fix
default
```yml
rules:
no-multi-spaces: error
```
```js
foo
<FF>  bar; // <FF> represents a form feed character
```
I expected no error to be reported because the whitespace is at the beginning of the line.
The code was autofixed to invalid syntax:
```js
foo bar;
``` …
> Fix: no-multi-spaces false positive with irregular indent whitespace

- conf/eslint-recommended.js
- docs/rules/indent-legacy.md
- lib/rules/indent-legacy.js
- tests/fixtures/rules/indent-legacy/indent-invalid-fixture-1.js
- tests/fixtures/rules/indent-legacy/indent-valid-fixture-1.js
- tests/lib/rules/indent-legacy.js
[x] New rule
The indent rewrite in https://github.com/eslint/eslint/pull/7618 will cause the indent rule to report more errors when it is merged for v4.0.0. To make the migration process easier, this commit introduces an indent-legacy rule as a snapshot of the v3.x version of the indent rule. The indent-legacy rule is immediately deprecated in favor of the indent rule.
Although this is not a breaking change, it should not be merged until 4.0.0. I've added the "do not merge" label for now.
This rule proposal was accepted in the [2017-03-16 TSC meeting](https://github.com/eslint/tsc-meetings/blob/452d118d368d1e3eedb1 …
> Update: add deprecated indent-legacy rule as v3.x indent rule snapshot

- lib/rules/indent-legacy.js
[x] Other, please explain: Chore
The master branch is now failing after merging in the `indent-legacy` rule because the new indent rule doesn't treat doubled up parentheses the same way the legacy rule did. Might be worth …
> Chore: Fix indentation errors in indent-legacy

- lib/ast-utils.js
- lib/rules/curly.js
- lib/rules/dot-notation.js
- lib/rules/no-extra-parens.js
- lib/rules/no-floating-decimal.js
- lib/rules/no-implicit-coercion.js
- lib/rules/no-useless-computed-key.js
- lib/rules/space-unary-ops.js
- tests/lib/ast-utils.js
- tests/lib/rules/dot-notation.js
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-floating-decimal.js
[x] Bug fix
default
```yml
rules:
no-floating-decimal: error
dot-notation: error
```
```js
typeof.2
foo['bar']instanceof baz
```
I expected the code to be autofixed to valid syntax.
The code was autofixed to invalid syntax.
```js
typeof0.2
foo.barinstanceof baz
``` …
> Fix: more autofix token-combining bugs

- docs/rules/space-before-function-paren.md
https://github.com/eslint/eslint/commit/7dd890db194faec55cfd0485118c1a8fdf0b076d changed the default options for the `space-before-function-paren` rule, but it did not update the docs to indicate the change. This commit updates the docs.
Fixes #8430
> Docs: update space-before-function-paren docs for 4.0 (fixes #8430)

- docs/rules/indent.md
Unlike `indent-legacy`, the rewritten `indent` rule does not have a special case for `MemberExpression` nodes that have `VariableDeclarator` parents. This commit removes that note from the docs.
> Docs: clarify new indent behavior with MemberExpressions

- lib/token-store/index.js
Previously, the TokenStore constructor cloned the list of comments because core would sometimes mutate it afterwards in order to remove shebangs. Core no longer removes shebangs from the comment list, so it's no longer necessary for TokenStore to clone it.
> Chore: avoid cloning comments array in TokenStore

- conf/eslint-recommended.js
- docs/user-guide/migrating-to-4.0.0.md
- lib/rules/array-callback-return.js
As noted in https://github.com/eslint/eslint/issues/8428, there's no way for ESLint to know that the `.map` it is warning on for `array-callback-return` is actually `Array.prototype.map`. As a …
> Breaking: Remove array-callback-return from recommended (fixes #8428)

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixes #8442.
The rule should warn the variables which are in destructuring even if those exist in non-last parameters because those can always be removed.
This is semver-minor matter since a bug fix which increases warnings.
> Update: no-unused-vars false negative about destructuring (fixes #8442)

- Makefile.js
Chore
This PR turns off caching when running tests. While this does speed multiple runs up, it can also lead to non-deterministic tests (i.e. it failed on Travis but passed locally for me!). Since …
> Chore: Do not use cache when testing

- docs/rules/comma-dangle.md
Add documentation for the comma-dangle rule that states that requiring
trailing commas in parameter lists may cause errors in pre-ES2017 code.
Update the documentation for the `functions` option in …
> Docs: State that functions option only applies in ES2017 (fixes #7809)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix
```yml
rules:
indent: error
parserOptions:
ecmaVersion: 6
```
```js
x => {}
```
I expected ESLint to not crash.
ESLint crashed.
```
TypeError: Cannot read property 'range' of null
at lodash.sortedIndexBy.token (path/to/lib/rules/indent.js:703:100)
at baseSortedIndexBy (path/to/node_modules/lodash/lodash.js:4143:15)
at …
```
> Fix: indent crash on arrow functions without parens at start of line

- docs/rules/no-unexpected-multiline.md
- lib/rules/no-unexpected-multiline.js
- tests/lib/rules/no-unexpected-multiline.js
Bug fix (https://github.com/eslint/eslint/issues/8469)
Previously, the no-unexpected-multiline docs mentioned that the division operator could prevent semicolon insertion, but it did not report an error for cases where this happens. This commit updates the rule to report an error when a multiline division operation looks like it was intended to be a regular expression with flags.
Fixes https://github.com/eslint/eslint/issues/8469
Do you have any suggestions for improving the method used to detect "confusing" division?
Also see: https://github.com/eslint/eslint/issues/8469#issuecomment-294953414
> Update: no-unexpected-multiline to flag confusing division (fixes #8469)

- lib/rules/no-confusing-arrow.js
- tests/lib/rules/no-confusing-arrow.js
[X] Add autofixing to a rule
Added a fix function to `no-confusing-arrow` which will auto wrap an arrow function body if `allowParens` is set to true.
I'm doing an early …
> Update: add fix for "no-confusing-arrow" rule

- docs/rules/object-curly-newline.md
- lib/rules/object-curly-newline.js
- tests/lib/rules/object-curly-newline.js
See https://github.com/eslint/eslint/issues/6488.
`object-curly-newline`.
Fewer.
**How will the change be implemented? (New option, new …
> Update: Add `consistent` option to `object-curly-newline` (fixes #6488)

- docs/rules/no-undefined.md
Addded no-shadow-restricted-names as a related rule to no-undefined's documentation, because some people might want to flag all shadowing of undefined (as the former does) and then not use the …
> Docs: list another related rule in no-undefined

- lib/rules/brace-style.js
- tests/lib/rules/brace-style.js
[x] Bug fix (https://github.com/eslint/eslint/issues/7621)
Previously, the brace-style autofixer would leave any existing whitespace between tokens when removing newlines. This would result in a large amount of extra whitespace on a line when fixing indented code. Users generally don't expect indentation whitespace to be preserved inline when fixing brace styling, so this commit updates the fixer to always output a single space between tokens when removing newlines.
> Fix: avoid creating extra whitespace in brace-style fixer (fixes #7621)

- lib/rules/no-self-compare.js
- tests/lib/rules/no-self-compare.js
[x] Bug fix (https://github.com/eslint/eslint/issues/7677)
Previously, the `no-self-compare` rule would only check comparisons between identifiers and did not check comparisons between more complex expressions. (I assume this is because the APIs that would allow comparing complex expressions didn't exist yet at the time the rule was implemented.) The rule is still applicable to non-literals, so this commit updates the rule to check comparisons that aren't between literals.
> Update: fix no-self-compare false negative on non-literals (fixes #7677)

- README.md
Followup to @kborchers's email on JSF adopting FOSSA for license scanning. We're currently merging in PRs for scan status into repo READMEs (i.e. webpack/webpack#4768)
Congrats on the passing license scan! In the PR is a green badge and report.
> Add license report and scan status

- package.json
Since I had espree@>=3.4.0 <3.4.2 on my system, `npm install` never updated the package. With ESLint freezing the parser options/config object, seems we are relying on 3.4.2's bugfix not to set ecmaFeatures.impliedStrict. So this dependency really should be at 3.4.2.
[x] …
> Upgrade: espree@^3.4.2

- lib/rules/max-len.js
- tests/lib/rules/max-len.js
* **ESLint Version:** 3.19.0
* **Node Version:** 6.9.3
* **npm Version:** 3.10.10
babel-eslint
```
"max-len": …
```
> Fix: max-len does not allow comments longer than code when comment length is specified

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/8438)
This updates the `indent` rule to ensure that `from` tokens are indented in `import a from 'b'` statements.
> Update: indent `from` tokens in import statements (fixes #8438)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8455)
Previously, the indent rule was inconsistent about handling cases where a multiline node had a child that followed it on the same line. This commit fixes the rule to handle these cases consistently.
For example, the rule considers the following code to be valid:
```js
// case 1
foo.bar({
ok: true
}).baz({
ok: true
});
// case 2
it(['foo'
'bar'], function() {
baz();
})
```
However, it previously considered the following cases to be invalid (it expected another two indentation levels for the last two lines):
```js
// case 1
if (
foo
) baz({
ok: true
});
// case 2
[
'foo',
'bar'].forEach(function() {
baz();
}); …
```
> Update: handle multiline parents consistently in indent (fixes #8455)

- lib/rules/no-extend-native.js
- tests/lib/rules/no-extend-native.js
See issue #8461.
Rewrote the rule to use eslint-scope references to find violations of this rule. Previously, a prototype extension would be reported if the name of the owning object was the same as …
> Update: no-extend-native checks global scope refs only (fixes #8461)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8493)
Previously, there was a bug in the indent rule where allman-style blocks with function bodies would be indented by one too many levels. This commit fixes the issue and updates the BlockStatement indentation handler to use the same logic as other lists of nodes (e.g. arrays).
> Update: check allman-style blocks correctly in indent rule (fixes #8493)

- lib/testers/rule-tester.js
- tests/lib/testers/rule-tester.js
[x] Bug fix
* **Node Version:** 7.10.0
```js
const RuleTester = require("eslint").RuleTester;
const ruleTester = new RuleTester();
ruleTester.run("foo", require("eslint/lib/rules/new-parens"), {
valid: [
{
code: "foo",
options: { ok: true } // <-- not an array
}
],
invalid: []
});
```
I expected `RuleTester` to either run to completion or give a clear error message.
`RuleTester` produced a confusing error message:
```
TypeError: …
```
> Fix: confusing RuleTester error message when options is not an array

- lib/rules/no-unexpected-multiline.js
- tests/lib/rules/no-unexpected-multiline.js
The rule should only execute if two division operators are found next to each other.
I'm not sure if this is the best solution but it works as …
> Fix: only run no-unexpected-multiline division operator if needed (fixes #8550)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8552)
This commit updates the indent rule's MemberExpression handler to avoid expecting NaN indentation when the MemberExpression option is set to "off". It also fixes a related bug with indenting MemberExpressions with parenthesized objects, and adds a few comments to clarify why particular pieces of the MemberExpression logic are necessary.
> Update: make indent MemberExpression handling more robust (fixes #8552)

- tests/fixtures/config-hierarchy/overwrite-ecmaFeatures/.eslintrc
- tests/lib/config.js
When working on 734846b1557a45eb43286c4da2bdc1e13b89d1c6, it was discovered that the regression test for https://github.com/eslint/eslint/issues/3735 was broken and always passing. The test was …
> Chore: avoid skipping test for env overrides (refs #8291)

- lib/rules/prefer-arrow-callback.js
- tests/lib/rules/prefer-arrow-callback.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8541)
Previously, the `prefer-arrow-callback` autofixer would simply replace a function expression with an arrow function. However, arrow functions have a different precedence than regular functions, so this was sometimes creating invalid syntax. This commit updates the fixer to parenthesize the arrow functions if necessary to avoid a syntax error.
> Fix: invalid syntax from prefer-arrow-callback autofixer (fixes #8541)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[X ] Bug fix (fixes #8546 )
Allow the VariableDeclarator node listener to ignore the operator as well as the initial value.
I tried to match the behavior of variable assignment but might have missed something. The following are now all valid:
```js
const aLongName 
= 1,
bLongName
= 2;
```
```js
const aLongName 
=
1,
bLongName
=
2;
```
> Fix: Indent Ignore Variable Declaration init operator (fixes #8546)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8493#issuecomment-299860602)
Previously, the logic in the `indent` for handling classes was separate from the logic for handling block statements, and there was a bug where the opening curly brace in a class was incorrectly offset from the start of the class. This commit updates the rule to use the same logic for handling block statements and class bodies.
> Update: check allman-style classes correctly in indent (fixes #8493)

- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8576)
This commit adds a missing node type check to fix the crash described in https://github.com/eslint/eslint/issues/8576.
> Fix: object-shorthand crash on some computed keys (fixes #8576)

- lib/rules/indent.js
- tests/fixtures/parsers/unknown-nodes/abstract-class-invalid.js
- tests/fixtures/parsers/unknown-nodes/abstract-class-valid.js
- tests/fixtures/parsers/unknown-nodes/functions-with-abstract-class-invalid.js
- tests/fixtures/parsers/unknown-nodes/functions-with-abstract-class-valid.js
- tests/fixtures/parsers/unknown-nodes/interface.js
- tests/fixtures/parsers/unknown-nodes/namespace-invalid.js
- tests/fixtures/parsers/unknown-nodes/namespace-valid.js
- tests/fixtures/parsers/unknown-nodes/namespace-with-functions-with-abstract-class-invalid.js
- tests/fixtures/parsers/unknown-nodes/namespace-with-functions-with-abstract-class-valid.js
- tests/fixtures/parsers/unknown-nodes/variable-declarator-type-indent-two-spaces.js
- tests/fixtures/parsers/unknown-nodes/variable-declarator-type-no-indent.js
- tests/lib/rules/indent.js
Created a new function that is run after program exit. It traverses the entire AST searching for unknown nodes. If an unknown node exists it will ignore the first token of each line within the node. If the token has a dependency, used to calculate its offset, then we find the last dependency and set it's offset to match that of the first token on its line.
This is my first attempt at a solution. There might be a cleaner one or more efficient one. I tried to keep it simple and readable. Not sure how we can …
> Fix: Ignore unknown nodes for Indent rule (fixes #8440)

- tests/lib/rules/indent.js
Since #8569 class bodies are used to indent classes. This means that Abstract Classes in typescript are now indented the same as classes. This commit updates the failing test where class indentation was not expected
> Fix: Fix failing uknown node test since #8569 indents class bodies

- lib/rules/indent.js
- tests/lib/rules/indent.js
This updates the `indent` rule to enforce reasonable defaults for JSX nodes. Previously, it always enforced that their indentation was zero, which was usually undesirable.
For some users, this might …
> Update: Use sane defaults for JSX indentation (fixes #8425)

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
Fixes #8481.
This PR improves indentation when `{flatTernaryExpressions: true}`. See also #8481.
Please check whether the usage of `offsets.increaseOffset` method is correct or not.
> Update: improve indent of `flatTernaryExpressions` (fixes #8481)

- docs/user-guide/configuring.md
Updated the documentation to remove a reference to ignoring transpiled files (coffeescript, typescript, etc.) This used to reference an example that was removed due to eslint not supporting use of …
> Docs: Remove .eslintignore reference to transpiled file filtering

- lib/rules/indent.js
- tests/lib/rules/indent.js
Variable Declaration initial value should now be indented the same way as Assignment Expressions. We ignore the equal operator token and the token after it instead of just ignoring the initial value. By ignoring both of these token we can allow for an optional indent whether the equal operator is on a new line or not. Since a parenthesis token is not part of the initial value node it needs to be ignored in case it appears on a new line. We must also match indent of the first token after the equal since it might be a parenthesis that should have the same indentation …
> Fix: Call expression consistency in variable declaration (fixes #8607)

- docs/user-guide/migrating-to-4.0.0.md
- lib/util/traverser.js
- tests/lib/util/traverser.js
This reverts commit 66af53e86ae2640981ed06b48c07cd2d7af261d5.
In light of the discussion surrounding adding a `VisitorKeys` option to `parseForESLint()` ([PR …
> Revert "Breaking: Traverse into type annotations (fixes #7129) (#8365)"

- docs/developer-guide/shareable-configs.md
Docs: Add missing documentation for scoped modules in sharable config developer-guide (refs #3136) (#4800)
Updated the documentation for sharable configurations developer guide, to add instructions …
> Docs: Add missing documentation for scoped modules in sharable config developer-guide

- lib/config.js
- package.json
- tests/lib/config.js
- tests/lib/config/config-file.js
Module user-home dependency replaced with core module os.homedir().
I had little trouble with mocking os.pathname(), can you check if is it …
> Chore: Remove dependency to user-home (fixes #8604)

- lib/config/config-ops.js
- tests/lib/config/config-ops.js
Config merge never took care of the extends that why it was overriding the array as mentioned in the issue. This has never caught because the rules for all those extended configs got picked up, it …
> Fix: Config merge to correctly account for extends (fixes #8193)

- docs/developer-guide/contributing/pull-requests.md
This updates the contribution guidelines to suggest adding new commits to a PR when changes are requested, rather than amending the original commit.
As a reviewer, adding additional commits makes it easier to tell what has changed. For example, if I suggest a very small change on a large PR, and a commit is added to address the change, I can easily look at the diff for that commit and make sure it looks okay. On the other hand, if the original commit is amended, it is harder to tell what was changed, so I might have to look through the entire PR again. 
I think the original guideline here was added before GitHub had the "squash and merge" …
> Docs: suggest pushing new commits to a PR instead of amending

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8637)
This updates the `indent` logic to correctly handle cases where the last two clauses of a ternary expression are on the same line.
> Update: fix parenthesized ternary expression indentation (fixes #8637)

- lib/config.js
- lib/file-finder.js
- tests/fixtures/config-hierarchy/root-true/parent/.eslintrc
- tests/lib/config.js
- tests/lib/file-finder.js
Relates to https://github.com/eslint/eslint/issues/8561
[X] Other, please explain: Chore to optimize how scanning for configurations work by looking for root:true earlier on in the scanning process. Earlier as in starting at the project root level and then moving up the directory structure.
**What …
> Chore: check for root:true in project sooner (fixes #8561)

- lib/rules/prefer-const.js
This code was added to work around a bug in acorn (https://github.com/ternjs/acorn/issues/487), which has since been fixed.
> Chore: remove dead code from prefer-const

- docs/rules/no-mixed-requires.md
Corrected the comment found in an example for `no-mixed-requires` doc.
Nothing.
> Docs: Correct the comment in an example for `no-mixed-requires`

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[ X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
Added a fix around supporting parens support for for-in and for-of loops which weren't giving off warnings. I updated no-extra-parens.js with supporting tests. …
> Update: Add support for parens on left side for-loops (fixes: #8393) 

- lib/rules/arrow-parens.js
- tests/lib/rules/arrow-parens.js
Update the fixer code to add space between async and the arrow function parameter when they are side by side.
> Fix: Add space between async and param on fix (fixes #8682)

- lib/rules/semi-style.js
- tests/lib/rules/semi-style.js
Ensure prevToken and nextToken are not null before checking for comments
Nothing
> Fix: Semi-Style only check for comments when tokens exist (fixes #8696)

- lib/ignored-paths.js
- tests/lib/ignored-paths.js
Per #8363 , this pr introduces caching fs reads to the ignored-paths.js file. This is to reduce the synchronous reads which would affect performance.
Per #8363 , this pr introduces caching fs reads …
> Chore: Cache fs reads in ignored-paths (fixes #8363)

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- lib/linter.js
- tests/lib/linter.js
[ x ] Add something to the core
Moved fixer code from `CLIEngine` to `Linter` API. This way it can be consumed on the web also. 
Issue link: https://github.com/eslint/eslint.github.io/issues/322 …
> Update: Add Fixer method to Linter API

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8721)
This fixes a bug where token dependencies were configured incorrectly when the "off" MemberExpression option was set, resulting in incorrect behavior for chained expressions.
> Update: fix MemberExpression indentation with "off" option (fixes #8721)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8666, https://github.com/eslint/eslint/issues/8717, https://github.com/eslint/eslint/issues/8710)
Fixes #8666, fixes #8717, fixes #8710
Previously, the logic for indenting multiline parenthesized expressions assumed that the indentation of every token in the expression other than the first was dependent on the first token. However, this assumption is not always correct. This led to bugs with multiline parenthesized expressions (#8710). Additionally, the BinaryExpression listener attempted to account for this assumption by always linking its tokens' indentation to the first token's indentation, even when it didn't …
> Update: fix multiline binary operator/parentheses indentation

- lib/config/config-initializer.js
- lib/util/npm-util.js
- tests/lib/config/config-initializer.js
- tests/lib/util/npm-util.js
Fixes #7338.
In `eslint --init`, if people select a popular style guide, it installs wrong versions of eslint and plugins.
- `airbnb` and `airbnb-base` requires ESLint 3 but it installs ESLint 4.
- `standard` requires `eslint-plugin-standard` and `eslint-plugin-node` but it does not install those plugins.
This PR improve `eslint --init`.
If people select a popular style guide, it checks the `peerDependencies` of the shareable config, then installs the correct dependencies.
To install correct versions, this PR's `eslint --init` installs all dependencies even if those …
> Fix: eslint --init installs wrong dependencies of popular styles (fixes #7338)

- templates/formatter-examples.md.ejs
This updates the autogenerated formatters page to describe how to use a formatter. Previously this could only be found in the CLI docs page, and was easy to miss.
> Docs: describe how to use formatters on the formatter demo page

- lib/cli-engine.js
- lib/code-path-analysis/code-path-state.js
- lib/config.js
- packages/eslint-config-eslint/default.yml
This enables `computed-property-spacing` on the ESLint codebase. We almost exclusively do not use spaces for computed properties, so I used the default `never` option.
No
> Chore: enable computed-property-spacing on ESLint codebase

- conf/default-config-options.js
- lib/linter.js
- tests/fixtures/parsers/throws-with-options.js
- tests/lib/linter.js
[x] Bug fix (#8744)
afbea78d4b94839ec6d59d2c98321901aeb76313 accidentally introduced a regression where parsers would get passed additional "default" options even when the user did not specify them. This updates the default parserOptions to prevent any unexpected options from getting passed to parsers. …
> Fix: don't pass default parserOptions to custom parsers (fixes #8744)

- lib/rules/indent.js
- tests/lib/rules/indent.js
* **ESLint Version:4.0.0**
* **Node Version:6.9.5**
* **npm Version:3.10.10**
default
I have a fix for errors that were being reported on multiline destructure as reported in #8729 
I Added test cases for a bug where errors were reported on indentation on multiline destructure
Not sure if my approach is correct. Any feedback is welcome.
> Fix: fix indent errors on multiline destructure

- lib/cli-engine.js
- tests/lib/cli-engine.js
* Only instantiate `fileEntryCache` class when the  `cache` flag is set inside `CLIEngine` constructor
* We were calling `file.distroy` after every file runn when the `cache: false`. Move that to …
> Chore: Only instantiate fileEntryCache when cache flage set (perf)

- docs/rules/no-trailing-spaces.md
- lib/rules/no-trailing-spaces.js
- tests/lib/rules/no-trailing-spaces.js
Adds the option `ignoreComments` to the `no-trailing-spaces` rule. In many IDEs, spaces are automatically added after the * character in multi-line comment blocks. When trying to add a blank line to your comment, you currently have to delete the trailing spaces yourself, even though they're in a comment block and don't affect anything.
```js
/* I'm leaving a comment here.
* 
* Please don't remove it! */
```
The second line has a trailing space, but in many ways that's expected; each other line begins with *[space], so it makes sense for the blank line to do so as well.
This change doesn't just modify `skipBlankLines` on an empty comment line, as theoretically you could use any symbol at the start of your comment lines. I'm not sure why you _would_, but you could.
```js
/*- Some comment …
```
> Update: Add ignoreComments option to no-trailing-spaces

- docs/rules/no-extra-parens.md
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
`no-extra-parens`
Fewer.
Option.
**Please provide some …
> Update: `enforceForArrowConditionals` to `no-extra-parens` (fixes #6196)

- docs/rules/padded-blocks.md
Remove wrong descriptions from `padded-blocks.md`.
Rule `padded-blocks` now enforces padding in class bodies and switch statements.
See: …
> Docs: Remove wrong descriptions in `padded-block` rule

- lib/config/config-cache.js
In a previous iteration of the glob config implementation, the ConfigCache class was not exported from its module. However, now it is exported. This commit removes an outdated comment that stated the opposite.
> Chore: Fix misleading comment in ConfigCache.js

- lib/rules/indent.js
This improves the comments explaining the internals of the `indent` rule. The goal is to make it less confusing to work on the rule.
Do the comments and examples make sense?
> Chore: improve comment explanation of `indent` internal functions

- lib/config.js
- lib/config/config-file.js
- tests/lib/config.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8791)
Due to a bug, an invalid Config instance was getting used when applying extensions to a `baseConfig` object. This updates the `Config` constructor to use the correct context, and to make sure the config cache exists when the `baseConfig` is evaluated.
> Fix: avoid crashing when using baseConfig with extends (fixes #8791)

- lib/config/config-cache.js
- lib/config/config-file.js
- tests/fixtures/config-file/plugins/.eslintrc2.yml
- tests/lib/config/config-file.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8792)
Config files are cached by file path to avoid needing to load the same config file twice. However, configs provided by plugins all have the same file path (the index file of the plugin). This created a bug when loading multiple configs for the same plugin where only the highest-precedence config from that plugin would be loaded. All other configs from that plugin would be considered identical by the cache, so they would all end up getting pulled from the cache as the same config.
This commit updates the caching logic to use the config full name as a cache index. This is still the file path when resolving a …
> Fix: ensure configs from a plugin are cached separately (fixes #8792)

- docs/developer-guide/working-with-plugins.md
The new section in the docs about parsers is great -- I'm glad we finally have docs for parser services. This just fixes a few minor formatting/wording issues I found while reading that section:
* Consistently use code formatting for method names
* Avoid duplicated explanations about which method gets used
* Clarify where the second argument to `parse` methods comes from
> Docs: add minor formatting improvement to paragraph about parsers

- docs/developer-guide/nodejs-api.md
- lib/linter.js
- tests/lib/linter.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8805)
Previously, `linter.verifyAndFix` would crash if no third argument was provided, because some debugging lines assumed that the argument always existed. This updates the method to make the third argument optional.
> Fix: don't require a third argument in linter.verifyAndFix (fixes #8805)

- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
[x] Bug fix
* **Node Version:** 8.1.2
* **npm Version:** 5.0.3
default
```yml
rules:
dot-notation: [error, { allowKeywords: false }]
```
```js
var let = { if() { console.log('foo') } };
let.if();
```
I expected `eslint --fix` to not break the code.
The code was autofixed to invalid syntax:
```js
var let = { if() { console.log('foo') } };
let["if"]();
```
**What …
> Fix: dot-notation autofix produces syntax errors for object called "let"

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix
* **Node Version:** 8.1.2
* **npm Version:** 5.0.3
default
```yml
rules:
```
```js
for ((let) in foo); // iterating a variable called "let" over "foo"
for ((let)[foo] in bar); // assigns to the foo property of the "let" variable in a loop
for ((let[foo]) in bar); // assigns to the foo property of the "let" variable in a loop
```
I expected `eslint --fix` to not change the behavior of the code.
**What actually …
> Fix: no-extra-parens false positives for variables called "let"

- conf/eslint-recommended.js
- docs/rules/getter-return.md
- lib/rules/getter-return.js
- tests/lib/rules/getter-return.js
fixes #8449 
[ x] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
New rule: enforces that a return statement is present in property getters.
**Example code:**
```js
/*eslint getter-return: "error"*/
// Incorrect
class MyClass {
get a() {
this.retreiveVal('a');
}
}
function MyConstructorFunction() {
Object.defineProperty(this, 'a', {
get: function () {
this.retreiveVal('a');
}
});
}
// Correct
class MyClass {
get a() {
return this.retreiveVal('a');
}
}
function MyConstructorFunction() {
Object.defineProperty(this, 'a', {
get: function () {
return this.retreiveVal('a');
}
});
}
``` …
> New rule: getter-return

- lib/rules/no-debugger.js
- tests/lib/rules/no-debugger.js
[x] Bug fix
* **Node Version:** 8.1.2
* **npm Version:** 5.0.3
default
```yml
rules:
no-debugger: error
```
```js
if (foo) debugger
```
I expected the code to be valid after running `eslint --fix`.
The code was fixed to `if (foo)`, which is invalid syntax.
This updates the `no-debugger` autofixer to not remove …
> Fix: no-debugger autofixer produced invalid syntax

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8785)
This fixes the `indent` rule's VariableDeclarator logic to correctly handle the case where a declaration has more than one declarator, but neither is on the same line as the start of the declaration.
This also updates the variable declarator …
> Update: simplify variable declarator indent handling (fixes #8785)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8790)
This fixes a bug in the `indent` rule where the arguments of a call expression were aligned offset the last token of the callee, even when the callee was parenthesized. Instead, the rule should offset from the closing paren in those cases.
> Update: fix parenthesized CallExpression indentation (fixes #8790)

- docs/rules/no-redeclare.md
See #8814 (but scroll down a bit).
Added a note to `no-redeclare` docs explaining that Node/CommonJS module scoping means "global variables" are not actually global, so the "builtinGlobals" option …
> Docs: Added note about Node/CJS scoping to no-redeclare (fixes #8814)

- docs/rules/no-extra-parens.md
See #8741.
Added note about arrow function parens being covered by `arrow-parens` instead of `no-extra-parens`. Also added `arrow-parens` to Related Rules section. …
> Docs: Clarify arrow function parens in no-extra-parens (fixes #8741)

- docs/maintainer-guide/releases.md
This updates the release documentation to describe how to use release issues to communicate releases to the team.
Is there anything important I …
> Docs: add guidelines for patch release communication (fixes #7277)

- docs/user-guide/migrating-to-4.0.0.md
> docs: add missing item: `LineComment` and `BlockComment` events will no longer be emitted during AST traversal

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- lib/linter.js
- lib/util/source-code-fixer.js
- tests/lib/util/source-code-fixer.js
Closes #8039 
The main change here is to allow the `fix` option of the CLIEngine to be either a boolean or now also a function which is given each linting message and is expected to return a boolean. …
> New: Allow passing a function as `fix` option (fixes #8039)

- Makefile.js
[x] Bug fix (fixes https://github.com/eslint/eslint.github.io/issues/363)
Since 3ec436eeed0b0271e2ed0d0cb22e4246eb15f137 was committed, the demo at http://eslint.org/demo has occasionally failed to load properly -- see https://github.com/eslint/eslint.github.io/issues/363 for more details. It appears that the issue was caused by a change to the build process in that commit which involved placing two browserified modules in the same bundle file. Based on https://github.com/eslint/eslint/pull/8465#discussion_r117091971 this was changed in order to pass the tests in karma, but the tests seem to pass without the change.
I'm not exactly sure what the root cause of the issue …
> Build: fix race condition in demo

- lib/rules/arrow-parens.js
- tests/lib/rules/arrow-parens.js
> Fix: arrow-parens fixer gets tripped up with trailing comma in args

- tests/lib/linter.js
The `linter` test suite was mistakenly still called "eslint" from when lib/linter.js was called lib/eslint.js. This renames the test suite to call it "linter" instead.
No
> Chore: fix title of linter test suite

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8832)
Previously, the `indent` rule handled JSXExpressionContainer nodes by only setting the first token's offset, incorrectly assuming that all the other tokens in the expression would be dependent on the first token. (This had been a problem since JSX support was added to the rule.) As a result of an unrelated, correct fix in b5a70b4e8c20dc1ea3e31137706fc20da339f379, the bug ended up also appearing for BinaryExpressions in JSXExpressionContainers.
This commit updates the JSXExpression logic to offset all of its inner tokens.
> Update: fix indentation of JSXExpressionContainer contents (fixes #8832)

- docs/developer-guide/working-with-rules.md
- lib/rules/comma-dangle.js
* fixes typos ($refs is used instead of $ref)
* “defs” is inconsistent with the use of “definitions” in other schemas
* uses full JSON schema format instead of array of schemas, as currently $ref inside array of schemas is unsupported
**What changes …
> Fix: correct comma-dangle JSON schema

- docs/rules/multiline-ternary.md
- lib/rules/multiline-ternary.js
- tests/lib/rules/multiline-ternary.js
See #8770 
This adds an `always-multiline` option to [`multiline-ternary`](http://eslint.org/docs/rules/multiline-ternary). This option enforces newlines between the operands of a ternary expression only if the expression spans multiple lines.
Nope.
However, I would like out point out that with the addition of this option, the name of this rule could be changed to `ternary-newline` to follow the naming convention of similar ESLint rules.
> Update: Add always-multiline option to multiline-ternary (fixes #8770)

- lib/cli.js
- tests/bin/eslint.js
- tests/fixtures/autofix-integration/left-pad-expected-quiet.js
- tests/fixtures/autofix-integration/left-pad.js
- tests/lib/cli.js
See #8675.
When `--quiet` is specified by user, lib/cli.js will pass a fix predicate function to CLIEngine so that only errors are fixed. That way, warnings (which aren't even reported in `--quiet` …
> Fix: --quiet no longer fixes warnings (fixes #8675)

- docs/rules/object-curly-newline.md
Fixes #8874
Wording "at least" copied from array-bracket-newline docs.
Documentation wording change to object-curly-newline.
The one line of …
> Docs: Fix wording of minProperties in object-curly-newline (fixes #8874)

- lib/rules/no-sync.js
- tests/lib/rules/no-sync.js
This address issues #7985 
This update lets the no-sync rule take an option parameter allowAtRootLevel: boolean that will allow sync operations at the root level.
less errors since it is making the rule more lenient.
New option
```js
//no-sync: [1, { allowAtRootLevel: true }]
// good
const contents = …
```
> Update: allow sync operation at root level (fixes: #7985)

- lib/rules/indent.js
- tests/lib/rules/indent.js
…tructuring assignment
fixes #8815 
> Fix: indent false positive with multi-line await expression.

- CONTRIBUTING.md
Replacing old URL redirect with the new JS Foundation URL
Update a URL in the Markdown contributing doc.
The URL.
> Update CLA link in Contributing docs

- docs/maintainer-guide/pullrequests.md
[x] Other, please explain: Modifying PR guidelines in maintainer guide
In the PR guide for maintainers:
* Separated human verification steps (check that commit tag is correct for issue) from bot verification steps (check that …
> Docs: Clarified PR guidelines in maintainer guide

- .travis.yml
- appveyor.yml
- Turnoff branch build on all CI
- Run docs only if the master branch is building
> Build: Turnoff CI branch build (fixes #8804)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8882)
The `indent` rule contains some logic to ensure that semicolons at the start of a line are indented correctly when using semicolon-free style. For example, in the following code the semicolon on the second line is not indented, even though it's part of the `bar()` statement.
```js
if (foo) bar()
; [1, 2, 3].map(foo)
```
Due to a bug, this logic also applied to semicolons in `EmptyStatement` nodes, resulting in an incorrect indentation for those semicolons. This commit fixes that bug.
> Update: fix indentation of EmptyStatements (fixes #8882)

- lib/rules/no-regex-spaces.js
- tests/lib/rules/no-regex-spaces.js
If the last space has a quantifer attached, that one should not be
considered.
* **ESLint Version:** latest
* **Node Version:** various
* **npm Version:** various
**What parser (default, Babel-ESLint, etc.) are …
> Fix: no-regex-spaces rule incorrectly fixes quantified spaces

- lib/rules/indent.js
The `OffsetStorage#increaseOffset` method for the `indent` rule is no longer used anywhere. This commit removes it.
No
> Chore: remove unused helper method from `indent`

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8892)
Previously, the `indent` rule would only offset the first token of an element in a list (e.g. an array). However, this was incorrect because the other tokens of the element might not depend on the indentation of the first token. For example, in a function expression, the indentation of the parens does not depend on the indentation of the `function` token. This commit updates the `indent` rule to correctly offset all of the tokens in the element.
> Update: fix indentation of nested function parameters (fixes #8892)

- docs/rules/multiline-ternary.md
The [`multiline-ternary`](http://eslint.org/docs/rules/multiline-ternary) docs had the wrong configuration in the `always-multiline` example (I copy-pasted and forgot to change it in #8841). This fixes the docs to use the right option in the example.
> Docs: Fix always-multiline example in multiline-ternary docs

- docs/developer-guide/nodejs-api.md
Not sure whether it's a docs error or API error, but `verifyAndFix` in `eslint 4.2` returns fixed code in `output` property, not in the `text`.
> Docs: fix verifyAndFix result property name

- .gitignore
- Makefile.js
- package.json
- tests/tools/eslint-fuzzer.js
- tools/eslint-fuzzer.js
- tools/fuzzer-runner.js
This commit adds a fuzzer to detect bugs in core rules. The fuzzer can detect two types of problems: crashes (where a rule throws an error given a certain syntax) and autofix errors (where an autofix results in a syntax error).
The fuzzer works by running eslint on randomly-generated code with a random config. The code is generated with [eslump](https://github.com/lydell/eslump), and the config is generated with the existing autoconfig logic.
I've been using and developing this fuzzer locally for the past few weeks. It has been immensely helpful for finding bugs in rules. (It discovered the bugs fixed by …
> Chore: add a fuzzer to detect bugs in core rules

- docs/rules/no-sync.md
[x] Documentation update (https://github.com/eslint/eslint/issues/8902)
This adds documentation for the `allowAtRootLevel` option for `no-sync`, which was added in 3767cda2f58472ed3397ac188a71262a7b111c4b.
> Docs: add description of no-sync `allowAtRootLevel` option (fixes #8902)

- lib/config/plugins.js
- tests/lib/config/plugins.js
I'm throwing an Error if the plugins set doesn't match expected input type.  This isn't a bug necessarily, but it's something I've ran into multiple times on multiple projects where I initially tried to pass in a string (with one plugin name) …
> Fix: Throw error if plugins from config is not an array.

- lib/rules/indent.js
The header of the `indent` rule says "ported from nodeca", but there isn't anything left in the rule that actually came from nodeca, so the line is probably more misleading than useful for people reading the file.
No
> Chore: update header info in `indent`

- lib/rules/indent.js
- package.json
This updates the `indent` rule to be more performant by storing information on ranges of tokens rather than performing operations on many individual tokens one-at-a-time.
This results in a *19% end-to-end performance increase (!)* according to our `npm run perf` benchmark.
<details>
<summary>End-to-end benchmark</summary>
`master` branch:
```
Single File:
CPU Speed is 3100 with multiplier 13000000
Performance Run #1:  6601.645335ms
Performance Run #2:  6537.859522ms
Performance Run #3:  6469.447266ms
Performance Run #4:  6777.504465ms
Performance Run #5:  6431.605835ms
Performance budget exceeded: 6537.859522ms (limit: 4193.548387096775ms) …
```
> Chore: improve performance of `indent` rule

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8914)
This fixes an issue where the indentation of the right-hand side of a `BinaryExpression` did not depend on the indentation of the operator. This could result in a situation where the rule would verify the absolute indentation of a node within the BinaryExpression, rather than the relative indentation from the operator.
> Update: fix BinaryExpression indentation edge case (fixes #8914)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8924)
The MemberExpression listener in `indent` contains some logic to ensure that if the object of a MemberExpression is wrapped in parentheses, the property is offset from the opening paren, not the object itself. Due to a bug, this logic also caused the property to be offset from the opening paren if the entire MemberExpression was wrapped in parentheses, raather than just the object. This commit updates the MemberExpression listener to specifically check for parentheses around the object, not the entire MemberExpression.
> Update: fix indentation of parenthesized MemberExpressions (fixes #8924)

- lib/rules/indent.js
* Get rid of an `if` statement whose condition was always true. (With this change, the `indent` rule now has 100% branch coverage.)
* Remove the `matchIndentOf` helper in favor of using `setDesiredOffset` with an offset of 0.
* Fix outdated or misleading comments
* Move some function declarations into methods on the listeners object when possible
Should I split this into separate PRs? I ended up putting these all in one PR because they would have otherwise conflicted with each other, but I'm fine with splitting them up anyway if that makes it easier to review.
> Chore: make minor improvements to `indent` internals

- docs/rules/no-restricted-globals.md
- lib/rules/no-restricted-globals.js
- tests/lib/rules/no-restricted-globals.js
See #8315.
Updated schema for `no-restricted-globals` to support custom error messages, similar to `no-restricted-syntax`.
Nothing in …
> Update: no-restricted-globals custom error messages (fixes #8315)

- tests/lib/rules/indent.js
This fixes an `indent` test that was intended to contain a `JSXExpressionContainer`, but actually contained a `BlockStatement`.
> Chore: fix misleading `indent` test

- lib/util/npm-util.js
- package.json
- tests/lib/util/npm-util.js
* **ESLint Version:** 4.2.0
* **Node Version:** 4.8.3
* **npm Version:** 3.5.2
Ran `eslint --init` and selected the Google style guide.
**What actually happened? Please include the actual, raw output from ESLint.** See above.
This ended up calling `execSync("npm i --save-dev eslint>=4.1.1")`. Because `execSync` spawns the child through a shell, this had the effect of running `npm i --save-dev eslint` with its output redirected to a new file named `=4.1.1`, leaving the wrong version in `package.json`.
$ …
> Fix: Avoid shell mangling during eslint --init

- docs/maintainer-guide/pullrequests.md
[x] Other, please explain: Maintainer guide update
Added a note to maintainer guide that core PRs require an issue.
Not really. Like my last PR to this file, the goal is …
> Docs: Clarified that core PRs require issue in maintainer guide

- docs/rules/prefer-numeric-literals.md
- lib/rules/prefer-numeric-literals.js
- tests/lib/rules/prefer-numeric-literals.js
See #8913.
The `prefer-numeric-literals` rule now warns on `Number.parseInt` invocations as well as `parseInt` invocations.
Nothing in …
> Update: prefer-numeric-literals warns Number.parseInt (fixes #8913)

- docs/rules/no-underscore-dangle.md
- lib/rules/no-underscore-dangle.js
- tests/lib/rules/no-underscore-dangle.js
#7065
When `enforceInMethodNames` is `true`, the rule checks for dangling
underscores in method names too. This includes methods of classes
and method properties of …
> Update: add enforceInMethodNames option to no-underscore-dangle (fixes #7065)

- packages/eslint-config-eslint/README.md
The badge in the `eslint-config-eslint` readme correctly links to the `eslint-config-eslint` package, but it displays the image for `eslint`. As a result, the displayed version number is incorrect (it displays the version of the latest `eslint` release, not the latest `eslint-config-eslint` release).
No
> Docs: fix badge in eslint-config-eslint readme

- lib/config/config-initializer.js
- lib/util/npm-util.js
- package.json
- tests/lib/config/config-initializer.js
[X] Bug fix : fixes #8870
This PR adds a question to confirm that people allow `eslint --init` downgrades ESLint.
<details><summary>(Click to open) In a `Yes` case:</summary>
```diff
$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb
? Do you use React? No
? What format do you want your config file to be in? JSON
Checking peerDependencies of eslint-config-airbnb-base@latest
+ ? The style guide "airbnb" requires eslint@^3.19.0. You are currently using eslint@4.2.0.
+   Do you want to downgrade? Yes
Installing eslint-config-airbnb-base@latest, eslint@^3.19.0, eslint-plugin-import@^2.2.0
+ …
```
> Update: add question to confirm downgrade (fixes #8870)

- tests/lib/rules/array-bracket-newline.js
- tests/lib/rules/array-element-newline.js
Use `output: null` to assert that a test case is not autofixed. it is detected by `eslint-plugin-eslint-plugin` rule prefer-output-null.
> Chore: Use `output: null` to assert that a test case is not autofixed.

- docs/rules/comma-dangle.md
removed a trailing comma from `comma-dangle` rule object 
trailing commas (while valid javascript) are not valid json
> trailing commas not allowed in json (package.json)

- bin/eslint.js
- tests/bin/eslint.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8964)
This updates the uncaught exception handler to avoid printing the error message twice. The error message is included in the stack, so it's not necessary to print the error message and the stack separately.
> Fix: duplicated error message if a crash occurs (fixes #8964)

- docs/developer-guide/shareable-configs.md
Make `peerDependencies` package.json snippet valid.
> Make `peerDependencies` package.json snippet valid JSON

- lib/rules/object-curly-newline.js
- tests/lib/rules/object-curly-newline.js
Avoid fixing objects containing comments proposed by @not-an-aardvark in PR #8487
> Fix: Avoid fixing objects containing comments (fixes #8484)

- docs/rules/prefer-destructuring.md
- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
[X ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
prefer-destructuring.js
This pr is in reference to the issue #7886 
less warnings since you have more flexibility to control destructuring errors.
The first parameter of destructuring has been updated to also take a VariableDeclarator value or an AssignmentExpression value. Each value takes an object that takes an object of optional keys array and/or object.
The old parameters of  {object: Boolean, array: Boolean} is still supported
**Please provide some example code that …
> Update: support more options in prefer-destructuring

- lib/testers/rule-tester.js
This fixes a misleading comment in the `RuleTester` source file. The `RuleTester` API exposes a `run` method, not an `add` method.
No
> Chore: fix misleading comment in RuleTester

- lib/config/config-file.js
- lib/config/config-validator.js
- tests/fixtures/config-file/invalid/invalid-top-level-property.yml
- tests/lib/config/config-file.js
- tests/lib/config/config-validator.js
- tests/lib/testers/rule-tester.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8963)
Previously, if an ESLint configuration was invalid, the error message would not contain the filename of the offending config. Instead, the error message contained `[object Object]`, which was probably a bug. This commit updates the error message to clearly indicate which config file contains the error.
> Fix: include name of invalid config in validation messages (fixes #8963)

- conf/config-schema.js
- lib/config/config-validator.js
- tests/bin/eslint.js
- tests/fixtures/config-file/ecma-features/.eslintrc.yml
(refs https://github.com/eslint/tsc-meetings/issues/51#issuecomment-315669556)
Starting in 4.0.0, ESLint has been throwing a fatal error when encountering unexpected config file properties, including `ecmaFeatures`. However, many old configs still have the top-level `ecmaFeatures` option, which has had no effect since ESLint 1.x. This commit updates ESLint to emit a warning when it encounters a config with `ecmaFeatures`, rather than throwing an error.
This was approved by the TSC in [today's meeting](https://github.com/eslint/tsc-meetings/blob/4a238489c2f035711070e8beaa2ba11827bcc521/notes/2017/2017-07-20.md#stop-throwing-for-ecmafeatures) …
> Update: emit a warning for ecmaFeatures rather than throwing an error

- Makefile.js
- lib/config/config-file.js
- lib/config/plugins.js
- lib/linter.js
- lib/rules/no-multi-spaces.js
- lib/rules/space-infix-ops.js
- packages/eslint-config-eslint/default.yml
This updates eslint-config-eslint to disallow String#substr and String#substring in favor of String#slice.
> Chore: disallow .substr and .substring in favor of .slice

- lib/linter.js
- tests/lib/linter.js
[x] Bug fix
* **Node Version:** 8.2.1
default
```yml
rules:
nonexistent-rule: error
```
```js
foo;
bar;
baz;
qux;
```
I expected an error to be reported at the top of the file due to the nonexistent rule.
An error was reported, spanning the entire file.
<details>
<summary>Output of JSON formatter</summary>
```json …
```
> Fix: avoid reporting the entire AST for missing rules

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8989)
This removes an incorrect exception in the `indent` rule for computed `Property` nodes.
> Fix: inconsistent `indent` behavior on computed properties (fixes #8989)

- lib/rule-context.js
- tests/lib/cli-engine.js
- tests/lib/linter.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8980)
This refactors `RuleContext` and updates it to simply pass report locations directly to `Linter`, rather than modifying them beforehand. `Linter` already contains all the necessary functionality for handling locations, so it's not necessary to duplicate any logic in `RuleContext`. The duplication caused a bug where `Linter` was modified and `RuleContext` was not.
> Fix: refactor RuleContext to not modify report locations (fixes #8980)

- lib/rules/no-multi-spaces.js
- tests/lib/rules/no-multi-spaces.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9001)
This refactors the `no-multi-spaces` rule to compare spacing between tokens, rather than matching a regex against the source text. This prevents performance issues resulting from quadratic-time regex matching (https://github.com/eslint/eslint/issues/9001). This also allows the rule to be simpler because by only evaluating spacing between tokens, it no longer needs to specifically exclude spacing in comments.
> Fix: refactor no-multi-spaces to avoid regex backtracking (fixes #9001)

- conf/eslint-recommended.js
- lib/config/config-file.js
- lib/testers/rule-tester.js
- tests/lib/config.js
- tests/lib/config/config-file.js
- tests/lib/util/source-code.js
This removes or decreases the scope of some unneeded `eslint-disable` comments in the codebase.
> Chore: remove unnecessary eslint-disable comments in codebase

- lib/rules/padding-line-between-statements.js
- tests/lib/rules/padding-line-between-statements.js
* **ESLint Version:** v4.0.0
* **Node Version:** v8.1.0
* **npm Version:** 5.0.3
babel-eslint
```yaml
--- …
```
> Fix: Add lastToken check at padding-line-between-statements

- lib/rules/indent.js
- tests/fixtures/parsers/babel-eslint7/array-pattern-with-annotation.js
- tests/fixtures/parsers/babel-eslint7/object-pattern-with-annotation.js
- tests/fixtures/parsers/babel-eslint7/object-pattern-with-object-annotation.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/8990)
This updates the `indent` rule to select tokens in destructuring patterns more precisely, which makes it more robust when handling custom syntax.
As a separate note, I think we should really address https://github.com/eslint/eslint/issues/8991 soon -- having to copy-paste ASTs when dealing with custom parsers is kind of tedious.
> Update: make indent handle custom syntax more reliably (fixes #8990)

- bin/eslint.js
- tests/bin/eslint.js
- tests/fixtures/bin/.eslintrc.yml
[ X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
default
eslint: v4.3.0
node: v8.2.1
npm: 3.10.10
Add back err.message to bin/eslint
It provides clearer error messaging. It undoes changes [here](https://github.com/eslint/eslint/commit/a5fd1011bd4bd9ea119d70c1d980816f96672f97) to reduce duplicate error messaging in err.message and err.stack
> Fix: Add error mssg in bin/eslint (fixes #9011)

- lib/rules/getter-return.js
- tests/lib/rules/getter-return.js
fixes #8919 https://github.com/eslint/eslint/issues/8919#issuecomment-315467793
the currently fix is not decent. I think there should be an easier way to check the AST node structure that I didn't know (like selector).
> Fix: getter-return marking method named 'get' as an issue (fixes #8919)

- docs/rules/no-mixed-operators.md
Rewrote some of the descriptions for the no-mixed-operators Options section.
The original description for the `allowSamePrecedence` option …
> Docs: clarify options descriptions (fixes #8875)

- lib/rules/id-blacklist.js
- lib/rules/id-match.js
- lib/rules/no-cond-assign.js
- lib/rules/no-inner-declarations.js
- lib/rules/no-restricted-properties.js
- lib/rules/no-tabs.js
- lib/rules/prefer-reflect.js
- lib/rules/valid-jsdoc.js
- packages/eslint-config-eslint/default.yml
- tests/lib/cli-engine.js
- tests/lib/linter.js
- tests/lib/rules/brace-style.js
- tests/lib/rules/dot-notation.js
- tests/lib/rules/id-length.js
- tests/lib/rules/new-parens.js
- tests/lib/rules/no-catch-shadow.js
- tests/lib/rules/no-continue.js
- tests/lib/rules/no-else-return.js
- tests/lib/rules/no-extra-bind.js
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-implicit-coercion.js
- tests/lib/rules/no-lone-blocks.js
- tests/lib/rules/no-restricted-imports.js
- tests/lib/rules/no-shadow-restricted-names.js
- tests/lib/rules/sort-vars.js
- tests/lib/rules/space-before-function-paren.js
- tests/lib/rules/use-isnan.js
- tests/lib/testers/rule-tester.js
enalbe object-curly-newline.(fixes #9042)
Personally I see the fixed code looks a little strange:
```js
context.report({
node, message, data: {
name: node.name
}
});
```
any thoughts?
> Chore: enable object-curly-newline & object-property-newline.(fixes #9042)

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
Add an option to `indent`.
Fewer.
Expose a new object …
> Update: Add ImportDeclaration option to indent rule

- docs/developer-guide/working-with-plugins.md
- lib/rules/arrow-parens.js
- lib/rules/curly.js
- lib/rules/key-spacing.js
- lib/rules/no-else-return.js
- lib/rules/no-regex-spaces.js
- lib/rules/object-curly-spacing.js
- lib/rules/padded-blocks.js
- lib/rules/prefer-template.js
- lib/rules/spaced-comment.js
- lib/testers/test-parser.js
- tests/lib/rules/_set-default-parser.js
Fixes #8956.
This PR updates the document "Working with Custom Parsers" to clarify the specification of AST.
Also, this PR fixes 8 rules which are violating the spec.
It's hard that we catch the violations in review since `start` and `end` properties are legal on Location objects. So I added the custom parser which removes the properties from the result of `espree`. Tests of core rules use the custom parser by default. This does not affect to plugin developers.
- Please correct my …
> Fix: clarify AST and don't use `node.start`/`node.end` (fixes #8956)

- lib/rules/no-multi-spaces.js
- tests/lib/rules/no-multi-spaces.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9079)
An unintended side-effect of the refactor in 0f9727902fce753c87f45d439c521c93850d7dd8 caused `no-multi-spaces` to start reporting any consecutive whitespace characters between tokens, rather than just reporting consecutive spaces. This commit fixes the rule to only report consecutive spaces.
To be honest, reporting any consecutive whitespace seems like it would also be a reasonable behavior -- I'm not really convinced that it's better for the rule to only report spaces. But that would be a semver-major change.
> Fix: no-multi-spaces to avoid reporting consecutive tabs (fixes #9079)

- templates/blogpost.md.ejs
Remove an extra space character in the blogpost template. It doesn't actually get rendered on the website, but does exist in markdown files.
Example: …
> Chore: Remove extra space in blogpost template

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9083)
This fixes an issue where the `indent` rule would sometimes expect "NaN spaces" of indentation when an `"off"` option was used. The value `"off"` was incorrectly getting used as a numeric offset, so it was cast to a number, resulting in `NaN`.
> Update: avoid requiring NaN spaces of indentation (fixes #9083)

- docs/maintainer-guide/governance.md
From [last month's TSC meeting](https://github.com/eslint/tsc-meetings/blob/4a238489c2f035711070e8beaa2ba11827bcc521/notes/2017/2017-07-06.md#difficulty-of-reaching-quorum), the TSC started using a calendar invite for meetings. When TSC members are added in the future, we should remember to add them to the calendar invite. This commit updates the guidelines for adding TSC members to include that reminder. 
> Docs: update instructions for adding TSC members

- lib/linter.js
- tests/lib/linter.js
[x] Bug fix
* **Node Version:** 8.3.0
N/A
N/A
```js
const eslint = require("eslint");
const linter = new eslint.Linter();
linter.verifyAndFix("foo", { rules: { semi: 2 } }, { fix: false });
```
I expected no autofixes to be applied. The `fix` property specifies a filter function for fixes, and can also be set to a boolean (where `true` implies that all problems are fixed, and `false` implies that no problems are fixed). …
> Fix: don't autofix with linter.verifyAndFix when `fix: false` is used

- lib/formatters/junit.js
- tests/lib/formatters/junit.js
[X] Bug fix https://github.com/eslint/eslint/issues/9093
Currently when a file has no errors there isn't an entry in the junit results. This breaks some junit parsers as they expect at least one result. It also provides more data since now you know how many files have actually been parsed.
> Update: Include files with no messages in junit results (#9093)

- Makefile.js
- lib/formatters/stylish.js
- package.json
- tests/lib/formatters/codeframe.js
Update `chalk` to the latest _major_ 2.x branch from 1.x
• Release notes: https://github.com/chalk/chalk/releases/tag/v2.0.0
• Changelog for chalk 1.1.3 to 2.0.0 changes …
> chore: Update `chalk` to 2.x release

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix
* **Node Version:** 8.4.0
default
```yml
rules:
indent: error
```
```js
foo
.bar;
new
.target;
}
```
I expected no errors to be reported.
```
<text>
6:1  error  Expected indentation of 4 spaces but found 8  indent
✖ 1 problem (1 error, 0 warnings)
1 error, 0 warnings potentially fixable with the `--fix` option. …
```
> Update: fix indentation of multiline `new.target` expressions

- docs/rules/indent.md
- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Changes an existing rule (https://github.com/eslint/eslint/issues/8594)
This adds an option to the `indent` rule to allow the indentation checking for an arbitrary node type to be ignored, as described in https://github.com/eslint/eslint/issues/8594. This should make it easier for users to use the `indent` rule even if they think a different indentation should be enforced for a particular node type.
> Update: allow arbitrary nodes to be ignored in `indent` (fixes #8594)

- lib/ast-utils.js
- lib/config.js
- lib/ignored-paths.js
- lib/linter.js
- tests/lib/cli.js
- tests/lib/config.js
- tests/lib/linter.js
- tests/lib/rule-context.js
This adds some tests for code in `lib/*.js` that wasn't previously covered, and removes some code which is now unreachable.
> Chore: improve coverage in lib/*.js

- lib/rules/no-extra-parens.js
This updates `no-extra-parens` to avoid unnecessarily complex `forEach` calls.
I'm not sure why it was done like this before. My guess is that someone got confused and thought `node.arguments` was an [`arguments` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) (so it wouldn't have a `forEach` method, which would make the `[].forEach.call` workaround necessary), even though it's actually just a regular array.
> Chore: avoid unnecessarily complex forEach calls in no-extra-parens

- Makefile.js
To add metadata to the rule docs, specifying the edit link for the rules
I added an `edit_link` key to the YAML front matter of the generated website docs. Additionally, I added progress logging to the `npm run gendocs` script.
Note: this is a dependency of eslint/eslint.github.io#367.
> Build: Edit link in rule docs

- lib/ast-utils.js
- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9140)
This updates `no-extra-parens` to handle IIFEs more consistently by doing an IIFE check as part of the `report` call, rather than overloading the precedence calculation with special logic for IIFEs.
The bug occurred because the rule was assuming that the precedence calculation would always return -1 for an IIFE, preventing it from ever being reported (since any surrounding parens would always be considered necessary). However, the `ReturnStatement` listener doesn't check the precedence of its argument (since it correctly assumes that `return` statements have the lowest precedence), so it incorrectly caused the …
> Fix: no-extra-parens reported some parenthesized IIFEs (fixes #9140)

- lib/testers/rule-tester.js
This updates `RuleTester` to use the public `Linter#defineRule` API rather than the private `Linter#on` API.
> Chore: avoid using internal Linter APIs in RuleTester (refs #9161)

- tests/lib/util/source-code.js
This updates the tests for `SourceCode` to use the public `Linter#defineRule` API rather than the private `Linter#on` API.
> Chore: avoid using private Linter APIs in SourceCode tests (refs #9161)

- tests/lib/linter.js
This updates the tests for `Linter` to use the public `Linter#defineRule` API rather than the private `Linter#on` API.
> Chore: avoid using private Linter APIs in Linter tests (refs #9161)

- lib/linter.js
- lib/testers/rule-tester.js
- lib/util/source-code-fixer.js
- tests/lib/util/source-code-fixer.js
- tools/eslint-fuzzer.js
This updates `SourceCodeFixer` to operate on a string containing the source text, rather than a `SourceCode` instance. This removes the need for `Linter` to retain a reference to a given `SourceCode` instance after calling `verify`. (This change was also included as part of https://github.com/eslint/eslint/pull/9090, but it's probably better to separate it.)
> Chore: Make SourceCodeFixer accept text instead of a SourceCode instance

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9157)
This updates `indent` to add a missing null check for sparse arrays when using the `ArrayExpression: "off"` option.
> Fix: indent crash on sparse arrays with "off" option (fixes #9157)

- docs/developer-guide/nodejs-api.md
This adds documentation for the new APIs that were added in https://github.com/eslint/eslint/issues/6525, as well as a few other `Linter` methods that are undocumented.
The other methods on `Linter.prototype` (`reset`, `report`, `getSourceCode`, `getAncestors`, `getScope`, `markVariableAsUsed`, `getFilename`, `defaults`, `getDeclaredVariables`, the external methods [here](https://github.com/eslint/eslint/blob/ffa021e7696b24722cbbef306d494dd64d7b5215/lib/linter.js#L1256-L1277), and the methods on `EventEmitter.prototype`) are not intended to be used by Node.js API users, and are only exposed incidentally, so I didn't document them. Eventually …
> Docs: add documentation for Linter methods (refs #6525)

- tests/lib/ast-utils.js
This updates the tests for `ast-utils` to use the public `Linter#defineRule` API rather than the private `Linter#on` API.
> Chore: avoid using private Linter APIs in astUtils tests (refs #9161)

- lib/linter.js
This updates `Linter` to not be a subclass of `EventEmitter`. The reasoning for this is described in https://github.com/eslint/eslint/issues/9161.
None of the inherited `EventEmitter` methods are considered part of the public API, but a lot of tests were using them. As a result, this PR is blocked on ~~#9172~~, ~~#9173~~, ~~#9174~~, and ~~#9175~~, which fix the tests to only use the public API. After those are merged, the tests in this PR will pass.
> Chore: don't make Linter a subclass of EventEmitter (refs #9161)

- lib/linter.js
This refactors the private `parse` function in `linter.js` to be a pure function. Instead of adding an error to a provided `messages` array, it now returns an object with a boolean `success` property. It also handles extracting `parserServices` when `parseForESLint` is used, which simplifies the logic in the `Linter#verify` method a bit.
> Chore: make parse() a pure function in Linter (refs #9161)

- lib/config/config-initializer.js
- lib/util/npm-util.js
- tests/lib/util/npm-util.js
Fix init command crashing on machines that don't have npm installed #9102 .
Modify `fetchPeerDependencies()` function in npm-util to retun null if the npm process exited with an `ENOENT` error. …
> Fix: Handle error when running init without npm

- lib/linter.js
The `currentScopes` property is undocumented, and is redundant with the `scopeManager` property. This commit removes it.
> Chore: remove currentScopes property from Linter instances (refs #9161)

- docs/rules/generator-star-spacing.md
- lib/rules/generator-star-spacing.js
- tests/lib/rules/generator-star-spacing.js
https://github.com/eslint/eslint/issues/8918
Added configurability to generator star spacing.
Users of the rule will now be able to override the behavior of this rule per method type.
The types of …
> Update: Add configurability to generator star spacing

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
This is a WIP and is just providing an implementation of tests to ensure the cases are satisfactory before updating the rule.
no-unused-vars …
> no-unused-vars: Improve error messages to include the allowed patterns

- lib/report-translator.js
This updates the helper functions in `report-translator` to avoid mutating their argument.
Previously, these helper functions were designed to mutate their argument to avoid repeatedly copying properties. However, if the helper functions only return the data that they relate to (e.g. the `message` property) rather than returning an entire descriptor, it's not necessary to copy any properties.
> Chore: avoid mutating report descriptors in report-translator

- docs/rules/prefer-arrow-callback.md
- lib/rules/prefer-arrow-callback.js
For this PR (My FIRST PR btw... so go easy on me!), I did a re-write of the documentation   
for the "prefer-arrow-callback" rule. per issue 8950, I only worked on the `allowUnboundThis` option …
> Docs: Completely re-write allowUnboundThis option (fixes #8950)

- lib/linter.js
- tests/lib/linter.js
[x] Bug fix
* **Node Version:** 8.4.0
N/A
N/A
```js
const eslint = require("eslint");
const linter = new eslint.Linter();
linter.defineRule("checker", context => ({
Program() {
context.report({ loc: { line: 1, column: 0 }, message: "foo" });
}
}));
linter.verify(" /* eslint-disable */", { rules: { checker: "error" } });
```
I expected an error to be reported, because the report location is before the start of the …
> Fix: off-by-one error in eslint-disable comment checking

- lib/linter.js
- tests/lib/linter.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9193)
This provides a fix for https://github.com/eslint/eslint/issues/9193 so that libraries like `eslint-plugin-eslint-comments` will still work.
Rather than reverting https://github.com/eslint/eslint/commit/d672aef42b2950c710d598cb970d630f49b2be4b and https://github.com/eslint/eslint/commit/1be5634efe6bedb6f5d9dab5b431fc8eed2f62be, this tries to provide the minimum possible legacy behavior to make `eslint-plugin-eslint-comments` and `eslint-plugin-github` work, without giving rules full access to the `linter` instance again.
> Fix: avoid breaking eslint-plugin-eslint-comments (fixes #9193)

- lib/linter.js
This updates the `parseJsonConfig` function in `Linter` to return a result object rather than pushing problems to a provided list of messages. The goal of this change is to give the `verify` method sole control of the `messages` array. This will make the code easier to follow (since the array won't be mutated from a distance), and it will also allow the array to be replaced with a local variable rather than an instance property.
(refs #9161)
> Chore: Make parseJsonConfig() a pure function in Linter

- Makefile.js
- conf/eslint-recommended.js
- docs/rules/function-paren-newline.md
- lib/code-path-analysis/code-path-analyzer.js
- lib/code-path-analysis/code-path-segment.js
- lib/code-path-analysis/code-path-state.js
- lib/code-path-analysis/code-path.js
- lib/code-path-analysis/fork-context.js
- lib/linter.js
- lib/rules/function-paren-newline.js
- lib/rules/indent-legacy.js
- lib/rules/no-invalid-this.js
- lib/timing.js
- lib/util/fix-tracker.js
- packages/eslint-config-eslint/default.yml
- tests/lib/config.js
- tests/lib/config/config-validator.js
- tests/lib/ignored-paths.js
- tests/lib/report-translator.js
- tests/lib/rules/function-paren-newline.js
- tests/lib/util/source-code.js
[x] New rule (see https://github.com/eslint/eslint/issues/6074)
This implements the `function-paren-newline` rule as described in https://github.com/eslint/eslint/issues/6074, and enables it on the ESLint codebase for dogfooding. The rule applies to all function parameters, as well as `CallExpression`/`NewExpression` arguments.
I decided to use `multiline` as the default, instead of `always` as described in https://github.com/eslint/eslint/issues/6074, because `always` seems like a very unusual style.
* I'm unsure of the correct behavior for the `multiline` option. There are two possible behaviors that I can think …
> New: function-paren-newline rule (fixes #6074)

- bin/eslint.js
add eslint version to error output. (fixes #9037)
is this will be a breaking change?
> Update: add eslint version to error output. (fixes #9037)

- docs/rules/generator-star-spacing.md
I fixed a typo in the docs which refers to a setting that was removed from the PR during review.
This should get in pretty soon, otherwise it …
> Fix: Correct a typo in generator-star-spacing documentation

- lib/linter.js
- tests/lib/rules/no-catch-shadow.js
- tests/lib/rules/no-redeclare.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9202)
This fixes a regression introduced in f005e2467edda78a6654c4717aa23e99b3289131 (merged as part of 60c51486849c3765ac21fb63e615db2c56b614fd) where globals would get added to environments when the env was set to `false` in a config file. (The globals would not get added if the env was omitted).
I had originally assumed this was a dead code path because it wasn't covered in any tests (and I had thought environments with `env: false` where stripped out of the config beforehand). However, it turns out that we just didn't have tests for this case.
Nothing in …
> Fix: avoid adding globals when an env is used with `false` (fixes #9202)

- Makefile.js
[x] Bug fix
* **Node Version:** 8.4.0
N/A
N/A
I cloned the ESLint repo and ran
```bash
$ node Makefile.js gensite
```
I expected the website to generate in a reasonable amount of time, and I expected the build script to not spawn hundreds of concurrent processes.
The build script froze after generating about 300/350 docs files. Running `ps` …
> Build: avoid process leak when generating website

- tests/lib/linter.js
This updates the tests for `Linter` to avoid relying on the undocumented `getFilename` method.
> Chore: avoid relying on undocumented Linter#getFilename API in tests

- lib/linter.js
This updates `Linter#verify` to create a new array of problems rather than storing problems in `this.messages`. As a result, the private `messages` property can be removed.
> Chore: avoid storing list of problems on Linter instance (refs #9161)

- lib/linter.js
- tests/lib/linter.js
This updates `Linter` to remove the internal `getAncestors` method. (The documented `context.getAncestors` method in rules is still available.)
> Chore: remove internal Linter#getAncestors helper (refs #9161)

- lib/config/config-ops.js
- lib/linter.js
- tests/lib/config/config-ops.js
This removes the `normalize` method from `config-ops` in favor of a `getRuleSeverity` method.
Previously, `ConfigOps.normalize` would only convert string severities to numeric severities, but it would still leave severities in arrays, and `Linter` used a separate `getRuleSeverity` function to extract them. Now `ConfigOps.getRuleSeverity` handles both operations, so the `getRuleSeverity` function in `Linter` is redundant.
The goal of this change is to (a) reduce the number of places where modules mutate each others' objects, and (b) organize the rule severity logic into one place.
Nothing …
> Chore: remove ConfigOps.normalize in favor of ConfigOps.getRuleSeverity

- CONTRIBUTING.md
- docs/developer-guide/contributing/README.md
I changed the CLA link from https://contribute.jquery.org/cla to https://cla.js.foundation/eslint/eslint in the following pages:
- https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md
- …
> Docs: Replace misleading CLA links (#9133)

- lib/linter.js
This removes the undocumented `currentFilename` property from `Linter` instances.
This relies on https://github.com/eslint/eslint/pull/9218. The tests will pass after https://github.com/eslint/eslint/pull/9218 is merged.
> Chore: remove currentFilename prop from Linter instances (refs #9161)

- lib/linter.js
This updates `Linter#verify` to only create a report translating function for a given rule after the rule has already reported a problem for a given file. When running ESLint on any given file, it's common for a vast majority of rules to not report any errors. This avoids creating an extra two functions in the common case, which has a significant effect on performance because creating `ruleContext`s is a hot path.
I tested the performance impact by running ESLint on its own codebase 5 times with and without this change applied, and taking the average time of the 5 runs in each case.
```bash
time bin/eslint.js 'tests/**/*.js' 'bin/**/*.js' …
```
> Chore: create report translators lazily

- lib/linter.js
- lib/rules.js
- tests/lib/config/plugins.js
- tests/lib/rules.js
This moves the logic for handling missing rules out of `Linter#verify` and into the rule storage module. This is useful because it simplifies the function signature of `Rules#get` (it now always returns a rule, rather than sometimes returning null) and it helps to make `Linter#verify` less complex.
> Chore: move logic for handling missing rules to rules.js

- lib/linter.js
- lib/rules.js
- lib/testers/rule-tester.js
- tests/lib/rules.js
This updates `rules.js` to always normalize rules to the new-style API when retrieving them from storage. This avoids the need for other modules, such as `Linter`, to deal with casework for multiple different rule formats.
> Chore: always normalize rules to new API in rules.js

- package.json
* Fix: some rules crashing if tests array has missing elements (fixes [#35](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/35)). ([#36](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/36)) ([e3a14e1](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/commit/e3a14e11d86836b1ab63d19c689327fea8f8a4bc))
* Breaking: update ESLint peerDependency to >=4.1.0 ([#33](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/33)) ([7cabcdc](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/commit/7cabcdcae32ae67fc3769804aad5e5d8882b3baa))
* Chore: use local variable. …
> Chore: upgrade eslint-plugin-eslint-plugin@1.0.0

- tests/lib/cli-engine.js
This updates the `CLIEngine` tests to avoid using globals and patching `String.prototype`, since this leaks into other tests and isn't really necessary.
> Chore: avoid using globals in CLIEngine tests

- lib/linter.js
- lib/util/apply-disable-directives.js
- tests/lib/linter.js
- tests/lib/util/apply-disable-directives.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9215)
This extracts the processing logic for `eslint-disable` comment processing into a different module file, rather than storing state on `Linter` throughout the comment traversal. This fixes bugs such as https://github.com/eslint/eslint/issues/9215, and adds a bunch of tests for edge cases to avoid issues like https://github.com/eslint/eslint/pull/9195 in the future.
This also improves the asymptotic complexity of disable comment checking logic -- it was previously `O(#problems * #disable comments)`, and now it's `O(#problems + #disable comments * log(#disable comments))`. In most cases this probably won't be …
> Fix: refactor eslint-disable comment processing (fixes #9215)

- docs/rules/sort-imports.md
Fixed the errors in the examples of correct code for [sort-imports.md](https://eslint.org/docs/rules/sort-imports).
N/A
> Docs: Fix error in example code for sort-imports (fixes #8734)

- lib/linter.js
- tests/lib/linter.js
This removes the undocumented `defaults()` method from `Linter.prototype`. (Also see: #9161)
> Chore: remove undocumented defaults() method (refs #9161)

- lib/linter.js
- tests/lib/linter.js
I filtered out shebang comments before comments are processed for the function `modifyConfigsFromComments` in linter.js. I also added additional tests to the linter.js test file. …
> Fix: shebang error in eslint-disable-new-line; add tests (fixes #9238)

- tests/lib/util/apply-disable-directives.js
This updates the test file for `apply-disable-directives` to always use the correct name.
When working on this locally, I went through a few different names for the module before settling on `apply-disable-directives`. However, there were a few places I forgot to update with the latest name.
> Chore: use consistent names for apply-disable-directives in tests

- lib/code-path-analysis/code-path.js
This removes an unused `eslint-disable` comment (found by the implementation in https://github.com/eslint/eslint/issues/9250).
No
> Chore: remove unused eslint-disable comment

- tests/lib/linter.js
This updates the tests for `Linter` to avoid using undocumented methods as passthroughs to `SourceCode`.
> Chore: avoid internal SourceCode methods in Linter tests (refs #9161)

- lib/cli-engine.js
This updates `executeOnFile` in `CLIEngine` to avoid modifying the cache for each file, and instead modify the cache for all the results at the end. 
This will make it easier to accumulate results …
> Chore: make executeOnFile a pure function in CLIEngine

- tests/lib/linter.js
This updates the `Linter` tests to avoid using the private `Linter#getScope` and `Linter#markVariableAsUsed` methods. The public `context.getScope` and `context.markVariablesAsUsed` methods are used instead.
(refs #9161)
All of the tests here are changed in the same way. The `spy` method, which was previously a pure node listener, now needs a reference to `context` so that it can call `context.getScope` rather than `linter.getScope`. So the method is now created inside a `linter.defineRule` call rather than outside it.
> Chore: avoid relying on Linter#getScope/markVariableAsUsed in tests

- lib/linter.js
- tests/lib/ast-utils.js
This updates `Linter` to remove undocumented methods like `Linter#getSource` and `Linter#getSourceLines`.
Note that the deprecated `context.getSource` and `context.getSourceLines` methods are still available to rules. This just removes the duplicate methods from `Linter`.
> Chore: remove SourceCode passthroughs from Linter.prototype (refs #9161)

- lib/cli-engine.js
Previously, CLIEngine would store the last config object when executing on multiple files, as a performance optimization to avoid rehashing configs if the same config was used for multiple files.
This can be better implemented by using a WeakMap to map config objects to hash results.
No
> Chore: refactor config hash caching in CLIEngine

- lib/linter.js
This updates `Linter` to remove the undocumented `getScope` method. It doesn't make sense to call `getScope` from a `Linter` instance, since API users can't access the `Linter` instance while the AST is being traversed.
Note that the documented `context.getScope` method still exists, and is still available to rules. This just removes the `getScope` method on `Linter`.
(refs #9161)
~~This is blocked by https://github.com/eslint/eslint/pull/9252. The tests will fail until https://github.com/eslint/eslint/pull/9252 is merged.~~
> Chore: remove undocumented Linter#getScope method

- lib/cli-engine.js
- lib/code-path-analysis/code-path-state.js
- lib/config/autoconfig.js
- lib/config/config-initializer.js
- lib/linter.js
- lib/rules/key-spacing.js
- lib/rules/no-unmodified-loop-condition.js
- lib/rules/quote-props.js
- lib/rules/quotes.js
- lib/rules/space-before-blocks.js
- lib/rules/valid-jsdoc.js
I made an attempt at implementing the `prefer-smaller-scope` rule proposal, which was originally proposed in https://github.com/eslint/eslint/issues/5284. That attempt can be found [here](https://gist.github.com/not-an-aardvark/e7cc13acbb593f402035b587aab226ec).
Unfortunately, I found that the rule would incorrectly report some places where declaring a variable in an outer scope is necessary if an inner scope is executed multiple times. I don't know of a good way to avoid those false positives while still keeping the rule useful.
```js
let flag; // `flag` is only ever used in the function, but still needs to be declared outside it.
function …
```
> Chore: prefer smaller scope for variables in codebase

- lib/linter.js
- tests/lib/ast-utils.js
- tests/lib/linter.js
This updates `Linter` to remove the `Linter#getDeclaredVariables` method. The `context.getDeclaredVariables` method is still available to rules -- this just removes the version of the method on `Linter`.
No
> Chore: remove internal Linter#getDeclaredVariables method (refs #9161)

- lib/linter.js
This updates `Linter` to remove the `markVariableAsUsed` method. (The `context.markVariableAsUsed` function is still available to rules -- this just removes the version on `Linter`.
> Chore: remove undocumented Linter#markVariableAsUsed method (refs #9161)

- lib/formatters/codeframe.js
- lib/formatters/stylish.js
- tests/lib/formatters/codeframe.js
- tests/lib/formatters/stylish.js
For codeframe.js and stylish.js, I checked if the reported messages end with a " ." - if they do, the " ." is kept in the output. For "."s that aren't preceded by a space, the "." is removed in the …
> Fix: Formatters keep trailing '.' if preceded by a space (fixes #9154)

- lib/linter.js
This removes the undocumented `traverser`, `scopeManager`, and `currentConfig` properties from `Linter` instances. Since the properties are no longer used in any methods, they can just be replaced with local variables.
> Chore: remove extraneous linter properties (refs #9161)

- docs/developer-guide/working-with-rules.md
The documentation for `npm run perf` says that the perf script only enables rules from `eslint:recommended`. In fact, the perf script enables all core rules.
> Docs: fix inaccuracy in `npm run perf` description

- lib/linter.js
- tests/lib/linter.js
* **ESLint Version:** `master`
* **Node Version:** 8.4.0
* **npm Version:** 5.4.1
- default
- nothing
Gave a `SourceCode` object to `linter.verify()`.
In more accurate, I resolved conflictions between #8755 and `master`, then [this test](https://github.com/eslint/eslint/pull/8755/files#diff-c6fc98e70cf39f54c23015c3db45f14aR3794) got broken.
It reuses the AST of the …
> Fix: reuse the AST of source code object in verify

- .eslintrc.yml
- lib/rules/indent-legacy.js
- lib/rules/no-tabs.js
- package.json
This upgrades [`eslint-plugin-eslint-plugin`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) to v1.2.0, and enables the new [`no-deprecated-context-methods`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/no-deprecated-context-methods.md) rule, which disallows calls to deprecated methods like `context.getFirstToken`.
[Full changelog](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/efae7daaeecc96545aac3714c043e4b564aa0edd/CHANGELOG.md)
> Chore: enable eslint-plugin/no-deprecated-context-methods

- lib/cli-engine.js
- lib/config/config-file.js
- lib/config/config-validator.js
- lib/linter.js
- lib/testers/rule-tester.js
- tests/lib/config/config-validator.js
Handling `Rules` instances outside of `Linter` is undesirable, because this gives any handler the ability to mutate linters at a distance. This commit updates `config-validator` to avoid handling `Rules` instances directly, and instead handle `Map`s that won't affect the underlying `Rules` instance if mutated.
The long-term goal is to make the `rules` property of `Linter` instances private, so that only `Linter` handles `Rules` instances. However, this isn't possible yet because `Plugins` still relies on mutating a `Rules` instance that it's provided as an argument.
> Chore: avoid handling Rules instances in config-validator

- lib/ast-utils.js
- tests/lib/rules/no-invalid-this.js
[X] Bug fix
Fixes #9126.
This PR adds the IIFE of arrow functions into the assignment target detection logic.
> Fix: IIFE and arrow functions in no-invalid-this (fixes #9126)

- Makefile.js
[x] Bug fix (fixes https://github.com/eslint/eslint.github.io/issues/407)
This updates the `npm run gensite` script to run browserify as part of the site generation, rather than using whatever it finds in `build/eslint.js`. This has a few advantages:
* The built file will always be up-to-date (previously, it would reflect the state of the repository whenever `npm test` was last run).
* The gensite script won't fail if it's run on its own and there isn't a `build/` directory.
> Build: re-run browserify when generating site

- docs/developer-guide/nodejs-api.md
- lib/cli-engine.js
- lib/linter.js
- lib/testers/rule-tester.js
- tests/lib/ast-utils.js
- tests/lib/code-path-analysis/code-path-analyzer.js
- tests/lib/code-path-analysis/code-path.js
- tests/lib/linter.js
- tests/lib/util/source-code.js
- tests/tools/eslint-fuzzer.js
This updates `Linter` to remove the undocumented `reset` method.
It also removes the fourth argument from `Linter#verify`, because that argument now has no effect at all. (It was previously used to control what happened to the internal state of the `Linter` instance, but now the `Linter` instance has no internal state except for the `sourceCode` property, which was always reset regardless). In fact, the fourth argument has never had any effect for users that only used documented APIs. Integrations that use the fourth argument will continue to work the same way that they did before (the fourth argument will just be ignored now).
~~This builds …
> Chore: remove Linter#reset (refs #9161)

- lib/testers/rule-tester.js
This updates `RuleTester` to avoid monkeypatching its `Linter` instance, and use rule composition instead in order to freeze the context properties.
> Chore: avoid monkeypatching Linter instances in RuleTester

- lib/rules/newline-per-chained-call.js
- tests/lib/rules/newline-per-chained-call.js
This updates the [newline-per-chained-call](https://eslint.org/docs/rules/newline-per-chained-call) by making it fixable and does not affect the rule definition. The result of the fix was tested by …
> Update: make newline-per-chained-call fixable

- lib/rules/no-undef-init.js
- tests/lib/rules/no-undef-init.js
[X ] Other, please explain: Remove autofixing to no-undef-init rule, particularly for var declarations
1. To the point in #9231 about not using let: Using let looks like it still works, so I want to make sure I understand.
```
function fun() {
for (var p in [0, 1, 2]) {
let selected = undefined;// auto fix will remove `= undefined`
for (var i in [0, 1, 2]) {
if (!selected) {
console.log('selected');
}
selected = i;
}
}
}
fun();
```
2. Is it okay to keep as separate if? I didn't include in the same if as line 50 since the inner comment wouldn't make sense.
3. I am checking node.parent.kind because it looks to …
> Fix: remove autofix for var undef inits (fixes #9231)

- lib/rules/indent.js
- tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9285)
This updates the `flatTernaryExpression` option of `indent` to check whether a ternary expression is on the same *line* as a statement, rather than checking if the expression itself starts the statement.
As a sidenote, it seems like it might be …
> Update: indent flatTernary option to handle `return` (fixes #9285)

- docs/developer-guide/nodejs-api.md
- docs/developer-guide/working-with-plugins.md
- docs/user-guide/command-line-interface.md
- lib/cli-engine.js
- lib/linter.js
- tests/lib/cli-engine.js
- tests/lib/linter.js
This implements the proposal from https://github.com/eslint/eslint/issues/7510#issuecomment-275947091 to allow autofixes to be applied when using processors.
The processor API basically remains the same. The only changes are:
* Processors can now export a `supportsAutofix: true` property, which opts a processor into autofixing.
* If a processor supports autofixing, the `postprocess` method is expected to also transform autofix ranges as necessary when it transforms the locations of reported problems. Afterwards, the transformed fixes are applied to the original, unprocessed text.
Multipass autofixing works by calling `preprocess` and …
> Update: allow autofixing when using processors (fixes #7510)

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
[x] Bug fix 
For https://github.com/eslint/eslint/issues/9156.
- Report any call expression wrapped in parentheses in a member expression
- Do not report any member expression wrapped in parentheses in a new expression if the member expression contains any call expression
- Let me know if this is the correct behavior.
- Let me know if there is a simpler implementation you have in mind.
> Fix handling of no-extra-parens on some MemberExpression cases

- lib/linter.js
> Chore: rewrite parseListConfig for a small perf gain.

- docs/rules/prefer-arrow-callback.md
Fixes a small copy-paste mistake.
The documentation is talking about the `allowUnboundThis` option here, but this code snippet refers to the `allowNamedFunctions` option instead. A small copy-paste mistake.
> Fix code snippet to refer to the correct option

- lib/cli-engine.js
- lib/config/config-file.js
- lib/config/config-validator.js
- lib/linter.js
- lib/testers/rule-tester.js
- tests/lib/config/config-validator.js
This reverts commit 7c95d5d0a44b7f4f7f885621deb7007a7faa3a4b to avoid the performance impact of iterating through all ~200 core rules in the `Linter#getRules` method every time Linter#verify is called.
This is most noticeable when using `RuleTester`, since `Linter#verify` is called a lot of times on small code samples, so the added overhead is a significant portion of the total time.
I noticed this when running the `indent` tests. On `master`, it takes about 3.5 seconds to run all 751 `indent` tests, but after reverting this change it takes about 2.3 seconds.
Eventually, it would be nice to reapply this commit, but we will probably need to …
> Chore: Revert "avoid handling Rules instances in config-validator"

- docs/rules/max-len.md
this regex will cause an error:
```js
new RegExp("^\\s*var\\s.+=\\s*require\\s*\\(/");
```
it didn't cause an error, but when apply the config, it didn't work. is this expected?
> Docs: fix wrong config in max-len example.

- docs/developer-guide/working-with-plugins.md
- lib/linter.js
- lib/util/source-code.js
- tests/lib/linter.js
- tests/lib/util/source-code.js
This is a reference implementation of #9122. With this change, rules don't have to worry about whether `node.parent` has been set at any given point, because all of the `node.parent` properties will be assigned by the time the rule gets run.
~~This builds on https://github.com/eslint/eslint/pull/9268, and should not be merged until https://github.com/eslint/eslint/pull/9268 is merged. For now, only look at the [second commit](https://github.com/eslint/eslint/pull/9283/commits/f65fdac1b0f8962cd44a899a4c6cf1a10e852fbf).~~
Since this stores nodes in a queue rather than doing another traversal, this has very little performance impact: …
> Update: run rules after `node.parent` is already set (fixes #9122)

- lib/util/apply-disable-directives.js
This is a PR onto https://github.com/eslint/eslint/pull/9322 to simplify `eslint-disable-line` handling.
With this implementation, it's not necessary to keep track of the location of `disable-line` comments after processing them -- the comments can be processed in order like before. This also gets rid of the special "all" value in favor of a separate boolean.
> Chore: Simply line-comment handling in fix for #9318

- lib/util/apply-disable-directives.js
- tests/lib/util/apply-disable-directives.js
This is another patch on https://github.com/eslint/eslint/pull/9322.
It makes the fix simpler again by just treating `line` and `block` directive comments separately, to avoid needing to keeping track of extra state.
> Chore: handle disable-line comments in a separate pass

- lib/linter.js
> Revert "Chore: rewrite parseListConfig for a small perf gain."

- docs/developer-guide/working-with-plugins.md
- lib/linter.js
- lib/util/source-code.js
- tests/lib/linter.js
- tests/lib/util/source-code.js
This reverts commit 1488b511f3be3220d6f187f48c8b22075c6bbd30. Some rules
from plugins were relying on the behavior that a a `node.parent`
property is only sometines present, and other rules were …
> Fix: Revert setting node.parent early (fixes #9331)

- lib/linter.js
- lib/rules/max-len.js
- lib/rules/no-alert.js
- lib/rules/no-loop-func.js
- lib/rules/padding-line-between-statements.js
- lib/rules/space-unary-ops.js
This updates some functions in the codebase to remove unused arguments.
I found these by enabling `no-unused-vars` with `args: all`. Unfortunately, that also resulted in some false positives (not included in this PR), so I don't think we can check for this statically with the existing core rules.
> Chore: remove unused arguments in codebase

- lib/logging.js
[ x ] Add something to the core
Remove unnecessary slice.
> Chore: Remove unnecessary slice from logging utility

- lib/formatters/html-template-page.html
"normal" is invalid property value, so change from "normal" to "medium".
* **ESLint Version:** 4.7.1
* **Node Version:** 6.9.5
* **npm Version:** 4.3.0 …
> Fix: Invalid font-size property value issue.

- lib/code-path-analysis/code-path-segment.js
- lib/code-path-analysis/code-path-state.js
- tests/fixtures/code-path-analysis/try--try-with-for-inof-1.js
- tests/fixtures/code-path-analysis/try--try-with-for-inof-2.js
- tests/lib/rules/constructor-super.js
- tests/lib/rules/no-this-before-super.js
Fixes #8848.
This PR fixes code path analysis to generate correct code paths.
Before, it was wrong if `ForInStatement#right` is the first throwable location (e.g. a variable reference, a call expression, ...) in the outer `try` block. (It makes 2 paths from `try` block to `catch` block at the first throwable location and the end of `try` block. The former seemed to conflict with the looping path of `for-in`.)
In the following code:
```js
try {
for (let x of xs) {
}
} catch (err) {
}
```
<details><summary>Before: broken code path.</summary>
</details> …
> Fix: fix wrong code-path about try-for-in (fixes #8848)

- lib/linter.js
- lib/util/node-event-generator.js
- lib/util/safe-emitter.js
- tests/lib/code-path-analysis/code-path-analyzer.js
- tests/lib/linter.js
- tests/lib/util/node-event-generator.js
- tests/lib/util/safe-emitter.js
[x] Bug fix
* **Node Version:** 8.5.0
N/A
N/A
```js
"use strict";
const eslint = require("eslint");
const linter = new eslint.Linter();
linter.defineRule("foo-rule", context => {
return {
newListener() {
assert(false);
}
}
});
linter.verify("foo", { rules: { "foo-rule": "error", "no-undef": "error" } });
```
I expected the `newListener` method to never get called, because there are no nodes with type `newListener`. …
> Fix: special EventEmitter keys leak information about other rules

- lib/formatters/html-template-page.html
Open html output file used Firefox and output the following error message in console.
'The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.'
So add meta element with charset(UTF-8) attribute.
* **ESLint Version:** 4.7.2
* **Node Version:** 6.10.2
* **npm Version:** 5.4.1 …
> Fix: Add meta element with charset attribute.

- README.md
With the new [rule deprecation policy](https://eslint.org/docs/user-guide/rule-deprecation), we don't remove rules even in major releases.
> Docs: remove line about removing rules from semver policy

- lib/linter.js
This removes the `sourceCode` property from `Linter` instances, as part of the ongoing effort in #9161 to reduce undocumented API surface area.
The `sourceCode` property was used because `Linter` has a `getSourceCode` method which points to the `SourceCode` instance from the last `verify` call. This is unfortunate, because it prevents `Linter#verify` from being side-effect-free as described in #9161. However, we can't remove it right now, because it's documented [here](https://eslint.org/docs/developer-guide/nodejs-api#linterverify). Eventually I think we should deprecate and remove that, but that is a separate issue. …
> Chore: remove sourceCode property from Linter (refs #9161)

- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
Fixes #9350
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
I added a check for `TemplateLiteral` and if it is the case then it checks the quasi associated as long as no expression is found, as if it has an expression is not a valid dot notation. …
> Fix: dot notation rule failing to catch string template (fixes #9350)

- conf/default-cli-options.js
- docs/developer-guide/nodejs-api.md
- docs/user-guide/command-line-interface.md
- lib/cli-engine.js
- lib/cli.js
- lib/linter.js
- lib/options.js
- lib/util/apply-disable-directives.js
- tests/lib/cli-engine.js
- tests/lib/linter.js
- tests/lib/util/apply-disable-directives.js
[x] Add something to the core (see https://github.com/eslint/eslint/issues/9249)
This adds the `--report-unused-disable-directives` CLI flag, and the `reportUnusedDisableDirectives` option to `CLIEngine` and `Linter`, as described in https://github.com/eslint/eslint/issues/9249.
> New: add option to report unused eslint-disable directives (fixes #9249)

- docs/user-guide/command-line-interface.md
- lib/cli.js
- lib/options.js
- tests/bin/eslint.js
- tests/lib/cli.js
I've added the new flag, as discussed in #9076.
Nothing in particular, the changes are rather small.
**To do**
> Add the fix-dry-run flag

- lib/ignored-paths.js
- lib/testers/rule-tester.js
- lib/util/node-event-generator.js
throw a TypeError after a type checking if-statement, instead of a generic Error.
> Chore: Error => TypeError

- lib/rules/array-bracket-newline.js
- tests/lib/rules/array-bracket-newline.js
Fixes #9211
[X] Bug fix
Added another case for requiring line breaks. This is when an array contains only a comment and spans multiple lines. Before it failed on this as it did not recognise the new lines as it was empty according to the check.
No
> Fix: recognise multiline comments as multiline arrays (fixes #9211)

- docs/rules/no-console.md
Add documentation on how to show warnings/error for console calls and not method overwrites with the use of no-restricted-syntax
That I got all the details from the opened issue
> Docs: show console call with no-restricted-syntax (fixes #7806)

- docs/rules/class-methods-use-this.md
Update the documentation that it is not 100% case that a method in a class that doesn't use `this` can be converted to a static method. 
This updates the text and links to mdn docs on classes and static methods.
Not sure if it's beyond the scope to try and provide an example where you might not add a static
> Docs: update doc for class-methods-use-this (fixes #8910)

- docs/rules/array-bracket-newline.md
- lib/rules/array-bracket-newline.js
- tests/lib/rules/array-bracket-newline.js
https://github.com/eslint/eslint/issues/9136
Added a "consistent" option to `array-bracket-newline`
> Update: Add "consistent" option to array-bracket-newline (#9136)

- templates/blogpost.md.ejs
[x] Other, please explain: Fix an issue with the blog post template (used for generating blog posts on release).
For non-patch releases, template used to generate this string:
> This release adds some new features andfixes …
> Chore: Add missing space in blog post template

- lib/util/source-code.js
Chore
Inspired by https://github.com/eslint/eslint/issues/6238#issuecomment-332393428, this is a refactor of SourceCode#getJSDocComment. The current implementation doesn't make as much sense given …
> Chore: Refactor SourceCode#getJSDocComment

- lib/rules/indent.js
- tests/lib/rules/indent.js
(I shan’t include the bug report template here unless you would especially like me to, since I have already filed the corresponding issue as #9392.)
When a node is ignored by the indent rule, it …
> Fix: ignored nodes in indent rule (fixes #9392)

- docs/rules/no-mixed-operators.md
Update docs for `no-mixed-operators` to clarify that a pair of errors will be triggered for each pair of mixed consecutive operators used. Fixes #8051.
Just an update to the documentation for the …
> Docs: clarify no-mixed-operators (fixes #8051)

- docs/rules/prefer-destructuring.md
> Docs: Add jquery warning to prefer-destructuring

- docs/rules/prefer-numeric-literals.md
`Number.parseInt("1F7", 16)` -> `503`
Just check it in the console. 😉
> Docs: fix examples for prefer-numeric-literals

- docs/developer-guide/development-environment.md
Without this, config file in home directory makes 1 test fail.
Added instruction to disable any ESLint config file in home directory.
Check my …
> Docs: Add instruction re home-directory config files (refs #7729)

- docs/developer-guide/development-environment.md
Original headings made it seem that sections after Step 5 could be additional steps.
And summary of workflow without a link to the full workflow could make a reader think
that the summary is the whole workflow. …
> Docs: Reorganized to avoid misunderstandings.

- docs/rules/no-restricted-imports.md
- docs/rules/no-restricted-modules.md
- lib/rules/no-restricted-imports.js
- lib/rules/no-restricted-modules.js
- tests/lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-modules.js
`no-restricted-imports` and `no-restricted-modules` (am interested in feedback first before making the changes to `no-restricted-modules` as well)
**Does this change cause the rule to produce more or fewer …
> Add support for custom messages to restricted imports

- docs/rules/require-jsdoc.md
- lib/rules/require-jsdoc.js
- tests/lib/rules/require-jsdoc.js
Fixes #5867.
Add a `FunctionExpression` configuration option to the `require-jsdoc` rule.
Nothing in particular!
> Update: Add FunctionExpression to require-jsdoc (fixes #5867)

- lib/linter.js
`/* eslint-env */` comments are processed differently from other directive comments in that they're actually [matched by a regex](https://github.com/eslint/eslint/blob/4ae7ad3325abe962f4f56cd7b547476b313d6024/lib/linter.js#L461-L478) and applied before parsing occurs. This was done as a fix for https://github.com/eslint/eslint/issues/2134 in order to allow `/* eslint-env */` comments to change the parser options. (A side-effect is that some envs are incorrectly added when `/* eslint-env */` appears in a string rather than a comment, like [this](https://github.com/eslint/eslint/blob/4ae7ad3325abe962f4f56cd7b547476b313d6024/tests/lib/linter.js#L …
> Chore: avoid applying eslint-env comments twice

- conf/eslint-recommended.js
- docs/rules/multiline-comment-style.md
- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
> New: multiline-comment-style rule (fixes #8320)

- docs/rules/lines-around-comment.md
- lib/rules/lines-around-comment.js
- tests/lib/rules/lines-around-comment.js
Fix #8564.
~~Moved the "ClassBody" check from "Block" to "Object"~~ Added `allowClassStart` and `allowClassEnd` options, updated tests, and added docs. …
> Fix: Add class options for `lines-around-comment` (fixes #8564)

- messages/no-config-found.txt
- tests/bin/eslint.js
Corrected error message and test description so they no longer exclude home-directory config files from set of directories searched for config files. …
> Fix: Correct error and test messages to fit config search path

- docs/maintainer-guide/pullrequests.md
This updates the maintainer guide to recommend deleting the git branch after merging a PR. (It seems like we usually already do this, but I think we should document it to make the recommendation more official.)
> Docs: suggest deleting branches after merging PRs

- Makefile.js
- tests/tools/internal-rules/internal-consistent-docs-description.js
- tests/tools/internal-rules/internal-no-invalid-meta.js
This fixes an issue with https://github.com/eslint/eslint/commit/b31e55ac5fe0dccb827abe5c1db3a32dfaa9efd3 where the tests for internal rules are no longer getting run.
> Chore: ensure tests for internal rules get run

- docs/rules/no-use-before-define.md
- lib/rules/no-catch-shadow.js
- tests/lib/config/config-ops.js
- tests/lib/util/source-code.js
* Fix the typo in no-use-before-define docs (declaring variable `c` before using it `c++`), see #8368
* Remove the comment `// With blockBindings: true` in no-use-before-define docs, see #8368
* …
> Remove blockBindings references

- tests/bench/bench.js
- tests/bench/xform-rules.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9397)
This fixes the `npm run profile` script in the repository.
This is actually the first time I've tried to use the script, and I'm not very familiar with the design goals (e.g. I'm not sure why it runs the benchmark in chrome rather than Node). I think having a benchmark for `Linter` is a good idea -- if we decide to keep using this, we might want to convert it to ES6 and add tests for it.
> Build: fix `npm run profile` script (fixes #9397)

- lib/rules/generator-star-spacing.js
- lib/rules/no-trailing-spaces.js
- tests/lib/rules/no-trailing-spaces.js
no-trailing-spaces
More
New default behavior
```js
// Comment with trailing space 
```
By default trailing spaces in comments are ignored.
As specified in the docs (https://eslint.org/docs/rules/no-trailing-spaces) the comments are also checked for trailing whitespace by default. …
> Update: Don't ignore comments (no-trailing-spaces)

- docs/developer-guide/development-environment.md
- tests/bin/eslint.js
Eliminate assumption that there is no config file in / or ~/ by checking for that
and expecting no-config-file-found error message and exit code 1 only if neither
directory contains a config file. …
> Fix: Revise no-config-file test to prevent false failure.

- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
To update the node in the report so that the error underlines in code editor linter is more accurate.
The node type in the report had to be updated as well.
For example, from the issue - with this fix, the linter looks like so
> Fix: change err report in constant condition (fixes #9398)

- docs/user-guide/configuring.md
This seems to be the last step in liquidating issue #7729.
Stated exceptional treatment of home-directory configuration file in the document that needs that additional info. …
> Docs: Add missing info about special status of home-dir config files.

- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
[x] Bug fix
* **ESLint Version:** 4.9.0
* **Node Version:** 8.7.0
* **npm Version:** 5.4.2
default
```yml
rules:
multiline-comment-style: [error, separate-lines]
```
```js
/* foo
bar */ baz;
```
I expected no error to be reported, because that comment can't safely be converted into line comments.
ESLint autofixed the code to:
```js
// foo
// bar baz
```
In other words, the `baz` statement was …
> Fix: multiline-comment-style reports block comments followed by code

- lib/rules/multiline-comment-style.js
- tests/lib/rules/multiline-comment-style.js
[x] Bug fix
* **ESLint Version:** 4.9.0
* **Node Version:** 8.7.0
* **npm Version:** 5.4.2
default
```yml
rules:
multiline-comment-style: error
```
```js
/*
* foo
*
* bar
*/
```
I expected an error to be reported for the misaligned star, and I expected the code to be autofixed to:
```js
/*
* foo
*
* bar
*/
```
The code was autofixed to:
```js
/*
* foo
*•
* bar
*/
```
(`•` represents a space …
> Fix: multiline-comment-style autofixer added trailing space

- docs/rules/padded-blocks.md
`padding-line-between-statement` should be `padding-line-between-statements`
Edited a linked rule to match the actual rule name. It was hitting the 404 page.
**Is there anything you'd like reviewers …
> Docs: Incorrect link to related rule

- docs/developer-guide/README.md
- docs/developer-guide/contributing/README.md
- docs/developer-guide/contributing/new-rules.md
- docs/developer-guide/contributing/pull-requests.md
- docs/developer-guide/contributing/reporting-bugs.md
- docs/developer-guide/contributing/rule-changes.md
- docs/developer-guide/nodejs-api.md
- docs/developer-guide/selectors.md
- docs/developer-guide/working-with-plugins.md
- docs/developer-guide/working-with-rules-deprecated.md
- docs/developer-guide/working-with-rules.md
Fix a bunch of broken links to other pages in the docs for Markdown files
inside the `developer-guide` directory.
> Docs: Fix broken links in developer-guide

- docs/rules/lines-between-class-members.md
The docs for `lines-between-class-members`' boolean `exceptAfterSingleLine` option showed `"true"` and `"false"` (notice the quotes), but the [rule's …
> Docs: Unquote booleans in lines-between-class-members docs

- lib/rules/comma-style.js
- lib/rules/indent-legacy.js
- lib/rules/indent.js
- lib/rules/lines-around-comment.js
- lib/rules/no-lonely-if.js
- lib/rules/no-unneeded-ternary.js
- lib/rules/no-unused-labels.js
- lib/rules/no-useless-computed-key.js
- lib/rules/no-useless-escape.js
- lib/rules/object-shorthand.js
- lib/rules/operator-linebreak.js
- lib/rules/sort-imports.js
- packages/eslint-config-eslint/default.yml
since we are using 4 spaces indent, it's very easy to exceed 120, I set max-len to 160 and ignore options to true.
> Chore: enable max-len.

- docs/developer-guide/nodejs-api.md
Violated convention is “using a single var statement with one variable per line.
All lines after the first should be indented one level”. Interpreted this as
applying to “let” and “const”, too.
In 2 …
> Docs: Correct violations of “Variable Declarations” in Code Conventions

- lib/rules/valid-jsdoc.js
- tests/lib/rules/valid-jsdoc.js
#9412 
I've added tests to make sure that the jsdoc tags can be used in any order. So you will find each possible combination of jsdoc tags, based on these …
> Fix: Expected order of jsdoc tags (fixes #9412)

- Makefile.js
- lib/cli-engine.js
`string.startsWith` has a better readability.
> Chore: regex.test => string.startsWith to improve readability

- lib/cli.js
- tests/lib/cli.js
[x] Bug fix (fixes https://github.com/eslint/eslint/issues/9515)
This fixes an issue where `cli` would treat an empty-string argument as missing.
> Fix: allow linting the empty string from stdin (fixes #9515)

- lib/rules/no-var.js
- tests/lib/rules/no-var.js
[X] Bug fix
Fixes #9520.
This PR makes `no-var` rule not fixing global variables.
If the program has special scope (`sourceType: "module"` or `ecmaFeatures: { globalReturn: true }`), the rule keeps the current behavior.
> Fix: no-var don't fix globals (fixes #9520)

- docs/developer-guide/contributing/working-on-issues.md
Made this more DRY and extended its coverage to previously missing but important
labels (like `accepted`, `evaluating`, and `blocked`) by referencing maintainer
doc instead of repeating. Reorganized labels by the questions they answer for
contributors. Incorporated bounty info into priority section. Some labels, like
`needs bikeshedding`, seem totally undocumented. Fixing that could be another task.
[ ] Changes an existing rule …
> Docs: Revise contributor documentation on issue labels.

- Makefile.js
- docs/developer-guide/contributing/pull-requests.md
- package.json
The check-commit npm script seems useful in theory, but it doesn't accurately reflect the current commit conventions. For example, it still instructs users to squash their commits, when we no longer advise this. Additionally, the commit message on a branch is sometimes irrelevant to the commit message that gets created when a PR is merged (only the PR title matters when a branch has more than two commits).
Do you use `check-commit`? It seems like it could be useful in the case when there is only one commit on a branch, even though it's misleading when there is more than one commit.
> Chore: remove `npm run check-commit` script

- docs/rules/object-property-newline.md
Corrected and completed documentation on rule `object-property-newline` to complete step 1 of plan to handle issue #6251.
This rule seems to …
> Docs: Amend rule document to correct and complete it (refs #6251).

- docs/rules/strict.md
> Docs: add .md to link(for github users)

- tests/lib/formatters/html.js
This commit removes a test that has been commented out for 2 years and doesn't appear to work.
> Chore: remove commented test for HTML formatter

- tests/lib/rules/indent.js
- tests/lib/rules/keyword-spacing.js
[x] Bug fix (fixes https://github.com/eslint/eslint/issues/9539)
This corrects some tests which used `super` in an invalid way, and are
now failing due to an acorn upgrade.
> Fix: invalid tests with super (fixes #9539)

- docs/rules/id-match.md
The current documentation for `id-match` mentions that the rule has performance problems for complex rules. This seems a bit misleading to me; the rule does have to match a user-provided regex against all identifiers, but I think the documentation exaggerates how important this problem is in practice. Matching a regex against all identifiers seems unlikely to be a major performance bottleneck compared to some other rules which do much more performance-intensive tasks.
(I noticed this as a result of https://github.com/eslint/eslint/issues/9538.)
> Docs: improve id-match usage advice

- tests/lib/rules/object-property-newline.js
Add tests to an existing rule
Added tests for some code patterns not already tested for.
I would appreciate guidance on whether I am …
> Chore: Add object-property-newline tests to increase coverage.

- docs/rules/object-property-newline.md
Added examples to better show the rule’s coverage of cases.
> Docs: Add examples to better show rule coverage.

- lib/formatters/junit.js
- tests/lib/formatters/junit.js
This fixes JUnit parsing errors which treat no testcases as a failure (e.g. Atlassian bamboo).
On files that pass, a "passing" testcase should be added. Without any passing testcases, some JUnit parsers will fail, claiming that there are no tests. …
> Files with no failures get a "passing" testcase

- docs/user-guide/command-line-interface.md
- lib/cli-engine.js
- lib/config/config-file.js
- lib/config/plugins.js
- lib/util/naming.js
- tests/fixtures/cli-engine/node_modules/@somenamespace/eslint-formatter-foo/index.js
- tests/fixtures/cli-engine/node_modules/eslint-formatter-bar/index.js
- tests/lib/cli-engine.js
- tests/lib/config/config-file.js
- tests/lib/config/plugins.js
- tests/lib/util/naming.js
Attempt to solve [issue:5900](https://github.com/eslint/eslint/issues/5900).
CLIEngine#getFormatter will check if format is resolvable as `eslint-formatter-{format}`. Providing the …
> Update: Resolve npm installed formatters (#5900)

- lib/cli-engine.js
- lib/config/config-file.js
- package.json
This removes an indirect dependency on jsonify which is unlicensed and not needed in supported environments.  Doesn't yet slim down the installed size as `ajv` has the same dependency. A PR in its repo is also open epoberezkin/ajv#579
**What changes …
> Chore: Remove an indirect dependency on jsonify

- lib/config/config-validator.js
- tests/lib/config/config-validator.js
Stops error.data from being output as [object Object] when the data property
is an object, such as a rule’s options object.
4.10.0
9.0.0
5.5.1
**What …
> Fix: Correct [object Object] output of error.data.

- lib/ast-utils.js
- lib/rules/no-useless-call.js
- lib/rules/prefer-spread.js
- tests/lib/ast-utils.js
`isValidThisArg` is used both in `no-useless-call.js` and `prefer-spread.js`. placed it in ast-utils in case some other rules will use it.
> Chore: add isValidThisArg in ast-utils.

- lib/rules/object-curly-newline.js
- tests/fixtures/parsers/object-curly-newline/flow-stub-parser-multiline-type-literal.js
- tests/fixtures/parsers/object-curly-newline/flow-stub-parser-multiline.js
- tests/fixtures/parsers/object-curly-newline/flow-stub-parser-singleline-type-literal.js
- tests/fixtures/parsers/object-curly-newline/flow-stub-parser-singleline.js
- tests/lib/rules/object-curly-newline.js
The `object-curly-newline` rule made the assumption that the last token
is always `}`. However, when an object is typed with flow this is not
the case. This causes false positives, as described in https://github.com/babel/babel-eslint/issues/513. …
> Fix: object-curly-newline for flow code

- lib/rules/semi-style.js
- tests/lib/rules/semi-style.js
[X] Bug fix
* **ESLint Version:** 4.10.0
* **Node Version:** 8.9.0
* **npm Version:** 5.5.1
- default
- nothing
> [The online demo for `"first"` option](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgc2VtaS1zdHlsZTogW2Vycm9yLCBmaXJzdF0gKi9cclxuXHJcbntcclxuXHQ7IC8vIFNob3VsZCBiZSBpZ25vcmVkLiBJdCdzIHJlcG9ydGVkIGJ5IGBuby1leHRyYS1zZW1pYC5cclxufVxyXG5cclxud2hpbGUgKGEpXHJcblx0OyAvLyBTaG91bGQgYmUgaWdub3JlZCB0byBrZWVwIHRoZSBpbmRlbnRlZCBsb29wIGJvZHkuXHJcbmZvb1xyXG5cclxuZG9cclxuXHQ7IC8vIFNob3VsZCBiZSBpZ25vcmVkIHRvIGt …
> Fix: edge-cases of semi-style

- Makefile.js
This fixes an issue with the build process where the tests in [this file](https://github.com/eslint/eslint/blob/1073bc5a5af087c89d63e4a07f8ee690817d6dc8/tests/tools/eslint-fuzzer.js) weren't getting run, because `shelljs` was handling globs in an unintended way.
> Build: ensure fuzzer tests get run with `npm test`

- docs/rules/lines-around-comment.md
> Docs: Add missing `allowClassStart` and `allowClassEnd` in `lines-around-comment` options list

- appveyor.yml
> Build: use Node 8 in appveyor

- lib/util/safe-emitter.js
This fixes an incorrect comment in `safe-emitter.js`.
When I created this comment I forgot how to declare JSDoc typedefs, so I copy-pasted a typedef from somewhere else, but I forgot to change this line.
> Chore: fix incorrect comment in safe-emitter.js

- docs/rules/no-sequences.md
refs: https://github.com/eslint/eslint/pull/9465#issuecomment-338511025
no.
> Docs: disallow use of the comma operator using no-restricted-syntax

- docs/rules/no-restricted-imports.md
- lib/rules/no-restricted-imports.js
- tests/lib/rules/no-restricted-imports.js
https://eslint.org/docs/rules/no-restricted-imports
It adds more granularity to the existing rule.
**How will the change be implemented? (New …
> Update: no-restricted-imports - ability to check imported objects

- lib/rules/prefer-destructuring.js
- tests/lib/rules/prefer-destructuring.js
This fixes #9625 
- `tests/lib/rules/prefer-destructuring.js`: I added a test to reproduce #9625 
- `lib/rules/prefer-destructuring.js`: I updated a line to fix #9625  …
> Fix: prefer-destructuring says "Use destructuring" on "super" (#9625)
