README.md
This removes an incorrect punctuation mark from the readme.
=> Docs: remove extra punctuation from readme

lib/rules/space-in-parens.js, tests/lib/rules/space-in-parens.js
* **Node Version:** 8.9.1
* **npm Version:** 5.5.1
- default
- nothing
```js
/* eslint space-in-parens: [error, always, {}] */
1
```
> I couldn't get the URL of our online demo because it crashes. Please copy/paste then see devtools' console.
No errors.
A type …
=> Fix: space-in-parens crash

conf/environments.js, package.json
Fixes #9614.
Closes #9555.
This PR upgrades the dependency to `globals` package to `11.x` from `9.x` ([diff](https://github.com/sindresorhus/globals/compare/v9.17.0...v11.0.0#diff-1c916b21daa3b4eab4ea8661b409056c)).
Estimated effects:
- `no-undef` rule reports `System` variables (#9614).
- `no-shadow` and `no-redeclare` with `{builtinGlobals: true}` option no longer report `System` variables.
- `no-extend-native` rule reports about `Atomics` and `SharedBufferArray`.<br><br>
- ~~`node` environment no longer has the deprecated globals: `root`, `GLOBAL`, and …
=> Update: upgrade `globals` to 11.0.1 (fixes #9614)

lib/formatters/checkstyle.js, lib/formatters/jslint-xml.js, lib/formatters/junit.js, tests/lib/formatters/checkstyle.js, tests/lib/formatters/jslint-xml.js, tests/lib/formatters/junit.js
[x] Bug fix 
This should fix the problem reported in #9607
Changed all the XML headers to set the version to 1.1
=> Fix: Use XML 1.1 on XML formatters (fixes #9607)

conf/eslint-recommended.js, docs/rules/implicit-arrow-linebreak.md, lib/rules/implicit-arrow-linebreak.js, tests/lib/rules/implicit-arrow-linebreak.js
Introduces a new rule enforcing the location of arrow function bodies with implicit returns. Also adds tests and docs.
Refs: #9510 & #6067 
I think this rule gets a little less intuitive when it comes to function bodies surrounded by parentheses. 
I would like to make sure that this rule never warns on a case where parentheses are used to surround a multiline body, like this: 
```js
(foo) => (
bar
);
```
However, currently, it does warn on cases like: 
```js
// incorrect code for "beside" option
(foo) => 
(bar);
// incorrect code for "below" option
(foo) => (bar)
```
I'm not sure if that's the best way to handle …
=> New: Adds implicit-arrow-linebreak rule (refs #9510)

docs/rules/semi.md, lib/rules/semi.js, tests/lib/rules/semi.js
[X] Changes an existing rule: fixes #9521.
This PR adds a new option `beforeUnreliableLineButSafe` to `semi` rule. This option specifies the behavior about semicolons (or lacking semicolons) which satisfy the following two condition:
1. The semicolon (or lacking semicolon) is followed by the tokens which can make ASI hazard (`[`, `(`, `+`, `-`, or `` ` ``).
2. But the semicolon (or lacking semicolon) does not make ASI hazard because the next token does not connect to the previous statement.
For example:
```js
import a from "a"
[1,2,3].forEach(doSomething)
```
The option can be one of three values:
- `{ beforeUnreliableLineButSafe: "any" }` ignores the semicolons (or …
=> Update: add `beforeStatementContinuationChars` to semi (fixes #9521)

lib/rules/sort-vars.js, tests/lib/rules/sort-vars.js
The `sort-vars` rule can now automatically fix unsorted variable declarations when each variable is either unassigned or assigned to a literal value. I added the implementation for this fixer, test cases to validate that the fixer works as expected, and test cases to validate that it does not fix when a variable is assigned to a non-literal value.
In short, the fixer will convert `var c, b, a` to `var a, b, c` and `var b = 3, a = true` to `var a = true, b = 3` but **will not** fix `var b = f(), a = g()` or `var b = 5, a = b`.
All of it, please :confused:
=> Update: Add autofix for `sort-vars`

lib/formatters/checkstyle.js, lib/formatters/jslint-xml.js, lib/formatters/junit.js, tests/lib/formatters/checkstyle.js, tests/lib/formatters/jslint-xml.js, tests/lib/formatters/junit.js
This reverts commit 208fb0f3f8a42236e7324f9119d5791555fdb6f0.
[x] Other, please explain: Revert a breaking change.
Revert PR #9608.
This seems to be the wrong approach to fix #9607: Instead, ESLint errors should render the …
=> Revert "Fix: Use XML 1.1 on XML formatters (fixes #9607) (#9608)"

tests/lib/testers/rule-tester.js
Changes to the output of strictEqual are breaking the test suite
This minor adjustment to the regex will fix Node 10+ while keeping
support for older versions of node
=> test: fix test-suite to work with node master

docs/rules/max-len.md
I used the documented object-style configuration for the `max-len` rule in the docs, instead of the array-style `["error", 80, 4]`.
Nothing in …
=> Docs: Don’t use undocumented array-style configuration for max-len

docs/rules/camelcase.md, lib/rules/camelcase.js, tests/lib/rules/camelcase.js
What changes did you make? (Give an overview)
Fixes the bug reported in https://github.com/eslint/eslint/issues/8511 . I forked from https://github.com/eslint/eslint/pull/8529 and added a check for the right-side of the value assignment
Is there …
=> Update: update handling of destructuring in camelcase (fixes #8511)

tests/tools/internal-rules/no-invalid-meta.js, tools/internal-rules/no-invalid-meta.js
See #9534.
Added new lint error report for files that don't assign to `module.exports`, avoiding a crash that otherwise occurs later in the rule. …
=> Chore: no-invalid-meta crash if no export assignment (refs #9534)

lib/rules/camelcase.js, tests/lib/rules/camelcase.js
See #9700.
The camelcase rule has a subtle requirement that we keep track of both the original property/identifier name, as well as a version of the name with leading and trailing underscores …
=> Fix: camelcase destructure leading/trailing underscore (fixes #9700)

lib/rules/eol-last.js
Note that there are already tests asserting this behavior, but they aren't actually run in the rules. See https://github.com/eslint/eslint/issues/9534.
Add code to explicitly allow empty string …
=> Fix: eol-last allow empty-string to always pass (refs #9534)

lib/rules/lines-between-class-members.js, tests/lib/rules/lines-between-class-members.js
I fixed the bug of issue #9665 
=> Fix: `lines-between-class-members` (fixes #9665)

lib/rules/arrow-body-style.js, tests/lib/rules/arrow-body-style.js
https://github.com/eslint/eslint/issues/5498 gets more than twice as much traffic as any of our other issues. My interpretation of this fact is that people are often confused by errors from the `arrow-body-style` rule, and end up searching and finding that issue. This commit updates the error message for `arrow-body-style` to be more specific about how to fix the problem.
Any wording suggestions?
=> Chore: improve arrow-body-style error message (refs #5498)

docs/user-guide/getting-started.md
fixing a link. Currently, it goes to a 404
not really
=> Docs: fix the link to contributing page

docs/developer-guide/nodejs-api.md
I made the deprecated `message.source` property a little more subtle so that people don’t try to use it. I removed it from all of the examples, and adjusted the warning text at the end of the section …
=> Docs: Make the lint message `source` property a little more subtle

package.json
This version of debug addresses a minor ReDoS issue. See visionmedia/debug#501, visionmedia/debug#504 for more information. Looking at the rest of the changelog, this should be a pretty low-risk upgrade.
[x] Other, please explain: Dependency upgrade (reducing the risk of …
=> Upgrade: debug@^3.1.0

tests/lib/config/config-ops.js
Adds unit tests for `lib/config/config-ops.js`'s `pathMatchesGlobs` utility method. This does not include any changes to the implementation at all, and is intended to make it easier to grok any changes made while addressing #9740.
=> Chore: Add unit tests for overrides glob matching.

docs/rules/no-extra-parens.md
The doc lists two exceptions in a bulleted list and then adds a third
exception in prose. Move the prose to the bulleted list so it has three
items.
Changed the formatting of text in …
=> Docs: improve no-extra-parens formatting

docs/rules/array-callback-return.md, lib/rules/array-callback-return.js, tests/lib/rules/array-callback-return.js
Implements: #8539 
Added an `allowImplicit` option to `array-callback-return` that is consistent with the [`allowImplicit` option in `getter-return`](https://eslint.org/docs/rules/getter-return#option …
=> New: Add allowImplicit option to array-callback-return (fixes #8539)

docs/rules/valid-typeof.md
This example is intended to be an invalid `typeof` string, to illustrate that the rule reports an error if the user makes a typo like this. However, the spelling was inadvertently corrected in …
=> Docs: reintroduce misspelling in `valid-typeof` example

README.md, docs/developer-guide/working-with-rules.md, docs/rules/camelcase.md, docs/rules/eol-last.md, docs/rules/lines-between-class-members.md, docs/rules/no-array-constructor.md, docs/rules/no-div-regex.md, docs/rules/no-irregular-whitespace.md, docs/rules/no-lone-blocks.md, docs/rules/object-shorthand.md, docs/rules/sort-imports.md, docs/rules/space-before-keywords.md, docs/rules/vars-on-top.md, docs/user-guide/configuring.md
I fixed a few typos and adjusted capitalization.
=> Docs: Fix typos

docs/rules/one-var.md, lib/rules/one-var.js, tests/lib/rules/one-var.js
=> Update: support separate requires in one-var. (fixes #6175)

docs/maintainer-guide/releases.md
This updates the release guide to ensure that the release team adds the `post-release` label to the release issue when a patch release is pending.
* Should we give the `post-release` label a better name? I was thinking something like `patch release pending` would be more clear. If we do change this, we should also update the constant string in `eslint-github-bot`.
* With the bot running, I don't think it's necessary to leave a reminder comment about only merging semver-patch PRs, because the bot should prevent those PRs from being merged anyway. However, I left that comment for the time …
=> Docs: Add note about "patch release pending" label to maintainer guide

docs/developer-guide/working-with-plugins.md
A feature-detection mechanism for `scopeManager` and `visitorKeys` was implemented in https://github.com/eslint/eslint/commit/1c2aafdc03467ab3a3291b238f561f784b60616e, but was not documented. This PR documents it.
=> Docs: describe how to feature-detect scopeManager/visitorKeys support

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
See #9018.
Added `ignoreComments` option (default: false) to indent rule.
This seemed, um, simpler than I thought. Is there a more idiomatic …
=> Update: add `ignoreComments` option to `indent` rule (fixes #9018)

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
fixes #9774.
It showed `Allowed unused vars must match {varsIgnorePattern}.` for an unused *argument* without `argsIgnorePattern` specified.
=> Fix: incorrect error messages of no-unused-vars (fixes #9774)

docs/developer-guide/nodejs-api.md
Also standardize headers to ClassName#methodName so that it's easier to
keep track of the context.
- Add a table of contents to the Node.js API documentation
- Update headers so they consistently …
=> Docs: Add table of contents to Node.js API docs

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
Fixes https://github.com/eslint/eslint/issues/9755 by ignoring parens for sequence expressions in for-of statements 
Nope!
=> Fix: no-extra-parens false positive (fixes: #9755)

lib/testers/rule-tester.js, tests/lib/testers/no-test-runners.js
The assert message now is a little bit confused. It only tells you "`Output is incorrect.`", but doesn't specificly show the received value and the expected value.
This change is to make the assert …
=> Update: More detailed assert message for rule-tester

docs/developer-guide/nodejs-api.md, lib/cli-engine.js, tests/lib/cli-engine.js
[x] Add a CLI <del>option</del> <ins>method</ins>
- add CLIEngine#getRules() as discussed in [TSC](https://github.com/eslint/tsc-meetings/blob/3ef527b67712b5cecd0e2231dfb1a8a59a052155/notes/2017/2017-12-07.md#proposal-add …
=> New: CLIEngine#getRules() (refs #6582)

docs/rules/sort-imports.md
One of the blocks in rule `sort-imports` was missing language highlighting, added language as two previous blocks.
=> Docs: add sort-imports rule missing block language

docs/developer-guide/working-with-rules.md, lib/linter.js, lib/report-translator.js, lib/testers/rule-tester.js, lib/util/interpolate.js, tests/lib/report-translator.js, tests/lib/util/interpolate.js
Add something to the core
Fixes #6740.
I added a new `messageId` parameter to `context.report`:
```js
context.report({
messageId: 'foo'
})
```
This takes the value `foo` key from `meta.messages`:
```js
meta: {
// ...
messages: {
foo: "Your message here"
}
},
create(context) {
// ...
}
}
```
You can also use them in `RuleTester` tests:
```js
ruleTester.run('rule-name', rule, {
valid: [
// ...
],
invalid: [
{
code: 'Something here',
errors: [
{
messageId: 'foo'
// if you have {{ }} markers in your message, add a `data` key here:
// data: {
//   myKey: 'my value'
// }
}
]
}
]
})
```
---
If my example (`accessor-pairs`) looks good, I’ll be happy to …
=> New: Add context.report({ messageId }) (fixes #6740)

docs/developer-guide/working-with-rules.md
The `{{ name }}` gets replaced with an empty string when rendered on the site: https://eslint.org/docs/developer-guide/working-with-rules#messageids
Based on the above example where `{{ identifier …
=> Docs: fix substitution of {{ name }}

docs/rules/object-property-newline.md, lib/rules/object-property-newline.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/object-property-newline.js
Object option `allowMultiplePropertiesPerLine` is stricter than the name implies.
It creates an exception to `object-property-newline` only if ALL properties are
on a SINGLE line. Renamed accordingly. Old name left deprecated, and 2 tests with
deprecated name (1 valid and 1 invalid) left in force.
[ ] Add …
=> Update: Rename and deprecate misnamed option

docs/developer-guide/nodejs-api.md
The `RuleTester` documentation says that column numbers in `RuleTester` are considered to be 0-based, but in reality the column numbers are considered to be 1-based. This commit corrects the documentation.
=> Docs: fix misleading info about RuleTester column numbers

docs/rules/keyword-spacing.md
Changed all instances of "not conflict" to "no conflict" in the "keyword-spacing" documentation.
I hope "not conflict" means the same as "no conflict".
=> Docs: Typo in "keyword-spacing" documentation?

lib/rules/prefer-destructuring.js, tests/lib/rules/prefer-destructuring.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9784)
This fixes the `prefer-destructuring` bug described in https://github.com/eslint/eslint/issues/9784.
=> Fix: prefer-destructuring error with computed properties (fixes #9784)

lib/rules/indent.js, tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9729)
This updates the `indent` rule to fix an issue where comments would interfere with token logic.
=> Update: fix indent bug on comments in ternary expressions (fixes #9729)

lib/config/config-validator.js, lib/linter.js, tests/lib/linter.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9373)
This updates `Linter` to treat malformed configuration comments as linting errors rather than fatal issues that crash the process. Previously, this could cause surprising behavior because it was the only known instance where a problem in the source code (given a valid configuration) could cause an error to be thrown.
For example, this also fixes https://github.com/eslint/eslint.github.io/issues/413.
=> Fix: avoid crashing on malformed configuration comments (fixes #9373)

lib/rules/indent.js, tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9061)
This updates the `indent` rule to handle multiline template arguments correctly to fix the issue described in https://github.com/eslint/eslint/issues/9061.
=> Update: fix indent behavior on template literal arguments (fixes #9061)

lib/rules/valid-jsdoc.js, package.json, tests/lib/rules/valid-jsdoc.js
`valid-jsdoc`
The same amount
New default behavior
```js
/**
* @param {number} a
* @param {number} notB
*/
function foo(a, b) {}
```
It reports the entire JSDoc comment to indicate that the second parameter name is wrong.
It will report only the text `@param {number} notB` in the comment to indicate that the …
=> Update: use doctrine range information in valid-jsdoc

docs/developer-guide/working-with-rules.md
Small changes to messageId code samples to match style of other examples on the ESLint site.
Not really.
=> Docs: Sync messageId examples' style with other examples

tools/internal-rules/.eslintrc.yml, tools/internal-rules/consistent-docs-description.js, tools/internal-rules/consistent-docs-url.js, tools/internal-rules/no-invalid-meta.js
[x] Other, please explain: Deactivating consistent-docs-url rule on our other internal rules, since we intentionally don't document them
Deactivated consistent-docs-url rule on our other internal rules, since we intentionally …
=> Chore: Deactivate consistent-docs-url in internal rules folder

docs/rules/no-useless-escape.md
Fix `correct` examples for `no-useless-escape`.
* https://eslint.org/docs/rules/no-useless-escape
Currently, the correct example occurs `no-useless-escape` errors.
So I've fixed the examples. …
=> Docs: Fix examples for no-useless-escape

docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, docs/user-guide/configuring.md, lib/options.js
Users must use --no-eslintrc to prevent `.eslintrc.*` files from being used
See #9535.
* Switched the order of `--no-eslintrc` and `-c` options in CLI help
* Clarified that `-c` will merge with …
=> Docs: Clarify that -c configs merge with `.eslintrc.*` (fixes #9535)

lib/rules/no-eq-null.js, tests/lib/rules/no-eq-null.js
* **Node Version:** doesn't matter
* **npm Version:** doesn't matter
Default, but doesn't matter
**Please show your full …
=> Fix: Removing curly quotes in no-eq-null report message

lib/linter.js, lib/report-translator.js
I fixed the `docs` script that was failing due to JSDoc syntax errors.
- JSDoc doesn't yet support specifying array content, i.e. "[number,
number]" is a syntax error, so I'm using "number[]" instead. (source:
https://github.com/jsdoc3/jsdoc/issues/1073)
- JSDoc doesn't support multiline objects, e.g. returning report information
was a syntax error, so I extracted it into a typedef, as well as the
disable directive.
- I added two additional `@typedef`s, which now show up in the docs. Is that acceptable or should I inline them?
- The `[number, number]` syntax isn't a valid way to describe arrays, so I had to turn …
=> Build: Fix JSDoc syntax errors

docs/rules/comma-style.md, lib/rules/comma-style.js, tests/lib/rules/comma-style.js
comma-style
more, if new option is enabled
New …
=> Update: Add NewExpression support to comma-style

lib/rules/guard-for-in.js, tests/lib/rules/guard-for-in.js
=> Update: allow continue instead of if wrap in guard-for-in (fixes #7567)

docs/rules/no-undef.md
Added a sentence to `no-undef` mentioning the `globals` key.
=> Docs: Mention the `globals` key in the no-undef docs

docs/developer-guide/working-with-rules.md
Fixes #9889.
I updated the `messageId` example to correctly use the message API. I also made the code formatting match the rest of ESLint. …
=> Docs: Fix the messageId example (fixes #9889)

docs/rules/space-unary-ops.md, lib/rules/space-unary-ops.js, tests/lib/rules/space-unary-ops.js
* **ESLint Version:** 4.16.x / master
* **Node Version:** 8.9.3
* **npm Version:** 4.1.1
Default
(See demo link …
=> Update: space-unary-ops uses astUtils.canTokensBeAdjacent (fixes #9907)

.github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md, docs/developer-guide/contributing/changes.md, docs/developer-guide/contributing/new-rules.md, docs/developer-guide/contributing/reporting-bugs.md, docs/developer-guide/contributing/rule-changes.md, templates/rule-change-proposal.md, templates/rule-proposal.md
This change utilizes GitHub's new [multiple issue and pull request templates feature](https://github.com/blog/2495-multiple-issue-and-pull-request-templates) to make it so that users don't have to copy and paste the the template questions manually …
=> Docs: Use GitHub Multiple PR/Issue templates

lib/util/npm-util.js
=> Fix: Typo in error message when running npm

docs/developer-guide/working-with-rules.md
This removes the recommendation that rule names be very short and use abbreviations. In the gitter channel a few days ago, there was some consensus that the recommendation was outdated and could lead to confusing rule names.
=> Docs: remove outdated rule naming convention

docs/rules/max-len.md
[ ] Bug fix (template)
[ ] New rule (template)
[ ] Changes an existing rule (template)
Proposed change to the documentation for the `max-men` rule, specifically, the `ignorePattern` example (https://eslint.org/docs/rules/max-len#ignorepattern).
Proposed change is to add a `\` to the `ignorePattern` example to properly escape the final `(`.
The current example of `"ignorePattern": "^\\s*var\\s.+=\\s*require\\s*\("` results in an error due to the invalid escape character in the string because the final open parentheses character isn't …
=> Docs: Fix typo in max-len ignorePattern example.

docs/developer-guide/nodejs-api.md, docs/rules/valid-typeof.md
=> Docs: Propose fix typo for function

docs/user-guide/configuring.md, lib/linter.js, tests/lib/linter.js
[ X] Add something to the core
Updated block comments to support `eslint-disable-line` and `eslint-disable-next-line`
Nope!
=> Update: support eslint-disable-* block comments (fixes #8781)

docs/rules/key-spacing.md
Categorized key-spacing options based on their values.
No
=> Docs: clean up key-spacing docs (fixes #9900)

docs/rules/no-mixed-operators.md
Improved documentation for `no-mixed-operators` rule - `allowSamePrecedence` option.
N/A
=> Docs: no-mixed-operators - fixes #9962

lib/rules/keyword-spacing.js, lib/rules/no-await-in-loop.js, lib/rules/object-shorthand.js, lib/rules/require-await.js, tests/lib/rules/generator-star-spacing.js, tests/lib/rules/keyword-spacing.js, tests/lib/rules/no-await-in-loop.js, tests/lib/rules/no-useless-computed-key.js, tests/lib/rules/object-shorthand.js, tests/lib/rules/require-await.js
[X] Bug fix
Fixes #9891.
This PR fixes false positive and wrongly autofix about async iteration.
- b80d41a fixed `keyword-spacing` rule to check the spacing between `await` and `(` in `for-await-of` loops.
- 8c0e801 fixed `no-await-in-loop` rule to not report await expressions on `for-await-of` loops and to report `for-await-of` loops as same as await expressions.
- a64e8fe fixed `object-shorthand` rule to fix async generators correctly.
- 1c977b4 fixed `require-await` rule to handle `for-await-of` loops as same as await expressions.
- e30dd5f added tests to `generator-star-spacing` rule for async generators.
- 4a2a6a2 added tests to `no-useless-computed-key` rule for …
=> Fix: support Async iteration (fixes #9891)

docs/rules/object-curly-newline.md, lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-newline.js
Resolves #8501 
Added configuration for named imports and exports.
Due to code reuse, the config allows for the `consistent` option which acts …
=> Update: add named imports and exports for object-curly-newline

lib/rules/indent.js, tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9882)
This updates the `indent` rule to avoid setting the offset of the right-hand side of a `BinaryExpression` to depend on the token after the operator, which was unnecessary and could cause problems when the right-hand side of the expression was ignored.
=> Update: fix indent bug with binary operators/ignoredNodes (fixes #9882)

lib/util/glob-util.js
I attempted a brief review of `eslint` with performance in mind and I found (just) a few quick wins.
Running the repo's `lint` task with `--debug` I first noticed that the ignore file processing …
=> Chore: Apply memoization to config creation within glob utils

docs/user-guide/configuring.md
We have released Rest/Spread Properties formally in 4.18.0, so the option `experimentalObjectRestSpread` has finished its role.
I should make this change in #9943, but I forgot it.
=> Docs: deprecate experimentalObjectRestSpread

docs/rules/key-spacing.md
Fixed typo in the list of allowed string values for `mode` option in the rule `key-spacing` (said `"miniumum"` instead of `"minimum"`).
=> Docs: Fixed typo in key-spacing rule doc

lib/rules/no-await-in-loop.js, tests/lib/rules/no-await-in-loop.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9992)
This fixes a regression in https://github.com/eslint/eslint/commit/f012b8c7802e702a69ea8b3522cdc4c7842f038c where `no-await-in-loop` started reporting the surrounding loop node rather than the `AwaitExpression` node. As a result, some `eslint-disable` comments broke and caused more errors because they were on the wrong line.
=> Fix: ensure no-await-in-loop reports the correct node (fixes #9992)

lib/rules/max-len.js, tests/lib/rules/max-len.js
Fixes #9954.
Previously, `getAllStrings` only filter for tokens with type `String`. The filter should check if the token type is `JSXText` as well. …
=> Fix: Make max-len ignoreStrings ignore JSXText (fixes #9954)

.eslintrc.js, tests/lib/testers/no-test-runners.js, tests/tools/internal-rules/no-useless-catch.js, tools/internal-rules/no-useless-catch.js
This commit removes an unnecessary `catch` clause from the codebase that just rethrows the error. It also adds an internal linting rule to avoid code like that in the future.
=> Chore: avoid useless catch clauses that just rethrow errors

lib/linter.js
This makes a few improvements to directive comment processing in `linter.js`:
* Avoids internally adding some unrelated properties to config objects
* Fixes some code duplication
* Avoids some unnecessary branches
Note: it might be useful to view the diff with whitespace changes omitted ([link](https://github.com/eslint/eslint/pull/10007/files?w=1))
=> Chore: refactor directive comment processing

conf/environments.js, lib/linter.js, tests/lib/linter.js
This refactors `linter.verify` to simplify the dataflow throughout the function, and separate out some parts when possible. Specifically:
* Rules are now run as part of a separate function
* Environments are now resolved once, as opposed to several times in different places for `parserOptions` and `globals`.
* The defaults for `linter.verify` are now processed into a consistent object in a separate function.
This should make it easier to implement https://github.com/eslint/eslint/issues/9998.
=> Chore: Simplify dataflow in linter.verify

lib/util/interpolate.js
Change template substitution regex to exclude fields with whitespace.
This addresses possible O(n^2) catastrophic backtracking behavior.
The function behavior is unchanged.
Very unlikely to be …
=> Fix: remove catastrophic backtracking vulnerability

lib/linter.js
This is a refactoring that moves the logic for loading parsers out of `linter._verifyWithoutProcessors` and into the `parse` function, for the purpose of simplifying `linter._verifyWithoutProcessors`.
=> Chore: refactor parser-loading out of linter.verify

lib/linter.js
This fixes an incorrect JSDoc comment about the return value of `linter.verify` when there are no linting problems.
=> Chore: fix incorrect comment about linter.verify return value

README.md
Update the information about supported ES versions to FAQ.
No.
=> Docs: Update ECMAScript versions in FAQ

lib/rules/indent.js, tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9878)
This fixes a bug in the `indent` rule where a line comparison with the end of a token would use the end location of any trailing whitespace in the token, rather than the location of the last non-whitespace character in the token. This behavior went against user intuition for tokens with trailing whitespace.
=> Update: Correctly indent JSXText with trailing linebreaks (fixes #9878)

lib/rules/indent.js, tests/lib/rules/indent.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9995)
This updates the `indent` rule to ensure that the tokens in a non-ignored node are always indented at least as much as the first token of the node. This fixes an issue where some tokens would not have enough indentation if their node's listener did not explicitly give them an offset.
=> Update: give a node at least the indentation of its parent (fixes #9995)

docs/rules/quote-props.md
The removed part seems wrong, like copy-paste artifact.
No. Sorry if I am wrong.
=> Docs: fix possible typo

lib/rules/no-buffer-constructor.js
Wraps `Buffer()` in backticks in the `no-buffer-constructor` rule description
Adds further consistency to already backtick'd code in rule docs and descriptions:
> …
=> Docs: Wrap `Buffer()` in backticks in `no-buffer-constructor` rule description

docs/rules/one-var.md, lib/rules/one-var.js, tests/lib/rules/one-var.js
=> Update: consecutive option for one-var (fixes #4680)

Makefile.js
[x] Other, please explain: Added a message "Running unit tests" to help indicate to developers when `npm test` has transitioned from linting to unit tests. Not high-value but does slightly improve the developer experience. …
=> Chore: Adding log at beginning of unit tests in Makefile.js

lib/config/plugins.js
[x] Other, please explain: Adding some debug logs for successful plugin loads, to help users detect if plugin versions don't match expectations.
Added some debug logging to lib/config/plugins.js on successful plugin load. …
=> Chore: Adding debug logs on successful plugin loads

docs/rules/guard-for-in.md
It's unclear that the for...in example of correct usage is showing 2 different options. I split them into 2 separate examples.
No
=> Docs: Update ambiguous for...in example for guard-for-in

lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-newline.js
minProperties only tracks ImportSpecifier and ExportSpecifier nodes
See #10101.
The `object-curly-newline` rule used to count all `specifiers` under an `ImportDeclaration` or `ExportDeclaration` node …
=> Fix: object-curly-newline minProperties w/default export (fixes #10101)

lib/rules/no-invalid-regexp.js, tests/lib/rules/no-invalid-regexp.js
`flags` was Initialized to `""`, but sometimes it could be `null` -- this might cause confusing.
no. 😃
=> Fix: no-invalid-regexp not understand variable for flags (fixes #10112)

lib/rules/no-cond-assign.js, tests/lib/rules/no-cond-assign.js
Addresses issue https://github.com/eslint/eslint/issues/10091
Made the `no-cond-assign` rule also check for ternaries.
=> Update: Make no-cond-assign work for ternaries (fixes #10091)

docs/developer-guide/working-with-rules.md, lib/report-translator.js, lib/testers/rule-tester.js, tests/fixtures/testers/rule-tester/messageId.js, tests/lib/rules/no-fallthrough.js, tests/lib/testers/rule-tester.js
This PR:
- Makes `RuleTester` compare `messageId` in the test to `messageId` in the runtime error.
- Fixes an issue with `tests/lib/rules/no-fallthrough.js` where the wrong message and type data was being passed through. …
=> Fix: Make rule-tester strictly check messageId. (ref #9890)

bin/eslint.js, docs/user-guide/command-line-interface.md, lib/cli.js, tests/bin/eslint.js, tests/lib/cli.js
This updates the CLI to use an exit code of 2 for configuration errors or crashes. As described in https://github.com/eslint/eslint/issues/9384, this is useful for integrations to distinguish between successful lint runs with errors and unsuccessful lint runs.
=> Breaking: use an exit code of 2 for fatal config problems (fixes #9384)

docs/developer-guide/nodejs-api.md, docs/developer-guide/working-with-custom-formatters.md, lib/linter.js, lib/report-translator.js, lib/util/apply-disable-directives.js, tests/lib/cli-engine.js, tests/lib/formatters/json.js, tests/lib/linter.js, tests/lib/report-translator.js, tests/lib/util/apply-disable-directives.js, tests/tools/eslint-fuzzer.js
This removes the `source` property from individual linting messages, as described in https://github.com/eslint/eslint/issues/7358. The property has been deprecated since October 2016.
=> Breaking: remove `source` property from linting messages (fixes #7358)

docs/developer-guide/working-with-plugins.md, lib/linter.js, lib/util/source-code.js, tests/lib/linter.js, tests/lib/util/source-code.js
This updates `linter` to perform a traversal before rules run in order to set the `parent` property, and store all the traversed nodes in a queue to invoke the listeners afterwards. (See https://github.com/eslint/eslint/issues/9122 for more information.)
This was originally merged in https://github.com/eslint/eslint/commit/1488b511f3be3220d6f187f48c8b22075c6bbd30, but was reverted because it broke a couple of rules. The issue was re-accepted as a breaking change.
=> Breaking: set `parent` of AST nodes before rules run (fixes #9122)

lib/api.js
#9270
I  made `require('eslint').linter` non-enumerable so people aren’t tempted to use it.
Is this actually a breaking change? The ESLint API …
=> Breaking: Make require('eslint').linter non-enumerable (fixes #9270)

tests/tools/internal-rules/no-invalid-meta.js
[x] Other, please explain: Follow-up to #9698.
Uncommented a test that should be invalid but is currently valid, so fails RuleTester. Depends on #9534.
Not really. Just …
=> Chore: Uncommented test for empty program for no-invalid-meta

lib/report-translator.js, tests/lib/linter.js, tests/lib/report-translator.js
This updates ESLint core to throw an error when a rule reports a problem without providing a report message, as described in https://github.com/eslint/eslint/issues/10011.
=> Breaking: require rules to provide report messages (fixes #10011)

README.md
Remove eslint vs jshint justification from the FAQ. eslint is vastly more popular than jshint these days, I don't think there is a need to justify its existence anymore. …
=> Docs: remove eslint vs jshint from faq

docs/rules/capitalized-comments.md
Added `d` to the end of `capitalize` to make it `capitalized` in two places.
=> Docs: Update capitalized-comments with missing letters (fixes #10135)

docs/user-guide/command-line-interface.md
Moved sections and options around in long-form descriptions of the CLI options to match the current sections and options as shown by `node bin/eslint.js --help` …
=> Docs: Ensure CLI doc sections match command line help order

lib/formatters/html-template-message.html
…urity risk.
External links without noopener/noreferrer are a potential security risk.
=> Chore: add noopener/noreferrer 

lib/util/glob-util.js
While working on https://github.com/eslint/eslint/pull/10143 I noticed that the `addFile` function in `glob-util` was very complex and hard to read. I refactored it to make it more readable.
=> Chore: refactor --no-ignore flag logic

lib/config/plugins.js, lib/util/naming.js, tests/fixtures/plugin-shorthand/basic/.eslintrc.json, tests/fixtures/plugin-shorthand/basic/node_modules/@scope/eslint-plugin/index.js, tests/fixtures/plugin-shorthand/extends/.eslintrc.json, tests/fixtures/plugin-shorthand/extends/node_modules/@scope/eslint-plugin/index.js, tests/lib/cli-engine.js, tests/lib/util/naming.js
Fixes #9903.
This is a reference implementation for #9903.
This PR changes the logic to normalize plugin names as same as shareable config's.
As the result, we can use `plugins: ["@scope"]` shorthand …
=> Breaking: support @scope shorthand in plugins (fixes #9903)

package.json, tests/lib/linter.js
Remove a dependency.
Replace `esprima-fb` usage in tests by `esprima`
No.
=> Chore: Remove `esprima-fb` dependency.

package.json, tests/lib/rules/no-restricted-syntax.js
See #8733.
Upgraded esquery to ^1.0.1. This pulls in a bugfix for #8733.
Do we want to add unit tests to the no-restricted-syntax rule to try …
=> Upgrade: esquery@^1.0.1 (fixes #8733)

lib/rules/no-case-declarations.js, tests/lib/rules/no-case-declarations.js
`no-case-declarations` is now on the variable declaration statement instead of the SwitchCase.
=> Fix: report no-case-declarations from declarations (fixes #10048)

lib/rules/no-return-await.js
We don't have plans to add no-return-await to recommended, according to https://github.com/eslint/eslint/issues/8865
Remove an incorrect comment implying we had decided to make `no-return-await` …
=> Chore: Remove misleading comment.  

tests/lib/config/config-initializer.js
This updates the tests for config-initializer to always restore `process.cwd()` back to its original location if an assertion fails. Previously, the CWD would end up incorrect if one of the assertions failed, so a large number of other tests would also fail at the same time due to the incorrect CWD.
=> Chore: avoid modifying global state when tests fail

lib/util/ajv.js, package.json
[x] Other, please explain: Upgrade ajv dependency (JSON schema validator)
Upgraded ajv to ^6.0.1. Also had to change the way the Ajv instance was initialized per the release notes. …
=> Upgrade: ajv@^6.0.1, still using json schema draft 04

docs/rules/no-unused-vars.md, lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
See #9909.
The `no-unused-vars` rule was changed some time ago (likely unintentionally) to only report the last unused parameter when using the `args: "after-used"` setting. This resulted in poor UX …
=> Breaking: no-unused-vars reports all after-used params (fixes #9909)

Makefile.js, lib/file-finder.js, lib/linter.js, lib/logging.js, lib/report-translator.js, lib/rules/no-irregular-whitespace.js, lib/rules/no-shadow.js, lib/rules/no-undefined.js, lib/timing.js, lib/util/safe-emitter.js, packages/eslint-config-eslint/default.yml, tests/lib/ast-utils.js, tests/lib/cli-engine.js, tests/lib/cli.js, tests/lib/config.js, tests/lib/config/config-initializer.js, tests/lib/ignored-paths.js, tests/lib/util/glob-util.js, tests/lib/util/source-code-util.js
This enables the `prefer-rest-params`, `prefer-spread`, and `rest-spread-spacing` rules on the ESLint codebase.
This is blocked on https://github.com/eslint/eslint/pull/10074 (and the tests will fail …
=> Chore: enable rest/spread rules on ESLint codebase

bin/eslint.js, package.json
We use the `concat-stream` module to get source text from stdin when the `--stdin` flag is used. However, getting text from stdin is a one-liner without `concat-stream`, so it's not necessary to keep …
=> Chore: remove concat-stream dependency

conf/environments.js
This removes deprecated globals from the `browser`, `jest`, and `node` environments, as discussed in #10141.
=> Breaking: remove deprecated browser/jest/node globals (fixes #10141)

lib/linter.js, tests/lib/linter.js
This removes a compatibility hack for plugins that monkeypatched `linter` instances from rules with the `context._linter` property, as described in https://github.com/eslint/eslint/issues/10140.
=> Breaking: stop using fake `context._linter` property (fixes #10140)

docs/rules/getter-return.md
add backticks for `undefined` and `return`, and removed unnessary `;`
no~
=> Docs: add backticks in getter-return

docs/rules/no-mixed-spaces-and-tabs.md
I corrected the wording for the `smart-tabs` option in the `no-mixed-spaces-and-tabs` rule’s docs. Before, it implied that spaces would be used for indentation and tabs for alignment.
**Is there …
=> Docs: Correct wording in the `smart-tabs` docs page

lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
https://github.com/eslint/eslint/issues/10038
I added a check in the ```makeFunctionShorthand``` function that returns a null fixer if there is a comment between a functionExpression property key and …
=> Fix: do not autofix object-shorthand with comments (fixes #10038)

lib/config/config-validator.js, lib/linter.js, tests/fixtures/config-file/experimental-object-rest-spread/another-parser/.eslintrc.yml, tests/fixtures/config-file/experimental-object-rest-spread/another-parser/parser.js, tests/fixtures/config-file/experimental-object-rest-spread/basic/.eslintrc.yml, tests/fixtures/config-file/experimental-object-rest-spread/extends/.eslintrc.yml, tests/fixtures/config-file/experimental-object-rest-spread/extends/common.yml, tests/fixtures/config-file/experimental-object-rest-spread/subdir/.eslintrc.yml, tests/fixtures/config-file/experimental-object-rest-spread/subdir/lib/.eslintrc.yml, tests/lib/config.js, tests/lib/linter.js
[X] Other, please explain: fixes #9990
1. If `parserOptions.ecmaFeatures.experimentalObjectRestSpread` is given and `parserOptions.ecmaVersion` is less than `9`, `linter` enables `parserOptions.ecmaVersion: 9` for backward compatibility.
2. If `parserOptions.ecmaFeatures.experimentalObjectRestSpread` is given, `linter` generates a deprecation warning to show the deprecation.
I make the deprecation warning is as a message with `severity: 1`. Should it be with another way?
=> Update: re-enable experimentalObjectRestSpread (fixes #9990)

docs/rules/valid-jsdoc.md, lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
Also check for async function to determine if return is present.
=> Fix: valid-jsdoc does not know async function returns (fixes #9881)

lib/config/config-file.js, tests/lib/config/config-file.js
Fixes #9904.
This PR fixes plugin resolver in `extends` setting.
ESLint can handle `plugin:` prefix in `extends` setting, but it had resolved `plugin:` path with shareable config's resolver rather than plugin resolver. So it could load different plugin entity between `extends` setting and `rules` setting.
Now ESLint handle `plugin:` prefix with plugin resolver correctly.
This PR doesn't add any new test, but fixes some existing tests.
=> Breaking: fix plugin resolver in extends (fixes #9904)

lib/testers/rule-tester.js, tests/lib/testers/rule-tester.js
This improves the tests a bit by rewriting them to be independent of Node.js cores `assert` error messages, by switching to a better `isEqual` implementation (feature detecting the Node.js version) and by removing `assert.doesNotThrow`.
Fixes: …
=> Chore: improve errors

docs/developer-guide/working-with-rules.md, docs/user-guide/migrating-to-5.0.0.md, lib/linter.js, tests/lib/linter.js
[X] Bug fix
- Fixes #10246
- Fixes #10247
This PR removes the extra check in `getScope()` function. As a result, `context.getScope()` gets a better behavior on some AST nodes.
- `context.getScope()` returns `for` scope on `ForStatement`, `ForInStatement`, and `ForOfStatement` in `>=ES2015`.
- Currently it returns the parent scope of the correct scope. This means that it returns the parent `for` scope if `for` loop is nested. It was confusing.
- `context.getScope()` returns `catch` scope on `CatchClause` in `ES5`.
- Currently it returns the parent scope of the correct scope. 
- `context.getScope()` returns `with` scope on `WithStatement` in `>=ES5`.
- Currently it …
=> Breaking: remove extra check in getScope (fixes #10246, fixes #10247)

docs/user-guide/migrating-to-5.0.0.md
This makes a few grammatical changes to the migration guide. It also moves the `context.getScope` section higher up since it's more likely to affect rule authors than the changes below it.
=> Docs: make grammatical tweaks in migration guide

docs/user-guide/migrating-to-5.0.0.md
This removes some outdated notes from the migration guide.
No
=> Docs: remove outdated notes from migration guide

lib/cli-engine.js, tests/lib/cli-engine.js
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
https://github.com/eslint/eslint/issues/10076
I added a conditional expression to the CLIEngine constructor that throws an error if the ignorePath file name does not point to a file. Also added a …
=> Fix: Throw error when --ignore-path not a file (fixes #10076)

lib/config/plugins.js, messages/plugin-missing.txt
[x] Other, please explain: Adding the path to ESLint inside the plugin-missing message.
Added ESLint path (path to the package folder) to the plugin-missing template. This should hopefully allow users or team members to spot …
=> Chore: Add ESLint path to plugin-missing message

docs/user-guide/integrations.md
Added ALE as a suggested plugin for vim. Syntastic is a little dated because it doesn't offer asynchronous syntax checking. Also, standardjs only makes a small mention of Syntastic …
=> Docs: suggest a better vim linting engine

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md
Github introduced issue type selector, but the format needs to be updated to follow their guidelines. I tried using their UI, but it only supports up to 3 types, and we need 4. So modified those template manually.
Updated issue templates
Do we still need to links to other templates in the comments?
=> Chore: Update issue templates with new format

conf/default-cli-options.js, docs/developer-guide/nodejs-api.md, lib/util/glob-util.js, tests/lib/cli-engine.js, tests/lib/util/glob-util.js
Add `globInputPaths` CLIEngine option.
Set to false to skip glob resolution of input file paths to lint (default: true). If false, each input file paths is assumed to be a non-glob path to an existing file.
Should more doc be added somewhere else?
=> New: Add `globInputPaths` CLIEngine option (fixes #9972)

lib/rules/prefer-template.js, tests/lib/rules/prefer-template.js
https://github.com/eslint/eslint/issues/10031
Added a check for octal escape sequences in binary expressions. The```prefer-template``` rule does not attempt to fix binary expressions that contain …
=> Fix: do not autofix octal escape sequence (fixes #10031)

docs/rules/no-self-assign.md, docs/rules/object-curly-newline.md, docs/user-guide/migrating-to-5.0.0.md, lib/rules/no-self-assign.js, lib/rules/object-curly-newline.js, tests/lib/rules/no-self-assign.js, tests/lib/rules/object-curly-newline.js
[x] Changes an existing rule (see https://github.com/eslint/eslint/issues/10215)
This updates the default for `object-curly-newline` to `{ consistent: true }`, and updates the default for `no-self-assign` to `{ props: true }`.
=> Breaking: new object-curly-newline/no-self-assign default (fixes #10215)

conf/eslint-recommended.js, docs/rules/max-classes-per-file.md, lib/rules/max-classes-per-file.js, tests/lib/rules/max-classes-per-file.js
Enforce a maximum number of classes per file.
[x] Enforces code style
**Provide 2-3 code examples that this rule will warn about:**
```js
// incorrect with defaults
class Foo {}
class Bar {}
// correct with defaults
class Foo {}
// correct with excludeClassExpressions
class Foo {}
var Bar = class {};
```
**Why should this rule be included in ESLint (instead of a plugin)?**
It's a fairly common best practice many follow already.
=> New: add max-classes-per-file rule

conf/eslint-recommended.js, docs/rules/prefer-object-spread.md, lib/rules/prefer-object-spread.js, package.json, tests/lib/rules/prefer-object-spread.js
This is a follow up to #7230, we implemented `prefer-object-spread` internally at @airbnb.
The rule requires that you use an object spread over an `Object.assign` call with multiple arguments and an object literal as the first argument.
We also warn on cases where an `Object.assign` call is made using a single argument that is an object literal, in this case, the `Object.assign` is not needed (7f7f97d).
The following patterns are considered errors:
```js
Object.assign({}, foo)
Object.assign({}, {foo: 'bar'})
Object.assign({ foo: 'bar'}, baz)
Object.assign({ foo: 'bar' }, Object.assign({ bar: 'foo' }))
Object.assign({}, { foo, bar, baz })
Object.assign({}, { ...baz }) …
```
=> New: Adds prefer-object-spread rule (refs: #7230)

lib/config/config-ops.js
This removes code from `ConfigOps.isErrorSeverity` that was already present in `ConfigOps.getRuleSeverity`.
=> Chore: avoid code duplication in rule severity checking

lib/config/config-file.js
This avoids an unnecessary filesystem access when looking for config files by performing a `stat` syscall directly and catching an error if necessary, rather than first checking whether the file exists and then using `stat`.
=> Chore: avoid unnecessary filesystem accesses during config search

lib/rules/prefer-object-spread.js, tests/lib/rules/prefer-object-spread.js
https://github.com/eslint/eslint/issues/10344
Allow, eg:
```js
Object.assign({}, ...objects)
```
=> Fix: allow array spread for prefer-object-spread rule (fixes #10344)

lib/rules/arrow-body-style.js, tests/lib/rules/arrow-body-style.js
close #10372 
Allow:
```js
test = () => { return }
```
=> Fix: allow no tokens after `return` keyword (fixes #10372)

tests/.eslintrc.yml, tests/bin/eslint.js, tests/lib/cli.js, tests/lib/config.js, tests/lib/config/config-validator.js, tests/lib/ignored-paths.js, tests/lib/linter.js, tests/lib/testers/rule-tester.js, tests/lib/util/npm-util.js
The `assert.doesNotThrow` API is not useful and just slows down the test run by
catching errors and then rethrowing in case of an error. In case
there is no error, it is a noop.
Removed all …
=> Chore: remove assert.doesNotThrow in tests

lib/config/config-initializer.js, tests/lib/config/config-initializer.js
close #9918 
Change CLI behavior.
https://github.com/eslint/eslint/issues/9918
After user answered a series of questions, ESLint will compute and collect what npm modules should be installed. Then, …
=> New: prompt users before installing dependencies

bin/eslint.js, tests/bin/eslint.js
[x] Bug fix
* **Node Version:** 8.11.1
* **npm Version:** 5.6.0
N/A
N/A
This issue is simplest to reproduce with bash:
```bash
$ (echo 'a' && sleep 1 && echo 'b') | eslint --stdin --no-eslintrc
```
(I originally encountered this issue when using `curl` to fetch a JS file and pipe it to `eslint --stdin`.)
I expected ESLint to read stdin until the end (resulting in two lines of input), and then lint those two lines.
**What actually happened? …
=> Fix: ensure --stdin flag works when stdin is piped asynchronously

docs/rules/array-element-newline.md, lib/rules/array-element-newline.js, tests/lib/rules/array-element-newline.js
close #9457
https://github.com/eslint/eslint/issues/9457
Add a new option `"consistent"` for rule `array-element-newline`.
=> Update: Add "consistent" option to array-element-newline (fixes #9457)

lib/rules/prefer-object-spread.js, tests/lib/rules/prefer-object-spread.js
- Includes a change to stop warning if the if the file is importing `Object`. 
- Uses `context.getScope()` to determine is `Object` is being overwritten, instead of visiting every assignment and …
=> Update: Improves the prefer-object-spread rule by removing extraneous visitors

lib/config/config-validator.js, tests/lib/config/config-validator.js
[X] Bug fix
This PR fixes a bug that ESLint overlooks invalid `env` and `rules` option values in the `overrides` option. This is important to catch invalid rule options.
This might be a breaking change since it can throw new error on invalid configs.
=> Update: config-validator should validate overrides

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
close #9108
https://github.com/eslint/eslint/issues/9108
Allow:
```js
(function ({ a }) {
let b;
({ a, b } = obj);
})();
```
or
```js
let a;
{
let b;
({ a, b } = obj);
}
```
=> Fix: prefer-const object destructuring false positive (fixes #9108)

lib/config/config-initializer.js, tests/fixtures/config-initializer/new-es-features/new-es-features.js, tests/lib/config/config-initializer.js
[x] Bug fix
close #10003 
When running `eslint --init`, the CLI will ask user the ECMAScript version and whether using es6 globals.
Note that I haven't resolved ES7+ globals. This should be in another PR.
=> Fix: parse later ES files in `eslint --init` (fixes #10003)

lib/config/config-file.js, lib/ignored-paths.js, lib/util/npm-util.js, messages/failed-to-read-json.txt, tests/fixtures/ignored-paths/broken-package-json/package.json, tests/lib/config/config-file.js, tests/lib/ignored-paths.js, tests/lib/util/npm-util.js
close #10364 
Display better error message when failed to parse JSON.
=> Fix: prevent crashing from JSON parsing error (fixes #10364)

docs/user-guide/migrating-to-5.0.0.md
While updating `eslint-plugin-react` for the upcoming ESLint v5 I noticed some changes that were not addressed in the current [migration guide](https://eslint.org/docs/5.0.0/user-guide/migrating-to-5.0.0):
* The spread operators now always have the `SpreadElement` type, they previously had the `ExperimentalSpreadProperty` type when the `experimentalObjectRestSpread` was enabled.
* The spread operators now always have the `RestElement` type, they previously had the `ExperimentalRestProperty` type when the `experimentalObjectRestSpread` was enabled.
This is due that the backward compatibility is handled by forcing the `ecmaVersion` in …
=> Docs: Add rest and spread operator changes to migration guide

docs/rules/valid-jsdoc.md, lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
This option allows to skip specyfing parameters type in JSDoc comments. It is usefull in cases, when there are other type annotations available already - i.e. Flow type.
Having types both in JSDoc and other annotation is redundant
and may cause inconsistency.
Example:
```js
/*eslint valid-jsdoc: ["error", { "requireParamTypes": false, "requireReturnType": false }]*/
/**
* Add two numbers.
* @param num1 The first number.
* @param num2 The second number.
* @returns The sum of the two numbers.
*/
function add(num1: number, num2: number): number {
return num1 + num2;
}
```
[ ] New rule …
=> Update: Add requireParamType option to valid-jsdoc (fixes #6753)

lib/config/config-initializer.js
[x] Bug fix
When running `eslint --init`, if the user chooses `prompt` mode, write the config file with corresponding format.
=> Fix: fix writing config file when `source` is `prompt`

docs/README.md
The main purpose of this landing page is to allow users to view "https://eslint.org/docs", which currently is HTTP 404 on our site.
As a secondary benefit, this would also allow the landing page to be used as the launching point for Algolia's Docsearch crawler.
[ ] Other, …
=> Docs: Create docs landing page

README.md
See https://github.com/eslint/eslint/issues/9804#issuecomment-360810237.
[x] Other, please explain: Applying a policy update, so may need to be discussed at TSC meeting.
Updated README to clarify experimental language feature …
=> Docs: Add new experimental syntax policy to README (fixes #9804)

lib/rules/no-use-before-define.js, tests/lib/rules/no-use-before-define.js
[X] Bug fix: #10227
This PR does:
- fixes many false negatives of `no-use-before-define` rule.
- remove the accesses to `parserOptions` from the rule.
- adds several lacking tests to the rule.
The tests for `CatchClause` and `WithStatement` were lacking.
Please check the added tests to make a consensus.
=> Update: fix false negative in no-use-before-define (fixes #10227)

lib/rules/no-warning-comments.js, tests/lib/rules/no-warning-comments.js
Updated the RegExp to look for the term provided in the body of the comment, not just the beginning. 
Please review new test cases add/moved …
=> Update: Fixes multiline no-warning-comments rule. (fixes #9884)

lib/config.js, lib/ignored-paths.js
use `config.unshift()` to avoid calling `config.reverse()` -- more clear, and a little perf win.
no
=> Chore: small opt to improve readability

docs/rules/camelcase.md, lib/rules/camelcase.js, tests/lib/rules/camelcase.js
The `camelcase` rule.
Fewer.
A new option:
```js …
```
=> Update: Add ignoreDestructing option to camelcase rule (refs #9807)

docs/rules/valid-typeof.md
This was accidentally removed in #9965.
=> Docs: Restore intentional spelling mistake

lib/rules/no-catch-shadow.js, lib/rules/no-shadow-restricted-names.js, tests/lib/rules/no-catch-shadow.js, tests/lib/rules/no-shadow-restricted-names.js
Fixes #10392.
[X] Bug fix
~~[X] Other, please explain: Upgrade `espree` to support ES2019 syntax.~~
~~**Note**: this PR depends on `eslint/espree#upgrade-acorn-5.6` branch.~~
~~This PR upgrades `espree` to support ES2019 syntax.~~
This PR fixes the bug that it crashes on optional `catch` binding syntax in some core rules.
I searched rules with `/\.param\b/` then I fixed found two rules.
=> Upgrade: espree@next (fixes #10392)

docs/rules/func-name-matching.md, lib/rules/func-name-matching.js, tests/lib/rules/func-name-matching.js
Fixes #9926.
Change an existing rule.
`func-name-matching`
Fewer.
**How will the change be implemented?**
Add option `{ considerPropertyDescriptor: true }` to have rule do some additional checks on what the function name should be.
Previously only property key was checked. With this option enabled it will check if the property is within `Object.defineProperty`, `Object.defineProperties`, or `Object.create`.
```js
/** eslint func-name-matching: ["always", { "considerPropertyDescriptor": true }] */
Object.defineProperty(foo, 'bar', {
value: function baz() {}
})
```
**What …
=> Update: Add considerPropertyDescriptor option to func-name-matching

lib/rules/no-shadow-restricted-names.js, tests/lib/rules/no-shadow-restricted-names.js
[x] Bug fix
fix #10467 
@mysticatea said that this rule can be merged into the `no-shadow` rule, but I think this should be done in another commit/PR.
=> Fix: check destructuring for "no-shadow-restricted-names" (fixes #10467)

lib/code-path-analysis/code-path-analyzer.js, tests/fixtures/parsers/unknown-operators/unknown-logical-operator.js, tests/lib/linter.js
I modified the code path analysis code to explicitly check the operator of the logical expressions in order to create new code paths. This will allow users to use a custom parser that adds a new …
=> Fix: do not fail on unknown operators from custom parsers (fixes #10475)

docs/rules/no-process-exit.md
Added a recommendation to use `process.exitCode` instead of `process.exit()` if the goal is only to specify the exit code.
This was my main reason for using `process.exit()` for a long time. I only …
=> Docs: no-process-exit: recommend process.exitCode

docs/rules/max-lines-per-function.md
Fix the documentation for the max-lines-per-function rule to display the correct code's max value.
Verify that max value for the correct code …
=> Docs: Fix max-lines-per-function correct code's max value

lib/rules/valid-jsdoc.js, tests/lib/rules/valid-jsdoc.js
Original issue: https://github.com/eslint/eslint/issues/10386
For async functions with no return statements and `requireReturn:false`, allow the presence of `@returns` to be optional.
**Is there …
=> Fix: Change valid-jsdoc to allow returns to be optional for async functions in the requireReturn:false case (fixes #10386)

lib/rules/no-debugger.js, tests/lib/rules/no-debugger.js
[x] Bug fix (see https://github.com/eslint/eslint/issues/10242)
This removes the autofixer for `no-debugger`, as discussed in https://github.com/eslint/eslint/issues/10242.
=> Fix: Remove autofixer for no-debugger (fixes #10242)

docs/rules/no-implied-eval.md
Fixed the word "both" in docs that referred to three items.
It is really simple ;)
=> Docs: fix a word in no-implied-eval

docs/user-guide/command-line-interface.md
Added note to CLI docs that only successfully linted files are cached, and files which fail linting are not cached. (Note: Issue #9948 is a proposal to store even files which failed linting into the …
=> Docs: Only successfully linted files are cached (fixes #9802)

lib/code-path-analysis/code-path-analyzer.js, tests/fixtures/parsers/unknown-operators/unknown-logical-operator-nested.js, tests/lib/linter.js
Fixes #10560, after adding support in #10476.
=> Fix: do not fail on nested unknown operators

lib/formatters/stylish.js, tests/lib/formatters/stylish.js
Changes grammar of stylish to read more intuitively.
Adjusting a potentially confusing CLI message. Where (when reading quickly) a user may be confused about how many errors/warnings are potentially fixable with the `--fix` option. A comma may imply …
=> Adjust grammar of error/warnings fixable

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Fixes https://github.com/eslint/eslint/issues/10520
* Added tests for array destructuring assignment where the array has ignored / empty elements.
* Fixed a bug where trying to read the `name` …
=> Fix: Prefer-const rule crashing on array destructuring (fixes #10520)

docs/rules/sort-keys.md, lib/rules/sort-keys.js, tests/lib/rules/sort-keys.js
I caused the linter to ignore any key-ordering in an object that contains a spread operator. Previously, it would verify that any keys that were not themselves spread operators were in the correct …
=> Fix: sort-keys in an object that contains spread (fixes #10261)

docs/rules/max-lines-per-function.md
I made a change to the documentation for the `max-lines-per-function` rule to clarify the default values for the `skipComments`, `skipBlankLines` and `IIFEs` options. We originally read the `true` as …
=> Docs: Clarifies option defaults in max-lines-per-function docs

lib/rules/prefer-object-spread.js, package.json, tests/lib/rules/prefer-object-spread.js
[X] Bug fix: fixes #10512, fixes #10532
This PR fixes `prefer-object-spread` rule to generate valid code in autofix.
This PR is massive because it's hard to handle code correctly in text-based way.
The new way is token-based. Basically, it finds unnecessary tokens and removes those.
1. remove the callee (`Object.assign`).
2. replace the parentheses of the argument list to braces (`(` → `{`, `)` → `}`).
3. process arguments:
- if it's an `ObjectExpression` node, remove braces (and enclosing parentheses), and remove trailing comma if exists.
- otherwise, insert `...` before the argument.
I tried to make close formatting to the original, but there are some difference in …
=> Fix: prefer-object-spread duplicated comma (fixes #10512, fixes #10532)

Makefile.js, templates/blogpost.md.ejs
[x] Other, please explain: Build improvement to ensure that prerelease blog posts contain installation and migration guide information.
Added some logic to ensure that if we are doing a prerelease, that the info about …
=> Build: Include prerelease install info in release blog post

packages/eslint-config-eslint/default.yml
no-restricted-properties error message should be "Use assert.deepStrictEqual instead of assert.deepEqual."
=> Chore: fix error message in eslint-config-eslint

lib/testers/rule-tester.js
[X] Other, please explain: improve performance.
This PR removes a redundant equality check which was found in #10612.
```js
!util.isDeepStrictEqual(beforeAST, afterAST) || !lodash.isEqual(beforeAST, afterAST)
```
fixed to:
```js
!lodash.isEqual(beforeAST, afterAST)
```
As the result, `mocha --reporter progress tests/lib/rules/*.js` in our codebase gets 15% faster.
`lodash.isEqual` looks faster than `util.isDeepStrictEqual`.
See details: https://gist.github.com/mysticatea/1045687663c17f2a9f1488e92d9b3038
=> Chore: fix redundant equality check

lib/testers/rule-tester.js, package.json, packages/eslint-config-eslint/package.json
[X] Other, please explain: upgrade `eslint-plugin-node` to `7.0.1` for linting our codebase.
It has new features:
- It reports the APIs of Node.js built-in modules and globals if those are not supported on the configured Node.js versions (`^6.14.0 || ^8.10.0 || >=9.10.0`).
- It reports newly deprecated APIs.
I'm not sure if this `util.isDeepStrictEqual()` part is needed.
That looks to do double checking for the AST if `util.isDeepStrictEqual` exists. But why?
```js
// Feature detect the Node.js implementation and use that if available.
if ((util.isDeepStrictEqual && !util.isDeepStrictEqual(beforeAST, afterAST)) || …
```
=> Upgrade: eslint-plugin-node to 7.0.1

lib/linter.js
[x] Other, please explain: Change an `Object.assign.apply` call to use array spread instead.
Changed an `Object.assign.apply` call in Linter to use array spread instead. …
=> Chore: Fixing a call to Object.assign.apply in Linter

tests/lib/rules/prefer-object-spread.js
=> Chore: rm deprecated experimentalObjectRestSpread option in tests

lib/rules/key-spacing.js, lib/rules/no-unmodified-loop-condition.js, lib/rules/no-useless-return.js, lib/rules/prefer-const.js, lib/testers/rule-tester.js, lib/util/node-event-generator.js, tests/lib/rules/no-invalid-this.js, tests/lib/testers/rule-tester.js
[x] Other, please explain: Just replacing some calls to `Function.prototype.apply` by using spread operators (or, in a few cases, `Function.prototype.call`.
Replaced some function application with spread operators.
**Is there …
=> Chore: Replace some function application with spread operators

docs/developer-guide/nodejs-api.md, lib/cli-engine.js
This fixes some outdated documentation. The documentation for `baseConfig` implied the existence of a "default" configuration for normal linting runs, because the documentation hadn't been updated since we stopped enabling rules by default.
=> Docs: fix outdated description of `baseConfig` option

lib/rules/prefer-object-spread.js, tests/lib/rules/prefer-object-spread.js
=> Fix: ESLint crash with prefer-object-spread (fixes #10646)

lib/ignored-paths.js, tests/fixtures/ignored-paths/subdir/.eslintignoreInChildDir, tests/lib/ignored-paths.js
[x] Bug fix (https://github.com/eslint/eslint/issues/9227)
This fixes an issue where the default ignore patterns, such as `/node_modules`, would always be resolved from the location of an `.eslintignore` file. As a result of the bug, the `node_modules` folder in the project root directory would not be ignored if an `.eslintignore` file in a subdirectory was being used.
=> Fix: always resolve default ignore patterns from CWD (fixes #9227)

conf/eslint-recommended.js, docs/rules/require-atomic-updates.md, lib/rules/require-atomic-updates.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/require-atomic-updates.js
[x] New rule (https://github.com/eslint/eslint/issues/10405)
This adds a `require-atomic-updates` rule, designed to prevent possible race conditions as described in https://github.com/eslint/eslint/issues/10405. Specifically, the rule activates whenever (a) an assignment expression assigns to a new value that depends on its old value, and (b) the execution is interrupted with `await` or `yield` between reading the old value and assigning the new value. As an exception, the rule does not report an error if the assignment expression is assigning to a local variable, provided that the variable is never leaked outside of the surrounding function via a closure.
**Is there …
=> New: require-atomic-updates rule (fixes #10405)

lib/rules/indent.js, lib/rules/max-len.js, tests/lib/rules/indent.js
Also needed to ensure that comments between element lists have desired offsets set if first element is on same line as beginning of element list
See issue #9733.
Ensure that comments (which are the …
=> Update: indent comments w/ nearby code if no blank lines (fixes #9733)

packages/eslint-config-eslint/default.yml
it has been added in `node/recommended`(previous included just since it has not been released):
https://github.com/mysticatea/eslint-plugin-node/blob/master/lib/configs/recommended.json#L13
=> Chore: rm unnecessary plugin in eslint-config-eslint

lib/rules/padding-line-between-statements.js, tests/lib/rules/padding-line-between-statements.js
See issue #10487.
For the "function" statement type in padding-line-between-statements: Instead of relying on the `function` keyword token, just check to see if the node in question is a …
=> Update: Fix 'function' in padding-line-between-statements (fixes #10487)

docs/rules/prefer-object-spread.md
object spread is not just syntax sugar but actually performs better in browsers. The "When Not To Use It" section should therefore give a more nuanced opinion on when Object.assign is desireable. …
=> Changes rationale for Object.assign

lib/rules/line-comment-position.js, tests/lib/rules/line-comment-position.js
* **ESLint Version:** 5.2.0
* **Node Version:** v8.9.4
* **npm Version:** 5.6.0
```js
{
"env": { …
```
=> Update: Fix incorrect default value for position

lib/ignored-paths.js, tests/lib/ignored-paths.js
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
https://github.com/eslint/eslint/issues/10675
Only the parent folder was excluded. Added '*' at end to exclude parent of parent directory.
=> Fix: The "../.." folder is always ignored (fixes #10675)

lib/cli-engine.js, tests/lib/cli-engine.js
See issue #10679.
Changed CLIEngine so that it will not always used cached lint results. Specifically, if the cached lint result had errors and autofix has been turned on for the current CLIEngine …
=> Fix: ESLint cache no longer stops autofix (fixes #10679)

docs/rules/array-bracket-newline.md, docs/rules/array-element-newline.md, docs/rules/capitalized-comments.md, docs/rules/func-call-spacing.md, docs/rules/func-name-matching.md, docs/rules/func-names.md, docs/rules/indent-legacy.md, docs/rules/indent.md, docs/rules/line-comment-position.md, docs/rules/linebreak-style.md, docs/rules/lines-around-directive.md, docs/rules/lines-between-class-members.md, docs/rules/max-lines.md, docs/rules/multiline-ternary.md, docs/rules/no-tabs.md, docs/rules/no-useless-rename.md, docs/rules/nonblock-statement-body-position.md, docs/rules/object-curly-newline.md, docs/rules/object-property-newline.md, docs/rules/one-var.md, docs/rules/prefer-numeric-literals.md, docs/rules/sort-keys.md
I removed links to `jscs.info` domain, as they all lead to a site with info
```
The domain jscs.info is for sale. To purchase, call BuyDomains.com at 781-373-6841 or 844-896-7299. Click here for more …
```
=> Docs: remove links to terminated jscs.info domain

docs/rules/no-await-in-loop.md
Re: https://github.com/vkarpov15/mastering-async-await-issues/issues/1, I added another example of another case when you would want to avoid the `no-await-in-loop` rule. I'd like to make sure eslint …
=> Docs: add another example for when not to use no-await-in-loop

Makefile.js
This updates the website generation script to preserve URL fragments that appear after stripped `.md` extensions.
I manually tested this change by running `npm run gensite` and observing that the resulting URLs had fragments. I'm hoping that we will have an automated test setup for this logic at some point (see https://github.com/eslint/eslint/issues/8489).
=> Build: ensure URL fragments remain in documentation links (fixes #10717)

.eslintrc.js, lib/rules/.eslintrc.yml, packages/eslint-config-eslint/default.yml, tools/internal-rules/.eslintrc.yml
similar to https://github.com/eslint/eslint/pull/10566
no
=> Chore: use eslintrc overrides

tests/tools/internal-rules/consistent-docs-url.js, tools/internal-rules/consistent-docs-url.js
Issue ( #10722 )
- Added a check to report missing property if `metaDocs` is `null`
- Changed the `checkMetaDocsUrl` function
=> Fix: consistent-docs-url crashes if meta.docs isn't present

lib/rules/no-extra-parens.js
When I encountered this error, it was not unclear to me what the
problem was or what alternative would be preferred.
The input was:
```js
return ( { foo: 1, bar: 2 }[ key ] || 0 );
```
Receiving the following in Atom's footer:
```
eslint (0|4), Gratuitous parentheses around expression., Line 165, Column 17
```
=> Update: Improve no-extra-parens error message

tests/tools/internal-rules/no-invalid-meta.js, tools/internal-rules/consistent-docs-description.js, tools/internal-rules/consistent-docs-url.js, tools/internal-rules/no-invalid-meta.js
Issue ( #10750 )
- Added a check to prevent `getPropertyFromObject` trying to access the `length` property of `undefined`
- Changed the …
=> Fix: no-invalid-meta crashes for non Object values (fixes #10750)

docs/rules/array-bracket-newline.md, docs/rules/array-element-newline.md, docs/rules/capitalized-comments.md, docs/rules/func-call-spacing.md, docs/rules/func-name-matching.md, docs/rules/func-names.md, docs/rules/indent-legacy.md, docs/rules/indent.md, docs/rules/line-comment-position.md, docs/rules/linebreak-style.md, docs/rules/lines-around-directive.md, docs/rules/lines-between-class-members.md, docs/rules/max-lines.md, docs/rules/multiline-ternary.md, docs/rules/no-tabs.md, docs/rules/no-useless-rename.md, docs/rules/nonblock-statement-body-position.md, docs/rules/object-curly-newline.md, docs/rules/object-property-newline.md, docs/rules/one-var.md, docs/rules/prefer-numeric-literals.md, docs/rules/sort-keys.md
I "reverted" a recent pull request that removed links for JSCS rule names spread through the docs. I have replaced them with the new jscs-dev.github.io link target. …
=> Docs: Add jscs-dev.github.io links to rule names in docs

.eslintrc.js, lib/rules/for-direction.js, lib/rules/func-call-spacing.js, lib/rules/func-name-matching.js, lib/rules/func-names.js, lib/rules/func-style.js, lib/rules/function-paren-newline.js, lib/rules/generator-star-spacing.js, lib/rules/getter-return.js, lib/rules/no-magic-numbers.js, tests/lib/rules/for-direction.js, tests/lib/rules/func-call-spacing.js, tests/lib/rules/func-name-matching.js, tests/lib/rules/func-names.js, tests/lib/rules/func-style.js, tests/lib/rules/function-paren-newline.js, tests/lib/rules/generator-star-spacing.js, tests/lib/rules/getter-return.js, tests/lib/rules/no-magic-numbers.js, tests/tools/internal-rules/consistent-meta-messages.js, tools/internal-rules/consistent-meta-messages.js
+ add a interal rule: consistent-meta-messages
+ use messages in some rules
Not all the rules have to be changed in just one PR, I plan to …
=> Chore: use meta.messages in some rules (1/4)

docs/user-guide/command-line-interface.md, docs/user-guide/configuring.md
Adds cross links between .eslintignore and --ignore-pattern sections.
Adds link to --ignore-pattern section directing to .gitignore specs.
Adds description to .eslintignore section that emphasizes …
=> Docs: gitignore syntax updates (fixes #8139)

lib/formatters/codeframe.js, package.json
Bumping babel-code-frame to version 7. Note I didn't touch the babel version used in the build process, only code-frame.
=> Upgrade: babel-code-frame to version 7

lib/rules/max-params.js, tests/lib/rules/max-params.js
Update the max-params rule to only report the location of the method header. Some tools, like Nuclide, will otherwise highlight the entire body of the method, which makes the rule visually noisy in …
=> Update: max-params to only highlight function header

lib/rules/camelcase.js, tests/lib/rules/camelcase.js
See #10801 for description of behavior
Fixed the logic in `lib/rules/camelcase.js`, and added a test that would've been broken before the fix
Basically, there appears to have been faulty logic …
=> Fix: camelcase duplicate warning bug (fixes #10801)

lib/rules/no-constant-condition.js, tests/lib/rules/no-constant-condition.js
See #10826 for a description of the bug/environment
Made `no-constant-condition` behave the same with respect to generator `FunctionExpression`s as it does for generator `FunctionDeclaration`s
**Is …
=> Fix: respect generator function expressions in no-constant-condition

docs/developer-guide/nodejs-api.md
Updated code example to use `require("eslint").Linter` instead of `require("eslint").linter`.
Please make sure the code is correct. :)
=> Docs: Use Linter instead of linter in Nodejs API page

bin/eslint.js, tests/bin/eslint.js
Removed the extra console output that included just the error message and updated the associated tests.
No
=> Fix: Remove duplicate error message on crash (fixes #8964)

docs/rules/no-unneeded-ternary.md
The documentation for the no-unneeded-ternary rule seems to have a mistake. (https://github.com/eslint/eslint/issues/10872).
At one point, it mentions that a `||` should be used when the middle operand of the ternary is the same as the first:
```
// Bad
var foo = bar ? bar : 1;
// Good
var foo = bar || 1;
```
Later, however, it lists something seemingly identical to this as an example of correct code:
```
var a = x ? x : 1;
```
In my project, I was given a no-unneeded-ternary error for using this type of code, so the documentation seems to have an error. Either way, the documentation seems to list this sort of construct as both correct and incorrect, so one of those is probably in error.
Fixes #10872.
=> Docs: clarify defaultAssignment option, fix no-unneeded-ternary examples

tests/lib/config/config-validator.js, tests/lib/testers/rule-tester.js
This updates some failing tests to account for an error message change in the `ajv` dependency. The build is currently broken on master as a result of these tests, which is preventing other changes from being merged.
=> Build: fix failing tests on master

CONTRIBUTING.md, docs/developer-guide/contributing/README.md
This updates the documentation to tell people to use the [HackerOne program](https://hackerone.com/eslint) in order to report security issues.
=> Docs: add information about reporting security issues

lib/rules/one-var.js, tests/lib/rules/one-var.js
=> Fix: make separateRequires work in consecutive mode (fixes #10784)

lib/rules/require-atomic-updates.js, tests/lib/rules/require-atomic-updates.js
[x] Bug fix (https://github.com/eslint/eslint/issues/10893)
Previously, the `require-atomic-updates` rule would traverse over every path in the control flow graph, resulting in a runtime that was exponential in the number of edges in the graph. This commit updates the rule to use a lattice-based …
=> Fix: avoid exponential require-atomic-updates traversal (fixes #10893)

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/QUESTION.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md, .github/ISSUE_TEMPLATE/SECURITY.md
Add emoji to issue template selection screen for easier scanning.
=> Chore: Update issue templates

docs/rules/camelcase.md, lib/rules/camelcase.js, tests/lib/rules/camelcase.js
[ ] Bug fix
[ ] New rule
camelcase
No, only less if used.
New option to the rule.
```js
class MyComponent extends React.Component {
UNSAFE_componentWillMount() {
// ...
}
}
```
It throw an error: `Identifier 'UNSAFE_componentWillMount' is not in camel case.` …
=> Update: camelcase rule ignoreList added

docs/user-guide/command-line-interface.md
Removed old note and added new note per consideration from  @platinumazure 
No.
=> Docs: Replace old note about caching with a new one considering autofixes (fixes #10739)

docs/rules/space-infix-ops.md
I added the usual _'When Not To Use It'_ section to the docs of `space-infix-ops`.
I'm not sure if there's anything else that's usually …
=> Docs: Add 'When Not To Use' section to space-infix-ops

package.json, tests/lib/rules/no-invalid-regexp.js
[X] Bug fix: fixes #10861.
This PR upgrades `regexpp` package to 2.0.1 which fixed this bug (https://github.com/mysticatea/regexpp/commit/0dc0b654b54054bef039a84f2e18cc53eb0b3821), and adds a test case.
=> Fix: no-invalid-regexp disallows \ at end of pattern (fixes #10861)

docs/rules/no-unsafe-finally.md
The comment erroneously said `1 is returned` but the value returned is `0`.
=> Fix typo for no-unsafe-finally

lib/rules/one-var.js, tests/lib/rules/one-var.js
https://github.com/eslint/eslint/issues/10937
If there is no `tokenAfterDeclarator` when mapping over the declarators, `return null` rather than attempt to access a property on the `null` object. …
=> Fix: Cannot read property 'range' of null error with one-var (#10937)

lib/rules/space-infix-ops.js
`space-infix-ops` is a bit overcomplicated. there can be a lot of tokens between `left` and `right`, but only one of them can be an infix operator, the others must be opening and closing parens. if …
=> Chore: Simplify space-infix-ops

lib/rules/no-unused-vars.js, tests/lib/rules/no-unused-vars.js
#10952
Added check to `isAfterLastUsedArg()` to recognize variables used by `context.markVariableAsUsed()`
I did not check other situations for …
=> Fix: no-unused-vars false pos. with markVariableAsUsed (fixes #10952)

lib/rules/no-extra-bind.js, tests/lib/rules/no-extra-bind.js
Ensure autofix is only performed if the argument to `.bind()` is definitely side-effect free. For most practical situations, this means ensuring the argument is a Literal, Identifier, or …
=> Fix: no-extra-bind No autofix if arg may have side effect (fixes #10846)

docs/rules/no-tabs.md, lib/rules/no-tabs.js, tests/lib/rules/no-tabs.js
See #10256.
Added new option to no-tabs: `allowIndentationTabs`. This allows tabs that occur before any tokens or comments on a line.
Any more …
=> Update: no-tabs allowIndentationTabs option (fixes #10256)

docs/rules/padding-line-between-statements.md, lib/rules/padding-line-between-statements.js, tests/lib/rules/padding-line-between-statements.js
See #10853.
Added "iife" statement type to `padding-line-between-statements` rule.
* Any issues with the documentation changes I've added?
* …
=> Update: iife statement type for padding-line-between-statements (fixes #10853)

Makefile.js
Bit of refactor, using deconstruction assignment instead of require the whole shelljs modules.
=> Chore: Using deconstruction assignment for shelljs

tests/fixtures/parsers/typescript-parsers/type-alias.js, tests/lib/rules/space-infix-ops.js
Added some edge case tests, originally part of #10923 
The original implementation was looking for tokens between `Foo` and `T`, and thought …
=> Chore: Add typescript-specific edge case test to space-infix-ops

docs/rules/prefer-const.md, lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Changed `prefer-const` so that it considers destructuring assignment with an object property to disqualify using `const` for variables used in the same destructuring assignment. …
=> Fix: prefer-const when using destructuring assign (fixes #8308)

docs/maintainer-guide/governance.md, docs/maintainer-guide/npm-2fa.md, docs/maintainer-guide/releases.md
(refs #10631)
This adds a page to the maintainer guide describing how to get access to the npm 2FA secret for the `eslint` account. It also updates the release guidelines to account for the 2FA step.
If you're on the TSC and you haven't set up Keybase yet, it might be useful to use these instructions to get set up, and point out any issues you encounter with the instructions.
=> Docs: add instructions for npm 2FA (refs #10631)

docs/user-guide/configuring.md
Added mention that configuration glob overrides require v4.1.0 or higher.
Does this look okay? I used the `<b>` tag to specify that this should …
=> Docs: Mention version for config glob patterns

docs/developer-guide/nodejs-api.md, lib/linter.js, tests/lib/linter.js
Added `Linter.version`. I used a getter because JavaScript doesn't yet have static class properties, and otherwise, I'd need to do some hacky thing to add a property to the `Linter` constructor. I …
=> Update: Create Linter.version API (fixes #9271)

lib/rules/no-irregular-whitespace.js
This updates the no-irregular-whitespace rule to avoid using the legacy multi-argument `context.report` API. We have a linting rule to enforce against using the API, but the rule wasn't enforcing it in this case.
This was originally found by @Aladdin-ADD in https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/64.
=> Chore: avoid using legacy report API in no-irregular-whitespace

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md
Added a question to each issue template asking if the person creating the issue is willing to implement the change they are requesting. I thought at one point we had this, and I think it's a good way …
=> Docs: Update issue templates to ask for PRs

lib/testers/rule-tester.js
[x] Bug fix
<details>
```js
```
</details>
```js
"use strict";
const RuleTester = require("eslint").RuleTester;
try {
new RuleTester().run(
"foo",
context => (context.report(context.getSourceCode().ast, "message"), {}),
{ valid: [], invalid: [{ code: "", errors: [5] }] }
);
} catch (err) {
// ignore
}
```
I expected `RuleTester` to produce no output because the error was caught. …
=> Fix: deprecation warning in RuleTester using Node v11

lib/cli-engine.js, packages/eslint-config-eslint/default.yml, tests/fixtures/cli-engine/deprecated-rule-config/.eslintrc.yml, tests/lib/cli-engine.js
[x] Bug fix
* **Node Version:** 11.0.0
* **npm Version:** 6.4.1
N/A
N/A
From within the ESLint repository:
```js
const CLIEngine = require(".").CLIEngine;
const cliEngine = new CLIEngine();
console.log(cliEngine.executeOnFiles(["Makefile.js"]));
```
Ran `eslint Makefile.js --format json` in the ESLint repository
I expected the output to contain a `usedDeprecatedRules` property indicating that the `no-catch-shadow` rule (which we enable in …
=> Fix: rule deprecation warnings did not consider all rules

docs/rules/no-useless-rename.md, docs/rules/object-shorthand.md
Cross reference two rules in the documentation.
Nope; there's not much to see!
/cc @platinumazure
=> Docs: Cross-reference two rules (refs #11041)

tests/lib/linter.js, tests/lib/rules/constructor-super.js, tests/lib/rules/keyword-spacing.js, tests/lib/rules/no-useless-constructor.js, tests/lib/rules/prefer-arrow-callback.js
Acorn now reports parsing errors for invalid uses of the `super` keyword, and some tests are failing on master as a result. This commit updates the affected tests as necessary (or removes them if they're no longer applicable).
=> Chore: fix invalid super() calls in tests

lib/rules/no-unreachable.js, tests/lib/rules/no-unreachable.js
Made `no-unreachable` ignore `EmptyStatement` nodes.
Was this the correct approach?
=> Fix: Ignore empty statements in no-unreachable (fixes #9081)

docs/rules/no-restricted-imports.md, lib/rules/no-restricted-imports.js, tests/lib/rules/no-restricted-imports.js
Added checks to `no-restricted-imports` to check for re-export using `export * from 'foo'` and `export {f} from 'foo'` syntax forms.
Did I miss …
=> Fix: no-restricted-imports to check re-export (fixes #9678)

docs/rules/require-await.md
Updated the docs for `require-await` to explain why you might not want to use it. Also, expanded the rule's description. It seems like this rule really needed a lot more documentation than it had. …
=> Docs: Update require-await docs with exception (fixes #9540)

docs/rules/space-before-blocks.md, lib/rules/space-before-blocks.js, tests/lib/rules/space-before-blocks.js
This PR modifies the behavior of the `space-before-blocks` rule.
This PR does not affect the number of warnings for existing configurations of the `space-before-blocks` rule. It allows a new configuration option which ignores whitespace for functions, classes, and/or keywords, no longer warning regardless of whether whitespace was included in the specified cases.
The PR adds a new accepted value to …
=> Update: "off" options for "space-before-blocks" (refs #10906)

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
Removed the guard checking for multiline var declarations to ensure autofix is applied.
Issue: https://github.com/eslint/eslint/issues/10582 …
=> Fix: prefer-const autofix (fixes #10582)

docs/rules/id-match.md, lib/rules/id-match.js, tests/lib/rules/id-match.js
add `ignoreDestructuring` option to `id-match` rule
Nope.
Sorry that I do this code split job so late, cause I caught a cold and fever last …
=> Update: add `ignoreDestructuring` option to `id-match` rule

lib/linter.js
a very small refactor to improve readability.
no.
=> Chore: refactor linter#parseBooleanConfig to improve readability

lib/rules/indent.js, tests/lib/rules/indent.js
=> Fix: allow leading semi in next line (fixes #11082)

tests/lib/util/npm-utils.js
This is a workaround for https://github.com/tschaub/mock-fs/issues/256, which has been causing the build to fail on master for the past few days. It seems like we might eventually need to find an alternative to mock-fs for future Node versions, but this workaround should make the build pass in the meantime.
=> Build: fix test failure on Node 11

docs/rules/no-console.md
The snippet provided in [no-console#When Not To Use It](https://eslint.org/docs/rules/no-console#when-not-to-use-it) aims to achieve "only receiving errors for console calls" but the selector results in a warning for `console.log()` instead of `console.foobar()`. 
To fix it, the 'unexpected property' should be  selected with `!=` instead of `=`. Also, turning off "no-console" is still required to achieve "only receiving errors for console calls with unexpected property"
After change:
`console.log()` is ok
`console.logs()` is warned
=> Docs: no-console#When-Not-To-Use provides incorrect rule snippet

docs/rules/id-match.md
It looks like we always show the incorrect example first, so the fact that in this example we want to show the correct code first might be on purpose, but it does not look like it is
I switched the correct code with the incorrect one, not the code itselft, just the text since we always show the incorrect code first
=> switch incorrect example with correct one

README.md
I fixed the typo `to setup`.
`setup` is a noun. The correct verb is `to set up`
Source: 
- http://www.future-perfect.co.uk/grammar-tip/is-it-setup-set-up-or-set-up/
- https://grammarist.com/spelling/set-up-vs-setup/
No
=> Docs: (Grammar) "the setup" -> "to set up".

lib/rules/camelcase.js, tests/lib/rules/camelcase.js
refactor when the name is stripped so it doesn't affect the allow option
=> Fix: Do not strip underscores in camelcase allow (fixes #11000)

Makefile.js, lib/config/autoconfig.js, lib/config/config-rule.js, lib/config/config-validator.js, lib/linter.js, lib/rules/array-element-newline.js, lib/rules/eqeqeq.js, lib/rules/handle-callback-err.js, lib/rules/implicit-arrow-linebreak.js, lib/rules/indent-legacy.js, lib/rules/newline-before-return.js, lib/rules/no-constant-condition.js, lib/rules/no-else-return.js, lib/rules/no-implied-eval.js, lib/rules/no-restricted-imports.js, lib/rules/no-this-before-super.js, lib/rules/object-curly-newline.js, lib/rules/one-var.js, lib/rules/space-in-parens.js, lib/util/ignored-paths.js, packages/eslint-config-eslint/default.yml, tests/lib/rules/indent-legacy.js, tests/lib/rules/indent.js, tests/lib/rules/no-empty-function.js, tests/lib/util/ignored-paths.js
the fixes some jsdoc-related issues in eslint codebase.
+ enable prefer `"Araray"` in `valid-jsdoc` (and fixes the errors)
+ removed some unused params in jsdoc.
+ fixes some incorrect params.
**Is …
=> Chore: fix some jsdoc-related issues in the codebase

lib/rules/keyword-spacing.js, tests/lib/rules/keyword-spacing.js
I updated the keyword-spacing rule definition to properly validate `default` keywords. At present, it mistakenly validates the `export` token rather than the accompanying `default`. I changed the …
=> Fix: Amend keyword-spacing to validate `default` keywords

docs/rules/object-shorthand.md
Fixed link to rule: no-useless-rename that erroneously linked to the same currently viewed rule: object-shorthand
Trivial fix.
=> Docs: Fix link to rule `no-useless-rename`

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/QUESTION.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md, .github/ISSUE_TEMPLATE/SECURITY.md
This updates the issue templates to add the appropriate labels to new issues depending on which template was used. All of the changes in this PR were made using GitHub's [issue template editing wizard](https://github.com/eslint/eslint/issues/templates/edit).
This uses a recently-shipped GitHub feature: https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements/
=> Docs: Update issue templates

lib/rules/require-jsdoc.js, lib/rules/valid-jsdoc.js, lib/util/source-code.js, tests/lib/cli-engine.js
Also see: https://eslint.org/blog/2018/11/jsdoc-end-of-life
This deprecates the `valid-jsdoc` and `require-jsdoc` rules. We are currently still using them to lint the ESLint codebase -- at some point we should probably switch to `eslint-plugin-jsdoc` to dogfood the process.
=> Update: deprecate valid-jsdoc and require-jsdoc

docs/developer-guide/nodejs-api.md
This aims to prevent some of the common pitfalls/points of confusion when configuring `CLIEngine`, such as:
* it not being clear that `baseConfig` supports all of the options defined in the `.eslintrc.*` schema, and so can be used for options that are not supported as top-level `CLIEngine` arguments such as `extends` and `settings`.
* some of the CLIEngine options being named the same or almost the same as their `.eslintrc.*` equivalents, but being a different data type.
* it not being clear that CLIEngine silently ignores invalid options (which will hopefully be fixed at some point by #10272).
Refs:
#4402
#5179
#6605
#7247
#7967
#10272 …
=> Docs: Clarify the CLIEngine options

lib/rules/space-infix-ops.js, tests/lib/rules/space-infix-ops.js
`space-infix-ops`
no change
change the error message to …
=> Update: space-infix-ops reports violating operator

docs/rules/padding-line-between-statements.md, lib/rules/padding-line-between-statements.js, tests/lib/rules/padding-line-between-statements.js
https://github.com/eslint/eslint/issues/10721
- Added new `STATEMENT_TYPE`s for multiline variable declarations (`multiline-const`, `multiline-let`, `multiline-var`, `singleline-const`, …
=> Update: single- and multiline const, let, var statements (fixes #10721)

docs/rules/require-jsdoc.md, docs/rules/valid-jsdoc.md
The rules were deprecated in the last release, but the deprecation notices in the documentation are not autogenerated.
=> Docs: add missing deprecation notices for jsdoc rules

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/CHANGE.md, .github/ISSUE_TEMPLATE/NEW_RULE.md, .github/ISSUE_TEMPLATE/RULE_CHANGE.md
This updates the issue templates to ensure that the `triage` label is added to new issues. The bot had stopped adding the `triage` label to issues as an unintended side-effect of https://github.com/eslint/eslint/pull/11163.
(fixes https://github.com/eslint/eslint-github-bot/issues/99)
=> Docs: Ensure `triage` label is added to new issues

docs/rules/require-jsdoc.md, docs/rules/valid-jsdoc.md
Linked in to the [end of life blog post](https://eslint.org/blog/2018/11/jsdoc-end-of-life) regarding the deprecation of JSDoc rules. It took a bit of searching to find the post when it could just …
=> Docs: link to JSDoc EOL blogpost in valid-jsdoc and require-jsdoc

docs/rules/no-unused-vars.md
I clarified the example given in the `no-unused-vars` docs.
Not particularly.
=> Docs: Clarify the no-unused-vars docs

docs/developer-guide/working-with-plugins.md
Was writing a new plugin with some configs and noticed there aren't any concrete examples of how a config is actually defined in a configuration file. Added an example to show how a user would do …
=> Docs: clarify how to use configs in plugins

lib/rules/camelcase.js, tests/lib/rules/camelcase.js
* **ESLint Version:** `5.9.0`
* **Node Version:** `11.0.0`
* **npm Version:** `6.4.1`
<details> …
=> Fix: handle computed properties in camelcase (fixes #11084)

lib/rules/no-useless-catch.js, tests/lib/rules/no-useless-catch.js
When optional catch bindings are used, `node.param` is `null`.
Added a missing check in no-useless-catch.
No
=> Fix: handle optional catch bindings in no-useless-catch (fixes #11208)

lib/rules/no-param-reassign.js, tests/lib/rules/no-param-reassign.js
Added case of `ConditionalExpression` (ternary operator) in rule `no-param-reassign` when checking modification to parameters.
Parameter used in condition of ternary operator will now be ignored.
`(arg ? a : b).c = 3;` should no longer trigger the rule.
=> Fix: no-param-reassign - ignore parameter used as condition in ternary operator

.eslintrc.js, lib/rules/block-spacing.js, lib/rules/capitalized-comments.js, lib/rules/func-name-matching.js, lib/rules/max-classes-per-file.js, lib/rules/prefer-object-spread.js, package.json, tools/internal-rules/consistent-docs-description.js, tools/internal-rules/consistent-docs-url.js, tools/internal-rules/consistent-meta-messages.js, tools/internal-rules/no-invalid-meta.js
upgrade eslint-plugin-eslint-plugin@2.0.1, it mainly added a new rule: require-meta-type.
thoughts on the types of internal rules?
=> Upgrade: eslint-plugin-eslint-plugin@2.0.1

docs/rules/sort-imports.md, lib/rules/sort-imports.js, tests/lib/rules/sort-imports.js
This allows users to enforce sorting import members, without having to enforce
sorting of import declarations.
fixes #11019
=> Update: Add sort-imports ignoreDeclarationSort (fixes #11019)

docs/developer-guide/working-with-custom-formatters.md
Updated the custom formatter docs. I added a section on how to properly package up custom formatters, rearranged some sections, cleaned up grammar, and generally tried to make the docs a bit more …
=> Docs: Improve custom formatter docs

docs/user-guide/getting-started.md
`npx` is a shorter alternative to navigating to the executable found in `node_modules/.bin`
I've added a documentation regarding the usage of `eslint` with `npx`. …
=> Docs: Add `npx` usage to Getting Started guide

docs/rules/sort-imports.md
Fixed the examples of the `ignoreDeclarationSort` option of the `sort-imports` rule. This was pointed out by @mysticatea after #11019 was merged. …
=> Docs: fix example for sort-imports ignoreDeclarationSort

lib/formatters/tap.js, tests/lib/formatters/tap.js
As reported in #11110, result with severity of 1 (ie. warning) were reported as errors (not ok)
This will allow:
- a result with one or many messages and all of them are of severity of 1 to be `ok`
- …
=> Fix: Manage severity of 1 with TAP reporter (fixes #11110)

lib/rules/no-constant-condition.js, tests/lib/rules/no-constant-condition.js
* **ESLint Version: 5.9.0**
* **Node Version: 11.3.0**
* **npm Version: 6.4.1**
babel-eslint
<details> …
=> Fix: warn constant on RHS of || in no-constant-condition (fixes #11181)

conf/eslint-all.js, lib/config/config-rule.js, lib/load-rules.js, tests/lib/config/config-rule.js
The `lib/rules.js` file contains a code path that was previously needed to load core rules, but is no longer used as of aa56247746a0095996a41dd03bdbbf659f0f93b6.
=> Chore: remove dead code for loading rules

Makefile.js, lib/cli-engine.js, lib/config.js, lib/config/plugins.js, lib/linter.js, lib/rules.js, tests/lib/config/config-validator.js, tests/lib/config/plugins.js, tests/lib/load-rules.js, tests/lib/rules.js
This removes the undocumented `rules` property from `Linter` instances, as part of the effort to remove undocumented API surface from `Linter` (also see https://github.com/eslint/eslint/issues/9161). Config processing now exclusively uses `Linter`'s public API when defining rules. As a side-effect, the rule map utility in `lib/rules.js` no longer needs to access the filesystem, so we can remove the odd code generation logic from the browserify build.
=> Chore: remove undocumented `Linter#rules` property (refs #9161)

docs/user-guide/configuring.md, lib/config/config-ops.js, lib/linter.js, lib/util/config-comment-parser.js, tests/lib/config/config-ops.js, tests/lib/linter.js, tests/lib/util/config-comment-parser.js
As described in https://github.com/eslint/eslint/issues/9940, this allows globals in a config file to be specified with the strings `readable` and `writeable` rather than `false` and `true`, respectively. It also adds a new value, `off`, which turns off a previously-enabled global.
=> New: Allow globals to be disabled/configured with strings (fixes #9940)

docs/user-guide/configuring.md
This updates a few examples to use the newer string value for configuring the severity of rule warnings. There are more instances of using the older numerical value, but I left these because they're …
=> Docs: update rule configuration values in examples

lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
[x] Bug fix
Fixes #11305 
Maybe no.
=> Fix: only remove arrow before body in object-shorthand (fixes #11305)

lib/rules/no-constant-condition.js, tests/lib/rules/no-constant-condition.js
=> Fix: false positive in no-constant-condition (fixes #11306)

lib/rules/for-direction.js, tests/lib/rules/for-direction.js
I updated the for-direction rule to prevent false positives and false negatives.
No
=> Update: for-direction detection false positives/negatives

package.json, tests/lib/rules/comma-dangle.js, tests/lib/rules/indent.js, tests/lib/rules/keyword-spacing.js, tests/lib/rules/no-irregular-whitespace.js, tests/lib/rules/no-undefined.js, tests/lib/rules/no-useless-rename.js, tests/lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-spacing.js, tests/lib/rules/padding-line-between-statements.js, tests/lib/rules/semi-spacing.js, tests/lib/rules/semi.js
the master is building failing. This PR mainly updated some tests to let the tests passed.
no.
=> Chore: update incorrect tests to fix build failing

docs/rules/no-useless-call.md
`prefer-spread` mentions `no-useless-call`, but not the other way around. This PR updates the docs of `no-useless-call` to mention `prefer-spread`. …
=> Docs: mention 'prefer-spread' in docs of 'no-useless-call'

package.json, tests/lib/cli-engine.js
[x] Other, please explain: **Update Dependency**
Update `file-entry-cache` to v4 to avoid the `CircularJSON dependency warning`, along with updating the test cases to parse the content using `flatted` which is used to create …
=> Upgrade: CircularJSON dependency warning

lib/config/config-file.js, tests/lib/config/config-file.js
Update `--init` as described in #9947 
Updated the behavior of `--init` so generated JS config files follow linting rules. As described in #9947, this change makes `--init` run generated JS config …
=> Update: Make --init run js config files through linter (fixes #9947)

docs/rules/no-shadow-restricted-names.md, lib/rules/no-shadow-restricted-names.js, tests/lib/rules/no-shadow-restricted-names.js
[`no-shadow-restricted-names`](https://eslint.org/docs/rules/no-shadow-restricted-names)
Fewer
New default behavior
```js
{ let undefined; }
{ let undefined = 5; }
```
It reports an error on both lines.
It will not report an error on the first line, but it will continue reporting an error on the second line.
**What changes did you make? (Give …
=> Update: no-shadow-restricted-names lets unassigned vars shadow undefined

docs/rules/no-prototype-builtins.md
The first section in the no-prototype-builtins docs mentions objects created with Object.create(null), but does not mention builtin shadowing (which is arguably a much more compelling reason to use the rule). This commit updates the description to clarify the risks of using prototype builtins on user input.
=> Docs: clarify motivation for no-prototype-builtins

lib/rules/one-var.js, tests/lib/rules/one-var.js
Resolves #10741.
Removed adding extraneous linefeeds in the fixer with input variable declarations being multiline.
No, there isn't.
=> Fix: Remove extraneous linefeeds in `one-var` fixer (#10741)

docs/user-guide/configuring.md
Before this change users can mistakenly assume that setting
parserOptions.ecmaVersion automatically implies the globals from that
ecmaVersion are available, in fact globals are controlled by a separate
environment setting that is not affected by ecmaVersion.
This PR implements the suggestion from
https://github.com/eslint/eslint/issues/9812
[ ] Add …
=> Docs: Clarify ecmaVersion doesn't imply globals (refs #9812)

lib/rules/prefer-destructuring.js, tests/lib/rules/prefer-destructuring.js
#11151 
Add fixer that fixes the simple case of object destructuring, like `var x = a.x` => `var {x} = a`. All other cases are not fixed, which includes assignment expression, array destructuring and renamed properties. 
=> Update: add fixer for `prefer-destructuring` (fixes #11151)

lib/rules/prefer-spread.js, tests/lib/rules/prefer-spread.js
[ x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
fixes #11330 
no.
=> Update: remove prefer-spread autofix (fixes #11330)

docs/developer-guide/working-with-custom-parsers.md, docs/user-guide/configuring.md
updated the docs about typescript-eslint-parser(it has been deprecated)
somewhere else?
=> Docs: update typescript parser (refs #11368)

docs/rules/prefer-spread.md
The `...` in function call syntax is not an operator. It's more of a punctuation supported in various places (function call, function definition, array/object definitions, destructuring syntax), but …
=> Docs: `...` is not an operator

docs/rules/no-extra-bind.md
“... it's important that the function actually use `this` in its function body.”
changed to 
“... it's important that the function actually use**s** `this` in its function body.” …
=> Docs: “the function actually use”: use -> uses

tests/lib/util/npm-utils.js
This reverts commit 709190f8c5d7559b1e0915e25af60b50a94ba1c7.
fixes #11104 
This reverts commit 709190f8c5d7559b1e0915e25af60b50a94ba1c7.
it …
=> Revert "Build: fix test failure on Node 11 (#11100)"

docs/user-guide/configuring.md, lib/config/config-ops.js, tests/lib/config/config-ops.js
Changes globals configuration to also accept "readonly" and "writable".
* Updated `config-ops#normalizeGlobalsConfig()` to also accept "readonly" and "writable" (the values returned from this …
=> Update: Use 'readonly' and 'writable' for globals (fixes #11359)

lib/config/config-initializer.js, package.json, tests/lib/config/config-initializer.js
Updates the behavior of `--init` per #11105
Rearranged the questions that are asked using `--init`. We now assume the latest version of ECMAScript is desired.
Also, there was a bug where if you chose …
=> Update: Behavior of --init (fixes #11105)

docs/rules/prefer-object-spread.md
Added a few notes to `prefer-object-spread` rule to indicate that it is only available in environments that support ES2018 features. 
I tried …
=> Docs: Add note about support for object spread (fixes #11136)

docs/rules/semi.md
Changed “those who says” to “those who say”.
No.
=> Docs: fix grammar in “those who says”

docs/rules/space-before-blocks.md
Examples of **correct** code for this rule when configured `{ "functions": "never", "keywords": "always", "classes": "never" }`:
Replaced
```js
class Foo {
constructor(){}
}
```
with
```js
class Foo{
constructor(){}
}
```
No.
=> Docs: fix correct code for "classes": "never"

lib/rules/comma-spacing.js, tests/lib/rules/comma-spacing.js
[x] Bug fix
Fixes #11295 
Maybe no.
=> Fix: ignore comma before closing paren (fixes #11295)

docs/rules/padded-blocks.md, lib/rules/padded-blocks.js, tests/lib/rules/padded-blocks.js
padded-blocks
Less
New option: `allowSingleLineBlocks` …
=> New: add allowSingleLineBlocks opt. to padded-blocks rule (fixes #7145)

docs/rules/sort-keys.md, lib/rules/sort-keys.js, tests/lib/rules/sort-keys.js
I added a check for boundary spread elements to fix #10760. The PR implements [the following suggeston](https://github.com/eslint/eslint/pull/10495#issuecomment-400037448). …
=> Fix: support boundary spread elements in sort-keys

docs/maintainer-guide/governance.md
Added details of the reviewer status per [TSC meeting](https://github.com/eslint/tsc-meetings/blob/cb387a430cbd9e30398d02f9e1125c8364ad3cb0/notes/2019/2019-02-14.md); updated details of the TSC.
**Is …
=> Docs: Update governance doc with reviewers status

lib/rules/one-var.js, tests/lib/rules/one-var.js
Added conditionals to the `hasOnlyOneStatement` based on currentScope that has requires to avoid throwing an error when it should not.
Looking …
=> Fix: Adds conditional for separateRequires in one-var (fixes #10179)

lib/rules/sort-keys.js, tests/lib/rules/sort-keys.js
=> Fix: sort-keys throws Error at SpreadElement (fixes #11402)

Makefile.js, tools/eslint-fuzzer.js, tools/fuzzer-runner.js
This commit turns on our existing fuzzer tool to run a small number of iterations when the user runs `npm test`. This is intended to prevent bugs like https://github.com/eslint/eslint/issues/11402 where a rule completely breaks when it encounters a particular syntax, but the author doesn't think to test for that kind of syntax.
When there are no fuzzing errors, this adds about 5 seconds to the `npm test` time. (When there are fuzzing errors, it takes more time because the fuzzer does extra work to try to find the minimal config that reproduces the bug.)
The fuzzer actually has two modes: "crash" (where it only tries to detect rule crashes), …
=> Chore: run fuzzer along with unit tests

docs/developer-guide/code-conventions.md, docs/maintainer-guide/releases.md, docs/user-guide/configuring.md
see the PR title.
is it the correct spelling? ( I'm just a English learner :(
=> Docs: use more common spelling

Makefile.js, karma.conf.js, packages/eslint-config-eslint/index.js, packages/eslint-config-eslint/package.json, webpack.config.js
Previously, `npm run lint` would invoke ESLint three separate times for different sets of files. There doesn't seem to have been a clear reason for this (it was added in 9b8c639d35d154a27b81470cd432a1ae0e707ef7 about 5 years ago), and some files in the repo were inadvertently being missed. This commit updates the lint task to simply invoke ESLint once on the entire repository. It also fixes some linting errors in files that were previously being skipped.
=> Chore: lint all files in the repo at the same time

webpack.config.js
5018378131fd5190bbccca902c0cf4276ee1581a broke the build on master because it wasn't rebased onto f6ba633f56eca6be20fc4b0d9496a78b9498d578 when the tests were run.
=> Build: fix linting errors on master

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[x] Bug fix
The PR title contains all of the information needed to reproduce the issue.
* **Node Version:** latest
* **npm Version:** latest
default
```yml
rules:
```
```js
((let))
```
I expected an error to be reported by the `no-extra-parens` rule, because the identifier `let` is unnecessarily parenthesized twice.
The rule crashed:
``` …
```
=> Fix: no-extra-parens crash when code is "((let))"

tests/lib/rules/_utils.js, tests/lib/rules/indent.js
some functions can be reused in rule tests (like `unIndent`). does it make sense?
[x] Other, please explain: 
no.
=> Chore: add utils for rule tests

Makefile.js
Use `path.join` instead of `path.resolve` to ensure relative path is passed to Webpack when releasing on the Jenkins server. For some reason, the absolute path is not actually resolved correctly …
=> Build: Remove path.resolve in webpack build

lib/rules/no-warning-comments.js, tests/lib/rules/no-warning-comments.js
[x] Bug fix
See https://github.com/eslint/eslint/issues/11471
5018378131fd5190bbccca902c0cf4276ee1581a changed the codebase to use unicode regexes almost everywhere, with the exception of places where regexes are constructed from user input. However, two issues occurred to cause a bug:
* Due to an oversight, the regular expressions constructed in the `no-warning-comments` rule were changed to be unicode regexes even though those regexes were constructed from user input.
* The `no-warning-comments` rule dynamically creates regexes with unnecessary escape characters, and unnecessary escape characters are invalid in unicode regexes.
This commit fixes the first issue. The …
=> Fix: avoid creating invalid regex in no-warning-comments (fixes #11471)

webpack.config.js
fixes https://github.com/eslint/eslint.github.io/issues/546
the commit message checking failing -- how to fix a cross-repo issue?
=> Build: bundle espree (fixes eslint/eslint.github.io#546)

docs/rules/func-name-matching.md
Added a missing word in the docs.
No.
=> Docs: Fix typo in func-name-matching rule docs

docs/user-guide/configuring.md
Fixed missing quotes in the JSON snippets in this line:
> `{ env: { es6: true } }` enables ES6 syntax automatically, but `{ parserOptions: { ecmaVersion: 6 } }` does not enable ES6 globals …
=> Fix invalid JSON in "Specifying Parser Options"

docs/developer-guide/working-with-rules.md
I've fixed JSON Schema example correct link.
I found a dead link of JSON Schema example.
In the JSON Schema official site, I couldn't find the …
=> Docs: fix json schema example link

docs/rules/no-restricted-modules.md
This rule doesn't allow passing an array of paths like this.
Corrected an example that is not valid, which actually results in no paths being restricted. This has caused confusion.
**Is there …
=> Docs: Fix example in no-restricted-modules docs

Makefile.js, webpack.config.js
[x] Bug fix (https://github.com/eslint/eslint/issues/11504)
This updates the webpack config to compile dependencies to ES5, to ensure that the final output file is runnable in ES5 browsers. It tests this behavior by running ESLint on the output file.
=> Build: compile deps to ES5 when generating browser file (fixes #11504)

lib/config/config-file.js, lib/config/config-validator.js, lib/testers/rule-tester.js, tests/lib/config/config-validator.js
move the function param `source` to be last, and defaults to `null`.
since it's not always necessary, as in some of the tests.
no
=> Chore: make config validator params more consistent

lib/linter.js, tests/lib/linter.js
Add line number to the output in the event of a rule crash
See #11304.
Added file name and line information to the error being thrown. This will get output independent of the verbosity setting.
**Is …
=> Chore: improve crash reporting (fixes #11304)

lib/util/glob-utils.js, tests/lib/util/glob-utils.js
* **ESLint Version:** 5.15.0
* **Node Version:** 10.15.2
* **npm Version:** 6.4.1
Any; this bug occurs before ESLint parses anything.
**Please show your …
=> Fix: Empty glob pattern incorrectly expands to "/**"

lib/rules/implicit-arrow-linebreak.js, tests/lib/rules/implicit-arrow-linebreak.js
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
Fixes [11268](https://github.com/eslint/eslint/issues/11268)
The original auto-fix calculated white spaces into formatting comments and parentheses, which was the cause for extra characters.
The …
=> Fix: implicit-arrow-linebreak adds extra characters (fixes #11268)

.eslintrc.js, tests/lib/rules/array-bracket-spacing.js, tests/lib/rules/comma-dangle.js, tests/lib/rules/indent.js, tests/lib/rules/keyword-spacing.js, tests/lib/rules/no-console.js, tests/lib/rules/no-eval.js, tests/lib/rules/no-global-assign.js, tests/lib/rules/no-magic-numbers.js, tests/lib/rules/no-mixed-spaces-and-tabs.js, tests/lib/rules/no-native-reassign.js, tests/lib/rules/no-redeclare.js, tests/lib/rules/no-restricted-globals.js, tests/lib/rules/no-sequences.js, tests/lib/rules/no-shadow.js, tests/lib/rules/no-unused-vars.js, tests/lib/rules/object-curly-newline.js, tests/lib/rules/object-curly-spacing.js, tests/lib/rules/prefer-const.js, tests/lib/rules/quote-props.js, tests/lib/rules/require-unicode-regexp.js, tests/lib/rules/space-infix-ops.js
[X] Other, please explain
This PR changes the option of `eslint-plugin/test-case-property-ordering` rule in our `.eslintrc.js` to recognize the properties the rule tester is supporting.
Is this order good?
=> Chore: make test-case-property-ordering reasonable

lib/rules/implicit-arrow-linebreak.js, tests/lib/rules/implicit-arrow-linebreak.js
[x] Bug fix (https://github.com/eslint/eslint/issues/11521)
Currently, the implicit-arrow-linebreak rule contains a lot of logic to determine how comments should be adjusted in code when an autofix is needed. The goal is to be able to autofix cases where there is a comment between an arrow token and the start of an arrow function body. Most other core rules simply decide not to fix cases when there is a comment interfering with the fix.
This logic accounts for a large fraction of the code in the rule, and seems to require a lot of different code for many individual cases. Unfortunately, bugs keep being reported identifying problems in the rule (e.g. #11268, #11521) and …
=> Fix: avoid moving comments in implicit-arrow-linebreak (fixes #11521)

docs/user-guide/command-line-interface.md
This removes an extra colon that I noticed while reading the CLI docs.
No
=> Docs: fix duplicate punctuation in CLI docs

docs/developer-guide/working-with-custom-formatters.md, lib/cli.js, lib/formatters/html-template-message.html, lib/formatters/html.js, lib/formatters/json-with-metadata.js, tests/lib/cli.js, tests/lib/formatters/html.js, tests/lib/formatters/json-with-metadata.js
https://github.com/EasyRhinoMSFT/rfcs/blob/master/designs/2019-expose-rules-to-formatters/readme.MD
This change adds a new optional argument to the interface function exported by formatters. The …
=> Update: pass rule meta to formatters RFC 10

docs/rules/func-style.md
`func-style`: clarify when `allowArrowFunctions` is used
No
=> Docs: `func-style`: clarify when `allowArrowFunctions` is used

lib/formatters/html.js, tests/lib/formatters/html.js
Added small check to allow HTML formatter to work without rules meta data. This is to fix a release issue introduced by #11551
Nothing
=> Fix: Allow HTML formatter to handle no meta data

Makefile.js
Fixed an issue where gensite was not passing `{ rulesMeta }` to formatters when generating formatter output.
Not really.
=> Build: gensite passes rulesMeta to formatter rendering

lib/rules/camelcase.js, lib/rules/capitalized-comments.js, lib/rules/default-case.js, lib/rules/dot-notation.js, lib/rules/handle-callback-err.js, lib/rules/id-match.js, lib/rules/line-comment-position.js, lib/rules/lines-around-comment.js, lib/rules/max-len.js, lib/rules/new-cap.js, lib/rules/no-fallthrough.js, lib/rules/no-unused-vars.js, lib/rules/no-warning-comments.js, lib/rules/spaced-comment.js, lib/rules/valid-jsdoc.js, tests/lib/rules/max-len.js, tests/lib/rules/no-unused-vars.js
Fixes #11423
This updates the core rules that interpret user-provided options as regular expressions. Those rules now interpret the options as unicode regexes, which avoids some cases of unexpected behavior with astral symbols.
=> Breaking: interpret rule options as unicode regexes (fixes #11423)

docs/rules/function-paren-newline.md, lib/rules/function-paren-newline.js, tests/lib/rules/function-paren-newline.js
`function-paren-newline`
New option `consistent-arguments`.
`"consistent-arguments"` requires consistent usage of linebreaks for each pair of parentheses and parameters/arguments. It allows linebreaks inside function parentheses if there is only one parameter/argument.
Examples of **incorrect** code for this rule with the `"consistent-arguments"` option:
```js
/* eslint function-paren-newline: ["error", "consistent-arguments"] */
function foo(bar,
baz
) {}
var foo = function(bar,
baz
) {};
var foo = (
bar,
baz) => {};
foo(
bar,
baz);
foo(
bar, qux,
baz …
```
=> Update: support single argument on newline with function-paren-newline

docs/rules/arrow-parens.md
Corrected the explanation of the arrow-parens "as-needed" rule in the docs. 
Make sure the wording is what we want. I took the wording from the …
=> Docs edit arrow-parens as-needed explanation (fixes #11202)

docs/rules/no-confusing-arrow.md, lib/rules/no-confusing-arrow.js, tests/lib/rules/no-confusing-arrow.js
…es#11503)
[ x] Changes an existing rule ([template]
fixes #11503 
no.
=> Breaking: no-confusing-arrow enable allowParens: true (fixes #11503)

lib/config/config-validator.js, lib/rules/line-comment-position.js, lib/rules/max-len.js, lib/rules/max-lines-per-function.js, lib/rules/one-var.js, lib/testers/rule-tester.js, lib/util/ajv.js, package.json, tests/conf/config-schema.js, tests/lib/rules/max-len.js, tests/lib/rules/max-lines-per-function.js, tests/lib/testers/rule-tester.js
This implements the proposal from https://github.com/eslint/eslint/issues/11473 to make `RuleTester` throw an error when a rule uses an invalid `default` keyword in its schema. It also fixes a few remaining cases where core rules were doing that.
=> Breaking: disallow invalid rule defaults in RuleTester (fixes #11473)

lib/cli-engine.js, tests/lib/cli-engine.js
* **ESLint Version:** 5.9.0
* **Node Version:** 10.9.0
* **npm Version:** 6.2.0
Changed the `getErrorResults` to not mutate passed parameter …
=> Fix: getErrorResults function to not mutate passed parameter

lib/rules/object-shorthand.js, tests/lib/rules/object-shorthand.js
Fix for https://github.com/eslint/eslint/issues/11595.
Also added test for normal operation of `object-shorthand` `ignoreConstructors` option. …
=> Fix: object-shorthand ignoreConstructors option wrongly identifies '_' as constructor name

lib/rules/no-loop-func.js, tests/lib/rules/no-loop-func.js
no-loop-func
**Please provide some example code that this …
=> Improve no-loop-func rule description and message

package.json
This updates espree to v6.0.0-alpha.0, which fixes https://github.com/eslint/eslint/issues/9687.
=> Breaking: upgrade espree to 6.0.0-alpha.0 (fixes #9687)

tests/lib/config/config-file.js
This updates a test to avoid failing a regex match whenever the user's CWD contains a space.
=> Chore: fix test that fails when the CWD contains a space

lib/rules/no-unneeded-ternary.js, tests/lib/rules/no-unneeded-ternary.js
[X] Bug fix
This PR fixes #11579.
The new logic uses operator precedence instead of whitelist of node types in order to check the necessity of parenthesizing.
=> Fix: autofix of no-unneeded-ternary made syntax error (fixes #11579)

lib/rules/no-async-promise-executor.js, lib/rules/no-console.js, lib/rules/no-misleading-character-class.js, lib/rules/no-prototype-builtins.js, lib/rules/no-shadow-restricted-names.js, lib/rules/no-useless-catch.js, lib/rules/no-with.js, lib/rules/require-atomic-updates.js, packages/eslint-config-eslint/default.yml, tests/lib/cli.js, tests/lib/config/config-initializer.js
[x ] Other, please explain: fixes #10768 
any objections on the rules?
=> Breaking: eslint:recommended changes (fixes #10768)

docs/user-guide/migrating-to-6.0.0.md
This updates the migration guide to remove the "unimplemented" notice for features that have now been implemented, and it brings the `eslint:recommended` section up to date with the latest decision.
=> Docs: update status of breaking changes in migration guide

package.json
[X] Other, please explain: add markdownlint-cli to devDependencies
This PR adds `markdownlint-cli` to `devDependencies` because https://github.com/eslint/eslint/pull/11556 added a commit hook that uses `markdownlint` command.
=> Chore: add markdownlint-cli

package.json
[X] Other, please explain: add `eslint` to devDependencies
This PR adds `eslint` to `devDepndencies`.
```diff
+     "eslint": "file:.",
```
From this, npm makes a symbolic link `./node_modules/eslint` ⇔ `./` so editors such as VSCode can use it to lint our codebase.
=> Chore: add eslint as a devDependeny

lib/rules/no-cond-assign.js, tests/lib/rules/no-cond-assign.js
[x] Bug fix 
Fixes #11611 
Nothing.
=> Fix: check token before using in no-cond-assign (fixes #11611)

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
=> Fix: consider comments in object-curly-spacing (fixes #11656)

lib/rules/no-throw-literal.js, tests/lib/rules/no-throw-literal.js
[x] Bug fix
Fixes #11637 
Maybe no.
=> Fix: update rule message of no-throw-literal (fixes #11637)

docs/user-guide/migrating-to-6.0.0.md
Node.js 6 went EOL in April 2019, as per https://github.com/nodejs/Release#end-of-life-releases. This looks like a simple typo.
=> Docs: Fix Node.js 6 EOL date

tests/lib/cli-engine.js
This fixes a test failure on macOS. Previously, some `CLIEngine` tests were failing because some parts of the CLIEngine tests call realpath() and others didn't.
=> Chore: fix CLIEngine tests when os.tmpdir is a symlink

lib/rules/no-useless-return.js, tests/lib/rules/no-useless-return.js
[X] Bug fix #11647
This PR fixes `no-useless-return` rule to ignore `return` statements in unreachable code.
=> Fix: ignore return statements in dead code (fixes #11647)

lib/rules/curly.js, tests/lib/rules/curly.js
Added a lexical declaration check to the `multi-or-nest` curly rule to prevent single line lexical declarations from being flagged as errors. See #11663 
Nothing specific
=> Fix: Curly rule incorrectly flagging lexical declarations (fixes #11663)

docs/developer-guide/nodejs-api.md, docs/user-guide/command-line-interface.md, docs/user-guide/migrating-to-6.0.0.md, lib/cli-engine.js, lib/cli-engine/cascading-config-array-factory.js, lib/cli-engine/config-array-factory.js, lib/cli.js, lib/options.js, messages/plugin-missing.txt, tests/fixtures/plugins/node_modules/eslint-plugin-with-rules.js, tests/lib/cli-engine.js, tests/lib/cli-engine/config-array-factory.js, tests/lib/cli.js
With the [2018-simplified-package-loading RFC](https://github.com/eslint/rfcs/blob/8bc0b80e0b3e54d10991a4774c41f7375dfcbbfe/designs/2018-simplified-package-loading/README.md) implemented, ESLint always resolves plugins relative to the current working directory. The CWD works well for the most common use case, but is inconvenient for certain integrations. This commit proposes adding a CLI flag to specify an alternative place where plugins should be resolved from.
(Implements https://github.com/eslint/rfcs/pull/18)
=> New: add --resolve-plugins-relative-to flag

lib/config/config-initializer.js
=> Fix: delete unnecessary duplicated question (fixes #11617)

docs/rules/object-curly-newline.md
Move an example from invalid to valid.
```js
o = {a,
b}
// This should pass `{consistent: true}`, but the docs say otherwise.
```
No.
=> Docs: fix example in object-curly-newline docs

lib/cli-engine/config-array-factory.js, lib/util/relative-module-resolver.js, tests/fixtures/module-not-found/.eslintrc.yml, tests/fixtures/module-not-found/extends-js/.eslintrc.yml, tests/fixtures/module-not-found/extends-plugin/.eslintrc.yml, tests/fixtures/module-not-found/node_modules/eslint-config-throw.js, tests/fixtures/module-not-found/node_modules/eslint-plugin-throw.js, tests/fixtures/module-not-found/plugins/.eslintrc.yml, tests/fixtures/module-not-found/throw-in-config-itself/.eslintrc.js, tests/fixtures/module-not-found/throw-in-extends-js/.eslintrc.yml, tests/fixtures/module-not-found/throw-in-extends-plugin/.eslintrc.yml, tests/fixtures/module-not-found/throw-in-plugins/.eslintrc.yml, tests/lib/cli-engine.js
[X] Bug fix: #11720 (wrong `plugin-missing` errors on Node.js 12)
This PR fixes wrong `plugin-missing` errors on Node.js 12.
The config array factory distinguishes by the following way if a `MODULE_NOT_FOUND` error was plugin's or came from inside of the `plugin`.
```js
error.code === "MODULE_NOT_FOUND" && error.message.includes(request)
```
Because the `error.message` was `"Cannot find module '${request}'"` until Node.js 12.
Since Node.js 12, the `error.message` contains the `require` stack. For example:
```
Cannot find module 'eslint/lib/util/glob-util'
Require stack:
- C:\Users\t-nagashima.AD\dev\sandbox\node_modules\eslint-plugin-import\lib\rules\no-unused-modules.j …
```
=> Fix: wrong 'plugin-missing' error on Node.js 12 (fixes #11720)

packages/eslint-config-eslint/package.json
I presume there is no much need to target the EOL node versions. and it seems too wordy to add something like `"eslint-plugin-node": "^6.0.1 || ^7.0.1 || ^8.0.0 || ^9.0.0..."` :)
=> Chore: eslint-config-eslint require node >= 8

docs/rules/no-proto.md
#11743
* Added instructions to change an object's prototype with `Object.setPrototypeOf`.
* Disambiguated `getPrototypeOf` to `Object.getPrototypeOf`.
* Some new code examples.
* Revised "When Not To …
=> Docs: updated no-proto rule (fixes #11743)

README.md
=> Docs: add table of contents in readme

docs/user-guide/migrating-to-6.0.0.md
[X] Documentation update (fixes #11728)
This PR updates the migration guide to describe the change that `RuleTester` disallows `parser` property with package names.
=> Docs: add about RuleTester's parser to migration guide (fixes #11728)

Makefile.js
it removed something in created config for perf test:
a. rule config for deprecated rules
b. index, utils. the result of ls() includes index.js and utils/* while they are not rules, that's say, it's not a 'valid' config …
=> Chore: improve perf test

lib/rules/complexity.js, lib/rules/max-classes-per-file.js, lib/rules/max-depth.js, lib/rules/max-len.js, lib/rules/max-lines-per-function.js, lib/rules/max-lines.js, tests/lib/linter/linter.js, tests/lib/rules/complexity.js, tests/lib/rules/max-depth.js, tests/lib/rules/max-len.js, tests/lib/rules/max-lines-per-function.js
It is proposed to unify the content of messages from the category "[complexity](https://eslint.org/docs/rules/complexity)". And make them more informative.
no changed
- Changing the message template in `exports.meta.messages`
- Changing `data` in a `context.report` method call
```js
function test(a) {
// Comment qwerty qwerty qwerty qwerty
if (a) {
if (a) {
console.log('qwerty');
}
a(function() {
onsole.log('qwerty qwerty');
})
a++;a++;a++
if (a) a(); else a();
}
} …
```
=> Update: Uniform messages for the rules in "complexity" section

docs/rules/no-div-regex.md, lib/rules/no-div-regex.js, tests/lib/rules/no-div-regex.js
[] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
fixes: #11355
Adding fixer for no-div-regex-rule and use [=] instead of \\= as suggestion to avoid conflicting with no-useless-escape error.
No.
=> Update: add fixer for no-div-regex rule (fixes #11355)

lib/linter/linter.js, lib/linter/rules.js, lib/shared/config-validator.js, tests/lib/cli-engine/cli-engine.js, tests/lib/linter/code-path-analysis/code-path.js, tests/lib/linter/linter.js, tests/lib/linter/rules.js, tests/lib/rules/no-inline-comments.js
todo: 
fixes #9505 
config | before | after
------------- | ------------- | -------
`/*eslint-enable foo*/`  | no error | linting error
`/*eslint-disable(-line) foo*/`  | no error | linting error
`/*eslint foo: 0*/` | no error | linting error
`{rules: {foo: 0}}` | no error | no error
`{rules: {foo: 1}` | linting warning | linting error
+ please note `getRule()` will not return a stub rule if the rule cannot be loaded.
Previously, the `ruleMapper.getRule()` will return a stub rule, when the rule is not defined. it was really counter-intuitive and confusing.
After this change, it will …
=> Breaking: stricter rule config validating (fixes #9505)

docs/rules/new-parens.md, lib/rules/new-parens.js, tests/lib/rules/new-parens.js
#10034 was closed automatically for a lack of interest, I'm not sure if this functionality is wanted.
Added an argument to `new-parens` for always or never. The default with no arguments keeps the …
=> Update: Add never option for new-parens (refs #10034)

lib/cli-engine/formatters/junit.js, tests/lib/cli-engine/formatters/junit.js
This PR is a follow up from the discussion in issue https://github.com/eslint/eslint/issues/11068. 
With this change we are adding `classname` attribute to the `<testcase>` item.
[x] Other, please explain: Add new attribute to JUnit formatter …
=> New: Add classname attribute to JUnit testcase (refs #11068)

lib/rules/arrow-parens.js, tests/lib/rules/arrow-parens.js
=> Update: improve reported location of arrow-parens (fixes #11773)

templates/blogpost.md.ejs
As mentioned in #11614, there is a missing space in the blog post template when the release is semver-major.
Added a space in the template. …
=> Build: Fix typo in blog post template (fixes #11614)

lib/rules/no-useless-escape.js, tests/lib/rules/no-useless-escape.js
=> Update: add `endColumn` to no-useless-escape (fixes #11629)

lib/rules/no-restricted-imports.js, tests/lib/rules/no-restricted-imports.js
[x] Bug fix 
Fixes #11580 .
Nothing.
=> Fix: show custom message for namespace import (fixes #11580)

lib/rule-tester/rule-tester.js, tests/lib/rule-tester/rule-tester.js, tests/lib/rules/complexity.js, tests/lib/rules/quotes.js
[X] Bug fix #11615
This PR fixes `RuleTester` to fail the test case if autofix made syntax errors.
Additionally,
- fixes some test cases that autofix made syntax errors.
- fixes the side-effect that overrides `RuleTester.describe` and `RuleTester.it` permanently in `tests/lib/rule-tester/rule-tester.js`. This side-effect had confused `tests/lib/rules/*.js` as using the stub functions to test rules.
I have noticed that `errors` property with a number allows syntax errors. Some of our tests depend on the behavior in order to use syntax error in rule's tests (E.g. [tests/lib/rules/spaced-comment.js#L577-L589](https://github.com/eslint/eslint/blob/cb1922bdc07e58de0e55c13fd9 …
=> Fix: fails the test case if autofix made syntax error (fixes #11615)

lib/cli-engine/config-array/override-tester.js, tests/lib/cli-engine/config-array/override-tester.js
[X] Bug fix #11577
This PR fixes `overrides[].files` and `overrides[].excludedFiles` to handle `./` as expected.
The change is below. Especially, we newly can specify `./*.js`-like patterns that match with the files in the root directory but not in subdirectories.
Pattern      | FilePath     | Before  | After   | Fixed
:------------|:-------------|:--------|:--------|:-----
`*.js`       | `foo.js`     | `true`  | `true`  |
`*.js`       | `dir/foo.js` | `true`  | `true`  |
`./*.js`     | `foo.js`     | `false` | `true`  | ✅
`./*.js`     | `dir/foo.js` | `false` | `false` |
`dir/*.js`   | `foo.js`     | `false` | `false` |
`dir/*.js`   | `dir/foo.js` | `true`  | `true` …
=> Fix: `overrides` handle relative paths as expected (fixes #11577)

docs/developer-guide/working-with-rules.md
removed unnecessary `>` from docs
=> Docs: removed '>' prefix from from docs/working-with-rules

lib/linter/node-event-generator.js
also reduces cyclomatic complexity with a slight reconfiguring of some conditions
see below
I noticed that this code could be a tad bit improved by removing the assignment  that was inside the for loop.  I also reduced the complexity of the bottom bit slightly.
it's a very small change. no.
=> Chore: removes unnecessary assignment in loop

docs/rules/valid-typeof.md, lib/rules/valid-typeof.js, tests/lib/rules/valid-typeof.js
[BigInt just moved to Stage 4](https://github.com/tc39/proposals/pull/217), so add support for it to the valid-typeof rule.
valid-typeof …
=> Update: support "bigint" in valid-typeof rule

lib/rules/no-octal.js, tests/lib/rules/no-octal.js
Examples: 08, 018, 08.1
[X] Bug fix:  [#11794](https://github.com/eslint/eslint/issues/11794)
Reference: [ECMAScript Additional Syntax Numeric Literals](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-additional-syntax-numeric-literals)
no-octal rule used to report all LegacyOctalIntegerLiteral literals (00, 01, 071...) and only some NonOctalDecimalIntegerLiteral literals (018...).
The rule didn't report NonOctalDecimalIntegerLiteral literals that start with 08 or 09.
With this fix, the rule will report all LegacyOctalIntegerLiteral and all NonOctalDecimalIntegerLiteral literals as well as all DecimalLiteral literals that contain them (e.g. 08.1, …
=> Fix: no-octal should report NonOctalDecimalIntegerLiteral (fixes #11794)

docs/rules/sort-keys.md, lib/rules/sort-keys.js, tests/lib/rules/sort-keys.js
Fixes #11624 
Modified the `sort-keys` rule to accept a `minKeys` option, which specifies minimum number of keys required for an object's unsorted keys to produce an error. Default for the option is …
=> Update: introduce minKeys option to sort-keys rule (fixes #11624)

lib/rules/require-atomic-updates.js, tests/lib/rules/require-atomic-updates.js
[X] Bug fix: #11723 
But the resolution is different from the original report. The report was a false positive, but this is a false negative. (See also https://github.com/eslint/eslint/issues/11723#issuecomment-496038083)
This PR changes `require-atomic-updates` behavior.
- Makes the member accesses of parameters were not local. Parameters are local variables, but if it updates the member of a parameter asynchronously, it causes a race condition. This is the false negative that #11723 reported.
- ~~Makes the closure handling relax because it causes a ton of false positive. We cannot know if the closure will be run sync or async. If the synchronous callbacks such as …
=> Fix: require-atomic-updates reports parameters (fixes #11723)

docs/rules/prefer-destructuring.md
Fixes #9970 
Related discussion in PR [#9989](https://github.com/eslint/eslint/pull/9989)
Clarified the way the rule distinguishes between array and object destructuring and described the resulting …
=> Docs: Clarify prefer-destructuring array/object difference (fixes #9970)

package.json, webpack.config.js
🚨 As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions):
not really.
=> Upgrade: @babel/polyfill => core-js v3

Makefile.js, lib/cli-engine/config-array/config-array.js
=> Chore: rm superfluous argument & fix perf-multifiles-targets

lib/rules/no-var.js, tests/lib/rules/no-var.js
[X] Bug fix: [#11830](https://github.com/eslint/eslint/issues/11830)
This PR changes `no-var` auto fix behavior:
The rule will not fix declarations that contain a variable named `'let'`
=> Fix: no-var should not fix variables named 'let' (fixes #11830)

lib/rules/max-len.js, tests/lib/rules/max-len.js
Fixes: #11838
`stripTrailingComment` recursively to ignore trailing comments properly in the same line.
=> Fix: max-len properly ignore trailing comments (fixes #11838)

package.json, tests/lib/cli-engine/cascading-config-array-factory.js, tests/lib/cli-engine/cli-engine.js, tests/lib/cli-engine/formatters/codeframe.js, tests/lib/cli-engine/formatters/stylish.js, tests/lib/cli-engine/lint-result-cache.js, tests/lib/cli.js, tests/lib/init/config-file.js, tests/lib/init/config-initializer.js, tests/lib/init/npm-utils.js, tests/lib/init/source-code-utils.js, tests/lib/linter/linter.js, tests/lib/source-code/source-code.js
[X] Other
This PR updates `sinon` package to the latest version `7.3.2` from `3.3.0`. The old `sinon` depends on some deprecated packages, so this update removes some deprecation warnings of `npm install`.
And this PR fixes our tests as following [Migration Guide](https://sinonjs.org/guides/migrating-to-5.0.html).
=> Upgrade: sinon

docs/rules/no-floating-decimal.md
This ESLint rule handles both leading and trailing decimal points.
In order to ease discovery of this ESLint rule, mention the latter
warning as well, as users might only find those in their code.
https://github.com/jshint/jshint/blob/7993101/src/style.js#L100-L116
=> Docs: Add JSHint W047 compat to no-floating-decimal

lib/rules/multiline-comment-style.js, tests/lib/rules/multiline-comment-style.js
```js
/* eslint multiline-comment-style: [2, 'bare-block'] */
// Expected a block comment instead of consecutive line comments. (multiline-comment-style)
/*
* reqrewq
* rewqrewq 
*/
```
Error message is wrong because the code has no consecutive line comments.
This pr fix change the message when option `bare-block` is used and the code has a star-style comment. 
The error message is changed in the following way:
```diff
- Expected a block comment instead of consecutive line comments.
+ Expected a block comment without padding stars.
```
=> Fix: multiline-comment-style incorrect message

lib/rules/no-else-return.js, tests/lib/rules/no-else-return.js
[X] Bug fix [#11069](https://github.com/eslint/eslint/issues/11069)
Disable `no-else-return` auto-fix in cases where it would cause name collisions.
This prevents syntax errors:
```js
function foo(){
let bar = 0;
if (cond) {
return bar;
} else {
let bar = 1; // redeclaration, if the rule removes else and braces
return bar;
}
}
```
and reference changes:
```js
function bar() {
return 0;
}
function foo(){
if (cond) {
return bar(); // reference to the variable below, if the rule removes else and braces
} else {
let bar = 1;
return bar;
}
}
```
=> Fix: no-else-return autofix produces name collisions (fixes #11069)

docs/user-guide/migrating-to-6.0.0.md
=> Docs: Fix typo in 6.0.0 migration guide

docs/user-guide/migrating-to-6.0.0.md
This fixes some inconsistent formatting in the migration guide. Previously, the [`comma-dangle` header](https://eslint.org/docs/user-guide/migrating-to-6.0.0#comma-dangle-updates) was blue (and a link to itself) while all the other headers were not.
=> Docs: Fix inconsistent linking in migration guide

lib/cli-engine/cascading-config-array-factory.js, lib/cli-engine/cli-engine.js, tests/lib/cli-engine/cli-engine.js
[X] Bug fix: #11871
This PR fixes `CLIEngine` as the following code contains plugin rules.
```js
new CLIEngine({ plugins: ['foo'] }).getRules()
```
Previously, `CLIEngine#getRules()` contains core rules and the plugin rules that the last `CLIEngine#executeOn*()` methods call used.
This PR changes only the behavior that is before `CLIEngine#executeOn*()` methods called.
=> Fix: CLIEngine#getRules() contains plugin rules (fixes #11871)

docs/rules/no-confusing-arrow.md
- Removed redundant sentence from the summary as the default for allowParens is now true.
- Updated examples according to the new default.
N/A
=> Docs: Update no-confusing-arrow with the new default option

lib/cli-engine/config-array-factory.js, messages/extend-config-missing.txt, tests/lib/cli-engine/cli-engine.js
[x] Bug fix
* **Node Version:** 12.4.0
default
<details>
```js
extends: 'nonexistent-config'
};
```
</details>
(Any source code)
I expected to get an error message saying that `nonexistent-config` doesn't exist, with a useful indicator for which config was trying to load `nonexistent-config`.
**What actually happened? Please include the actual, raw output from …
=> Fix: improve diagnostics for shareable-config-missing errors

bin/eslint.js, lib/cli-engine/cli-engine.js, messages/print-config-with-directory-path.txt, tests/lib/cli-engine/cli-engine.js, tests/lib/cli.js
[X] Bug fix #11874
This PR fixes the error message when people used `--print-config` with a directory path.
```
> eslint --print-config .     
Oops! Something went wrong! :(
ESLint: 6.0.0.
'--print-config' CLI option requires a path to a source code file rather than a directory.
See also: https://eslint.org/docs/user-guide/command-line-interface#--print-config
```
Is this direction correct?
=> Fix: improve error message on --print-config (fixes #11874)

lib/cli-engine/cascading-config-array-factory.js, tests/lib/cli-engine/_utils.js, tests/lib/cli-engine/cli-engine.js
[X] Bug fix: #11888
This PR fixes a bug that `CLEngine` ignored `baseConfig` and `rulePaths` if a config file has `root:true`.
=> Fix: --rulesdir option didn't work (fixes #11888)

docs/user-guide/migrating-to-6.0.0.md
refs #9505
wording improvement?
=> Docs: add 'stricter rule config validating' in migrating docs

docs/rules/unicode-bom.md
Fixed incorrect code comments in code examples for "unicode-bom" rule
Comments in example code blocks (assuming wrong default)
=> Docs: Fix incorrect example comments for unicode-bom rule (fixes #11937)

lib/rule-tester/rule-tester.js
[X] Other, please explain: Small fix in rule tester
**ESLint Version:** master
  
Add the following test example to `tests/lib/rules/dot-location.js`:
```js
{
code: "obj\n.property",
output: "obj.\nproperty",
options: ["object"],
errors: [{ messageId: "expectedDotBeforeProperty" }]
}
```
```
AssertionError [ERR_ASSERTION]: messageId 'expectedDotAfterObject' does not match expected messageId 'expectedDotBeforeProperty'.
+ expected - actual
-expectedDotAfterObject
+expectedDotBeforeProperty
```
```
AssertionError [ERR_ASSERTION]: …
```
=> Fix: actual messageId and expected messageId are switched in rule tester

docs/rules/no-global-assign.md, docs/rules/no-native-reassign.md, docs/rules/no-undef.md
Replace in rule docs: 
`/*global a:false*/` with  `/*global a:readonly*/`
`/*global a:true*/` with  `/*global a:writable*/`
as these are now the preferable option names and more expressive than their aliases.
Also replaced `globals` with `global` to be consistent with the configuring doc and other rules (except `capitalized-comments` where there are both).
=> Docs: Replace global true and false with writable and readonly in rules

lib/linter/linter.js, tests/lib/linter/linter.js
[x] Bug fix
**issue:** #11929
There was an issue when there were comments like `/*global toString:true*/`
Therefor `if (enabledGlobals[id])`
https://github.com/eslint/eslint/blob/8eaa9b259dc08dfb48269b1e4413d0d47698ed87/lib/linter/linter.js#L315
was `true` because of `Object.prototype.toString`
=> Fix: creating of enabledGlobals object without prototype (fixes #11929)

.gitignore
These temporary files are being created during `npm test`, and could be accidentally committed:
* `.temp-eslintcache` created in `tests/bin/eslint.js` in `describe("cache files")`
* `tests/fixtures/autofix-integration/temp.js` created in `tests/bin/eslint.js` in `describe("automatically fixing files")`
Added both to .gitignore
Line endings, I got `LF will be replaced by CRLF` warning.
=> Chore: Add temporary test files to .gitignore

package.json
- Dependency upgrade / security fix
- Dependency upgrade
- reference https://github.com/lodash/lodash/issues/4348
=> Upgrade: Upgrade lodash dependency (fixes #11992)

docs/rules/no-duplicate-imports.md
I adjusted a typo to match the description format of found in the Options section.
> _This rule_ takes one optional argument ...
=> Docs: Fixed a typo (fixes #11999)

lib/cli-engine/cli-engine.js
Fixes #11945.
Add additional exception for `EROFS` (when cache file does not exist) next to the already existing `ENOENT` exception upon trying to delete cache file.
=> Fix: Cache file error handling on read-only file system.

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
[X] Bug fix
[issue #11699 ](https://github.com/eslint/eslint/issues/11699)
Fixed the autofix for the following cases:
```js
let {a, b} = c, d;
```
```js
let {a, b, c} = {}, e, f;
```
```
let {a, b} = {}, c = 0;
c = 1;
```
by moving and modifying logic from `checkGroup()` to `VariableDeclaration()`
=> Fix: prefer-const produces invalid autofix (fixes #11699)

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[x] Bug fix: [#11706](https://github.com/eslint/eslint/issues/11706)
In the `no-extra-parens` rule, keep parens if necessary when an `in` expression is in a for-loop initializer.
For example, the following will be treated as a correct code (not reported):
```js
for (let a = (b in c); ;);
for (let a = (b in c && d); ;);
for (let a = b => (b in c); ;);
```
Removing parens would produce SyntaxError. Each line would be treated as an invalid for-in loop.
Also, this change is trying to minimize false negatives, i.e. to remove really 'extra' parens.
For example, the following:
```js
for (let a = ((b in c) && (d in e)); ;);
```
would be fixed to:
```js
for (let a = (b in c && …
```
=> Fix: no-extra-parens autofix with `in` in a for-loop init (fixes #11706)

docs/rules/no-param-reassign.md, lib/rules/no-param-reassign.js, tests/lib/rules/no-param-reassign.js
no-param-reassign
more
```js
/* eslint no-param-reassign: ["error", { "props": true }] */
function foo(a) {
for (a.prop in obj);
for (a.prop of arr);
}
```
No warnings
2 warnings
Added `ForInStatement.left` and `ForOfStatement.left` checks. …
=> Update: Add for-in and for-of checks for props in no-param-reassign

Makefile.js, tools/update-readme.js
[x] Other, please explain: Update release script
refs https://github.com/eslint/website/issues/576
This updates the release script now that we've change the website repository name to `eslint/website`. …
=> Chore: update release script for new website repo

docs/rules/object-curly-newline.md
[ ] X Documentation update
fixes #11634
=> Docs: update docs for object-curly-spacing (fixes #11634)

lib/rules/arrow-body-style.js, tests/lib/rules/arrow-body-style.js
[x] Bug fix
Add parens for `SequenceExpression`.
=> Fix: add parens for sequence expr in arrow-body-style (fixes #11917)

docs/rules/dot-location.md, lib/rules/dot-location.js, lib/rules/utils/ast-utils.js, tests/lib/rules/dot-location.js, tests/lib/rules/utils/ast-utils.js
[X] Bug fix #11868
Fixed `dot-location` rule (`"object"` option) because it produces syntax errors with parenthesized objects. 
Parentheses around `MemberExpression.object` node are now treated as a part of the 'object'.
For example, the following was a false positive:
```js
( 
object
).
property
```
and the auto-fix produced syntax error:
```js
( 
object.
)
property
```
With this PR, the example above does not have a warning.
Also, with this PR auto-fix works correctly for similar cases that do have warnings. For example, this:
```js
( 
object
)
.property
```
will be fixed to:
```js
( 
object
).
property
```
I've also added several test cases unrelated to this issue. …
=> Fix: dot-location errors with parenthesized objects (fixes #11868)

docs/developer-guide/nodejs-api.md
`eslint.linter` exists for backwards compatibility, but we do not recommend using it because any mutations to it are shared among every module that uses `eslint`. Instead, please create your own instance of `eslint.Linter`.
no.
=> Docs: no use eslint.linter in code example

docs/rules/func-names.md
X [ ] Documentation update
Add these cases to docs:
```js
// Both of the two functions has implied names by spec.
const cat = {
meow: function() {}
}
const cat = {
meow() {}
}
```
=> Docs: add a case to func-names

docs/rules/no-restricted-globals.md
The global variable that the user doesn't want to use is event not error
I think the confusion came from the rule setting being named error
I've fixed an incorrect example in the documentation.
**Is …
=> Docs: Fix Incorrect Documentation

docs/rules/no-undef.md
[X] Documentation update #11963
Removed an example that does not apply to this rule.
Removed `writable` flag as it's irrelevant for this rule.
Modified a 'write' example (`b = 10`) to 'read' example (`var bar = a + 1`).
Should there be a 'correct' example like this:
```js
/*global b*/
/*eslint no-undef: "error"*/
b = 10;
```
It is indeed a correct code for this rule, but it isn't the right way to use eslint global variables in general.
=> Docs: Remove readonly/writable global logic from no-undef (fixes #11963)

lib/rules/class-methods-use-this.js, tests/lib/rules/class-methods-use-this.js
[X] Bug fix
This is a small bug fix, but it can produce more warnings.
default
<details>
```js
},
};
```
</details>
```js
/*eslint class-methods-use-this: ["error", { "exceptMethods": ["foo"] }] */
class A {
[foo]() {
}
}
```
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgY2xhc3MtbWV0aG9kcy11c2UtdGhpczogW1wiZXJyb3JcIiwgeyBcImV4Y2 …
=> Update: fix class-methods-use-this false negatives with exceptMethods

lib/rules/no-restricted-syntax.js
configured the rule invalidly:
```js
{
rules: {
'no-restricted-syntax': ['error', 'FunctionExpression', 1, false, [], {}],
}
}
```
eslint fails with a configuration validation errors
the rule ran fine with no errors.
--------------
For reference, running the current schema through jsonschemavalidator.net:
Running the new schema through jsonschemavalidator.net:
Running a lint with the new schema:
```
Error: .eslintrc.js: …
```
=> Fix: no-restricted-syntax - correct the schema

README.md, docs/user-guide/getting-started.md
do not recommend global-installed usage. this has been discussed for a long time, and seems we have done some work in this direction.
refs:
* https://github.com/eslint/eslint/issues/11914
* …
=> Docs: do not recommend global-installed usage

docs/rules/no-mixed-operators.md, lib/rules/no-mixed-operators.js, tests/lib/rules/no-mixed-operators.js
[X ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
https://github.com/eslint/eslint/issues/11704
Added additional check to see if the parent is a conditional expression and see if it's mixed and added messages for the same …
=> Update: warn about mixing ternary and logical operators (fixes #11704)

docs/developer-guide/scope-manager-interface.md
Removed TDZ Scope type and TDZ Definition type from `scope-manager-interface.md`
=> Docs: Remove TDZ scope from the scope manager interface documentation

lib/rules/no-unused-vars.js
To remove a condition that is always `true` as the TDZ scope type does not exist anymore.
Removed `scope.type !== "TDZ"` from `no-unused-vars`
=> Chore: Remove TDZ scope type condition from no-unused-vars

lib/rules/no-extra-boolean-cast.js, tests/lib/rules/no-extra-boolean-cast.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint no-extra-boolean-cast: "error"*/
// Bug #1
var foo = Boolean() ? bar() : baz();
if (Boolean()) {
foo();
}
while (Boolean()) {
foo();
}
// Bug #2
var foo = typeof!Boolean();
```
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZXh0cmEtYm9vbGVhbi1jYXN0OiBcImV …
=> Fix: no-extra-boolean-cast invalid autofix for Boolean() without args

lib/rules/no-extra-bind.js, tests/lib/rules/no-extra-bind.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint no-extra-bind: "error"*/
var boundF = (function (a, b) { 
return a + b;
}).bind(...foo);
```
No errors. 
Bind calls that apply arguments are allowed, I guess it can be assumed that `.bind(...foo)` is such case.
**What actually happened? …
=> Fix: Allow bind call with a single spread element in no-extra-bind

lib/rules/class-methods-use-this.js, tests/lib/rules/class-methods-use-this.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint class-methods-use-this: "error"*/
class A {
"foo"() {}
123() {}
[f()]() {}
}
```
Error messages with method names, where it is possible.
```
5:8  error …
```
=> Fix: class-methods-use-this reports 'undefined' names

lib/rules/sort-keys.js, tests/lib/rules/sort-keys.js
[X] Bug fix
This is a small bug fix, but it can produce more warnings.
default
<details>
```js
},
};
```
</details>
```js
/*eslint sort-keys: "error"*/
const obj = {
"a": 1,
"": 2
}
```
1 error
No errors.
**What changes did you …
=> Update: Check empty string property names in sort-keys

lib/rules/yoda.js, tests/lib/rules/yoda.js
[X] Bug fix
This small bug fix can produce only fewer warnings.
default
<details>
```js
},
};
```
</details>
```js
/*eslint yoda: ["error", "never", { "exceptRange": true }]*/
if (0 < x[``] && x[``] < 100) {} // backticks
```
No errors.
**What actually happened? Please include the actual, raw output from …
=> Fix: yoda exceptRange false positives on empty string property names

lib/rules/no-dupe-keys.js, tests/lib/rules/no-dupe-keys.js
[X] Bug fix
This is a small bug fix, but it can produce more warnings.
default
<details>
```js
},
};
```
</details>
```js
/*eslint no-dupe-keys: "error"*/
const obj = {
"": 1,
"": 2
}
```
1 error
No errors.
**What changes did you …
=> Update: fix no-dupe-keys false negatives on empty string names

lib/init/npm-utils.js
[x] Other, please explain: fix typo
Fixed minor typo.
Nope
=> Fix: minor typo

lib/rules/no-duplicate-case.js, tests/lib/rules/no-duplicate-case.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint no-duplicate-case: "error"*/
switch (foo) {
case toString:
break;
}
```
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZHVwbGljYXRlLWNhc2U6IFwiZXJyb3JcIiovXG5cbnN3aXRjaCAoZm9vKSB7XG4gIGNhc2UgdG9TdHJpbmc6XG4gICAgYnJlYWs7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRp …
=> Fix: no-duplicate-case false positives on Object.prototype keys

lib/rules/dot-notation.js, tests/lib/rules/dot-notation.js
[X] Bug fix
This is a small fix that prevents `dot-notation` from converting `bigint` and some regex literals to `null` in Node 8.
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgZG90LW5vdGF0aW9uOmVycm9yKi9cblxuYVsvKD88emVybz4wKS9dO1xuXG5cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) - the error is observable if you open this link in Firefox (which also doesn't support the syntax, like Node 8).
* **Node Version:** 8.16.0
* **npm Version:** 6.4.1
default
**Please show your full …
=> Fix: Check literal type explicitly in dot-notation

lib/rules/prefer-template.js, lib/rules/utils/ast-utils.js, tests/lib/rules/prefer-template.js, tests/lib/rules/utils/ast-utils.js
[X] Bug fix
default
<details>
```js
},
};
```
</details>
```js
/*eslint prefer-template: "error"*/
"\0 \1" + foo
```
```js
/*eslint prefer-template: "error"*/
"\08" + foo
```
Not a syntax error in autofix.
```js
/*eslint …
```
=> Fix: prefer-template autofix produces syntax error with octal escapes

docs/rules/function-call-argument-newline.md, lib/rules/function-call-argument-newline.js, lib/rules/index.js, tests/lib/rules/function-call-argument-newline.js, tools/rule-types.json
[x] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:) …
=> New: function-call-argument-newline rule (fixes #10323)

docs/rules/accessor-pairs.md, lib/rules/accessor-pairs.js, tests/lib/rules/accessor-pairs.js
[X] Bug fix
This is a **bug fix**, not an enhancement, but it will produce more errors by default.
default
<details>
```js
},
};
```
</details>
```js
/*eslint accessor-pairs: "error"*/
var o = { get a() {}, set b(foo) {} };
```
By default, this rule reports setters without getters.
I would expect 1 error …
=> Update: Fix accessor-pairs to enforce pairs per property in literals

docs/rules/accessor-pairs.md
Additional documentation for `accessor-pairs`  
[conversation in PR #12062](https://github.com/eslint/eslint/pull/12062#discussion_r314998502)
Added an example with duplicate keys to the Known Limitations section.
=> Docs: Add duplicate keys limitation to accessor-pairs

package.json, tests/lib/rules/require-unicode-regexp.js
[X] Other, please explain: update `eslint-utils` package.
This PR updates `eslint-utils` package. It has limited some method calling.
=> Upgrade: eslint-utils 1.4.2

docs/rules/no-useless-constructor.md
I switched the parent and child class names for the class extension examples in the rules for no-useless-constructor
=> Docs: corrected class extension example

lib/init/config-initializer.js, tests/lib/init/config-initializer.js
Added a new CLI option for TypeScript.
Should we add a separated CLI option for TypeScript? Or add it to an existing one?
=> New: support TypeScript at config initializer (fixes #11789)

lib/rules/no-extra-boolean-cast.js, tests/lib/rules/no-extra-boolean-cast.js
[X] Bug fix
* **ESLint Version:** 6.2.2
default
<details>
```js
},
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZXh0cmEtYm9vbGVhbi1jYXN0OiBcImVycm9yXCIqL1xuXG5mdW5jdGlvbiAqZm9vKCkge1xuICB5aWVsZCEhYSA/IGIgOiBjO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWx …
=> Fix: no-extra-boolean-cast invalid autofix with yield before negation

lib/rules/yoda.js, tests/lib/rules/yoda.js
[X] Bug fix
* **ESLint Version:** 6.2.2
default
<details>
```js
},
};
```
</details>
[Demo link 1](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG5cbmZ1bmN0aW9uICpmb28oKSB7XG4gIHlpZWxkKDEpIDwgYTtcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY …
=> Fix: yoda rule produces invalid autofix with preceding yield

lib/cli-engine/formatters/stylish.js, tests/lib/cli-engine/formatters/stylish.js
When we issue a warning on webpack, every warning is yellow and bold.
With `eslint-loader` and the` stylish` formatter the first line is different from the others. …
=> Fix: reset to the default color

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[X] Changes an existing rule #11916
New `enforceForSequenceExpressions` option in `no-extra-parens`, to avoid conflicts with `no-sequences`.
When this option is set to `false` (default is `true`) `no-extra-parens` rule does not report extra parens around sequence expressions.
`no-extra-parens`
fewer
new option
```js
/* eslint  no-extra-parens: "error" */
(a, b);
if ((a, b));
while((a, b));
```
3 warnings.
**What …
=> Update: enforceForSequenceExpressions to no-extra-parens (fixes #11916)

conf/config-schema.js, conf/default-cli-options.js, docs/user-guide/configuring.md, lib/cli-engine/config-array-factory.js, lib/cli-engine/config-array/config-array.js, lib/cli-engine/config-array/extracted-config.js, lib/linter/apply-disable-directives.js, lib/linter/linter.js, lib/options.js, lib/shared/types.js, tests/lib/cli-engine/cli-engine.js, tests/lib/cli-engine/config-array-factory.js, tests/lib/cli-engine/config-array/config-array.js, tests/lib/linter/apply-disable-directives.js, tests/lib/linter/linter.js
This PR adds `reportUnusedDisableDirectives` top-level property support to config files. This feature has been approved in eslint/rfcs#22.
=> New: reportUnusedDisableDirectives in config (refs eslint/rfcs#22)

lib/init/npm-utils.js
[x] Other, please explain: code refactoring
code refactoring
Nope
=> Chore: refactor code

lib/rules/quotes.js, tests/lib/rules/quotes.js
[X] Bug fix
* **ESLint Version:** 6.2.0
default
<details>
```js
},
};
```
</details>
```js
/*eslint quotes: ["error", "backtick"]*/
var foo = '\1';
```
Given how `prefer-template` works in similar situations, to report a warning but without the auto-fix. …
=> Fix: quotes autofix produces syntax error with octal escape sequences

lib/rules/no-extra-boolean-cast.js, tests/lib/rules/no-extra-boolean-cast.js
[X] Bug fix #11324
This PR fixes `no-extra-boolean-cast` to report the correct node - double negation instead of its inner negation.
Note: This PR closes #11324 as the reported `range` was not a bug.  Reported `column` was indeed a bug, and it's fixed with this PR.
* **ESLint Version:** 6.3.0
default
<details>
```js
}
};
```
</details>
```js
/*eslint …
```
=> Fix: no-extra-boolean-cast reports wrong negation node (fixes #11324)

lib/cli-engine/config-array/override-tester.js, tests/lib/cli-engine/cli-engine.js, tests/lib/cli-engine/config-array/override-tester.js
[X] Bug fix
This PR fixes #12032.
The cause was the reuse of `OverrideTester` instances in spite of mutable.
=> Fix: OverrideTester basePath (fixes #12032)

docs/rules/space-in-parens.md, lib/rules/space-in-parens.js, tests/lib/rules/space-in-parens.js
The current space-in-parens description is a little unclear. Technically empty parens can trigger an error if specified in the exceptions options. This PR updates that line in the docs and adds a paragraph that attempts to explain what exactly this rule does. [Current rule description](https://eslint.org/docs/rules/space-in-parens#rule-details).
The linting error messages are now more specific and inform whether the paren token is either rejecting an extra space or missing a required space. Previously the output did not specify if the space was required or missing (so it could be either).
The previous context/report behavior would sometimes report only the first error encountered within a node due to the token checks …
=> Update: space-in-parens linting messages and report behaviour

docs/rules/default-param-last.md, lib/rules/default-param-last.js, lib/rules/index.js, tests/lib/rules/default-param-last.js, tools/rule-types.json
closes #11361.
X [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
Enforce default params to be last. Only es6 default params are dealt with.
[ ] Enforces code style
[ ] Warns about a potential error
X [ ] Suggests an alternate way of doing something
[ ] Other (please specify:)
**Provide 2-3 code examples that this rule will warn about:**
```js
function f(a = 5, b) {}
function f(a, b = 5, c) {}
```
**Why should this rule be included in ESLint (instead of a plugin)?**
See the accepted proposal #11361. …
=> New: add rule default-param-last (fixes #11361)

lib/rules/eqeqeq.js, tests/lib/cli-engine/cli-engine.js, tests/lib/rules/eqeqeq.js
[X] Bug fix
* **ESLint Version:**  6.3.0
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGVxZXFlcTplcnJvciAqL1xuXG4oYSArIGIpID09IGM7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJ …
=> Fix: eqeqeq rule reports incorrect locations

lib/rules/space-before-function-paren.js, tests/lib/rules/space-before-function-paren.js
[X] Bug fix #12259
This PR fixes the `space-before-function-paren` rule fixer with the `"never"` option, to:
* Concatenate block comments instead of removing them.
* Report error but doesn't fix anything if there is a line comment between.
Example:
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHNwYWNlLWJlZm9yZS1mdW5jdGlvbi1wYXJlbjpbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cblxuZnVuY3Rpb24gZm9vIC8qICovKCl7fVxuXG5mdW5jdGlvbiBiYXIgLyogMSAqL1xuLyogMiAqL1xuLyogMyAqLyAoKXt9XG5cbmZ1bmN0aW9uIGJheiAvLyBsaW5lIGNvbW1lbnRcbigpe31cblxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV …
=> Fix: space-before-function-paren autofix removes comments (fixes #12259)

docs/rules/no-obj-calls.md, lib/rules/no-obj-calls.js, tests/lib/rules/no-obj-calls.js
[X] Bug fix
[X] Changes an existing rule #12234
This PR modifies the `no-obj-calls` to:
* Report `Atomics()` as described in #12234, which can produce **more** errors by default.
* Report only globals, which can produce fewer errors.
E.g., the rule will not report `Math()` if the `Math` is shadowed or turned `off`.
Also, the rule will not report `Reflect()` if an ES2015+ environment is not activated (and the variable isn't added manually as a global in the config file or `/*global*/`). The same applies to `Atomics` and ES2017+ environment.
Added `Atomics` to the list of non-callable globals and modified the logic to report only references to defined global variables. …
=> Update: Report global Atomics calls in no-obj-calls (fixes #12234)

docs/rules/prefer-regex-literals.md, lib/rules/index.js, lib/rules/prefer-regex-literals.js, tests/lib/rules/prefer-regex-literals.js, tools/rule-types.json
[X] New rule #12238
```js
new RegExp("abc");
new RegExp("abc", "u");
RegExp("abc");
RegExp("abc", "u");
new RegExp("\\d\\d\\.\\d\\d\\.\\d\\d\\d\\d");
RegExp(`^\\d\\.$`);
new RegExp(String.raw`^\d\.$`);
```
Examples of **correct** code for this rule:
```js
/abc/;
/abc/u;
/\d\d\.\d\d\.\d\d\d\d/;
/^\d\.$/;
// RegExp constructor is allowed for dynamically generated regular expressions
new RegExp(pattern);
RegExp("abc", flags);
new RegExp(prefix + "abc");
RegExp(`${prefix}abc`);
new RegExp(String.raw`^\d\. ${sufix}`);
```
Added new rule `prefer-regex-literals`
=> New: Add prefer-regex-literals rule (fixes #12238)

docs/rules/no-import-assign.md, lib/rules/index.js, lib/rules/no-import-assign.js, tests/lib/rules/no-import-assign.js, tools/rule-types.json
[X] New rule: fixes #12237.
This PR adds a new rule `no-import-assign`.
- Is documentation enough?
- Are tests enough?
=> New: add no-import-assign (fixes #12237)

lib/rules/object-shorthand.js, tests/fixtures/parsers/typescript-parsers/object-with-arrow-fn-props.js, tests/lib/rules/object-shorthand.js
[x] Bug fix 
Related: https://github.com/typescript-eslint/typescript-eslint/issues/124
The bug is that currently the fixer adds extra parentheses when fixing a TS arrow function with a return type:
```ts
/* eslint object-shorthand: [1, "always", { avoidExplicitReturnArrows: true }] */
const test = {
key: (arg: any): any => {}
}
///// fixes to
const test = {
key((arg: any): any) {}
}
```
This happens because the rule currently searches backwards from the `=>` to find a `)`, to determine if it should wrap the arguments in parentheses. It obviously instead finds a return type annotation, hence the breakage.
Adjusted the fix algorithm for arrow functions so that it …
=> Fix: object-shorthand providing invalid fixes for typescript

lib/rules/no-sequences.js, tests/lib/rules/no-sequences.js
[X] Bug fix
* **ESLint Version:**  6.3.0
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXNlcXVlbmNlczplcnJvciAqL1xuXG4oMSksIDI7XG4oKDEpKSAsICgyKTtcbndoaWxlKCgxKSAsIDIpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3R …
=> Fix: no-sequences is reporting incorrect locations

lib/rules/indent.js, tests/lib/rules/indent.js
fixes #12232
This PR adds additional logic for comments that precede a line that begins with a semicolon. The current behavior (indenting 1 level) exists because the comment is treated as a child of …
=> Update: indentation of comment followed by semicolon (fixes #12232) 

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
[X] Bug fix #11902
This PR allows one particular exception in `object-curly-spacing` default behavior, and nothing more:
* When the option is `never`, spaces will be allowed between `{` and a line comment `//`.
All other combinations of options and comments are unchanged.
`object-curly-spacing`
fewer
```js
/*eslint object-curly-spacing: ["error", "never"]*/
var foo = { // line comment
bar: baz
}
var { // line comment …
```
=> Fix: Allow line comment exception in object-curly-spacing (fixes #11902)

docs/developer-guide/working-with-plugins.md, docs/user-guide/configuring.md
Updated the "Working with Plugins" documentation section to clarify the usage of scoped and non-scoped packages for ESLint plugins. This was something that was never really clear to me, which led me to openning #12190 .
I am not sure I made the edits in the right place. If not, please point me to the right direction.
=> Docs: Added naming convention details to plugin usage

docs/rules/computed-property-spacing.md, lib/rules/computed-property-spacing.js, tests/lib/rules/computed-property-spacing.js
[X] Changes an existing rule #12049
`computed-property-spacing`
More if the option is set to `true`. Default is `false`.
New option `enforceForClassMembers`
```js
/*eslint computed-property-spacing: ["error", "never"]*/
class Foo {
[a ]() {}
get [ b ](){}
set [ b ](val){}
static [ c](){}
static get [ d](){}
static set [d ](val){}
}
```
No errors.
```js
/*eslint …
```
=> Update: enforceForClassMembers computed-property-spacing (fixes #12049)

lib/rules/no-lone-blocks.js, tests/lib/rules/no-lone-blocks.js
[X] Bug fix
* **ESLint Version:** 6.3.0
* **Node Version:** 11.12.0
* **npm Version:** 6.7.0
default
<details>
```js
},
};
```
</details>
There is a hole in the `ES6` logic for the `no-lone-blocks` rule. It is set to accept blocks with declarations, but if such a block appears as a lonely child of another block, it should be an error.
```javascript
// Not caught by the rule prior to this PR
{
const x = …
```
=> Fix: patch hole in the no-lone-blocks rule

docs/rules/accessor-pairs.md, lib/rules/accessor-pairs.js, tests/lib/rules/accessor-pairs.js
[X] Changes an existing rule #12063
`accessor-pairs`
More if the option is set to `true`. Default is `false`.
New option.
```js
/*eslint accessor-pairs: ["error", { "enforceForClassMembers": true }]*/
class foo {
set a(bar) {}
}
```
Nothing
Error: `"Getter is not present for class setter 'a'."`
New option …
=> Update: enforceForClassMembers option to accessor-pairs (fixes #12063)

docs/rules/operator-linebreak.md
- The "default" option is now set to `overrides` instead of `after` because the ternary examples in `after` may be misleading.
- Changed the example in `overrides` to reflect the default behavior. …
=> Docs: Improve examples and clarify default option

lib/rules/capitalized-comments.js, packages/eslint-config-eslint/default.yml
note: this is a breaking change in eslint-config-eslint.
refs:https://github.com/eslint/eslint/commit/0313441d016c8aa0674c135f9da67a676e766ec5
[x] Other, please explain: just dog fooding the new rule. :-)
not really.
=> Chore: enable default-param-last

lib/rules/indent.js, tests/lib/rules/indent.js
fixes #12208
This PR adds support to the `indent` rule for JSX Fragments, which are currently ignored. While working on this, I noticed that comments inside both JSX Element and Fragment tags are …
=> Update: add support for JSXFragments in indent rule (fixes #12208)

docs/developer-guide/nodejs-api.md
Add a clarifying example in the documentation for the optional 3rd parameter of `CLIEngine#executeOnText()`
=> Docs: add example for CLIEngine#executeOnText 3rd arg

docs/rules/array-callback-return.md
Fixed `Array.prototype.findIndex` and `Array.prototype.reduceRight` links in [array-callback-return](https://eslint.org/docs/rules/array-callback-return).
This is a minimal change, the links are still to the ES2015 spec.
As noted in #12267, should the docs maybe use [https://tc39.es/ecma262/](https://tc39.es/ecma262/) links instead? It's a living standard, but also has a 'Draft' title. Another alternative is to change all links to ES2019.
=> Docs: fix links in array-callback-return

docs/developer-guide/working-with-rules.md
https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/
=> Docs: English fix

lib/rules/prefer-numeric-literals.js, tests/lib/rules/prefer-numeric-literals.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Online demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1udW1lcmljLWxpdGVyYWxzOmVycm9yICovXG5cbnBhcnNlSW50KFwiMTFcIiwgLyogY29tbWVudCAqLyAyKTtcblxuTnVtYmVyIC8vIGNvbW1lbnRcbiAgICAucGFyc2VJbnQoXCIxMVwiLCAyKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUs …
=> Fix: prefer-numeric-literals autofix removes comments

lib/shared/runtime-info.js, tests/lib/shared/runtime-info.js
This change improves performance by caching the results of the shell commands the `RuntimeInfo` module executes. In practice, this only improves performance when ESLint is installed locally and …
=> Chore: cache results in runtime-info

lib/cli-engine/cli-engine.js, lib/cli-engine/ignored-paths.js, lib/cli-engine/lint-result-cache.js, lib/init/config-rule.js, lib/init/npm-utils.js, lib/linter/code-path-analysis/debug-helpers.js, lib/linter/linter.js, lib/rule-tester/rule-tester.js, lib/rules/indent-legacy.js, lib/shared/logging.js, lib/source-code/source-code.js, package.json, packages/eslint-config-eslint/default.yml, packages/eslint-config-eslint/package.json, tests/lib/_utils.js, tests/lib/cli-engine/_utils.js, tests/lib/cli-engine/cascading-config-array-factory.js, tests/lib/cli-engine/cli-engine.js, tests/lib/cli-engine/file-enumerator.js, tests/lib/cli-engine/ignored-paths.js, tests/lib/cli.js, tests/lib/init/config-initializer.js, tests/lib/init/source-code-utils.js, tests/tools/loose-parser.js, tools/code-sample-minimizer.js, tools/internal-rules/no-invalid-meta.js
refs https://github.com/eslint/eslint/issues/11146
Finally have the time to switch to [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) in `eslint-config-eslint` now that our core JSDoc rules are deprecated!
**What changes did …
=> Chore: enable eslint-plugin-jsdoc (refs #11146)

Makefile.js, package.json
This adds a `fix` flag to the `lint` task in `Makefile.js` and adds a `fix` npm script as a small convenience for contributors.
Nothing in …
=> Chore: add autofix npm script

lib/rules/new-parens.js, tests/lib/rules/new-parens.js
[X] Bug fix
This bug fix can produce **more** errors by the `new-parens` rule in some cases. Also fixes wrong autofix in some other cases.
default
<details>
```js
}
};
```
</details>
[Demo link 1](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5ldy1wYXJlbnM6W1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxubmV3IG5ldyBmb28oKTsiLCJvcHRpb25zIjp7InBhcn …
=> Update: Fix handling of chained new expressions in new-parens

lib/rules/no-useless-rename.js, tests/lib/rules/no-useless-rename.js
fixes #12301 
This updates `no-useless-rename` to check destructured assignments with default values. I think this should be considered a semver-minor bug fix, since it feels like an oversight that …
=> Update: no-useless-rename also reports default values (fixes #12301)

bin/eslint.js, tests/bin/eslint.js
closes eslint/eslint#12212
[ X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
See https://github.com/eslint/eslint/issues/12212
Applied nodejs recommendations for processing stdin as per https://github.com/nodejs/node/blob/master/doc/api/process.md#p …
=> Fix: use async reading of stdin in bin/eslint.js

lib/rules/no-undef-init.js, tests/lib/rules/no-undef-init.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVuZGVmLWluaXQ6ZXJyb3IgKi9cblxubGV0IGEgLyogY29tbWVudCAqLyA9IHVuZGVmaW5lZDtcblxubGV0IGIgPSAvLyBjb21tZW50XG4gICAgdW5kZWZpbmVkOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWF …
=> Fix: no-undef-init autofix removes comments

lib/rules/no-extra-label.js, tests/lib/rules/no-extra-label.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLWxhYmVsOmVycm9yICovXG5cbkE6IHdoaWxlICh0cnVlKSB7XG4gIGJyZWFrIC8qIGNvbW1lbnQgKi8gQTtcbn1cblxuQjogd2hpbGUgKHRydWUpIHtcbiAgY29udGludWUvKiBjb21tZW50ICovQjtcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjY …
=> Fix: no-extra-label autofix removes comments

lib/rules/no-useless-return.js, tests/lib/rules/no-useless-return.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVzZWxlc3MtcmV0dXJuOmVycm9yICovXG5cbmZ1bmN0aW9uIGZvbygpIHtcbiAgYmFyKCk7XG4gIHJldHVybiAvKiBjb21tZW50ICovO1xufVxuXG5mdW5jdGlvbiBiYXooKSB7XG4gIGJhcigpO1xuICByZXR1cm4gLy8gY29tbWVudFxuICA7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25 …
=> Fix: no-useless-return autofix removes comments

lib/rules/prefer-named-capture-group.js, tests/lib/rules/prefer-named-capture-group.js
[X] Bug fix #12233
This PR fixes reporting incorrect location in `prefer-named-capture-group` when the pattern in `RegExp()` or `new RegExp()` is any of the following:
* Computed string
* String with an escape sequence
* Multiline string
* **ESLint Version:**  6.3.0
default
<details>
```js
}
};
```
</details>
[Demo …
=> Fix: prefer-named-capture-group incorrect locations (fixes #12233)

lib/rules/no-regex-spaces.js, tests/lib/rules/no-regex-spaces.js
[X] Bug fix #12226 + 2 other bugs.
This PR fixes 3 unrelated bugs in `no-regex-spaces`:
1. False positives in character classes (e.g. `/[  ]/` fixed to `/[ {2}]/`)
2. Invalid autofix for strings with escape sequences (e.g. `RegExp('\\d  ')` fixed to `RegExp('\\ {2} ')`)
3. Regex with invalid syntax were reported and fixed (e.g. `RegExp('[  ')` fixed to `RegExp('[ {2}')`). This might not be a bug, but I guess it's better to ignore invalid regex.
**1. Character classes**
The following tests were failing:
```js
// valid[]
"var foo = /[  ]/;",
"var foo = /[   ]/;",
"var foo = / [  ] /;",
"var foo = new RegExp('[  ]');",
"var foo = new RegExp('[   ]');",
"var foo = new RegExp(' [  ] ');",
// invalid[]
"var foo = /[   ] …
```
=> Fix: no-regex-spaces false positives and invalid autofix (fixes #12226)

lib/rule-tester/rule-tester.js, tests/lib/rule-tester/rule-tester.js
https://github.com/eslint/eslint/issues/12027
I remove an unnecessary `\u000d` so that a new line will show properly.  
=> Fix: exclude `\u000d` so new line won't convert to text (fixes #12027)

docs/rules/use-isnan.md, lib/rules/use-isnan.js, tests/lib/rules/use-isnan.js
Refs #12207
`use-isnan`
More if the option is set.
New option, which might be removed in major version to be new default behavior.
```js
/*eslint use-isnan: ["error", {"enforceForSwitchCase": true}]*/
switch (foo) {
case NaN:
bar();
break;
case 1:
baz();
break;
// ...
}
```
Nothing.
Report warning.
`case NaN` is a possible error, basically …
=> Update: Add enforceForSwitchCase option to use-isnan

lib/rules/no-useless-rename.js, tests/fixtures/parsers/babel-eslint10/object-pattern-with-rest-element.js, tests/lib/rules/no-useless-rename.js
fixes #12335
https://github.com/eslint/eslint/pull/12322 removed the check for `ExperimentalRestProperty`, causing the rule to crash with babel-eslint. This will be fixed by …
=> Fix: no-useless-rename handles ExperimentalRestProperty (fixes #12335)

docs/rules/no-magic-numbers.md
[ x ] Documentation update
Added a missing "s" to "times" to correct the grammar.
=> Docs: fix typo in no-magic-numbers

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG_REPORT.md
[x] Other, please explain: 
updated the issue template accordingly such that it instructs the user to use `eslint --env-info` to find information converning his/her local environment.
`v6.5.0` release introduced a new …
=> Chore: update issue template with --eslint-fix flag

docs/rules/no-process-env.md
Very minor change to the documentation.
No.
=> Fix missing word in sentence

docs/developer-guide/contributing/pull-requests.md, docs/rules/no-obj-calls.md, docs/rules/space-infix-ops.md, docs/rules/symbol-description.md
* Fixed link to code conventions from the pull requests doc
* "[[Call]]" => "`[[Call]]`" in no-obj-calls doc
* Object literal spacing in example config in space-infix-ops
* "may have optional description" => "may have an optional description" in symbol-description
No.
=> Docs: Fix minor formatting/grammar errors

docs/rules/max-depth.md
As mentioned by @imai0917 on #11991, the example given for `max-depth` in the documentation doesn't trigger the rule, so this updates the example with one that does. …
=> Docs: fix wrong max-depth example (fixes #11991)

lib/linter/linter.js
Clean up somewhat confusing code.
While exploring what would be required to implement [RFC #34](https://github.com/eslint/rfcs/pull/34) I looked into this code and found it more confusing than it …
=> Chore: Clean up inline directive parsing

lib/cli-engine/cascading-config-array-factory.js, lib/cli-engine/config-array/config-dependency.js, lib/cli-engine/config-array/override-tester.js, lib/cli-engine/file-enumerator.js, lib/cli-engine/formatters/html.js, lib/cli-engine/ignored-paths.js, lib/init/autoconfig.js, lib/init/config-rule.js, lib/linter/code-path-analysis/code-path-analyzer.js, lib/linter/code-path-analysis/code-path-segment.js, lib/linter/code-path-analysis/code-path-state.js, lib/linter/code-path-analysis/code-path.js, lib/linter/code-path-analysis/fork-context.js, lib/linter/code-path-analysis/id-generator.js, lib/linter/node-event-generator.js, lib/rules/default-param-last.js, lib/rules/indent.js, lib/rules/no-dupe-keys.js, lib/rules/no-unused-expressions.js, lib/rules/prefer-destructuring.js, lib/rules/vars-on-top.js, lib/shared/traverser.js, packages/eslint-config-eslint/default.yml, tests/lib/rule-tester/rule-tester.js
Following up on https://github.com/eslint/eslint/pull/12336#pullrequestreview-295990298, this PR enables the `jsdoc/require-description` rule, using `eslint-disable-*` comments for the 30 instances …
=> Chore: enable jsdoc/require-description

docs/user-guide/migrating-to-6.0.0.md
I fixed a typo in the "Migrating to v6.0.0" page of the documentation.
=> Docs: Fix typo in v6 migration guide

docs/user-guide/configuring.md
This patch updates the [Use a Plugin](https://eslint.org/docs/user-guide/configuring#use-a-plugin) example which has `rules` listed as an array instead of a regular object. …
=> Docs: Fixes object type for `rules` in "Use a Plugin"

README.md
Clarified the semver policy around `eslint:recommended`, based on [this TSC resolution](https://github.com/eslint/tsc-meetings/blob/63e51177ebcfdbaeaaa35f79d237b3f99cda3b04/notes/2019/2019-10-10.md#re …
=> Docs: Clarify `eslint:recommended` semver policy

lib/rules/no-self-assign.js, tests/lib/rules/no-self-assign.js
[x] Changes an existing rule 
[`no-self-assign`](https://eslint.org/docs/rules/no-self-assign)
more
updates default behavior
```js
this.x = this.x
```
doesn't raise an issue
raise an issue
I updated  `no-self-assign` rule to support member expression using `this` identifier. …
=> Update: no-self-assign should detect member expression with this

docs/developer-guide/nodejs-api.md, docs/developer-guide/working-with-rules.md, lib/cli-engine/cli-engine.js, lib/linter/linter.js, tests/lib/linter/linter.js
Pass the cwd from the cli engine
https://github.com/eslint/eslint/issues/11218
RFC link: https://github.com/eslint/rfcs/pull/35
`Linter.js`
=> New: pass cwd from cli engine

docs/developer-guide/unit-tests.md, package.json
[x] Other, please explain: Add a script to `package.json`
Issue link: https://github.com/eslint/eslint/issues/12442
Not sure whether I am the only one, I tends to not read the documentation page by page before the development …
=> Chore: Add a script for testing with more control

lib/rules/no-multi-spaces.js, tests/lib/rules/no-multi-spaces.js
Change the report location of no-multi-spaces. Previously the rule highlights the token next to the problematic spaces. Now the rule highlights the problematic spaces.
```js
foo &&  moo
//      ~~~    before
//    ~~       after
[1, 2,   ...a]
//       ~~~   before
//    ~~~      after
```
no
=> Update: improve report location for no-multi-spaces

lib/rules/space-in-parens.js, tests/lib/rules/space-in-parens.js
Change the report location of no-space-in-parens. When option `never`, location is changed to that of the disallowed spaces. When option 'always', missing end location is added. This change fixes part of #12334, where missing end location causes VS code to render highlighting tildes in unexpected locations.
```js
/* eslint no-space-in-parens: [2, 'never'] */
Math.random( foo)
//   ~~~~~~          vs code report location — before
//          ~        vs code report location — after
//         ~         report location — before (missing end location)
//          ~        report location — after
/* eslint no-space-in-parens: [2, 'always'] */ …
```
=> Update: improve report location for no-space-in-parens

lib/rules/keyword-spacing.js, tests/lib/rules/keyword-spacing.js
Remove `default` property in overrides scheme
I found that `the overrides scheme's default value` override `the undeclared overrides option's value` …
=> Update: remove default overrides in keyword-spacing (fixes #12369)

lib/source-code/source-code.js, tests/lib/source-code/source-code.js
[X] Bug fix (#12263)
Fix regex in sourceCode.isSpaceBetweenTokens() 
#12263
=> Update: Regex incorrectly checks newline in comments (fixes #12263)

lib/rules/dot-location.js, tests/lib/rules/dot-location.js
Fixes `dot-location` to report the full location of the dot token instead of just its start. This can improve highlighting behavior in editors.
For example, [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGRvdC1sb2NhdGlvbjogZXJyb3IgKi9cblxuYVxuICAgIC5iO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19) at the moment doesn't highlight anything. 
`dot.loc.start` -> `dot.loc`
=> Fix: report full dot location in dot-location

lib/rules/array-bracket-newline.js, tests/lib/rules/array-bracket-newline.js
[X] Bug fix #12416
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktYnJhY2tldC1uZXdsaW5lOiBbXCJlcnJvclwiLCBcImNvbnNpc3RlbnRcIl0qL1xuXG5jb25zdCBmb28gPSBbIC8vIGNvbW1lbnRcbiAgMSxcbiAgMlxuXTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3Jpc …
=> Fix: array-bracket-newline consistent error with comments (fixes #12416)

docs/rules/no-extra-parens.md, lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[X] Changes an existing rule #12428
no-extra-parens
Fewer if the option is set to `false`. Default is `true`.
new option `enforceForNewInMemberExpressions`
```js
/* eslint no-extra-parens: "error" */
const foo = (new Bar()).baz; // error
const quux = (new Bar())[baz]; // error
(new Bar()).doSomething(); // error
```
3 errors.
No errors if the option is set to `false`: …
=> Update: enforceForNewInMemberExpressions no-extra-parens (fixes #12428)

lib/rules/prefer-numeric-literals.js, tests/lib/rules/prefer-numeric-literals.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1udW1lcmljLWxpdGVyYWxzOiBbXCJlcnJvclwiXSAqL1xuXG5pZiAocGFyc2VJbnQoXCIxMVwiLCAyKWluIGZvbykge1xuICBkb1NvbWV0aGluZygpO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIs …
=> Fix: prefer-numeric-literals invalid autofix with adjacent tokens

lib/rules/no-mixed-operators.js, tests/lib/rules/no-mixed-operators.js
Make no-mixed-operators report both start and end location, instead of only start location. 
```js
let p = a && b || c
//        ~    ~    before
//        ~~   ~~   after
``` 
No
=> Update: improve report location for no-mixed-operators

lib/linter/linter.js
When there's an exception thrown by the parser, currently ESLint swallows this exception.
This is fine for end users, as it allows ESLint to provide a nicer experience, but can make it hard for parser developers to debug problems when reported by users.
This change simply adds a debug log message which includes the exception stack when a parser exception occurs.
That way we can just instruct users to run `eslint --debug` so we can get the exception stack (amongst other things) from them.
=> Chore: Provide debug log for parser errors

lib/rules/comma-dangle.js, tests/lib/rules/comma-dangle.js
- Enable `function string option` in comma-dangle.
- #12058
=> Update: Enable function string option in comma-dangle (fixes #12058)

README.md, docs/user-guide/getting-started.md
Adds a small note that Node.js requires SSL to be built in. While this hasn't affected many users, it's good to document in case this comes up in the future. (And the Node.js project itself did run …
=> Docs: Add note about Node.js requiring SSL support (fixes #11413)

package.json, tests/lib/rules/no-obj-calls.js
[X] Bug fix: #12437.
This PR updates `eslint-utils` package to fix a bug in `ReferenceTracker`. The fix is https://github.com/mysticatea/eslint-utils/commit/8f9e481ecc1204c7a1331b697f97903f90c75154, it was passing through unary/binary/conditional expressions to track.
=> Fix: no-obj-calls false positive (fixes #12437)

lib/rules/dot-location.js
The `obj` param in `dot-location` check function became unused after some changes. Both `obj` and `prop` are redundant since the third param is their `MemberExpression` node.
Removed the unused `obj` param and the unnecessary `prop` param in `dot-location`.
=> Chore: Remove unused parameter in dot-location

docs/rules/no-param-reassign.md, lib/rules/no-param-reassign.js, tests/lib/rules/no-param-reassign.js
Clickbait title. Not actually regex. Just a string that looks like a regex.
`no-param-reassign`: https://eslint.org/docs/rules/no-param-reassign
**Does this change cause the rule to produce more or fewer …
=> Update: Allow regex in no-param-reassign ignore option array

lib/rules/no-param-reassign.js
We merged a PR (#11275) that had been waiting for a while, and we had added a lint rule since it had been opened that caused the build to fail once merged to master. …
=> Chore: Fix lint failure in JSDoc comment

lib/cli-engine/cli-engine.js, tests/lib/cli-engine/cli-engine.js
[X] Bug fix: #12425
This PR fixes `CLIEngine#addPlugin()` method to reset `lastConfigArrays` internal state as well. Because `CLIEngine#getRules()` gets plugin rules from the `lastConfigArrays` internal state, this reset is needed.
=> Fix: CLIEngine#addPlugin reset lastConfigArrays (fixes #12425)

lib/rules/operator-assignment.js, tests/lib/rules/operator-assignment.js
[X] Bug fix
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG9wZXJhdG9yLWFzc2lnbm1lbnQ6IFtcImVycm9yXCIsIFwibmV2ZXJcIl0qL1xuXG5mb28rPStiYXIiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9 …
=> Fix: operator-assignment invalid autofix with adjacent tokens

lib/rules/operator-assignment.js, tests/lib/rules/operator-assignment.js
[X] Bug fix
This PR fixes `operator-assignment` to prevent autofix if it would remove or duplicate comments.
default
<details>
```js
}
};
```
</details>
[Online Demo Link 1](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG9wZXJhdG9yLWFzc2lnbm1lbnQ6IFtcImVycm9yXCIsIFwiYWx3YXlzXCJdKi9cblxueCA9IC8qIGNvbW1lbnQgKi8geCArIHk7XG5cbnggPSB4IC8vIGNvb …
=> Fix: operator-assignment removes and duplicates comments

lib/cli-engine/config-array-factory.js
I've added measurement of loading time for each plugin. Times are shown in debug output.
The reason is in unexpectedly significant startup time for some plugins, even when there is nothing to check …
=> Update: measure plugin loading time and output in debug message

docs/rules/use-isnan.md, lib/rules/use-isnan.js, tests/lib/rules/use-isnan.js
[X] Changes an existing rule #12207
Examples of **incorrect** code for this rule with `"enforceForIndexOf"` option set to `true`:
```js
/*eslint use-isnan: ["error", {"enforceForIndexOf": true}]*/
var hasNaN = myArray.indexOf(NaN) >= 0;
var firstIndex = myArray.indexOf(NaN);
var lastIndex = myArray.lastIndexOf(NaN);
```
New option `enforceForIndexOf` in the `use-isnan` rule.
It seemed too complex to have an advice in the message since it depends on whether the user wants to find index or just check for existence, and also what environments are available. There are examples in the docs for different environments.
=> Update: Add enforceForIndexOf option to use-isnan (fixes #12207)

lib/rules/no-misleading-character-class.js, tests/lib/rules/no-misleading-character-class.js
[X] Bug fix #12169
<details>
```js
}
};
```
</details>
```js
/* eslint no-misleading-character-class: ["error"] */
var r = new RegExp('[Á] [ ');
```
Not to crash.
```
SyntaxError: Invalid regular expression: /[Á] [ /: …
```
=> Fix: no-misleading-character-class crash on invalid regex (fixes #12169)

lib/rules/no-trailing-spaces.js, tests/lib/rules/no-trailing-spaces.js
[X ] Bug fix #12479
This change produces **more** errors.
This PR fixes `no-trailing-spaces` to report trailing spaces after block comments when the `ignoreComments` option is set to `true`. 
The option allows trailing spaces * in * comments, not after comments.
In addition to the example from #12479, the following are also false negatives (all lines with comments have trailing spaces):
```js
/* eslint no-trailing-spaces: ["error", { ignoreComments: true }]*/ 
/* */     
/* */foo     
/* 
*/foo     
```
Don't count the last line of a `Block` comment as a 'comment line' that should be ignored.
=> Update: no-trailing-spaces false negatives after comments (fixes #12479)

lib/rules/no-trailing-spaces.js, tests/lib/rules/no-trailing-spaces.js
[X] Changes an existing rule #12315
Reports the full location (start+end) of trailing spaces.
Before this fix:
After this fix:
Added the `end` to the location.
It looks a bit unusual to read from the `location` to calculate the `range`, but I didn't change that. Tried a version with intermediate variables and it didn't add any clarity (was the opposite, actually).
This is a kind of enhancement, but I think it could be processed as a bug fix (i.e. accepted with 1 confirmation).
=> Update: improve report location for no-trailing-spaces (fixes #12315)

lib/rules/function-call-argument-newline.js, tests/lib/rules/function-call-argument-newline.js
Fixes #12123
Given two adjacent arguments (`a` & `b`), the rule logic was previously:
1. let `prevArgToken` be the _first_ token of `a`
2. let `currentArgToken` be the _first_ token of `b`
3. compare …
=> Update: false positives in function-call-argument-newline (fixes #12123)

package.json
Update dependency
Update `globals` dependency to v12.1.0 Here are the [changes](https://github.com/sindresorhus/globals/compare/v11.7.0...v12.1.0)
Most notably for me is the addition of globals to …
=> update globals to v12.1.0

docs/rules/no-underscore-dangle.md, lib/rules/no-underscore-dangle.js, tests/lib/rules/no-underscore-dangle.js
Implemented a new option for `no_underscore_dangle` rule
See rationale in issue.
=> New: allowAfterThisConstructor for no-underscore-dangle (fixes #11488)

docs/rules/no-inline-comments.md, lib/rules/no-inline-comments.js, tests/lib/rules/no-inline-comments.js
[X] Changes an existing rule #11270
Marked as 'Update' although this change produces fewer warnings by default, because it wasn't a bug.
no-inline-comments
fewer
```js
/*eslint no-inline-comments: "error"*/
var foo = (
<div>
{/* These braces are just for this comment and there is nothing else on this line */}
<h1>Some heading</h1>
</div>
)
var quux = (
<div>
{/*
Multiline
comment
*/}
<h1>Some heading</h1>
</div>
)
```
**What does the rule …
=> Update: Allow JSX exception in no-inline-comments (fixes #11270)

docs/rules/prefer-exponentiation-operator.md, lib/rules/index.js, lib/rules/prefer-exponentiation-operator.js, tests/lib/rules/prefer-exponentiation-operator.js, tools/rule-types.json
[X] New rule #10482
```js
/*eslint prefer-exponentiation-operator: "error"*/
const foo = Math.pow(2, 8);
const bar = Math.pow(a, b);
let baz = Math.pow(a + b, c + d);
let quux = Math.pow(-1, n);
```
Examples of **correct** code for this rule:
```js
/*eslint prefer-exponentiation-operator: "error"*/
const foo = 2 ** 8;
const bar = a ** b;
let baz = (a + b) ** (c + d);
let quux = (-1) ** n;
```
New `prefer-exponentiation-operator` rule with the autofix.
* The category should be `"Stylistic Issues"`?
* Should the autofix add spaces around `**`?
=> New: Add prefer-exponentiation-operator rule (fixes #10482)

docs/rules/no-invalid-this.md, lib/rules/no-invalid-this.js, lib/rules/utils/ast-utils.js, tests/lib/rules/no-invalid-this.js
[X] Changes an existing rule #12271
`no-invalid-this`
More if the option is set to `false` (default is `true`).
New option.
```js
/*eslint no-invalid-this: ["error", { "capIsConstructor": false }]*/
"use strict";
function Foo() {
this.a = 0;
}
var bar = function Foo() {
this.a = 0;
}
var Bar = function() {
this.a = 0;
};
Baz = function() {
this.a = 0;
};
```
No errors.
4 …
=> Update: Add capIsConstructor option to no-invalid-this (fixes #12271)

lib/rules/space-infix-ops.js, tests/lib/rules/space-infix-ops.js
Make `space-infix-ops` report end location.
```js
const a = p&&q
//         ~   before
//         ~~  after
```
No
=> Update: improve report location for space-infix-ops

lib/rules/no-cond-assign.js, tests/lib/rules/no-cond-assign.js
[X] Bug fix
This bug fix can produce only fewer warnings.
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWNvbmQtYXNzaWduOiBbXCJlcnJvclwiLCBcImFsd2F5c1wiXSAqL1xuXG5zd2l0Y2ggKGZvbykge1xuICAgIGNhc2UgYSA9IGI6IFxuICAgICAgICBicmVhaztcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZW …
=> Fix: no-cond-assign with `always` option reports switch case clauses

lib/rules/curly.js, tests/lib/rules/curly.js
[x] Bug fix
Fixes #12370.
I made the `isOneLiner` function use the last token excluding the semicolon instead of just the last token, like the `isCollapsedOneLiner` function, which stopped multi-or-nest flagging code like the following as one line.
```js
console.log('foo')
;
```
No.
=> Update: curly multi-or-nest flagging semis on next line (fixes #12370)

lib/rules/prefer-const.js, tests/lib/rules/prefer-const.js
=> Fix: unexpected autofix in prefer-const (fixes #12514)

lib/rules/curly.js, tests/lib/rules/curly.js
[X] Bug fix #11908
* **ESLint Version:**  6.6.0
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGN1cmx5OiBbXCJlcnJvclwiLCBcIm11bHRpXCJdICovXG5cbmlmIChmb28pIHtcblx0Y29uc3QgYSA9IDE7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzI …
=> Fix: curly `multi` reports single lexical declarations (fixes #11908)

docs/rules/keyword-spacing.md
Documentation update
Added notice about `function` keyword to reduce confusion.
=> Docs: add notice about `function` keyword in keyword-spacing

lib/source-code/source-code.js, tests/lib/source-code/source-code.js
I noticed that `sourceCode#isSpaceBetweenTokens()` assumes that the given arguments are tokens and that they are adjacent, but there is nothing stopping a consumer from using non-adjacent tokens as …
=> Fix: sourceCode#isSpaceBetweenTokens() checks non-adjacent tokens

package.json
Add the new `funding` field to `package.json`. See:
* https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md
* https://medium.com/npm-inc/npm-weekly-222-announcing-lots-of-launches-2de4bd670340 …
=> Chore: Add funding field to package.json

docs/user-guide/getting-started.md
Updated the Getting Started Guide by:
1. Removing the video (very old at this point)
2. Added mention of how to install ESLint via Yarn
3. Added instructions on how to use `npx` to run ESLint instead …
=> Docs: Clean up Getting Started Guide

docs/rules/camelcase.md, lib/rules/camelcase.js, tests/lib/rules/camelcase.js
Changes an existing rule
Added a new option `ignoreImports` to rule `camelcase`. The option is `false` by default.
Also, this PR is with some refactorings.
Fixes #12527 .
=> New: add option for camelcase (fixes #12527)

docs/developer-guide/working-with-rules.md, lib/source-code/source-code.js, tests/lib/source-code/source-code.js
Please evaluate just the last commit. We should wait to merge this until after we land https://github.com/eslint/eslint/pull/12491. I'll rebase at that time. Adding the "do not merge" label until then. …
=> Update: deprecate sourceCode#isSpaceBetweenTokens()

lib/rules/function-call-argument-newline.js, tests/lib/rules/function-call-argument-newline.js
This is a PR for #12454
- Add checking whether there is a line comment(`// comment`) before currentArgToken
=> Fix: invalid autofix in function-call-argument-newline (fixes #12454)

docs/rules/no-setter-return.md, lib/rules/index.js, lib/rules/no-setter-return.js, tests/lib/rules/no-setter-return.js, tools/rule-types.json
[X] New rule #12285
```js
/*eslint no-setter-return: "error"*/
var foo = {
set a(value) {
this.val = value;
return value;
}
};
class Foo {
set a(value) {
this.val = value * 2;
return this.val;
}
}
const Bar = class {
static set a(value) {
if (value < 0) {
this.val = 0;
return 0;
}
this.val = value;
}
};
Object.defineProperty(foo, "bar", {
set(value) {
if (value < 0) {
return false;
}
this.val = value;
}
});
```
Examples of **correct** code for this rule:
```js
/*eslint no-setter-return: "error"*/
var foo = {
set a(value) {
this.val = value;
}
};
class Foo {
set a(value) {
this.val = value * 2;
}
}
const Bar = class {
static set a(value) {
if (value < 0) {
this.val = 0; …
```
=> New: Add no-setter-return rule (fixes #12285)

lib/init/config-initializer.js
This add the recommended config for eslint-plugin-react when using `eslint --init`
doc: https://github.com/yannickcr/eslint-plugin-react#configuration
Without it, eslint detects React components and other stuff as unused vars, while they are used in jsx tags
=> Update: add react plugin config for eslint init

lib/init/config-initializer.js, tools/eslint-fuzzer.js
When initializing new eslint project and coming to style guide step, visual studio code terminal doesn't properly format style guide links so when user clicks on one of the links (in the terminal) it takes them to e.q `https://github.com/airbnb/javascript)` (note the `)` at the end) 
Putting spaces after the opening brace and before the closing brace fixes this issue.
No
=> Chore: Format style guide links so they can be clicked

.github/FUNDING.yml
I added the @eslint organization to `FUNDING.yml` so that the "Sponsor" button on the [eslint/eslint](https://github.com/eslint/eslint) repository shows GitHub Sponsors as an option in addition to …
=> Chore: Add GitHub organization to Sponsor button

docs/rules/camelcase.md
Additional description and some common use cases for `ignoreDestructuring` option in `camelcase` docs.
=> Docs: clarify ignoreDestructuring option in the camelcase rule

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
Count properties on a line as a single line.
I think this PR can fix #11414 
=> Update: fix uglified align in key-spacing (fixes #11414)

lib/rules/spaced-comment.js, tests/lib/rules/spaced-comment.js
[X] Bug fix #12036
If the whole comment is equal to any of the specified markers, that comment will be ignored by this rule.
This applies to both line comments and block comments.
This indirectly allows `/***/` and `//*` (`"*"` is always a marker).
=> Fix: ignore marker-only comments in spaced-comment (fixes #12036)

lib/rules/object-curly-spacing.js, tests/lib/rules/object-curly-spacing.js
Change `object-curly-spacing` report locations.
* For missing spaces, the difference is small, the rule will now report complete `loc` of the curly braces instead of just `loc.start.`
* For disallowed spaces,  the rule will now report the location of spaces (the range that should be removed) instead of the location of curly braces. like this:
Since this doesn't change the start line, it produces neither more nor fewer warnings, even in the case of `eslint-disable-*` comments.
I guess this could be accepted as a bug fix?
=> Fix: improve report location for object-curly-spacing

lib/rules/require-await.js, tests/fixtures/parsers/typescript-parsers/global-await.js, tests/fixtures/parsers/typescript-parsers/global-for-await-of.js, tests/lib/rules/require-await.js
`@typescript-eslint/parser` allows global `awaits`.
This currently rule assumes that is not allowed, because espree throws a parsing error on it.
This PR just stops the rule from crashing on global await statements.
Related: https://github.com/typescript-eslint/typescript-eslint/issues/1077
=> Fix: require-await crash on global await

docs/developer-guide/contributing/pull-requests.md
=> Docs: Change "Code Conventions" link in pull-requests.md

lib/rules/comma-dangle.js, lib/rules/semi.js, lib/rules/utils/ast-utils.js, tests/lib/rules/comma-dangle.js, tests/lib/rules/semi.js, tests/lib/rules/utils/ast-utils.js
Change the report location for semi and comma-dangle. Fixes part of #12334 .
```js
/* eslint semi: [2, 'always'] */
const a = Math.random
//             ~~~~~~    vscode highlight ⁠— before
//                   ~   vscode highlight ⁠— after
/* eslint comma-dangle: [2, 'always-multiline'] */
[
Math.random
]
//     ~~~~~~    vscode highlight ⁠— before
//           ~   vscode highlight ⁠— after
```
When reporting the location for a linefeed, there is two reasonable way to do so, the first is to report `{start: {line: m, column: n}, end: {line: m, column: n+1}}`. This approach does not …
=> Update: improve location for semi and comma-dangle

docs/rules/no-dupe-else-if.md, lib/rules/index.js, lib/rules/no-dupe-else-if.js, tests/lib/rules/no-dupe-else-if.js, tools/rule-types.json
[X] New rule #12469
```js
/*eslint no-dupe-else-if: "error"*/
if (isSomething(x)) {
foo();
} else if (isSomething(x)) {
bar();
}
if (a) {
foo();
} else if (b) {
bar();
} else if (c && d) {
baz();
} else if (c && d) {
quux();
} else {
quuux();
}
if (n === 1) {
foo();
} else if (n === 2) {
bar();
} else if (n === 3) {
baz();
} else if (n === 2) {
quux();
} else if (n === 5) {
quuux();
}
```
New rule `no-dupe-else-if`
=> New: Add no-dupe-else-if rule (fixes #12469)

lib/rules/multiline-comment-style.js, tests/lib/rules/multiline-comment-style.js
fixes #12312
~~This PR preserves leading whitespace when converting a block comment to a "starred" block comment in the `multiline-comment-style` rule's autofixer. Since this rule doesn't know about …
=> Fix: preserve whitespace in multiline-comment-style (fixes #12312)

docs/user-guide/integrations.md
Updated the bundles available for Textmate 2.
Nothing other than I ordered the Textmate 2 bundles by last release date.
=> Docs: Added another Textmate 2 bundle.

docs/rules/no-constructor-return.md, lib/rules/index.js, lib/rules/no-constructor-return.js, tests/lib/rules/no-constructor-return.js, tools/rule-types.json
New rule
Added new rule: no-constructor-return
Are there anything should be polished at the documentation?
Are there more cases to be handled?
=> New: new rule no-constructor-return (fixes #12481)

docs/rules/no-useless-computed-key.md, lib/rules/no-useless-computed-key.js, tests/lib/rules/no-useless-computed-key.js
Fixes #12041.
- Added a new `enforceForClassMembers` option to the schema
- Extracted `Property` visitor to a `check` function
- Added a `MethodDefinition` visitor that is `check` if option is …
=> Update: Add enforceForClassMembers option to no-useless-computed-key

lib/rules/computed-property-spacing.js, tests/lib/rules/computed-property-spacing.js
=> Fix: invalid token checking in computed-property-spacing (fixes #12198)

lib/rules/operator-assignment.js, tests/lib/rules/operator-assignment.js
[X] Bug fix
I believe this is a bug fix, but it produces **more** warnings.
This PR fixes two things in the `operator-assignment` rule:
* The default `always` option was ignoring `this` member expressions, such as `this.x = this.x + y`.
* The `never` option was reporting `this` member expressions, but didn't auto-fix in some cases where it seems to be safe, such as `this.x += y`.
`operator-assignment`
more
```js
/* …
```
=> Update: Check member expressions with `this` in operator-assignment

lib/rules/indent.js, tests/lib/rules/indent.js
Fixes #12574
Add code to the `indent` rule to specifically handle `JSXSpreadAttribute` nodes.
=> Fix: indent rule with JSX spread props

docs/developer-guide/nodejs-api.md, docs/developer-guide/unit-tests.md, docs/developer-guide/working-with-rules.md, lib/linter/report-translator.js, lib/rule-tester/rule-tester.js, lib/rules/no-useless-escape.js, lib/shared/types.js, tests/fixtures/testers/rule-tester/suggestions.js, tests/lib/linter/linter.js, tests/lib/linter/report-translator.js, tests/lib/rule-tester/rule-tester.js, tests/lib/rules/no-useless-escape.js
1. This PR implements the proposal for a new suggestions API [described in this rfc](https://github.com/eslint/rfcs/pull/30). This API will allow other tools, such as editors, to provide fixes for …
=> New: Add suggestions API

docs/rules/no-implicit-globals.md, lib/rules/no-implicit-globals.js, tests/lib/rules/no-implicit-globals.js
[X] Changes an existing rule 
Two changes based on #11981
-----------------------------------------------------------------------------
-- New option --
no-implicit-globals
Same by default, more if the option is set.
New option.
```js
/*eslint no-implicit-globals: "error"*/
const a = 1;
let b;
class C {}
```
No warnings.
```js
/*eslint no-implicit-globals: ["error", …
```
=> Update: Add 'lexicalBindings' to no-implicit-globals and change messages

docs/rules/grouped-accessor-pairs.md, lib/rules/grouped-accessor-pairs.js, lib/rules/index.js, tests/lib/rules/grouped-accessor-pairs.js, tools/rule-types.json
[X] New rule #12277
Checks object literals, class declarations and class expressions.
If a property has a getter and a setter, their definitions should be one right after the other.
Optionally, the rule can also enforce consistent order (`getBeforeSet` or `setBeforeGet`).
[X] Enforces code style
**Provide 2-3 code examples that this rule will warn about:**
```js
/*eslint grouped-accessor-pairs: "error"*/
var foo = {
get a() {
return this.val;
},
b: 1,
set a(value) {
this.val = value;
}
};
class Foo {
set a(value) {
this.val = value;
}
b(){}
get a() {
return this.val;
}
}
```
```js
/*eslint …
```
=> New: Add grouped-accessor-pairs rule (fixes #12277)

lib/rules/no-unexpected-multiline.js, tests/fixtures/parsers/typescript-parsers/tagged-template-with-generic/tagged-template-with-generic-1.js, tests/fixtures/parsers/typescript-parsers/tagged-template-with-generic/tagged-template-with-generic-2.js, tests/fixtures/parsers/typescript-parsers/tagged-template-with-generic/tagged-template-with-generic-3.js, tests/fixtures/parsers/typescript-parsers/tagged-template-with-generic/tagged-template-with-generic-and-comment.js, tests/lib/rules/no-unexpected-multiline.js
https://github.com/eslint/eslint/issues/11650
Adds support for multiline tagged template expressions with generics (typescript only)
```ts
tag<
generic
>`string`
```
I thought that because this change was so simple, and it is a no-op for non-ts code, it might be a good fit to fix upstream instead of creating a new rule in the typescript plugin.
Don't be afraid to reject if you don't think it fits.
=> Fix: Add support for tagged template literal generics in no-unexpected-multiline

docs/developer-guide/working-with-rules.md
refs #12606 (first item only)
Added a section in `working-with-rules` to clarify that suggestion message with placeholders should have its own `data`.
=> Docs: Clarify suggestion's data in Working with Rules (refs #12606)

lib/cli-engine/file-enumerator.js, tests/lib/cli-engine/cli-engine.js, tests/lib/cli-engine/file-enumerator.js
[X] Bug fix: #12604 
This PR fixes #12604 as unignoring the entry directory.
Previously, the `eslint dir` command had checked if the directly given directory (`dir`) is ignored by `.eslintignore` or not. By #12274, the ignore check has gotten to load config files from the directory that the `dir` exists in order to check `ignorePatterns` property. As a result, the `eslint .` command has gotten to try loading config files from `../`. Then if config files were not found from `../` and ancestors, ESLint loads personal config file.
I think that it's not intuitive if the `eslint .` command checks the ignore of `.`, so this PR changes that behavior. If `eslint dir` is …
=> Fix: don't ignore the entry directory (fixes #12604)

lib/source-code/source-code.js, tests/lib/source-code/source-code.js
[X] Bug fix: #12614 
This PR changes `isSpaceBetweenTokens()` method to recognize spaces in `JSXText` tokens in order to fix #12614. The `JSXText` tokens include whitespaces such as indentation.
- Is this direction right?
=> Fix: isSpaceBetweenTokens() recognizes spaces in JSXText (fixes #12614)

conf/eslint-recommended.js, lib/rules/require-atomic-updates.js
refs https://github.com/eslint/eslint/issues/11899#issuecomment-541714523
The TSC made a determination to remove `require-atomic-updates` from `eslint:recommended`, but it looks like we didn't end up …
=>  Update: do not recommend require-atomic-updates (refs #11899) 

tests/lib/rules/comma-dangle.js
[x] Other, please explain: Add test cases in comma-dangle
Added test cases for covering this branch(screenshot). This PR increases test coverage for comma-dangle.
=> Chore: Add tests to cover empty object options in comma-dangle

docs/rules/no-restricted-imports.md
[X] Documentation update #11717
The following example from the `no-restricted-imports` documentation is an incorrect configuration:
```json
"no-restricted-imports": ["error", [{
"name": "import-foo",
"message": "Please use import-bar instead."
}]]
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwibm8tcmVzdHJpY3RlZC1pbXBvcnRzXCI6IFtcImVycm9yXCIsIFt7XG4gIFwibmFtZVwiOiBcImltcG9ydC1mb29cIixcbiAgXCJtZXNzYWdlXCI6IFwiUGxlYXNlIHVzZSBpbXBvcnQtYmFyIGluc3RlYWQuXCJcbn1dXSAqLyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)
Configuration should be either flat `["error", {}, {}, ...]` or `["error", { paths: …
=> Docs: Fix configuration example in no-restricted-imports (fixes #11717)

docs/developer-guide/working-with-rules.md
fixes https://github.com/eslint/website/issues/661
Due to the fact that the interpolation delimiters in the new suggestions feature match those in Liquid, the `{{ }}` tags here end up not rendering …
=> Docs: wrap {{}} in raw liquid tags to prevent interpolation

Makefile.js, docs/rules/comma-style.md, docs/rules/no-multi-spaces.md, docs/rules/no-restricted-syntax.md, webpack.config.js
In addition to the documentation update, this PR also removes the bundling of espree, since it's only used for the parser demo. 
refs https://github.com/eslint/website/issues/652
Following up on …
=> Chore: remove references to parser demo

lib/cli-engine/lint-result-cache.js, tests/lib/cli-engine/lint-result-cache.js
Add node version to the key used in cache.
the result from the linting is possible to be different (some rules may fail) when the node is upgraded or downgraded. …
=> New: Include node version in cache

docs/rules/brace-style.md, tests/lib/rules/brace-style.js
add documentation and tests demonstrating iffy edge cases
[x ] Other, please explain:  Additional tests
Added tests and documentation for 1tbs with allowSingleLine …
=> Docs: 1tbs with allowSingleLine edge cases (refs #12284)

Makefile.js
Chore
Now that https://github.com/eslint/website/pull/665 has landed, we can remove the bundling step in our release script. We should keep the bundling step for our Karma browser tests to ensure …
=> Chore: remove bundling of ESLint during release

docs/user-guide/configuring.md, lib/cli-engine/config-array-factory.js, tests/fixtures/config-file/cjs/.eslintrc.cjs, tests/lib/cli-engine/config-array-factory.js
In ES module packages w/ "type": "module" defined treat all .js files as ES modules. Since `eslint` is expecting the config in CommonJS format, it needs to be named w/ a `.cjs` extension.
For details about the issue, see #12319.
For details about …
=> Update: support .eslintrc.cjs (refs eslint/rfcs#43)

conf/config-schema.js, tests/lib/shared/config-validator.js
Allowed the usage of `$schema` in the configuration. This key is useful for some IDEs to find information about the schema of the JSON 🤷‍♂  …
=> Update: Allow $schema in config

lib/linter/config-comment-parser.js
A chore to avoid an error that occurs while bundling linter for the online demo.
[regjsparser](https://github.com/jviereck/regjsparser) treats escaped `-` in character classes in a regex with the `u` flag as invalid syntax.
E.g., `/[\-]/u`
ref: jviereck/regjsparser#98
Modified one regex in `linter/config-comment-parser.js` to avoid escaping `-`.
Are the new and the old regexes equivalent.
=> Chore: refactor regex in config comment parser

docs/rules/no-console.md
Added spaces before comment markers /* */, not having the spaces was throwing another eslint error :) 
=> Docs: Add spacing in comments for no-console rules

docs/rules/func-style.md
**Documentation update**
With the `allowArrowFunction` parameter, it was not clear at the first read that arrow function expression was include in the default option. I think adding this example will make it more clear
=> Add example for func-style 

lib/rules/prefer-numeric-literals.js, tests/lib/rules/prefer-numeric-literals.js
[X] Bug fix
This PR can produce only fewer warnings in `prefer-numeric-literals`.
From the documentation:
> This rule disallows calls to parseInt() or Number.parseInt() if called with two arguments: a string; and a radix option of 2 (binary), 8 (octal), or 16 (hexadecimal).
This PR fixes the following:
1. The rule didn't check the type of the first literal argument.
It did check if it's a `Literal`. Now it also checks if it's a `string` literal.
This probably didn't cause some notable problems, but it isn't by the spec (which is explicit about the first argument), and it might be unwanted in some cases.
```js
/* eslint prefer-numeric-literals: error */
parseInt(1e8, 2); // fixed to 0b100000000;
```
[Demo …
=> Fix: prefer-numeric-literals doesn't check types of literal arguments

lib/rules/array-bracket-spacing.js, tests/lib/rules/array-bracket-spacing.js
Changes `array-bracket-spacing` report locations.
* For missing spaces, the difference is small, the rule will now report complete `loc` of the brackets instead of just `loc.start.`
* For disallowed spaces,  the rule will now report the location of spaces (the range that should be removed) instead of the location of the brackets. like this:
Since this doesn't change the start line, it produces neither more nor fewer warnings, even in the case of `eslint-disable-*` comments.
I guess this could be accepted as a bug fix
=> Fix: improve report location for array-bracket-spacing

lib/rules/no-restricted-imports.js, tests/lib/rules/no-restricted-imports.js
[X] Bug fix 
At the moment, `no-restricted-imports` schema allows multiple objects with `paths`/`patterns` keys:
```js
/* eslint "no-restricted-imports": ["error", {
"paths": ["foo"]
}, {
"paths": ["bar"]
}] */
import a from "bar"; // no errors
```
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwibm8tcmVzdHJpY3RlZC1pbXBvcnRzXCI6IFtcImVycm9yXCIsIHtcbiAgICBcInBhdGhzXCI6IFtcImZvb1wiXVxufSwge1xuICAgIFwicGF0aHNcIjogW1wiYmFyXCJdXG59XSAqL1xuXG5pbXBvcnQgYSBmcm9tIFwiYmFyXCI7IC8vIG5vIGVycm9ycyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)
This shouldn't be allowed because it isn't …
=> Fix: no-restricted-imports schema allows multiple paths/patterns objects

lib/rules/no-multiple-empty-lines.js, tests/lib/rules/no-multiple-empty-lines.js
The `+ 1` was from a time where we warned about anything with more than one empty line, but since then the rule has become configurable. We should put the warning on the first line that breaks this rule, instead of on the first empty line.
**What …
=> no-multiple-empty-lines: Adjust reported `loc`

docs/rules/no-multi-assign.md
Update `no-multi-assign` rule documentation:
- Update description to explain "unexpected results"
I believe the updated snippet offers a better explanation of why this rule should be used than the …
=> Docs: Update no-multi-assign explanation

lib/rules/no-unsafe-negation.js, tests/lib/rules/no-unsafe-negation.js
[X] Changes an existing rule #12591
Suggestions for the `no-unsafe-negation` rule.
Example:
```js
code: "!a in b",
errors: [{
message: "Unexpected negating the left operand of 'in' operator.",
suggestions: [
{
desc: "Negate 'in' expression instead of its left operand. This changes the current behavior.",
output: "!(a in b)"
},
{
desc: "Wrap negation in '()' to make the intention explicit. This preserves the current behavior.",
output: "(!a) in b"
}
}]
```
Messages
=> Update: Add suggestions for no-unsafe-negation (fixes #12591)

lib/rule-tester/rule-tester.js, tests/lib/rule-tester/rule-tester.js
Previously you had to explicitly set `suggestions: undefined`, or omit the property.
I hate writing `undefined` in my code, but I also prefer to be explicit in my tests, and explicitly say "I expect no suggestions".
This just lets a user pass any falsey value, or an empty array.
The rule tester will interpret any of these values as "I expect no suggestions".
I.e. these will now be equivalent:
```js
ruleTester.run("suggestions-basic", rule, {
valid: [],
invalid: [
// previously only allowed:
{},
{
suggestions: undefined,
},
// now also allows
{
suggestions: [],
},
{
suggestions: null,
},
{
suggestions: false,
},
],
});
```
=> Update: improve suggestion testing experience

packages/eslint-config-eslint/default.yml
this is a breaking change in eslint-config-eslint.
=> Chore: enable prefer-regex-literals in eslint codebase

lib/rules/lines-between-class-members.js, tests/lib/rules/lines-between-class-members.js
This PR will fix three bugs in `lines-between-class-members`.
1. #12391
2. doesn't work well with `semicolons`. 
* the actual master version.
```js
/* eslint lines-between-class-members: ["error", …
```
=> Update: autofix bug in lines-between-class-members (fixes #12391)

tests/lib/rules/yield-star-spacing.js
Added test cases for covering this branch(screenshot) in `yield-star-spacing.js`.
This PR increases test coverage for yield-star-spacing
* Test coverage -  `yield-star-spacing.js`
|       | master | PR |
-- | -- | -- | 
Statements | 96.55% | 100%  | …
=> Chore: add object option test cases in yield-star-spacing

lib/rules/key-spacing.js, tests/lib/rules/key-spacing.js
fix #11414 
make it ignore aligning single line properties.
=> Fix: ignore aligning single line in key-spacing (fixes #11414)

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
Adds `offsetTernaryExpressions` boolean indent rule that solves following issues:
- https://github.com/eslint/eslint/issues/6606
- https://github.com/eslint/eslint/issues/7698
- https://github.com/standard/standard/issues/927
- https://github.com/standard/standard/issues/1451
- https://github.com/sheerun/prettier-standard/issues/76
- https://github.com/brodybits/prettierx/issues/41
Functions are normally formatted with indentation which looks nice:
```es6
commission => {
return suggestions.hits.map(hit => something(hit))
}
```
but when ternary expression is used suddenly `return` is at the same level as argument:
```es6
search.premium
? commission => {
return suggestions.hits.map(hit => …
```
=> New: Add offsetTernaryExpressions option for indent rule

docs/rules/no-void.md, lib/rules/no-void.js, tests/lib/rules/no-void.js
Changes an existing rule
`no-void`
Fewer, when the option is turned on
New option
Code that will now be valid, when the option is turned on:
```js
/*eslint no-void: ["error", { "allowAsStatement": true }]*/
void foo;
void someFunction();
```
Errors for all `void` operator usage, regardless of context
When the option is on, it will allow the `void` when used as a statement.
**Why?**
A common usage …
=> Update: no-void add an option to allow void as a statement

lib/rules/no-mixed-spaces-and-tabs.js, tests/lib/rules/no-mixed-spaces-and-tabs.js
[X] Bug fix
* **ESLint Version:**  6.6.0
default
<details>
```js
}
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLW1peGVkLXNwYWNlcy1hbmQtdGFiczogZXJyb3IgKi9cblxuJ1xcXG5cdCAnIC8vIHRhYiBhbmQgc3BhY2UgYXQgdGhlIGJlZ2lubmluZyBvZiB0aGlzIGxpbmUiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY …
=> Fix: no-mixed-spaces-and-tabs reports multiline strings

docs/rules/no-restricted-exports.md, lib/rules/index.js, lib/rules/no-restricted-exports.js, tests/lib/rules/no-restricted-exports.js, tools/rule-types.json
[X] New rule #10428
```js
/*eslint no-restricted-exports: ["error", ["foo", "bar", "Baz", "a", "b", "c", "d"]]*/
export const foo = 1;
export function bar() {}
export class Baz {}
const a = {};
export { a };
function someFunction() {}
export { someFunction as b };
export { c } from 'some_module';
export { something as d } from 'some_module';
```
New rule `no-restricted-exports`
* configuration
Configuration is `["error", ["foo", "bar"]]` instead of `["error", "foo", "bar"]`
This might be a better choice as it's clear that `"error"` isn't a restricted name, but it's …
=> New: Add no-restricted-exports rule (fixes #10428)

lib/cli-engine/formatters/junit.js, tests/lib/cli-engine/formatters/junit.js
This commit aims to fix the issues described in #12507 by removing the
assumption that POSIX style filePaths are supplied by messages.
The tests for this are also updated to run on both Windows and POSIX
based systems. The results can be seen by running ESLint with the JUnit
formatter on a Windows system.
Full details can be seen in the issue mentioned above.
This PR is a followup to fix a missed bug introduced in #11683 where Windows paths are not supported properly.
[ ] Changes an …
=> Fix: Windows path parsing for JUnit (fixes #12507)

Makefile.js, webpack.config.js
[X] Other, please explain: update the webpack configuration of browser tests and the online demo.
This PR update our webpack configuration to not use `regjsparser` package as a follow up of #12662. 
After this change, `@babel/preset-env` prints below:
```
Using targets:
{
"chrome": "76",
"edge": "18",
"firefox": "69",
"ios": "12.2",
"safari": "12.1",
"samsung": "10.1"
}
Using modules transform: auto
Using plugins:
transform-template-literals { "ios":"12.2", "safari":"12.1" }
transform-function-name { "edge":"18" }
transform-dotall-regex { "edge":"18", "firefox":"69" }
proposal-async-generator-functions { "edge":"18" }
proposal-object-rest-spread { "edge":"18" } …
```
=> Build: update browser build

lib/rules/max-lines-per-function.js
remove unused code in max-lines-per-function.
https://github.com/eslint/eslint/blob/8108f49f9fa0c2de80b3b66c847551beff585951/lib/rules/max-lines-per-function.js#L57-L59
Because the return value …
=> Chore: remove unused code in max-lines-per-function

lib/rules/utils/ast-utils.js, tests/lib/rules/no-dupe-keys.js, tests/lib/rules/no-restricted-properties.js, tests/lib/rules/no-self-assign.js, tests/lib/rules/sort-keys.js, tests/lib/rules/utils/ast-utils.js, tests/lib/rules/yoda.js
[X] Bug fix
* **Node Version:** 8.16.0
* **npm Version:** 6.4.1
default
<details>
```js
ecmaVersion: 2018,
},
};
```
</details>
This bug is observable in environments that don't support ES2018 regexp syntax, namely Node 8. 
For the online demo use Firefox (current Firefox version is 68, still doesn't support this syntax), results are different when compared to Chrome.
This bug affects 5 rules: …
=> Update: Handle locally unsupported regex in computed property keys

lib/rule-tester/rule-tester.js
Improve JSDoc typings.
Add type for valid and invalid RuleTester test cases. This addition enables editor autocomplete/suggestions.
The typings are copied from `@types/eslint`.
No
=> Chore: add JSDoc types for RuleTester test cases

tests/lib/rules/one-var.js
Some tests for the `separateRequires` option of the `one-var` rule had this:
```js
parserOptions: { env: { node: true } }
```
These are incorrect settings because `env` shouldn't be in `parserOptions`. It's just ignored as an unknown parser option.
Since the tests are passing without the `node` environment being actually set, I wasn't sure if the rule was working as intended. In particular, should the option apply to _global_ `require` or any `require` call.
By #9441, in particular [this thread](https://github.com/eslint/eslint/pull/9441#pullrequestreview-76335806) and [this comment](https://github.com/eslint/eslint/pull/9441#discussion_r15859 …
=> Chore: fix separateRequires tests for one-var rule

docs/rules/indent.md, lib/rules/indent.js, tests/lib/rules/indent.js
fixes #11377 
This PR adds the ability to set the `outerIIFEBody`  to `"off"`. This was a lot easier than I expected - the logic already allows for this, so I just needed to add the option to the …
=> Update: add outerIIFEBody: "off" to indent rule (fixes #11377)

lib/rules/max-len.js, tests/lib/rules/max-len.js
This pr will fix #12213.
If the comment is in the single line jsx comment, change the comment node for checking with JSXExpressionContainer. 
ex)
```jsx
<>
{/* comment */}
</>
``` …
=> Update: fix counting jsx comment len in max-len (fixes #12213)

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
[X] Bug fix
This bug fix produces **more** warnings.
* **ESLint Version:** v6.8.0
default
<details>
```js
},
};
```
</details>
[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogXCJlcnJvclwiICovXG5cbihhKCkuYikoKTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319 …
=> Update: fix no-extra-parens CallExpression#callee false negatives

docs/rules/no-useless-backreference.md, lib/rules/index.js, lib/rules/no-useless-backreference.js, tests/lib/rules/no-useless-backreference.js, tools/rule-types.json
[ X] New rule #12673
```js
/*eslint no-useless-backreference: "error"*/
/^(?:(a)|\1b)$/; // reference to (a) into another alternative
/^(?:(a)|b(?:c|\1))$/; // reference to (a) into another alternative
/^(?:a|b(?:(c)|\1))$/; // reference to (c) into another alternative
/\1(a)/; // forward reference to (a)
RegExp('(a)\\2(b)'); // forward reference to (b)
/(?:a)(b)\2(c)/; // forward reference to (c)
/\k<foo>(?<foo>a)/; // forward reference to (?<foo>a)
/(?<=(a)\1)b/; // backward reference to (a) from within the same lookbehind
/(?<!(a)\1)b/; // backward reference to (a) from within the same lookbehind
new RegExp('(\\1)'); // nested reference to (\1)
/^((a)\1)$/; // nested …
```
=> New: Add no-useless-backreference rule (fixes #12673)

lib/rules/no-extra-parens.js, tests/lib/rules/no-extra-parens.js
Fix #12127 
I tried to solve issue #12127 by adding just `|| hasDoubleExcessParens()` everywhere, but it had a performance issue when checking `ArrayExpression`'s element nodes.
So, I made a new function(`hasExcessParensWithConsiderPrecedence`) which checks extra parens with considering the precedence of a node. This function checks `isParenthesisedTwice` only if the node surrounded by at least one extra paren. 
This pr doesn't change the option's behavior that @mdjermanovic …
=> Update: report double extra parens in no-extra-parens (fixes #12127)

lib/rules/no-restricted-imports.js, tests/lib/rules/no-restricted-imports.js
[X] Bug fix (it should fix #12282)
Now rule can produce multiple errors depends on `importNames` option. This change allows applying directive comments on each item imported from the module.
Yes, the test cases since i'm too bad at it.
=> Update: fix no-restricted-imports importNames reporting (fixes #12282)

lib/rule-tester/rule-tester.js, tests/lib/rule-tester/rule-tester.js
#12031 introduced an invalid regex, which caused the `|` character to be displayed as `\u007c` in test output.
This ofc ruins any output with an OR (`||` / `|`). I finally got annoyed enough to look into a fix.
This just fixes the output and adds a test to make sure it doesn't happen again.
=> Fix: Display pipe character correctly in test output
